### ISSUE TITLE
Need help producing a `PSO.Molecule.Structure` (confused by `...state.data.select`) to initiate Volume Streaming.

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#1000]
I'm following the [`proteopedia-wrapper`](https://github.com/molstar/molstar/blob/6edbae80db340134341631f669eec86543a0f1a8/src/examples/proteopedia-wrapper/index.ts#L322-L331) example and my goal is  having the following control over the volume streaming utility:
 1. streaming a density map for the currently uploaded structure 
 2. streaming density maps for multiple structures 
 3. streaming density for a subchain of a structure (i'm not sure if PDB/RCSB provide those, hence 4)
 4. streaming density from a custom server (i'll serve the maps experimental maps)
 

<details>

  <summary>(For reference) The `proteopedia-wrapper` `experimentalData.init` function(`index.ts`): </summary>

```typescript
//index.ts
...
            const asm = this.state.select(StateElements.Assembly)[0].obj!;
            const params = InitVolumeStreaming.createDefaultParams(asm, this.plugin);
            params.options.behaviorRef = StateElements.VolumeStreaming;
            params.defaultView = 'box';
            params.options.channelParams['fo-fc(+ve)'] = { wireframe: true };
            params.options.channelParams['fo-fc(-ve)'] = { wireframe: true };
            await this.plugin.runTask(this.state.applyAction(InitVolumeStreaming, params, StateElements.Assembly));
            this.experimentalDataElement = parent;
            volumeStreamingControls(this.plugin, parent);
//helpers.ts
...
export enum StateElements {
    Model = 'model',
    ModelProps = 'model-props',
    Assembly = 'assembly',

    VolumeStreaming = 'volume-streaming',

    Sequence = 'sequence',
    SequenceVisual = 'sequence-visual',
    Het = 'het',
    HetVisual = 'het-visual',
    Het3DSNFG = 'het-3dsnfg',
    Water = 'water',
    WaterVisual = 'water-visual',

    HetGroupFocus = 'het-group-focus',
    HetGroupFocusGroup = 'het-group-focus-group'
}
```
</details>

I'm currently stuck on the (1.) because i'm not quite sure how to get the the `PSO.Molecule.Structure` from the PDB model that's donwloaded into the state already. Perhaps i'm misunderstanding the example itself, but if not -- i'm still not sure how to use the `hierarchy` or uuid refs to `createDefaultParams` with the downloaded [atomic] structure to start streaming its volume. An example follows:

Here is the minimal setup i have, from the docs. I download the '3j7z' model. 
```typescript
        window.molstar = await createPluginUI(parent.current as HTMLDivElement, MySpec);
        const data           = await window.molstar.builders.data.download( { url: "https://files.rcsb.org/download/3j7z.pdb" }, { state: { isGhost: true } } );
        const trajectory     = await window.molstar.builders.structure.parseTrajectory(data, "pdb");
        await window.molstar.builders.structure.hierarchy.applyPreset( trajectory, "default" );
```

Now i tried reproducing the first line in the `proteopedia-wrapper` example above(`this.state.select(StateElements.Assembly)[0].obj!;`) :
```typescript
function getObj<T extends StateObject>(ref:string):T['data']{
        const state = window.molstar!.state.data
        const cell = state.select(ref)[0];
        if (!cell || !cell.obj) return void 0;
        return (cell.obj as T).data;
}
        const asm1  = window.molstar!.state.data.select(StateElements.Assembly)[0].obj!;
        const model    = getObj<PluginStateObject.Molecule.Model>('model');
        const assembly = getObj<PluginStateObject.Molecule.Structure>('assembly');
        const asm2      = window.molstar?.state.data.selectQ(StateSelection.Generators.ofType(PSO.Molecule.Structure).first)[0]
```
Alas, all return `undefined`. 

My question is what is the idiomatic way to produce the `PSO.Molecule.Structure` object that [`createDefaultParams`](https://github.com/molstar/molstar/blob/6edbae80db340134341631f669eec86543a0f1a8/src/examples/proteopedia-wrapper/index.ts#L324C51-L324C67) takes as arg1.

In general i'm interested whether this is the best way to achieve what i want (1-4 above); how would i generalize this approach to a subchain of, say, 3J7Z (if that is possible provided a custom server); ever wary of assymetric unit/model dichotomy -- whether selecting a `model` versus `assembly` impacts the streaming behavior?

Perhaps this is also a good place to ask for a mental model or at least a pointer for how to slice/pick `State` with selectors in general. I have read the answer in  #561 and generally appreciate the `rx`-based event model of the state, but found that i'm missing the understanding of how to(again) select things i want.  

I.e. there is `select` and `selectQ` (`Q` i think is for MolScript compiled queries?), when to use [Generators](https://github.com/molstar/molstar/blob/6edbae80db340134341631f669eec86543a0f1a8/src/mol-state/state/selection.ts#L83-L164), what's the relationship between `Loci` and `Cell` (~`StateCell` types).. 

I'd be delighted to PR the collated answer to this and the previous few issues dealing with state (https://github.com/molstar/molstar/issues/561, etc) to the molstar docs since [that section](https://molstar.org/docs/data-state/) is still sitting empty, will come back for more. Thank you

**Comment by dsehnal** [comment]
Do you still need help with this?

**Comment by rtviii** [comment]
Yeah, that'd be sweet. Thanks for following up, David.

**Comment by rtviii** [comment]
@dsehnal bump! Still here for this.

**Comment by dsehnal** [comment]
Some pointers:

- The `hierarchy.applyPreset` call will return an object with selectors. One of them (can't remember from top of my head), will correspond to the structure passed to the create params.
- An alternative to this is to build the representation hierarchy yourself, the your getObj will work because you will be able to provide specific tags/refs to the individual elements (that's how the proteopedia wrapper works)
- there the two types of selections here: one is "state object selection" (data.selectQ) and the other is the MolQL based selection to select atoms inside a structure.

**Comment by rtviii** [comment]
Thank you, David.
