### ISSUE TITLE
Forcefully updating representation theme

### ISSUE THREAD

**Issue by KrzysztofMularski** [molstar/molstar#1003]
Hello,
In my project, I am using modified version of `BasicWrapper` from examples that use custom `coloring.applyColoring()` method which is similar to `coloring.applyStripes()` but it colors different residue groups for different models in trajectory. When I upload trajectory file containing 1000 models I want `applyColoring()` to run every time the model is changed. But first issue is that, I need to "manually restart" `representationTheme`, for example by calling other representation theme and it look like this:
```js
update = async () => {
    await this.coloring.applyDefault();
    await this.coloring.applyColoring();
}
```
which is weird but it works. But now there is a issue, when I run an animation, the theme sometimes is not updating and the representation theme is the same for all models, and sometimes (when I stop animating and start it again) it updates it correctly which is: different colored residues for different models.
I am subscribing to events and the update function definitely runs. 
```js
this.subscribe(this.plugin.state.data.events.changed, this.update);
this.subscribe(this.plugin.behaviors.state.isAnimating, this.update);
```
The question is, is there a way to force update color theme? Or is there something else that I could try to make sure that the representation theme is updating correctly?

Thanks in advance!

**Comment by dsehnal** [comment]
This code was written by @arose, but adjusting the `contextHash` value based on the current trajectory snapshots in your custom theme should fix your issue.

**Comment by arose** [comment]
Something like `const contextHash = Model.TrajectoryInfo.get(ctx.structure!.models[0]).index;` should do the trick.

**Comment by KrzysztofMularski** [comment]
Thanks for the response. I found the `contextHash` option as one of the fields of `CustomColorTheme` function. Is there a way to use `contextHash` or something similar but on the basis of `StripedResidues` from `basic-wrapper/coloring.ts`? Or other way around: I just want to have an access to ids of atoms, and then apply different colors to some atoms with specific ids. I have working example, but it uses `getData(model: Model)` function from `StripedResidues` and I don't know how to translate it to `CustomColorTheme`. I believe it is inside `color: location => {...}` but I just can't get it to work.
Every hint would be very helpful!
Thanks
