### ISSUE TITLE
Scripting selection

### ISSUE THREAD

**Issue by leguilv** [molstar/molstar#1004]
Dear All,

I was wondering if there was a way to perform script-based selection ? There are various such scripting facilities in most viewers (https://wiki.pymol.org/index.php/Selection_Language_Comparison), and browsing through the code, I found some "transpilers" for pymol, VMD etc...

But I've looked around and could not find any documentation as to what is available and how to use it.

Thanks :)

**Comment by rtviii** [comment]
What do you mean by `scripting` exactly? Let's say you have `PDB:3J7Z` opened. What would you like to select? Perhaps i can help.

**Comment by rtviii** [comment]
You are right that the docs are a little scant on this, but the there are lots of facilities and indeed a whole selection language at `https://github.com/molstar/molstar/tree/master/src/mol-script` where you found the `transpilers.ts`, i guess.

Some ways to use it is:
- via compiled query (select residues with `12`<`res_id`<`200` of chain with `auth_asym_id`==`A`) :
```typescript
import { compileIdListSelection } from 'molstar/lib/mol-script/util/id-list'

  const query = compileIdListSelection('A 12-200', 'auth');
  window.molstar?.managers.structure.selection.fromCompiledQuery('add',query);
 ```
 
 - via expression builder(select residues with `10`<`res_id`<`15` of chains with `auth_asym_id` in `['A', 'F']`):
 ```typescript
 import { MolScriptBuilder as MS, MolScriptBuilder } from 'molstar/lib/mol-script/language/builder';
import { Expression } from 'molstar/lib/mol-script/language/expression';
import {  StructureSelectionQuery } from 'molstar/lib/mol-plugin-state/helpers/structure-selection-query'
 
 
 export function select_multiple() {
  const args = [['A', 10, 15], ['F', 10, 15]]

  const groups: Expression[] = [];
  for (var chain of args) {
    groups.push(MS.struct.generator.atomGroups({
      "chain-test": MS.core.rel.eq([MolScriptBuilder.struct.atomProperty.macromolecular.auth_asym_id(), chain[0]]),
      "residue-test": MS.core.rel.inRange([MolScriptBuilder.struct.atomProperty.macromolecular.label_seq_id(), chain[1], chain[2]])
    }));
  }
  mstar.managers.structure.selection.fromSelectionQuery('set', StructureSelectionQuery('multiple', MS.struct.combinator.merge(groups)))
  return MS.struct.combinator.merge(groups);
}
```

Check these out for more examples : https://github.com/molstar/molstar/blob/6edbae80db340134341631f669eec86543a0f1a8/src/mol-plugin-state/helpers/structure-selection-query.ts#L88-L580

#998 , #250 , #249 , #822
