### ISSUE TITLE
Is it possible to make a `PluginUIComponent` (ex. `SequenceView`) external to the default `PluginUI`? (Trying to pass `PluginUIContext` via `useContext`)

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#1005]
I'm trying, as it were, to integrate Mol* into my application and not reinvent the wheel, but also would like to opt out of the default `PluginUI` layout and rearrange things on the page. I'd like to not brea any state interactions of the molstar components.

As a first stab at this I'm trying to "lift" `SequenceView` out of the Mol* UI and pass it the initiated `PluginUIContext` to via react's context `...Context.Provider`. I thouhgt it might do the trick after seeing the constructor on the `PluginUIComponent`:

```typescript

export abstract class PluginUIComponent<P extends {} = {}, S = {}, SS = {}> extends React.Component<P & { children?: any }, S, SS> {
    readonly plugin: PluginUIContext;

    constructor(props: P, context?: any) {          // context?: any
        super(props);
        this.plugin = context;                                   // <<<<< where exactly does `context` come from?
        if (this.init) this.init();
    }
}
```

Didn't work. Still getting `TypeError: this.plugin is undefined` from `SequenceView.prototype.render`:

<details>

<summary>My `PluginUIContext` drilling attempt</summary>

```typescript
import { SequenceView } from 'molstar/lib/mol-plugin-ui/sequence'

// structure.tsx (main component)
const MolstarStateContext = createContext<PluginUIContext | undefined>(undefined);
export default function StructurePage({ ...props }) {
  const molstarNodeRef = useRef<HTMLDivElement>(null);
  const [ molstarState, setMolstarState ]   = useState<PluginUIContext | undefined>(undefined);


  useEffect(() => {

      async function init(node_ref:RefObject<HTMLDivElement>) {
        window.molstar = await createPluginUI(node_ref.current, MySpec);
        setMolstarState(window.molstar)
        const data = await window.molstar.builders.data.download({ url: "https://files.rcsb.org/download/3j7z.pdb" }, { state: { isGhost: true } });
        const trajectory = await window.molstar.builders.structure.parseTrajectory(data, "pdb");
        await window.molstar.builders.structure.hierarchy.applyPreset(trajectory, "default");
      }
    if (molstarNodeRef.current !== null) {

      if (molstarNodeRef.current) {
        init(molstarNodeRef);
      }
      return () => {
        window.molstar?.dispose();
        window.molstar = undefined;
      };

    }

  }, [molstarNodeRef]);
  
  return (
            <MolstarStateContext.Provider value={molstarState}>
          <SequenceView/>
          </MolstarStateContext.Provider >
  //... some layout stuff omitted
           <MolstarNode ref={molstarNodeRef} />
  )
```

```typescript 
// just a separate node to pass a ref (to be able to initiate PluginContext from parent above)
export const MolstarNode = forwardRef<HTMLDivElement, {}>(function MolstarNode(_, ref){
  return <div ref={ref} id='molstar-wrapper'/>
})
```

</details>

This is straining my knowledge of React a little bit: i'm also not sure if the the `SequenceView` (or any other `PluginUIComponent`-based tool ) will pick up the state(context) updates the way i did it. 

The general point is i think it's something super desirable to have for the library and shouldn't be too hard to open up if it's not already possible. Would be happy to submit a PR with a little guidance. I think this is a high quality library and i don't want to reinvent the wheel.

**Comment by dsehnal** [comment]
Yes, you just need to wrap it in `<PluginContextContainer />`, see e.g. https://github.com/molstar/molstar/blob/master/src/examples/alpha-orbitals/controls.tsx#L14-L15

**Comment by rtviii** [comment]
Like a charm. Thanks, David.
#752 #117 #921
