### ISSUE TITLE
Move selected element(atoms, residue...)

### ISSUE THREAD

**Issue by monognuisy** [molstar/molstar#1016]
Hello, I'm very new to molstar library.

Are there any library function about moving selected(or focused) element? (with mouse drag, or via some other ui...)
I've tried 'apply transform conformation' but it transform whole component, not a single selection.

Thanks.

**Comment by monognuisy** [comment]
Oh, thank you for your reply. 

Then, how can i create a new component from given loci? i can only find to create with query, or static types.

**Comment by dsehnal** [comment]
`this.plugin.builders.structure.tryCreateComponentFromSelection` with `StructureSelectionQueries.current` should do the trick.

[This](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/component.ts#L375) is how it is called for this UI action:

![image](https://github.com/molstar/molstar/assets/21145776/c40aba96-8440-4b82-8020-01cb890f6358)

**Comment by monognuisy** [comment]
Oh, thanks for your help!
