### ISSUE TITLE
Announcement: v4 beta

### ISSUE THREAD

**Issue by arose** [molstar/molstar#1018]
Hi everyone, we are wrapping up development of v4 (https://github.com/orgs/molstar/projects/2/views/1) which contains a number of breaking changes and new exciting (and experimental/untested) features.

You can find the beta release on github (https://github.com/molstar/molstar/releases/tag/v4.0.0-beta.0) and npm (https://www.npmjs.com/package/molstar/v/4.0.0-beta.0).

You can try the Viewer (https://molstar.org/dev/viewer/) and the new Mesoscale Explorer (https://molstar.org/dev/me/examples/) online.

Please test and give us feedback. We plan to merge this into master sooner rather than later but can do a patch release for the v3 branch if needed.

UPDATE: merged into master.

TODO before release:
- [ ] update/fix remote state examples

**Comment by rtviii** [comment]
Thanks for your work, both. Excited about this direction.

**Comment by dsclassen** [comment]
I have only just begun efforts to incorporate a Mol* viewer into a React app I am developing. I am seeing a console error appearing at a rate of about 100/sec:  `Uncaught (in promise) Error: empty textures are not allowed`:

<img width="1006" alt="Screenshot 2024-01-08 at 1 35 08 PM" src="https://github.com/molstar/molstar/assets/8882563/e9c6b2f7-364c-49ed-b701-5e8d659484eb">

The React component I'm working on:

```
import { useEffect, createRef } from 'react'
import { Grid } from '@mui/material'
import { styled } from '@mui/material/styles'
import Paper from '@mui/material/Paper'
import { createPluginUI } from 'molstar/lib/mol-plugin-ui'
import { renderReact18 } from 'molstar/lib/mol-plugin-ui/react18'
import { PluginUIContext } from 'molstar/lib/mol-plugin-ui/context'
/*  Might require extra configuration,
see https://webpack.js.org/loaders/sass-loader/ for example.
create-react-app should support this natively. */
import 'molstar/lib/mol-plugin-ui/skin/light.scss'

const Item = styled(Paper)(({ theme }) => ({
  padding: theme.spacing(1),
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0
}))

declare global {
  interface Window {
    molstar?: PluginUIContext
  }
}

const MolstarViewer = () => {
  const parent = createRef<HTMLDivElement>()
  // const parent = useRef(null)

  useEffect(() => {
    async function init() {
      window.molstar = await createPluginUI({
        target: parent.current as HTMLDivElement,
        render: renderReact18
      })

      const data = await window.molstar.builders.data.download(
        { url: 'https://files.rcsb.org/download/3PTB.pdb' },
        { state: { isGhost: true } }
      )
      const trajectory = await window.molstar.builders.structure.parseTrajectory(
        data,
        'pdb'
      )
      await window.molstar.builders.structure.hierarchy.applyPreset(trajectory, 'default')
    }
    init()
    return () => {
      window.molstar?.dispose()
      window.molstar = undefined
    }
  }, [])

  return (
    <Item>
      <Grid container>
        <div
          ref={parent}
          style={{
            width: '800px',
            height: '400px',
            position: 'relative'
          }}
        />
      </Grid>
    </Item>
  )
}

export default MolstarViewer
```

**Comment by arose** [comment]
@dsclassen that error usually means the viewer canvas has a size of 0 pixels. You may need to call `window.molstar.handleResize()` but @dsehnal has more experience with react setups and might correct me.

**Comment by dsehnal** [comment]
@dsclassen if you are running in strict mode, the useEffect will get called twice in debug mode causing all sorts of trouble, it might be the case of yours.

**Comment by dsclassen** [comment]
Yes, that seems to be the case. In production there are no console errors. It is a bit annoying to have the constant error spam in the console when in development mode, but I can deal with that for now.

**Comment by giagitom** [comment]
I have made some tests with huge petworld models and I think v4 provides amazing performances and quality!


Regarding issues, so far I have found this square holes frequently appearing when rapidly rotating the view only when Hi Z is enabled.  
![image](https://github.com/molstar/molstar/assets/20627977/da8266e9-1833-415c-8892-bd4305fab034)

**Comment by arose** [comment]
> Regarding issues, so far I have found this square holes frequently appearing when rapidly rotating the view only when Hi Z is enabled.

Yeah, that is a side-effect from using past depth values for the occlusion culling, if the depth is too different from the current frame (e.g., when you move the camera very fast). Just moving the camera slowly when you see it will fix it. We can also think of triggering an extra render after the camera was at rest for a bit but did not want to add that extra code just yet.

**Comment by giagitom** [comment]
I don't know about how the algorithm works, but I suspect the artifacts could increase when operating at low frame rates. (I tested on my old GTX 980)  
Maybe could be an option also avoiding to use past depth values if next camera rotation/movement goes beyond a certain threshold?

**Comment by arose** [comment]
> I don't know about how the algorithm works, but I suspect the artifacts could increase when operating at low frame rates. (I tested on my old GTX 980) Maybe could be an option also avoiding to use past depth values if next camera rotation/movement goes beyond a certain threshold?

Maybe, one would need to estimate that per pixel though, because a small rotation can have a big effect depending on the size and center of rotation.

**Comment by arose** [comment]
@mandarsd @midlik @JonStargaryen @dsehnal Any more comments/concerns? If not I suggest to merge this into master end of next week.

**Comment by midlik** [comment]
I have no concerns.

**Comment by JonStargaryen** [comment]
Had a look at v4 using rcsb-molstar and everything seems good.

**Comment by arose** [comment]
released
