### ISSUE TITLE
Interactions between SDF entries and PDB entry

### ISSUE THREAD

**Issue by leguilv** [molstar/molstar#1021]
Hello,

I've a typical use case where I have a protein structures and an SD file next to it that contains some docking poses. I'm looking for a way to display interactions between these small molecule conformation and the protein binding site but I could not find any way to do this. My prime use case is to do that through the javascript API. It seems that through the UI it's not working.

I looked into the github issues and found this from 2022 https://github.com/molstar/molstar/issues/395 which suggest it was not possible at that time.

I was therefore wondering if this kind of thing can now be done or if I can forget the idea and look into tricks ? 

Thanks :)

**Comment by dsehnal** [comment]
You can have a look at the [docking viewer app](https://github.com/molstar/molstar/blob/master/src/apps/docking-viewer/index.ts#L1). You will need to build your app with a bundler like webpack or vite though.

**Comment by leguilv** [comment]
Thanks for your answer, so nothing natively available as far as I understand. 

After a quick read, I may be wrong but it seems it's about, when adding say a new ligand conformation, re-creating components by merging them and hence removing the previous ones. I'm I correct ? If so, what would happen to e.g. custom components or representation created ?
