### ISSUE TITLE
Getting bond information from selected atom

### ISSUE THREAD

**Issue by monognuisy** [molstar/molstar#1025]
Hello, I'm looking for how to get information(location, or atom index) of bonded atoms with a selected single atom. 

For example, if the given part of chain is: `X` - `Y` - `Z` (where `X`, `Y`, `Z` are arbitrary atom) and when I selected `Y`,  I'd like to get information of `X` and `Z`. 

I've tried getting information of selected atom with:
```typescript
Structure.eachAtomicHierarchyElement(selectedAtomStructure, {
  atom: (loc) => {
    // Get information with StructureProperties.atom....
  },
});
```
but i cannot find the information for bonded atoms. Is there any ways to solve this?

**Comment by dsehnal** [comment]
For performance reasons, Mol* stores bonds in two places. Given a `Structure` object, you can find bonds between atoms that are not part of the same units in `s.interUnitBonds`. For `Unit.Atomic`, there is `bonds` property.

There is no helper method to do what you are after, but for example the `bondedAtomicPairs` [function](https://github.com/molstar/molstar/blob/master/src/mol-model/structure/query/queries/generators.ts#L307) might provide some help to get what you are looking for.

(PS: Sorry for the late response)

**Comment by monognuisy** [comment]
Thank you for the reply. I'll give it a try.

**Comment by 6EMNKEY** [comment]
> Thank you for the reply. I'll give it a try.

Did you ever manage to do so??
