### ISSUE TITLE
How to set the custom residues label in the bottom right corner of the panel when hovering over them

### ISSUE THREAD

**Issue by CrazyHsu** [molstar/molstar#1027]
Hello,

I am currently working on visualizing PDB files that have been scored in the B-factor column by other tools. 

While AlphaFold2 provides CIF files and PDB files for predicted structures, I've noticed that when I hover over residues in the CIF structure, the pLDDT score is displayed in the right-bottom corner of the panel. However, this is not the case for PDB files. 

Is there a way to display the **B-factor scores** from PDB files in the right-bottom corner of the panel? Alternatively, when providing a CIF file, is it possible to **customize the text preceding the scores** instead of the default 'pLDDT score'? 

Thanks.

**Comment by xiaoxudoo** [comment]
you can check the code in src/mol-theme/label.ts -->  _elementLabel

**Comment by dsehnal** [comment]
You can add your own "loci label provider" that accomplishes this. Search `managers.lociLabels.addProvider` to get some examples in the codebase.

**Comment by CrazyHsu** [comment]
@xiaoxudoo @dsehnal Thanks for your help. I will try the method you mentioned.
