### ISSUE TITLE
A question about how to hide/show some part of component？

### ISSUE THREAD

**Issue by xiaoxudoo** [molstar/molstar#1029]
Hi，everyone：
I have a case about hide/show some part of component（ligand）？and I have read this issue：#970 
But it has some flaw，the effect picture is like this：
![image](https://github.com/molstar/molstar/assets/8873196/8f6c7a16-26f3-46e7-b550-66bc74ea28a7)

it only hide the element spheres and the cylinders belongs to the elements（so some bond left half），but I want to hide the bonds linked to the elements which they'll hide. 

how can I make that?  thank advance! @arose @dsehnal

**Comment by dsehnal** [comment]
The easiest way would likely be subtracting the atom in question from the corresponding "structure component". Search the codebase for `modifyByCurrentSelection` [link](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/component.ts#L202)

Before:
<img width="665" alt="image" src="https://github.com/molstar/molstar/assets/21145776/c9b38bd2-867d-422a-9f02-6e5e62419322">

After: 
<img width="674" alt="image" src="https://github.com/molstar/molstar/assets/21145776/544d7b10-d1ef-4599-8cdf-f9b34b0b19f5">

**Comment by xiaoxudoo** [comment]
@dsehnal   yep，I have try the method `modifyByCurrentSelection`，but I don‘t know how to add them back（we need to toggle the selected atoms in ligand）。At last，I have to fork the repo, and modify the code in [apply transparency to any loci](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/component.ts#L403).

```js
// mol-repr/structure/visual/util/bond.ts
OrderedSet.forEach(e.indices, v => {
    for (let t = offset[v], _t = offset[v + 1]; t < _t; t++) {
        if (!isMarking || OrderedSet.has(e.indices, b[t])) {
            let reverseInterval;
            const idx = unit.bonds.getDirectedEdgeIndex(b[t], unit.bonds?.a[t]);
            // origin:  apply(Interval.ofSingleton(unitIdx * groupCount + t))
            if (apply(Interval.ofSingleton(unitIdx * groupCount + t), Interval.ofSingleton(unitIdx * groupCount + idx))) changed = true;
        }
    }
});
```
