### ISSUE TITLE
TypeError: Cannot read property '_dynamicPropertyData' of undefined

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#103]
Steps to reproduce:

- molstar.org
- load 1tqn
- preset -> annotation -> validation report (geometry quality)

This will output 
> TypeError: Cannot read property '_dynamicPropertyData' of undefined

to the console. The representation still works, might point to some real issue though.

**Comment by dsehnal** [comment]
Can't reproduce this, not locally nor on molstar.org

![image](https://user-images.githubusercontent.com/21145776/100016407-a982b200-2dd9-11eb-92df-7e321da05484.png)

**Comment by JonStargaryen** [comment]
Sorry, I meant the Mol* console:

> 13:24:52 Updated Cartoon in 28ms.
> 13:24:52 Updated Ball & Stick in 9ms.
> 13:24:52 Updated Ball & Stick in 8ms.
> 13:24:52 Updated Cartoon in 16ms.
> 13:24:52 Updated Ball & Stick in 3ms.
> 13:24:52 Updated Ball & Stick in 1ms.
> 13:24:52 TypeError: Cannot read property '_dynamicPropertyData' of undefined
> 13:24:52 Created Clashes in 4ms.
> 13:24:52 Created Ball & Stick in 218ms.
> 13:24:52 Created Validation Clashes in 19ms.

Not in the browser console for me either.

**Comment by dsehnal** [comment]
Fixed by https://github.com/molstar/molstar/commit/c0116a3baa6984faa9e02d8bc60a9e5b1f7ebb74

**Comment by JonStargaryen** [comment]
Thank you David!
