### ISSUE TITLE
Moving gl and friends to optional peer dependencies

### ISSUE THREAD

**Issue by russellp17** [molstar/molstar#1031]
Hi! It seems that on Node 20 we've run into trouble where `gl` fails to build but still takes a long time to fail and contributes to longer build times (even though we're not using the headless context at the moment).

We had some discussion in https://github.com/molstar/molstar/issues/767 about these particular dependencies that are relevant to the `HeadlessPluginContext` and now I'm thinking that it makes more sense to make them optional peer dependencies. 

Does that seem like a reasonable solution? I can put together a patch if so

cc @midlik

**Comment by dsehnal** [comment]
I think that sounds reasonable. @midlik would this require a change in PDBimages?
