### ISSUE TITLE
Inconsistent prototype for BinaryCIF decoder/encoder for IntegerPacking

### ISSUE THREAD

**Issue by epeisach** [molstar/molstar#1038]
This came about as I am fixing the py-mmcif binarycif encoder to strictly follow the data types of each encoder/decoder.

I modified the bcif decoder to strictly check types of each data type coming in - and discovered that the prototype for the molstar decoder for IntegerPacking only  accepts signed int8/16.

Based on specification, IntegerPacking should take :
"Stores a 32-bit integer array using 8- or 16-bit values. Includes the size of the input array for easier decoding. The encoding is more effective when only unsigned values are privided."

The encoder declaration is:
src/mol-io/common/binary-cif/encoding.ts
    `// Int32[] -> (Int8 | Int16 | Uint8 | Uint16)[]
    export interface IntegerPacking {
        kind: 'IntegerPacking',
        byteCount: number,
        isUnsigned: boolean,
        srcSize: number
    }`

Frequently IntegerPacking is followed by ByteArray encoding as uint_8.

In fact the function _integerPacking encoder implementation will output  both signed and unsigned types around line 327 - depending on the need.

The prototype for the decoder.ts for integerPacking indicates signed arrays - when unsigned are acceptable based on the encoder.

`function integerPacking(data: (Int8Array | Int16Array), encoding: Encoding.IntegerPacking) {`

I believe this function prototype should be altered to include the unsigned declarations as well

**Comment by dsehnal** [comment]
You are right, the typing indeed seems to be wrong here. I've adjusted the type in #1048.

Btw there is also a Python BinaryCIF encoder implemented here https://github.com/molstar/ciftools-python
