### ISSUE TITLE
Cannot read properties of undefined (reading 'entry') when apply rawData

### ISSUE THREAD

**Issue by milanow** [molstar/molstar#1039]
I want to get "pdb" file remotely through binary with the following code:

```typescript
const MySpec: PluginUISpec = {
  ...DefaultPluginUISpec(),
  config: [[PluginConfig.VolumeStreaming.Enabled, false]],
};

useEffect(() => {
    async function createPlugin(parent: HTMLElement) {
      const plugin = await createPluginUI({
        target: parent,
        render: renderReact18,
        spec: MySpec,
      } as any);

      const response = await fetch(
        `http://localhost:8888/api/protein/get/${pdb}`
      );
      const responseData = await response.json();
      const data = await plugin.builders.data.rawData(
        decodeBinaryData(responseData.PDB.Result),
        { state: { isGhost: true } }
      );

      console.log(data);
      const trajectory = await plugin.builders.structure.parseTrajectory(
        data,
        "pdb"
      );
      await plugin.builders.structure.hierarchy.applyPreset(
        trajectory,
        "default"
      );

      return plugin;
    }

function decodeBinaryData(binaryData: string): any {
  return Buffer.from(binaryData, "base64").toString("utf-8");
}
```

I gets error `TypeError: Cannot read properties of undefined (reading 'entry')` where it crashes at 
```typescript
function trajectoryProps(trajectory) {
    const first = trajectory.representative;
    return {
        label: `${first.entry}`,
        description: `${trajectory.frameCount} model${trajectory.frameCount === 1 ? '' : 's'}`
    };
}
```

wonder how could I wrap my pdb data to let PluginUI's dataBuilder recognize my data?

Thanks.

**Comment by milanow** [comment]
I use `7U4F` as the example, and I printed out the decodedString data in the console, it looks normal.
![image](https://github.com/molstar/molstar/assets/3920110/cf3211ce-7c81-4880-90ef-9bef793c9895)

**Comment by ChrisHayduk** [comment]
@milanow Can you share if you were able to resolve this issue? I'm running into the same problem when providing a PDB as a string to plugin.builders.data.rawData

**Comment by milanow** [comment]
> @milanow Can you share if you were able to resolve this issue? I'm running into the same problem when providing a PDB as a string to plugin.builders.data.rawData

Yes, data should be added a wrapper on it, the trajectory data doesn't accept rawData
