### ISSUE TITLE
get params passed into custom theme

### ISSUE THREAD

**Issue by lidaof** [molstar/molstar#104]
Hi there,

I am trying to do some custom painting for residues for the g3d model. Using the example from basic wrapper: 
```ts
export const CustomColoring = CustomElementProperty.create<number>({
    label: 'Custom coloring',
    name: 'custom-coloring',
    async getData(model: Model, ctx: CustomProperty.Context) {
        const map = new Map<ElementIndex, number>();
        const info = (G3dInfoDataProperty as any).get(model);
        console.log(info, ctx);
        for (let i = 0, _i = info.start.length; i < _i; i++) {
            map.set(i as ElementIndex, i % 2);
        }
        return { value: map };
    },
    coloring: {
        getColor(e) { return e === 0 ? Color(0xff0000) : Color(0x0000ff); },
        defaultColor: Color(0x777777)
    },
    getLabel(e) {
        return e === 0 ? 'A' : 'B';
    }
});
```
I am using this theme as:
```ts
const colorTheme = { name: CustomColoring.propertyProvider.descriptor.name, params: {...this.plugin.representation.structure.themes.colorThemeRegistry.get(CustomColoring.propertyProvider.descriptor.name).defaultValues, 
url: 'my test url'} };        
```
you see that I passed in an extra url parameter, is there a way I can get the url value within my `CustomColoring` variable? there seems is a `getParams` function in the `propertyProvider ` property of the custom theme, but I am not sure how to access the property or call the function.

Thanks a lot in advance!

**Comment by dsehnal** [comment]
``CustomElementProperty`` does not allow to customize params of the theme. Here is an example of how to define theme and provider based on custom data https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/color.ts#L44 with custom params.

**Comment by lidaof** [comment]
Thank you so much David for reply @dsehnal. I will try and might follow up later.

**Comment by lidaof** [comment]
Hi @dsehnal sorry for bothering you again.
I found the full them example is difficult for me to understand...

in the `CustomElementProperty` module, is it possible to operate `CustomProperty.Context`, which seems contain `assetManager` property, then can I use `assetManager` to contain my `url` then passed into `CustomElementProperty` ?

Thanks a lot for any input!

**Comment by dsehnal** [comment]
Again, ``CustomElementProperty`` does not support your use case. I understand that it is difficult for you to understand how it works, but for better or worse, that's how it currently is. Saying "it's difficult for me to understand the other solution you pointed me to" doesn't help anyone to actually solve your problems.

**Comment by lidaof** [comment]
Agree and make sense. Thanks! I will try to be more specific.
