### ISSUE TITLE
Inter-structure selection of residues, atoms and ligands within 5 Angstroms

### ISSUE THREAD

**Issue by Joseph-Ellaway** [molstar/molstar#1044]
Selection of residues, atoms and residues from the union tool followed by "Manipulate Selection" > "Surrounding Residues (5A) of Selection" selects only residues within the same structure:

![image](https://github.com/molstar/molstar/assets/69363546/3f74489c-78a5-41bc-86c3-c5290ef0207d)
_*1)* Initial residue selection_

![image](https://github.com/molstar/molstar/assets/69363546/575c80fe-1005-4f46-929f-a10914023595)
_*2)* Manipulate Selection" > "Surrounding Residues (5A) of Selection" to select only residues in the orange structure._

![image](https://github.com/molstar/molstar/assets/69363546/1f6fdc14-eab0-4cf0-81bc-0da5141679f6)
_*3)* Measured distance between orange (selected) and teal residues is within 5 Angstroms_

Could a new/modified union tool be added to enable selection of all residues -- including those from the blue and teal structures -- be added? These structures have been superposed and may not share the same, original Cartesian spaces -- e.g. two structures solved independently.

**Comment by dsehnal** [comment]
The queries only work within a single structure. However, it would be possible to create a query and a more generalized UI that does what you need. Roughly:

- Add new `near-point-list` query
- Convert the selected residue atoms to a list of positions
- Execute this query on all loaded structures
