### ISSUE TITLE
Toggle selection radius in "Manipulate Selection" menu

### ISSUE THREAD

**Issue by Joseph-Ellaway** [molstar/molstar#1045]
Currently, only residues, atoms and ligands within 5 Angstroms can be selected. Could this be toggled by the user -- increased/decreased as they see fit?

<img width="430" alt="Screenshot 2024-02-07 at 10 23 02" src="https://github.com/molstar/molstar/assets/69363546/4fa23522-d866-466c-a842-4b0c4fc3e029">

**Comment by dsehnal** [comment]
Not with the current default implementation. But additional queries could be added with different radii; or even special controls which allow the users to type the radius.
