### ISSUE TITLE
failed yarn build with molstar 4.0.0

### ISSUE THREAD

**Issue by milanow** [molstar/molstar#1046]
Hi I am trying to import molstar as a React UI with the doc [here](https://molstar.org/docs/plugin/) - PluginContext with built-in React UI, I may paste my code below (I know there was no data, I have comment out my data part)
```typescript
import "molstar/lib/mol-plugin-ui/skin/light.scss";
import { useEffect, createRef } from "react";
import { createPluginUI } from "molstar/lib/mol-plugin-ui";
import { PluginUIContext } from "molstar/lib/mol-plugin-ui/context";
import { renderReact18 } from "molstar/lib/mol-plugin-ui/react18";
import { MySpec, defaultData } from "./molstar-spec";

declare global {
  interface Window {
    molstar?: PluginUIContext;
  }
}

const MolStarWrapper = () => {
  const parent = createRef<HTMLDivElement>();

  useEffect(() => {
    const init = async () => {
      // window.molstar = await createPlugin(parent.current as HTMLDivElement);
      window.molstar = await createPluginUI({
        target: parent.current as HTMLDivElement,
        render: renderReact18,
        spec: MySpec,
      });
    };
    init();

    return () => {
      window.molstar?.dispose();
      window.molstar = undefined;
    };
    // }, [parent, taskId]);
  }, [parent]);

  return (
    <div>
      <div
        className="h-svh w-svh"
        ref={parent}
        style={{ position: "relative" }}
      />
    </div>
  );
};

export default MolStarWrapper;

```
`yarn build` gets me the following error:
```plain
SyntaxError: Invalid destructuring assignment target
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/Users/wth/workspace/mos-fronted/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at requirePage (/Users/wth/workspace/mos-fronted/node_modules/next/dist/server/require.js:109:84)

> Build error occurred
Error: Failed to collect page data for /
    at /Users/wth/workspace/mos-fronted/node_modules/next/dist/build/utils.js:1220:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```
If I am not using this <MolStarWrapper /> in my main page, it would build with no error. So I am thinking maybe there was issue when creating new pluginUIContext?

**Comment by cmdcolin** [comment]
just wanted to say i think i can confirm the same build error under nextjs. the built artifact is attached. interestingly, running "prettier" fails on it at what looks to be the same location that the nextjs is complaining about the Invalid destructuring, and that is these multi-line template strings, but those should be fine to have, so not sure why it is breaking


built file from next.js from .next/server/app/page.js when I had app/page.tsx as the molstar component


[built_artifact.js.gz](https://github.com/molstar/molstar/files/14248584/built_artifact.js.gz)

**Comment by cmdcolin** [comment]
now that I look at it, maybe the code actually has a syntax error with that "let Xz" directly following the `}` curly...could report to nextjs

**Comment by cmdcolin** [comment]
similar bug posted here suggests swcMinify:false and I think that does fix it for me. they should probably fix it upstream in swc https://github.com/vercel/next.js/issues/52373

**Comment by milanow** [comment]
> similar bug posted here suggests swcMinify:false and I think that does fix it for me. they should probably fix it upstream in swc [vercel/next.js#52373](https://github.com/vercel/next.js/issues/52373)

Wow that helps. Thanks for sharing this!!!

**Comment by rtviii** [comment]
@cmdcolin goat.
