### ISSUE TITLE
Adding a Volume and representation resets the view to show the whole rep

### ISSUE THREAD

**Issue by pechersky** [molstar/molstar#1049]
In our code, we're loading the volume from web-derived data. We add it on top of an existing loaded structure. The volume addition happens on user toggle. This toggle might occur after the user has zoomed or focused in on a portion of the structure. But adding the volume and rep resets the view to show the whole volume rep, which loses the previous camera state. What's the right way to add a rep without resetting the camera state? Here is our volume add code:
```
      const edensityWrapper = await plugin.builders.data.rawData({
        data: electronDensityData,
        label: "CCP4 Electron Density Map",
      });
      const edensity = await Ccp4Provider.parse(plugin, edensityWrapper);
      await plugin
        .build()
        .to(edensity.volume)
        .apply(
          StateTransforms.Representation.VolumeRepresentation3D,
          createVolumeRepresentationParams(plugin, edensity.volume.data!, {
            type: "isosurface",
            typeParams: {
              alpha: 0.4,
              isoValue: { kind: "absolute", absoluteValue: 1 },
            },
          })
        )
        .commit();
```

**Comment by dsehnal** [comment]
Setting manual camera reset before applying the transform should help: ``plugin.canvas3d?.setProps({ camera: { manualReset: true } });``

**Comment by pechersky** [comment]
Awesome! Added a point in the documentation: https://github.com/molstar/docs/pull/14
