### ISSUE TITLE
Idiomatic way to color specific residues?

### ISSUE THREAD

**Issue by lazear** [molstar/molstar#1050]
Hi,

I'm working on a basic React wrapper around the Mol* viewer. I'd like to load in a specific PDB file, and highlight specific ranges of residues on specific chains. I want to be able to visualize *all* chains (e.g. the full model) in the PDB file. By default, the code in Approach A only loads one chain, and I don't have enough mastery of Mol* internals yet to figure out how load the rest with code.

I've tried a couple different approaches that I have pieced together from skimming the codebase and other issues. Ideally, I would like to merge a couple aspects of these approaches - showing full model with ribbon representation, and selected residues colored with ball & stick. I'd also like to make sure that I am using the idiomatic/best approach to loading & handling the data - is it using the `build`/state update style? Any tips are greatly appreciated!

I also have a couple other questions:

- Is it possible to programmatically zoom to a selection?
- Is it possible to strip out non-amino acids while loading a PDB?

Approach A:
![image](https://github.com/molstar/molstar/assets/14057244/ecd62dbe-35f4-451f-b60b-e920c02f8d81)

```ts
 const initViewer = async () => {
    if (viewerRef.current) {
        console.log(viewerRef);

        ctx = await createPluginUI({target: viewerRef.current, render: renderReact18, spec});
        if (ctx) {
            const data = await ctx.builders.data.download({url: "https://files.rcsb.org/download/5E7I.pdb"});
            const traj = await ctx.builders.structure.parseTrajectory(data, "pdb");
            const model = await ctx.builders.structure.createModel(traj);
            const structure = await ctx.builders.structure.createStructure(model);

            const q = MS.struct.generator.atomGroups({
                'chain-test': MS.core.rel.eq([
                    MS.ammp('label_asym_id'),
                    'B',
                ]),
                'residue-test': MS.core.logic.and([
                    MS.core.rel.gre([
                        MS.ammp('auth_seq_id'),
                        330
                    ]),
                    MS.core.rel.lte([
                        MS.ammp('auth_seq_id'),
                        340
                    ])
                ]),
            })

            
        
            const update2 = ctx.build();
            update2.to(structure)
                .apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(ctx, structure.data, {
                    type: 'cartoon',
                    color: 'uniform',
                }));

            const update = ctx.build();
            update.to(structure)
                .apply(StateTransforms.Model.StructureSelectionFromExpression, { label: 'Surroundings', expression: q })
                .apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(ctx, structure.data, {
                    type: 'ball-and-stick',
                    color: 'illustrative',
                }));
            await update.commit();
            await update2.commit();
        }
    }
};

```

Approach B: This one loads the full model, and I can successfully select the range of residues, but I don't know how to color them!
![image](https://github.com/molstar/molstar/assets/14057244/f7331022-46f9-4655-b439-d0fb4e3e6d45)

```ts
const initViewer = async () => {
    if (viewerRef.current) {
        console.log(viewerRef);

        ctx = await createPluginUI({target: viewerRef.current, render: renderReact18, spec});
        if (ctx) {
            const data = await ctx.builders.data.download({url: "https://files.rcsb.org/download/5E7I.pdb"});
            const traj = await ctx.builders.structure.parseTrajectory(data, "pdb");
            await ctx.builders.structure.hierarchy.applyPreset(traj, "all-models");
            const s = ctx.managers.structure.hierarchy.current.structures[0];
        
            stylized(ctx);


            const q = MS.struct.generator.atomGroups({
                'chain-test': MS.core.rel.eq([
                    MS.ammp('label_asym_id'),
                    'B',
                ]),
                'residue-test': MS.core.logic.and([
                    MS.core.rel.gre([
                        MS.ammp('auth_seq_id'),
                        330
                    ]),
                    MS.core.rel.lte([
                        MS.ammp('auth_seq_id'),
                        340
                    ])
                ]),
            })
            ctx.managers.structure.selection.fromSelectionQuery('add', StructureSelectionQuery("residues", q));


            // This doesn't work - structure isn't defined! and `s` doesn't match types
            // how do I obtain a `Structure`?
            const update = ctx.build();
            update.to(structure)
                .apply(StateTransforms.Model.StructureSelectionFromExpression, { label: 'Surroundings', expression: q })
                .apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(ctx, structure.data, {
                    type: 'ball-and-stick',
                    color: 'illustrative',
                }));
            await update.commit();
        }
    }
};
```

**Comment by dsehnal** [comment]
There are two basic ways to apply custom coloring to residues:
- Write a custom theme that takes the coloring data as params. See for example the [validation report coloring theme](https://github.com/molstar/molstar/blob/a1e2b0e5aec4d92fe84fcf8e6bfe1f08cdc08a29/src/extensions/pdbe/structure-quality-report/color.ts#L44)
- Use the overpaint mechanism, which allows you to color representations using a selection. See [here](https://github.com/molstar/molstar/blob/a1e2b0e5aec4d92fe84fcf8e6bfe1f08cdc08a29/src/mol-plugin-state/helpers/structure-overpaint.ts#L21-L22) for entry point.

> Is it possible to programmatically zoom to a selection?

Yes, see `plugin.managers.camera.focusLoci` (or other `focus*` functions.

> Is it possible to strip out non-amino acids while loading a PDB?

Yes, see for example the [polymer and ligand preset](https://github.com/molstar/molstar/blob/a1e2b0e5aec4d92fe84fcf8e6bfe1f08cdc08a29/src/mol-plugin-state/builder/structure/representation-preset.ts#L160) for how the state tree is built by default for PDB files. You can either hide the ligand after applying the preset or use the code as template for your own one.

**Comment by lazear** [comment]
OK, thanks. If I use the overpaint mechanism, how do I acquire a `StructureComponentRef[]`? And how do I select given AA ranges (a `Loci`) from a `Structure`?

<img width="913" alt="image" src="https://github.com/molstar/molstar/assets/14057244/464a4b90-2a37-4365-a871-f70d23dca585">

**Comment by dsehnal** [comment]
- `plugin.managers.structure.hierarchy.current` for `StructureComponentRef`s
- You can execute a query for example with `Script.getStructureSelection` and converting it to Loci with `StructureSelection.toLociWithSourceUnits`
