### ISSUE TITLE
Mostar.org front page interactive examples - several fail...

### ISSUE THREAD

**Issue by epeisach** [molstar/molstar#1052]
Several of the interactive examples fail...

a) Cellpack HIV Capsid - error message is "error reading state"
b) Enveloped HIV capsid - "error reading state"
c) Annotated assembly 1RB8 - error reading state

**Comment by dsehnal** [comment]
Thanks, I've pushed a fix.

**Comment by epeisach** [comment]
They all work now.   You might want to update the image of the first one - as it no longer reflects view when opened.  The (what looks like) 3j3q assembly is not shown by default.
