### ISSUE TITLE
How to run examples? (2)

### ISSUE THREAD

**Issue by htaldo** [molstar/molstar#1054]
What is the general process to view the examples, or use them as a starting point for new applications?
I've tried to follow through issue #713, but I think I'm missing something.
What I've tried:
```
npm install
npm run build
```
I did this in the root dir of my project, in node_modules/molstar/ and in node_modules/molstar/lib/examples/ , since I didn't really know which was the "root directory" mentioned in #713 . But I would always get 
```
[1] error TS5083: Cannot read file '/run/media/aldo/pro/A/node_modules/molstar/tsconfig.commonjs.json'.
[1] tsc --build tsconfig.commonjs.json --incremental exited with code 1
```

I also took index.js in lib/examples/basic-wrapper as an entrypoint in my webpack.config.js and after referencing the resulting bundle in my project, I get a blank page with no errors whatsoever.

Again, apologies for the beginner question but I think I'm at a loss.

**Comment by dsehnal** [comment]
Root folder is the one with `package.json`. `npm install; npm run build` should then have the examples in `build/examples` where you can just open the corresponding index.html file in a browser (or host it using `serve` or a similar tool).

> I also took index.js in lib/examples/basic-wrapper as an entrypoint in my webpack.config.js and after referencing the resulting bundle in my project, I get a blank page with no errors whatsoever.

You will need to use a bundler like vite or webpack. Just creating a default typescript/react vite template installing the `molstar` package from NPM could get you started. You can then import things via `import ?? from 'molstar/lib/...` and vite will take care of the rest. Hopefully, this will get you started.
