### ISSUE TITLE
Transforming a Volume under a rotation and translation

### ISSUE THREAD

**Issue by pechersky** [molstar/molstar#1055]
We are depicting structures and volumes together. We can calculate a transform matrix between structures, and use it in a transform step to superpose. We'd like to also shift the volumes over (we have a structure-volume correspondence). Right now, it doesn't seem like there is a VolumeTransform like PluginStateTransform. What's the best way to achieve this? Is it modifying a Volume.Data.Grid.Tensor.Space?

**Comment by pechersky** [comment]
Or perhaps we should supply the transform to a modified `createVolumeIsosurfaceMesh`?

**Comment by dsehnal** [comment]
The "tensor space" corresponds to the grid coordinates, not cartesian. To apply geometric transform (going from grid to cartesian), you need to set the `Grid.transform` field (matrix and spacegroup are supported). See for example the [usage in the `alpha-orbitals` example](https://github.com/molstar/molstar/blob/b70f2e073d4c8346621a7e21ee9eff8a8b0d6344/src/extensions/alpha-orbitals/data-model.ts#L129). You will need to write a custom state transform that assigns this.
