### ISSUE TITLE
How to preselect uncertainty color theme?

### ISSUE THREAD

**Issue by mdanner93** [molstar/molstar#1060]
Hey,

I am currently making use of molstar within a React App, in which I try to display some ESMFold structures. 
Displaying the structures works great. Now I like to color code the uncertainties of the model by means of the b_factors.
I know there is a color theme called "uncertainty", which I can already make use of via the UI. 
Nevertheless, I do need to preselect it for my users via code implementation.

This is what I have so far:

```
const traj = await plugin.builders.structure.parseTrajectory(
          data,
          file.type
        );
 await plugin.builders.structure.hierarchy.applyPreset(traj, "default", {
          representationPresetParams: {
            color: {
              #### Here I think I need to pass the presets  ######
            },
          },
        });
```

This is how I want it to look like:
![Screenshot_molstar](https://github.com/molstar/molstar/assets/48050453/dc7d3204-5c60-4960-b0ae-f34fec776aba)

Further questions:
Is there a way to display the pLDDT Score along with the meta data of the selection in the lower right corner?
How can I adjust the colors and the interval (min, max value) for my pLDDT score?

Many thanks in advance!

**Comment by dsehnal** [comment]
Hi,

you can't "pre-select" it using the `applyPreset` (you would have to create your own preset or build the tree manually), but you can apply it afterwards. Something like this:

```ts
const preset = await plugin.applyPreset(...);
const cartoon = preset.representation.representations.polymer;
if (cartoon) {
  await plugin.build.to(cartoon).update(createStructureRepresentationParams(...));
}
```
----------

To add the label, you need to create new "label provider" that shows the b factor property. Something like this:

```ts
this.plugin.managers.lociLabels.addProvider(MyProvider);

// ...

const MyProvider: LociLabelProvider = {
    label: (loci: Loci) => {
        if (StructureElement.Loci.is(loci)) {
            const loc = StructureElement.Loci.getFirstLocation(loci);
            if (!loc) return;
            const bFactor = StructureProperties.atom.B_iso_or_equiv(loc);
            return `pLDDT: ${bFactor}`;
        }
        return;
    }
};
```

**Comment by mdanner93** [comment]
Hi @dsehnal,

thanks for your help, I do believe I am already a little bit closer to what I want to achieve.
But I am still facing some issues while implementing your solution:

```        
const cartoon = preset.representation.representations.polymer;
if (cartoon) {
  console.log(cartoon);
  const update = await plugin
    .build()
    .to(cartoon)
    .update(
      createStructureRepresentationParams(plugin, cartoon, {
        type: "cartoon",
        color: "uncertainty",
        size: "uniform",
      })
    );
  await update.commit();
}
plugin.managers.lociLabels.addProvider(MyProvider);
```

![Screenshot 2024-03-13 at 12 17 02](https://github.com/molstar/molstar/assets/48050453/74d835c2-250d-49bb-af40-c030f7a13a6c)

I would highly appreciate any suggestion steering me in the right direction.

Thanks a lot in advance.

**Comment by dsehnal** [comment]
The 2nd argument to `createStructureRepresentationParams` is a Structure. It should work to pass undefined in this case.

**Comment by mdanner93** [comment]
That worked like a charm! Thank you so much.

Last question: Since my pLDDT values are scaled between [0, 1] I also like to overwrite the values for min & max. Also it would be great to change the color scale. Is there a way to do this with this approach? 

![Screenshot 2024-03-13 at 12 56 41](https://github.com/molstar/molstar/assets/48050453/82edc8c0-eeb9-4f20-b32b-048aca113703)

**Comment by dsehnal** [comment]
Play with `colorParams: { ... }`.
