### ISSUE TITLE
Creating a component from a selection that subsets out the central symmetry mate breaks on `conformation`

### ISSUE THREAD

**Issue by pechersky** [molstar/molstar#1062]
```
TypeError: Cannot read properties of undefined (reading 'conformation')
```
at `  operator_key: p2((l) => l.unit.conformation.operator.key),`

This happens when I am trying to do
```
      const components = {
        protein: await presetStaticComponent(plugin, structureCell, "protein"),
        mateProtein: await plugin.builders.structure.tryCreateComponentFromSelection(
          structureCell,
          StructureSelectionQuery("foo",
          MS.struct.modifier.exceptBy({
            0: StructureSelectionQueries.protein.expression,
            by: MS.core.rel.eq([1555, MS.struct.atomProperty.core.operatorKey()])
          })),
          "mateProtein"
        )
      };
```
What is the better way to create a component such that I can create a rep for the symmetry mates other than the central one?

**Comment by dsehnal** [comment]
You need to wrap this in `atoms` query (and use say the `chain` aggregation) which provides the "current element location" to the callback. Basically you are filtering just elements that have your desired property value (in this case the operator name).


Also, the name is a string, not a number and it has the `1_555` format if I recall correctly.
