### ISSUE TITLE
PresetProvider CommonParams for carbonColor should accept uniform+explicit color

### ISSUE THREAD

**Issue by pechersky** [molstar/molstar#1063]
https://github.com/molstar/molstar/blob/a619ae668706927c836d389e6f706be6141a08e4/src/mol-plugin-state/builder/structure/representation-preset.ts#L47

This is for instances where we want to override the carbon color with our own ColorList cycle default.

Relatedly, where does one control what colors a structure chooses for its defaults on creation of an additional rep after reps have been made? For example, I added a "line" rep to a ligand via code, setting carbonColor to some uniform value in an element-symbol context. Now, in the UI, I add a ball and stick rep, the default colors it chooses don't match the line rep. Ditto for the focus rep.

**Comment by dsehnal** [comment]
If you are doing custom things like this, just copy-paste the code that builds the preset and add customization params that you are after. This might include writing custom theme that does everything the way you want.

If you register the preset, you can also make it default for your instance of Mol* (`PluginConfig.Structure.DefaultRepresentationPreset`).
