### ISSUE TITLE
Failed to load 8ORK with REMARK records

### ISSUE THREAD

**Issue by simeonborko** [molstar/molstar#1065]
**What I did:**
- I downloaded protein 8ORK in the cif format from https://files.rcsb.org/view/8ORK.cif
- I converted it to PDB using MAXIT: https://sw-tools.rcsb.org/apps/MAXIT/index.html
- I tried to load it in https://molstar.org/viewer/

I expected it to load normally, but Mol* was not able to load it.
- Mol* console: "Error opening file '8ork.maxit.pdb'". 
- Browser console:
```
TypeError: r is undefined [viewer:13024:25]
    get https://molstar.org/viewer/molstar.js:2
    apply https://molstar.org/viewer/molstar.js:2
```

To find the root cause of what is "wrong" in my PDB, I was deleting different lines and came to conclusion, that REMARK records cause this issue. I went to PDB format specification (https://www.wwpdb.org/documentation/file-format-content/format33/remarks.html) and it seems to me, that my records are correct.

PyMol loads it correctly.

PDB file attached (added *.txt due to GitHub restrictions).
[8ork.maxit.pdb.txt](https://github.com/molstar/molstar/files/14601488/8ork.maxit.pdb.txt)

**Comment by dsehnal** [comment]
There seems to be a bug in MAXIT when generating `REMARK 350`. `REMARK 350 APPLY THE FOLLOWING TO CHAINS: AAA` -> `REMARK 350 APPLY THE FOLLOWING TO CHAINS: A` fixes the issue.

**Comment by simeonborko** [comment]
Thank you, you are right, it's not bug in Mol*. Closing and will report to wwPDB.

**Comment by simeonborko** [comment]
Response from wwPDB is that MAXIT doesn't rename chains. I need to rename it myself before.
