### ISSUE TITLE
Is there a way to make the file explorer to read the directory tree in the host environment?

### ISSUE THREAD

**Issue by cvyaru** [molstar/molstar#1078]
I recently started to use Mol* by launching the app from a remote server and accessing the URL from my local notebook.  
My usage plan requires loading structures that are stored in that remote server; however, the file explorer from Mol* only browses files locally in my notebook.  Is there a workaround to be able to read files from the host server? Thanks!

**Comment by dsehnal** [comment]
If your files are exposed via a URL and has CORS enabled, you can enter the URL along with the format in this menu:
![image](https://github.com/molstar/molstar/assets/21145776/aab1de06-a71b-4771-8358-b74bc6a110df)
