### ISSUE TITLE
Does loading structures from URL support compressed inputs?

### ISSUE THREAD

**Issue by valasatava** [molstar/molstar#108]
Trying to load structure from URL https://files.rcsb.org/download/4hhb.cif.gz, with parameters:
Format: mmcif
Is Binary: On

Following error appears in the logs: `Error: TypeError: undefined is not an object (evaluating 't.version.match')`

**Comment by dsehnal** [comment]
Compressed inputs are currently only supported from local files. But I suppose "compression" option could be added as well. Do you need that?

**Comment by valasatava** [comment]
It's not strictly required for me. Thanks for clarifications!
