### ISSUE TITLE
Add state tree params to `addLabel`

### ISSUE THREAD

**Issue by rjdirisio** [molstar/molstar#1085]
Hello,

We have a custom viewer that labels certain parts of the protein using `plugin.managers.structure.measurement.addLabel`. We would like to have more control over making this label visible/collapsible in the state tree (via `isGhost`, etc.), as well as removing it from the state tree.

`addLabel` creates a separate `Measurement` node to the state tree (outside the `Structure`'s tree), while also associating the `Label` with the underlying `Structure` via a `dependsOn`. In the picture, one can see the label is in the separate `Measurement` node from the (redacted) structure tree that its label is associated with:
![image](https://github.com/molstar/molstar/assets/35471342/23c39bc1-f044-46f6-b841-3c528a38f249)
When one removes the structure, this leaves the empty `Measurement` node behind (with no dropdown data, because the associated `Label` was removed along with the structure)
![image](https://github.com/molstar/molstar/assets/35471342/a329f203-9d70-4483-bc5d-f816f57cbf8e)
We don't see a way to clear these upon deletion aside from manual removal from the state tree, or check, after deletion, for any nodes in the state tree that are `Measurements` with no children.

I see a few ways to address this:
- If we had the ability to hide the measurement node, or the measurement node and its children, from the state tree at the outset, this would be less visible in the front end. This would involve exposing the `state` param object to addLabel, likely for both state transforms there (`MultiStructureSelectionFromExpression `and `StructureSelectionsLabel3D`, or just `MultiStructureSelectionFromExpression`)
- Less direct: Pass back the ref associated with the Measurement / label when one calls addLabel. Currently, there's not a great way to programmatically find that label after addLabel is called, since we just get back a `Promise<void>`.
    - Similarly, one _could_ provide an API in the `StructureMeasurementManager` to delete measurements, but, I think this could be accomplished by passing refs instead because the `StructureHierarchyManager` already has a `remove` method that should work for that.

Happy to clarify any points, thanks!

**Comment by dsehnal** [comment]
Hi, more customization options, including deleting the group when it's empty, could  definitely be added. If I understand it correctly, you just want the ability to hide the measurements group completely from the state tree?

As for the ability to select the labels after creation: this could be done either by you manually keeping the refs/selectors, or using the `tag` option on transforms. I think additional options would need to be added to support the latter as well.

**Comment by rjdirisio** [comment]
> If I understand it correctly, you just want the ability to hide the measurements group completely from the state tree?

Yes, that's right. That would make it so we don't have to manage nodes in the state tree by hand

> As for the ability to select the labels after creation: this could be done either by you manually keeping the refs/selectors, or using the tag option on transforms. I think additional options would need to be added to support the latter as well.

My issue is that I don't know how to keep track of the refs, since I don't get a ref returned from `addLabel`, and if I have multiple, similar labels already in my state tree, then it's hard to distinguish any one of them.

**Comment by rjdirisio** [comment]
Ideally, in my case though, we would have the ability to hide Measurements, but not the subsequent Label. That way, when a structure is deleted, the labels get deleted, and there's no leftover nodes in the state tree.

**Comment by dsehnal** [comment]
Maybe you can make a PR which adds the ability to create the measurements group as a ghost cell (perhaps via an option in `PluginConfig.Structure`) and also returns the corresponding refs from the add label/distance/etc. functions? (Just get the `.selector` from each of the apply calls there).

**Comment by arose** [comment]
@rjdirisio still on it?

**Comment by rjdirisio** [comment]
Here's a working branch on my forked repo that has the implementation:
https://github.com/molstar/molstar/compare/master...rjdirisio:molstar:hide-measurement-label
It removes the `Measurement` Node, but the child nodes are still visible.

**Comment by arose** [comment]
> It removes the Measurement Node, but the child nodes are still visible.

Would you like to turn this into a PR or are you OK with closing this?

**Comment by rjdirisio** [comment]
I think we're good to close, thanks.
