### ISSUE TITLE
documentation is split from code: let's put it alongside code here

### ISSUE THREAD

**Issue by alisterburt** [molstar/molstar#1088]
@dsehnal and I discussed putting documentation alongside the code in this repo rather than have it exist in two separate places

As I understand it, he will merge the two types of docs into this repo and I will set up CI here to build/deploy to molstar/molstar.github.io

Are we on the same page @dsehnal ?

**Comment by dsehnal** [comment]
There are two ways we can do this. One is what you suggest to push it to `molstar.github.io`, other is to compile the docs and push it to the `gh-pages` branch of this repo and map it to `/docs`. I think the latter will be easier to do given how things are set up now.

**Comment by alisterburt** [comment]
gotcha - #1089 is there with some CI that should work

`/docs` refers to https://github.com/molstar/docs I assume? I didn't know you could map a repo to a branch, cool!

**Comment by dsehnal** [comment]
Yeah molstar/docs repo maps to molstar.github.io/docs which then gets translated to molstar.org/docs. Thanks for the CI action, that will save some time.

**Comment by dsehnal** [comment]
Implemented in #1090 and https://molstar.org/docs/ is now automatically published when pushing to master from this repo.

**Comment by alisterburt** [comment]
Amazing @dsehnal - thanks for being willing to change structure, I know these things can be annoying but I think it's worth it long term 🙂
