### ISSUE TITLE
does tests/browser/render_spheres work?

### ISSUE THREAD

**Issue by toloudis** [molstar/molstar#1100]
When I try to run tests/browser/render_spheres it doesn't show anything.  The other tests (like render_lines for example) seem to work.  I'm trying to use Canvas3D to draw a group of spheres and thought this seemed like a good minimal example.

**Comment by dsehnal** [comment]
These are not mesh, but rather impostor spheres that cannot be combined with other geometry easily. Something is indeed broken in this examples and I am sure @arose will likely know what faster than me.

In the meantime, I think using the `mesh` examples will achieve the same goal, e.g. with `MeshBuilder.addPrimitive(builderState, Mat4.fromScaling(Mat4(), Vec3.create(0.1, 0.1, 0.1)), Sphere(2));`

**Comment by arose** [comment]
it's a bug related to the LOD system, will fix

**Comment by arose** [comment]
fixed with ebe727ba2469f86dc414ee8a68373cdb71019bdf
