### ISSUE TITLE
Q: how can you get the volume outline?

### ISSUE THREAD

**Issue by zachcp** [molstar/molstar#1117]
I wanted to replicate the style from your [vilin example](https://molstar.org/viewer/?snapshot-url=https%3A%2F%2Fmolstar.org%2Fdemos%2Fstates%2Fvillin-md.molx&snapshot-url-type=molx) where the volume is very faint but the outline is prominent. I've been playing around with various settings for a bit and can't seem to find the right set of settings so I figures I'd post here.

Thanks again for this great software.

<img width="313" alt="image" src="https://github.com/molstar/molstar/assets/1260667/ff45214a-23fb-48cd-99e2-e7db16312b0d">

**Comment by arose** [comment]
Have you tried to set the opacity to a low value? it is 0.1 in the villin example.

![image](https://github.com/molstar/molstar/assets/272250/7addbe7b-5ac1-4b22-8dd0-6cf00932c3f1)

**Comment by zachcp** [comment]
Yes but i don't get a crisp edge as in the villin example.

**Comment by arose** [comment]
Can you share your state/session?

**Comment by zachcp** [comment]
Thank you @arose 

- A vanilla session on molstar with the default `1TQN` looks perfect.   ( top )
- However, `4BF4` doesn't have the outline when loading directly from the PDB ( middle )
- But.... when I toggle `Stylized` view I get the outline on 4BF4.  ( bottom )
-  So my problem is solved - e.g. I know how to get the look I am after. 
- Do you still want session data?


<img width="645" alt="image" src="https://github.com/molstar/molstar/assets/1260667/b50cb747-70ae-46dc-915d-8dee66fd9ec4">
<img width="618" alt="image" src="https://github.com/molstar/molstar/assets/1260667/3eec489f-366c-4191-a555-b81295e50fd1">
<img width="563" alt="image" src="https://github.com/molstar/molstar/assets/1260667/49ba5f6a-ccb6-4228-9ed2-158a813e1189">

**Comment by arose** [comment]
I see, just enable the outline in the settings

![image](https://github.com/molstar/molstar/assets/272250/87de6797-acf5-49b0-9b64-4433fbf7997f)

**Comment by zachcp** [comment]
Thank you!
