### ISSUE TITLE
Occlusion issue on edges 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1122]
Here a test state to reproduce [test.molj.txt](https://github.com/molstar/molstar/files/15260514/test.molj.txt)

![image](https://github.com/molstar/molstar/assets/20627977/ecb98878-33e8-45c8-b379-016eebcf3725)

**Comment by arose** [comment]
Don't know why this happens, but the strength needs to be very high to to be apparent, so maybe a clamp is needed somewhere.

**Comment by giagitom** [comment]
I'm seeing this also with default occlusion strength, it is less perceivable of course, but it seems always there when zooming in

![image](https://github.com/molstar/molstar/assets/20627977/934ac33b-4cca-4336-bc78-c6ff38e1e4b1)

**Comment by corredD** [comment]
Looks like it's come from getMappedDepth and the different resoltution, plus the multisample. If I do the following change: `float sampleDepth = getDepth(offset.xy); // getMappedDepth(offset.xy, selfCoords); ` and disable the multisample effect the artifact disappear.

**Comment by giagitom** [comment]
Hi @corredD, 
Thanks, In my system I am able to resolve the issue just by disabling multisample. ```getMappedDepth``` seems to work fine to me.
I have found something else though, that remains even keeping multisample disabled. Here a [test-state.molj.txt](https://github.com/molstar/molstar/files/15308909/test-state.molj.txt) to reproduce

![image](https://github.com/molstar/molstar/assets/20627977/4c6dea6e-f926-4898-8986-b85e4395b171)

**Comment by giagitom** [comment]
I seems to be related to the blur kernel. When disabled it disappears

**Comment by corredD** [comment]
It seems related to the near and far clipping plane values, which are used to linearize the depth value. In your example try changing the clipping value.

**Comment by giagitom** [comment]
I see, it is visible in the front and back clipping planes. 

![image](https://github.com/molstar/molstar/assets/20627977/d4b0bb20-bb43-4e7a-a325-51b1a530fc6d)

And disabling far clipping plane it disappears on the back only
![image](https://github.com/molstar/molstar/assets/20627977/54b46d42-0a87-4420-9a2a-1cd39851aac2)

**Comment by arose** [comment]
Thanks for investigating this. I am addressing this in #1134.
