### ISSUE TITLE
Possible way to clean transparent cylinders while on solidInterior mode. 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1124]
@arose, what do you think about the following patch to clean unwanted caps on transparent cylinders using solidInterior mode? 
[cylinders-solidInterior+transparency.diff.txt](https://github.com/molstar/molstar/files/15298003/cylinders-interior%2Btransparency.diff.txt)

### Before
![image](https://github.com/molstar/molstar/assets/20627977/6b068dbe-67e7-4bbd-88d5-88f636d42d86)

### After
![image](https://github.com/molstar/molstar/assets/20627977/3c83a51e-1066-41c4-9bf9-fb3bbe19174a)

**Comment by dsehnal** [comment]
I like it.

**Comment by dsehnal** [comment]
I wonder if if we could also propagate a `top/bottom-sphere-radius` param and discard the pixels that intersect with the sphere.

**Comment by giagitom** [comment]
> I wonder if if we could also propagate a top/bottom-sphere-radius param and discard the pixels that intersect with the sphere.
@dsehnal I think I already discussed this with @arose some time ago https://github.com/molstar/molstar/pull/665#issuecomment-1352640437
