### ISSUE TITLE
Show residues as spacefill 

### ISSUE THREAD

**Issue by nataliarosa9** [molstar/molstar#1125]
How can I show specific residues, such as space fill, size theme uniform, and colour theme cartoons, after selection?

      import React, { useEffect, useRef, useMemo } from 'react';
      import { createPluginUI } from 'molstar/lib/mol-plugin-ui';
      import { ColorNames } from 'molstar/lib/mol-util/color/names';
      import 'molstar/lib/mol-plugin-ui/skin/light.scss';
      import { renderReact18 } from 'molstar/lib/mol-plugin-ui/react18';
      import { PluginCommands } from 'molstar/lib/mol-plugin/commands';
      import { Script } from 'molstar/lib/mol-script/script';
      import { StructureSelection } from 'molstar/lib/mol-model/structure/query';
      import { Expression } from 'molstar/lib/mol-script/language/expression';
      import { MolScriptBuilder as MS, MolScriptBuilder } from 'molstar/lib/mol-script/language/builder';

      const MolstarViewer = ({ pdbId }) => {

      const viewerRef = useRef(null);
      const pluginInstanceRef = useRef(null);
    
      const initMolstar = useMemo(() => async () => {
              if (viewerRef.current && !pluginInstanceRef.current) {
                const plugin = await createPluginUI({
                  target: viewerRef.current,
                  layoutIsExpanded: false,
                  layoutShowControls: false,
                  layoutShowRemoteState: false,
                  layoutShowSequence: true,
                  layoutShowLog: false,
                  layoutShowLeftPanel: false,
                  viewportShowExpand: false,
                  viewportShowSelectionMode: false,
                  viewportShowAnimation: false,
                  pdbProvider: 'rcsb',
                  backgroundColor: 'white',
                  render: renderReact18,
                });
          pluginInstanceRef.current = plugin;
    
          try {
            const data = await pluginInstanceRef.current.builders.data.download(
              { url: `https://files.rcsb.org/download/${pdbId}.cif` },
              { state: { isGhost: false } }
            );
            const trajectory = await pluginInstanceRef.current.builders.structure.parseTrajectory(data, 'mmcif');
            const structure = await pluginInstanceRef.current.builders.structure.hierarchy.applyPreset(
              trajectory,
              'default'
            );
    
          // Change background color
          const renderer = plugin.canvas3d.props.renderer;
          PluginCommands.Canvas3D.SetSettings(plugin, { settings: { renderer: { ...renderer, backgroundColor: ColorNames.white} } });

      const dta = plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
        if (!dta) return;

        const selection = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
            "chain-test": Q.core.rel.eq([MolScriptBuilder.struct.atomProperty.macromolecular.auth_asym_id(),'A']),
            "residue-test": Q.core.rel.eq([MolScriptBuilder.struct.atomProperty.macromolecular.label_seq_id(), 4]),
        }), dta);
        const loci = StructureSelection.toLociWithSourceUnits(selection);
        plugin.managers.interactivity.lociSelects.select({ loci });

      } catch (error) {
        console.error('Failed to load the PDB structure:', error);
      }
    }
      }, [pdbId]);

      useEffect(() => {
        initMolstar();
    
        return () => {
          if (pluginInstanceRef.current) {
            pluginInstanceRef.current.dispose();
            pluginInstanceRef.current = null;
          }
        };
      }, [initMolstar]);
    
      return <div key={pdbId} ref={viewerRef} style={{ width: '100%', height: '100%' }} />;
    };

    export default MolstarViewer;

![1TQN](https://github.com/molstar/molstar/assets/6066985/15b3fedb-c3d9-4a47-8462-c5ab9b8ced03)

**Comment by dsehnal** [comment]
Hi @nataliarosa9, 

The [proteopedia-wrapper het groups example](https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.ts#L355) does something very similar

-------------

When you are pasting in code for your current solution, could you please format it properly next time (see for example [this](https://www.freecodecamp.org/news/how-to-format-code-in-markdown/))?

**Comment by nataliarosa9** [comment]
Hi! I tried to implement the code based on the given example. I managed to select the loci, but the new representation isn't showing up. Any ideas on how I can fix it?


    import React, { useEffect, useRef, useMemo } from 'react';
    import { createPluginUI } from 'molstar/lib/mol-plugin-ui';
    import { ColorNames } from 'molstar/lib/mol-util/color/names';
    import 'molstar/lib/mol-plugin-ui/skin/light.scss';
    import { renderReact18 } from 'molstar/lib/mol-plugin-ui/react18';
    import { PluginCommands } from 'molstar/lib/mol-plugin/commands';
    import { Script } from 'molstar/lib/mol-script/script';
    import { StructureSelection } from 'molstar/lib/mol-model/structure/query';
    import { MolScriptBuilder as MS, MolScriptBuilder } from 'molstar/lib/mol-script/language/builder';
    import { StateTransforms } from 'molstar/lib/mol-plugin-state/transforms';
    import { createStructureRepresentationParams } from 'molstar/lib/mol-plugin-state/helpers/structure-representation-params';
    
    const MolstarViewer = ({ pdbId }) => {
      const viewerRef = useRef(null);
      const pluginInstanceRef = useRef(null);
    
      const initMolstar = useMemo(() => async () => {
        if (viewerRef.current && !pluginInstanceRef.current) {
          const plugin = await createPluginUI({
            target: viewerRef.current,
            layoutIsExpanded: false,
            layoutShowControls: false,
            layoutShowRemoteState: false,
            layoutShowSequence: true,
            layoutShowLog: false,
            layoutShowLeftPanel: false,
            viewportShowExpand: false,
            viewportShowSelectionMode: false,
            viewportShowAnimation: false,
            pdbProvider: 'rcsb',
            backgroundColor: 'white',
            render: renderReact18,
          });
          pluginInstanceRef.current = plugin;

      try {
        const data = await pluginInstanceRef.current.builders.data.download(
          { url: `https://files.rcsb.org/download/${pdbId}.cif` },
          { state: { isGhost: false } }
        );
        const trajectory = await pluginInstanceRef.current.builders.structure.parseTrajectory(data, 'mmcif');
        const structure = await pluginInstanceRef.current.builders.structure.hierarchy.applyPreset(
          trajectory,
          'default'
        );

        // Change background color
        const renderer = plugin.canvas3d.props.renderer;
        PluginCommands.Canvas3D.SetSettings(plugin, { settings: { renderer: { ...renderer, backgroundColor: ColorNames.white} } });

        const dta = plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
        if (!dta) return;

        const selection = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
          "chain-test": Q.core.rel.eq([MolScriptBuilder.struct.atomProperty.macromolecular.auth_asym_id(),'A']),
          "residue-test": Q.core.rel.eq([MolScriptBuilder.struct.atomProperty.macromolecular.label_seq_id(), 4]),
        }), dta);

        const loci = StructureSelection.toLociWithSourceUnits(selection);

        // Create representation for the selection
        const reprParams = createStructureRepresentationParams(plugin, structure, {
          type: 'spacefill',
          color: 'uniform',
          colorParams: { value: ColorNames.red },
          size: 'uniform',
          sizeParams: { value: 0.3 }
        });

        const builder = plugin.build();
        builder.toRoot()
          .apply(StateTransforms.Representation.StructureRepresentation3D, reprParams, { ref: 'selection-repr', state: { isGhost: false } });
        await builder.commit();

        // Select the loci to apply the representation
        plugin.managers.interactivity.lociSelects.select({ loci });

      } catch (error) {
        console.error('Failed to load the PDB structure:', error);
      }
    }
      }, [pdbId]);
    
      useEffect(() => {
        initMolstar();
    
        return () => {
          if (pluginInstanceRef.current) {
            pluginInstanceRef.current.dispose();
            pluginInstanceRef.current = null;
          }
        };
      }, [initMolstar]);
    
      return <div key={pdbId} ref={viewerRef} style={{ width: '100%', height: '100%' }} />;
    };
    
    export default MolstarViewer;

![Screenshot 2024-05-27 190749](https://github.com/molstar/molstar/assets/6066985/50f3c4dc-ffb1-402c-b9cf-c46e3ae5fb28)

**Comment by arose** [comment]
Do you use TypeScript? There should be type issues flagged when you see such an error.

**Comment by nataliarosa9** [comment]
I use JavaScript
