### ISSUE TITLE
RCSB will be shutting down its DSN6 service edmaps.rcsb.org

### ISSUE THREAD

**Issue by epeisach** [molstar/molstar#1127]
Good afternoon,

We will be shutting down the DSN6 service on edmaps.rcsb.org at the end of June.  It would be useful to remove support in molstar.

The relevant code is at

https://github.com/molstar/molstar/blob/b11e24cd068e434c1a35d43b9f7d53392486aca7/src/mol-plugin-state/actions/volume.ts#L83-L89

Thank you

**Comment by dsehnal** [comment]
Can you please create a PR that removes the relevant provider then?

**Comment by epeisach** [comment]
Will create a PR this week.
