### ISSUE TITLE
SSAO use of getMappedDepth instead of getDepth inside normal evaluation

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1130]
@corredD @arose  
Shouldn't it be conceptually better to use getMappedDepth instead of getDepth during normal evaluation inside ```viewNormalAtPixelPositionAccurate``` ?
 
I did some tests and there are appreciable differences

**Comment by arose** [comment]
What kind of differences? Is it faster? The main reason for getMappedDepth is to get depth from a lower resolution texture when further away from a pixel to be more cache friendly. However in viewNormalAtPixelPositionAccurate the texture accesses are all very close to the pixel.

**Comment by giagitom** [comment]
Thanks for the explanation. I didn't checked about performances, but I think It would not change anything from this point of view. 
Also regarding the difference I noticed before I'm unable to reproduce it. It was probably due to something else.  

About performances, I tried to substitute ```distance()``` with ```distSquared()``` in order to avoid square root calculation
Surprisingly for me, it seems this change leads to a slight **worsening** in frame rate. Any Idea why?

```ts
#define dQuarterThreshold 0.01 // 0.1 squared
#define dHalfThreshold 0.0025 // 0.05 squared

float distSquared(const in vec2 coords1, const in vec2 coords2 ) {
    vec2 sub = coords1 - coords2;
    return dot( sub, sub );
}

float getMappedDepth(const in vec2 coords, const in vec2 selfCoords) {
    vec2 c = vec2(clamp(coords.x, uBounds.x, uBounds.z), clamp(coords.y, uBounds.y, uBounds.w));
    float d = distSquared(coords, selfCoords);
    ...
```

**Comment by arose** [comment]
> About performances, I tried to substitute distance() with distSquared() in order to avoid square root calculation
> Surprisingly for me, it seems this change leads to a slight worsening in frame rate. Any Idea why?

hmm, maybe the built-in `distance` is faster of is handled better by shader compilers/drivers. unless you are on a very weak GPU I would not expect that change to have any effect. performance should generally be texture read bound.

**Comment by arose** [comment]
good to close?

**Comment by giagitom** [comment]
Sure, Thanks
