### ISSUE TITLE
How to connect 2 atoms from different residues.

### ISSUE THREAD

**Issue by kalraUtkarsh** [molstar/molstar#1131]
I want to connect two specific atoms in a molecule, and I know which residues and chains they are in. How can I define the type of line (like a dashed blue line) to show this connection?

For example I want to connect O6 of G 24 from chain A and N3 of C 27 from chain B with a dashed line in blue colour.

Please let me know if there are already some examples out there for such things, I tried a lot but couldn't manage to find.

Thank You

**Comment by arose** [comment]
There is no "easy", readily available solution. Look at the measurement representation for an approach (e.g. src\mol-repr\shape\loci\distance.ts).
