### ISSUE TITLE
Wondering if `superpose` should be able to handle chains longer than 100-200 residues? 

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#1137]
```typescript

export function dynamicSuperimpose(ctx: PluginContext,pivot_auth_asym_id: string ) {
    return ctx.dataTransaction(async () => {
        const pivot = MS.struct.filter.first([
            MS.struct.generator.atomGroups({
                'chain-test': MS.core.rel.eq([MS.struct.atomProperty.macromolecular.auth_asym_id(), pivot_auth_asym_id])
            })
        ]);
        const query         = compile<StructureSelection>(pivot);
        const structureRefs = ctx.managers.structure.hierarchy.current.structures;
        const selections    = structureRefs.map(s => StructureSelection.toLociWithCurrentUnits(query(new QueryContext(s.cell.obj!.data))));
        const transforms    = superpose(selections);

        console.log("Got transforms", transforms);
        await siteVisual(ctx, structureRefs[0].cell, pivot)

        for (let i = 1; i < selections.length; i++) {
            await transform(ctx, structureRefs[i].cell, transforms[i - 1].bTransform);
            await siteVisual(ctx, structureRefs[i].cell, pivot)
        }
    });
}
```

I'm going off the [basic wrapper superposition example](https://github.com/molstar/molstar/blob/af3351610770eda8e189b916435f1b3b5805062e/src/examples/basic-wrapper/superposition.ts#L57-L91), of course. 

My use case is pre-loading multiple similar protein chains into the viewer and trying to superimpose them. I'm getting pretty underwhelming results, which i'm wondering if that's just the limitation of the javascript linalg library. 

A concrete example: i loaded mmcif chains "3AFI.E" and "5AFI.E" into the viewer and trying to run the logic above, but they barely aligned (see pics)
<img src="https://github.com/molstar/molstar/assets/34076599/85fe1a9a-a887-4cb0-a7e1-30657dbc13fa" width="400" height="400" />
<img src="https://github.com/molstar/molstar/assets/34076599/6cc28491-58af-49c6-957f-c6190487e6bc" width="400" height="400" />

This is what the [superpose returns](https://github.com/molstar/molstar/blob/af3351610770eda8e189b916435f1b3b5805062e/src/examples/basic-wrapper/superposition.ts#L82) in terms of transforms: 
```
Array [ {…} ]
0: Object { bTransform: (16) […], rmsd: 0.7684224265900069 }
bTransform: Array(16) [ 0.15389930902561844, 0.9016882661254453, 0.4040706705222181, … ]
​0: 0.15389930902561844
​​​1: 0.9016882661254453
​​​2: 0.4040706705222181
​​​3: 0
​​​4: -0.6232907734541886
​​​5: 0.405907098142936
​​​6: -0.6683920424416687
​​​7: 0
​​​8: -0.7666964508666165
​​​9: -0.1489885277602081
​​​10: 0.6244829035830182
​​​11: 0
​​​12: 369.24723345810753
​​​13: -16.299677972091786
​​​14: 160.57300536943566
​​​15: 1
​​​length: 16
​​​<prototype>: Array []
​​rmsd: 0.7684224265900069
​​<prototype>: Object { … }
​length: 1
```

Okay, at least this seems like it has an attempt at alignment and an rmsd value.

If i try some slightly more dissimilar chains or three+ chains at a time, it returns an "identity" 4x4 Mat and `null` rmsd. Here is a result for trying `7K00.e` and `5AFI.E`: 
<img src="https://github.com/molstar/molstar/assets/34076599/ad31ad6a-090a-42d6-9704-469a04672331" width="400" height="400" />
<img src="https://github.com/molstar/molstar/assets/34076599/18065134-790a-4195-9e75-101e0257210b" width="400" height="400" />

```
Got transforms 
Array [ {…} ]
​0: Object { bTransform: (16) […], rmsd: NaN }
​​bTransform: Array(16) [ -1, 0, 0, … ]
​​​0: -1
​​​1: 0
​​​2: 0
​​​3: 0
​​​4: 0
​​​5: -1
​​​6: 0
​​​7: 0
​​​8: 0
​​​9: 0
​​​10: 1
​​​11: 0
​​​12: 0
​​​13: 0
​​​14: 0
​​​15: 1
​​​length: 16
​​​<prototype>: Array []
​​rmsd: NaN
​​<prototype>: Object { … }
​length: 1
​<prototype>: Array []
```

Am i doing something drastically wrong or should i just give up on the idea of doing this in the browser? 
Thanks in advance.

**Comment by dsehnal** [comment]
I think for this to work better, we would need to implement some sequence alignment as well to determine which residues should be paired together.

The reason you are getting NaN is a bug in the code where it expects the first chain to be longer than the second. I've hopefully fixed that here https://github.com/molstar/molstar/pull/1138

**Comment by rtviii** [comment]
Thanks a ton, David, I was just whipping up a chimerax backed instead. I'll try this as soon as it's merged.

**Comment by rtviii** [comment]
I realize this might be a tricky ask in the browser so i merely just reporting back that after the 4.3 release the situation is not much different from before with dynamic superpose:
the superposees just jump around the pivot with unary matrices for `bTransform`s and `NaN` `rmsd`s. 

My superpose code is taken from source:
```typescript
 private async siteVisual( s: StateObjectRef<PSO.Molecule.Structure>, pivot: Expression, ) {
    const center = await this.ctx.builders.structure.tryCreateComponentFromExpression(s, pivot, 'pivot');
    if (center) await    this.ctx.builders.structure.representation.addRepresentation(center, { type: 'ball-and-stick', color: 'residue-name' });
    }

private transform( s: StateObjectRef<PSO.Molecule.Structure>, matrix: Mat4) {
    const b = this.ctx.state.data.build().to(s).insert(StateTransforms.Model.TransformStructureConformation, { transform: { name: 'matrix', params: { data: matrix, transpose: false } } });
    return    this.ctx.runTask(this.ctx.state.data.updateTree(b));
}

dynamicSuperimpose(pivot_auth_asym_id: string ) {
    return this.ctx.dataTransaction(async () => {
            const pivot = MS.struct.filter.first([
            MS.struct.generator.atomGroups({
                'chain-test': MS.core.rel.eq([MS.struct.atomProperty.macromolecular.auth_asym_id(), pivot_auth_asym_id]),
                'group-by'  : MS.struct.atomProperty.macromolecular.residueKey()
            })
        ]);

        const query         = compile<StructureSelection>(pivot);
        const structureRefs = this.ctx.managers.structure.hierarchy.current.structures;
        const selections    = structureRefs.map(s => StructureSelection.toLociWithCurrentUnits(query(new QueryContext(s.cell.obj!.data))));
        const transforms    = superpose(selections);
        console.log({...transforms});
        
        await this.siteVisual( structureRefs[0].cell, pivot)

        for (let i = 1; i < selections.length; i++) {
            await this.transform( structureRefs[i].cell, transforms[i - 1].bTransform);
            await this.siteVisual( structureRefs[i].cell, pivot)
        }
    });
}
```

And my example models are `4UG0.LC`, `7K00.e` and `4V6X.CC`... 
 
<h4> Before </h4>
<img src="https://github.com/molstar/molstar/assets/34076599/f1461ab9-5d24-4b80-b57c-d5b578e21868" width="400" height="400" />
<h4> After </h4>
<img src="https://github.com/molstar/molstar/assets/34076599/892dace2-e29c-46ba-ada3-0280bb509762" width="400" height="400" />
 
The `const transforms = superpose(selections);log({...transforms});` logs the following: 
```typescript
{
  "bTransform": [
    -1,
    0,
    0,
    0,
    0,
    -1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1
  ],
  "rmsd": null
},
{
  "bTransform": [
    -1,
    0,
    0,
    0,
    0,
    -1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1
  ],
  "rmsd": null
}
```

**Comment by arose** [comment]
Hi, you want to use `alignAndSuperpose` (does sequence alignment and uses that to guide 3d superposition) not just `superpose` (assumes input is pairs of positions and 3d superposes those).

**Comment by giagitom** [comment]
```alignAndSuperposeWithSIFTSMapping``` in which case should be used instead?

**Comment by arose** [comment]
This uses the mapping provided by SIFTS to guide the 3d superposition. It work when you have multiple structures for the same uniprot id plus you have extra sifts categories in the mmcif file.

**Comment by rtviii** [comment]
Just not to confuse myself: SIFTS has to do with extra PDB\Uniprot annotations right? 
There is a way to do this with `alignAndSuperpose` just based on seq and structure coordinates, right?

I'll what your recommended today, Alex, and reprot back. Thanks again.

**Comment by giagitom** [comment]
Ok thanks, good to know this.

**Comment by arose** [comment]
@rtviii good to close?

**Comment by rtviii** [comment]
Yes, thanks Alex. I still haven't tried what you proposed, but will post the solution here if i figure out or reopen/tag in new issue.

Thanks for the issues office-hours, as always.
