### ISSUE TITLE
Add custom interaction from different residues

### ISSUE THREAD

**Issue by andrpet** [molstar/molstar#1139]
Hi Mol* community,

I'm trying to programmatically draw custom interactions between atoms at runtime. In the documentation. 
For example I want to connect O6 of G 24 from chain A and N3 of C 27 from chain B with a dashed line in blue colour.
I haven't found any convenient API for this task. Currently, I'm looking into the Mol* source code to find a possible implementation. Any suggestions are extremely appreciated.

Here is the snippet for plugin initialization inside my React app:

`async function init() {

      window.molstar = await createPluginUI({
        target: parent.current,
        render: renderReact18,
      });

      const data = await window.molstar.builders.data.rawData({
        data: PDB,
        label: void 0
      });

      const trajectory = await window.molstar.builders.structure.parseTrajectory(data, "pdb");

      const model = await window.molstar.builders.structure.createModel(trajectory);
      const structure = await window.molstar.builders.structure.createStructure(model);

      const components = {
        polymer: await window.molstar.builders.structure.tryCreateComponentStatic(structure, 'polymer'),
        ligand: await window.molstar.builders.structure.tryCreateComponentStatic(structure, 'ligand'),
        water: await window.molstar.builders.structure.tryCreateComponentStatic(structure, 'water'),
      };

      const builder = window.molstar.builders.structure.representation;
      const update = window.molstar.build();

      if (components.polymer) builder.buildRepresentation(update, components.polymer, { type: 'cartoon' }, { tag: 'polymer' });
      if (components.ligand) builder.buildRepresentation(update, components.ligand, { type: 'ball-and-stick' }, { tag: 'ligand' });
      if (components.water) builder.buildRepresentation(update, components.water, { type: 'ball-and-stick', typeParams: { alpha: 0.6 } }, { tag: 'water' });

      await update.commit();
    }`

Thank you!

**Comment by andrpet** [comment]
Thanks to [#979](https://github.com/molstar/molstar/issues/979) I have implemented a solution that works only for atoms in same residue. When I try to connect atoms from different residues i get this error message:

state.js:685 Error: incompatible groupCount and stride
    at LocationIterator (location-iterator.js:11:1)
    at Object.groupIterator (shape.js:48:1)
    at Impl.f (representation.js:93:1)
    at async execute (observable.js:68:1)
    at async Impl.f (representation.js:246:1)
    at async execute (observable.js:68:1)
    at async Impl.f (StructureSelectionsContact3D.js:26:1)
    at async execute (observable.js:68:1)
    at async updateNode (state.js:756:1)
    at async updateSubtree (state.js:658:1)

**Comment by arose** [comment]
Hi, could you create a reproduction of you issue in CodeSanbox following the examples https://github.com/molstar/example-gallery?

**Comment by andrpet** [comment]
I successfully created a distance representation to visualize a custom interaction, here a code snippet:

  ```const getLoci = (item) => {
    const { structure, atomId, chainId, resId, atomName, atomInResId } = item;
    
    let selection;

    if (chainId && resId && atomName) {
      selection = Script.getStructureSelection(
        (Q) =>
          Q.struct.generator.atomGroups({
            'chain-test': Q.core.rel.eq([Q.struct.atomProperty.macromolecular.auth_asym_id(), chainId]),            
            'residue-test': Q.core.rel.eq([Q.struct.atomProperty.macromolecular.auth_seq_id(), resId]),
            'atom-test': Q.core.rel.eq([Q.atomName(atomName), Q.ammp('label_atom_id')])
          }),
        structure
      );
      const loci = StructureSelection.toLociWithSourceUnits(selection);
      //window.molstar.managers.camera.focusLoci(loci);
      return loci;
    }
  };

  const addContact = (contactPair) => {
    const { pair, interactionType, color } = contactPair ?? {};
    if (pair.length !== 2) return;
    const loci1 = getLoci(pair[0]);
    const loci2 = getLoci(pair[1]);
    console.log(loci1, loci2, 'ssss');
    if (loci1 && loci2) {
      addCustomInteraction(loci1, loci2, { color: color });
    }
  };

const addCustomInteraction = (a, b, options) => {
    const cellA = window.molstar.helpers.substructureParent.get(a.structure);
    const cellB = window.molstar.helpers.substructureParent.get(b.structure);
    if (!cellA || !cellB)
        return;
    const dependsOn = [cellA.transform.ref];
    arraySetAdd(dependsOn, cellB.transform.ref);
    const update = getGroup();
    update
        .apply(StateTransforms.Model.MultiStructureSelectionFromExpression, {
            selections: [
                { key: 'a', groupId: 'a', ref: cellA.transform.ref, expression: StructureElement.Loci.toExpression(a) },
                { key: 'b', groupId: 'b', ref: cellB.transform.ref, expression: StructureElement.Loci.toExpression(b) }
            ],
            isTransitive: true,
            label: 'Distance'
        }, { dependsOn, tags: options === null || options === void 0 ? void 0 : options.selectionTags })
        .apply(StructureSelectionsDistance3DCocomaps, {
            customText: (options === null || options === void 0 ? void 0 : options.customText) || '', 
            unitLabel: 'Å',
            linesColor:  options.color, 
            ...options === null || options === void 0 ? void 0 : options.lineParams,
            ...options === null || options === void 0 ? void 0 : options.labelParams,
            ...options === null || options === void 0 ? void 0 : options.visualParams
        }, { tags: options === null || options === void 0 ? void 0 : options.reprTags });
    const state = window.molstar.state.data;
    await PluginCommands.State.Update(window.molstar, { state, tree: update, options: { doNotLogTiming: true } });
}```

It works well for interactions between two atoms. 
Is it also possible to measure the distance between two rings or between an atom and a ring?
How can I hide or delete a distance measurement after I've added it

**Comment by andrpet** [comment]
Tanks to @arose i've slitly modified my getLoci funtion:
  ```
  const getLoci = (item) => {
    const { structure, atomId, chainId, resId, atomName, atomInResId } = item;
    
    let selection;

    if (chainId && resId && atomName) {
      selection = Script.getStructureSelection(
        (Q) =>
          Q.struct.generator.atomGroups({
            'chain-test': Q.core.rel.eq([Q.struct.atomProperty.macromolecular.auth_asym_id(), chainId]),            
            'residue-test': Q.core.rel.eq([Q.struct.atomProperty.macromolecular.auth_seq_id(), resId]),
            'atom-test': Q.core.rel.eq([Q.atomName(atomName), Q.ammp('label_atom_id')])
          }),
        structure
      );
    }

    if (chainId && resId && Array.isArray(atomName)) {
      const Q = MolScriptBuilder;
      const groups = [];
      for (var an of atomName) {
        groups.push(Q.struct.generator.atomGroups({
          'chain-test': Q.core.rel.eq([Q.struct.atomProperty.macromolecular.auth_asym_id(), chainId]),            
          'residue-test': Q.core.rel.eq([Q.struct.atomProperty.macromolecular.auth_seq_id(), resId]),
          'atom-test': Q.core.rel.eq([Q.atomName(an), Q.ammp('label_atom_id')])
        }));
      }
      selection = Script.getStructureSelection((Q) => Q.struct.combinator.merge(groups), structure);
    }

    const loci = StructureSelection.toLociWithSourceUnits(selection);
    return loci;
  };

    addContact({
      pair: [{
        structure: objdata,
        chainId: 'A',
        resId: 115,
        atomName: ['CE2', 'CZ', 'CE1', 'CD1', 'CG', 'CD2']
      }, {
        structure: objdata,
        chainId: 'A',
        resId: 110,
        atomName: 'CB'
      }],
      interactionType: 'Interaction test',
      color: color
    });	

  ```
