### ISSUE TITLE
Import molstar in react project

### ISSUE THREAD

**Issue by andreagia** [molstar/molstar#114]
Hi there,
 I'm trying to substitute molstar to NGL in this react component
[https://oneservice.cerm.unifi.it/andrea/zincparamwebservice/-/blob/master/frontend/reactzincparam/src/components/Nglview.js](url)
I have started whit this simple implementation:

```javascript
import React, { Component } from 'react'
import molstar from 'molstar/build/viewer/molstar'
class Viewmolstar extends Component {
    viewer = null;
    componentDidMount() {
        if (!this.viewer) {
            this.viewer = new molstar.Viewer('app', {
                layoutIsExpanded: false,
                layoutShowControls: false,
                layoutShowRemoteState: false,
                layoutShowSequence: true,
                layoutShowLog: false,
                layoutShowLeftPanel: true,
                viewportShowExpand: true,
                viewportShowSelectionMode: false,
                viewportShowAnimation: false,
                pdbProvider: 'rcsb',
                emdbProvider: 'rcsb',
            });
            this.viewer.loadPdb('7bv2');
            this.viewer.loadEmdb('EMD-30210', { detail: 6 });
        }
    } 
```
but when I try to start the app i git this error:
TypeError: Cannot read property 'Viewer' of undefined
Viewmolstar.componentDidMount
src/components/Viewmolstar.js:8
   5 | viewer = null;
   6 | componentDidMount() {
   7 |     if (!this.viewer) {
>  8 |         this.viewer = new molstar.Viewer('app', {
     | ^   9 |             layoutIsExpanded: false,
  10 |             layoutShowControls: false,
  11 |             layoutShowRemoteState: false,
View compiled

Do you have any suggestions to solve the problem.

Thanks a lot in advance!
Andrea

**Comment by dsehnal** [comment]
Hi Andrea,

this seems like an issue with the import statement.

``import * as molstar from 'molstar/build/viewer/molstar'`` will hopefully solve the issue.

David

**Comment by andreagia** [comment]
Perfect it works, I thought I tried it but I was wrong.

Thanks a lot.
Andrea
