### ISSUE TITLE
Error: Symbol 'computed.accessible-surface-area.is-accessible' is not implemented.

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1144]
In my implementation without plugin, I import ```StructureSelectionQueries``` object containing all standard selection queries. I am able to use all of them. But if I try to import any other non-standard queries like  **computed.accessible-surface-area.is-accessible** I get the error in the title when using them. Are these queries fully implemented?

**Comment by dsehnal** [comment]
Calling `DefaultQueryRuntimeTable.addCustomProp(AccessibleSurfaceAreaProvider.descriptor)` explicitly should solve this. Normally this is called when registering the `AccessibleSurfaceArea` behavior in the plugin spec.

**Comment by giagitom** [comment]
Thanks for the tip @dsehnal! It is working as expected now
