### ISSUE TITLE
Highlighting Specific Regions and Adding Custom Geometries in Embedded Mol* Viewer

### ISSUE THREAD

**Issue by smbatyankh** [molstar/molstar#1148]
Hello Mol* Team,

I am using the Embedded Mol* viewer for molecular visualization and have two questions about its capabilities:

1) Is there an existing method to effectively highlight specific regions, such as active sites within a protein, especially for large molecules(from embedded html `src/apps/viewer/embedded.html`)?

2) Does Mol* support the addition of custom geometric shapes, such as boxes, based on specified center coordinates and dimensions within the embedded viewer? If not, is this a feature you might consider adding in the future(from embedded html `src/apps/viewer/embedded.html`)?

Thank you for your support and looking forward to your response.

**Comment by dsehnal** [comment]
Hi, this is not really possible to do directly. You will need to build a small library that bundles all the required functionality. To set this up, please refer to https://github.com/molstar/example-gallery to see how you can use `esbuild` for this purpose.

**Comment by smbatyankh** [comment]
This is super cool, thanks. I created library that can do the listed.

Just one small question, can I customize plugin specs to add controls. I mean without creating viewer or using react?

**Comment by dsehnal** [comment]
What specs and controls do you want to customize?

**Comment by smbatyankh** [comment]
I am trying to add this buttons but it seems to ignore the custom options that I am providing

![Uploading Screenshot_20240605-000020.png…]()

**Comment by arose** [comment]
Those buttons are svg, just use your browser dev tools inspect option. In molstar the svg is in src\mol-plugin-ui\controls\icons.tsx together with the source of the icons.
