### ISSUE TITLE
Undesired bond when display pdb file

### ISSUE THREAD

**Issue by Nanguage** [molstar/molstar#115]
Hi, I'm using molstar to display genome structure stored in the .pdb file, but some thing seems wrong, 

![image](https://user-images.githubusercontent.com/14010939/103724192-b9afc300-500e-11eb-994e-1b3190b9a20b.png)

There are a undesired bond, but I'm sure it's not in the pdb file, here is my gziped pdb file: 
[no_outlier_L02_GAATATCA.pdb.gz](https://github.com/molstar/molstar/files/5773717/no_outlier_L02_GAATATCA.pdb.gz)

This is the screenshot in pymol, there are no this bond:

![image](https://user-images.githubusercontent.com/14010939/103723426-fed2f580-500c-11eb-966d-5fc066338170.png)

By the way, this undesired bond also occured in the NGL viewer.
I don't know it's a bug? Or somthing else can be removed by adjust some parameters.

**Comment by arose** [comment]
So the CONECT records are given in the example file. That is good. What is bad is that we don't parse them for PDB files and just do auto-bonding based on distance. I will see if I can add that.

**Comment by arose** [comment]
Hi, added better support for your use-case
* parse CONECT records from PDB files and only use those if they seem to be exhaustive (98b118fd1ef047716412adee061d5617df095f89)
* better default preset: ball&stick and per-chain coloring (e1b830a59d88c915645a6736770ae7bc37cb456e)

![NO_OUTLIER_L02_GAATATCA PDB (1)](https://user-images.githubusercontent.com/272250/104109962-dd317280-5287-11eb-87d7-90632a442a43.png)
![NO_OUTLIER_L02_GAATATCA PDB](https://user-images.githubusercontent.com/272250/104109964-de629f80-5287-11eb-8d9f-3f5451419bc2.png)

**Comment by Nanguage** [comment]
Thanks!
