### ISSUE TITLE
Transparent outlines on opaque objects

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1155]
When an opaque object intersects with a transparent object, outlines from opaque object are transparent. Is this something wanted?

![image](https://github.com/molstar/molstar/assets/20627977/6b193af1-0edc-4443-99b9-63339c6a049b)

**Comment by arose** [comment]
That is an artifact from how post processing applied. The postprocessing is applied before the transparent pass is rendered. This is done to keep things more simple and reduce passes.

**Comment by arose** [comment]
@giagitom that is fixed, right?

**Comment by giagitom** [comment]
Yeah it is.
