### ISSUE TITLE
Create a bounding box

### ISSUE THREAD

**Issue by gcrth** [molstar/molstar#1158]
I wonder if there is a way to create a bounding box. It may be useful for checking docking site configuration. Thank you.

**Comment by dsehnal** [comment]
You can add a bounding box around a `Structure`. Just apply the [StructureBoundingBox3D](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/representation.ts#L1116) to any `Structure` node.

![image](https://github.com/molstar/molstar/assets/21145776/0f155317-e034-4289-aa72-0719e51f58eb)

**Comment by gcrth** [comment]
Thank you very much for your reply. I wonder if it is possible to create bounding boxes with coordinates directly.

**Comment by dsehnal** [comment]
It is, but you will have to write a shape provider for it that maps your coordiantes to the corresponding shape. See for example the [tunnels extension](https://github.com/molstar/molstar/blob/master/src/extensions/sb-ncbr/tunnels/representation.ts#L61) for how to do that. As for how to build the box itself, see the `StructureBoundingBox3D` implementation.
