### ISSUE TITLE
Bug in `OpenFiles` Action When Extension is Not Given

### ISSUE THREAD

**Issue by frederickparsons-tandemai** [molstar/molstar#1162]
I was trying to load a bcif file using a blob in memory. I tried creating an asset where I don't specify the extension in the name like this and specifying the type as mmcif manually. I would expect the loading of the file to work ok even if I don't give an extension
      
```
      const asset = Asset.File(new File([blob], '2ZZO'))
      
      const task = pluginUIContext.current.state.data.applyAction(OpenFiles, {
        files: [asset],
        format: {
          name: 'specific',
          params: 'mmcif',
        },
        visuals: true, // Create the visual representations
      });
```

See working example of the bug [here](https://codesandbox.io/p/sandbox/inspiring-frost-lnpgfl?file=%2Fsrc%2Findex.ts%3A1%2C1-30%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxdn85dz00063b6jp6ly14av%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxdn85dy00023b6j2w7byqik%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxdn85dy00033b6jq1rr4z9y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxdn85dy00053b6jwvg6ltcy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B58.40891257139729%252C41.59108742860271%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxdn85dy00023b6j2w7byqik%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdn85dy00013b6ja1bgrbd9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A30%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxdn85dy00023b6j2w7byqik%2522%252C%2522activeTabId%2522%253A%2522clxdn85dy00013b6ja1bgrbd9%2522%257D%252C%2522clxdn85dy00053b6jwvg6ltcy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdn85dy00043b6jule1gx4s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxdn85dy00053b6jwvg6ltcy%2522%252C%2522activeTabId%2522%253A%2522clxdn85dy00043b6jule1gx4s%2522%257D%252C%2522clxdn85dy00033b6jq1rr4z9y%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxdn85dy00033b6jq1rr4z9y%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D): 

edit: from asimards investigation, it appears that `isBinary` is only detected from the filename: 
![image](https://github.com/molstar/molstar/assets/110400964/f374083d-85b3-4b93-934d-b5310f1bb662)

Sounds like the fix is just to add an additional parameter to this action so it can specify it when `specific` is used. I'll see next week if I can get a PR for this fix.

**Comment by dsehnal** [comment]
Technically speaking, you are providing a file and extension is a common way how to determine a format. The `isBinary` is only present in the "URL assets" as it is not common to use extensions there.

What exactly is preventing you when specifying the extension when creating the asset?

**Comment by frederickparsons-tandemai** [comment]
The use case is a bit unique here. I in fact have a url asset but I am doing the download of the file outside of Mol*. 

In this case I am using the default mol-plugin-ui. The issue I have is that I can correctly specify `filename.bcif` but this will appear in the UI with the extension at the root of the tree. Instead, I just want `filename` to appear at the root.

**Comment by arose** [comment]
I think you can provide a label in that transform/action as a parameter, if not we can add it.

**Comment by arose** [comment]
Still an issue?
