### ISSUE TITLE
Hydrogen bonds perceived between polar hydrogens

### ISSUE THREAD

**Issue by papillot** [molstar/molstar#1163]
Hi team!
I was looking at PDB 1GJ5 and noticed that the hydrogens from a water molecules had Hbonds interactions perceived with other polar hydrogens (from hydroxyl or amine groups).
<img width="332" alt="image" src="https://github.com/molstar/molstar/assets/116235895/94eb15dc-8a2c-489a-9535-308176c33e22">

1GJC displays another example of questionable HBonds network:
<img width="444" alt="image" src="https://github.com/molstar/molstar/assets/116235895/0d51c325-f316-4556-8572-8891a5ae4aa7">

I would expect that no HBonds could be perceived between H atoms in general.
I suppose that HBonds are computed primarily from the heavy atoms and further adjusted if Hydrogen atoms are present. The results look good in some other structures of the same series (1GJD).
Thanks!

**Comment by dsehnal** [comment]
Yes, the Hbonds are indeed approximated, so there are going to be edge cases like this. We've considered adding features to make it more straightforward to add these using an external tool.

The implementation is [here](https://github.com/molstar/molstar/blob/master/src/mol-model-props/computed/interactions/hydrogen-bonds.ts) if you fancy having a go at improving this.

**Comment by papillot** [comment]
Thanks @dsehnal !
It seems that the code in the file you've pointed to, does not take into account the hydrogens and relies on the heavy atoms to set which ones are donor or acceptor candidates.
The following code src/mol-model-props/computed/representations/interactions-inter-unit-cylinder.ts would suggest that it's at the representation stage that hydrogens positions are "favored" if they are closer to the interacting atoms.
I'd be glad to look into that code and see what I can do ;-)
Thanks

**Comment by arose** [comment]
@papillot yes, the hydrogens are not use for the calculation but only for display. You can switch it of by setting the ignoreHydrogens param in the Non-covalent Interaction representation.

I'd be curious to see how the interactions would look for the two PDB entries after some minimization.

**Comment by papillot** [comment]
Made a first attempt, just by filtering the representations so that closest bonded H atom is only used if the atom is perceived as the HBond donor:
<img width="363" alt="image" src="https://github.com/molstar/molstar/assets/116235895/eeb7a0b0-1308-4418-80b7-568cf67e0d3f">
It's a bit better, but some HBonds appear as unrealistic.

I'll now try the hard way: consider the H positions in the geometric criterions when H atoms are explicit

**Comment by papillot** [comment]
After implementing the angles computations based on the explicit hydrogen atoms, the results look better (less interactions perceived though)
![image](https://github.com/molstar/molstar/assets/116235895/91190c1b-89c1-434f-bba2-f7d32f57506b)
