### ISSUE TITLE
What is the difference between element-loci type elements and element-location? How should I convert it?

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1165]
![image](https://github.com/molstar/molstar/assets/1294316/64a56400-72b2-4160-9ee3-bfd5b1d5ce2f)

![BulBYQVACm](https://github.com/molstar/molstar/assets/1294316/fdd6ac1d-c95a-4547-b360-66324f451260)

```js
      const selections = Array.from(this.molstarRef.current.getPlugin().managers.structure.selection.entries.values());
      const chains = [];
      const resdueList = [];
      for (const { structure } of selections) {
        if (!structure) continue;

        Structure.eachAtomicHierarchyElement(structure, {
          chain: (loc) => {
            chains.push(StructureProperties.chain.auth_asym_id(loc));
          },
          atom: (loc) => {
            console.log('conformation', loc);
          },
          residue: (loc) => {
            // const stat = StructureElement.Stats.ofLoci(loc);
            resdueList.push({
              label_seq_id: StructureProperties.residue.label_seq_id(loc),
              label_comp_id: StructureProperties.atom.label_comp_id(loc),
              // stat,
              // label_comp_id: StructureProperties.residue.label_comp_id(loc),
            });
          },
        });
      }
```
Unable to determine conformation for element-location element

Thank you for your help.
Best Regards

**Comment by dsehnal** [comment]
- `location` points to a single element. Usually this is an atom, but it can be a coarse-grained element, set of triangles, volumetric cell, etc.
- `loci` is a set of locations. You can iterate though all locations in loci via `StructureElement.Loci.forEachLocation`. Please note that the `location` passed to the callback is mutable, so you need to clone it if you want to store the raw locations.
  - The main reason for the `loci` vs just a list of locations is performance. This representation allows to efficiently store ranges, so for example "all atoms in residues 10 to 22" are presented as something like `{ kind: 'structure-loci`, structure, elements: [indexOfFirstAtom, indexOfLastAtom]  }` (the actual implementation is more complicated than this as there are more details to consider).
