### ISSUE TITLE
Why can't the [Focus] Surroundings (6 Å) structure be deleted in selection mode?

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1172]
![image](https://github.com/molstar/molstar/assets/1294316/cc02adc9-f01b-4411-bddc-fd2cbfa722b2)

Thank you for your help.
Best Regards

**Comment by dsehnal** [comment]
Because this works only on substructures created by the `StructureComponent` transform. The focus representation is implemented differently.

**Comment by luckyxutao** [comment]
Is there any way to achieve Modify by Selection on the surrounding structure?

**Comment by dsehnal** [comment]
I suppose one can implement the focus behavior using the StructureComponent transform as well.

**Comment by luckyxutao** [comment]
How can I change focus and focus surrdings to be "modifiy by selection"? Can you be more detailed? Thanks
<img width="347" alt="image" src="https://github.com/molstar/molstar/assets/1294316/72c846bf-e2e1-40d3-a885-4801ee6582a4">
![image](https://github.com/molstar/molstar/assets/1294316/b0c9e0df-2f49-41f1-8f54-c4996f0d6f8f)

![image](https://github.com/molstar/molstar/assets/1294316/d8908c42-f2ec-44d8-8786-e2ee16981ffb)

**Comment by luckyxutao** [comment]
i found this solution, thanks
