### ISSUE TITLE
How should I display only residues with multiple conformations? No other structures are displayed

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1173]
Only display GLN 190 conformation A and GLN 190 conformation B，Hide everything else

<img width="989" alt="image" src="https://github.com/molstar/molstar/assets/1294316/a2907341-d118-41d4-90db-7b43a13f60cf">

Thank you for your help.
Best Regards

**Comment by dsehnal** [comment]
You can't do this in the UI currently (or at least to my knowledge). From code:

Option A:
- Use `Structure.eachAtomicHierarchyElement` to find indices (`StructureProperties.residue.key`) of all residues that have multiple conformations
- Use `atoms`'s `residues` selector to check if `StructureProperties.residue.key` is in that given set.

Option B:
- Define a new function that takes in `StructureElement.Location` and determines of the corresponding residue has multiple conformations.
- Use `atoms`'s `residues` selector with that function.

**Comment by luckyxutao** [comment]
very thanks
