### ISSUE TITLE
How should I use molQL expressions to select residues with multiple conformations?

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1177]
Such as: AUM6 401

<img width="543" alt="image" src="https://github.com/molstar/molstar/assets/1294316/2a47ff6b-1489-43a7-914c-4f28a4e5163f">
<img width="744" alt="image" src="https://github.com/molstar/molstar/assets/1294316/20fb441a-2587-44d7-ba69-b07b4770c149">
<img width="1110" alt="image" src="https://github.com/molstar/molstar/assets/1294316/9ce7b1c9-d6a0-4f1b-aacd-1c92ab865e94">
Thank you for your help.
Best Regards

**Comment by arose** [comment]
![image](https://github.com/molstar/molstar/assets/272250/2f36c562-b983-4f93-aba5-255748f1a119)

where Expression is

```
(sel.atom.atom-groups
    :residue-test (and (= atom.resname UM6) (= atom.resno 401))
    :atom-test (or (= atom.altloc A) (= atom.altloc ``))
)
```
