### ISSUE TITLE
Is there any way to parse a `Loci` object at the `Residue`/`Chain`/`Atom` boundary?

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#1185]
Thanks in advance. My use case is getting some pdb/mmcif information (chain's `auth_asym_id`, residue's `sequence_id`) out of the molstart subselection. So, provided i already have a `Loci` object (can include multiple residues from multiple chains), how can i iterate over _only residues_ in it? Or only chains? This is what i found so far:
```typescript

    //... some standard MS selection logic.
    const loci = StructureSelection.toLociWithSourceUnits(selection);
    const structure = struct.structureRef.cell.obj?.data!;
    const resdueList = [];


    StructureElement.Loci.forEachLocation(loci,
      (loc) => {
        resdueList.push({
          _: StructureProperties.unit.model_entry_id(loc),
          s: StructureProperties.residue.chem_comp_type(loc),
          label_seq_id : StructureProperties.residue.label_seq_id(loc),
          label_comp_id: StructureProperties.atom.label_comp_id(loc),
          chain_id     : StructureProperties.chain.auth_asym_id(loc),
        });
      })
```
This already gives me somethign pretty close to what i want (i.e. i can scrape the sequence ids and chains that they belong to, but the iteration is obviously on a finer level than residue (since there are 20+ entries for each `label_seq_id`). How can iterate over the residues in the `Loci`? Cast `Loci` to Structure Hierarchy somehow?
```typescript
Array(313) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]:
​
0: Object { _: "5JU8", s: "rna linking", label_seq_id: 746, … }
1: Object { _: "5JU8", s: "rna linking", label_seq_id: 746, … }
​​2: Object { _: "5JU8", s: "rna linking", label_seq_id: 746, … }
//...
​​19: Object { _: "5JU8", s: "rna linking", label_seq_id: 746, … }
20: Object { _: "5JU8", s: "rna linking", label_seq_id: 747, … }
//...
​​332: Object { _: "5JU8", s: "rna linking", label_seq_id: 2445, … }
```

-------------------

Another solution i found was in #1165 :
```typescript
      Structure.eachAtomicHierarchyElement(structure, {
          chain: (loc) => {
            chains.push(StructureProperties.chain.auth_asym_id(loc));
          },
          atom: (loc) => {
            console.log('conformation', loc);
          },
          residue: (loc) => {
            // const stat = StructureElement.Stats.ofLoci(loc);
            resdueList.push({
              label_seq_id: StructureProperties.residue.label_seq_id(loc),
              label_comp_id: StructureProperties.atom.label_comp_id(loc),
            });
          },
        });
```

This would work perfectly for me, except i'm struggling to find a way to construct a  `Structure` (first arg to `eachAtomicHierarchyElement`) from `Loci`, which is the only thing i have. If someone could point in me the right direction here, i'd appreciate that just as well.

Best. 

​

**Comment by dsehnal** [comment]
- Using your 1st approach, you can group the unique residues by using `StructureProperties.residue.key`
- `StructureElement.Loci.toStructure` converts `Loci` to structure
- If you want a bounding box, you can use `StructureElement.Loci.getBoundary`
- You can also write your own iterator similar to `eachAtomicHierarchyElement` that works directly on the `Loci` based on the implementation ([A](https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/structure.ts#L1244), [B](https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/element/loci.ts#L151))

**Comment by rtviii** [comment]
Thanks as always, David.
