### ISSUE TITLE
adjustCylinderLength affects aromatic links

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#1188]
PubChem CID 2244:

| Default ball and stick representation settings | adjustCylinderLength = true |
|----|----|
| ![image](https://github.com/molstar/molstar/assets/4458965/be57b9f7-a52b-4b93-aad8-0cc1026fd597) | ![image](https://github.com/molstar/molstar/assets/4458965/4463c638-b08f-458f-a35b-b4db8cf364fb)

I think the dashed aromatic bonds should still stretch out fully. It does makes sense to adjust the bond cylinders to center the separation between the colors of both atoms.

**Comment by arose** [comment]
I agree, care to do a PR to make `adjustCylinderLength` not affect aromatic offset bonds?

**Comment by bergwerf** [comment]
I will give it a try. I have a bit of a hard time following the code. The BallAndStickRepresentationProvider introduces IntraUnitBondCylinderVisual which flags some bonds as LinkStyle.Aromatic. There is createIntraUnitBondCylinderMesh, which creates builder props that contain the position which takes adjustCylinderLength into account. Ultimately createLinkCylinderMesh is where the fix needs to happen.
- What is the difference between referencePosition and position?
- Should we add a boolean to position which indicates if it should be adjusted?

**Comment by bergwerf** [comment]
Something needs to happen at https://github.com/molstar/molstar/blob/354438052e5161b18104d12070bbfb6d441a7357/src/mol-repr/structure/visual/util/link.ts#L432. I think vm is supposed to be the midpoint, but it is used as endpoint for addFixedCountDashes.
