### ISSUE TITLE
Multi-touch interaction with multiple Canvas3D on one Canvas3DContext

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#1190]
I created a Canvas3DContext with two Canvas3D instances. When interacting with one of them through multi-touch (gesture), the other is changed as well: both canvases zoom/pan at the same time.

I think the general rule should be that the canvas where the first pointer is initiated should be the one that is manipulated. Even when first dragging that pointer out of the viewport boundary of that canvas into the viewport boundary of another one.

**Comment by dsehnal** [comment]
You are right, this check isn't currently happening and would require adding "start x/y coordinates" to `GestureInput` to `input-observer.ts` and an `outsideViewport` check in the corresponding callback in `trackball.ts`. Would you consider making a PR with this functionality?

**Comment by bergwerf** [comment]
I looked into it further. A few notes so far:
- The gesture input is actually based on nonstandard `gesture*` events that are only supported by iOS Safari.
- Multi-touch zoom does not work in Chrome (I tested on Android). There is something called pinch, but there is something wrong.
- Might be neat to migrate to the unified pointer events API at some point (97% of clients supported, even including IE11, probably there are other features in Mol* with much less support).

**Comment by bergwerf** [comment]
For pinch the implementation looks wrong. It calculates the fraction between the current touch distance and the previous touch distance, and then the difference with the fraction that was calculated after the previous event. This is like a second differential. It should simply keep the initial touch distance as reference.

**Comment by bergwerf** [comment]
It would be neat if multi-touch interaction allows pan and scale at the same time, similar to NGL. That probably means dropping the gesture events altogether and extending pinch with a center position. The onPointerMove encapsulates some non-trivial logic (like a mask function). Is there a reason why apart from x/y, it also propagates pageX and pageY? I am unclear about why there is both eventOffset and getPagePosition.

**Comment by dsehnal** [comment]
I am all for improving the gesture support and base it on the NGL implementation. In general, we haven't spend much time on this particular functionality and it wasn't really tested much during the development either. Would you be willing to contribute to this?

> The onPointerMove encapsulates some non-trivial logic (like a mask function). 

The mask `mask: (x: number, y: number) => true,` by default. It's actually unused by the mol* codebase. Perhaps @arose needed this in a sub-project.

> Is there a reason why apart from x/y, it also propagates pageX and pageY
> I am unclear about why there is both eventOffset and getPagePosition.

It just propagates both of these values down the stream, it's up to the consumer what to do with it. Event offset

**Comment by bergwerf** [comment]
I am willing to contribute to this, but it will take me some weeks to get back to it. I do find the current abstraction a bit ugly, but I think we may not want to break things. In a similar project I normalized everything to a type similar to Vec2, and propagate only a `position: Vec2`. IMO even the derivative `movement: Vec2` is something the listener should compute locally, to make sure the abstraction layers are as DRY/pure/stateless as possible. The DOM API includes several of these things for backwards compatibility and convenience, but an abstraction layer on top of that is a change to normalize things.

The more ad-hoc solution for fixing pinch could be:
- Remove gesture; it is non-standard and does the same as pinch, it may cause conflicts.
- Optional: simplify mouse/touch with pointerevents (should not conflict with the current interface).
- Extend pinch with x/y, startX/startY, movementX/movementY (based on what is needed for panning in trackball).
- Extend onPinch in trackball to do scaling as well as panning.

I do first need to look into how to trackball makes sure there is no interference between different Canvas3D's for other events. They aren't checking a startX/startY, and still other events (eg. single touch rotation) don't interfere with each other. Perhaps a similar approach can be used for pinch.

**Comment by dsehnal** [comment]
> I do find the current abstraction a bit ugly, but I think we may not want to break things. 

I agree about not making breaking changes even though the api is now "ideal".
