### ISSUE TITLE
Vscode plugin used in remote connection

### ISSUE THREAD

**Issue by zhenyuwei99** [molstar/molstar#1195]
Hi,

I am new to using the protein viewer plugin in the vscode. I think it would be cool if I could use it on remote-connected Windows so that I don't need to download it to my local host. However, when I start the protein viewer and use the open files, the file system still shows my local file systems. Are there any methods to fix this? 

I also tried to use the command "Launch Protein Viewer from File(s)" and threw the error:
<Cannot read properties of undefined (reading 'map')>

Thanks

**Comment by dsehnal** [comment]
Hi, I am not sure. The VS code plugin is not part of the main Mol* and was developed by Arian Jamasb. Maybe you can ask at the [extension GH page](https://github.com/molstar/VSCoding-Sequence)?

**Comment by zhenyuwei99** [comment]
Great! Thank you for your suggestions!
