### ISSUE TITLE
Set settings for computed interactions provider

### ISSUE THREAD

**Issue by asimard-ta** [molstar/molstar#1196]
Hello, I am using Mol* for my viewer. I am trying to set many custom settings so the user does not have to set them themselves, for example creating a different default representation, a different focus representation, etc.

For my custom focus representation, I have created a custom behavior and added it to my custom plugin spec. The issue I am running into is that I would like to show hydrophobic interactions, by default, as part of the NCI representation. From what I can see, the NCI params use the `InteractionsRepresentationProvider`, which uses the default `InteractionsProvider`.
```ts
nciParams: PD.Group(reprParams, {
            label: 'Non-covalent Int.',
            customDefault: createStructureRepresentationParams(plugin, void 0, {
                type: InteractionsRepresentationProvider,
                color: InteractionTypeColorThemeProvider,
                size: SizeTheme.BuiltIn.uniform
            })
        }),
```
I can not see any way to set params for the `InteractionsProvider` so that it always computes hydrophobic interactions. Even using the component manager panel and toggling the hydrophobic interaction option, this only applies the change to current structures. Any structures loaded afterwards do not show hydrophobic interactions. I am not sure if this is intended or a bug
![Screenshot 2024-07-09 at 9 16 11 AM](https://github.com/molstar/molstar/assets/168480422/e58a263d-d70c-41b2-8b2a-e4688c0dd8d2)

Is it possible to make it so my focus will always show hydrophobic interactions, without the user needing to set any settings?

I'd also be happy to make a PR to make this possible (if it isn't already) with some direction as to how this could fit into the current code.

**Comment by dsehnal** [comment]
[This](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/component.ts#L111) is the code mapped to the UI you are showing in your screenshot. Should be able to figure out the reset from there.
