### ISSUE TITLE
color by occupancy

### ISSUE THREAD

**Issue by Javad228** [molstar/molstar#1197]
I know it is possible to color by occupancy from the structure tools panel. How to do this from javascript?

**Comment by dsehnal** [comment]
You need a ref to the representation, then something like this should work:

```ts
const reprSelector: StateObjectSelector<PluginStateObject.Molecule.Structure.Representation3D> = 0 as any;
// fully specify params
await this.plugin.build().to(reprSelector).update(createStructureRepresentationParams(this.plugin, reprSelector.data?.sourceData, {
    type: 'cartoon',
    color: 'occupancy',
})).commit();
// or partially update
const params = createStructureRepresentationParams(this.plugin, reprSelector.data?.sourceData, {
    color: 'occupancy'
});
await this.plugin.build().to(reprSelector).update(StructureRepresentation3D, old => {
    old.colorTheme = params.colorTheme;
}).commit();
```

**Comment by dsehnal** [comment]
You can specify a color list to sample from using `{ colorParams: { list: 'viridis' }  }` for example. Supported named color lists are [here](https://github.com/molstar/molstar/blob/master/src/mol-util/color/lists.ts#L10). You can also specify your own color list by providing for example `{ list: { kind: 'interpolate', colors: [Color(0xff0000), Color(0x0000ff)] } }` (see the [param definition](https://github.com/molstar/molstar/blob/master/src/mol-util/param-definition.ts#L131))
