### ISSUE TITLE
Focus a specific unit/residue by ID from an external application

### ISSUE THREAD

**Issue by dvmoritzschoefl** [molstar/molstar#120]
Hello, I would like to embed the molstar viewer into a React application. It should be able to load a pdb source and then focus a specific residue by its generated name (for example "MEL 63" or "CYS 94"). This is basically the same behavior that is achieved by clicking on the sequence ui on one of the letters. The embedding of the viewer itself and the loading of the pdb works, thanks to your exposed viewer class, however I have problems understanding how to resolve the ID to a Loci, in order to focus it via
`viewer.plugin.managers.camera.focusLoci(loci)`.

I would be grateful for any hints.

**Comment by dsehnal** [comment]
Hi, this https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.ts#L336 should help you. Let me know if you have more questions.

**Comment by dvmoritzschoefl** [comment]
Thank you very much, this helped a lot in understanding how queries work. Using

`this.plugin.managers.structure.focus.addFromLoci(loci)
  this.plugin.managers.camera.focusLoci(loci)`

did the trick for me (Selecting the residue I got from a query and focusing it).

One additional thing that is unclear for me is how to get the individual residue labels (LEU 133, LEU 145, REA 200, etc) from a 'Loci' object that I got from the query. The label generator only takes a single 'Location' object, so is there a way to get an iterator for 'Location' objects from a 'Loci' object or something similiar?

**Comment by dsehnal** [comment]
There is a helper function https://github.com/molstar/molstar/blob/master/src/mol-theme/label.ts#L29

If you want a custom label, you will have to write your own transformation similar to https://github.com/molstar/molstar/blob/master/src/mol-theme/label.ts#L234

**Comment by Aystein** [comment]
Thanks, I solved this by iterating the atoms in the hierarchy like in the label code and adding the ids to a set.

The last thing I would like to do, is to create a custom group for my selection query and add a label representation for it (like in the protopedia viewer). The problem I have in my wrapper (which is based on the normal molstar viewer) is that the code in the 'focusFirst' method does not work, because my 'state' object throws an exception when I try to call

`update.to(StateElements.Assembly).group(Misc.CreateGroup.....)`.


Which is weird behavior for me, since I can see that I have loaded an assembly (Assembly 1) in my viewer at the time the code gets executed.
Is there a helper function for creating groups?

**Comment by dsehnal** [comment]
I don't think you need to create a "group" for this. You need to apply the group to the actual assembly/structure object in your state tree. You would need to show me more of your code for me to help you here.

**Comment by Aystein** [comment]
Under 'Assembly 1' there are group entries like "Ligand", "Water", "Polymer" etc. The protopedia wrapper creates a custom group for the surroundings of the ligand (which is exactly what I want to do). I think the problem I have is that I dont know how to select the first 'Assembly' of my state. This code here


```
const ligand = MS.struct.filter.first([
                MS.struct.generator.atomGroups({
                    'residue-test': MS.core.rel.eq([MS.struct.atomProperty.macromolecular.label_comp_id(), this.props.ligandName]),
                    'group-by': MS.core.str.concat([MS.struct.atomProperty.core.operatorName(), MS.struct.atomProperty.macromolecular.residueKey()])
                })
            ])

  // toRoot() should be replaced with to(...) which gets me the assembly so it is created under the correct place
  let update = viewer.state.build().toRoot().group(StateTransforms.Misc.CreateGroup, { label: 'TEST' }, { ref: 'TEST' })

  update.apply(StateTransforms.Model.StructureSelectionFromExpression, { label: 'core', expression: ligand})
  PluginCommands.State.Update(viewer.plugin, { state: viewer.plugin.state.data, tree: update })
```

nearly does what I want, but of course it will create the group under the root node instead of the assembly node

**Comment by dsehnal** [comment]
But how do you create the assembly node? It is thru the load function in the viewer class?

**Comment by Aystein** [comment]
Yes, the method I use is

`this.viewer.loadPdb(pdbId)`

**Comment by dsehnal** [comment]
It is complicated to do custom stuff when using this method.

Try creating the representation like this. It's the same as the ``loadPdb`` with the exception that you need to provide a full URL (just provide one from PDBe or RCSB's mmCIF/BinaryCIF files).

```ts
const data = await plugin.builders.data.download({ url, isBinary }, { state: { isGhost: true } });
const trajectory = await plugin.builders.structure.parseTrajectory(data, format);
const hierarchy = await this.plugin.builders.structure.hierarchy.applyPreset(trajectory, 'default');
if (!hierarchy) return;

// ret.structure can be used in update.to(ret.structure) ...
```

**Comment by Aystein** [comment]
Hi, thanks for all your help, I tried another approach, and this works for me, I post it here in case someone stumbles across similiar problems

```
let update = viewer.state.build()
let assembly = viewer.state.select(StateSelection.Generators.ofType(PluginStateObject.Molecule.Structure))[0]
let obj = assembly.obj as PluginStateObject.Molecule.Structure

const group = update.to(assembly)
    .group(StateTransforms.Misc.CreateGroup, { label: 'Surroundings' }, { ref: 'TEST' })

    group.apply(StateTransforms.Model.StructureSelectionFromExpression, { label: 'Surroundings', expression: this.surroundingsExpression(this.props.ligandName, this.props.excludedEntityTypes, this.props.radius) })
    .apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(viewer.plugin, obj.data, {
        type: 'label',
        typeParams: {level: 'residue'}
    }), { tags: ['labely'] })

PluginCommands.State.Update(viewer.plugin, { state: viewer.plugin.state.data, tree: update })
```


The missing piece was

`let assembly = viewer.state.select(StateSelection.Generators.ofType(PluginStateObject.Molecule.Structure))[0]`

which selected the right node for me

**Comment by ydzdfci** [comment]
> Hi, thanks for all your help, I tried another approach, and this works for me, I post it here in case someone stumbles across similiar problems
> 
> ```
> let update = viewer.state.build()
> let assembly = viewer.state.select(StateSelection.Generators.ofType(PluginStateObject.Molecule.Structure))[0]
> let obj = assembly.obj as PluginStateObject.Molecule.Structure
> 
> const group = update.to(assembly)
>     .group(StateTransforms.Misc.CreateGroup, { label: 'Surroundings' }, { ref: 'TEST' })
> 
>     group.apply(StateTransforms.Model.StructureSelectionFromExpression, { label: 'Surroundings', expression: this.surroundingsExpression(this.props.ligandName, this.props.excludedEntityTypes, this.props.radius) })
>     .apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(viewer.plugin, obj.data, {
>         type: 'label',
>         typeParams: {level: 'residue'}
>     }), { tags: ['labely'] })
> 
> PluginCommands.State.Update(viewer.plugin, { state: viewer.plugin.state.data, tree: update })
> ```
> 
> The missing piece was
> 
> `let assembly = viewer.state.select(StateSelection.Generators.ofType(PluginStateObject.Molecule.Structure))[0]`
> 
> which selected the right node for me

Hi, I have similar problem with focus. I would like to focus a specific unit/residue by ID from parameter in url on webpage. 
I am new to JS and would you please let me know which part or file I need to modify based on your codes? 
If I need to modify .ts file, do I need to build after modification and deploy on the server. Thanks

**Comment by arose** [comment]
@ydzdfci I will adress your issue in #122
