### ISSUE TITLE
Selecting a custom residue on file open

### ISSUE THREAD

**Issue by AidanPhilip** [molstar/molstar#1200]
Hi, I'm currently working on displaying multiple protein structures from their respective files. After the file is loaded initially, I would like to be able to immediately focus on a residue via it's label (ex, 2ndf, focus on VAL 68). I understand that this functionality has to be built through a plugin. I've found many other threads about the same issue, but I haven't been able to replicate them. Furthermore, my current plugin is quite stripped down compared to the viewer wrapper. Any advice or direction to maintain the functionality of the viewer wrapper while implementing the instant focus of a residue on startup would be greatly appreciated.

Thank you.

**Comment by dsehnal** [comment]
Modification of the [hetGroups.focusFirst of the proteopedia example](https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.ts#L355) should do the trick

**Comment by AidanPhilip** [comment]
Hi, thank you very much. I'm having trouble understanding the proteopedia code, but I found a workaround solution by loading through the viewer wrapper via URL with my own file being hosted. I then made some custom highlights using components, and was wondering if it would be possible, via the viewer wrapper, to be able to import my session automatically?

 This is sort of a weird idea/solution, but I have not been able to figure out the plugin code for weeks now.

**Comment by dsehnal** [comment]
You can provide the `snapshot-url` (`-type`) args to the URL https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.html#L90

For example like [this](https://molstar.org/viewer/?snapshot-url=https%3A%2F%2Fwebchem.ncbr.muni.cz%2Fmolstar-state%2Fget%2F93cd825f-2bc0-4687-9c39-54d8ead1343f] (need to call `encodeURIComponent` on the url)

**Comment by AidanPhilip** [comment]
Perfect! Thank you very much for your help!!

**Comment by AidanPhilip** [comment]
Hi again, sorry for continuing to drag this out with different questions, but I'm going back to working with the plugin code and I was wondering how I could add back viewer wrapper UI and functionality? I'm currently building off of the PluginContext without built-in React UI example in the documentation. I'm sure this is a stupid question, but any help would be greatly appreciated once more.
