### ISSUE TITLE
Is there a way to download a single `mmcif` chain from a composite RCSB structure?

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#1202]
Ex. i want to reuse the same mechanism for loading data into the viewer:
```ts
    const data = await this.ctx.builders.data.download({ url: `https://files.rcsb.org/download/${rcsb_id.toUpperCase()}.cif` }, { state: { isGhost: true } });
    const trajectory = await this.ctx.builders.structure.parseTrajectory(data, "mmcif");
    const st = await this.ctx.builders.structure.hierarchy.applyPreset(trajectory, "
```

But their FS doesn't seem to serve single chains (I'd expect something like `https://files.rcsb.org/download/3J7Z.0.cif` or `https://files.rcsb.org/download/3J7Z_0.cif` etc., if they did it.)

Anyone has any idea if this is possible to pull of without downloading the whole 10MB struct and then rummaging through the mmcif file before initializing the representations? 

Thank you.

**Comment by rtviii** [comment]
I'm assuming the answer is No since such option is not listed in https://www.rcsb.org/docs/programmatic-access/file-download-services, but wondering if someone knows a nifty way to just load a chain instead of a structure or general advice here. Feel free to close this.

**Comment by JonStargaryen** [comment]
Hi Artem,

the Mol* ModelServer API allows you to do that. It's hosted by the RCSB PDB (https://models.rcsb.org) and PDBe (https://www.ebi.ac.uk/pdbe/model-server/).

You can isolate individual chains of interest using their `label_asym_id` using this pattern: https://models.rcsb.org/v1/3J7Z/atoms?label_asym_id=A&encoding=cif. More options are available here: https://models.rcsb.org/#/General/atoms/.

**Comment by rtviii** [comment]
Thanks, Sebastian. Exactly what i was looking for.
