### ISSUE TITLE
如何使不同pdbid的配体颜色不同

### ISSUE THREAD

**Issue by LYH1122-ZX** [molstar/molstar#1206]

**Comment by arose** [comment]
Google translate: "How to make different pdbid's ligand colors different".

You could try the structure-index color theme. But depending on what you want you need to do it manually in the UI are write your own theme.

**Comment by LYH1122-ZX** [comment]
感谢您的回答，我目前尝试了另一种方法，就是通过匹配ligand_id来改变ligand的颜色，但是目前只能变成橙色，无法我自己定义颜色
`if (data.pdbLigandList) {
    let structuresList = [];
    console.log('pdbLigandList');

    // 构建结构列表
    data.pdbLigandList.forEach(element => {
        console.log(element);
        structuresList.push({
            customData: {
                url: baseUrl + 'pdb/file/' + element.toLowerCase(),
                format: 'pdb'
            },
            hideControls: true,
            bgColor: { r: 255, g: 255, b: 255 }
        });
    });

    const structures = structuresList;

    // 创建插件实例
    var viewerInstance = new PDBeMolstarPlugin();

    // 获取 HTML/模板中的元素以放置查看器
    var viewerContainer = document.getElementById('myViewer');

    // 调用渲染方法以显示第一个 PDB 文件
    viewerInstance.render(viewerContainer, {
        ...structures[0],
        hideControls: true,
        bgColor: { r: 255, g: 255, b: 255 }
    });

    // 配体颜色数据
    let ligandColorData = [
        {
            pdb_id: "5hcz",   // 第一个 PDB ID
            ligand_id: "0WN",  // 配体ID
            color: {
                r: 255,
                g: 0,
                b: 0 // 红色
            }
        },
        {
            pdb_id: "2gs6",   // 第二个 PDB ID
            ligand_id: "112",  // 配体ID
            color: {
                r: 0,
                g: 255,
                b: 0 // 绿色
            }
        }
    ];

    let structIndex = 1;
    viewerInstance.events.loadComplete.subscribe(() => {
        if (structIndex < structures.length) {
            // 加载下一个 PDB 文件
            viewerInstance.visual.update(structures[structIndex], false);
            structIndex++;
        } else {
            // 当所有结构加载完成后，应用配体颜色
            console.log('All structures loaded, applying ligand colors...');

            // 确保配体数据加载
            setTimeout(() => {
                ligandColorData.forEach(ligand => {
                    console.log('Applying color to ligand:', ligand.ligand_id);

                    viewerInstance.visual.select({
                        data: [{
                            label_comp_id: ligand.ligand_id, // 配体ID
                        }],
                        color: ligand.color,
                        focus: true
                    });
                });
            }, 1000); // 等待一段时间，确保配体数据加载完成
        }
    });

    return;
}`
