### ISSUE TITLE
Label issues

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1208]
I have found two issues on labels:

Labels are ovelapping
![image](https://github.com/user-attachments/assets/b189e315-9cb3-4a3e-b204-977dc332aa24)

and seems broken on mesoscale explorer
![image](https://github.com/user-attachments/assets/8664b58f-5d5b-4508-9f34-bcd1b80d19ee)

**Comment by giagitom** [comment]
I have also noticed transparency issues maybe due to the overlapping issue
![image](https://github.com/user-attachments/assets/94aeca4a-9a15-48a8-aa22-291ff3a92dc0)

**Comment by corredD** [comment]
I cant reproduce this issue on windows. What browser and device are you using ?

**Comment by giagitom** [comment]
I'm on ubuntu, I tried using chrome and Firefox the problem is on both browsers. I Have an nvidia gtx 980 

Tomorrow I'll test with an other gpu

**Comment by corredD** [comment]
no issue with Mac OS as well. But we were able to reproduce on a linux machine with RTX A5000. So definitely a linux issue.

**Comment by corredD** [comment]
try with prefer-webgl1=1 same issue. I dont have a linux machine myself, so I can't really investigate more.

**Comment by arose** [comment]
what is shown in chrome://gpu when there is an issue?

**Comment by giagitom** [comment]
Here is the report file 
[about-gpu-2024-08-04T10-23-44-532Z.txt](https://github.com/user-attachments/files/16487177/about-gpu-2024-08-04T10-23-44-532Z.txt)

**Comment by giagitom** [comment]
@arose, not sure if this could help, but labels with/without border are working fine in NGL on my system. 

![image](https://github.com/user-attachments/assets/2d549ba7-e609-46ad-9e14-9ef567368670)

![image](https://github.com/user-attachments/assets/6579f910-a269-474d-b5fe-ae9f4e5bb8d3)

**Comment by arose** [comment]
fixed in #1309
