### ISSUE TITLE
How do I load cryo-em volume files from code?

### ISSUE THREAD

**Issue by sanlopez** [molstar/molstar#1214]
Having a local .mrc or .map volume file, how can I load and see it? It should be possible since I can do it with the "Open file" button from the viewer https://molstar.org/viewer

I have tried things like:

```
<script type="text/javascript">

    molstar.Viewer.create('app', {
        layoutShowControls: true,
        viewportShowExpand: false,
        collapseLeftPanel: true,
        collapseRightPanel: true,
        pixelScale: 1,
        pickScale: 0.25,
        allowMajorPerformanceCaveat: false,
        powerPreference: 'high-performance',
    }).then(viewer => {
    
        viewer.loadStructureFromUrl('data/volume.mrc', 'ccp4', true);

        window.addEventListener('unload', () => {
            // to aid GC
            viewer.dispose();
        });
    });
</script>
```

or

```
<script type="text/javascript">

    molstar.Viewer.create('app', {
        layoutShowControls: true,
        viewportShowExpand: false,
        collapseLeftPanel: true,
        collapseRightPanel: true,
        pixelScale: 1,
        pickScale: 0.25,
        allowMajorPerformanceCaveat: false,
        powerPreference: 'high-performance',
    }).then(viewer => {

        viewer.loadVolumeFromUrl({
            url: 'data/volume.mrc',
            format: 'ccp4',
            isBinary: true
        });

        window.addEventListener('unload', () => {
            // to aid GC
            viewer.dispose();
        });
    });
</script>

```
and either nothing happens or I get an error :(

Any help would be welcomed :)

**Comment by dsehnal** [comment]
Hi, due to security limitations of web browsers, you generally can't access the local file system directly.

You need to serve the files (perhaps both the index.html and the volume files in the same folder to make this easier, since there are other limitations like CORS) on `localhost` and then use `locatVolumeFromUrl` on that path. [Here](https://medium.com/@vasist.96/running-html-files-with-serve-in-localhost-a-step-by-step-guide-e554c2da9eb0) is an example tutorial how to do that (there are many ways to achieve this)

**Comment by sanlopez** [comment]
Hi,

I'm already serving the files as you say, being in the same path index.html and volume files. Indeed, it works when I use loadStructureFromUrl from a pdb file like: `viewer.loadStructureFromUrl('data/1a6d_whole.pdb', format='pdb');` but I don't get to do it with a .mrc or .map

:(

**Comment by dsehnal** [comment]
In your code, you are missing the `isovalues` parameter so it only loads the data without showing anything.

```ts
viewer.loadVolumeFromUrl({
            url: '...',
            format: 'ccp4',
            isBinary: true
        }, [{
            type: 'relative',
            value: 1.5,
            color: 0x3362B2
        }]);
```

**Comment by sanlopez** [comment]
Thank you very much, David. You saved my life! :)
