### ISSUE TITLE
Issue with Impostor cylinders when changing size theme while having adjustCylinderLength on

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1215]
There is an issue with Impostor cylinders when changing size theme and  having ```adjustCylinderLength``` enabled.
It seems cylinders lengths are not updated. 

![image](https://github.com/user-attachments/assets/e72d1a4e-6fee-4770-b143-98f0f384e2fe)

**Comment by arose** [comment]
also fixed by #1209
