### ISSUE TITLE
Is it possible to extend carbonColor options to include custom theme

### ISSUE THREAD

**Issue by xuhen** [molstar/molstar#1216]
![image](https://github.com/user-attachments/assets/34425121-7fc7-49c7-9610-fd68100cb614)

![image](https://github.com/user-attachments/assets/11506674-ddf8-4986-b878-928fa92fa64c)

I have written a theme Provider, how to make it part of the carbonColor option

**Comment by giagitom** [comment]
This could help https://github.com/molstar/molstar/pull/1209#issuecomment-2245171393

**Comment by xuhen** [comment]
> This could help [#1209 (comment)](https://github.com/molstar/molstar/pull/1209#issuecomment-2245171393)

Yes It does help! cause there are some backend data & logic involved in my custom theme. It's better to keep it with my project, Is there some mechanism in molstar to integrate it to ElementSymbolColorThemeParams's carbonColor option, so I don't need to maintain a private molstar version. thx @giagitom

**Comment by giagitom** [comment]
>  Is there some mechanism in molstar to integrate it to ElementSymbolColorThemeParams's carbonColor option, so I don't need to maintain a private molstar version.

I think this not possible at the moment

**Comment by xuhen** [comment]
> > Is there some mechanism in molstar to integrate it to ElementSymbolColorThemeParams's carbonColor option, so I don't need to maintain a private molstar version.
> 
> I think this not possible at the moment

ok then, thx your reply. I will keep a private version.
