### ISSUE TITLE
sequence panel option still exist after deleted from left side bar

### ISSUE THREAD

**Issue by xuhen** [molstar/molstar#1219]
![image](https://github.com/user-attachments/assets/d5b991f1-d490-4f3a-882e-0a850cbd5519)

![image](https://github.com/user-attachments/assets/d170c34f-6b3a-4427-8d6c-c5ec7440d6e2)

![image](https://github.com/user-attachments/assets/7697a855-45f2-4c82-83da-675736ebeda5)

As the pics show:
    step1:  open 1tqn 
    step2: open Q8W3K0
    step3: keep 1tqn option chosen, then delete Q8W3K0

result:  Q8W3K0 still exist in the option list

**Comment by arose** [comment]
Thanks, should be fixed with 84b54d97df2d0be994fecf0ac4ef404e721a35ce
