### ISSUE TITLE
show specific residue or focus when open pdb file

### ISSUE THREAD

**Issue by ydzdfci** [molstar/molstar#122]
I would like to know if I can pass parameter in url to show residue or focus loc when click url. For example: "localhost/?pdb=7chy&focus=..."
For now, like on rcsb webiste, the option of focus is greyed out unless I click atom or residues.
Thanks for your help.
![image](https://user-images.githubusercontent.com/66649006/104957220-566d4b80-5993-11eb-81bd-5e1b8fd403d4.png)
![image](https://user-images.githubusercontent.com/66649006/104957206-50776a80-5993-11eb-9168-331d6c7034fe.png)

**Comment by arose** [comment]
see also #120

**Comment by ydzdfci** [comment]
On website https://www.rcsb.org/3d-view/, it seems I can pass parameter of preset and sele to focus on first match residue. 
For example: https://www.rcsb.org/3d-view/5S2I?preset=ligandInteraction&sele=LYS. which shows "LYS 11 | A", Is there a way I can pass parameter to select loci number, like pass number 11 to focus? Thanks

**Comment by arose** [comment]
wontfix for now
