### ISSUE TITLE
How to color carbons of different chains differently under the focused view

### ISSUE THREAD

**Issue by EBGU** [molstar/molstar#1223]
Hi!

It is a really good library!
I am currently using this library to visualize structures of protein-ligand complexes. I have all proteins in the A chain while ligands in the B chain.  To color the carbon atoms of the ligand differently, I wrote the code like:
```
selection: {
  data: [
    {
      struct_asym_id: 'B',
      atoms:['C1','C2'],
      color: '#ffff00',
    },
  ],
},
 ```
It works perfectly, but not under the focused view. When I click the ligand, there will be two new components, **[Focus] Target and [Focus] Surroundings (5A)**. These two components are colored under the Element Symbol mode by default, and all carbons are in dark grey. 
I read the source code and found that in the molstar/lib/mol-theme/color/element-symbol.js, the carbon color can be set by chain-ids:
```
export var ElementSymbolColorThemeParams = {
    carbonColor: PD.MappedStatic('chain-id', {
        'chain-id': PD.Group(ChainIdColorThemeParams),
        'unit-index': PD.Group(UnitIndexColorThemeParams, { label: 'Chain Instance' }),
        'entity-id': PD.Group(EntityIdColorThemeParams),
        'entity-source': PD.Group(EntitySourceColorThemeParams),
        'operator-name': PD.Group(OperatorNameColorThemeParams),
        'model-index': PD.Group(ModelIndexColorThemeParams),
        'structure-index': PD.Group(StructureIndexColorThemeParams),
        'uniform': PD.Group(UniformColorThemeParams),
        'element-symbol': PD.EmptyGroup(),
    }, { description: 'Use chain-id coloring for carbon atoms.' }),
    saturation: PD.Numeric(0, { min: -6, max: 6, step: 0.1 }),
    lightness: PD.Numeric(0.2, { min: -6, max: 6, step: 0.1 }),
    colors: PD.MappedStatic('default', {
        'default': PD.EmptyGroup(),
        'custom': PD.Group(getColorMapParams(ElementSymbolColors))
    })
};
```
However, I don't know how to enable this feature in my HTML file. I wonder if you could kindly help me with it? Thank you very much!
The official demo can be a perfect example of my problem: [PDBe Molstar plugin demo - Basic](https://embed.plnkr.co/plunk/eMPsfuW2msk9CKC3)

**Comment by dsehnal** [comment]
The focus representation is created by Structure Focus Representation behavior and the default parameters are set [here](https://github.com/molstar/molstar/blob/master/src/mol-plugin/behavior/dynamic/selection/structure-focus-representation.ts#L36-L37). You can override these either in the `PluginSpec` when adding the `StructureFocusRepresentationBehavior` or later when the app is running with 

```ts
plugin.state.updateBehavior(StructureFocusRepresentationBehavior, old => {
  old.surroundingsParams = createStructureRepresentationParams(...);
});
```

**Comment by EBGU** [comment]
Thank you for your reply!

I found the function viewerInstance.plugin.state.updateBehavior but I cannot find the StructureFocusRepresentationBehavior under viewerInstance.plugin.spec.behaviors and the function createStructureRepresentationParams.
Could you provide some more detailed codes? I am a rookie of JavaScript and not very familiar with those codes. 

Thank you very much!

**Comment by dsehnal** [comment]
I see. These functions are not available in the pre-build PDBe wrapper. You would have to build your own instance with with esbuild or webpack (or a similar bundler) in a way similar to how the ["default" viewer is initialized](https://github.com/molstar/molstar/blob/master/src/apps/viewer/app.ts#L128). To gain access to these functions, you can use the `import` statement in JavaScript.

**Comment by EBGU** [comment]
Thank you! 
However, my project is a little bit complicated, and building my own instance would lead to a lot of changes.
I wonder if there are any ways to just manually assign colors for atoms of the focus region? Something like:
```
selection: {
  data: [
    {
      struct_asym_id: 'B',
      atoms:['C1','C2'],
      color: '#ffff00',
    },
  ],
},
```

**Comment by dsehnal** [comment]
You can try using [MolViewSpec](https://github.com/molstar/mol-view-spec)

**Comment by EBGU** [comment]
I have fixed it. Thank you very much!
