### ISSUE TITLE
How to determine if an atom is in aromatic ring in molstar

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1225]
When I select an atom, how can I tell if the atom is in a aromatic ring?

![image](https://github.com/user-attachments/assets/ee839491-5a7d-47b5-9451-df8f4007ef07)

Thank you for your help. Best Regards

**Comment by dsehnal** [comment]
There is an internal function that determines this [here](https://github.com/molstar/molstar/blob/master/src/mol-model-props/computed/chemistry/functional-group.ts#L13). Let us know if you need more help.
