### ISSUE TITLE
Could not find a declaration file for module 'molstar/build/viewer/molstar'.

### ISSUE THREAD

**Issue by AidanPhilip** [molstar/molstar#1226]
Hi, I'm currently trying to use the viewer with the molstar npm package installed. The documentation states that the viewer can be imported via `import { Viewer } from 'molstar/build/viewer/molstar'` but it is not working for me. Any help would be greatly appreciated.

**Comment by dsehnal** [comment]
`import { Viewer } from 'molstar/lib/apps/viewer/app'` should work.

**Comment by AidanPhilip** [comment]
Thank you so much, works beautifully!
