### ISSUE TITLE
Unintuitive behavior when toggling non-covalent contacts 

### ISSUE THREAD

**Issue by bisejdiu** [molstar/molstar#123]
I stumbled upon this behavior that I find unintuitive and may not be intended. Steps to reproduce: 

1. Create a non-covalent interaction presentation for any protein.
2. Click on any residue. Mol* will bring that residue into focus. 
3. Reset the camera and delete the [Focus] representations.

If you now toggle the visibility of any of the non-covalent interactions (say, disable Cation-Pi interactions), Mol* will still put the previously selected residue into focus. Regardless if you make any other selection or create other representations, any time you toggle the visibility of non-covalent contacts, Mol* will highlight that residue and create the [Focus] representations.

**Comment by dsehnal** [comment]
I see, but if you click anywhere on the background to reset the focus selection, it will behave normally, right?

**Comment by bisejdiu** [comment]
Yes, that resets the focus but the whole behaviour I'd argue is not very intuitive and may get confusing. This is especially true if you are building an application that doesn't show the Focus menu. 
Perhaps a better way may be to reset the focus automatically anytime an action that has an implicit or explicit selection as input (e.g. creating a new representation) is performed? I realize though that in the grand scheme of things this is a relatively minor issue.

**Comment by arose** [comment]
@bisejdiu Would it be helpful to remove the `StructureFocusRepresentation` behavior altogether? The zooming in on click would still be available as that is another behavior.

@dsehnal As far as I can tell we currently can't remove the `StructureFocusRepresentation` behavior because it gets auto added via `this.plugin.state.updateBehavior` in two places.

**Comment by arose** [comment]
Hey @bisejdiu this should be fixed with https://github.com/molstar/molstar/commit/189fad3d84ca5e9aee660f2385ed2d913f2915c2.
