### ISSUE TITLE
Mol2 file status_bit display error.

### ISSUE THREAD

**Issue by QDMarkMan** [molstar/molstar#1232]
Hi, here is my  issue description:

### 1. Bug Description
If my MOL2 file contains status_bit in atoms or bonds, it will render an incorrect structure, as shown below:

**Expected Behavior:**
DIsplay the right version from mol2 file. 

**Actual Behavior:**
![image](https://github.com/user-attachments/assets/3050a83a-3eb5-4062-8c40-3b0843dd9e49)
![image](https://github.com/user-attachments/assets/adda9f96-d5a8-4096-b5fe-ff5446e9b5b6)

### 2. Environment
- molstar: [The latest version]

### 3. Possible Solution

After checked the code, I found teh code below maybe cause a mol2 parse error:
![image](https://github.com/user-attachments/assets/14c09b11-b89c-4ef3-8da5-1b6ca947f85f)

**Comment by arose** [comment]
Thanks for reporting this. Could you try to do a PR with a fix?

**Comment by QDMarkMan** [comment]
> Thanks for reporting this. Could you try to do a PR with a fix?

Thanks for your replay! I’ll try to submit a PR later.
