### ISSUE TITLE
Render proteins from url as models

### ISSUE THREAD

**Issue by smbatyankh** [molstar/molstar#1234]
Hi Mol* community,

I am wondering is there a way to load multiple protein structures using URLs and show them as separate models within Mol*, similar to how loading an SDF file displays each ligand as a separate model? Any guidance on how to do this would be greatly appreciated.

Thank you in advance!

**Comment by dsehnal** [comment]
I am not sure how you are using Mol*, but for example you can just do multiple `await viewer.loadPdb()` calls after each other.
