### ISSUE TITLE
Error: Unexpected token. Expected data_, loop_, or data name 

### ISSUE THREAD

**Issue by MungShu71** [molstar/molstar#1240]
Hello. I'm very new to this and am trying to integrate Mol* with Django. 

I've added a url link to the CIF/PDB file, but whenever  I try to load it using an instance example from [https://molstar.org/docs/plugin/instance/](https://molstar.org/docs/plugin/instance/) and viewer.loadStructureFromUrl I get and error statement of Unexpected token. Expected data_, loop_, or data name and a long list of functions/variables.

![image](https://github.com/user-attachments/assets/5bbd241f-0f6e-4917-9040-35fa38694a4c)

Any ideas?

**Comment by dsehnal** [comment]
CIF and PDB are different formats. The error says you have not provided a valid CIF file to the viewer.

**Comment by MungShu71** [comment]
I've made sure the CIF file is correct, but still getting the same error.

**Comment by dsehnal** [comment]
Maybe CORS?

**Comment by MungShu71** [comment]
I'm able to open PDB files but not mmcif.

**Comment by dsehnal** [comment]
I can't really advice you more without seeing your code, but seems to me like you are linking a PDB file to the `loadStructureFromUrl` instead of the mmCIF one.

**Comment by MungShu71** [comment]
`viewer.loadStructureFromUrl(url=path_to_file, format='pdb')` works when the file is a PDB.
However,
viewer.loadStructureFromUrl(url=path_to_file, format='mmcif') does not work when the file is a mmcif/cif file (downloaded from RCSB). I still get the unexpected token error.

**Comment by JonStargaryen** [comment]
Are you maybe requesting the gzipped file? https://files.rcsb.org/download/4HHB.cif works, https://files.rcsb.org/download/4HHB.cif.gz doesn't.

**Comment by MungShu71** [comment]
```
{% include "base.html" %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Molecular Viewer</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/molstar/build/viewer/molstar.css"
    />
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/molstar/build/viewer/molstar.js"
    ></script>
  </head>

  <body>
    <p>Name: {{name}}</p>
    <a href="{% url 'file' file=cif_file%}">cif_file</a>
    <div id="app"></div>
    <style>
      #app {
        position: absolute;
        width: 598px;
        height: 670px;
      }
    </style>

    <script type="text/javascript">
      molstar.Viewer.create("app", {
        layoutIsExpanded: false,
        layoutShowControls: false,
        layoutShowRemoteState: false,
        layoutShowSequence: true,
        layoutShowLog: false,
        layoutShowLeftPanel: true,
        viewportShowExpand: true,
        viewportShowSelectionMode: false,
        viewportShowAnimation: false,
        pdbProvider: "rcsb",
        emdbProvider: "rcsb",
      }).then((viewer) => {
        const path = "http://127.0.0.1:8000/{{ cif_file }}";
        viewer.loadStructureFromUrl((url = path), (format = "cif"));
      });
    </script>
  </body>
</html>

```
Here is my code.

**Comment by dsehnal** [comment]
Have you tried downloading that file via your link and loading it in https://molstar.org/viewer?

**Comment by MungShu71** [comment]
File opens without issue in the viewer.

**Comment by dsehnal** [comment]
> ` viewer.loadStructureFromUrl((url = path), (format = "cif"));`

Try `format = "mmcif"`

**Comment by MungShu71** [comment]
Still get this error.
![image](https://github.com/user-attachments/assets/3922e950-f641-454a-a180-5b791d7624c4)

**Comment by dsehnal** [comment]
Last advice I can give you is that the path that you pass to the `<a href="{% url 'file' file=cif_file%}">cif_file</a>` is different from `const path = "http://127.0.0.1:8000/{{ cif_file }}";`
