### ISSUE TITLE
Session file groupedUnits

### ISSUE THREAD

**Issue by nezix** [molstar/molstar#1243]
Hello,

I am reading data from a session file (.molx), especially trying to extract selections and representations.

Bundle selections are stored as `ms-plugin.structure-component` transformers with elements composed of a "groupedUnits", either a "set" or "ranges".

My issue is that I don't have a clear way to translate these sets and ranges of atom indices to the actual file atom indices.

- Example: If I create a custom selection containing the surrounding of a ligand and save that to a .molx file, then extracting the state.json file from the .molx, this custom selection will be composed of 2 (or more) elements, one for the groupedUnits 0 (probably polymer), one of the groupedUnits 1 (maybe ligand, or water, or sugar ?) and potentially much more depending on the content of the file.

**Comment by dsehnal** [comment]
And your goal is to extract these for use in another software?

**Comment by nezix** [comment]
Indeed, I am interested in extracting the current view to external softwares.
Ideally something close to MVS but Mol* does not export a session to the mvsj format yet, right ?

**Comment by dsehnal** [comment]
> Indeed, I am interested in extracting the current view to external softwares.

I think this will be quite difficult to do directly, because these are indices into internal Mol* representation of the structures and do not directly correspond to atoms.

I think you essentially have two options:

- If you can run nodejs on you backend, I would recommend just reading the state using Mol* code and converting the selection to something you can parse downstream. 
- Add an extenstion to Mol* that exports the data in a format your app will understand.

> Ideally something close to MVS but Mol* does not export a session to the mvsj format yet, right ?
MVS is a limited subset of the Mol* state. We do have some plans for MVS export directly from Mol* though.

**Comment by nezix** [comment]
I figured that it would be hard to reproduce all Mol* logic on selection and coloring so I think I will go for the 2nd option.
Do you happen to have an example of a code that gets file based indices from a component selection ?
Thanks for your replies !

**Comment by dsehnal** [comment]
```ts
const indices: number[] = [];
StructureElement.Loci.forEachLocation(loci, loc => {
    indices.push(StructureProperties.atom.sourceIndex(loc));
});
```

**Comment by nezix** [comment]
Thank you !

**Comment by nezix** [comment]
@dsehnal Sorry to bother you again, I have a hard time exporting colors for each atom.
Especially, I struggle to reliably apply the color scheme and get a per atom color.
Could you please provide a brief example of how to achieve this if that's not too much code ?

**Comment by dsehnal** [comment]
In most cases, mol* doesn't store the color for each element explicitly. This is for performance and memory management reasons.

To do this, you need to obtain a separate instance of the color theme in question and iterate through every location you want to get the color for. Look at the code that creates representations how to do that (starting at StructureRepresentation3D transform should work).

**Comment by nezix** [comment]
I managed to do most of the work but there still is an issue with getting colors for the element-symbol color scheme.
It looks like this is not retrieving the correct colors:

```js
const structure = plugin.managers.structure.component.currentStructures[0];
const cell = plugin.state.data.select(structure.properties.cell.transform.ref)[0];
const realStructure = (cell.obj as PluginStateObject.Molecule.Structure).data;

const rep = structure.components[0].representations[0];
const colorThemeParams = rep.cell.params.values.colorTheme.params;

Structure.eachAtomicHierarchyElement(realStructure , {
                                atom: loc => console.log(ElementSymbolColorTheme(loc, colorThemeParams).color(loc, false))
                            });
```
Is this the correct way to get colors for each atom of the component ?

**Comment by dsehnal** [comment]
Try this:

You are not passing in correct values. `cell.params` is the definition of the parameters used to build the UI, you need `cell.transform.params`.

This should work: 

```ts
const themeParams = repr.cell.transform.params?.colorTheme.params;
const theme = ElementSymbolColorTheme({ structure: realStructure }, themeParams);
Structure.eachAtomicHierarchyElement(realStructure , {
  atom: loc => console.log(theme.color(loc, false))
});
```

If you want to fully automate the theme creation:

```ts
const theme = plugin.representation.structure.themes.colorThemeRegistry.create(
    colorTheme?.name,
    { structure: realStructure }
    colorTheme?.params
);
```

**Comment by nezix** [comment]
Thanks again, I will add a doc page to do a summary !

I am almost there, I am clearly not fluent in javascript/typescript. It looks like the color property does not exist when creating a ColorThemeLocation<any>, how would I get a Color from that ?

```js
const colorThemeName = rep.cell.params?.values.colorTheme.name;
const colorThemeParams = rep.cell.transform.params?.colorTheme.params;
let colors = Array<Color>();

const theme = plugin.representation.structure.themes.colorThemeRegistry.create(
    colorThemeName,
    {structure: realStructure},
    colorThemeParams
);

Structure.eachAtomicHierarchyElement(realStructure, {
    atom: loc => colors.push(theme.color(loc, false))
});
```

**Comment by dsehnal** [comment]
Or just `ColorTheme<any>` could work, hopefully :)
