### ISSUE TITLE
PDB TER `Sequence` Panel lost some residues.

### ISSUE THREAD

**Issue by QDMarkMan** [molstar/molstar#1245]
Hi, here is my issue description:

### 1. Description
If my PDB file contains another TER in file content, the  Sequence panel just render from start to the first `TER` flag, as shown below:
![image](https://github.com/user-attachments/assets/d9c863ce-7875-414e-8186-a9abc1fb25cc)
![image](https://github.com/user-attachments/assets/877a3b09-e2a6-45a6-9712-18c5fc0f96a2)

If i remove the TER line above. The `Sequence` will render the right residues.
![image](https://github.com/user-attachments/assets/8f2d70cb-6202-4340-99b1-9cdadd3aead2)

The TER line was added by other software.

### 2. Environment
molstar: [The latest version]

**Comment by dsehnal** [comment]
I think when loaded from PDB format, we treat TER as "next chain" since in mmCIF I believe these would have different `label_asym_id`s.

The reset of the sequence should be when you select a different chain in the top menu:

![image](https://github.com/user-attachments/assets/2d27c484-4c00-4a4c-b0e6-aa7fe1f36d06)

**Comment by QDMarkMan** [comment]
Actually, I tried to find residues from other chains, but I’m still having trouble.
![image](https://github.com/user-attachments/assets/92c1c8ff-a8af-43cb-80b4-dfa389563f14)
![image](https://github.com/user-attachments/assets/0548a0b6-2bdb-4b1e-b0ae-221b4ef3fc08)
The residues in the A_1 chain appear to be non-interactive. Are there any other methods or approaches to identify these residues?

**Comment by arose** [comment]
Please share your PDB file so we can have a closer look.

**Comment by QDMarkMan** [comment]
Thanks! Here is my pdb attach file. 
[8TB6_prepared.pdb.txt](https://github.com/user-attachments/files/16791316/8TB6_prepared.pdb.txt)

**Comment by arose** [comment]
@QDMarkMan, please have a look at #1249.

Strictly following the PDB format you should either have no TER record or a different chain id. Anyway, we try to support it.

**Comment by QDMarkMan** [comment]
Got it, Thanks for the support in handling this!
