### ISSUE TITLE
Add representation without moving camera

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#1246]
I switch between representations using `canvas.clear` followed by `canvas.add(repr)` where `repr` is newly constructed. This somehow causes the camera to move, similar to a `canvas.requestCameraReset`. This is a bit untransparent from a programmers perspective. Can this behavior be disabled?

**Comment by dsehnal** [comment]
`plugin.canvas3d?.setProps({ camera: { manualReset: true } });`

**Comment by bergwerf** [comment]
Thanks! One problem: the camera snapshot radius is not updated, causing clipping in representations that take up more space (such as spacefill). My solution was to manually pass the boundingSphere.radius to the camera state.
