### ISSUE TITLE
Sequence Panel: Cursor & Contrast of Unmodeled Regions

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#1248]
It can be difficult to recognize unmodeled regions in the Sequence Panel: https://molstar.org/viewer/?pdb=7YNT.

What do you think about changing the cursor for these position from `pointer` to `default` as these positions can't be interacted with?

It might also be beneficial to increase the contrast between modeled and unmodeled sequence positions. However, that depends on the rest of the theme (and might be more pronounced for rcsb-molstar).

I can adjust the contrast in rcsb-molstar but the cursor change seems relevant for all Mol* instances.

![seq](https://github.com/user-attachments/assets/60bd4e6f-684e-49ab-9898-d1e119ad3d99)

**Comment by arose** [comment]
Both points sound like nice improvement!
