### ISSUE TITLE
Interactions: Charge and H donor perceived on neutral Nitrogen when residue is protonated

### ISSUE THREAD

**Issue by papillot** [molstar/molstar#1257]
I've noticed the following interactions with the PDB structure 6KNR that has all hydrogens defined on its ligand DL9:
notice the highlighted Nitrogen which has 3 covalent single bonds (hence should be neutral) but participates in a Hbond and a cation-π interaction.
<img width="789" alt="image" src="https://github.com/user-attachments/assets/9e8ed5b8-ef48-4d0c-9021-2e6795a5e939">
https://www.rcsb.org/3d-view/6KNR?preset=ligandInteraction&label_asym_id=C

The mmCIF does not specify formal charge for any of the atoms (symbol `?`)
The ValenceModel seems to infer that the Nitrogen highlighted in the screen capture has a positive charge and is a putative hydrogen donor.
Can we improve this based on the protonation that is fully specified for this residue?
(I'd be happy to contribute a PR)

**Comment by arose** [comment]
The valence model has options for when to assign charge/H. The complication is that only part of the structure has H/charge given. Maybe add an to check if H are given for  each unit?

**Comment by arose** [comment]
> Maybe add an to check if H are given for each unit?

@papillot would you be interested inn trying this?

**Comment by papillot** [comment]
Fixed
