### ISSUE TITLE
WebGPU for molstar?

### ISSUE THREAD

**Issue by RodenLuo** [molstar/molstar#1259]
Hi, 

Is there any plan to use WebGPU? I do see the projection to the future in https://github.com/molstar/molstar/issues/1077. 

Thanks,
Roden

**Comment by arose** [comment]
It is planned, yes. Why/what for would you like to see WebGPU support?

**Comment by RodenLuo** [comment]
To use compute shader for general computing purposes.

**Comment by arose** [comment]
If the general computing purposes do not produce something that immediately needs to be rendered (like a surface) you can also just use WebGPU additionally.

**Comment by RodenLuo** [comment]
Will explore the possibilities. Thanks!
