### ISSUE TITLE
customText does not override label text in loci/label 

### ISSUE THREAD

**Issue by neksa** [molstar/molstar#126]
`customText` overrides label text in distance, angle and dihedrals labels. But not in simple "select one" labels. Thus customText property is ignored in loci/label.ts. Behavior should be similar between label types.

https://github.com/molstar/molstar/blob/410655052fa9b93c2d205d3528bc36914753dd4d/src/mol-repr/shape/loci/label.ts#L63

**Comment by dsehnal** [comment]
Thanks for finding this out. Should be fixed in b9864fb.

Do you need this in NPM package right now?

**Comment by neksa** [comment]
Thanks. No, I don't, whenever it gets there.
