### ISSUE TITLE
Show structure as cartoon and Gaussian Surface 

### ISSUE THREAD

**Issue by nataliarosa9** [molstar/molstar#1266]
How can I show the structure as a cartoon and Gaussian surface, similar to the example below?

![Screenshot 2024-09-19 111345](https://github.com/user-attachments/assets/3c3ce5d9-dfed-4f92-a7c4-e3f46491facb)

![Screenshot 2024-09-19 111330](https://github.com/user-attachments/assets/fbc3f405-a365-4cbc-814e-338ea029d592)

![immagine](https://github.com/user-attachments/assets/96308af1-abf3-4b9f-9963-16934176bdbb)

 

        import React, { useEffect, useRef, useMemo } from 'react';
        import { createPluginUI } from 'molstar/lib/mol-plugin-ui';
        import { ColorNames } from 'molstar/lib/mol-util/color/names';
        import 'molstar/lib/mol-plugin-ui/skin/light.scss';
        import { renderReact18 } from 'molstar/lib/mol-plugin-ui/react18';
        import { PluginCommands } from 'molstar/lib/mol-plugin/commands';
        import { Script } from 'molstar/lib/mol-script/script';
        import { StructureSelection } from 'molstar/lib/mol-model/structure/query';
        import { MolScriptBuilder as MS, MolScriptBuilder } from 'molstar/lib/mol-script/language/builder';
        import { StateTransforms } from 'molstar/lib/mol-plugin-state/transforms';
        import { createStructureRepresentationParams } from 'molstar/lib/mol-plugin-state/helpers/structure-representation-params';
        import { Color } from "molstar/lib/mol-util/color";
        import { setStructureOverpaint } from 'molstar/lib/mol-plugin-state/helpers/structure-overpaint'
        
        
        const MolstarViewer = ({ pdbId }) => {
          const viewerRef = useRef(null);
          const pluginInstanceRef = useRef(null);
        
          const initMolstar = useMemo(() => async () => {
            if (viewerRef.current && !pluginInstanceRef.current) {
              const plugin = await createPluginUI({
                target: viewerRef.current,
                layoutIsExpanded: false,
                layoutShowControls: false,
                layoutShowRemoteState: false,
                layoutShowSequence: true,
                layoutShowLog: false,
                layoutShowLeftPanel: false,
                viewportShowExpand: false,
                viewportShowSelectionMode: false,
                viewportShowAnimation: false,
                pdbProvider: 'rcsb',
                backgroundColor: 'white',
                render: renderReact18,
              });
              pluginInstanceRef.current = plugin;
        
              try {
                const data = await pluginInstanceRef.current.builders.data.download(
                  { url: `https://files.rcsb.org/download/${pdbId}.cif` },
                  { state: { isGhost: true } }
                );
                const trajectory = await pluginInstanceRef.current.builders.structure.parseTrajectory(data, 'mmcif');
                const structure = await pluginInstanceRef.current.builders.structure.hierarchy.applyPreset(
                  trajectory,
                  'default'
                  , {
                    showUnitcell: false,
                    representationPreset: 'auto',
                }
                );
        
             } catch (error) {
                console.error('Failed to load the PDB structure:', error);
              }
                }
              }, [pdbId]);
        
          useEffect(() => {
            initMolstar();
        
            return () => {
              if (pluginInstanceRef.current) {
                pluginInstanceRef.current.dispose();
                pluginInstanceRef.current = null;
              }
            };
          }, [initMolstar]);
        
          return <div key={pdbId} ref={viewerRef} style={{ width: '100%', height: '100%' }} />;
        };
        
        export default MolstarViewer;

**Comment by nataliarosa9** [comment]
How can I display both cartoon and gaussian surfaces? I managed to display the structure as a gaussian surface, but I'm unable to display both simultaneously.
   
![immagine](https://github.com/user-attachments/assets/720a3b76-04bd-4201-88fd-e6bb5a3d9dd7)


              // Create and apply custom representation
                const reprParamsStructureResetColor = createStructureRepresentationParams(plugin, undefined, {
                   type: "cartoon",
                   color: 'uniform',
                   colorParams: { value: ColorNames.green }
                });
    
                const updateTheme = plugin
                .build()
                .to(cartoon)
                .update(reprParamsStructureResetColor);
    
                await updateTheme.commit();
    
                 // Create and apply custom representation
                const reprParamsStructureGaussian = createStructureRepresentationParams(plugin, undefined, {
                   type: "gaussian-surface",
                   color: 'uniform',
                   alpha: 0.5
                });
    
                const updateStructure = plugin
                .build()
                .to(cartoon)
                .update(reprParamsStructureGaussian);
    
                await updateStructure.commit();
    
                // Set script language
                const language = 'mol-script';
    
                // Create params object
                const params = {
                    layers: []
                };
    
                // Add layers to params object
                params.layers.push({
                        script: Script(
                             `(sel.atom.atom-groups
                                 :chain-test (= atom.auth_asym_id A )
                              )`,
                            language
                        ),
                        value: 0.5
                });
    
                const updateTransparency = plugin.build();
                updateTransparency
                      .to(cartoon)
                      .apply(StateTransforms.Representation.TransparencyStructureRepresentation3DFromScript, params);
    
                await updateTransparency.commit();

**Comment by dsehnal** [comment]
For example:

```ts
await plugin.builders.structure.representation.addRepresentation(
    preset?.representation.components.polymer,
    { type: 'cartoon' }
)
```
