### ISSUE TITLE
Removing models/trajectory from the state tree

### ISSUE THREAD

**Issue by ThijsMaas** [molstar/molstar#1268]
Hi!

I have the plugin setup with some external action that can load pdbs into the plugin using 

```ts
const data = await plugin.builders.data.download({ url: pdbUrl });
const trajectory = await plugin.builders.structure.parseTrajectory(data, 'pdb');
const model = await plugin.builders.structure.hierarchy.applyPreset(trajectory, 'default');
```

Now I would also like to setup an action that can remove models/trajectories one by one from the state, similar to how this would be done in the plugin UI when you click the remove button in the state tree. With some digging I found a way to do it as follows:
```ts
await PluginCommands.State.RemoveObject(plugin, {
    state: plugin.state.data,
    ref: model.model.ref,
    removeParentGhosts: true,
});
```

This works but I also see this uncaught promise error log and I'm not sure where is comes from:
```
transient.js:273 Uncaught (in promise) Error: Node 'h_hDQJ6FmK74AqLMwbimGw' is not present in the tree.
    at ensurePresent (transient.js:273:1)
    at TransientTree.setParams (transient.js:137:1)
    at buildTree (builder.js:25:1)
    at Root.getTree (builder.js:73:1)
    at State.updateTreeAndCreateCtx (state.js:249:1)
    at State._updateTree (state.js:233:1)
    at Impl.f (state.js:195:1)
    at async execute (observable.js:68:1)
    at async TaskManager.run (task-manager.js:65:1)
```

Any clue how to prevent/catch this, or is there a better way to do what I'm after?

**Comment by dsehnal** [comment]
I just tested your exact code and cant reproduce your issue.

Aren't you calling the remove object multiple times or passing in wrong value for model for example?

This is the code I tested:

```ts
async loadAndDeleteModel() {
    const plugin = this.plugin;
    const url = 'https://www.ebi.ac.uk/pdbe/entry-files/download/1tqn_updated.cif';
    const data = await plugin.builders.data.download({ url });
    const trajectory = await plugin.builders.structure.parseTrajectory(data, 'mmcif');
    const model = await plugin.builders.structure.hierarchy.applyPreset(trajectory, 'default');

    await PluginCommands.State.RemoveObject(plugin, {
        state: plugin.state.data,
        ref: model?.model.ref!,
        removeParentGhosts: true,
    });

    // await plugin.build().delete(model?.model.ref!).commit();
}
```

**Comment by ThijsMaas** [comment]
Thanks for the input! The issue was caused by a subsequent `updateRepresentationsTheme` on the current structures in the state, so a timing issue between the deletion of the structure and the resetting of the theme of all structures. 

PS I also found out I need to delete the `data.ref` in the above example to remove the whole structure's tree.
