### ISSUE TITLE
Noticeable aliasing with v4.7.0

### ISSUE THREAD

**Issue by papillot** [molstar/molstar#1279]
I've just upgraded to v4.7.0 (released yesterday) from v4.6.0
I find the rendering to not be as sharp looking as before.
I'm using a high pixel density screen `window.devicePixelRatio === 2`

Here is a detail screenshot of what I can see with 4.7.0. Notice the aliasing on the white trace boundaries.
<img width="45" alt="Screenshot 2024-09-30 at 10 43 20" src="https://github.com/user-attachments/assets/c490c8bb-cf62-45a9-ae88-7952b2fceff9">

Here is what it looked like with 4.6
<img width="49" alt="image" src="https://github.com/user-attachments/assets/c7d2ea2e-ee69-4bd3-a94d-cde5009af602">

**Comment by papillot** [comment]
I see that this may be due to the new `resolutionMode` param

**Comment by arose** [comment]
How about we add an "auto" mode that checks if it is a mobile device or not? Use scaled on mobile and native elsewhere?

**Comment by dsehnal** [comment]
Yeah, `auto` sounds good too.
