### ISSUE TITLE
How To: Create components from thir party apps

### ISSUE THREAD

**Issue by bioinsilico** [molstar/molstar#128]
I am trying to create multiple components from a third party application. Is the best way to do that through "plugin.managers.structure.component.add" method ? 

In this case, I am having troubles when the new components are created after a new structure is loaded in the panel. If I don't setup  a time out the new components are not created.

Thanks a lot for your help!

**Comment by arose** [comment]
Do you `await` the call to `plugin.managers.structure.component.add`?

**Comment by bioinsilico** [comment]
Yes, this is the function that is trying to build the component. 

private async createComponentFromChain(componentId: string, structureRef: StructureRef, asymId: string, representationType: StructureRepresentationRegistry.BuiltIn): Promise<void>{
        const selection: StructureSelectionQuery = StructureSelectionQuery(
            'innerQuery_' + Math.random().toString(36).substr(2),
            MolScriptBuilder.struct.generator.atomGroups({
                'chain-test': MolScriptBuilder.core.rel.eq([asymId, MolScriptBuilder.ammp('label_asym_id')])
            }));
        await this.plugin.managers.structure.component.add({
            selection: selection,
            options: {checkExisting: false, label: componentId},
            representation: representationType,
        }, [structureRef]);
    }

**Comment by bioinsilico** [comment]
@arose My bad, my own code was deleting the components :-/ The "component.add" method works as expected. Thanks for your fast response!
