### ISSUE TITLE
Transparency Blend & Wboit issue with Fog off and transparent background

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1284]
I have found an issue using blend or wboit modes (dpoit is working fine in this case). With transparent background and fog off there are blending issues (colors are lighter than normal. Just compare with the dpoit version and you'll notice it). here is a test 
[state.molx](https://github.com/user-attachments/files/17243314/test-7.molx.txt) to reproduce.

**Wboit**
![image](https://github.com/user-attachments/assets/302f8455-7a9b-4bb5-b3e0-8f77ac85b094)

**Dpoit**
![image](https://github.com/user-attachments/assets/339226a0-ca45-4963-b24b-b2d98956a5f3)

**Comment by arose** [comment]
Should be fixed with e1d92a58be689c296c4608bf207b2fd7923b26ed
