### ISSUE TITLE
Issue with backfaces always visible using blend transparency on impostor spheres and cylinders

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1285]
Wboit and Dpoit are working fine, the issue is present only using blend transparency. Here a test [state.molx](https://github.com/user-attachments/files/17243396/test-6.molx.txt) to reproduce.

**Blend**
![image](https://github.com/user-attachments/assets/574987aa-4cd3-44b1-b9d1-bb474ba3eb4c)

**Wboit**
![image](https://github.com/user-attachments/assets/b8d4c9cc-d0eb-4c33-8795-a5565574b219)

**Comment by arose** [comment]
This is only for spheres with `solidInterior` on, right?

**Comment by giagitom** [comment]
Yes, I observed this only on impostor spehres. Other representations are working fine

**Comment by arose** [comment]
So the question is, what is the "right" behavior. How to interpret "solid" in the context of backfaces... Should blend work like wboit & dpoit or the other way around
