### ISSUE TITLE
Volume blending issues on transparent background and fog on / off

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1286]
There are issues blending volume on transparent background. All transparency modes are affected.

 - When **fog is ON** only dpoit mode presents the issue.
 - When **fog is OFF** all modes are affected. 

here a test [state.molx](https://github.com/user-attachments/files/17244174/test-5.molx.txt) to reproduce

![image](https://github.com/user-attachments/assets/c3e5d80b-e28b-4770-8daa-63644cbd96ce)

**Comment by arose** [comment]
Should be fixed with 05ff705c254e1d8befc90e850408a8bfa71b67de
