### ISSUE TITLE
Issues with extensions.depthTexture = null

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1287]
I tried to force  ```extensions.depthTexture = null``` for testing purpouses and noticed issues with all postprocessing effects. 

![image](https://github.com/user-attachments/assets/e6fd3545-8069-486b-a2c0-fec67bc6e4d3)

**Comment by arose** [comment]
Fixed with d2f354d949f95a40672f46a517415c6cb035e461.

Not really a problem because it would only happen if you disable depthTexture in webgl2 where it is always supported.

But good for testing to have it working.
