### ISSUE TITLE
Draw a pocket box

### ISSUE THREAD

**Issue by voIeon** [molstar/molstar#1296]
I want draw a pocket box. need help.
`       
 async function init() {

const plugin = await molstar.createPlugin(document.getElementById('app'));

await plugin.loadStructureFromUrl('https://files.rcsb.org/download/1cbs.pdb');

const box = {
    min: { x: 10, y: 20, z: 30 },  
    max: { x: 40, y: 50, z: 60 }  
};

const center = {
    x: (box.min.x + box.max.x) / 2,
    y: (box.min.y + box.max.y) / 2,
    z: (box.min.z + box.max.z) / 2
};
const size = {
    x: box.max.x - box.min.x,
    y: box.max.y - box.min.y,
    z: box.max.z - box.min.z
};

plugin.builders.structure.addRepresentation({
    type: 'shape',
    params: {
        shape: plugin.createShape({
            geometry: 'box',          
            color: 'red',             
            scale: 1.0,               
            position: center,         
            size: size                
        })
    }
});
}

init();
`

**Comment by dsehnal** [comment]
Maybe https://github.com/molstar/molstar/issues/1158 can help?
