### ISSUE TITLE
How to only show snapshot itself?

### ISSUE THREAD

**Issue by QY0831** [molstar/molstar#1301]
I am using `molstar.Viewer.create` to display `molx` file on website:
```
<script>
    document.addEventListener('DOMContentLoaded', function () {
        molstar.Viewer.create('app', 
        {
            "layoutShowLog":false,
            "layoutIsExpanded":false,
            "layoutShowSequence":false,
            "layoutShowControls":false,
            "layoutShowRemoteState":false,
            "layoutControlsDisplay":false,
            "layoutShowLeftPanel":false,
            "layoutShowRemoteState":false,
            "collapseLeftPanel": true,
            "collapseRightPanel": true,

            "viewportShowAnimation":false,
            "viewportShowSelectionMode":false,
            "viewportShowExpand":false,
            "viewportShowSettings":false,
            "viewportShowSelectionMode:":false,
            "viewportShowTrajectoryControls":false,

        }).then(async (viewer) => 
        {
            await viewer.loadSnapshotFromUrl("test.molx", 'molx');
            viewer.plugin.canvas3d.requestCameraReset()
        }).then(() => {
            console.log('Viewer loaded');
        });
    });
</script>
```
using code above, it can be shown as:
<img width="435" alt="image" src="https://github.com/user-attachments/assets/294d9b7d-dde2-457b-b1fd-de841ad2aa53">

but I want to hide everything outside the movie, like:
<img width="279" alt="image" src="https://github.com/user-attachments/assets/b205e3f7-2dd3-485b-a814-37ef37c19978">

No background color, no buttons, no icons... but still can interact with the mol. Is there a way to do this? Thanks!

**Comment by dsehnal** [comment]
- For hiding the remaining UI elements you use CSS. Just inspect the elements that remain in your view and the include `display: none` for that class (you can namespace it via `msp-plugin.class-name {...}`
- To hide the axes you can call `viewer.plugin.canvas3d.setProps` near where you reset the camera. I don't remember the name of the prop from the to of my head but it should be easy to find.

----------

If you want to get more fancy, you can completely customize all aspects of the UI, but that would require building the scrips with a bundler like webpack or esbuild.

**Comment by QY0831** [comment]
It works, thank you!
