### ISSUE TITLE
Labels look odd in Linux with nvidia GPU

### ISSUE THREAD

**Issue by josemduarte** [molstar/molstar#1306]
Not sure if this is reproducible in other Linux (without nvidia) or not. But I can see it happening consistently in my box (Chrome 130.0.6723.58, Ubuntu 22.04, Nvidia RTX2060, driver version 535.183.01).

Examples

- The ligand summary page at rcsb.org (e.g. https://www.rcsb.org/ligand/HEM) with labels enabled:
![Screenshot from 2024-10-24 16-01-50](https://github.com/user-attachments/assets/9024ff1c-64ee-4c03-ae22-5a632ec56340)

- Creating a label from the molstar.org app:
![Screenshot from 2024-10-24 16-03-19](https://github.com/user-attachments/assets/bd34177a-f810-49dc-a47b-def931ac44f5)

- Mesoscale explorer, here the effect is a bit different with an all-black effect:
![Screenshot from 2024-10-24 16-04-48](https://github.com/user-attachments/assets/8bae56b4-4b9c-4f93-a776-d6d690b9479b)

**Comment by giagitom** [comment]
same issue https://github.com/molstar/molstar/issues/1208

**Comment by dsehnal** [comment]
Can you try changing transparency to "Blended" in the bottom left options?

<img width="337" alt="image" src="https://github.com/user-attachments/assets/276b6c45-fdc1-450f-86fa-9558ecfa8224">

**Comment by giagitom** [comment]
>Can you try changing transparency to "Blended" in the bottom left options in https://molstar.org/viewer/ ?

Hi @dsehnal,

I tried this too and didn't see any change.

**Comment by josemduarte** [comment]
> Can you try changing transparency to "Blended" in the bottom left options in https://molstar.org/viewer/ ?

Same result here: no change when switching to "Blended"

**Comment by arose** [comment]
Does changing

`float w = clamp(smoothness * (abs(dFdx(vTexCoord.x)) + abs(dFdy(vTexCoord.y))), 0.0, 0.5);`

to

`float w = 0.0;`

in src\mol-gl\shader\text.frag.ts fix it?

**Comment by giagitom** [comment]
> float w = 0.0;
>
>in src\mol-gl\shader\text.frag.ts fix it?

Not on my side. Same as before

**Comment by giagitom** [comment]
I have found that if I change this part

```if (a < 0.5) discard;```

to this

```if (sdf < 0.5) discard;```

it works fine on my side

![image](https://github.com/user-attachments/assets/b020a1bc-ea0d-4fdc-8219-f80691a73a3a)
