### ISSUE TITLE
Set coloring b-factor after local files read

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [molstar/molstar#131]
Hi. Mol* is awesome...

I would like to include Mol* in one of my recent projects and I need to implement something simple. However, since I just started typescript/javascript and Mol* have not `API` documentation, it is very difficult.

I know that to read a local file there are two variants:
`loadStructureFromUrl`
`loadStructureFromData`

I would like to know if in both cases a PDB file with multiple models is loaded as a Trajectory? Once I do, it appears as models but I can't animate it as a trajectory.

After loading the structure, how can I set coloring by b-factor (Uncertainty/Disorder)? Do I need to create a new representation as described in [issue #68](https://github.com/molstar/molstar/issues/68)?

Thanks in advance
Mario

**Comment by dsehnal** [comment]
Hi Mario,

Unfortunately, loading the structure using ``loadStructureFrom*`` makes it kind of hard to customize the loaded data by code.

#68 is a good start which would allow you to create your representation directly with the b-factor coloring.

```ts
builder.buildRepresentation(update, components.polymer, { type: 'gaussian-surface', typeParams: { alpha: 0.51 } }, { tag: 'polymer' });
...
```

can take as argument ``color: 'uncertainty'`` in the 3rd param (the object with ``type``). That way you decide which part of the representation should be colored and how.

Also you can store the references from the builder for future edits of the visuals.

--------------

As far as replaying animation

```ts
this.plugin.managers.animation.play(AnimateModelIndex, {
  mode: { name: 'loop', params: { } },
  duration: { name: 'fixed', params: { durationInS: 5 }  }
});

...

await this.plugin.managers.animation.stop();
```

should do the trick.

------------

Let me know if you need more help.

David

**Comment by Valdes-Tresanco-MS** [comment]
Hi David.
Thank you very much, I will try to do it with this information.
Best regards
