### ISSUE TITLE
CIF Rep bonds removed when ignore hydrogens is toggled

### ISSUE THREAD

**Issue by rjdirisio** [molstar/molstar#1315]
Hello, I am experiencing something going wrong with ligand reps derived from a CIF when one toggles the ignoreHydrogens to be on. 

I am attaching a minimal example: 

Attached is a CIF (in the form of a .txt, since GitHub doesn't like attaching `.cif` files) that, when clicked and dragged into the viewer (https://molstar.org/viewer/) has bonds in its default rep, but once I toggle the ignore hydrogens, the bonds go away. In addition, toggling non-polar seems to be working, but there just aren't bonds shown on the rep.

Any idea what could be happening here? Is there something going wrong with bond perception?

Default settings
![image](https://github.com/user-attachments/assets/875cf004-9f33-4104-9656-47fba88828c0)

Ignore Hydrogens is On
![image](https://github.com/user-attachments/assets/5926fe51-6413-4889-8c63-f9aed3acbba8)

Non-Polar Hydrogens only
![image](https://github.com/user-attachments/assets/133f8eea-93eb-4642-907b-51d52197276c)

[example_cif.txt](https://github.com/user-attachments/files/17559730/example_cif.txt)

**Comment by arose** [comment]
Definitely a bug, will need to investigate.

**Comment by arose** [comment]
Should be fixed with 05a87fded941e82b12b07fa24aab6ecd4b4b281f, please test, thanks!

**Comment by rjdirisio** [comment]
It's working as expected now. Thanks!
