### ISSUE TITLE
Turn off the surroundings in the structure 

### ISSUE THREAD

**Issue by nataliarosa9** [molstar/molstar#1317]
How can I turn off the surroundings in the structure and keep it in the sequence panel? 

    const selection = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
    "chain-test": Q.core.rel.eq([MolScriptBuilder.struct.atomProperty.macromolecular.auth_asym_id(), "A"]),
    'residue-test': Q.core.set.has([Q.set(...positions), Q.ammp('auth_seq_id')])}), dta);

     const loci = StructureSelection.toLociWithSourceUnits(selection);

     plugin.managers.interactivity.lociSelects.select({ loci });

   
![immagine](https://github.com/user-attachments/assets/b1818ad5-f4bf-4a30-80a3-f3ed34ea4741)

**Comment by dsehnal** [comment]
You would have to write your own version of the sequence panel that shows the selection.

Although this requirement keeps popping up from time to time, so might have a look into having a more standardized way of doing this supported out of the box.
