### ISSUE TITLE
WebGL fence sync already deleted

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#1318]
While trying to upgrade from 4.5.0 to 4.8.0 I encountered an issue: no rendering.

My JS console reports the following: WebGL warning: getSyncParameter: Object `sync` is already deleted.

I dug through the diffs, and found something about a fence sync addition in the canvas3d render routine: https://github.com/molstar/molstar/compare/v4.5.0...v4.8.0#diff-a387ffcb1f053ad2d4ad3f869712109e398311a2846d9eb2a5db831956356adfR514

I have no idea what the fence sync is used for, but I am under the impression that the clear and dispose functions of Canvas3D (in particular clear, since that is not a final operation) should set fenceSync back to null after deleting it, otherwise the rendering loop will be blocked forever.

EDIT: I was able to 'fix' the issue by removing all my calls to `Canvas3D.clear`. The fix should be very simple: ALWAYS set fenceSync = null after gl.deleteSync.

**Comment by arose** [comment]
> The fix should be very simple: ALWAYS set fenceSync = null after gl.deleteSync.

Indeed, would you mind doing a PR that does so for the two instances in `Canvas3D`?

**Comment by bergwerf** [comment]
Thanks!
