### ISSUE TITLE
Is it possible to create a representation with opacity (`alpha`) varying by residue?

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#1319]
As always, mighty thanks for the software. 

Given: a list an `Array<[auth_asym_id, auth_seq_id, some_score]>` where `auth_asym_id` and `auth_seq_id` uniquely specify a residue and `score` is any value betwen 0 and 1 that i provide as parameter. 

As the questions says, i'd like to be able to creaate a representation of a number of residues where each residue's individual cartoon has `alpha`==`score`. Is this possible without creating a separate "component" for each specified residue?

I tried going the way of `ColorTheme` first (according to #1307) but unfortunately i'm not able to figure out how to squeeze opacity (`alpha`) in there (if it is possible)..:

<details>

<summary>My custom `ColorTheme` code (doesn't achieve varying opacity)</summary>

```typescript
export interface ScoredBsite {
  // auth_asym_id---vvv..... ..residue_id--vvv...........vvv---the bespoke"score"
  [chain_auth_asym_id: string]: { [auth_seq_id: number]: number }
}

export const VaryingResidueColorThemeParams = {
    bsite: PD.Value<ScoredBsite>({}),
};

export function VaryingResidueTheme(
    ctx: ThemeDataContext,
    props: PD.Values<VaryingResidueColorThemeParams>
): ColorTheme<VaryingResidueColorThemeParams> {

    const bsite = props.bsite
    const color: LocationColor = (location: Location): Color => {
        // return ColorNames.red
        if (StructureElement.Location.is(location)) {
            const auth_seq_id = StructureProperties.residue.auth_seq_id(location)
            const auth_asym_id = StructureProperties.chain.auth_asym_id(location)

            if (auth_asym_id in Object.keys(bsite) && auth_seq_id in Object.keys(bsite[auth_asym_id])) {
                return ColorNames.blue
            }
            else {
                return ColorNames.gray;
            }
        }
        else{
            return ColorNames.gray
        }
    };

    return {
        factory: VaryingResidueTheme,
        granularity: 'group',
        
        // It would have been the most convenient if there was something like 
        // `opacity: (Location) => PD.Value<number>` like there is for color here
        color: color,
        props: props,
        description: 'Per atom color color theme',
    };
}
``` 

And i use it by just passing the specification of my "scored" residues:
```typescript
 await ctx?.applyBsiteColors(composite_bsite.data as ScoredBsite)
 ...
 // select the residues the usual Molscript way..
         const bsiteSel = group1.apply(StateTransforms.Model.StructureSelectionFromExpression, { label: `onetwo Ligand`, expression: expr }, { ref: 'ligandSel' });
        bsiteSel.apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(this.ctx, struct.structureRef.cell.obj?.data, {
          type: 'cartoon',
          color: VaryingResidueColorThemeProvider.name as any,
          colorParams: {
            bsite: bsite
          },
          typeParams: {
            alpha: 1 // <-- this varies opacity for the whole representaion as i understand unfortuntaley
          }
        }), { ref: 'ligandBallAndStick' });
```

 </details>

-------

The i noticed #149 where atsehnal mentions that it's probably better to use the `Overpaint` facilities. However that issue also deals with varying parts of "muting" parts of already existing representations and i'm havign a hard time seeing how to apply it.  

So, again my question is whether it's possible to assign opacity on a "per-residue" granularity given aforementionedparameters? Either via a `StructureSelection`/`Expression`/`Loci` or via a `ColorTheme or `StructureRepresentationPresetProvider` or similar).

Thank you kindly
#68

**Comment by arose** [comment]
You will need to use `TransparencyStructureRepresentation3DFromScript` or `TransparencyStructureRepresentation3DFromBundle`, from `src\mol-plugin-state\transforms\representation.ts`

**Comment by rtviii** [comment]
Hi, Alex. Thank you for the quick response. 

In the case that i use transparency is there a way to combine this with leaving the `outline` (..i think it is) visible the same way `opacity` does for representations? 

I first actually reached for `TransparencyStructureRepresentation3DFromBundle`, but show in #1312 a little bit of a different visual effect that it achieves. I guess it also presupposes that there is an already a representation "underneath", correct?

**Comment by arose** [comment]
> In the case that i use transparency is there a way to combine this with leaving the outline (..i think it is) visible the same way opacity does for representations?

sure, transparency is just `1 - opacity`

**Comment by rtviii** [comment]
Ah, neat. I had the impression they are two different effetcs.
Thanks
