### ISSUE TITLE
ASA coloring wrong after removing part of a chain

### ISSUE THREAD

**Issue by arose** [molstar/molstar#132]
Accessible Surface Area coloring wrong after removing part of a chain. Label/tooltip value seems to be still ok. Only effects the chain that had something removed. Example below is pdb 3sn6

![3SN6](https://user-images.githubusercontent.com/272250/108805871-f3a03e80-7554-11eb-8791-a91308539892.png)
![3SN6 (1)](https://user-images.githubusercontent.com/272250/108805874-f438d500-7554-11eb-9c43-4458b3362a7f.png)

**Comment by arose** [comment]
@JonStargaryen could you have a look at this? Might not be limited to ASA but since you did this, I ask you first :)

**Comment by JonStargaryen** [comment]
Both the color theme as well as the labels use a similar pattern to determine the index in the array of ASA values:
https://github.com/molstar/molstar/blob/d121a11e28a4b23b8f33504ebac1d846bbf89d5b/src/mol-model-props/computed/accessible-surface-area/shrake-rupley.ts#L104
and
https://github.com/molstar/molstar/blob/d121a11e28a4b23b8f33504ebac1d846bbf89d5b/src/mol-plugin/behavior/dynamic/custom-props/computed/accessible-surface-area.ts#L87

The `unit` instance processed by the color theme is missing the deleted elements and maps to incorrect values. The one processed to create labels still contains the initial elements and delivers correct results.

First, the `unit` used to color. The `unit` used to create labels at the bottom.
![units](https://user-images.githubusercontent.com/9744615/108917183-33623700-75e4-11eb-9f90-988cf80cb381.png)

Is it expected that different `units` are processed? It throws me off that labels are correct but the coloring is messed up.

**Comment by JonStargaryen** [comment]
Sorry for the late reply. c6073b8 should fix the issue.

**Comment by arose** [comment]
> Sorry for the late reply. c6073b8 should fix the issue.

Thanks Sebastian. Can confirm that it fixes it for me as well.

**Comment by JonStargaryen** [comment]
Turns out the serial mapping is needed and caused the issues for Assembly 3 of 5CBG in #193.

**Comment by arose** [comment]
Hmm, 3sn6 is still fixed for me :)

**Comment by arose** [comment]
I can't reproduce it anymore after #193. Do you still see it @JonStargaryen or have an idea what fixed it?

**Comment by JonStargaryen** [comment]
It's fixed. I've replaced the unit-dependent `getSerialIndex` call with an indexOf operation on `structure.root.serialMapping.elementIndices` (in c6073b8 and b47d046). The problem was that removal of residues would change the results delivered by `getSerialIndex`, the new mapping remains consistent after the removal of residues.

**Comment by arose** [comment]
Great, thanks @JonStargaryen
