### ISSUE TITLE
Discover unit inter-compute bugs

### ISSUE THREAD

**Issue by rxht** [molstar/molstar#1321]
I found the peptide key missing when displaying the pdb file！

**molstar V4.7.1**

**Projected results：**

![image](https://github.com/user-attachments/assets/c490a44c-bc5e-47b6-ab4f-19e2e37eb876)

**Current results：**
![image](https://github.com/user-attachments/assets/56a72856-d162-4f40-9e82-959f598f2924)

After debugging the file  [inter-compute.ts](https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/unit/bonds/inter-compute.ts#L179) here are，Residue ids are expected rather than atom ids.

Should it be fixed with the following code！
![image](https://github.com/user-attachments/assets/1bd3a2a4-a42c-4719-b828-3be5e4a2227f)

**Comment by arose** [comment]
Can you provide an example file/state?

The code you quote is intended, we don't want bonds between images of the same residue with only partial occupancy.

**Comment by arose** [comment]
Thank you @rxht, I applied the fix in c4a900e2ea2d4c7d9b823f21554ae94599c8ebb3
