### ISSUE TITLE
How to set the transparency of the pdb I loaded?

### ISSUE THREAD

**Issue by Leonacoder** [molstar/molstar#1324]
I try to set the transparency of the pdb like this:
 await window?.molstar?.builders.structure.hierarchy.applyPreset(
        trajectory,
        "default",{
            
            representationPreset: 'auto',
            representationPresetParams:{
              quality:0.1,
              theme:{
                Transparency:0.1,
              }
            }
          }
      );
But it doesn't work,How to set the transparency correctly?

**Comment by dsehnal** [comment]
```ts
const preset = await window?.molstar?.builders.structure.hierarchy.applyPreset(...);
const update = plugin.build();
for (const repr of Object.values(preset.representation.representations)) {
  if (!repr) continue;
  update.to(repr).update(old => {
    old.type.params.alpha = 0.5;
  });
}
await update.commit();
```

Something like this should work.
