### ISSUE TITLE
Transparent volume slice issue when transparent ssao enabled

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1332]
Just noted an issue with transparent volume slice and ssao transparentThreshold. Not sure what is causing it 

![image](https://github.com/user-attachments/assets/2e2b1159-9ae8-475e-8623-941765f86734)

**Comment by arose** [comment]
Should be fixed with 195f7284b575042352da18fbda792a60cfc5c3bb, please test, thanks!

**Comment by giagitom** [comment]
It works! Thanks @arose
