### ISSUE TITLE
Infrastructure questions

### ISSUE THREAD

**Issue by danwentworthart** [molstar/molstar#1333]
We built a couple pages that originally used the LiteMol plugin, and have since replaced the LiteMol plugin with Mol*. Note that the bulk of our site is built in a containerized Django system that uses vanilla JavaScript. 

To integrate with Mol*, we added a new Docker container that can run Node and the Mol* module. Within this container, we mount a pdb file that will be loaded into the viewer. We have this working in its most basic state. Our interface still exists in vanilla JavaScript served by our Django container, and that loads a Mol* viewer into an iframe element. 

We have 2 needs:
1. Load carbohydrates with custom SNFG representations. We have a snippet David shared with us, but cannot get it to load the pdb file. 
2. Eventually we would like to react to events in both containers. Users would be greatly helped if they could hover over a linkage in a molecule and have a table record that represents the same linkage become highlighted. The opposite would also be useful, where hovering on a table row would highlight the linkage in the molecule. Do you think the current setup will prevent this or should I press forward assuming it is possible, once we get stuff configured correctly?

Custom SNFG:
Molecule loads correctly without the custom SNFG when we do this:

```
async load_viewer(){
        await this.check_file_exists(this.filename);
        molstar.Viewer.create('app', {
            layoutIsExpanded: true,
            layoutShowControls: false,
            layoutShowRemoteState: false,
            layoutShowSequence: true,
            layoutShowLog: false,
            layoutShowLeftPanel: true,
            viewportShowExpand: true,
            viewportShowSelectionMode: false,
            viewportShowAnimation: false,   
            saccharideCompIdMapType: 'glycam' //snfg
        }).then(viewer => {               
            console.log("Creating a Molstar Viewer.");
            try{
                console.log("loading file: ", this.filename);
                viewer.loadStructureFromUrl(this.filename, 'pdb', false, {
                    label: this.label
                });
            }catch(error){
                console.error("Failed to load file into Molstar. Error: ", error);
            
            }
        }) 
    }
```

The snippet we were sent gives errors in our context, because we are inside a then block, so await keywords break it. I kept the spirit of the code the same but tried breaking the file loading into a new function to get around that. This seems to run, but fails to load the molecule:

```
// Can't use await calls in a then() block, so I need to use a function to finish loading the viewer.
    async finish_loading(viewer, filename){
        try{
            console.log("finish_loading was called.");
            const plugin = viewer.plugin;
            const data = await plugin.builders.data.download({ filename }); 
            console.log("data type: ", typeof data);
            const trajectory = await plugin.builders.structure.parseTrajectory(data, 'pdb'); 
            const model = await plugin.builders.structure.createModel(trajectory); 
            const structure = await plugin.builders.structure.createStructure(model, { name: 'model', params: { } }); 
            await plugin.builders.structure.representation.addRepresentation(structure, { 
                type: 'ball-and-stick', 
                typeParams: { alpha: 0.5 } 
            }); 
            await plugin.builders.structure.representation.addRepresentation(structure, { 
                type: 'carbohydrate', 
                typeParams: { 
                    alpha: 1.0, 
                    sizeFactor: 0.55 
                } 
            });
        }
        catch(error){
            console.error("Failed to finish loading file into Molstar. Error: ", error);
        }
    }

}
```

Am I close?

**Comment by dsehnal** [comment]
Hi,

- Why do you use Docker? You can just serve the JS/CSS from a static build you do once.
- I would recommend that you build a custom smaller Mol* library as documented in https://molstar.org/docs/plugin/custom-library/. With that you will be able to serve just a single static JS and CSS file with entire Mol* while having access to the "full might of TypeScript".  Essentially, you just need to replace the `loadStructure` function from the example above with the snippet you linked in your post (when I sent Oliver the snippet I didn't actually test it, but I am fairly convinced something at least close to this should work and you should be able to debug it separately from your django solution).

**Comment by danwentworthart** [comment]
Thanks, this is helpful.
