### ISSUE TITLE
Issue with tubular alpha helices and single-residue alpha helices

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1335]
When single residue alpha helices are present in the structure and tubular helices is on, a gap is shown instead of a tubular helix. Here is a test state [test.molj](https://github.com/user-attachments/files/17666791/test.molj.txt). The unit should be coarse, I'm not sure if this is reproducible also on non-coarse units.

The issue should be due to ```PolymerTraceIterator``` when ```useHelixOrientation = true```

**With tubular helices on**
![image](https://github.com/user-attachments/assets/1be6a391-1d88-4361-9128-c02996131ac0)

**With standard helices**
![image](https://github.com/user-attachments/assets/8aa55f29-69bd-4e7c-9f13-0203b99b4764)

**Comment by arose** [comment]
Thanks for reporting, could you also look into a fix?

**Comment by giagitom** [comment]
Ok, I'll try
