### ISSUE TITLE
Why is the benzene ring broken in this result? In other results such as pymol nglview, it is intact.

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1339]
<img width="367" alt="image" src="https://github.com/user-attachments/assets/e92ae359-9c41-4e21-90c3-412b6d54b5b2">
<img width="177" alt="image" src="https://github.com/user-attachments/assets/6f1c7221-4237-42af-98d6-6b51f1933a78">

Could different bond lengths cause this problem?
thanks a lot~

**Comment by papillot** [comment]
What's the data source for this structure? Some file formats (e.g. mol, sdf) have the connectivity fully specified, so if the bond is missing from the source data, it may not be inferred from coordinates by Mol* by default.

**Comment by luckyxutao** [comment]
> What's the data source for this structure? Some file formats (e.g. mol, sdf) have the connectivity fully specified, so if the bond is missing from the source data, it may not be inferred from coordinates by Mol* by default.
pdb format

MODEL        1           
ATOM     23  N2  MOL A 277     -35.510  10.580   9.940  1.00  0.00            
ATOM     24  C18 MOL A 277     -36.360   9.390  10.230  1.00  0.00            
ATOM     25  C19 MOL A 277     -35.550   8.250  10.940  1.00  0.00            
ATOM     26  N3  MOL A 277     -34.300   7.870  10.190  1.00  0.00            
ATOM     27  C20 MOL A 277     -33.460   9.090   9.900  1.00  0.00            
ATOM     28  C21 MOL A 277     -34.260  10.070   9.060  1.00  0.00                
TER
ENDMDL

**Comment by arose** [comment]
We use 1.6 as the max bond length for C-N when deriving the bonds from distances. The experimentally observed C-N bond length for a variety of species is quite a bit lower, see https://cccbdb.nist.gov/expbondlengths2x.asp?descript=rCN&all=1. Where does your data come from?

![image](https://github.com/user-attachments/assets/be185ddf-da8e-45c8-a677-505143e6010a)

Mol* reads PDB CONECT records and will add a given bond irrespective of the distance.

**Comment by arose** [comment]
@luckyxutao does the above answers this for you?

**Comment by luckyxutao** [comment]
> @luckyxutao does the above answers this for you?

thanks very much~
