### ISSUE TITLE
No 3D SNFG showing for glycans

### ISSUE THREAD

**Issue by danwentworthart** [molstar/molstar#1341]
My viewer is in a transition state. We previously had built an instance of the Mol* viewer that did show glycans with 3D SNFG. We got advice to change how we work with the viewer. Where we had previously instantiated a viewer via:

molstar.Viewer.create()

... we were advised to build a custom lib, which guided us to instead use 

molstarLib.initViewer()
molstarLib.loadStructure()

Which we got to load from pdb files, but now fails to show any SNFG symbols. Currently, we load both for comparison purposes. When the new custom viewer works, we will remove the old one. 

I am uncertain what to dig into next. When we used `molstar.Viewer.create()` we added some arguments, and I believe `saccharideCompIdMapType: 'glycam'` gave us the SNFG?

In the new context, I have tried adding the same argument to the initViewer() function call, but that didn't work.
On the advice of David, I also tried adding the following to  loadStructure() in the custom lib:

```
await plugin.builders.structure.representation.addRepresentation(structure, {
            type: 'ball-and-stick',
            typeParams: { 
                alpha: 0.5,
            }
        });
await plugin.builders.structure.representation.addRepresentation(structure, {
            type: 'carbohydrate',
            typeParams: {
                alpha: 1.0,
                sizeFactor: 0.55
            }
        });
```

This also does not show SNFG. To my eye, it looks like it applies both representations to the same component, instead of applying the second representation to the SNFG. If I hover over the elements in the viewer that is still showing SNFG, I see that the SNFG elements seem to be nested under the Carbohydrate, and it looks like the same "type" of Carbohydrate is given there. 

So I wonder if I have a problem of needing to either load this differently, or getting my type value correct? Something else?

I am attaching a screenshot so you can see the two viewers for illustration.
![Viewer_comparison](https://github.com/user-attachments/assets/0aa13d29-ed32-40a1-bc9c-c3b38c644196)

**Comment by dsehnal** [comment]
You need to add `[PluginConfig.Structure.SaccharideCompIdMapType, 'glycam'],` to the `initViewer` function's `spec` similar to https://github.com/molstar/molstar/blob/e65f5b270ed3aa94a03ec5bbe0e8c707625fff36/src/apps/mesoscale-explorer/app.ts#L204

**Comment by danwentworthart** [comment]
I think I am getting close now. I really appreciate your help on this.  I tried what you suggested, and though I do see the snfg, and I can tell the representation is responding to edits to sizeFactor or alpha, it seems to link the SNFG components as though they  were also getting a ball and stick treatment? Unsure. Attaching a code snippet in case it is how I'm doing this, and image for illustration.
![LinkedSNFG](https://github.com/user-attachments/assets/d561994b-7017-4ac3-a55c-2e88acbfb93f)
```
const defaultSpec = DefaultPluginSpec();
        const spec : PluginUISpec = {
            actions: defaultSpec.actions,
            behaviors: defaultSpec.behaviors,
            config: [
                [PluginConfig.Structure.SaccharideCompIdMapType, 'glycam']
            ]
        }

        console.log('spec,', spec);

        const plugin = new PluginContext(spec);
        await plugin.init();
        plugin.initViewer(canvas, parent);
        return plugin;

```

**Comment by dsehnal** [comment]
You can turn the links off in the carbohydrate repr params. I don't recall from the top of my head what the param is called but I think you need to specify the list of `visuals`. Either way should be quite straightforward to search the code for the available options.

**Comment by danwentworthart** [comment]
Found it! 
`linkSizeFactor: 0.0`

Appreciate the help! This is resolved.
![Score](https://github.com/user-attachments/assets/8bcc3093-fc8b-4325-a171-7fbf1df4f596)
