### ISSUE TITLE
How to hide structures other than the currently selected structure?

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1351]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/3dd47c52-1417-4ff7-9008-1e1a41b7d982">

How can I hide all structures except the selected ones? Inverse?
thanks a lot~

**Comment by QDMarkMan** [comment]
You can try using the [PluginCommands.State.ToggleVisibility](https://github.com/molstar/molstar/blob/79ed8e7de4d2e8ca518f4273fe5d93ca4f7f57db/src/mol-plugin/commands.ts) API.

**Comment by luckyxutao** [comment]
> You can try using the [PluginCommands.State.ToggleVisibility](https://github.com/molstar/molstar/blob/79ed8e7de4d2e8ca518f4273fe5d93ca4f7f57db/src/mol-plugin/commands.ts) API.

How to hide/display custom discontinuous atoms?

**Comment by QDMarkMan** [comment]
That’s great! You can also try the method from @dsehnal; it works as well.
