### ISSUE TITLE
Issue with Screenshot download using illumination mode and transparent bg

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1364]
Outlines facing transparent background seems missing while taking a screenshot using illumination mode

![image](https://github.com/user-attachments/assets/cbf3e089-a2c9-4a15-a62b-b998ddb15396)

**Comment by arose** [comment]
Could you look into it?

**Comment by giagitom** [comment]
@arose this should be fixed with #1373

**Comment by giagitom** [comment]
I also included a fix in the second commit to address transparent depth texture artifacts that appeared when a scene had transparency but no longer does.
