### ISSUE TITLE
Showing all models for SDF files

### ISSUE THREAD

**Issue by chdominguez** [molstar/molstar#1367]
I have several SDF files that contain more than one molecule, it seems that there is no way using the UI to display all the models at once. I've looked at #329 but it seems that for SDF files it does not work the same. In the GUI I only see the current model.

In the state tree you can see there are 15 models:
<img width="652" alt="Captura de pantalla 2024-11-27 a las 9 17 44" src="https://github.com/user-attachments/assets/63cae8d9-5093-4644-82cf-464ff6706f15">

But in the Structure Tools there is no "All" button to display all of them at once.
<img width="585" alt="Captura de pantalla 2024-11-27 a las 9 17 58" src="https://github.com/user-attachments/assets/bbcac800-2fce-40f7-bd94-5dc9a14529f7">

**Comment by dsehnal** [comment]
That's weird. I just tried an SDF file with two models and it works for me:

![image](https://github.com/user-attachments/assets/687231bf-ab08-446a-8342-af785a860097)

**Comment by chdominguez** [comment]
This may sound stupid but I was clicking the central part of the button instead of the rightmost "bookmark" icon to toggle all of the models. Now I can see the "All models" button. Thanks!
