### ISSUE TITLE
Possible bug on ball and stick representation

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1369]
https://github.com/molstar/molstar/blob/ba38fe2474734460332392b842c822cc6fbe027f/src/mol-repr/structure/representation/ball-and-stick.ts#L46

@arose Shouldn't be like this instead? 

```ts
    params = PD.clone(BallAndStickParams);
```

**Comment by arose** [comment]
Yes, thanks fixed in 8bda5103788d85ebeb019c89207313865589fa76
