### ISSUE TITLE
Molstar spec: Error: MolViewSpec extension is not loaded.

### ISSUE THREAD

**Issue by hainm** [molstar/molstar#1377]
hi, 

I am trying to use Molstar with below code (for nglview) and getting `Molstar spec: Error: MolViewSpec extension is not loaded.`

```javascript

import { loadMVS } from 'molstar/lib/extensions/mvs/load';
import { MVSData } from 'molstar/lib/extensions/mvs/mvs-data';
...
    async loadMolstarSpec(spec_json: string, options: any) {
        const data = MVSData.fromMVSJ(spec_json);
        console.log('Loading Molstar spec:', data);
        try {
            await loadMVS(this.plugin, data, options);
        } catch (error) {
            console.error('Error loading Molstar spec:', error);
        };
    }
```

Any idea how to fix? Thanks.

**Comment by hainm** [comment]
<img width="918" alt="image" src="https://github.com/user-attachments/assets/4988295c-b12e-4d00-ad95-74a8bf33c3f7">

**Comment by dsehnal** [comment]
You need to add `PluginSpec.Behavior(MolViewSpec)` to the plugin spec when creating the viewer instance.

**Comment by hainm** [comment]
@dsehnal I am using below code. How can I correct it? thanks
```
        this.plugin = await createPluginUI({
            target: this.container,
            render: (component, container) => {
                renderReact18(component, container);
            },
            // spec: PluginSpec.Behavior(MolViewSpec), # THIS IS NOT RIGHT
            spec: undefined, 
            onBeforeUIRender: async (ctx) => {
                // Implement the onBeforeUIRender logic here
            }
        });
```

**Comment by dsehnal** [comment]
See for example src/examples/basic-wrapper/index.ts, the behaviors is a list on the spec object and you extend the one provided by the default spec.

Just on mobile now, so hard to share exact snippet.

**Comment by hainm** [comment]
Thanks. Will try later. On mobile too. :)

**Comment by hainm** [comment]
> the behaviors is a list on the spec object and you extend the one provided by the default spec.

I have something that works now. But the repr doesn't seem right?

```javascript
        var defaultSpec = DefaultPluginSpec();
        var spec: PluginUISpec = {
            ...defaultSpec,
            behaviors: [
            ...defaultSpec.behaviors,
            PluginSpec.Behavior(MolViewSpec)
            ]
        };
        this.plugin = await createPluginUI({
            target: this.container,
            render: (component, container) => {
                renderReact18(component, container);
            },
            spec: spec,
            onBeforeUIRender: async (ctx) => {
                // Implement the onBeforeUIRender logic here
            }
        });
```

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/152111bd-f78b-4086-8354-655c3e7f14c0">

**Comment by hainm** [comment]
@dsehnal Here is the code to load the spec. Do you know why I got grey color like above? Thanks.

https://github.com/nglviewer/nglview/blob/09a6e232839aa8db3cbaf9633218b2fdcfd8d64e/js/src/molstarview/widget.ts#L336-L345

**Comment by dsehnal** [comment]
I don't know, the code looks correct and taken directly from the example. 

Maybe a bug got introduced during the development or we made some tweaks that got out of sync with the published package. I will check.

**Comment by dsehnal** [comment]
I just tried

```py
builder = create_builder()
    (
        builder.download(url=_url_for_mmcif(id))
        .parse(format="mmcif")
        .model_structure()
        .component()
        .representation()
        .color(color="blue")
    )
```

From `mol-view-spec` master together with latest Mol* and it works with the color blue.

----

@sbittrich How outdated is the molviewspec package? Can we perhaps do at least a beta release with the current version?

**Comment by hainm** [comment]
@dsehnal I've tried with master branch of mol-view-spec and `'4.9.0'` of molstar.
It doesn't help either. So either with my code or the molstar 4.9.0?

**Comment by hainm** [comment]
> @dsehnal I've tried with master branch of mol-view-spec and `'4.9.0'` of molstar. It doesn't help either. So either with my code or the molstar 4.9.0?

Oh, master branch of mol-view-spec does help. lol

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/35c87bb4-0206-4203-9701-673b2fa8dfbd">

**Comment by hainm** [comment]
I think I can close this issue now. It's like a side effect of the jupyter notebook to memorize the previous created view.
Basically, I forgot to add `.color(color='blue')` -> got grey color -> I added `.color(color='blue')` and display the view again -> still grey. But if I clear the notebook and restart the kernel, I could see the "blue" color. Thanks guys.

**Comment by hainm** [comment]
So it's not an issue with the published version of `molviewspec` either.

**Comment by sbittrich** [comment]
> How outdated is the molviewspec package? Can we perhaps do at least a beta release with the current version?

Created the v1.1.0 release, just in case.
