### ISSUE TITLE
How to change the opacity of the representation layer programmatically?

### ISSUE THREAD

**Issue by daenbol** [molstar/molstar#149]
Hello! I need to programmatically change the opacity of the selection layer. Unfortunately, I wasn't able to find out how to do that with the debugger.
1. I introduced a DOM-linked breaking point to an opacity changing slider
2. It highlighted this line of code (please find {setAttribute} in the first part of code below)
3. However, there is also an alpha var which is also responsible for the opacity of a layer. Is it possible to execute a function to set the opacity to a specific selection? (see the second part of code)

```
    function Z(e, t, r, n) {
        var i = Q.hasOwnProperty(t) ? Q[t] : null;
        (null !== i ? 0 === i.type : !n && (2 < t.length && ("o" === t[0] || "O" === t[0]) && ("n" === t[1] || "N" === t[1]))) || (function (e, t, r, n) {
            if (null == t || function (e, t, r, n) {
                    if (null !== r && 0 === r.type) return !1;
                    switch (typeof t) {
                        case "function":
                        case "symbol":
                            return !0;
                        case "boolean":
                            return !n && (null !== r ? !r.acceptsBooleans : "data-" !== (e = e.toLowerCase().slice(0, 5)) && "aria-" !== e);
                        default:
                            return !1
                    }
                }(e, t, r, n)) return !0;
            if (n) return !1;
            if (null !== r) switch (r.type) {
                case 3:
                    return !t;
                case 4:
                    return !1 === t;
                case 5:
                    return isNaN(t);
                case 6:
                    return isNaN(t) || 1 > t
            }
            return !1
        }(t, r, i, n) && (r = null), n || null === i ? function (e) {
            return !!H.call(q, e) || !H.call(G, e) && (z.test(e) ? q[e] = !0 : (G[e] = !0, !1))
        }(t) && (null === r ? e.removeAttribute(t) : e.setAttribute(t, "" + r)) : i.mustUseProperty ? e[i.propertyName] = null === r ? 3 !== i.type && "" : r : (t = i.attributeName, n = i.attributeNamespace, null === r ? e.removeAttribute(t) : (r = 3 === (i = i.type) || 4 === i && !0 === r ? "" : "" + r, n ? e.setAttributeNS(n, t, r) : e.{setAttribute}(t, r))))
    }

///////////////////////////////

alpha: o.ParamDefinition.Numeric(1, {
                min: 0,
                max: 1,
                step: .01
            }

**Comment by dsehnal** [comment]
Hi.
You most likely won't be able to "hack" mol* in this way. How to do this programatically is tied to how you actually set up your state. Could you be more specific about what you are trying to do?

**Comment by daenbol** [comment]
I'm trying to load a structure with specific visual parameters (Just for predefined pocket visualization and more comfortable color scheme). Is it possible to use MolQl language for that purpose? Do we have some more effortless way to specify the opacity?

**Comment by dsehnal** [comment]
[This](https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.ts#L349) is how you would use MolQL to define selections. 

You can then use these to create components and color them in various ways. However, if you want localized opacity based on selection, you would need to use "overpaint" feature (https://github.com/molstar/molstar/blob/7f79ff9ff23f176f7055bd568ca5f068a1f3c432/src/mol-plugin-state/transforms/representation.ts#L259, https://github.com/molstar/molstar/blob/7f79ff9ff23f176f7055bd568ca5f068a1f3c432/src/mol-plugin-state/transforms/representation.ts#L311).

I admit it's pretty complicated and could probably use a simpler API on top of what's there currently.

**Comment by daenbol** [comment]
However, I'm using a pdbe version of molstar (https://github.com/PDBeurope/pdbe-molstar) because some pdbe molstar functions are viable for me. Is there an easy way to combine them?

**Comment by dsehnal** [comment]
You might fork the PDB version and include some code or fork this repo and include code from the PDB one. However without going the "modern webdev route" (e.g. using a solution that relies on webpack or a similar tool) you won't be able to achieve your goal.

**Comment by daenbol** [comment]
> [This](https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.ts#L349) is how you would use MolQL to define selections.
> 
> You can then use these to create components and color them in various ways. However, if you want localized opacity based on selection, you would need to use "overpaint" feature (
> 
> https://github.com/molstar/molstar/blob/7f79ff9ff23f176f7055bd568ca5f068a1f3c432/src/mol-plugin-state/transforms/representation.ts#L259
> 
> ,
> https://github.com/molstar/molstar/blob/7f79ff9ff23f176f7055bd568ca5f068a1f3c432/src/mol-plugin-state/transforms/representation.ts#L311
> 
> ).
> I admit it's pretty complicated and could probably use a simpler API on top of what's there currently.

Could you please give me an example that could be inserted in js script after building? I have troubles with this way( I also tried 1) to change hex colors by adding a "00" extent at the start or the end but it didn't succeed 2) to initialize PluginStateTransform.BuiltIn, but I wasn't able to find proper parameters

**Comment by dsehnal** [comment]
Sorry I've misled you somewhat with the overpaint. That is for changing the color, not the transparency.

You will have to write a utility function before you compiler it and then call that from JS. Something like this:

```ts
makeTransparent(compId: string) {
    // build a query based on the function params
    const sel = MS.struct.generator.atomGroups({ 'residue-test': MS.core.rel.eq([MS.struct.atomProperty.macromolecular.label_comp_id(), compId]) });

    // this is just for testing, provide the structure/representations you want this applied to
    const struct = this.plugin.managers.structure.hierarchy.current.structures[0];
    const repr = struct.components[0].representations[0].cell;

    const { selection } = StructureQueryHelper.createAndRun(struct.cell.obj!.data.root, sel);
    const bundle = StructureElement.Bundle.fromSelection(selection);

    const update = this.plugin.build();

    // if you have more than one repr to apply this to, do this for each of them
    update.to(repr).apply(StateTransforms.Representation.TransparencyStructureRepresentation3DFromBundle, {
        layers: [{ bundle, value: 0.5 }]
    });

    return update.commit();
}
```

calling ``viewer.makeTransparent('ALA')`` will make all ALA residues on the "1st representation" transparent.

**Comment by arose** [comment]
@daenbol did the suggestion work for you?
