### ISSUE TITLE
Interval quantization encoder should use max as upper bound

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#15]
The interval quantization encoder uses numSteps as upper bound.

https://github.com/molstar/molstar-proto/blob/50ebd5467cbf80da6898bf307a8062f9cd300b6d/src/mol-io/common/binary-cif/array-encoder.ts#L175

The line should probably read
`else if (v >= max) output[i] = max; `
otherwise the example at https://github.com/dsehnal/BinaryCIF#interval-quantization cannot be recreated.

**Comment by arose** [comment]
ping @dsehnal, we just discussed this and now think it should be `numSteps - 1`. Do you agree?

**Comment by dsehnal** [comment]
Yes, you are right, nice find!
