### ISSUE TITLE
Getting residue/atom information from selection

### ISSUE THREAD

**Issue by davidhoksza** [molstar/molstar#161]
Hey, 

I would like to query the data model based on a selection. So for example, I have something like
```
getStructureSelection(Q => Q.struct.generator.atomGroups({
                'residue-test': Q.core.rel.inRange([Q.struct.atomProperty.macromolecular.label_seq_id(), 10, 20]),
                'group-by': Q.struct.atomProperty.macromolecular.residueKey()
            }), data);
```
which returns
```
{kind: "sequence", source: Structure, structures: Array(11)}
kind: "sequence"
source: Structure {units: Array(8), unitMap: Map(8), unitIndexMap: Map(8), state: {…}, _child: undefined, …}
structures: (11) [Structure, Structure, Structure, Structure, Structure, Structure, Structure, Structure, Structure, Structure, Structure]
__proto__: Object
```

And now I would like to find out what are, for example, residue names (or any other property) of each of the residues/atoms. I am pretty sure there is a way how to easily do this, but I was not able to find out how.

**Comment by dsehnal** [comment]
Hi,

first step would be to convert it to a Structure object:

```ts
const s = StructureSelection.unionStructure(selection)
```

For the next part there isn't anything in particular and we usually did this "by hand". But I've added a helper method for this in https://github.com/molstar/molstar/commit/a8541d5967e2374d0831855643c98f9c8de21405.

The usage is for example:

```ts
Structure.eachAtomicHierarchyElement(s, { 
  residue: l => console.log(StructureProperties.residue.label_seq_id(l))
});
```

Alternatively, you can get the code from the commit and tweak it to your needs. Also there is a lot more "structure data model manipulation" available for example in https://github.com/molstar/molstar/tree/master/src/mol-model/structure/query/queries.

**Comment by davidhoksza** [comment]
Thanks, David. Works!
