### ISSUE TITLE
Isosurface transparency confusion

### ISSUE THREAD

**Issue by iainmaryanow** [molstar/molstar#165]
Hey,

I am working with isosurface volumes on top of proteins and molecular surfaces. When I have some transparency on the surface but not for the volume, the representations look exactly as expected.

<img width="687" alt="Screen Shot 2021-04-15 at 12 44 45 PM" src="https://user-images.githubusercontent.com/55925317/114858436-be43fe80-9de9-11eb-99cc-aaac7ee2fe17.png">

The portions of the volume that are not enveloped by the surface are easily visible.

However, when I add any amount of transparency to the volume (attached below is using alpha=0.99), the volume becomes more transparent when looking through the volume.

<img width="686" alt="Screen Shot 2021-04-15 at 12 45 36 PM" src="https://user-images.githubusercontent.com/55925317/114858653-095e1180-9dea-11eb-9228-149f610b38d8.png">

Seen here, I would not expect the volume to appear much different with alpha of 0.99. And then when turning the camera to not look at the volume directly over the surface representation, the volume transparency seems to act as I would expect.

<img width="595" alt="Screen Shot 2021-04-15 at 12 45 45 PM" src="https://user-images.githubusercontent.com/55925317/114858782-33afcf00-9dea-11eb-85dd-f7f38e2d75b3.png">

Thanks again

**Comment by dsehnal** [comment]
The change is so big because Mol* uses a separate render pipeline for transparent objects. We needed to make some tradeoffs, and one of them is that near 1 transparency objects will look like this.

I remember there also being a "trapdoor transparency" option (the object is rendered as a checkered pattern with each other square being transparent) which is currently not exposed. Maybe we could try playing around with this again.

**Comment by arose** [comment]
Hi @iainmaryanow, I suggest to not use opacity close to 1.0 and if transparent objects should be distinguished to use opacity values that differ by 0.2 or 0.3 like below.

Are you trying to get a specific effect with using an opacity value of 0.99 or is it mostly an example?


![image](https://user-images.githubusercontent.com/272250/115811294-486d0380-a3a4-11eb-9f65-56d749067855.png)
Protein Opacity 0.6
Water Opacity 1.0

![image](https://user-images.githubusercontent.com/272250/115811448-9255e980-a3a4-11eb-9d5b-020986438936.png)
Protein Opacity 0.6
Water Opacity 0.9
