### ISSUE TITLE
Measurement Labels

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#166]
All measurement labels are currently empty, hover and highlights are also affected. Broke between v2.0.0-dev.11 and v2.0.0-dev.12.

![meas](https://user-images.githubusercontent.com/9744615/115344906-e2456e00-a162-11eb-85bd-f22e88c97a28.png)

Looks like this is related to the refactoring of `cell.obj.data.sourceData` that now provides `infos`/`pairs`/`triples`/`quads`. This seems to cause issues at the following locations:

https://github.com/molstar/molstar/blob/b53debcfef324066f71ba0f60a8b3f45ef6f2a31/src/mol-plugin-ui/structure/measurements.tsx#L261

https://github.com/molstar/molstar/blob/b53debcfef324066f71ba0f60a8b3f45ef6f2a31/src/mol-plugin-ui/structure/measurements.tsx#L308

**Comment by dsehnal** [comment]
Thanks Sebastian, I will have a look.

**Comment by dsehnal** [comment]
Should be fixed in e0d36c30d32629adead9f004b732dabb69d27940.

**Comment by JonStargaryen** [comment]
It's working again, thank you!

On a side note: Is there a way to increase the default text-size of rendered distance/angle/dihedral labels? Right now it's possible to change each value individually, but that's quite laborious for multiple labels.

**Comment by dsehnal** [comment]
This is not implemented but I suppose it could be added to the common params.
