### ISSUE TITLE
How to select multiple residues by auth_sequence_id

### ISSUE THREAD

**Issue by dvmoritzschoefl** [molstar/molstar#168]
Hi, until now I selected one residue with an expression I created and converted that to a structure selection (which then got focused), like in #120.

Now I have a different use case. I want to select multiple residues by their auth sequence id and focus them. It is clear for me how to select exactly one residue by its auth sequence id, the code I use is

```
const expr = MS.struct.generator.atomGroups({
      "residue-test": MS.core.rel.eq([
          MS.struct.atomProperty.macromolecular.auth_seq_id(),
          557, // or any other auth seq id
      ]),
})

const sel = Script.getStructureSelection(expr, root);

const loci = StructureSelection.toLociWithSourceUnits(sel);
```

What I need:
An expression that can select **multiple** residues at once by their auth seq id (so [556, 558, ...] for example). So is there an easy way to do this or to combine multiple single select expressions to one big expression?

Thanks in advance

**Comment by arose** [comment]
try

```ts
MS.struct.generator.atomGroups({
    'residue-test': MS.core.set.has([MS.set([556, 558]), MS.ammp('auth_seq_id')])
})
```

**Comment by dvmoritzschoefl** [comment]
Thank you, that worked as expected, for anyone looking at this issue, here is the code that created the expression for selecting residues by their auth sequence id (and chain)

```
export function createSequenceIdExpression(
  sequenceIds: number[],
  chain?: string
): Expression {
  const query: any = {
    "residue-test": MS.core.set.has([
      MS.set(...sequenceIds),
      MS.ammp("auth_seq_id"),
    ]),
    "group-by": MS.struct.atomProperty.macromolecular.residueKey(),
  };

  if (chain) {
    query["chain-test"] = MS.core.rel.eq([
      MS.struct.atomProperty.macromolecular.auth_asym_id(),
      chain,
    ]);
  }

  return MS.struct.generator.atomGroups(query);
}
```

**Comment by kscgl** [comment]
Typescript complains about number[] when I do the same thing. And cannot find the related loci.

```
let list: number[] = [];
for (let i = 60; i <= 87; i++) {
  list.push(i);
 }
 
const sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
    'residue-test': Q.core.set.has([Q.set(list), Q.ammp('auth_seq_id')]),
    'group-by': Q.struct.atomProperty.macromolecular.residueKey(),
}), data);
```

`TS2345: Argument of type 'number[]' is not assignable to parameter of type 'Expression'.   Type 'number[]' is not assignable to type 'string'.`

However it works as expected if I write down the numbers one by one as below;

```
const sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
    'residue-test': Q.core.set.has([Q.set(60, 61, 62, 63, 64), Q.ammp('auth_seq_id')]),
    'group-by': Q.struct.atomProperty.macromolecular.residueKey(),
}), data);
```

Am I missing anything here?

**Comment by arose** [comment]
Hi, try writing `Q.set(...list)` so the list is spread as separate arguments.

**Comment by kscgl** [comment]
Yes, that worked! Thank you

**Comment by kscgl** [comment]
@eje24 can you share your code snippet? That could help to figure out how you can obtain because eg I am getting it as below;

```
for (const s of this.plugin.managers.structure.hierarchy.current.structures) { 
    const components = s.components;
    for (const c of components) {
        for (const r of c.representations) {
             const root = repr.obj!.data.sourceData.root;
```

**Comment by eje24** [comment]
Thanks @kscgl , of course. It's essentially the same as that of the original poster's:

```
const MS = molstar.MolScriptBuilder;
    atomGroups = molstar.MolScriptBuilder.struct.generator.atomGroups({
    'residue-test': MS.core.set.has([MS.set([...residueList]), MS.ammp('auth_seq_id')])
    });
const sel = Script.getStructureSelection(expr, root);
const loci = StructureSelection.toLociWithSourceUnits(sel);
```
In this case, I wasn't sure as to the source of `root`. Does that clear things up?

**Comment by eje24** [comment]
As a bit of clarification, what I'm trying to implement is the following. I'd like to take as input:
1. an atom from a particular residue on the protein (for example, the oxygen OE2, from the residue with sequence ID 65)
2. an atom from the ligand (for example, the nitrogen N2)
and apply the measure the distance between the two. This will take the form:
```
residueAtomLoci = getResidueAtomLoci(residueID = {id of residue eg 65}, atomName = {atom name eg OE2})
ligandAtomLoci = getLigandAtomLoci(atomName = {atom name eg N2})
Viewer.plugin.managers.structure.measurement.addDistance(residueAtomLoci, ligandAtomLoci);
```
What I'm trying to do is implement the functions getResidueAtomLoci and getLigandAtomLoci. Any help or suggestions would be much appreciated. Thank you!
