### ISSUE TITLE
Entity Source color scheme leaves parts black 

### ISSUE THREAD

**Issue by valasatava** [molstar/molstar#172]
Some parts are left black when Entity Source color scheme is applied to 4AFI (other examples 4Q95, 1MOW)
![image](https://user-images.githubusercontent.com/16787092/116632894-ffb9cb00-a90c-11eb-87d5-0a1a5ee65feb.png)

**Comment by arose** [comment]
Thanks @valasatava, this can happen for regions with unknown source. But it should not use black but white/light-grey for coloring in those cases.
