### ISSUE TITLE
Roadmap question regarding 3D editing functionality

### ISSUE THREAD

**Issue by goraj** [molstar/molstar#18]
Hello,

is this in scope for this project?

Regards,
Jacob

**Comment by arose** [comment]
Hi Jacob, what do you mean by "3D editing functionality" specifically?

**Comment by goraj** [comment]
Hi Alexander,
I mean things like adding/deleting/changing the atom and bond types, rotating torsion angles, changing stereochemistry in 3D.

**Comment by arose** [comment]
not currently on the roadmap
