### ISSUE TITLE
How can molstar display the interaction between two structures?

### ISSUE THREAD

**Issue by qitayang** [molstar/molstar#185]
Dear Team,

Thanks for your wonderful work to Molstar.

We found that Molstar show good interaction between ligand and target protein well when they are written in one file or one structure, **eg. complex.pdb**. However, if we written them in separated file, **e.g. lig.pdb + rec.pdb,**  and open them in Molstar viewer, the interaction between  ligand and target protein will not display, even we select them and add new no-covalent representation.

Could you tell me how to deal with it? How to show interaction between ligand and protein target which saved in different file/structures?

Thanks.

Best Regards,
Jack

**Comment by dsehnal** [comment]
Hi Jack,

unfortunately, automatic computation of interactions between different structures isn't currently supported.

However, there might be a relatively simple solution for this by using Mol* to merge the structures into a single one after you load them.

The code would look something like 

```ts
const protein = await loadStructure('protein.pdb');
const ligand = await loadStructure('lig.pdb');

const merged = await mergeStructuresAndCreateVisuals([protein, ligand], { representation: 'default' });
```

Would you be interested in this option?

David

**Comment by qitayang** [comment]
Hi, David,

Thanks for your quick help.

Your solution seems work for my case, I will try it soon.

Best  Regards,

Jack

**Comment by dsehnal** [comment]
The transform that does this is currently not implemented, but it should be fairly straightforward to do.

Can you do this on your own or do you want some help with it?

**Comment by qitayang** [comment]
Hi  David,

I want try it my own at first. If I can not deal with it myself, I will come back to you. Thanks.

> The transform that does this is currently not implemented, but it should be fairly straightforward to do.
> 
> Can you do this on your own or do you want some help with it?

Thanks for your help,  I am test it myself

**Comment by arose** [comment]
Hi @qitayang did you made it work?

**Comment by arose** [comment]
You can also look at the docking-viewer app which does merge structures, see https://github.com/molstar/molstar/blob/master/src/apps/docking-viewer/index.ts#L197-L205 in a way @dsehnal suggested.

**Comment by hadim** [comment]
I often use the molstar viewer at https://molstar.org/viewer/ (because it's seriously great) and it will be awesome to be able to merge a PDB file with various molecules from an SDF file in order to see the interactions without having to merge the files manually before using mol viewer.
