### ISSUE TITLE
Absence of a ligand in a structure. Parsing error?

### ISSUE THREAD

**Issue by daenbol** [molstar/molstar#186]
There is no ligand in this list of ligands Amicoumacin A in [5I4L](https://www.rcsb.org/3d-view/5I4L).
![image](https://user-images.githubusercontent.com/53538336/118352437-18abb880-b56a-11eb-91f6-bb066eca572d.png)

**Comment by arose** [comment]
The Amicoumacin A (UAM) ligand is only present in the 2nd Assembly but not in the 1st, see https://www.rcsb.org/3d-view/5I4L/2.

![image](https://user-images.githubusercontent.com/272250/118374297-28c69680-b570-11eb-8c4a-4fb120ab736c.png)

**Comment by arose** [comment]
Hi @daenbol, did this help you?
