### ISSUE TITLE
How to trigger hydrogen bonds display in JS code?

### ISSUE THREAD

**Issue by daenbol** [molstar/molstar#187]
Hello! How to trigger hydrogen bonds display in the structure that was loaded in molecular-surface representation? Something like in these picture.
![image](https://user-images.githubusercontent.com/53538336/118353586-af2ea880-b56f-11eb-9e86-2ab020ced7d3.png)

**Comment by dsehnal** [comment]
Hi, create a selection and add ``interactions`` representation (e.g. same way you would add ``ball-and-stick`` or ``cartoon``.

**Comment by arose** [comment]
Hi @daenbol, did this help you?

**Comment by daenbol** [comment]
I could add only part of all protein-ligand interactions. E.g. there are no interactions with the red-circled atom in 1cbs. How to enter mode with surroundings as stick-balls and calculated interactions?
