### ISSUE TITLE
Vault protein assembly not rendered completely

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#19]
I am evaluating the Mol* viewer on the RCSB beta page, so I am not sure if issues there have been resolved here already. But I found that `4V60` is not fully shown (only the top and bottom part are shown as surface).

![image](https://user-images.githubusercontent.com/4458965/67987078-d4c5bc80-fc2c-11e9-847b-bb22e57e16c9.png)

**Comment by arose** [comment]
Thanks!

**Comment by arose** [comment]
should be good now, thank you for reporting @bergwerf
