### ISSUE TITLE
How to enable default hover labels on 3D structure when using PluginContext

### ISSUE THREAD

**Issue by CodeGit** [molstar/molstar#190]
Hi,
I'm working on embedding mol* into a react-based website. Based on the documentation here: https://molstar.org/docs/plugin/ I've got most functionality working as we'd like using the PluginContext without the build-in react. 

I haven't been able to get the labels that show residue information when hovering over the 3D structure to display. Is there a default label provider which can be used or should I implement a class hierarchy similar to PDBeStructureQualityReport?

I've attached some snippets below to help illustrate what I'm doing in case the issue is with how the Plugin is being initialised

```
const MySpec = {
        ...DefaultPluginSpec(),
        layout: {
          isExpanded: true,
          showControls: true,
        },
        config: [[PluginConfig.VolumeStreaming.Enabled, false]],
      };
this.viewer = new PluginContext(MySpec);

await this.viewer.init();
      this.viewer.initViewer(
        this._structureViewerCanvas.current,
        this._structureViewer.current,
      );
```

**Comment by dsehnal** [comment]
Hi,

The UI for the tooltips is part of the React code, so you will have to write your own UI to display them.

It's quite simple, here's how it's done in the Mol* React UI: https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/controls.tsx#L254

If you are using React Hooks, you can use the [``useBehavior`` hook](https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/hooks/use-behavior.ts#L18) like this:

```ts
function Labels({ plugin }: { plugin: PluginContext }) {  
  // or use const plugin = useContext(...);
  const labels = useBehavior(plugin.behaviors.labels.highlight);
  return <div>{labels.map(....)}</div>;
}
```

You can also play around and display the labels at the cursor position etc.
