### ISSUE TITLE
Canvas not cleared with transparent background on and antialiasing off

### ISSUE THREAD

**Issue by sukolsak** [molstar/molstar#201]
**Steps to reproduce:**
1. Load a model, such as 1TQN
2. Click the Settings button on the bottom left of the screen
3. Turn on "Transparent Background"
4. Click "Postprocessing" and turn off "Antialiasing"
5. Move the model around

**Result:**
The canvas is not cleared before it is repainted.
![Screen Shot 2021-05-29 at 1 04 25 PM](https://user-images.githubusercontent.com/226473/120083604-a31e0d00-c07e-11eb-8e45-2613ed167cde.png)

**Comment by arose** [comment]
Thanks @sukolsak. Always producing nice bug-art these clearing issues :)
