### ISSUE TITLE
Why molstar is slower(heavy) than NGL ?

### ISSUE THREAD

**Issue by flat35hd99** [molstar/molstar#202]
Thank you for good product. I often use this at PDB webpage.
This is question issue and I want to contribute through resolving this problem.

# environment
Windows10, Chrome 90.0.4430.212 (Official Build)
WebGL1.0 and 2.0 is available.
LIFEBOOK UH90/B3( it only have gpu built into cpu.

# problem
At [rcsb.org](rcsb.org)'s 3D viewer, mol* is slower than NGL and JSmol when I rotate camera and the product I build on local machine also slower than them.
mol* is newer project and I think mol* should be faster and lighter if there is no reason. or, Can I set the "resolution" or "quality" of render ?

**Comment by arose** [comment]
Thanks for the report @flat35hd99. What resolution does your display have? Please try switching off the Ambient Occlusion effect (see below) and check if that improved performance.

![image](https://user-images.githubusercontent.com/272250/120111233-01ea9180-c126-11eb-86fb-001f1e4aa414.png)

**Comment by flat35hd99** [comment]
Thank you for your reply.
Wow! That works well and viewer follows my cursor !
However, it has still been slower.(again, it can withstand practical use)
Can I find methods to improve experience in exchange for view quality ? I know my machine is not good but I want to know how to improve that.

**Comment by arose** [comment]
If you compile molstar yourself you can additionally set enableWboit (fallback to cheaper transparency rendering) to false and pixelScale (render at lower resolution) to something lower than 1, e.g., 0.75 (https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.ts#L75-L76).

**Comment by flat35hd99** [comment]
@arose I'm so sorry for late reply.
I identified why performance of molstar on my device is low and I want to share that.
It is simple, hardware acceleration was disabled. I turned on that, then the viewer is very faster and lighter.
I appreciate you to advice and support me.

**Comment by arose** [comment]
Wonderful, glad you made it work.

**Comment by jiucenglou** [comment]
> @arose I'm so sorry for late reply.
> I identified why performance of molstar on my device is low and I want to share that.
> It is simple, hardware acceleration was disabled. I turned on that, then the viewer is very faster and lighter.(as much as NGL and molstar is richer than NGL)
> I appreciate you to advice and support me.

Could you share how to enable hardware acceleration for Mol* ? Many thanks !

**Comment by flat35hd99** [comment]
Hi @jiucenglou 
My web browser is Google chrome. if you so, access chrome://settings/system and you may find hardware acceleration and turn on it. It worked well for me.

**Comment by jiucenglou** [comment]
> Hi @jiucenglou
> My web browser is Google chrome. if you so, access chrome://settings/system and you may find hardware acceleration and turn on it. It worked well for me.

Thanks for your clarification. That setting is already on for me :D
