### ISSUE TITLE
when will fs in browser fix be published?

### ISSUE THREAD

**Issue by dlrice** [molstar/molstar#204]
We're encountering an error when using mol* in the browser:

```
../node_modules/molstar/lib/mol-io/common/file-handle.js
Module not found: Error: Can't resolve 'fs' in '/Volumes/Developer/nightingale/node_modules/molstar/lib/mol-io/common'
```
and noticed that https://github.com/molstar/molstar/commit/45ef00f1d188cc03907be19d20aed5e6aa9d0ee0 will fix this error - just wondering when you plan to publish these changes?

**Comment by dsehnal** [comment]
2.0.6 is out.
