### ISSUE TITLE
Drawing helices as cylinder ?

### ISSUE THREAD

**Issue by tubiana** [molstar/molstar#206]
Hi :-) 

Recently I discovered 3dproteinimaging.com and I thought that it could be super nice for molstar to draw helices as cylinders, like in this example bellow :-) 

![requested_image (46)](https://user-images.githubusercontent.com/8037224/121034846-a4051c00-c7ad-11eb-9c85-b0de550b31cb.png)

Best,
Thibault Tubiana.

**Comment by arose** [comment]
Yeah, definitely something I still need to port over from NGL. Thanks for suggesting it.

**Comment by arose** [comment]
Hi @tubiana, here is a little preview

![image](https://user-images.githubusercontent.com/272250/124523818-7bbd0d00-ddad-11eb-9a73-9572f5a31a78.png)

**Comment by tubiana** [comment]
Wow this is so nice! And the cylinder are even bended so it's even cooler thank you 😃
