### ISSUE TITLE
Import of PDB assembly coordinates throws TypeError

### ISSUE THREAD

**Issue by isaphan** [molstar/molstar#207]
Download Structure
- Source = PDB; PDB Id(s) = 2vre
- Options = Type = Symmetry (Assembly)

Throws:
TypeError: Cannot read property '_staticPropertyData' of undefined

**Comment by dsehnal** [comment]
Thanks for the report. When selecting ``Symmetry (Assembly)`` it is required to add at least one generator otherwise it returns an empty structure and hence the error.

![image](https://user-images.githubusercontent.com/21145776/121070111-9ad87700-c7ce-11eb-8af4-80e3cb4e55dc.png)

I will have a look into adding a better error message for this case. If you want to see just the biological assembly, that will be shown by default. To change which assembly is displayed, use the Structure panel in the top right:

![image](https://user-images.githubusercontent.com/21145776/121070240-bfccea00-c7ce-11eb-8017-bb7792c565bb.png)

**Comment by isaphan** [comment]
Thanks David, this was baffling but I get it now.

Another issue: How do I fit a structure into a map?

I have to say I have been using structure viewers for over 20 years and this one is the most baffling I have ever used. I spent over an hour trying to figure things out and got NOWHERE. THen I wasted another half hour on the docs and still got NOWHERE.

So so so frustrating!!!

**Comment by dsehnal** [comment]
I understand your frustration and that some features might be somewhat non-intuitive and/or have missing documentation (there is indeed no mention of the volumes in the docs which is an omission).

To do this in the default viewer, enable ``Volume Streaming`` and click on a residue:

![image](https://user-images.githubusercontent.com/21145776/121085583-5a82f400-c7e2-11eb-9a41-13c3b1ee30ef.png)

Good news is that the viewer at molstar.org is more about showing all the available functionality of the viewer. Individual Mol* integrations often provide better and more targeted user experience. For example, the RCSB/PDBe integrations load the experimental maps automatically and clicking on a residue (or selection to show the map around the whole structure) will work by default:

- https://www.rcsb.org/3d-view/2VRE?preset=electronDensityMaps
- https://www.ebi.ac.uk/pdbe/entry/view3D/2vre/?view=entry_index&viewer=litemol&assembly=1

**Comment by isaphan** [comment]
Sorry I was not clear: what I am trying to do is fit the PDB atomic coordinates into a Cryo-EM map that I have uploaded from my computer, i.e. the equivalent of ‘Fit in Map’ in Chimera.
Thanks,

Isabelle

**Comment by arose** [comment]
> Sorry I was not clear: what I am trying to do is fit the PDB atomic coordinates into a Cryo-EM map that I have uploaded from my computer, i.e. the equivalent of ‘Fit in Map’ in Chimera.

Hi @isaphan, that feature is not supported in Mol*. Generally anything related to building or editing models is so far beyond the scope of the project.

That said I can imagine to add a rigid fit/align method that just tries to maximize the overlap or correlation between map/map or map/structure (converted to map).

**Comment by isaphan** [comment]
I understand, thanks for your help!

Isabelle
