### ISSUE TITLE
Recommended/ Default Styling

### ISSUE THREAD

**Issue by ianconrad** [molstar/molstar#208]
I was wondering what styling is required to configure this like pretty much any of the examples. I'm looking to actually be able to specify the canvas width and height and have the controls appear both on the canvas and have them be styled. It doesn't seem like many of the examples actually include explicit styling or overwrites of the default styling ([alpha-orbitals](https://github.com/molstar/molstar/blob/master/src/examples/alpha-orbitals/index.ts)).
Here's what the default looks like when I render this just using the standard documentation for the plugin-ui. I have included a couple relevant snippets below. I haven't found any other example or instance that renders like this, and I want to confirm if that is on my end or not.
<img width="787" alt="Screen Shot 2021-06-08 at 11 48 57 AM" src="https://user-images.githubusercontent.com/65552264/121217351-c18ac200-c84f-11eb-8050-d0f5d27b1a60.png">
<img width="751" alt="Screen Shot 2021-06-08 at 11 49 07 AM" src="https://user-images.githubusercontent.com/65552264/121217354-c18ac200-c84f-11eb-9019-8595f6f2e0a7.png">
The width and height here are about 1 to 1 as passed in by props, but it looks like the vast majority of the height is being allocated for the controls. 

Config:
```
const MySpec = {
  ...defaultSpecs,
  config: [
    [PluginConfig.VolumeStreaming.Enabled, false],
    [PluginConfig.Viewport.ShowControls, false],
    [PluginConfig.Viewport.ShowExpand, false],
    [PluginConfig.Viewport.ShowSelectionMode, false],
    [PluginConfig.Viewport.ShowSettings, true],
  ],
  components: {
    ...defaultSpecs.components,
    hideTaskOverlay: false,
    controls: { left: 'none', right: 'none', top: 'none', bottom: 'none' },

    remoteState: 'none',
  },
  layout: {
    initial: {
      isExpanded: false,
      showControls: true,
    },
  },
}
```

Component Render:
```
 return (
    <div
      style={{
        position: 'relative',
        top: 0,
        left: 0,
        width: width,
        height: height,
      }}
    >
      <div
        id={'molstar-parent'}
        ref={parent}
        style={{
          width: width,
          height: height,
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
        }}
      />
    </div>
  )
```

In the above, the parent ref is being passed to the injection div and is initialized exactly as it is in the documentation for react-ui ([https://molstar.org/docs/plugin/](url))

**Comment by dsehnal** [comment]
Have you included the styles? E.g. https://github.com/molstar/molstar/blob/master/src/examples/alpha-orbitals/index.ts#L26 ? This also requires using WebPack.

Alternatively, you can get ``molstar.css`` for example from the ``build/viewer`` directory.

--------------

One comment regarding the custom sizing: you might have to call ``PluginContext.handleResize`` by hand after custom resize for the canvas to update properly, e.g. something along the lines of:

```ts
useEffect(() => plugin.handleResize(), [width, height]);
```

**Comment by ianconrad** [comment]
Including the `molstar.css` file totally did the trick. I tried including the `.scss` yesterday, and it didn't have an effect. I think this has to do with my webpack config that didn't have a rule for scss files as this is the first time I've run into these. Thanks for the help!
