### ISSUE TITLE
Questions about selection criteria

### ISSUE THREAD

**Issue by ianconrad** [molstar/molstar#209]
Hi,

The issue I'm facing at the moment is taking the region from a selection query, updating its representation, and then updating the state tree/visualization. I'm sort of mirroring an approach taken in this [issue](https://github.com/molstar/molstar/issues/120). Here is the selection criterion and attempted rendering I'm trying:
```
  const sel = MS.struct.filter.first([
    MS.struct.generator.atomGroups({
      'residue-test': MS.core.rel.eq([MS.struct.atomProperty.macromolecular.label_comp_id(), 160]),
    })
  ]);

  let group = update.to(assembly).group(StateTransforms.Misc.CreateGroup, {label: 'TEST'}, {ref: 'TEST'})

  group.apply(StateTransforms.Model.StructureSelectionFromExpression, {label: 'Surroundings', expression: sel})
    .apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(plugin, obj.data, {
      type: 'ball-and-stick',
      color: 'uniform',
      colorParams: {value: ColorNames.aliceblue}
    }), {tags: ['labely']})
  await PluginCommands.State.Update(plugin, {state: plugin.state.data, tree: group})
  
  await update.commit()
```

As for initialization of the plugin, that is following the recommended structure with an explicit url
```
  const model = await plugin.builders.structure.createModel(trajectory)
  const structure = await plugin.builders.structure.createStructure(model)
  const update = plugin.build()
  let assembly = plugin.state.select(StateSelection.Generators.ofType(PluginStateObject.Molecule.Structure))[0]
  //let assembly = plugin.managers.structure.hierarchy.current.structures[0]?.cell
  let obj = assembly.obj
```

I assume my issue has to do with selection of the assembly used in `update.to(...)`, but I really don't know what it should be instead. Any help would be much appreciated

**Comment by dsehnal** [comment]
Hi,

This should do the trick:

```ts
const _selection = group.apply(StateTransforms.Model.StructureSelectionFromExpression, {label: 'Surroundings', expression: sel});
selection.apply(StateTransforms.Representation.StructureRepresentation3D, ...);

const selection = _selection.selector;

// .... later

const update = plugin.build();
update.to(selection).update(newParams);
await update.commit();
```

The rest of the tree will update automatically.

**Comment by ianconrad** [comment]
I left the implementation of group based off the assembly I listed above and it seems like this line is the breaking line:
```
let assembly = plugin.state.select(StateSelection.Generators.ofType(PluginStateObject.Molecule.Structure))[0]
```
This is used in defining group as:
```
let group = update.to(assembly).group(StateTransforms.Misc.CreateGroup, {label: 'TEST'}, {ref: 'TEST'})
```

Were there any changes needed to these definitions? I also tried doing `let assembly = plugin.state.data.select(...)[0]` instead, but it seems like both variants of this line break the visualization (no error, just nothing shown). Also, for the newParams, should that mirror the params passed to the` createStructureRepresentation()` call from the original code I included?

**Comment by dsehnal** [comment]
Right, sorry, I misunderstood what you are trying to do. You cannot change representation of selection, you can only add an existing one.

This code definitely works:

```ts
async test() {
    const plugin = this.plugin;
    const _data = await plugin.builders.data.download({ url: 'https://www.ebi.ac.uk/pdbe/entry-files/download/1tqn.bcif', isBinary: true });
    const trajectory = await plugin.builders.structure.parseTrajectory(_data, 'mmcif');
    const model = await plugin.builders.structure.createModel(trajectory);
    const structure = await plugin.builders.structure.createStructure(model);

    const sel = MS.struct.generator.atomGroups({
        'residue-test': MS.core.rel.eq([MS.struct.atomProperty.macromolecular.label_comp_id(), 'ALA']),
    });

    const update = plugin.build();

    update.to(structure)
        .apply(StateTransforms.Model.StructureSelectionFromExpression, { label: 'Surroundings', expression: sel })
        .apply(StateTransforms.Representation.StructureRepresentation3D, createStructureRepresentationParams(plugin, structure.data, {
            type: 'ball-and-stick',
            color: 'uniform',
            colorParams: { value: ColorNames.aliceblue }
        }));

    await update.commit();
}
```

It creates a selection of all ALA residues and shows them as balls and sticks. One of the errors you made was that you tried to compare ``label_comp_id`` to ``160``. However, the ``label_comp_id`` is the string name of the residue, not the index. If you want the index, you need to use ``label_seq_id``.

**Comment by ianconrad** [comment]
This worked straight out of the box. Thanks for the help!
