### ISSUE TITLE
Inconsistent state for density channels

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#210]
**Steps to reproduce**

1. Load 1TQN
2. Enable Volume Streaming
3. Disable some channel, e.g. Fo-Fc(+ve)
4. Focus on HEM ligand

The manipulated channel will show visuals but the UI indicates it's still hidden. 

<img width="1680" alt="channels" src="https://user-images.githubusercontent.com/9744615/121608532-0b69d880-ca07-11eb-9553-e2cf60b50976.png">

Thanks for having a look!

**Comment by dsehnal** [comment]
Should be fixed in 4853ff7a1ae2a90369d46a8b838435700f5f8cc3.

**Comment by JonStargaryen** [comment]
Thanks David, this works nicely!

**Comment by JonStargaryen** [comment]
There was some regression here and now it's back to the inconsistent behavior described above.
No code changes stand out to me and `visible` seems to be applied correctly.
