### ISSUE TITLE
Selecting disulfide bridges throws a TypeError

### ISSUE THREAD

**Issue by sukolsak** [molstar/molstar#211]
Steps to reproduce:
1. Load 6VXX
2. Use the selection mode
3. Click the "Add/Union Selection" button
4. Click "Bond Property" > "Disulfide Bridges"

You will see a TypeError in the console.

**Comment by arose** [comment]
@dsehnal could you have a look, please?

**Comment by dsehnal** [comment]
Thanks for the report. Should be fixed in 53d3480.

**Comment by sukolsak** [comment]
Thanks! It's fixed.
