### ISSUE TITLE
Loss of outline when camera is set to orthographic 

### ISSUE THREAD

**Issue by somasushma** [molstar/molstar#213]
The current version of the viewer does not render the outline when the camera is set to orthographic. This especially apparent when clipping is set to a low value. Could this be fixed?

**Comment by arose** [comment]
Thanks for reporting this. I can reproduce this and we will look into fixing it.

**Comment by arose** [comment]
Hi @somasushma, this is fixed in 9ec0f9e736759d155cb0310f1b4a42e8e945f89a and release in 2.1.0. Please let us now if it works for you. Thanks.

**Comment by somasushma** [comment]
> Hi @somasushma, this is fixed in [9ec0f9e](https://github.com/molstar/molstar/commit/9ec0f9e736759d155cb0310f1b4a42e8e945f89a) and release in 2.1.0. Please let us now if it works for you. Thanks.

Thank you: it is working fine now.
