### ISSUE TITLE
Displaying hydrogen bonds starting from donor hydrogen

### ISSUE THREAD

**Issue by ManuelSe** [molstar/molstar#214]
Hi! I am trying to implement Mol* into a website to visualize protein-ligand complexes obtained from docking. As my structures contain explicit hydrogen atoms, I'd like to display the hydrogen bonds between the donor hydrogen and acceptor hetero atom.
The default behavior is that the hydrogen bonds are shown between the hetero atoms of donor and acceptor. Is there a way to change this (in Javascript)?

**Comment by arose** [comment]
Hi @ManuelSe, that is not possible at present. Would you be interested in implementing this?

**Comment by arose** [comment]
done in v3.35.0
