### ISSUE TITLE
How to display channels from MOLE2

### ISSUE THREAD

**Issue by jingyile** [molstar/molstar#216]
sorry, I want to know how to display channels, how to load channel data？

**Comment by arose** [comment]
Hi @jingyile, molstar cannot calculate channels itself (but it does calculate molecular surfaces). What format is your channel data in?

**Comment by jingyile** [comment]
> Hi @jingyile, molstar cannot calculate channels itself (but it does calculate molecular surfaces). What format is your channel data in?

thanks for your reply, my channel data is exported by Mole2( #http://webchem.ncbr.muni.cz/Platform/App/Mole). Many formats are available, such as CSV, JSON, Pymol. I don't know which is better to display channels.

**Comment by arose** [comment]
This is related to https://github.com/dsehnal/LiteMol/issues/70, right?

Mol* does not support reading/displaying Mole2 results. However it is possible to write an extension. Would you be interested in writing one?

**Comment by jingyile** [comment]
> This is related to [dsehnal/LiteMol#70](https://github.com/dsehnal/LiteMol/issues/70), right?
> 
> Mol* does not support reading/displaying MOLE2 results. However it is possible to write an extension. Would you be interested in writing one?

Yes！I'll try if I have time！ Thanks！
