### ISSUE TITLE
How to show label for water oxygens for pdb files ?

### ISSUE THREAD

**Issue by jiucenglou** [molstar/molstar#218]
When we use Mol* to view pdb files, labels can be added for non-water atoms but not water oxygens. 
Is it possible to show label for water oxygens ? Residue id of the selected water oxygen would be more than enough.

**Comment by dsehnal** [comment]
Do you want to do this in code or just by hand is enough?

If by hand is enough, you can use the selection mode to achieve this:

![image](https://user-images.githubusercontent.com/21145776/123921983-dd354400-d987-11eb-9aa7-4e6f71788429.png)

**Comment by jiucenglou** [comment]
> Do you want to do this in code or just by hand is enough?
> 
> If by hand is enough, you can use the selection mode to achieve this:
> 
> ![image](https://user-images.githubusercontent.com/21145776/123921983-dd354400-d987-11eb-9aa7-4e6f71788429.png)

It looks that what you have demonstrated is not for water oxygen ? :D

**Comment by dsehnal** [comment]
I see. I misunderstood your question. Just add "Label" representation to the "Water" component:

![image](https://user-images.githubusercontent.com/21145776/124025639-fe7e4a80-d9f0-11eb-9615-17c7adf76e66.png)

It should work for any selection and you can select the label level between atom/residue/chain in the "Advanced Type" options later.
