### ISSUE TITLE
How to load .xyz from url ?

### ISSUE THREAD

**Issue by jiucenglou** [molstar/molstar#219]
I am trying to load .xyz from URL. I have tested [a Dropbox url](https://www.dropbox.com/s/bsf7q0fkd3fbooh/AbstractH__9A__6__H43O3_150_TS.out.xyz) and [a Slack url](https://files.slack.com/files-pri/T0183C5JUDT-F026UK737KK/abstracth__9a__6__h43o3_150_ts.out.xyz) but Mol* does not show the molecule. Could you suggest how to load .xyz from url ?

The log at the bottom of the webpage shows the following 
```
10:58:29 Failed to download data. Possible reasons: Resource is not available, or CORS is not allowed on the server.
10:58:29 Error: Invalid data cell.
```

**Comment by dsehnal** [comment]
You need to host your molecule file somewhere that supports cross-origin requests (CORS), otherwise the browser won't be able to load the data.

**Comment by jiucenglou** [comment]
> You need to host your molecule file somewhere that supports cross-origin requests (CORS), otherwise the browser won't be able to load the data.

Thank you for explaining the underlying reason. 
Unfortunately, after checking, I think neither Dropbox, Slack, or Google Drive  supports CORS...

**Comment by dsehnal** [comment]
Well, the Dropbox URL doesn't point to the file itself and the Slack URL requires a login to access, so neither of these will work. If you want CORS, you might have to use Google Cloud or Amazon S3 or something along the lines where you can allow CORS.

**Comment by jiucenglou** [comment]
> allow CORS

Thank you for your helpful comments !
It looks like that wget or curl can download the .xyz file using the Dropbox url, probably by following redirections.
I am wondering if it is possible for `Mol*` to do that ?

**Comment by arose** [comment]
Hi @jiucenglou, CORS is a set of security restriction in web browser that allow you to safely browse the internet. Command line tools like wget or curl do not have/need such protections. In addition to the services @dsehnal suggested there is also Github pages which is essentially free (if you don't have much traffic).

In principal you can write a web application that authenticates with Slack or Dropbox and get the files from there but that means visitors need to have an account with Slack or Dropbox and it is outside the scope of Mol*.
