### ISSUE TITLE
How to share Mol* viewer state using URL ?

### ISSUE THREAD

**Issue by jiucenglou** [molstar/molstar#220]
After one loads .pdb/.xyz in `https://molstar.org/viewer/`, zoom, rotate, and label important distances, is it possible to share the viewer state using URL to other people so that they can click the URL and then see and manipulate (on their own browser) ? :D

It looks like right now Mol* allows one to download state/session to local files, after which one can send the downloaded files to colleagues.  The state downloaded is quite large, probably too large to be embedded in URL ? :D

**Comment by dsehnal** [comment]
You cannot embed in the URL, but you can host the file anywhere (with CORS) and link to it in the URL.

This is how we do it on https://molstar.org to load the states from the landing page:

- https://github.com/molstar/molstar.github.io/blob/master/index.html#L142
- https://github.com/molstar/molstar.github.io/tree/master/demos/states

**Comment by jiucenglou** [comment]
> You cannot embed in the URL, but you can host the file anywhere (with CORS) and link to it in the URL.
> 
> This is how we do it on https://molstar.org to load the states from the landing page:
> 
> * https://github.com/molstar/molstar.github.io/blob/master/index.html#L142
> * https://github.com/molstar/molstar.github.io/tree/master/demos/states

Thank you for your helpful comments and [documentation](https://molstar.org/viewer-docs/query-parameters) !
