### ISSUE TITLE
How to export a pdb or sdf file?

### ISSUE THREAD

**Issue by Barret-ma** [molstar/molstar#223]
Hi，I would like to export pdb or sdf file. How can I export a pdb or sdf file?

**Comment by dsehnal** [comment]
Hi. 

In what context would you like to export these structures? Fully supported export is currently only available for mmCIF format with some limited support for MOL/SDF/MOL2 formats.

- If mmCIF is enough for you, you can just call the ``to_mmCIF`` function from https://github.com/molstar/molstar/blob/master/src/mol-model/structure/export/mmcif.ts#L250.
- For the other formats:

```ts
function write(name: string, structure: Structure) {
    const enc = MolWriter.createEncoder();  // Mol2Writer/SdfWriter
    enc.startDataBlock(name);
    encode_mmCIF_categories(enc, structure);
    return enc.getData();
}
```

should do the trick. (source and params for the other encoders is in https://github.com/molstar/molstar/blob/master/src/mol-io/writer)

David

**Comment by Barret-ma** [comment]
Thank you very much for you reply @dsehnal , it`s very useful to me.
