### ISSUE TITLE
How to Render Molstar Visualization as React Component

### ISSUE THREAD

**Issue by QuantumTCode** [molstar/molstar#226]
I'm trying to embed a molstar visualization in my react code, but I have been having difficulty parsing through documentation to figure out how to do this. Any assistance would be greatly appreciated!

**Comment by samirelanduk** [comment]
I recently started a library for doing just this - [molstar-react](https://github.com/samirelanduk/molstar-react). It's pretty basic at the moment - it only supports the prebuilt Molstar Viewer - but it will become more developed over time.

**Comment by dsehnal** [comment]
This depends on whether you want to use the built in react UI or not, and how the rest of your app structured.

For basic usage something along these lines should do the trick (modified version from https://molstar.org/docs/plugin.html) :

```ts
function MolStarWrapper({ url: string }) {
    const parent = React.createRef<HTMLDivElement | null>();
    const [initialized, setInitialized] = React.useState(false);
    const plugin = React.useRef<PluginContext | null>();

    useEffect(() => {
        async function init() {
            plugin.current = await createPluginAsync(parent.current, /* plugin spec with say initial layout */);
            setInitialized(true);
        }
        init();
        return () => { plugin.current?.dispose(); plugin.current = null; };
    }, []);
    
    useEffect(() => {
        if (!initialized || !plugin.current) return;
        
        // sync state here
    }, [initialized, url]);

    return <div ref={parent} style={{ width: 640, height: 480 }} />;
}
```

Depending on the complexity of what you are trying to achieve, I usually create a separate a separate class that handles the Mol* state syncing for the particular instance, e.g.

```ts
export class MyMolStarWrapper {
  plugin?: PluginContext;

  async init(target: HTMLElement) {
    // ...
  }

  async syncState(state: MyState) {
    // ....
  }
}
```

Using [rxjs](https://www.npmjs.com/package/rxjs) to pass some state around was also useful for me in the past.

---------------

@samirelanduk Thanks for taking the time to do the react wrapper. You code contains a bug where a new instance of the viewer is created on every single re-render, and without disposing the previous one. The code above should point you in the right direction.

**Comment by QuantumTCode** [comment]
Interesting, thank you for the assist! I currently have a string representation of the PDB I would like to display, how would I display that through this wrapper based on this implementation?

**Comment by dsehnal** [comment]
> 
> 
> Interesting, thank you for the assist! I currently have a string representation of the PDB I would like to display, how would I display that through this wrapper based on this implementation?

Something along these lines: https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.ts#L188

**Comment by QuantumTCode** [comment]
Thank you for the resources! I have been trying to get the initial code working, but have been unable to debug a specific section of it, does this run for you? — I am getting an Unexpected Token error on this line: 
`const parent = React.createRef<HTMLDivElement | null>();`

In what context should I run/implement this function?

**Comment by samirelanduk** [comment]
The `<` is typescript, and that is probably the unexpected token - if you're just using plain javascript you can omit the `<HTMLDivElement | null>`.

**Comment by QuantumTCode** [comment]
Thanks again! I got it loaded into my component, but am having issues with the actual display of the molstar plugin. 

I set my spec to: 

`const MySpec = {
  ...DefaultPluginUISpec(),
  config: [
    [PluginConfig.VolumeStreaming.Enabled, false],
    [PluginConfig.Viewport.ShowExpand, false],
    [PluginConfig.Viewport.ShowControls, false],
    [PluginConfig.Viewport.ShowSettings, false],
    [PluginConfig.Viewport.ShowAnimation, false],
  ],
};`

and also set it in the wrapper as:

`async function init() {
      plugin.current = await createPluginAsync(parent.current, MySpec);
      setInitialized(true);
    }`

But when it actually displays on the frontend, its not interactable and my custom specs don't seem to be updated:

<img width="627" alt="Screen Shot 2021-07-27 at 1 56 03 PM" src="https://user-images.githubusercontent.com/22753813/127203988-8701eac9-1307-4a7a-b293-926be33a4958.png">

**Comment by dsehnal** [comment]
It seems you are missing the CSS. Either include the ``molstar.css`` to the HTML template or ``import/require`` ``molstar/lib/mol-plugin-ui/skin/light.scss`` or ``molstar/build/viewer/molstar.css``. Importing the (s)css might require some additional webpack config.

---------

Also, the ``[PluginConfig.Viewport.ShowControls, false]`` setting is for showing the controls toggle button (what a misleading name :) ). To hide the control panels, adding ``layout: { initial: { showControls: false } }`` to the spec will do the trick.

**Comment by QuantumTCode** [comment]
Amazing — thank you all so much, I got the plugin set up! 

Finally, I'm trying to load in the data and tried basing the data load-in on the Viewer class `loadStructureFromData ` function, but it is not working cleanly, does it need me to define a new class or is there any other implementation I need to do?

**Comment by dsehnal** [comment]
I would need see more code to be able to help you here.

**Comment by QuantumTCode** [comment]
Gotcha, the base code is very similar to what you had above:

`const MySpec = {
  ...DefaultPluginUISpec(),
  config: [
    [PluginConfig.VolumeStreaming.Enabled, false],
    [PluginConfig.Viewport.ShowExpand, false],
    [PluginConfig.Viewport.ShowControls, false],
    [PluginConfig.Viewport.ShowSettings, false],
    [PluginConfig.Viewport.ShowAnimation, false],
  ],
  layout: { initial: { showControls: false } },
};

const MolstarRender = (props) => {
  const { pdbId, url, options } = props;
  const parent = React.createRef();
  const [initialized, setInitialized] = React.useState(false);
  const plugin = React.useRef();

  useEffect(() => {
    async function init() {
      plugin.current = await createPluginAsync(parent.current, MySpec);
      setInitialized(true);
    }
    init();

    return () => {
      plugin.current?.dispose();
      plugin.current = null;
    };
  }, []);

  useEffect(() => {
    if (!initialized || !plugin.current) return;

    // sync state here
  }, [initialized, pdbId, url]);

  async function loadStructureFromData(data, format, options) {
    const _data = await plugin.builders.data.rawData({
      data,
      label: options?.dataLabel,
    });
    const trajectory = await plugin.builders.structure.parseTrajectory(
      _data,
      format
    );
    await plugin.builders.structure.hierarchy.applyPreset(
      trajectory,
      "default"
    );
  }

  return <div ref={parent}/>;
};`

and I tried methods of plugging in the data like:

` async loadStructureFromData(data: string | number[], format: BuiltInTrajectoryFormat, options?: { dataLabel?: string }) {
        const _data = await this.plugin.builders.data.rawData({ data, label: options?.dataLabel });
        const trajectory = await this.plugin.builders.structure.parseTrajectory(_data, format);
        await this.plugin.builders.structure.hierarchy.applyPreset(trajectory, 'default');
    }
` and also: 
`
    loadPdb(pdb: string, options?: LoadStructureOptions) {
        const params = DownloadStructure.createDefaultParams(this.plugin.state.data.root.obj!, this.plugin);
        const provider = this.plugin.config.get(PluginConfig.Download.DefaultPdbProvider)!;
        return this.plugin.runTask(this.plugin.state.data.applyAction(DownloadStructure, {
            source: {
                name: 'pdb' as const,
                params: {
                    provider: {
                        id: pdb,
                        server: {
                            name: provider,
                            params: PdbDownloadProvider[provider].defaultValue as any
                        }
                    },
                    options: { ...params.source.params.options, representationParams: options?.representationParams as any },
                }
            }
        }));
    }`

but neither of them ran properly. Any help would be greatly appreciated!

**Comment by dsehnal** [comment]
You are not calling the ``loadStructureFromData`` function anywhere in the code you posted above.

**Comment by QuantumTCode** [comment]
Oops forgot to send that version — this is the version that's giving me an error, I think it is saying that plugin.builders does not exist:

```
const MolstarRender = (props) => {
  const { pdb, options } = props;
  const parent = React.createRef();
  const [initialized, setInitialized] = React.useState(false);
  const plugin = React.useRef();

  useEffect(() => {
    async function init() {
      plugin.current = await createPluginAsync(parent.current, MySpec);
      setInitialized(true);
    }
    init();

    return () => {
      plugin.current?.dispose();
      plugin.current = null;
    };
  }, []);

  useEffect(() => {
    if (!initialized || !plugin.current) return;
    loadStructureFromData(pdb, 'pdb')
    // sync state here
  }, [initialized, pdb]);

  async function loadStructureFromData(data, format, options) {
    const _data = await plugin.builders.data.rawData({
      data,
      label: options?.dataLabel,
    });
    const trajectory = await plugin.builders.structure.parseTrajectory(
      _data,
      format
    );
    await plugin.builders.structure.hierarchy.applyPreset(
      trajectory,
      "default"
    );
  }

  return <div ref={parent} />;
};
```

**Comment by dsehnal** [comment]
``plugin.`` => ``plugin.current.``

**Comment by QuantumTCode** [comment]
Oh! That was it — it's working great now, thank you so much for all the help!

One last small thing I'm trying to get working is the ['uncertainty' color theme](https://github.com/molstar/molstar/blob/master/src/mol-theme/color/uncertainty.ts), is there an easy way to change the color scale, scale direction, and other base params?

This is the way I tried to modify it:

```
    const model = await plugin.current.builders.structure.createModel(trajectory);
    const structure = await plugin.current.builders.structure.createStructure(model)

    const components = {
      polymer: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'polymer'),
      ligand: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'ligand'),
      water: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'water'),
    };

    const builder = plugin.current.builders.structure.representation;
    const update = plugin.current.build();

    const myUncertaintyColorThemeParams = {
      domain: PD.Interval([0, 100]),
      list: PD.ColorList('turbo', { presetKind: 'scale' }),
    };
    function mygetUncertaintyColorThemeParams(ctx) {
      return myUncertaintyColorThemeParams; // TODO return copy
    };

    const myUncertaintyColorThemeProvider = {
      ...UncertaintyColorThemeProvider,
      getParams: mygetUncertaintyColorThemeParams,
      defaultValues: PD.getDefaultValues(myUncertaintyColorThemeParams)
    };

    if (components.polymer) builder.buildRepresentation(update, components.polymer, { type: 'cartoon', color: myUncertaintyColorThemeProvider }, { tag: 'polymer' });
    if (components.ligand) builder.buildRepresentation(update, components.ligand, { type: 'ball-and-stick' }, { tag: 'ligand' });
    if (components.water) builder.buildRepresentation(update, components.water, { type: 'ball-and-stick', typeParams: { alpha: 0.6 } }, { tag: 'water' });
    
```

**Comment by dsehnal** [comment]
You can just do ``{ ... color: 'uncertainty' ...  }`` and it will use the default params; add ``{ ... colorParams: { kind: ??, colors: ?? } ... }``.

The kind/colors can be obtained for example like this (from ``ParamDefinition.ColorList``):

```ts
        let def: ColorList['defaultValue'];
        if (typeof defaultValue === 'string') {
            const colors = getColorListFromName(defaultValue);
            def = { kind: colors.type !== 'qualitative' ? 'interpolate' : 'set', colors: colors.list };
        } else {
            def = defaultValue;
        }
```

**Comment by QuantumTCode** [comment]
I tried something like this, but it's still showing the default colors — Is this the correct implementation?:

```
const colors = getColorListFromName('turbo');
    let def = { kind: colors.type !== 'qualitative' ? 'interpolate' : 'set', colors: colors.list };

    if (components.polymer) builder.buildRepresentation(update, components.polymer, { type: 'cartoon', color: 'uncertainty', colorParams: def }, { tag: 'polymer' });
    if (components.ligand) builder.buildRepresentation(update, components.ligand, { type: 'ball-and-stick' }, { tag: 'ligand' });
    if (components.water) builder.buildRepresentation(update, components.water, { type: 'ball-and-stick', typeParams: { alpha: 0.6 } }, { tag: 'water' });
```

**Comment by dsehnal** [comment]
That looks correct. How are you applying it? Have you removed the hierarchy manager call?

**Comment by QuantumTCode** [comment]
I don't believe I have the hierarchy manager call — this is my latest code:

```
const MolstarRender = (props) => {
  const { pdb, options } = props;
  const parent = React.createRef();
  const [initialized, setInitialized] = React.useState(false);
  const plugin = React.useRef();

  useEffect(() => {
    async function init() {
      plugin.current = await createPluginAsync(parent.current, MySpec);
      setInitialized(true);
    }
    init();

    return () => {
      plugin.current?.dispose();
      plugin.current = null;
    };
  }, []);

  useEffect(() => {
    if (!initialized || !plugin.current) return;
    loadStructureFromData(pdb, 'pdb')
    // sync state here
  }, [initialized, pdb]);

  async function loadStructureFromData(data, format, options) {
    const _data = await plugin.current.builders.data.rawData({
      data,
      label: options?.dataLabel,
    });
    const trajectory = await plugin.current.builders.structure.parseTrajectory(
      _data,
      format
    );
    const model = await plugin.current.builders.structure.createModel(trajectory);
    const structure = await plugin.current.builders.structure.createStructure(model)

    const components = {
      polymer: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'polymer'),
      ligand: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'ligand'),
      water: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'water'),
    };

    const builder = plugin.current.builders.structure.representation;
    const update = plugin.current.build();

    const colors = getColorListFromName('turbo');
    let def = { kind: colors.type !== 'qualitative' ? 'interpolate' : 'set', colors: colors.list };

    if (components.polymer) builder.buildRepresentation(update, components.polymer, { type: 'cartoon', color: 'uncertainty', colorParams: def }, { tag: 'polymer' });
    if (components.ligand) builder.buildRepresentation(update, components.ligand, { type: 'ball-and-stick' }, { tag: 'ligand' });
    if (components.water) builder.buildRepresentation(update, components.water, { type: 'ball-and-stick', typeParams: { alpha: 0.6 } }, { tag: 'water' });

    await update.commit();
  }

  return <div ref={parent} />;
};
```

**Comment by dsehnal** [comment]
I've just tested this code (same as yours, only the data source is different) in the "embedded" viewer: 

```ts
async loadStructureTest(url: any, format: any) {
    const plugin = { current: this.plugin };
    const _data = await plugin.current.builders.data.download({ url }, { state: { isGhost: true } });
    const trajectory = await plugin.current.builders.structure.parseTrajectory(
        _data,
        format
    );
    const model = await plugin.current.builders.structure.createModel(trajectory);
    const structure = await plugin.current.builders.structure.createStructure(model);

    const components = {
        polymer: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'polymer'),
        ligand: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'ligand'),
        water: await plugin.current.builders.structure.tryCreateComponentStatic(structure, 'water'),
    };

    const builder = plugin.current.builders.structure.representation;
    const update = plugin.current.build();

    const colors = getColorListFromName('turbo');
    let def = { kind: colors.type !== 'qualitative' ? 'interpolate' : 'set', colors: colors.list };

    if (components.polymer) builder.buildRepresentation(update, components.polymer, { type: 'cartoon', color: 'uncertainty', colorParams: def }, { tag: 'polymer' });
    if (components.ligand) builder.buildRepresentation(update, components.ligand, { type: 'ball-and-stick' }, { tag: 'ligand' });
    if (components.water) builder.buildRepresentation(update, components.water, { type: 'ball-and-stick', typeParams: { alpha: 0.6 } }, { tag: 'water' });

    await update.commit();
}

// ......

viewer.loadStructureTest('https://files.rcsb.org/download/1TQN.pdb', 'pdb');
```

and it shows 

![image](https://user-images.githubusercontent.com/21145776/127640606-c546c317-8977-4e23-8a10-a138d43016c9.png)

which looks correct to me.

It maybe your PDB input doesn't have the temperature/b-factor column assigned correctly?

**Comment by QuantumTCode** [comment]
I see, apologies for not being more clear, the protein is modeled properly on my end too, but the updated color map (turbo) is not applied properly — the default color mapping for 'uncertainty' is displayed.

**Comment by dsehnal** [comment]
Right, ``const colorParams = { list: { kind: colors.type !== 'qualitative' ? 'interpolate' : 'set', colors: colors.list } };`` =>

![image](https://user-images.githubusercontent.com/21145776/127642842-19cebfb2-8e98-4453-923f-c1b522550886.png)

--------------

If you have some spare time, would you be willing to turn this thread into a docs topic and make a PR at https://github.com/molstar/docs ?

**Comment by QuantumTCode** [comment]
Amazing! It's working great — I'd be glad to convert this into a docs topic!

**Comment by QuantumTCode** [comment]
Another quick thing, just wondering if there's a way to modify the hover label without messing with the package code directly — I got this code to display the uncertainty with hover working when I modify the [label.ts code](https://github.com/molstar/molstar/blob/b53debcfef324066f71ba0f60a8b3f45ef6f2a31/src/mol-theme/label.ts#L234) directly, like so:

```
function _atomicElementLabel(location, granularity, hideOccupancy) { 
...
var uncertainty = location.unit.model.atomicConformation.B_iso_or_equiv.value(location.element)
...
case 'residue':
            var seq_id = label_seq_id === auth_seq_id || !has_label_seq_id ? auth_seq_id : label_seq_id;
            label.push("Value: " + uncertainty);
...
```

It would be awesome if there's a way to do this without direct editing, but I couldn't figure out anything clear after looking through the package.

**Comment by dsehnal** [comment]
``this.plugin.managers.lociLabels.addProvider(...);``. Seaching the code for ``lociLabels.addProvider`` should yield enough examples.

**Comment by QuantumTCode** [comment]
Perfect, that got it working — thanks again!

**Comment by arose** [comment]
> Amazing! It's working great — I'd be glad to convert this into a docs topic!

@QuantumTCode this would be much appreciated! We have repo for developer docs (https://github.com/molstar/docs). Going to close this issue for now. Please feel free to open more ith new questions or suggestions. Thanks.
