### ISSUE TITLE
Color a loci range programmatically for integration  

### ISSUE THREAD

**Issue by singhindresh** [molstar/molstar#227]
Greetings,

  Is there any existing documentation or example which demonstrate how to set the color of a loci range programmatically?

Thanks
 Indresh

**Comment by dsehnal** [comment]
Hi Indresh,

Convert the Loci into a bundle and use [OverpaintStructureRepresentation3DFromBundle ](https://github.com/molstar/molstar/blob/ae2f2e7d0e59665857cb6d358bba3ea8ac767175/src/mol-plugin-state/transforms/representation.ts#L357). The overpaint is applied to a representation node. [Here's](https://github.com/molstar/molstar/blob/b53debcfef324066f71ba0f60a8b3f45ef6f2a31/src/mol-plugin-state/helpers/structure-overpaint.ts#L21) one way to use it. 

If you want something more sophisticated, you will need to create your own theme. Non trivial example is coloring based on [residue validation](https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/color.ts#L90). The theme also needs to be [registered](https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/behavior.ts#L51) to be used.

David

**Comment by singhindresh** [comment]
Hi David, 

   We are able to select a color but we would like to select features by coordinate and highlight with different color. Also, similar question in https://github.com/molstar/molstar/issues/233.
 What is the best approach to accomplish it programmatically? Below is example 
![image](https://user-images.githubusercontent.com/275604/127559736-ae9ac8be-1e95-4ccc-9e73-6d9658592843.png)

Thanks
 Indresh

**Comment by dsehnal** [comment]
Can you please be more specific about what exactly are you trying to achieve? Ideally an example of how your input looks like.
