### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by JoaoRodrigues** [molstar/molstar#23]
Hi there,

Is there any documentation on how to use this code to load/visualize/manipulate structures? Even any sort of API documentation would be great!

Thanks

**Comment by adsodemelk** [comment]
Would be also very good to get an example of a  simple react app with jsx importing and rendering some of these components.

**Comment by harryjubb** [comment]
Any updates on this? Would love to try it out in the context of our app. Some related questions:

- Is the viewer React-specific or framework agnostic?
- Where is development up to? Is the code stable / usable or still under heavy development and changes? I would love to try it however without documentation / stability it's harder to justify in production over NGL.

**Comment by arose** [comment]
There is now https://molstar.org/docs/. See also #124 to discuss this further.
