### ISSUE TITLE
Access SD file data items

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#230]
Hello!

It is possible to get the data items for compounds in SD files?

I can see that in `src/mol-io/reader/sdf/parser.ts` (lines 27-63) these items are parsed by looking for lines starting with `> <` and receiving that line and following lines as data headers and data.

Unfortunately I can see later that this data is discarded and not attached to the resulting `Model` during the parsing process in `src/mol-plugin-state/transforms/model.ts` (lines 298-324). Only the `molFile` objects are destructured from each `parsed.result.compounds`.

1. Would it be possible to attach the parsed data items to the resulting `Model` objects that populate the returned `ArrayTrajectory`, perhaps in each model's `customProperties` property? Or is there another mechanism through which I should retrieve the parsed data items?
2. If the above can be done then would it be possible to update the parsing in `src/mol-io/reader/sdf/parser.ts` so that it can recognise more complex data headers such as the examples given in http://c4.cabrillo.edu/404/ctfile.pdf - page 41:
- `> <MELTING.POINT>`
- `> 55 (MD-08974) <BOILING.POINT> DT12`
- `> DT12 55`
- `> (MD-0894) <BOILING.POINT> FROM ARCHIVES`
- additionally (and most importantly to me) parsing any amount of white space after the starting `>`, e.g. `>  <data_header>`

Thanks in advance for your help.

**Comment by dsehnal** [comment]
Hi, this should addressed by #231.

**Comment by jpattle** [comment]
Looks great, thank you very much for implementing this so quickly! Do you know when this will be released?

Thanks again.

**Comment by arose** [comment]
Hi @jpattle, I just did a pre-release (2.2.0-dev.1). You can get it as molstar@next or by specifying the exact version from npm.

**Comment by jpattle** [comment]
Great, thank you very much. I'll check it out
