### ISSUE TITLE
Molstar Viewer module format - consider an ESM module ?

### ISSUE THREAD

**Issue by 0gust1** [molstar/molstar#232]
Hi, we currently use NGLviewer, but were really interested in trying to replace it by Molstar viewer.
Thanks a lot for the hard work, the viewer is really awesome !

We use svelte (via sveltekit) as an applicative framework. And when importing the viewer, we get an error : `ReferenceError: self is not defined`. It's caused by the packaging/format of the viewer, which behave as a module with side-effects. We're currently fiddling with our project config to make it work.

We may try also the https://molstar.org/docs/plugin.html#plugincontext-without-built-in-react-ui and https://molstar.org/docs/plugin.html#canvas3d-without-built-in-state-management leads too. Any hints welcome :)

It may be only a documentation issue, but having the viewer exposed as a proper ESM module would greatly improve the project interoperability and success. Hope to find a solution and will help if we can.

**Comment by arose** [comment]
The two doc pages are a good start. You might also want to look at the viewer source (https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.ts) itself. The viewer is just an app build using the molstar library which is all modules.

**Comment by 0gust1** [comment]
Thanks for the feedback! I dug a little yesterday evening: I somehow managed to make it work in an SPA context.
So far, the problem I have is caused by 2 things: 
- the way SvelteKit build work : modules are imported and evaluated in a non-browser context (even if those are not executed)
- the way the "compiled" viewer is packaged : the final module has side-effects (code is executed when the module is imported) and suppose that some browser API/objects are present.

I think it's solvable by either some webpack config adjustment and/or a shim in the right place of the viewer source code (this kind of line `export default typeof self !== 'undefined' ? (self: Window) : (({}: any): Window);`)
The problem is quite similar to this one https://github.com/mapbox/mapbox-gl-js/issues/4593 (CW: thread is confuse).

I'll keep digging and will post my findings here (I'm quite motivated to make a Svelte wrapper component for the Molstar viewer :) )

**Comment by arose** [comment]
> I'll keep digging and will post my findings here (I'm quite motivated to make a Svelte wrapper component for the Molstar viewer :) )

thanks, please do and feel free to point out offending parts in the code

**Comment by dsehnal** [comment]
Hi @0gust1,

if you want to evalute mol* code in nodejs (assuming the issue is similar to the one you [linked](https://github.com/mapbox/mapbox-gl-js/issues/4593), it might work by importing CommonJS build of Mol*: ``import ??? from 'molstar/lib/commonjs/mol-??/??'``. This is what the Model and Volume Servers do and it does work.

David

**Comment by 0gust1** [comment]
My initial attempt was to find a quick way to reuse the Viewer in my app. So, I hope to find some time to fiddle with the Mol* package and build. The Svelte/Sveltekit/Vite ecosystems are pushing toward ESM usage, hence the issue title.

I got past the initial `ReferenceError: self is not defined`error, by forcing the module to be dynamically loaded on client-side only. Now I get an `Automatic publicPath is not supported in this browser` error that I recognize as a webpack-generated thing.  

Thanks @dsehnal, I'll keep note of this!  
To rebuild a custom Viewer from `molstar/lib/*` will require me (a justified and understandable) deeper knowledge and reading of the internals. I still have to find the right level where I want to hook my code (presumably, before the React part).

**Comment by arose** [comment]
Hey @0gust1 any update from your side?

**Comment by 0gust1** [comment]
sorry for the delay.

I had the time to make another test, after a big update (local node version, all my applicative dependencies and build). 
I won't have the time to trace why, but everything works fine ! 

We are now able to start the replacement of NGL and dig the possibilities of Molstar. Thanks for the great work.
