### ISSUE TITLE
How to select and color chain of residues programmatically on top panel and structure tools

### ISSUE THREAD

**Issue by kscgl** [molstar/molstar#233]
Hello,

I am trying to figure out selecting and coloring residues programmatically on top panel and show the count of residues on structure tools. 

I create the query as below and apply color (black in this case) on loci without any problem. 

```
const sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
    'residue-test': Q.core.set.has([Q.set(60, 61, 62, 63, 64), Q.ammp('auth_seq_id')]),
    'group-by': Q.struct.atomProperty.macromolecular.residueKey(),}), data);
```

<img width="770" alt="Screen Shot 2021-07-21 at 2 54 19 PM" src="https://user-images.githubusercontent.com/11564750/126565263-b827570d-751b-4369-87dd-7b975a340c96.png">

Is there any way to show these residues (programmatically) on top and right panels as below?

<img width="770" alt="Screen Shot 2021-07-21 at 2 56 49 PM" src="https://user-images.githubusercontent.com/11564750/126565531-8b2d6bb7-eb10-420b-9058-f98f86fbc05c.png">

**Comment by arose** [comment]
If you have a PluginContext you can use context.managers.structure.selection, see https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/selection.ts#L37.

**Comment by kscgl** [comment]
`this.plugin.managers.structure.selection.fromLoci('add', loci);`

This worked. Thank you!

**Comment by kscgl** [comment]
@arose can we select a different color for `this.plugin.managers.structure.selection.fromLoci('add', loci);` ? It seems 'green' is default.

I am looking for something similar below;

```
const layer = {
  bundle: StructureElement.Bundle.fromLoci(loci),
  color: Color(color),
  clear: false
  };

const overpaint = Overpaint.ofBundle([layer], structure.root);
const merged = Overpaint.merge(overpaint);
const filtered = Overpaint.filter(merged, structure);

update.to(repr.transform.ref)
  .apply(StateTransforms.Representation.OverpaintStructureRepresentation3DFromBundle, Overpaint.toBundle(filtered), { tags: 'overpaint-controls' });

```

**Comment by arose** [comment]
You can change the default color from green to something else but it will always apply to all selected parts. Something like plugin.canvas3d?.setProps({renderer: { selectColor: Color(0xffcc11) }}) should do it.

**Comment by kscgl** [comment]
Which part of the code should I focus to apply different colors to different parts based on selection. 

```
if (props.selectColor !== undefined && props.selectColor !== p.selectColor) {
  p.selectColor = props.selectColor;
  ValueCell.update(globalUniforms.uSelectColor, Color.toVec3Normalized(globalUniforms.uSelectColor.ref.value, p.selectColor));
}
```

The piece of code above updates the color for all as you mentioned. I added ```Color(color)``` argument to ```this.plugin.managers.interactivity.lociSelects.select``` to change the color of selected sequences and it is eventually being applied in ```Sequence.getBackgroundColor(marker: number, color?: string | null)``` I am looking for something similar on canvas.

**Comment by arose** [comment]
> Which part of the code should I focus to apply different colors to different parts based on selection

you can not use the selection coloring to apply different colors, that is what overpaint is for

**Comment by kscgl** [comment]
Yes, I figured that out with overpaint. Thank you
