### ISSUE TITLE
Program for changing the color and the representation (from cartoon to surface)  ?

### ISSUE THREAD

**Issue by mugdhata** [molstar/molstar#234]
I was able to load multiple pdb files in a single frame. The challenge is to change the representation (from cartoon to surface) of one of them, programmatically. Is there any help available?

**Comment by mugdhata** [comment]
I was able to load multiple pdb files in a single frame. The challenge is to change the representation (from cartoon to surface) of one of them programmatically. Is there any help available? thanks

**Comment by arose** [comment]
Have a look at the component manager (https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/component.ts) which is available in the PluginContext.

**Comment by mugdhata** [comment]
Could you please give us a sample java script code or refer us to use proper method..

thanks

**Comment by arose** [comment]
You will need to build your own viewer wrapper. You can use the proteopedia wrapper example as a starting point https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.ts#L112
