### ISSUE TITLE
Is it possible to open a pdb file by composing from an https url?

### ISSUE THREAD

**Issue by avilella** [molstar/molstar#235]
I have a pdb file saved as a blob in a LIMS system (benchling) and I would like to open molstar with it by composing a URL.

I've tried:

https://molstar.org/viewer/?url=http://foobar.benchling.com/blobs/id-of-the-blob

```
Failed to download data. Possible reasons: Resource is not available, or CORS is not allowed on the server.
```
But it doesn't open the structure. If I download from the link and upload as PDB file, then it works. 

Any ideas? Would having our own Mol* server in the same domain help?

**Comment by dsehnal** [comment]
Yes, it is possible. Use the ``structure-url`` and ``-format`` parameters as explained here https://molstar.org/viewer-docs/query-parameters/. You might also have to url encode the URL (e.g. use the ``encodeURIComponent`` function).

**Comment by avilella** [comment]
I've tried encoding the url and providing the pdb format, but no luck.

If I try manually via the download structure menu, I get this error:


   - Failed to download data. Possible reasons: Resource is not available,
   or CORS is not allowed on the server.
   -


It may be that the server from the LIMS is providing it in a way that's
incompatible with this type of URL.

**Comment by dsehnal** [comment]
Are you using https URL? Because you can't use http if the original source is https.

**Comment by arose** [comment]
@avilella did you figure it out? From your error it might simple that your server does not have CORS enabled (for security reasons).
