### ISSUE TITLE
Issue rendering AlphaFold structures

### ISSUE THREAD

**Issue by xwatkins** [molstar/molstar#236]
v2.1.0

If I load an AlphaFold structure as "mmcif" (e.g. https://alphafold.ebi.ac.uk/files/AF-P05067-F1-model_v1.cif), the structure renders but the "cartoon" representation is never applied. Changing to other representations seems to work fine.

```
    const data = await plugin.builders.data.download(
      { url, isBinary: false },
      {
        state: { isGhost: true },
      }
    );

    const trajectory = await plugin.builders.structure.parseTrajectory(
      data,
      "mmcif"
    );

    return plugin.builders.structure.hierarchy.applyPreset(
      trajectory,
      "default",
      {
        structure: { name: "model", params: {} },
        showUnitcell: false,
        representationPreset: "auto",
      }
    );
```

**Comment by dsehnal** [comment]
The ``struct_conf`` entries in your files have incorrect values in the ``_auth_seq_id`` columns (e.g. 0 everywhere):

```
loop_
_struct_conf.beg_auth_asym_id
_struct_conf.beg_auth_comp_id
_struct_conf.beg_auth_seq_id
_struct_conf.beg_label_asym_id
_struct_conf.beg_label_comp_id
_struct_conf.beg_label_seq_id
_struct_conf.conf_type_id
_struct_conf.end_auth_asym_id
_struct_conf.end_auth_comp_id
_struct_conf.end_auth_seq_id
_struct_conf.end_label_asym_id
_struct_conf.end_label_comp_id
_struct_conf.end_label_seq_id
_struct_conf.id
_struct_conf.pdbx_beg_PDB_ins_code
_struct_conf.pdbx_end_PDB_ins_code
A GLY 0 A GLY 24  TURN_TY1_P   A GLY 0 A GLY 27  TURN_TY1_P1    ? ? 
A LEU 0 A LEU 29  BEND         A ALA 0 A ALA 30  BEND1          ? ? 
A GLN 0 A GLN 33  STRN         A ALA 0 A ALA 35  STRN1          ? ? 
```

Is this something you can fix on your end or something we need to implement a workaround for?

**Comment by dsehnal** [comment]
I have discussed this with Sameer V. and will have a version working with the current structures later this week or during the next.

**Comment by ValZapod** [comment]
> your files have incorrect values in the `_auth_seq_id` columns

But if it, why molstar works fine on alphafold DB site? https://alphafold.ebi.ac.uk/entry/A2RTF1 compare to https://www.uniprot.org/uniprot/A2RTF1.

**Comment by dsehnal** [comment]
@ValZapod There has been a change in how secondary structure is assigned between 1.x (used at the EBI site; uses ``label`` prefixed fields) and 2.x (used at Uniprot; uses ``auth`` fields to resolve #72). 

I will change it so that it prefers ``label`` fields and falls back to ``auth`` if ``label`` is not available.

**Comment by ValZapod** [comment]
InterPro also has it. https://www.ebi.ac.uk/interpro/protein/reviewed/Q6IMT1/alphafold/

**Comment by dsehnal** [comment]
As far as I know the files all come from the AlphaFold people anyway, and the error in the files is real (mentioned in https://github.com/molstar/molstar/issues/236#issuecomment-887644865). 

If you take say https://alphafold.ebi.ac.uk/files/AF-A2RTF1-F1-model_v1.cif  and replace the zeroes in ``_struct_conf.*_auth_*`` with the values in ``_struct_conf.*_label_*``, the secondary structure will display correctly on molstar.org. 

But it will all be resolved eventually and everything will be fine up until someone else does something unexpected with the PDB/mmCIF files :)

**Comment by dsehnal** [comment]
Mol* 2.2 should now displays the secondary structure correctly, e.g.

![image](https://user-images.githubusercontent.com/21145776/127741433-35bd27dc-6d22-4296-8662-b9b1cb682905.png)

**Comment by ValZapod** [comment]
Yes, nice. Now they just need to update.

**Comment by xwatkins** [comment]
Many thanks @dsehnal , now updated.

**Comment by ValZapod** [comment]
Can you notify https://www.ebi.ac.uk/interpro/protein/reviewed/Q6IMT1/alphafold/ folks?

**Comment by ValZapod** [comment]
Interpro also fixed!
