### ISSUE TITLE
Q: Setting up representation as default/preset?

### ISSUE THREAD

**Issue by cycle20** [molstar/molstar#237]
Hi,
First of all: Thank you for this great project and your work.

My task requires a customization of your viewer app. I would like to preset membrane-orientation representation as default - I don't know what is the right term in your model. I could setup this representation as a preset in the right config panel manually. Furthermore I could set it on the left structure hierarchy panel. I think there are many ways to customize your viewer.

I found this test code: https://github.com/molstar/molstar/blob/master/src/tests/browser/render-structure.ts
But I couldn't integrate its relevant steps into the main index.ts: https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.ts
I had bunch of struggling with it, I didn't record them.
Finally I gave it up and "invented" this "solution":

```typescript
     applyMembrane() {
        const hier = this.plugin.managers.structure.hierarchy;
        const stateObj: StateObjectRef<PluginStateObject.Molecule.Structure> =
            hier.selection.structures[0].components[0].structure.cell;
        
        tryCreateMembraneOrientation(this.plugin, stateObj);
    }
```
I think it can smell and sub-optimal/not so elegant.
I called from the index.html script. It works, but very slow.

```ts
viewer.loadPdb(pdb).then(val => viewer.applyMembrane());
```

Can you suggest a more effective/obvious/robust way?
I guess there are just a simple viewer parameter expression and that's all, but I couldn't figure it out.
Thank you.

_Minor NOTE: I have no any React or TypeScript experience. And fundamental concepts of the design are also mysterious to me. For example: states, structures, components, behaviors, actions, attachment and so on. Ok, I know, documentation is under construction. Not so easy to read the code without knowing its internal concepts._

**Comment by dsehnal** [comment]
Hi,

this should do the trick:

```ts
async loadStructureWithMembraneRepresentation(url: string, format: BuiltInTrajectoryFormat, isBinary: boolean) {
    const data = await this.plugin.builders.data.download({ url, isBinary }, { state: { isGhost: true } });
    const trajectory = await this.plugin.builders.structure.parseTrajectory(data, format);
    await this.plugin.builders.structure.hierarchy.applyPreset(trajectory, 'default', { representationPreset: 'preset-membrane-orientation' as any });

    // reset the camera because the membranes render 1st and the structure might not be fully visible
    requestAnimationFrame(() => this.plugin.canvas3d?.requestCameraReset());
}
```

**Comment by cycle20** [comment]
Hi @dsehnal,
It works. :+1:  Thank you very much for your quick response and support.
Best regards
