### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by samirelanduk** [molstar/molstar#239]
I've been diving into the code trying to get to grips with what the underlying object types and entities are in Molstar. This is what I've sort of worked out far:

**Plugin** - a react component for rendering the interface to screen. 'Plugin' also seems to be the word used to describe the visible rectangle on screen?

**PluginContext** - a javascript object which seems to hold the underlying state of the plugin, and has methods for doing things to change that state. Not really clear on the distinction between a plugin and a plugin context.

**PluginUIContext** - a subclass of PluginContext, not really sure what the distinction between this and PluginContext is.

**Specification** - a set of options passed to a plugin context when creating it.

**Viewer** - a wrapper around a plugin (plugin context?) with helper methods for loading structures etc. Not completely clear on when you would use a viewer vs a plugin.

Is that correct? Some other concepts which I have no idea about are: behaviours, events, tasks, managers. What are they? How do they work? How should I as a developer be interacting with these? They seem to be attributes of the PluginContext object.

My questions are basically the same as https://github.com/molstar/molstar/issues/138#issuecomment-824676284 but nobody really answered their question.

**Comment by arose** [comment]
Plugin, PluginContext, PluginSpec can be used without react. It is to be read as something you can plug into your own project.

PluginUIContext and PluginUISpec depend on react.

Viewer is an app build using the above objects. It is not really meant to be extended but it can serve as an example of how to setup your own custom viewer. You can also look at https://www.npmjs.com/package/@rcsb/rcsb-molstar (@JonStargaryen can the repo be made public too?) and https://github.com/PDBeurope/pdbe-molstar and https://github.com/reuter-group/peprmint-web as examples of how to create custom apps. We unfortunately don't have much documentation apart from the excuse "the code is the documentation". Everything that is exposed in the PluginContext is certainly intended to be used. The https://github.com/molstar/molstar/tree/master/src/extensions directory has more hints on how to extend molstar. A common pattern is that you define behaviors, transforms, themes and then register them with the plugin context.

**Comment by samirelanduk** [comment]
Thanks Alex - I think I'm starting to get a getter understanding of it.
