### ISSUE TITLE
Could react be a peer dependency rather than a dependency?

### ISSUE THREAD

**Issue by samirelanduk** [molstar/molstar#240]
At the moment molstar has a dependency of `"react": "^17.0.1"`, which means that it can only be used in react apps that use react 17.x.x - you cannot have different versions of react in the same react app, and installing molstar will install a second version of react if the existing react doesn't match `^17.0.1`.

Could react be made a peer dependency instead? This is the [preferred way](https://stackoverflow.com/a/30454133/4499072) to specify that a plugin requires react. I'm happy to make a pull request to this effect, I just wanted to make sure it wouldn't break anything or that I hadn't misunderstood something about how react was being used.

**Comment by arose** [comment]
Might very well work. I never looked into it though. One thing to keep in mind is TypeScript typings. I don't know if that would pose an issue.

Maybe do a PR which can be used by other who use molstar with react in their project for testing.

**Comment by samirelanduk** [comment]
Ok thanks - the dependency override thing is particularly useful. If it will cause issues with the versioning I will hold off on the pull request but I really think this should be considered for the next major version increment.

**Comment by arose** [comment]
ping @JonStargaryen @bioinsilico @valasatava you might be interested in this as well

**Comment by dsehnal** [comment]
``3.0.0-dev.4`` and newer now have React as peer dep.

**Comment by samirelanduk** [comment]
Amazing - thanks!

**Comment by arose** [comment]
@dsehnal what about rxjs, immer, immutable as peer deps as well? What are pros and cons?

**Comment by dsehnal** [comment]
I was thinking about this and decided to keep them as normal dependencies because they are not as commonly used as react and for most functionality the are internal to Mol*. Manually specifying the same version of rxjs/immer as Mol* should cause only 1 version being used. Am I missing something?

**Comment by arose** [comment]
Ok, sounds reasonable. To force a specific version one can use `overrides` (https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in npm or `resolutions` in yarn, as you suggested above.

**Comment by arose** [comment]
@samirelanduk good to close?

**Comment by samirelanduk** [comment]
Absolutely - thanks for changing this.

**Comment by russellp17** [comment]
Using Molstar as a library this breaks compilation for me - upgrading from `3.0.0-dev.3` to `3.0.0-dev.4` errors with: `Module not found: Error: Can't resolve 'react/jsx-runtime' in ...` 

although I do think making React a peer dependency is the right thing to do

**Comment by dsehnal** [comment]
@russellp17  Yeah that's why we waiting till 3.0 since it's a breaking change.

**Comment by russellp17** [comment]
@dsehnal do you know if there's a workaround? Other packages I import have React as a peer dependency but they import from 'react' (rather than 'react/jsx-runtime') and don't cause errors in the Webpack build

**Comment by dsehnal** [comment]
@russellp17  What react/TS version are you using? 
I found https://stackoverflow.com/questions/65527359/got-cant-resolve-react-jsx-runtime-error-while-use-try-to-create-the-shared-c and we are using ``"jsx": "react-jsx"``

**Comment by russellp17** [comment]
@dsehnal ah still on 16. Will look into upgrading or other workarounds

**Comment by samirelanduk** [comment]
Does this mean molstar will only support react version 17 and higher once this is released?

**Comment by dsehnal** [comment]
It works just fine with ``React 16.14``, just tested it from scratch: https://gist.github.com/dsehnal/cca77414a115e460ce5a1b685e56878b

**Comment by russellp17** [comment]
So it looks like 16.14.0 has support for `react-jsx` but not earlier React 16.* versions: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#how-to-upgrade-to-the-new-jsx-transform 

Just put up a PR to permit React 16 as a peer dependency
