### ISSUE TITLE
Model/density server external configuration

### ISSUE THREAD

**Issue by otienoanyango** [molstar/molstar#25]
It would be nice to be able to configure the DefaultModelServerConfig object using either environment variables or externalized config file. I'd want to add this into a Dockerfile for Kubernetes deployment. Currently, I can have a copy of the config with the settings I want and pass that on to the docker container before build. But this assumes the TS file doesn't change in the near future. but an externalized JSON/YAML config is easy enough to replace without breaking things unnecessarily.

**Comment by dsehnal** [comment]
This is already possible.

- VolumeServer config options as command line/env variables: https://github.com/molstar/molstar/blob/master/src/servers/volume/config.ts
- ModelServer supports a JSON object: https://github.com/molstar/molstar/blob/master/src/servers/model/server.ts#L48

It should not be a big problem to add the VolumeServer style of options to the ModelServer as well. Do you need that?

Also, we plan to add separate npm packages for both servers as well. Might do that sooner than later I suppose...

**Comment by otienoanyango** [comment]
Separating the npm packages is very welcome. It helps me sort two things: I am creating a Dockerfile for the two servers and need to host the separately. The npm run build takes quite a while to run. I assume this is because of everything building and not necessarily the server stuff. The separation would make it build faster as well as allow for better  deployment esp on the cloud. 

A request would be to make the build and run steps a lot clearer and consistent. That would include the configurable options.

**Comment by dsehnal** [comment]
Very well, I will have a look into this probably next week.

Thanks for the feedback.

**Comment by dsehnal** [comment]
Both model and volume servers now support JSON/cmd line config.

Instead of creating separate npm packages, I've added binaries to the molstar npm package (currently at ``@next`` tag, will in "main" with 0.6 release). So what now works is

```
npm install --production molstar@next
node_modules\.bin\model-server
```

Other binaries are ``model-server-query`` (execute model server queries locally), ``model-server-preprocess`` (to create BinaryCIF files fast), ``volume-server``, ``volume-server-pack``, ``volume-server-query`` (for local queries, for example to precompute volumes around ligands).

----------------------

If you still prefer to get it from GitHub, it is not required to build the whole thing, but calling ``npm run build-tsc`` is enough and then running with ``node lib/servers/model/server/server``.

**Comment by otienoanyango** [comment]
Thank you so much David. The npm install is a lot easier plugin. I have tried it with file system and it works great. Can it support data from http/ftp source?

**Comment by dsehnal** [comment]
Well, the way we handled this remote data issue before was to mount a virtual drive. But technically speaking there is no reason it can’t support fetching from http/ftp. I will try to add it to the model server (would not work directly with volumes as it needs file seeking).

If there is demand for it, I guess I can finish the custom property support to the model server. This means you would be able to add custom data to the CIFs on demand. Would this be something useful to you?

**Comment by otienoanyango** [comment]
By the way does it handle gzipped files.

**Comment by dsehnal** [comment]
Yes it does handle these. I've just pushed an update that supports the http fetching, tested it on this:

```
node lib\servers\model\server --sourceMapUrl pdb-cif "https://www.ebi.ac.uk/pdbe/entry-files/download/${id.toLowerCase()}_updated.cif" cif --sourceMapUrl pdb-bcif "https://webchem.ncbr.muni.cz/ModelServer/static/bcif/${id.toLowerCase()}" bcif

node lib\servers\model\server --defaultSource wwpdb --sourceMapUrl wwpdb "https://ftp.wwpdb.org/pub/pdb/data/structures/divided/mmCIF/${id.toLowerCase().substr(1, 2)}/${id.toLowerCase()}.cif.gz" cif.gz
```

Please get it from the GitHub repo for now if you want to test it yourself.

**Comment by otienoanyango** [comment]
No worries. As I am on something for today, you can push it to next and I will work on it tomorrow

**Comment by arose** [comment]
Hey @otienoanyango and @dsehnal, is this resolved?
