### ISSUE TITLE
Some metadata is lost when uploading `.cif`s from PyMOL to Mol*.  Where is the logic contained for parsing `.cif` files contained?

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#251]
Some of the files i have saved from PyMOL i would like to be able to upload and inspect in Mol*. The issue is problem is that when i upload the pymol-generated file to Mol*, the metadata for chains seems to be lost. My guess is that is courtesy to how PyMOL writes .cif files i.e. :
```pdbx/mmcif
# generated by PyMOL 2.3.0
#
data_3J7Z_6
_entry.id 3J7Z_6
#
loop_
_atom_site.group_PDB
_atom_site.id
_atom_site.type_symbol
_atom_site.label_atom_id
_atom_site.label_alt_id
_atom_site.label_comp_id
_atom_site.label_asym_id
_atom_site.label_entity_id
_atom_site.label_seq_id
_atom_site.pdbx_PDB_ins_code
_atom_site.Cartn_x
_atom_site.Cartn_y
_atom_site.Cartn_z
_atom_site.occupancy
_atom_site.B_iso_or_equiv
_atom_site.pdbx_formal_charge
_atom_site.auth_asym_id
_atom_site.pdbx_PDB_model_num
ATOM   1   N N   . SER A . 1 ? 230.572 269.225 194.086 1.00  48.83 0 6 1
ATOM   2   C CA  . SER A . 1 ? 229.572 268.432 193.372 1.00  53.57 0 6 1
...
ATOM   27  C CG  . LYS A . 4 ? 219.573 271.377 195.894 1.00  38.63 0 6 1
ATOM   28  C CD  . LYS A . 4 ? 218.260 271.772 195.264 1.00  33.88 0 6 1
#
data_3J7Z_N
_entry.id 3J7Z_N
#
loop_
_atom_site.group_PDB
_atom_site.id
_atom_site.type_symbol
_atom_site.label_atom_id
_atom_site.label_alt_id
_atom_site.label_comp_id
_atom_site.label_asym_id
_atom_site.label_entity_id
_atom_site.label_seq_id
_atom_site.pdbx_PDB_ins_code
_atom_site.Cartn_x
_atom_site.Cartn_y
_atom_site.Cartn_z
_atom_site.occupancy
_atom_site.B_iso_or_equiv
_atom_site.pdbx_formal_charge
_atom_site.auth_asym_id
_atom_site.pdbx_PDB_model_num
ATOM   1   N N   . MET A . 1 ? 217.170 235.558 216.085 1.00  27.02 0 N 1
ATOM   2   C CA  . MET A . 1 ? 215.967 236.354 216.338 1.00  19.71 0 N 1
ATOM   3   C C   . MET A . 1 ? 216.326 237.800 216.611 1.00  11.02 0 N 1
...
ATOM   12  O O   . ARG A . 2 ? 219.215 241.232 217.318 1.00   9.74 0 N 1
```

Still, it would be nice to know what kind of a .cif file counts as well-formed and what Mol* uses to parse the files. I realize also that the authors of Mol* have been involved in the development of the format itself and it's entirely possible that i should be taking this up with Shroedinger rather than here. Please advise.

I'm currently using the [PDBe plugin](https://github.com/PDBeurope/pdbe-molstar)with the following syntax. It'd be nice to know whether there are differences between how the actual viewer does it  and how the viewer plugin handles this.

```typescript
          viewerInstance.visual.update({
            customData: {
              url:
              `https://url_to_my_pymol_files`,
              format: "cif",
              binary: false,
            },
 ```

**Comment by arose** [comment]
Hi @rtviii, it is not clear to me what you mean by chain metadata. Could you please elaborate what data exactly is missing and how this manifests. Is this a problem in the Mol* Viewer at molstar.org/viewer or is it something you only observe in your code? Could you provide an example with which to reproduce the problem?

**Comment by rtviii** [comment]
![Screenshot from 2021-08-10 21-36-40](https://user-images.githubusercontent.com/34076599/128970426-c4cb77ba-d176-4d85-8104-883555176e33.png)
Here are two individual ribosomal protein strands/chains extracted from 2 different molecules and aligned in PyMOL(original alignment on the right), saved as .cif file and visualized in Mol* (on the left). File :https://gofile.io/d/f3Jm8c

In particular you can see that only one of the two aligned chains on the left get displayed on the right (in green). My guess is that this happens because the [alignment .cif file](https://gofile.io/d/f3Jm8c) is written without some headers (loops in mmcif parlance) that identify individual entities within a larger molecule usually. If you open a cif file in a text editor it contains details like authors, pdb names, sequence etc. This one doesn't. Nevertheless, when i upload it to PyMOL or Chimera, they seem to identify two distinct chains in the file correctly. Can this be done in Mol*? What about other fields/metadata like strand-annotation for example, can i get at those with some tool in the package somehow, if not the viewer itself? 

By metadata i mean basically everything except the atom coordinates themselves by the way.. Sorry if this is kind of broad. I will try to edit my .cif files to conform to the spec if this can't be done in the viewer right now or contribute to the parsing facilities if they are open.

Thanks a ton for your work

**Comment by arose** [comment]
Thanks for the example. The files contain two cif blocks (indicated by `data_`), each with one structure. By default molstar shows only the first one for structures. The Viewer App does currently not have a simple API to show all structures from such files. With some programming it can certainly done (the TrajectoryFromMmCif transform has a cif block parameter). Using the state tree on the left oin the Viewer App you can do it in the UI as well, see below.

> What about other fields/metadata like strand-annotation for example, can i get at those with some tool in the package somehow, if not the viewer itself?

Molstar calculates secondary structure automatically if not given in the file.

![image](https://user-images.githubusercontent.com/272250/128974802-e33b5fae-4110-42ee-bcfc-7d534557e3f8.png)

**Comment by arose** [comment]
- It would be nice to have loading such files and displaying all structures automatically supported.
- There is an issue with automatic chain coloring when loading such files: both structures got the same chain colors.
