### ISSUE TITLE
Text Representations in v.2.2.2

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#259]
Greetings, I updated from v2.2.1 to v2.2.2 and I need to render labels for atoms but I cannot do so. My code looks like this:
```javascript
this.addTextForAtoms = (structureKey, representationKey, atomLabels, styleProps = undefined, size = 0.5) => {

      const atomExpression = (atomId) => {
                return query.struct.generator.atomGroups({
                    'atom-test': query.core.rel.eq([query.struct.atomProperty.core.sourceIndex(), atomId])
                });
            }
      const structure = _structures[structureKey].data;
      const context = _plugin.managers.task.currentContext;

      Object.keys(atomLabels).forEach((atomId) => {
          const _atomId = parseInt(atomId)

          const query = molstar.StructureSelectionQuery('Query', atomExpression(_atomId));
          query.getSelection(_plugin, context, structure)
              .then((selection) => {
                  const loci = molstar.StructureSelection.toLociWithSourceUnits(selection);

                  molstar.createTextRepresentation({ text: atomLabels[atomId], loci, size }, styleProps)
                      .then((label) => {
                          label.setState({ pickable: false });
                          _plugin.canvas3d.add(label);
                      });
              });
      });
  }
```
Is there some change in the way labels can be attached?

**Comment by dsehnal** [comment]
Hi,

I wasn't able to test the exact version of your code, but I tested this on the latest commit in master and it does produce the labels. Can you please check if your bug disappears when you use the latest build from master?

(Please note that this is not the most efficient way to add labels but should be good enough if you don't have too many of them)

```ts
testLabels() {
    const createQuery = (atomId: number) => MS.struct.generator.atomGroups({
        'atom-test': MS.core.rel.eq([MS.struct.atomProperty.core.sourceIndex(), atomId])
    });

    const structure = this.plugin.managers.structure.hierarchy.current.structures[0].cell.obj?.data!;

    const atomIds = [1, 2, 3, 4];
    const task = Task.create('test', async ctx => {
        for (const id of atomIds) {
            const q = compile(createQuery(id));
            const sel = q(new QueryContext(structure));
            const loci = StructureSelection.toLociWithSourceUnits(sel);

            // I am cheating here a bit as I've added the customText option here as it was not available before
            // it would just use the default atom name label otherwise
            await this.plugin.managers.structure.measurement.addLabel(loci, { customText: `Label ${id}` });

            // check the index is correct
            const fst = StructureElement.Loci.getFirstLocation(loci)!;
            const idx = StructureProperties.atom.sourceIndex(fst);
            console.log(idx);
        }
    });

    this.plugin.runTask(task);
}
```

![image](https://user-images.githubusercontent.com/21145776/130677039-0ce0a0bb-e29a-484f-8c8a-d57d4eab65ad.png)

**Comment by ptourlas** [comment]
Greetings! 
Building from master's latest commit resolves the issue indeed.
However, I noticed something rather strange after building 3 different versions of the codebase:
[2.2.1](https://github.com/molstar/molstar/tree/v2.2.1) --> labels appear
[2.2.2](https://github.com/molstar/molstar/tree/v2.2.2) --> labels do not appear
[latest](https://github.com/molstar/molstar/commit/77139afe7f3c3ccdfabbc8d5553b58d36288e01d) --> labels appear

Unfortunately, I have limited familiarity with the codebase at the moment but could these changes be relevant?
2482ef92af306979102d734119c760fbbb8339d0
6dd876232dc5677f6626d5d6740182bdb9711baf

Thanks a lot!

**Comment by dsehnal** [comment]
Thanks for the investigation. I will make v2.2.3 later today.

The changes don't seem to be relevant on the 1st sight, but I guess you never know :)

**Comment by dsehnal** [comment]
2.2.3 is out!
