### ISSUE TITLE
Input SDF/MOL and XYZ files

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#26]
SDF/MOL and XYZ are formats I use for small molecules. I did not yet see these in the source code so I created this issue to track it.

**Comment by arose** [comment]
We have a mol2 reader (https://github.com/molstar/molstar/tree/master/src/mol-io/reader/mol2) but it needs to be integrated with the rest of the library to produce a Structure object.

**Comment by dsehnal** [comment]
I've added basic MOL/SDF support.

**Comment by arose** [comment]
@bergwerf do you still need XYZ format support or is the now available sdf/mol and mol2 support enough?

**Comment by bergwerf** [comment]
I don't think I need XYZ anywhere. Also my MolView rewrite project again got stuck on time limitations. Perhaps by the time I'm ready to continue there is a small/self contained mol* canvas compilation :)  (I use Dart instead of modern JS, and I would prefer staying out of the modern JS build tool chain).

**Comment by dsehnal** [comment]
I will be adding XYZ support soon as well regardless.

**Comment by arose** [comment]
@dsehnal added XYZ support in 29d4cfbccadfdea217f3a6e6025a1ab6cf841e19.
