### ISSUE TITLE
How can I resolve the stuttering problem of visualization?

### ISSUE THREAD

**Issue by CallMeDek** [molstar/molstar#260]
Hi, 
I am working with 3D structure of protein by this project on local computing environment.
I already succeeded in seeing the result of my file but there is a serious problem. 
Whenever I interact with the embedded viewer like rotating the structure, there is so much lag on the web browser.
I have to wait for a few minutes until results come out. 
If you think it is related to only hardware, then could you let me know specification of your server?
I ran it by Visual Studio Code with Live Server extension. 

OS: Ubuntu 20.04.2 LTS
![screen_shot](https://user-images.githubusercontent.com/22671339/130547957-a239fe32-4e48-49bb-a600-5d747e070755.png)
The above picture shows the CPU utilization when I interacted with the viewer.

Thank you.

**Comment by arose** [comment]
Hi @CallMeDek, a few questions.

- Do you have the same issue with the viewer on https://molstar.org/viewer/? 
- What file are you loading? Number of atoms? Anything special? Can you share it?
- What are your hardware specs? Specifically GPU?
- Do you have proper GPU drivers installed?
- What browser are you using?
- Does https://threejs.org/examples/?q=perfo#webgl_performance run well for you?

**Comment by CallMeDek** [comment]
Hi @arose,

I built this project on the other computer and it worked. There is no problem with that environment. 
This is not what I expected because I thought second one had worse specs than first one. 
So, I tried re-constructing the pipeline on the first one and I got some hints like below. 

> molstar@2.2.2 build-webpack
> webpack --mode production --config ./webpack.config.production.js

assets by chunk 20 KiB (auxiliary name: main)
  asset favicon.ico 15 KiB [emitted] [from: lib/apps/viewer/favicon.ico] (auxiliary name: main)
  asset index.html 3.38 KiB [emitted] [from: lib/apps/viewer/index.html] (auxiliary name: main)
  asset embedded.html 1.56 KiB [emitted] [from: lib/apps/viewer/embedded.html] (auxiliary name: main)
assets by chunk 4.15 MiB (name: main)
  asset molstar.js 4.09 MiB [emitted] [minimized] [big] (name: main) 1 related asset
  asset molstar.css 65 KiB [emitted] (name: main)
Entrypoint main [big] 4.15 MiB (20 KiB) = molstar.css 65 KiB molstar.js 4.09 MiB 3 auxiliary assets
orphan modules 6.07 MiB [orphan] 1118 modules
runtime modules 1.84 KiB 6 modules
code generated modules 8.39 MiB (javascript) 65 KiB (css/mini-extract) [code generated]
  modules by path ./node_modules/ 2.53 MiB
    javascript modules 2.52 MiB 164 modules
    json modules 12.7 KiB
      modules by path ./node_modules/browserify-sign/ 2.23 KiB 2 modules
  optional modules 120 bytes [optional] 8 modules
  modules by path ./lib/ 5.86 MiB (javascript) 65 KiB (css/mini-extract)
    cacheable modules 22.8 KiB
      ./lib/mol-util/polyfill.js 22.7 KiB [built] [code generated]
      ./lib/mol-plugin-ui/skin/light.scss 50 bytes [built] [code generated]
    ./lib/apps/viewer/index.js + 968 modules 5.84 MiB [not cacheable] [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./lib/mol-plugin-ui/skin/light.scss 65 KiB [code generated]
  7 modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  molstar.js (4.09 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (4.15 MiB)
      molstar.css
      molstar.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.37.1 compiled with 3 warnings in 65098ms


In my opinion, I need to focus on below statement.

"WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance."

Do you think it is related to the specs of each computer? 
Then, I think I can tell you the specs of each computer.

Thanks

**Comment by arose** [comment]
Hi @CallMeDek

> "WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance."

this only effects loading time of the js files but has no effect on the speed of the visualization, i.e. the 3D rendering
