### ISSUE TITLE
Display only H-Bonds in a custom preset?

### ISSUE THREAD

**Issue by fechan** [molstar/molstar#262]
I'm writing a `TrajectoryHierarchyPresetProvider` and when I apply my preset, I want it to disable visibility of all non-covalent interactions except hydrogen bonds. How would I do this programmatically?

I know it can be done in the GUI by going into  "Options that are applied to all applicable representations" in the Components panel and unchecking everything except "Hydrogen bonds," but I just don't know how to do it with code.
![image](https://user-images.githubusercontent.com/56131910/131759761-fb9e40e0-0fde-49b3-baa6-2ee73c4c9f30.png)

Additional info (maybe relevant?): my `TrajectoryHierarchyPresetProvider` creates a structure and applies a custom structure representation preset implementing `StructureRepresentationPresetProvider` to it. This in turn creates a component and applies the Non-covalent Interactions Representation (`InteractionsRepresentationProvider`) to the component.

Thanks in advance!

**Comment by dsehnal** [comment]
Hi, when creating the structure object and inserting properties, adjust the default parameters the action gets. [This](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/component.ts#L105) shows how it's done when updating the UI.

Let me know if you need more help.
