### ISSUE TITLE
load trajectory from java script

### ISSUE THREAD

**Issue by jmbuhr** [molstar/molstar#277]
Hi there and thank you for your work!

I am currently using it to embedd pdb files into interactive reports and wonder how to add a trajectory (e.g. a `xtc` file) to the application from java script.
For example with a molstar viewer instance:

```
var viewer = new molstar.Viewer('app', {<options>})
viewer.loadPdb('<mypdb>')
```

is there also a method to add a `xtc` trajectory to the viewer?

**Comment by dsehnal** [comment]
Hi, 

I've added the ``loadTrajectory`` function. https://github.com/molstar/molstar/commit/a0d919c8db41d98f4a1132b72eb73ce72841455d

**Comment by jmbuhr** [comment]
This is amazing, thank you so much!
