### ISSUE TITLE
Hiding Right Panel and structure colour

### ISSUE THREAD

**Issue by CodesByShivam** [molstar/molstar#278]
Hi,

I am importing Molstar for visualization for pdb files in my React app. I am facing 2 issues. 

1. I want to show the sequence, but hide other controls. if I make layoutShowControls as false and layoutShowSequence as true, all the controls including sequence disappears. But If I keep layoutShowControls as true and make other options like layoutShowLeftPanel, layoutShowLog as false, then the sequence viewer remains, but I am not able to hide the right panel.
2. The second issue is, I load the PDB file using a URL but my own API which loads the structure successfully, but the colour coding of the structure becomes green only unlike how it looks when I use the RCSB url for the same structure.

Below is my React implementation.

```
import React, { useEffect, useRef } from 'react';
import { Viewer } from 'molstar/build/viewer/molstar';
import "molstar/build/viewer/molstar.css";

export default function MolstarComp(
    props
) {
    const viewerElement = useRef(null);
    const viewer = useRef(null);

    const { viewerWidth, viewerHeight, pdbFileName } = props;

    useEffect(() => {
        const viewerOptions = {
          layoutIsExpanded: false,
          layoutShowControls: false,
          layoutShowRemoteState: false,
          layoutShowSequence: true,
          layoutShowLog: false,
          layoutShowLeftPanel: false,
          viewportShowExpand: false,
          viewportShowControls: false,
          viewportShowSettings: false,
          viewportShowSelectionMode: false,
          viewportShowAnimation: false,
          volumeStreamingDisabled: false,
        };

        viewer.current = new Viewer(viewerElement.current, viewerOptions);
        viewer.current.loadStructureFromUrl(`http://localhost:3000/api/pivot/gene/pdb-file/${pdbFileName}`, 'pdb' );
        
    }, []);

    return (
        <div style={{
          position: "relative",
          width: viewerWidth, height: viewerHeight
        }}>
          <div ref={viewerElement} 
          style={{
            position: "absolute",
            width: viewerWidth, height: viewerHeight, left: 0, right: 0
          }}
          />
        </div>
    );
}
```

Issue  Screenshots:
<img width="1005" alt="Screenshot 2021-10-27 at 8 08 16 PM" src="https://user-images.githubusercontent.com/63360985/139087928-92c20431-debc-4d41-92db-d34499edd4a6.png">

Kindly help.

Thanks,
Shivam

**Comment by dsehnal** [comment]
@CodesByShivam I've added the ``collapseRightPanel`` option to Viewer options.

**Comment by arose** [comment]
Since v3.0.0-dev.6 alphafold db mmcif files are colored by plddt by default
