### ISSUE TITLE
Focus representation not updated when loading 'small' structures

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#280]
Hello,

While changing the default structure color theme using `PluginConfig.Structure.DefaultRepresentationPresetParams` I noticed that the 'focus' representations are not updated to use the default color theme set, but only for 'small' structures (such as molecules loaded from an `.sdf. file). Loading other larger structures (such as proteins using a `.pdb` file) do update the default focus representations to the default color theme set in the plugin config.

I may have found the issue in the codebase. In `src/mol-plugin-state/builder/structure/representation-preset.ts` when `StructureRepresentationPresetProvider` is called, each of the sizes in the switch (line 117) call a preset provider. The `coarseSurface`, `polymerCartoon`, and `polymerAndLigand` preset providers all call the function `updateFocusRepr` after applying their presets (lines 192, 231, 283 and 316). This call ensures that focus representations are set to the defaults in `PluginConfig.Structure.DefaultRepresentationPresetParams`. However, the `atomicDetail` preset provider (line 322) is the only one that does not call `updateFocusRepr`.

Is this a deliberate choice, or could it be a bug?

Reproduction steps:

1. In `src/apps/viewer/index.ts` add the following configuration to the plugin config (line 156):
```
[
  PluginConfig.Structure.DefaultRepresentationPresetParams,
  { theme: { globalName: "uniform", focus: { name: "uniform" } } },
],
```
2. Build & serve molstar
3. Open the viewer
4. Load any 'small' structure (such as a single molecule from `.sdf`)
5. Note that the structure's representation has the 'uniform' color theme by default, as expected
6. **Click on the structure. Note that the focus representations have the 'Element Symbol' color theme**
    - We expect the focus representations to have the 'uniform' color theme as set by the plugin config above
7. Now load any 'medium' or larger structure (such as a protein from `.pdb`)
8. Note that the new structure's representation also has the 'uniform' color theme by default
9. Click on the 'small' structure again. Note that the focus representations now have the 'uniform' color theme as expected

Thanks for your time.

Jason

**Comment by arose** [comment]
Thanks @jpattle, the call to `updateFocusRepr` was indeed missing.
