### ISSUE TITLE
Color theme with a different color for each structure source

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#281]
Hi,

What is the best way to create and register a new color theme that displays a different carbon color for each structure source?

For example: if I load a protein and ligand from one `.pdb` file it would by default have one carbon color (lets say green), then I load another protein from a different `.pdb` which should have a different carbon color (lets say blue), then I load additional structures into the viewer from any source (`.sdf`, url, other files...) and each of these should have a unique carbon color (magenta, yellow, salmon, etc...).

As far as I can tell there is no way to uniquely color each structure based on its source. Since all structures share the same representations it is not possible to use the 'Uniform' (or similar) representation to colour each separate structure differently.

Thanks for your time,

Jason

**Comment by arose** [comment]
Great question. The built-in `chain-id` color theme provides a unique color for each chain across all models. The 'element-symbol' color theme can use the `chain-id` for carbon coloring. This may or may not be enough for your use case. If you want to do something similar for a custom color theme have a look at the `chain-id` color theme. It makes use of two Model properties `Model.AsymIdOffset` (offset or starting index of the model's asym ids into an implicit list of all loaded models) and `Model.Index` (index into an implicit list of all loaded models). Both properties are automatically created by a behavior (src\mol-plugin\behavior\dynamic\custom-props\structure-info.ts) which means you need to use molstar state tree and make sure the behavior is registered (by default it is).

**Comment by jpattle** [comment]
Thank you, I think registering the `StructureInfo` behavior is what I was missing. Looks like I can set the default representation for structures to 'element-symbol' with carbon color 'chain-id', as you say, and it'll do what I need.

Thanks again
