### ISSUE TITLE
Adding frames to a trajectory from coordinates array

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#282]
Hello,
Based on https://github.com/molstar/molstar/issues/90, I would like to add some extra info regarding @stefdoerr 's case.
The frontend receives a PDB file from the backend which is loaded using:
```javascript
async function createStructureFromRawData(filecontent, molname, filetype, structureKey) {
    const raw_data = await viewer.plugin.builders.data.rawData({ data: filecontent, label: molname })
    const trajectory = await viewer.plugin.builders.structure.parseTrajectory(raw_data, filetype);
    // Apply default representations
    await viewer.plugin.builders.structure.hierarchy.applyPreset(trajectory, 'default');
    return trajectory
}
```
Once this is called, the frontend also receives an array of the form:
`[frame1, frame2, ..., frameN]`
with each entry being a list of the atomic coordinates in sequence, i.e.
`[x1,y1,z1,x2,y2,z2,...,xK,yK,zK]`
Ideally, we would like each one of the entries to be added as a new model for the given topology (if I'm using the term correctly here), like this:
![multi-model-struct](https://user-images.githubusercontent.com/46487703/140334176-3ad5f7cc-8fe3-46c0-b322-7bcaa04ba6de.png)
I think that: https://github.com/molstar/molstar/blob/7f39cf0f37e66e35c8016620a8d753065d9b2978/src/mol-plugin-state/actions/structure.ts#L176 could be of use but I'm not experienced with how these functions can be accessed.
(In fact, how to apply state transformations to the viewer programmatically is another big question and I perhaps I could help with documenting this since I'm already trying to understand the whole "state tree" concept.)

**Comment by dsehnal** [comment]
Hi,

the way to approach this would be:

- Create a transform that creates [``PluginStateObject.Molecule.Coordinates``](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/objects.ts#L100) object from your trajectory data.
- Look at [``AddTrajectory``](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/actions/structure.ts#L229) state action how to create a new trajectory from an existing model and additional "trajectory" (e.g. use the ``TrajectoryFromModelAndCoordinates`` transform).
- Do whatever you want with the resulting trajectory (e.g. create a separate model for each frame).
- Might also be worthwhile to delete the "default" representation of the original PDB model.

**Comment by ptourlas** [comment]
Thanks a lot! Will try to implement and I'll post again for any additional clarification.

**Comment by ptourlas** [comment]
Greetings,

I forked the whole thing in order to make additions freely and I'd like to confirm the steps for adding the transform for trajectory data (which were rather numerous :smile: ).

* I defined a [parser](https://github.com/ptourlas/molstar/blob/ab106f08733346b075bf0b79e42bd5c7a8a30ebe/src/mol-io/reader/jsarray/parser.ts) that gets the array and checks for structural errors.
(**Question 1**: Is that the parser's purpose in general? I also think that I don't really need this.)

* The [`coordinatesfromArray`](https://github.com/ptourlas/molstar/blob/feature/trajectory-from-array/src/mol-model-formats/structure/jsarr.ts) state transform is the one that creates the `Coordinates` type object.

* The parser and the function from above are then added to [`mol-plugin-state/transforms/model.ts`](https://github.com/ptourlas/molstar/blob/ab106f08733346b075bf0b79e42bd5c7a8a30ebe/src/mol-plugin-state/transforms/model.ts#L96) and the method defined here makes a call to the `SO.Molecule.Coordinates` constructor.
(**Question 2**: Once I get the value returned by this function I essentially get the `PluginStateObject.Molecule.Coordinates` that you mention in step 1 of the solution outline, correct?)

* In order to apply the state transform I created, I need a new [`DataFormatProvider`](https://github.com/ptourlas/molstar/blob/f46d3e40fc576f818da5eff4c55873be5a8f0ccb/src/mol-plugin-state/formats/structure.ts#L58) whose `parse()` method does the job.
(**Question 3**: This bit here is still somewhat obscure to me:
```javascript
parse: (plugin, data) => {
        const coordinates = plugin.state.data.build()
            .to(data)
            .apply(StateTransforms.Model.CoordinatesFromArray);

        return coordinates.commit();
    }
``` 
Could we explain it as "build a new node in the state tree, select the data you want to transform and then apply the transformation"?)

* Since my `DataFormatProvider` will handle `number[][]` types, I'll have to extend the interface by adding the [`PluginStateObject.Data.CoordArray`](https://github.com/ptourlas/molstar/blob/f46d3e40fc576f818da5eff4c55873be5a8f0ccb/src/mol-plugin-state/formats/provider.ts#L27) state object type I added to [`mol-plugin-state/objects.ts`](https://github.com/ptourlas/molstar/blob/f46d3e40fc576f818da5eff4c55873be5a8f0ccb/src/mol-plugin-state/objects.ts#L62).

* A new method, [`rawArr()`](https://github.com/ptourlas/molstar/blob/f46d3e40fc576f818da5eff4c55873be5a8f0ccb/src/mol-plugin-state/builder/data.ts#L22) , is added in the `DataBuilder` class. This method applies the [`RawArr`](https://github.com/ptourlas/molstar/blob/f46d3e40fc576f818da5eff4c55873be5a8f0ccb/src/mol-plugin-state/transforms/data.ts#L189) state transformation.

* Having all this arsenal of tools, I simply import the `BuildInStructureFormat` type in [`index.ts`](https://github.com/ptourlas/molstar/blob/f46d3e40fc576f818da5eff4c55873be5a8f0ccb/src/apps/viewer/index.ts#L21) and I add the [`loadMyArray()`](https://github.com/ptourlas/molstar/blob/f46d3e40fc576f818da5eff4c55873be5a8f0ccb/src/apps/viewer/index.ts#L199) method.

This (hopefully) creates the coordinate object.

But how should I get the UUID refs of the model I'm interested at and the coordinate object I created? And how will I feed them to `AddTrajectory()` ?

(P.S. Sorry for the extra long post but I need to understand this so that I can reproduce it in different scenarios as well.)

**Comment by dsehnal** [comment]
I think you are way over-complicating it.

Something like this should do the trick:

```ts
const CreateTransformer = StateTransformer.builderFactory('custom');

const CreateMyCoordinates = CreateTransformer({
    name: 'create-coords',
    from: PluginStateObject.Root,
    to: PluginStateObject.Molecule.Coordinates,
    params: {
        data: ParamDefinition.Value<number[][]>([])
    }
})({
    apply({ params }) {
        return Task.create('Create Trajectory', async ctx => {
            const coords = Coordinates.create(
                params.data.map((cs, i) => ({
                    ...getCoords(cs),
                    elementCount: cs.length / 3,
                    time: Time(i, 'step'),
                    xyzOrdering: { isIdentity: true }
                })),
                Time(1, 'step'),
                Time(0, 'step')
            );

            return new PluginStateObject.Molecule.Coordinates(coords, { label: 'label' });
        });
    }
});

function getCoords(data: number[]) {
    const len = data.length / 3;
    const x = new Float32Array(len);
    const y = new Float32Array(len);
    const z = new Float32Array(len);
    for (let i = 0, _i = data.length, o = 0; i < _i; i += 3) {
        x[o] = data[i];
        y[o] = data[i + 1];
        z[o] = data[i + 2];
        o++;
    }
    return { x, y, z };
}

async function createMyObjects(plugin: PluginContext, pdbData: string, coordinates: number[][]) {
    const _pdbData = await plugin.builders.data.rawData({ data: pdbData, label: '...' });
    const pdbTrajectory = await plugin.builders.structure.parseTrajectory(_pdbData, 'pdb');
    const pdbModel = await plugin.builders.structure.createModel(pdbTrajectory);

    const coords = await plugin.build().toRoot().apply(CreateMyCoordinates, { data: coordinates }).commit();


    const trajectory = await plugin.build().toRoot()
        .apply(TrajectoryFromModelAndCoordinates, {
            modelRef: pdbModel.ref,
            coordinatesRef: coords.ref
        }, { dependsOn: [pdbModel.ref, coords.ref] })
        .commit();

    await plugin.builders.structure.hierarchy.applyPreset(trajectory, 'all-models');
}
```

**Comment by ptourlas** [comment]
Greetings!

The snippet above did the trick indeed, thank you very much. However, one last note:
It seems that the state tree contains models than I need. The trajectory looks like this

![multimodel](https://user-images.githubusercontent.com/46487703/141116606-5e28069f-48c7-47ee-95e1-87a49270eb25.png)

but the two last entries are redundant. What I need looks like this:

![singlemodel](https://user-images.githubusercontent.com/46487703/141116624-7723d19d-e118-4042-b46d-be1e268455bc.png)

I can remove the two entries manually but this cannot scale when I'll use bigger arrays. What would you suggest?

**Comment by stefdoerr** [comment]
I would argue we don't need separate models at all. We just want a single model where the trajectory is loaded into. It's a single simulation.

**Comment by stefdoerr** [comment]
Ok @ptourlas fixed the above issue.

@dsehnal I have a question. I can vaguely remember the trajectory playback being smoother in the past. If I go now to https://molstar.org/viewer/?snapshot-url=https%3A%2F%2Fmolstar.org%2Fdemos%2Fstates%2Fvillin-md.molx&snapshot-url-type=molx and press play at each frame it seems to compute something `Creating or updating UnitsVisual [0/1]` as well as updating the model tree on the left. Is this working as expected? Is just the playback rate set low and can be set higher?

**Comment by dsehnal** [comment]
Glad it works for you.

Showing all the models at once is just one of the options and using ``default`` preset instead of ``all-models`` does "fix" that. I guess I misunderstood what you meant by 

> Ideally, we would like each one of the entries to be added as a new model for the given topology

in the original post.

**Comment by ptourlas** [comment]
> Ideally, we would like each one of the entries to be added as a new model for the given topology

My mistake, it was bad usage of the term "model".

What other options besides `default` and `all-models` are available?

Also, I think about gathering the modifications I make for my use cases and adding them to the documentation as some sort of "recipes" for future reference and tutorials, along with some explanation of what they do. @dsehnal do you think that would be suitable?

**Comment by arose** [comment]
> Also, I think about gathering the modifications I make for my use cases and adding them to the documentation as some sort of "recipes" for future reference and tutorials, along with some explanation of what they do. @dsehnal do you think that would be suitable?

That would be most welcome!

**Comment by dsehnal** [comment]
Yeah, making a PR to https://github.com/molstar/docs with your notes would be great @ptourlas !

**Comment by ptourlas** [comment]
I'm working on it then.

> What other options besides `default` and `all-models` are available?

This though? :smile:

**Comment by arose** [comment]
In general `TrajectoryHierarchyPreset`s take a Trajectory (that is a list of Models, can be a simulation trajectory or NMR models, ...) and create structures/representations from it. A `StructureRepresentationPreset` takes a Structure and creates (sub)-structures/representations from it. So both of them affect how things will look in the viewer.

The viewer context has methods to register additional presets, see https://github.com/molstar/molstar/blob/master/src/extensions/rcsb/validation-report/behavior.ts#L60-L62.

**Comment by dsehnal** [comment]
Regarding the presets: you can quite easily write your own preset and instead of passing the name of the preset, apply the preset "object" directly. Also, in the end the presets are just wrappers around ``plugin.build()`` (or some higher level helpers, mostly for building the selections).

**Comment by dsehnal** [comment]
@ptourlas Btw if you want to get fancy and your backend supports partial downloads of the trajectory frames, you can implement your own [``Trajectory`` interface](https://github.com/molstar/molstar/blob/b53debcfef324066f71ba0f60a8b3f45ef6f2a31/src/mol-model/structure/trajectory.ts#L20) which downloads and caches the frames asynchronously. You would also have to implement your own version of ``TrajectoryFromModelAndCoordinates`` (something like ``MyTrajectoryStreamingFromModel``; and possibly some other functions) to make this work.

**Comment by ptourlas** [comment]
Thanks a lot, will try to make something readable out of this issue and visit the docs repo with it.
