### ISSUE TITLE
V3000 SDF Support

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#286]
Hello,

Would it be possible to support a V3000 SDF format when loading SDF into the viewer?

Thanks for your time,
Jason

**Comment by dsehnal** [comment]
Hi,

It would certainly be possible. Maybe you can help with a with that by extending the current SDF parser to support V3 as well?

David

**Comment by jpattle** [comment]
Hi @dsehnal,

I've created a PR to add parsing functionality for v3 sd files.

Let me know if it can be improved.

Thanks,
Jason
