### ISSUE TITLE
Non-Covalent Interaction Calculation

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#287]
Hello,

Currently when loading in a protein file (pdb) that contains native ligand data the non-covalent interactions between that naive ligand and the protein structure are calculated and can be displayed when clicking on the ligand to show the focus surroundings.

I was wondering whether there is any way in the current viewer to calculate these non-covalent interactions for a ligand that is not the native ligand in the protein file. For example if I load in an SDF containing a ligand I would like to be able to calculate and display the non-covalent interactions between that ligand and a protein from a separate pdb file.

Is this possible with the current viewer? If not, where would I start if I wanted to extend the functionality of the viewer in order to enable this behaviour?

Thanks for your time,
Jason

**Comment by dsehnal** [comment]
Hi,

If you create a "merged" structure the computation will work. This has been briefly discussed in #185.

Seeing this is coming up again, we might consider adding an action for this in the mail viewer too.

David

**Comment by jpattle** [comment]
Hi David,

Thanks for getting back to me. I have been looking into using a merged structure as you suggested and that looks to be the right route. I have been using the docking viewer tool as a starting point which works great.

I have a few questions regarding the interactions that are calculated, specifically regarding hydrogen bonds. I'm comparing the interactions calculated by Molstar with those calculated by PyMol.

First of all could you advise on how best to set the default max angle values set by the `HydrogenBondsProvider`? Currently I am doing the following but it does not feel like the right way to go about it:

```
const params = InteractionsParams.providers.params['hydrogen-bonds'] as any
params.defaultValue.params = {
    ...params.defaultValue.params,
    accAngleDevMax: deviationAngle,
    donAngleDevMax: deviationAngle,
    accOutOfPlaneAngleMax: maxPlaneAngle,
    donOutOfPlaneAngleMax: maxPlaneAngle,
};
```

Secondly, I have noticed that aromatic Nitrogen (specifically Pyridine and Pyrimidine) are not showing up as hydrogen acceptors and therefore do not form hydrogen bonds. I have found in the code base ([hydrogen-bonds.ts#L74](https://github.com/molstar/molstar/blob/73ac445a44974d95649aada9c47139a4b597835d/src/mol-model-props/computed/interactions/hydrogen-bonds.ts#L74) and [hydrogen-bonds.ts#L114](https://github.com/molstar/molstar/blob/master/src/mol-model-props/computed/interactions/hydrogen-bonds.ts#L144)) that any element within an aromatic ring is automatically considered ineligible for a hydrogen bond. Is this intentional?

Thanks again for your help,
Jason

**Comment by dsehnal** [comment]
@arose wrote this code so I think he's more qualified to answer your questions.

**Comment by arose** [comment]
> Secondly, I have noticed that aromatic Nitrogen (specifically Pyridine and Pyrimidine) are not showing up as hydrogen acceptors and therefore do not form hydrogen bonds. I have found in the code base (hydrogen-bonds.ts#L74 and hydrogen-bonds.ts#L114) that any element within an aromatic ring is automatically considered ineligible for a hydrogen bond. Is this intentional?

Hmm not sure we I added that. It was not in the original NGL code. I removed that rule, see de96244706e7fd33738124cb491aea84be22cc49.

**Comment by arose** [comment]
> First of all could you advise on how best to set the default max angle values set by the HydrogenBondsProvider? Currently I am doing the following but it does not feel like the right way to go about it:

I don't think we have a good way to do that globally. @dsehnal?

**Comment by dsehnal** [comment]
> First of all could you advise on how best to set the default max angle values set by the `HydrogenBondsProvider`? Currently I am doing the following but it does not feel like the right way to go about it:
> 
> ```
> const params = InteractionsParams.providers.params['hydrogen-bonds'] as any
> params.defaultValue.params = {
>     ...params.defaultValue.params,
>     accAngleDevMax: deviationAngle,
>     donAngleDevMax: deviationAngle,
>     accOutOfPlaneAngleMax: maxPlaneAngle,
>     donOutOfPlaneAngleMax: maxPlaneAngle,
> };
> ```

This is currently the only way to do this globally and indeed it feels a bit hacky. 

An alternative is passing the default value to ``structureProperties`` when applying the preset when loading the structure, something along the lines of:

```ts
await plugin.builders.structure.hierarchy.applyPreset(data, "default", { structureProperties: ... })
```

Here's an example how to compose the ``structureProperties``: https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/component.ts#L105

You can also build the state yourself or create your own preset based on https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/builder/structure/hierarchy-preset.ts#L57.

--------

I can definitely see the value of being able to easily override defaults and I don't think we are doing a good job with that in Mol*. I will think about how we can improve on that.

**Comment by arose** [comment]
We actually have a little helper for setting default params: `ParamDefinition.setDefaultValues`

**Comment by jpattle** [comment]
Thank you so much for your help, I've managed to make a lot of progress in the last few days. I'm almost at my desired solution.

I am basing my code off the [MergeStructures docking-viewer/index.ts#L182](https://github.com/molstar/molstar/blob/1a8dc2c637c3291986c592ab5a5e911a4e42fd32/src/apps/docking-viewer/index.ts#L182) transform which has been very helpful. I can see that it takes all units from the two structures and adds them to a single structure.

I have some pdb files which include a native ligand (`HETATM` in the pdb file) and unfortunately if I merge such a structure with sd files containing ligands in a similar space it creates bonds between them and displays them incorrectly.

I can manually avoid this by excluding the unit from the pdb structure that has the same number of atoms as that native ligand. However this is not a sustainable solution and I was wondering if there was some programatic way of determining which unit from the pdb structure corresponds to the native ligand?

The only thought that I've had would be to determine the native ligand's unit by assuming it has no `interUnitBonds`:

```
// Line 213+
const structure = dependencies![ref].data as Structure;
for (const unit of structure.units) {
    if (structure.units.length > 1 && structure.interUnitBonds.getConnectedUnits(unit.id).length === 0)
    {
        continue;
    }

    builder.addUnit(...);
}
```

However I'm not sure this is a robust solution as this may accidentally ignore the unit that corresponds to the protein's backbone if it has no other connected units. Any advice would be appreciated.

Thank you so much for your help!

Jason

**Comment by dsehnal** [comment]
Create a selection that removes all the HETATM records (if that's how your native ligand is determined) from the source protein. This creates a new ``Structure`` node which you then pass to the merge transform.

You can use for example https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/builder/structure.ts#L137 to create the filtered structure. For constructing query expressions, many examples are here https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/helpers/structure-selection-query.ts.

Alternatively, you can just execure the query inside the "merge transform" to get the unique units.

**Comment by jpattle** [comment]
I have been able to reach our desired functionality in merging structures and ignoring the native ligand. Thank you both for your help and quick responses. With the release of V2.4.1 the hydrogen bonds involving aromatic nitrogen atoms is also functioning correctly, thank you for including those changes so quickly.

Again, thank you for your time and help throughout this. I'm happy to call this question closed.
Jason
