### ISSUE TITLE
NPM package includes source map files referencing non-existent directory

### ISSUE THREAD

**Issue by russellp17** [molstar/molstar#296]
The published NPM package includes source map files that reference the "src" directory (e.g. `{"version":3,"file":"data-source.js","sourceRoot":"","sources":["../../src/mol-util/data-source.ts"], ...}` but the output project root is `molstar/lib/` - this leads to a bunch of Webpack warnings: 
```
WARNING in ./node_modules/molstar/lib/mol-util/value-cell.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/mol-util/value-cell.ts': Error: Can't resolve '../../src/mol-util/value-cell.ts' in ...
```

**Comment by dsehnal** [comment]
The ``src`` folder is currently not included in the NPM package at all. We could either add it or not include the source map files. Any preferences?

**Comment by russellp17** [comment]
I think not including is more common for packages, but no real preference

**Comment by dsehnal** [comment]
``molstar@3.0.0-dev.2`` and later have the source maps ignored and overall the package is lot lighter. The trick was that the ``.npmignore`` file needs to be inside the ``lib`` folder otherwise it doesn't work for some arcane reasons.
