### ISSUE TITLE
loading a pdb, selecting and coloring a few AA

### ISSUE THREAD

**Issue by babarlelephant** [molstar/molstar#297]
Hi, npm fails to compile your code, anyway your code is already compiled on https://molstar.org/viewer/molstar.js

Once I have loaded a pdb  with   viewer.loadPdb("7KDG");

How can I reproduce programatically what I do when clicking on the buttons, that is adding a few AA to my selection then creating a component drawing them as ball & stick in red ?

viewer.plugin.managers.structure.selection.getLoci may be what I need but how to use it?

Thank you.

**Comment by dsehnal** [comment]
Hi,

> Hi, npm fails to compile your code, anyway your code is already compiled on https://molstar.org/viewer/molstar.js

It compiles for me. What version of node are you using and do you have the packages installed?

> 
> Once I have loaded a pdb with viewer.loadPdb("7KDG");
> 
> How can I reproduce programatically what I do when clicking on the buttons, that is adding a few AA to my selection then creating a component drawing them as ball & stick in red ?
> 
> viewer.plugin.managers.structure.selection.getLoci may be what I need but how to use it?

Unfortunately, you currently won't be able to achieve this just from the compiled "default viewer" but rather will have to use a JS bundler like WebPack.

To get started you can search the source code for ``setStructureOverpaint``. You can use it together with ``this.plugin.managers.structure.hierarchy`` and generating a query to get the required loci. Many query examples are in https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/helpers/structure-selection-query.ts and you find some ways to query for example in ``examples/basic-wrapper``.

--------------------

Regarding your edited comment about it being weird that there are missing docs for this, I understand your frustration. If you would like to make the situation better, we accept PRs with more docs at https://github.com/molstar/docs which will then show at https://molstar.org/docs/, for example with your solution for the coloring.

**Comment by dsehnal** [comment]
- The Viewer is a React application and it is common that the functions bound to UI elements are not exported. Using WebPack (or Rollup or esbuild or whatever) is a standard practice.
- If you have ideas on how to improve the project, you are more than welcome to contribute to it.
