### ISSUE TITLE
interface residues

### ISSUE THREAD

**Issue by MochaCai** [molstar/molstar#304]
Could any help me with this.  how do I generate a graph only with the interface residues of a homo-dimmer? Thank you!

**Comment by arose** [comment]
Not sure what you mean exactly.

With Mol* you can visualize, e.g., all the residues that are within 5 Angstrom of another chain. Here is a homo dimer example from the PDB, 5IN3:

![image](https://user-images.githubusercontent.com/272250/145504288-e209ce8a-6754-49bd-aaa2-7d3ce2ee4954.png)

**Comment by MochaCai** [comment]
My original plan was just show the interface without these residue far away, but your graph looks good to me. Thank you very much.
