### ISSUE TITLE
Add formal charge label to representation

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#313]
Greetings!

Is there a quick and painless way to add a label displaying the formal charge (`M  CHG  1   8  -1`) to the nitrogen at position 8
(` 0.2451   -0.3881   -0.5673 N   5  5  0  0  0  2  0  0  0  0  0  0`)

```
SMILES-CFFFSOON-SOOCFFF
     RDKit          3D

 15 14  0  0  0  0  0  0  0  0999 V2000
    2.4644   -0.6833    0.6783 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1589   -0.1223   -0.3545 F   0  0  0  0  0  0  0  0  0  0  0  0
    2.4354   -2.0263    0.4264 F   0  0  0  0  0  0  0  0  0  0  0  0
    3.2334   -0.5214    1.7934 F   0  0  0  0  0  0  0  0  0  0  0  0
    0.7862    0.0206    0.8608 S   0  0  0  0  0  6  0  0  0  0  0  0
    0.9929    1.4434    1.1263 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.1705   -0.7131    1.9690 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2451   -0.3881   -0.5673 N   5  5  0  0  0  2  0  0  0  0  0  0 <--------
   -1.0100    0.4366   -1.0736 S   0  0  0  0  0  6  0  0  0  0  0  0
   -1.6478   -0.2086   -2.2311 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7964    1.8705   -1.2847 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2304    0.2627    0.2953 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3428   -1.0280    0.7238 F   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9714    1.0394    1.3799 F   0  0  0  0  0  0  0  0  0  0  0  0
   -3.4880    0.6179   -0.1175 F   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  1  3  1  0
  1  4  1  0
  1  5  1  0
  5  6  2  0
  5  7  2  0
  5  8  1  0
  8  9  1  0
  9 10  2  0
  9 11  2  0
  9 12  1  0
 12 13  1  0
 12 14  1  0
 12 15  1  0
M  CHG  1   8  -1
M  END
$$$$
```
From what I understand, I could parse the file to get the charges and the atom ID's and then add the labels manually with something similar to this:
```javascript
styleProps = styleProps || { borderWidth: 0.1, borderColor: molstar.COLOR_NAMES.white };
            const atomExpression = this.expressions.atom;
            const structure = _structures[structureKey].data;
            const context = _plugin.managers.task.currentContext;

            Object.keys(atomLabels).forEach((atomId) => {
                const _atomId = parseInt(atomId)

                const query = molstar.StructureSelectionQuery('Query', atomExpression(_atomId));
                query.getSelection(_plugin, context, structure)
                    .then((selection) => {
                        const loci = molstar.StructureSelection.toLociWithSourceUnits(selection);

                        molstar.createTextRepresentation({ text: atomLabels[atomId], loci, size }, styleProps)
                            .then((label) => {
                                label.setState({ pickable: false });
                                _plugin.canvas3d.add(label);

                                if (!_representations[structureKey][representationKey]) {
                                    _representations[structureKey][representationKey] = [];
                                }
                                _representations[structureKey][representationKey].push(label);
                            });
                    });
            });
```
But I also saw this, https://github.com/molstar/molstar/blob/7a25699c2353c4142286c3403d3ab2416f48043c/src/mol-model/structure/model/properties/atomic/hierarchy.ts#L51
which made think that mol* is already aware of formal charges in some way.

Thanks in advance.

**Comment by dsehnal** [comment]
Hi,

- from what I gather the ``M  CHG`` isn't being parsed at all so the 1st step would be making a PR  that parses it to https://github.com/molstar/molstar/tree/master/src/mol-io/reader/sdf and https://github.com/molstar/molstar/blob/master/src/mol-io/reader/mol/parser.ts and assign the ``pdbx_formal_charge`` value in https://github.com/molstar/molstar/blob/master/src/mol-model-formats/structure/mol.ts#L20
- Displaying the labels: You can look up ``StructureSelectionsLabel3D`` and start from there. It is possible to access the property from a ``StructureElement.Loci`` for example with ``StructureProperties.atom.pdbx_formal_charge(loci)``.

**Comment by yangjiakun326** [comment]
> Hi,
> 
> * from what I gather the `M  CHG` isn't being parsed at all so the 1st step would be making a PR  that parses it to https://github.com/molstar/molstar/tree/master/src/mol-io/reader/sdf and https://github.com/molstar/molstar/blob/master/src/mol-io/reader/mol/parser.ts and assign the `pdbx_formal_charge` value in https://github.com/molstar/molstar/blob/master/src/mol-model-formats/structure/mol.ts#L20
> * Displaying the labels: You can look up `StructureSelectionsLabel3D` and start from there. It is possible to access the property from a `StructureElement.Loci` for example with `StructureProperties.atom.pdbx_formal_charge(loci)`.


Hello, I have the same demand. I read your code, but I don't know how to implement it. Could you be more specific?
sdf content
```sdf
26
                    3D
 Structure written by MMmdl.
 43 46  0  0  1  0            999 V2000
    3.8290  -49.9082    7.3567 O   0  0  0  0  0  0
    3.1153  -49.0416    6.8012 C   0  0  0  0  0  0
    3.5513  -47.8977    6.5562 O   0  5  0  0  0  0
    1.7057  -49.3580    6.4403 C   0  0  0  0  0  0
   -0.1076  -50.6487    6.3793 C   0  0  0  0  0  0
   -1.0211  -51.7084    6.5402 C   0  0  0  0  0  0
   -2.3348  -51.5531    6.0492 C   0  0  0  0  0  0
   -2.6993  -50.3586    5.3936 C   0  0  0  0  0  0
   -1.7635  -49.3099    5.2420 C   0  0  0  0  0  0
   -0.4423  -49.4338    5.7433 C   0  0  0  0  0  0
    0.7328  -48.6071    5.8015 C   0  0  0  0  0  0
    0.8592  -47.2049    5.2675 C   0  0  0  0  0  0
    0.9701  -46.1519    6.3924 C   0  0  0  0  0  0
   -0.0852  -45.0395    6.3276 C   0  0  0  0  0  0
   -1.4118  -45.4805    6.0441 O   0  0  0  0  0  0
   -2.2386  -45.8040    7.0949 C   0  0  0  0  0  0
   -4.0387  -46.5572    9.1587 C   0  0  0  0  0  0
   -2.7241  -47.0517    9.1502 C   0  0  0  0  0  0
   -1.8288  -46.6752    8.1339 C   0  0  0  0  0  0
   -0.7241  -52.6191    7.0419 H   0  0  0  0  0  0
   -3.0568  -52.3474    6.1618 H   0  0  0  0  0  0
   -3.7027  -50.2338    5.0158 H   0  0  0  0  0  0
   -2.0623  -48.3873    4.7602 H   0  0  0  0  0  0
    0.0186  -46.9829    4.6116 H   0  0  0  0  0  0
    1.7413  -47.1366    4.6230 H   0  0  0  0  0  0
    1.9528  -45.6851    6.3456 H   0  0  0  0  0  0
    0.9550  -46.6329    7.3658 H   0  0  0  0  0  0
    0.1913  -44.3765    5.5164 H   0  0  0  0  0  0
   -0.0677  -44.4348    7.2308 H   0  0  0  0  0  0
   -0.8492  -47.1142    8.1369 H   0  0  0  0  0  0
   -4.4644  -45.6869    8.1312 C   0  0  0  0  0  0
   -3.5686  -45.3157    7.0918 C   0  0  0  0  0  0
   -4.0196  -44.4491    6.0697 C   0  0  0  0  0  0
   -5.3473  -43.9766    6.0646 C   0  0  0  0  0  0
   -6.2357  -44.3575    7.0895 C   0  0  0  0  0  0
   -5.7910  -45.2055    8.1244 C   0  0  0  0  0  0
   -3.3603  -44.1405    5.2743 H   0  0  0  0  0  0
   -5.6744  -43.3185    5.2717 H   0  0  0  0  0  0
   -7.2548  -43.9991    7.0843 H   0  0  0  0  0  0
   -6.4744  -45.4962    8.9093 H   0  0  0  0  0  0
   -2.4004  -47.7370    9.9189 H   0  0  0  0  0  0
   -4.7163  -46.8570    9.9410 H   0  0  0  0  0  0
    1.2056  -50.5983    6.7955 O   0  0  0  0  0  0
M  CHG  1   3  -1
M  END
> <r_user_dG.exp>
-8.23584030891924

$$$$
```
charge 
```json
		"26": {
			"atom_info": {
				"0": {
					"type": "o_1ke-",
					"charge": -0.8228
				},
				"1": {
					"type": "c_3o",
					"charge": 0.9128
				},
				...
			}
		},
```

**Comment by arose** [comment]
> Hello, I have the same demand. I read your code, but I don't know how to implement it. Could you be more specific?
sdf content

Hi @yangjiakun326, what did you try so far? Where are you stuck?

Note that @ptourlas is working on a PR for this, see #314.

**Comment by ptourlas** [comment]
Hello @yangjiakun326! I'll try to clarify a bit as well.
The core idea is to add a parsing function similar to the one that parses the atoms and the bonds. My implementation of this can be seen here (the comment on the tokenizer's inner workings might help):
https://github.com/ptourlas/molstar/blob/ca38d9adb13b7361dea439b0b69ecb96363d2538/src/mol-io/reader/mol/parser.ts#L104
For now this function only reads the `M CHG * * *` properties and assigns them to the `formalCharges` property of the `MolFile` interface:
https://github.com/ptourlas/molstar/blob/ca38d9adb13b7361dea439b0b69ecb96363d2538/src/mol-io/reader/mol/parser.ts#L43

Normally, the formal charge in line `3.5513  -47.8977    6.5562 O   0  5  0  0  0  0` should also be parsed and replaced by `M  CHG  1   3  -1`, if the latter is present. But I haven't come up with a way to do that yet.
As for the second charge that you added (after the sdf content), I have not seen it again.

**Comment by arose** [comment]
> Normally, the formal charge in line 3.5513 -47.8977 6.5562 O 0 5 0 0 0 0 should also be parsed and replaced by M CHG 1 3 -1, if the latter is present. But I haven't come up with a way to do that yet.

You can parse both in `mol-io/reader/mol/parser.ts` and only when you create a `Model` in `mol-model-formats/structure/mol.ts` to decide which to use. Specifically when you add the atom_site.pdbx_formal_charge column.

While you are at it, how about you add a formal-charge color theme similar to `mol-theme/color/partial-charge.ts`?

**Comment by ptourlas** [comment]
> While you are at it, how about you add a formal-charge color theme similar to `mol-theme/color/partial-charge.ts`?

I am willing to work on this as well once I get the formal charge labels working. :+1:

**Comment by ptourlas** [comment]
>  Displaying the labels: You can look up `StructureSelectionsLabel3D` and start from there. It is possible to access the property from a `StructureElement.Loci` for example with `StructureProperties.atom.pdbx_formal_charge(loci)`.

@dsehnal Supposing I load a `.mol` file, how do I get these loci in order to see the structure properties? Is there a function I can call with the representation's `ref`?

**Comment by dsehnal** [comment]
@ptourlas What would you like to do with that? The Loci/Location should get passed down automatically to the relevant parts of the code (e.g. when you are creating a label provider: https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/behavior.ts#L27, there you can use ``StructureProperties.atom.pdbx_formal_charge(location)``; sorry if I created confusion about Loci vs Location; Loci is "multiple locations`` and you always need a single one to pass to the property getter).

**Comment by ptourlas** [comment]
> @ptourlas What would you like to do with that? The Loci/Location should get passed down automatically to the relevant parts of the code (e.g. when you are creating a label provider: https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/behavior.ts#L27, there you can use `StructureProperties.atom.pdbx_formal_charge(location)`; sorry if I created confusion about Loci vs Location; Loci is "multiple locations`` and you always need a single one to pass to the property getter).

This clarifies my use case. Since the relevant PR is also merged, I am closing the issue.
Thanks!
