### ISSUE TITLE
How to delete previous structure before to load another one

### ISSUE THREAD

**Issue by ebettler** [molstar/molstar#315]
Hello,
i've tried to do something close to 'lightning demo' but with molstar.js file (not default index.js file): display minimal windows, with additional buttons and sequence viewer.
My problem: when i click on an additionnal button to load another PDB structure, new file is added to the previous one on screen !
So how to delete previous structure and load another one ?
or..another solution: how to add sequence viewer with index.js lightning demo file ? 
Thanks,

Emmanuel

**Comment by dsehnal** [comment]
Hi, 

> So how to delete previous structure and load another one ?

```ts
await plugin.clear()
```

> another solution: how to add sequence viewer with index.js lightning demo file ?

Need to tweak the ``layout`` and ``components`` in the plugin spec. This is [here](https://github.com/molstar/molstar/blob/master/src/examples/lighting/index.ts#L75) in the lighting demo (if you use "Navigate to declaration" in VS Code (or any other editor that supports similar features) on the ``layout`` property it will navigate to the options you can use).

> molstar.js file (not default index.js file)

The "default viewer" provides some options you [can tweak about the layout](https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.ts#L69) but if want something more specific, you will have to get the NPM package or clone this repo and use a packager like WebPack to build your app.

**Comment by ebettler** [comment]
Thanks !! Was very helpfull !
