### ISSUE TITLE
How to change color preset automaticaly after protein loading or via html button/javascript command

### ISSUE THREAD

**Issue by ebettler** [molstar/molstar#317]
Hi,
sorry for my rookie question but i want to change atomic color automaticaly after protein loading.
More precisely, i want to apply color uncertainty and be able to apply other preset via javascript.
I'm using lightning example for html page, buttons etc... but i can't found which command to send to the viewer to change color.
Thanks,

**Comment by dsehnal** [comment]
Hi,

you can use an approach similar to https://github.com/molstar/molstar/discussions/301
