### ISSUE TITLE
Camera Position for 1GK8

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#318]
Camera gets positioned inside the structure when loading [1GK8](https://www.rcsb.org/3d-view/1GK8/1), resembling a Rorschach test. Thanks for having a look!

![Capture9](https://user-images.githubusercontent.com/9744615/146356884-09fd84b0-4f8f-47e4-a588-cf86ca42c11f.PNG)

**Comment by dsehnal** [comment]
It loads fine for me at https://molstar.org/viewer/

**Comment by JonStargaryen** [comment]
Same on molstar.org for me, in Chrome/Firefox/Safari, both on Windows and MacOS:

![Screen Shot 2021-12-16 at 11 50 15 AM](https://user-images.githubusercontent.com/9744615/146358329-60ed0ecf-8f2b-4a5a-8807-db97c852a81a.png)

**Comment by dsehnal** [comment]
Oh, my bad, I tried 1KG8. I will have a look.

**Comment by dsehnal** [comment]
Should be fixed in 3.0.0-dev.5.

**Comment by JonStargaryen** [comment]
Works nicely, thanks!

BTW is there a timeline for v3?

**Comment by dsehnal** [comment]
Pretty safe to use the "dev" version now as the breaking changes there should not affect you at all (only the per-object materials come to mind, another breaking change will be per-representation clipping). After #309 and #310 are merged we should be good to go with 3.0. One more upcoming feature coming by the start of January is the ability to export CIF files directly from the browser.

**Comment by JonStargaryen** [comment]
Thanks for clarifying. Yeah, there are a number of nice things in v3, I'll update the RCSB project accordingly.
