### ISSUE TITLE
Ball & Stick Representation Broken in Safari

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#322]
Water, ligands, and ball & stick representation in general aren't rendered in Safari. Still possible to hover/focus invisible elements. Happens in 15.1 & 15.2.

![safari](https://user-images.githubusercontent.com/9744615/146744572-94eff725-46c3-4650-bc24-3dc1a87f5898.png)

**Comment by dsehnal** [comment]
This seems like Safari fails to render the impostors. These issues seem to be solved in Safari 15.4 tech preview. Do you think an option is to just wait this one out?

**Comment by JonStargaryen** [comment]
Yeah, sounds good to me.

**Comment by arose** [comment]
@JonStargaryen can you try with lastest master? Fixed a webgl1 issue there.

**Comment by JonStargaryen** [comment]
Ligands and ball & stick representation are working in Safari 15.2. Waters are still missing, but now molecules get rendered when focused. No errors logged to the browser console.

![4CW6](https://user-images.githubusercontent.com/9744615/146893018-74a853c9-2ea8-4902-84f5-b840770b7e83.png)

**Comment by dsehnal** [comment]
The bug is that transparent impostors don't get rendered at all. I've already discussed this a bit with @arose. I can see these options:
- Disable wboit in Safari.
- Disable impostors in Safari.
- Somehow fix the bug (which might be a bug in Metal and not possible).
- Wait and see if they fix this at the Metal level.

**Comment by arose** [comment]
Did some digging and as far as I can tell the issue is the combination of writing to `gl_FragDepth` and using drawBuffers. Both features work fine on their own but not together.

**Comment by dsehnal** [comment]
So the action item is disable WBOIT for Safari 15.X for now and re-enable it if they fix it? Should we also submit a bug-report for this?

**Comment by arose** [comment]
> So the action item is disable WBOIT for Safari 15.X for now and re-enable it if they fix it?

Yes, will you do it?

> Should we also submit a bug-report for this?

I will submit try to create a minimal reproduction and then do the bug report.

**Comment by arose** [comment]
Created a ANGLE issue with a minimal reproduction for WebGL1: https://bugs.chromium.org/p/angleproject/issues/detail?id=6847.

**Comment by dsehnal** [comment]
> Yes, will you do it?

Yeah.
