### ISSUE TITLE
Clicking on surfaces from volume streaming does not correctly center

### ISSUE THREAD

**Issue by arose** [molstar/molstar#331]
Clicking on isosurfaces from volume streaming does not correctly center them. The center/zoom on click works fine for isosurfaces from volumes not loaded using the streaming behavior.

**Comment by arose** [comment]
@dsehnal any idea? Is there an extra transform done?

**Comment by arose** [comment]
This has been the case for long time, just never reported it since the default opacity for volume streaming surfaces is too low to allow picking.

**Comment by dsehnal** [comment]
I will have a look.

**Comment by dsehnal** [comment]
It is broken when you download volume from URL too when it's a subset, e.g. https://www.ebi.ac.uk/pdbe/densities/x-ray/1tqn/box/-10,-20,-20/0,-10,-10?detail=3 (download URL as BinaryCIF).

Anyway, this seems to be a problem with the GPU computation as it works fine when you do it on a CPU:

https://user-images.githubusercontent.com/21145776/147740216-d9dacea7-6b93-49e7-a33e-748e1b7cbbe6.mp4

Your turn @arose :)

**Comment by arose** [comment]
> Your turn @arose :)

Indeed... Very helpful to know that it happens only for GPU MC. Thanks @dsehnal. Fixed with #332.
