### ISSUE TITLE
TypeError: "group is undefined" upon loading from OPM

### ISSUE THREAD

**Issue by corredD** [molstar/molstar#34]
Hi,
while trying to load a structure from the OPM databased  the following error appeared:
TypeError: "group is undefined"
    parseRemark350 http://localhost/build/viewer/index.js:48603
    pdbToMmCif http://localhost/build/viewer/index.js:49395
    step http://localhost/build/viewer/index.js:183209
    verb http://localhost/build/viewer/index.js:183190
    __awaiter http://localhost/build/viewer/index.js:183183
    __awaiter http://localhost/build/viewer/index.js:183179
    pdbToMmCif http://localhost/build/viewer/index.js:49266
    trajectoryFromPDB http://localhost/build/viewer/index.js:48367
    step http://localhost/build/viewer/index.js:183209
    verb http://localhost/build/viewer/index.js:183190
    fulfilled http://localhost/build/viewer/index.js:183180
index.js:109125:33
    updateSubtree http://localhost/build/viewer/index.js:109125
    step http://localhost/build/viewer/index.js:183209
    verb http://localhost/build/viewer/index.js:183190
    rejected http://localhost/build/viewer/index.js:183181
here is one example of such file:
https://opm.phar.umich.edu/proteins/109
or direct link
https://opm-assets.storage.googleapis.com/pdb/1aa7.pdb
loading from disk give the same error. 
Thanks in advance for looking into it.

**Comment by arose** [comment]
looking into it...

**Comment by arose** [comment]
fixed, older pdb format...
