### ISSUE TITLE
color a specific part of protein?

### ISSUE THREAD

**Issue by blackjack-uic** [molstar/molstar#342]
Hi,

Thanks for the amazing tool! I'm trying to implement Mol* into a website and I need to color some region of the protein based on user input, for example, from resi 10-100 red, resi 200-300 green, and the rest grey. Is there a way to do this?

Thanks!

**Comment by dsehnal** [comment]
Hi,

yes, you can define custom themes to which you can pass properties to. Here's an example: https://github.com/molstar/molstar/blob/master/src/examples/basic-wrapper/index.ts#L108. You can pass the props to the theme say as ``{ color: 'theme-name', colorProps: { ranges: [[1, 10], [15, 25]] }}``. [Here's](https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/color.ts#L44) an example of a more complex theme which allows you pass props.

Let us know if you need more help.

**Comment by blackjack-uic** [comment]
> Hi,
> 
> yes, you can define custom themes to which you can pass properties to. Here's an example: https://github.com/molstar/molstar/blob/master/src/examples/basic-wrapper/index.ts#L108. You can pass the props to the theme say as `{ color: 'theme-name', colorParams: { ranges: [[1, 10], [15, 25]] }}`. [Here's](https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/color.ts#L44) an example of a more complex theme which allows you pass props.
> 
> Let us know if you need more help.

Thanks for the quick reply and the info! But typescript is completely new to me and I'm struggling of reading it...So what I did is after npm build, in the \build\examples\basic-wrapper\index.html, I found this line:
```
 addControl('Apply Custom Theme', () => BasicMolStarWrapper.coloring.applyCustomTheme());
```
I believe this is the function of the one you mentioned after converting TS into JS? Is there a way I can pass the props in this line or I need to do something on the TS script and npm build again?

Thank you for your help!

**Comment by dsehnal** [comment]
Unfortunately, that is not possible. You would have to set up a JS/TS project with webpack or a similar packing tool to be able to use these features with your own custom functionality.

**Comment by xuhen** [comment]
some follow up question, when I pass `colorParams`  how to get those params in [coloring.ts](https://github.com/molstar/molstar/blob/master/src/examples/basic-wrapper/coloring.ts) 's getData function.
