### ISSUE TITLE
How can I detect when a user clicks an atom?

### ISSUE THREAD

**Issue by samirelanduk** [molstar/molstar#350]
I am using the 'PluginContext without built-in React UI' method, and am displaying a protein structure in ball-and-stick representation. When the user clicks an atom, I need to obtain the ID and coordinates of that atom, and ideally change its representation. How can I do this?

Looking through the source code, I assume this has something to do with the 'behaviors' list of the PluginSpec object that gets passed on creation, but the source code for the 14 or so behaviors in the default plugin spec is quite hard to read/comprehend, and I am not really sure how to create custom behaviors.

The documentation just says "the state of the Mol* plugin is usually governed by dynamics behaviors which can be set up in initial plugin specification or updated during the plugin runtime. This allows for high modularity and customizability of individual plugin instances." This is useful to know but doesn't really explain how to use behaviors.

**Comment by arose** [comment]
One example is the the built in "focus" behavior, that shows sticks and interactions when clicking on a residue: https://github.com/molstar/molstar/blob/master/src/mol-plugin/behavior/dynamic/selection/structure-focus-representation.ts

**Comment by samirelanduk** [comment]
Thanks for linking to this, but it's not really clear what's happening in that file.

- What 'is' a behavior object, fundamentally? Is it a description of some 'if this happens, do that' connection? If so where is that actually defined in the behavior object?
- What is a 'ctor'?
- What is the distinction between the `StructureFocusRepresentationBehavior` and the `StructureFocusRepresentationParams` objects? What do they represent? The latter seems to return some kind of description of a view, does that mean the only possible output of a behavior is a change to the view on screen?
- Is 'focus' the same as 'is clicked on'?
- How can I detect when a user clicks an atom? Like, at a pseudocode level, what is the logic flow in doing that?

**Comment by samirelanduk** [comment]
I've stumbled my way to some sort of custom behavior, but the main thing I am stuck on now is getting the actual atom details from the Loci that is clicked. The loci object seems to mostly have information about the whole structure.

It has a `structure` property and an `elements` array:

- `structure` definitely seems to just describe the overall structure.
- `elements` is an array of... 'element' objects, I guess. I'm not sure what this represents as again it mostly seems to be a description of the whole structure, though it does seem to be possible to extract information about the *residue* that was clicked. It has an `indices` object which is an extremely small float (`3.3951932663e-313` - basically 0) and a `unit` object, which in turn has a `conformation` object, which does seem to have coordinate information, but just as vectors of xyz values for every atom in the structure. Is there a way to get at least the index of the atom that was clicked?

**Comment by arose** [comment]
Hi @samirelanduk, see below for an example on how to get some atom infos from a `Loci`. A `Loci` can point to other things than atoms so there are a few checks in there. The `StructureProperties` object has many more methods, your IDE will tell you. The "extremely small float" you see is because the `indices` are of type `OrderedSet` which is either a sorted array of indices or an interval encoded as a single number (double).

```ts
import { OrderedSet } from 'molstar/lib/mol-data/int';
import { Loci } from 'molstar/lib/mol-model/loci';
import { StructureElement, StructureProperties, Unit } from 'molstar/lib/mol-model/structure';

function getAtomInfo(loci: Loci) {
    const atomInfo: { id: number, labelCompId: string, authSeqId: number, authAsymId: string }[] = [];
    if (StructureElement.Loci.is(loci)) {
        const l = StructureElement.Location.create(loci.structure);
        for (const e of loci.elements) {
            if (Unit.isAtomic(e.unit)) {
                l.unit = e.unit;
                OrderedSet.forEach(e.indices, v => {
                    l.element = e.unit.elements[v];
                    atomInfo.push({
                        id: StructureProperties.atom.id(l),
                        labelCompId: StructureProperties.atom.label_comp_id(l),
                        authSeqId: StructureProperties.residue.auth_seq_id(l),
                        authAsymId: StructureProperties.chain.auth_asym_id(l),
                    });
                });
            }
        }
    }
    return atomInfo;
}
```

**Comment by samirelanduk** [comment]
Thanks!
