### ISSUE TITLE
Representing HETATM as surface and with diverse color?

### ISSUE THREAD

**Issue by rajiv03** [molstar/molstar#355]
How can we represent the heteroatoms like dummy atoms(i.e., cavities in HETATM) as surface and random color them? Can it be done in PDB format ?

**Comment by arose** [comment]
Hi, that should be possible to do with the UI on https://molstar.org/viewer/. If you want to do it programmatically you will need to write your own wrapper (like https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.ts).
