### ISSUE TITLE
Component transparency wrong when changing state snapshot

### ISSUE THREAD

**Issue by arose** [molstar/molstar#356]
See Polymer component in https://molstar.org/viewer/?snapshot-url=https://molstar.org/viewer-docs/tips/measurements/orientation.molx&snapshot-url-type=molx

**Comment by arose** [comment]
@dsehnal any idea?

**Comment by dsehnal** [comment]
Snapshot 2 has the polymer component hidden and when swapping to snapshot 1, it gets reset in the state tree but doesn't get updated for the visual, which stays hidden.

![image](https://user-images.githubusercontent.com/21145776/151701953-155c7709-e16a-43cd-a45d-1bc5dc4ebb9d.png)

Or is the issue also something else?
