### ISSUE TITLE
Molstar lighting feature gone? 

### ISSUE THREAD

**Issue by JoelTre** [molstar/molstar#359]
Hi there

In Molstar I used to be able to change the lighting type under the settings menu (to flat, glossy, metallic, plastic, etc) but this feature is not there anymore. Is this feature still available and if so where do I find it?

before: 
![image](https://user-images.githubusercontent.com/98678005/151686304-682daa1a-2c85-4e5e-b533-bd2708b39f0c.png)

now: 
![image](https://user-images.githubusercontent.com/98678005/151686311-77f01f31-8a6f-4619-9ce3-c758a2e0e931.png)

Thanks

**Comment by arose** [comment]
Hi @JoelTre, we now have a materials settings that can be changed for all components at once

![image](https://user-images.githubusercontent.com/272250/151686415-f04e1f66-2a77-4263-947b-840a78e356c4.png)

or per component representation

![image](https://user-images.githubusercontent.com/272250/151686440-2db1053c-77a0-4e71-81e6-2a95e5b5b63a.png)

For the "flat" option you have to drill down into the advanced representation options

![image](https://user-images.githubusercontent.com/272250/151686469-a26f5dfd-cd43-43a7-bc11-e913c16a62ec.png)

Finally, if you want to re-create the David Goodsell's illustrative style see this tip https://molstar.org/viewer-docs/tips/illustrative-style/

**Comment by JoelTre** [comment]
Thank you so much! Very clear answer :) I knew I'd be somewhere.

**Comment by arose** [comment]
You're welcome

**Comment by dsehnal** [comment]
@tubiana Would it be an option for you to add a button that changes the style yourself? You can change the ``material`` property of your visuals as well as the structure representations.

You should be able to do something like this:

```ts
const update = this.plugin.build();
const representations = this.plugin.state.data
    .selectQ(p => p.root.children().withTransformer(StateTransforms.Representation.StructureRepresentation3D));
const myVisuals = this.plugin.state.data
    .selectQ(p => p.root.children().withTransformer(WhateverTransformUsedToCreateCustomStuff));
for (const r of representations) {
    update.to(r).update(old => { old.type.params.material = newMaterial; })
}
for (const r of myVisuals) {
    update.to(r).update(old => { old.path.to.material = newMaterial; })
}
await update.commit();
```

**Comment by tubiana** [comment]
Hi again :-) 

Thank you for your answer, we will see if we can do it :-) 
I'm no expert in typescript code or webdev, so I will let this to our engineer :-)

Best regards,
Thibault.
