### ISSUE TITLE
Exported Structures Render without Secondary Structure if Transformed

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#364]
Alex mentioned in #334 that transformed chains get exported without secondary structure information. A problematic file is attached. As mentioned before, it's rendered with SSE after the `database_2` category is omitted.

No `struct_conf` content is exported due to the check at:
https://github.com/molstar/molstar/blob/b53debcfef324066f71ba0f60a8b3f45ef6f2a31/src/mol-model/structure/export/categories/secondary-structure.ts#L83

Can this check be more lenient and include records if the original unit would have been included and was only moved as part of a superposition?

[1U19.zip](https://github.com/molstar/molstar/files/7998366/1U19.zip)

**Comment by dsehnal** [comment]
I believe the condition is to prevent multiple records being emitted when trying to export an assembly.

Iterating over ``structure.unitSymmetryGroups`` instead of ``structure.units`` should solve this. Thoughts @arose?

**Comment by arose** [comment]
> Iterating over structure.unitSymmetryGroups instead of structure.units should solve this. Thoughts @arose?

Sounds right, so iterate over `structure.unitSymmetryGroups` and only check `!Unit.isAtomic(unit)`.

Can you test this @JonStargaryen and do a PR?

**Comment by JonStargaryen** [comment]
Sounds good. With [88a9516](https://github.com/JonStargaryen/molstar-proto/commit/88a95162e966e10966c6250547bac05741ea156d), the category gets populated when dealing with transformed chains. Entries are still unique for assemblies like 1m4x or when symmetry mates are being visualized.
