### ISSUE TITLE
Load local files

### ISSUE THREAD

**Issue by LivC182** [molstar/molstar#37]
Hi Sorry to bother you, I was wondering if it is possible to load locally generated pdb models.

**Comment by Valdes-Tresanco-MS** [comment]
@LivC182 Yes, "Open Files" appears in the Home menu. You can select any local file with format supported by molstar

**Comment by LivC182** [comment]
@Valdes-Tresanco-MS yes I know about that feature I mean loading it on the backend. Right now I am doing it: viewer.loadPdb(pdb_id). However, I generate homology models, which I would like to display on my website using molstar. I used ngl in the past and you could load a string. I was wondering if that feature is still available here, or if I can give the path to where my pdbs are stored.

**Comment by arose** [comment]
there is `viewer.loadStructureFromUrl` see https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.ts#L116-L129

**Comment by LivC182** [comment]
Saw that function and I was trying to many complex things. I just put the pdb in the static/public folder and ran this command:
```
viewer.loadStructureFromUrl('./nsp6.pdb', format='pdb')
```
However, I fear that if I add too many pdb stuctures my website will load too slow. I will try to find a better way to import them, maybe dynamically based on requests.

**Comment by dsehnal** [comment]
Mol* can also load data from string:

```ts
const data = await plugin.builders.data.rawData({
    data: '' /* string or Uint8Array */,
    label: void 0 /* optional label */
});
const trajectory = await plugin.builders.structure.parseTrajectory(data, format);
await plugin.builders.structure.hierarchy.applyPreset(trajectory, 'default');
```

**Comment by LivC182** [comment]
@dsehnal thank you very much very useful for me at least. One more question is there any way to load .grd files ? the formats that I fould molstar supports are: 'mmcif', 'cifCore', pdb',gro', 3dg', 'mol', 'mol2'

**Comment by dsehnal** [comment]
I assume you mean this http://peterbird.name/guide/grd_format.htm

The formats you listed are just for trajectories. It also supports map/dsn6/cube/cif for volumetric data. So you can convert your grd files into one of these. Or take say the cube parser and write the grd parser based on that. I guess support for different file formats is something we could streamline a bit more. I will think about a nice way to do that.

Also, the ``Viewer`` object supports shortcuts for only small subset of Mol* functionality. A good deal of functionality is accessed thru ``plugin.builders`` and ``plugin.managers`` objects (I.e. ``const v = Viewer(...); v.plugin...``, but you can create the ``plugin`` object without using the basic Viewer wrapper) and a good deal more using low level "transforms". You can see for example https://github.com/molstar/molstar/blob/master/src/examples/basic-wrapper/index.ts.

**Comment by arose** [comment]
Closing this as the original question was answered. @LivC182, if you are interested in support for the grd format (either to implement it yourself or as a feature request) please open e new isse. Thank you.

**Comment by xuelianl** [comment]
Hi, I'm new to Mol*, and I want to know is there any way that I load multiple local files in one view? 
Your prompt reply would be greatly appreciated!
