### ISSUE TITLE
Add TraceOnly option for Structure Superposition

### ISSUE THREAD

**Issue by dsehnal** [molstar/molstar#371]
Add a new param `traceOnly` to [``StructureSuperpositionParams``](https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/structure/superposition.tsx#L50) that is `true` by default and would affect "Chain" and "Uniprot" superposition options.

@JonStargaryen would you be able to help with this?

**Comment by JonStargaryen** [comment]
I've opened a PR: #373

**Comment by dsehnal** [comment]
Closed by #373, thanks @JonStargaryen
