### ISSUE TITLE
Invalid CSS selectors in mol-plugin-ui/skin/base/components/misc.scss

### ISSUE THREAD

**Issue by azangru** [molstar/molstar#376]
There are a couple of invalid CSS selectors on lines 604-610 of [mol-plugin-ui/skin/base/components/misc.scss](https://github.com/molstar/molstar/blob/430cc8325967b611f3fe879dc0653f8caeb38dfc/src/mol-plugin-ui/skin/base/components/misc.scss#L604-L611)

```
    .msp-slider {
        > div:first-child() {
            right: 42px;
        }
        > div:last-child() {
            width: 30px;
        }
    }
```

`first-child` and `last-child` should not have parentheses.

**Comment by arose** [comment]
thanks @azangru
