### ISSUE TITLE
Gaps in protein caused by deformations

### ISSUE THREAD

**Issue by brianjimenez** [molstar/molstar#38]
After applying some deformation using Normal Mode Analysis to a protein, geometry is not canonical anymore and when trying to visualize the molecule with Pymol or Chimera, lines and ribbons usually contain dashed lines for representing that effect. Is there any way to have such effect in Mol*? I see the same behavior coming from NGLViewer.
Thanks a lot for your help and time!

**Comment by arose** [comment]
Hi @brianjimenez, do you have an example file? Mol* tries to find gaps/chains breaks and display them as dashed lines between the stem resodues.

**Comment by brianjimenez** [comment]
For example the one attached. There is an extreme deformation of the tip of the protein partner and in the peptide too.
[top_1.pdb.zip](https://github.com/molstar/molstar/files/4623317/top_1.pdb.zip)

**Comment by arose** [comment]
We currently don't show the dashed-lines when the residue numbers are consecutive, but we could, see below. Would that be what you want? Third option would be to still draw the cartoon.

![image](https://user-images.githubusercontent.com/272250/81854670-2374dd00-9513-11ea-8e05-2f39d440d320.png)

**Comment by arose** [comment]
Option 3: Draw cartoon if polymer bond is <5A. Might be good to show breaks with dashed-lines instead.

![image](https://user-images.githubusercontent.com/272250/81855345-15738c00-9514-11ea-9416-afb4ed81298c.png)

**Comment by brianjimenez** [comment]
Any of the proposed options is amazing and would work. Could you please share a couple of snippets how to accomplish it? Thanks again for your help and quick answers, beautiful piece of software btw.

**Comment by arose** [comment]
Both option require changes to the core. I added the first option of showing the gaps, see https://github.com/molstar/molstar/commit/1f60d887a86590e5bcbb3cd01d6054b106c99209.

To draw the cartoon if the backbone atoms are further apart one would need to change the 3 in https://github.com/molstar/molstar/blob/1f60d887a86590e5bcbb3cd01d6054b106c99209/src/mol-model/structure/model/properties/utils/atomic-ranges.ts#L37 to something higher. I you export your structure with only CA the cartoon would likely be drawn as the distance threshold for coarse structures is 10A.
