### ISSUE TITLE
Changing TransformStructureConformation programmatically

### ISSUE THREAD

**Issue by sswang33** [molstar/molstar#384]
Hi,
I want to reproduce the action like "Apply Transform Conformation" by javascript. For example, when user clicks the button, the ligand (or polymer) can translate x 10 units. I try to mimic the code such as "transform function" from superposition.ts. However, I got "No suitable parent found" error when I plugin.runTask(plugin.state.data.updateTree(b)).

I  track the error code to mol-state/state.ts#876, 
if parentCell set to ctx.cells.get(current.transform.parent), the response is what i want.
However, transform.transformer.definition.from.length is 1 actually. so i got the error. 

Is there any example to do this?

Many Thanks,

![image](https://user-images.githubusercontent.com/95211835/155651432-7992e420-afb9-4d22-b0b7-053011017265.png)

**Comment by dsehnal** [comment]
Hi,

something along the lines of this should do the trick:

```ts
const ligand = await tryCreateComponentStatic(...);
const transform = await plugin.build().to(ligand!).apply(TransformConformation, ....).commit();
await addRepresentation(transform);
```

You can save reference to ``transform`` somewhere you can access it in the button event and do:

```ts
await plugin.build().to(transform).update(newParams).commit();
```

**Comment by sswang33** [comment]
Hi, 

Thank you for the information
I try to add the code "plugin.build().to..." at line 159-161
But I still get the same error info "No suitable parent found for ..."
Did the "StateTransforms.Model.TransformStructureConformation" put in the right way ?

![image](https://user-images.githubusercontent.com/95211835/155828655-bb78b40b-dd3f-4874-8227-d1de78cacb4a.png)

**Comment by sswang33** [comment]
Thank you Thank you very much. I update my comment. Sorry for that ugly code format...

**Comment by sswang33** [comment]
Thanks for your kind reply. The plugin object I made is wrong. 
After following the guideline, the problems are solved.
Thank you for building the wonderful project.  

[Right way to import plugin]
```typescript
    const plugin = new PluginContext(this.MySpec);
    await plugin.init();
    this.plugin = await plugin;
    const canvas = <HTMLCanvasElement> document.getElementById('molstar-canvas');
    const parent = <HTMLDivElement> document.getElementById('molstar-parent');
    if (!plugin.initViewer(canvas, parent)) {
        console.error('Failed to init Mol*');
        return;
    }
    await this.loadTestTransform();
```
[Wrong way to import plugin]
```typescript
    Viewer.create('molstar-parent', {
      layoutIsExpanded: false,
      layoutShowControls: false,
      layoutShowRemoteState: false,
      layoutShowSequence: false,
      layoutShowLog: false,
      layoutShowLeftPanel: true,
      GeneralPickScale: false,
      viewportShowExpand: false,
      viewportShowSelectionMode: false,
      viewportShowAnimation: false,
      pdbProvider: 'rcsb',
      emdbProvider: 'rcsb',
    }).then(async viewer => {
      this.plugin = viewer.plugin;     // <-- wrong here
      await this.loadTestTransform();
    })
```
