### ISSUE TITLE
Use only auth_asym_id when parsing mmCIF

### ISSUE THREAD

**Issue by AlessioDelConte** [molstar/molstar#387]
Hello,
is it possibile to use only the auth_asym_id when parsing mmCIFs? I have some files that have the label_asym_id as '.' and when parsed by Molstar there are some issues in the visualization. 
Thanks!

**Comment by dsehnal** [comment]
Hi, 

would it be possible for you to normalize the files before opening them? 

In theory, you could use the mmCIF parsed in Mol* to read the raw file, copy the auth_ column to the label one and then write it back as a string before loading.

**Comment by arose** [comment]
Could you share an example file?

**Comment by AlessioDelConte** [comment]
Hi,
the file is the output of a molecular dynamics simulation that I loaded into pymol in order to assign the chain names to the various chains, but apparently it do that only on the auth_asym_id and does not report it on the label_asym_id.
This is the file that I have (only first model)

[test.zip](https://github.com/molstar/molstar/files/8169702/test.zip)

**Comment by arose** [comment]
Hey @AlessioDelConte, thanks for the example. We added support for such files with #389.
