### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading 'entry')` when load local files using `viewer.loadStructureFromUrl()` 

### ISSUE THREAD

**Issue by xuelianl** [molstar/molstar#388]
Hi, 
I'm using Mol* to show my local files.
Now, I can load one file by `viewer.loadStructureFromUrl('http://xx:xx/structure/xx/xx', format='pdb')`, but when I add another line to load the second structure, it finally load only one structure.
So I want to know is there any way that I can load multiple local files in one view through passing url or other replaceable ways on the backend? 

Besides, how to rename the model name rather than url on the backend?
Your prompt reply would be greatly appreciated!

**Comment by xuelianl** [comment]
For the first question, it's not the problem of `viewer.loadStructureFromUrl()`, it's the second url I provided it.
When I load my local files, some will come out `TypeError: Cannot read properties of undefined (reading 'entry')`. 
So the first question turns to "how can I avoid the error"?

**Comment by xuelianl** [comment]
For the first question, it turns out that it's my fault, I'm giving the wrong format for the second structure url.
For the second question, I want to know how to change the model name in the state tree on the backend?
![Screenshot from 2022-03-04 09-34-52](https://user-images.githubusercontent.com/54713559/156682390-2677b3a6-7edc-4a68-8c74-9ac98c84228e.png)

**Comment by dsehnal** [comment]
On the backend you can't using the PDB format (with mmCIF you could assign entry.id category). On the front end you would have to built the transform that creates the state tree by hand and assigns the names as you need to.

**Comment by xuelianl** [comment]
I see. Thanks a lot for your patient answer!
