### ISSUE TITLE
Merging structures on already loaded structures

### ISSUE THREAD

**Issue by hadim** [molstar/molstar#397]
Following https://github.com/molstar/molstar/issues/395, I am trying to allow merging multiple structures that are already loaded within the hierarchy (versus structures loaded from URLs during the start of the viewer).

I have a couple of questions related to the code used in `docking-viewer`.

- It seems like this line `this.plugin.managers.structure.hierarchy.updateCurrent(this.plugin.managers.structure.hierarchy.current.structures, 'remove');` is supposed to remove the current structures (and then replace it by the merge). But removing it does not change anything and the original structures are still here.
- Also I noticed that if I manually removed the original structures from the hierarchy the new "Merged Structures" is also removed. I think they are a kind of dependency between each other. But I am not sure.
- The merging code is using `ref` as input for the merge, but I can't find it within the `this.plugin.managers.structure.hierarchy.current.structures` object. I would like to use those refs to perform a merge on-demand.
- The ligands are loaded from an SDF file and contain multiple ligands (loaded as different model on which I can iterate on using "Next Model"). But I can't see those list of models into the "Merged Structures" structure.

I am working on an internal viewer to add those new features, but I would be happy to contribute upstream to such features if this is of interest for molstar.

**Comment by hadim** [comment]
Here is the code I have so far. It's working well and seems to generate the same kind of merge as loading directly from URLs:

```ts
    async mergeCurrentStructures() {

        // Collect references from `structure-properties` objects.
        const structures = Array.from(this.plugin.managers.structure.hierarchy.current.refs).map(([key, value]) => {
            if (value.kind === 'structure-properties') {
                return { ref: key };
            } else {
                return null;
            }
        }).filter(v => v !== null) as { ref: string }[];

        // remove current structuresfrom hierarchy as they will be merged
        // TODO only works with using loadStructuresFromUrlsAndMerge once
        //      need some more API metho to work with the hierarchy
        this.plugin.managers.structure.hierarchy.updateCurrent(this.plugin.managers.structure.hierarchy.current.structures, 'remove');

        const dependsOn = structures.map(({ ref }) => ref);
        const data = this.plugin.state.data.build().toRoot().apply(MergeStructures, { structures }, { dependsOn });
        const structure = await data.commit();
        const structureProperties = await this.plugin.builders.structure.insertStructureProperties(structure);
        this.plugin.behaviors.canvas3d.initialized.subscribe(async v => {
            await this.plugin.builders.structure.representation.applyPreset(structureProperties || structure, ViewerAutoPreset);
        });
    }
```

**Comment by hadim** [comment]
Thanks, @dsehnal, that's helpful, and I'll try it soon.

Closing here but feel free to re-open.

**Comment by arose** [comment]
@hadim See also the action below as an example for an action that loads two files and combines them into a new node with dependents in the state tree. 

https://github.com/molstar/molstar/blob/6e5c20f442af01a85aff27e2bad956280532630d/src/mol-plugin-state/actions/structure.ts#L318-L439
