### ISSUE TITLE
Performances with huge structures

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#408]
Hi,
I'm using a no-plugin configuration for my integration. 
I'm having some performance issues on canvas update when huge structures like 3J3Q are loaded. The issue is only on my integration, the online app works very well using the same structure. 

Basically I generate the structure using ```Structure.ofModel()``` function, and then use the code below to build the representation. 
```
const cartoonRepresentation = CartoonRepresentationProvider.factory(this.reprCtx, CartoonRepresentationProvider.getParams);
    cartoonRepresentation.setTheme({
      color: this.reprCtx.colorThemeRegistry.create('element-symbol', { structure }),
      size: this.reprCtx.sizeThemeRegistry.create('uniform', { structure })
    })
    await cartoonRepresentation.createOrUpdate({ ...CartoonRepresentationProvider.defaultValues, quality: 'auto' }, structure).run();
    this.canvas3d.add(cartoonRepresentation);
```

Have you any idea on what is going on?

**Comment by arose** [comment]
Looks OK to me. Is anything sticking out when you do a Performance measurement with the Chrome Dev Tools?

**Comment by giagitom** [comment]
Ohh.. I have found the problem. It was the molstar debug mode on. Didn't expected it affects performances so much.

**Comment by arose** [comment]
Yeah the debug mode slows things down quite a bit because it does WebGL state checks which require synchronous communication with the GPU.
