### ISSUE TITLE
Focus on a given representation

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#410]
Greetings,

How can I focus programmatically to a given representation (or structure)?
Note that I have access to the state object ref.

**Comment by arose** [comment]
You can use `plugin.managers.structure.focus.setFromLoci`

**Comment by ptourlas** [comment]
Greetings,

I have some additional questions regarding this issue.
What I essentially want to do is to get the `loci` of a given structure or representation and pass it to:
`plugin.managers.structure.focus.setFromLoci()` and `plugin.managers.camera.focusLoci()`

* The `plugin.managers.structure.focus.setFromLoci()` only adds a ball-and-stick representation without affecting the camera position?
* These `loci` exist for structures only or for representations as well?
* How can I get its corresponding `loci` of a structure from its corresponding `StateObjectSelector` ?

**Comment by dsehnal** [comment]
Find the parent structure of that representation you must and convert it to the loci you seek ( :D ).

You can do this with `.selectQ` on the `plugin.state.data`.
