### ISSUE TITLE
from selection to residu list

### ISSUE THREAD

**Issue by fmareuil** [molstar/molstar#412]
Hello,

First of all, I would like to thank you for your amazing work!
I'm currently working on an integration of molstar and I would like to know the best way to obtain the list of atoms/residus by entity and by structure selected from the user interface. I have searched some functions/properties on plugin.managers.selection or others but without success.

Thank you for your help.
Best Regards

**Comment by dsehnal** [comment]
Hi,

you should be able to get the selection from ``plugin.managers.selection`` or ``plugin.behaviors.interaction`` and then call ``StructureSelection.unionStructure()``. On the result you can use ``Structure.eachAtomicHierarchyElement`` together with ``StructureProperties`` to access whatever you need.

**Comment by dsehnal** [comment]
Try something like this to start with:

```ts
const selections = Array.from(plugin.managers.structure.selection.entries.values());
const chains = [];
for (const { structure } of selections) {
    if (!structure) continue;

    Structure.eachAtomicHierarchyElement(s.structure, {
        chain: loc => {
            chains.push(StructureProperties.chain.auth_asym_id(loc));
        },
        residue: loc => {
            StructureProperties.residue.label_seq_id(loc);
        }
    });
}
```

**Comment by fmareuil** [comment]
Hi,

Thank you very much for your help. It was exactly what I needed !!

Best Regards,
