### ISSUE TITLE
No Secondary Structure Shown for AlphaFold Files

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#425]
Broke between 3.5.0 and 3.6.0 but I didn't see any obvious change that can explain this. Previously, it helped to remove the `database_2` category from the source file but not this time. Files from ModelArchive/SWISS-MODEL are fine.

![AF-Q8W3K0-F1](https://user-images.githubusercontent.com/9744615/164568219-63412aca-7060-4878-a3d6-47d02a8ee9fe.png)

**Comment by JonStargaryen** [comment]
Getting rid of `struct_conf` helps, as this triggers the fallback to computing SSEs on-the-fly. Maybe related to the case insensitive handling of mmCIF enumeration fields. I'll try to have another look tomorrow.

**Comment by arose** [comment]
> Maybe related to the case insensitive handling of mmCIF enumeration fields.

Exactly that, yes.

**Comment by JonStargaryen** [comment]
Thanks for the fix!
