### ISSUE TITLE
What is the correct way to explode a structure programmatically?

### ISSUE THREAD

**Issue by Bartvelp** [molstar/molstar#426]
Hi,

So I am loading a PDB file sucessfully and want to try to recreate certain function packaged in the normal UI of Molstar myself by manipulating the PluginUIContext. For example, I want to explode the structure.
To me it is not clear what the intended way to do this is. I understand Molstar implements "plugins" that can manipulate the state of the viewer.
As far as I can understand, there are 2 ways to explode a structure, the most obvious to me is to do it like how the packaged react UI does it. This is by "applying" a plugin action, specifically the `StateTransforms.Representation.ExplodeStructureRepresentation3D.toAction()`
action.

I (try to) do this in the following manner:

```typescript
  async explodeStructure () {
    console.log("exploding structure")
    const action = StateTransforms.Representation.ExplodeStructureRepresentation3D.toAction()
    const structureRef = this.plugin.managers.structure.hierarchy.selection.structures[0]
    const ref = structureRef.cell.transform.ref
    console.log('StateTransform.RootRef', StateTransform.RootRef)
    await PluginCommands.State.ApplyAction(this.plugin, {
      state: this.plugin.state.data,
      action: action.create({t: 0.2}),
      ref: StateTransform.RootRef
    })
  }
```

As you can see I need to pass a "ref", as far as I can understand this is used to update the react ui node after the structure is exploded, but I don't really care whether that UI is updated, since I want to do it programmatically. Omitting the ref parameter, passing the root ref, or passing the structure cell transform ref all raise the same error:
```log
Error: No suitable parent found for 'eQljTOLgTDxxgKpG-3XpcQ'
    at [molstar/src/mol-state/state.ts:880:1]()
    at step ([molstar/node_modules/tslib/tslib.es6.js:102:1]())
    at Object.next ([molstar/node_modules/tslib/tslib.es6.js:83:1]())
    at [molstar/node_modules/tslib/tslib.es6.js:76:1]()
    at new Promise (<anonymous>)
    at __awaiter ([molstar/node_modules/tslib/tslib.es6.js:72:1]())
    at updateNode (:255724:59)
    at [molstar/src/mol-state/state.ts:814:1]()
    at step ([/molstar/node_modules/tslib/tslib.es6.js:102:1]())
    at Object.next ([http://localhost:3000/static/js/bundle.js:319928:14]()) {stack: 'Error: No suitable parent found for 'eQljTOLg…localhost:3000[/static/js/bundle.js:319928:14]())', message: 'No suitable parent found for 'eQljTOLgTDxxgKpG-3XpcQ''}
```

So this approach seems a bit of dead-end to me, since I cannot omit the ref parameter, and don't know how to set it.

The other way would be to call 
```typescript
export function explodeStructure(structure: Structure, unitTransforms: StructureUnitTransforms, t: number, sphere: Sphere3D) {
```
directly, but unfortunatly I don't know how to get a `Structure` object from the PluginContext. I think I tried this a few days ago but lost the code on how I got this `Structure` object. Then it did not error, but also did not actually update the representation to be exploded, so I discarded that way. Now I only seem to find the `StructureRef`. 

What would be the correct way to explode the structure, are these `PluginCommands.State.ApplyAction` the correct way to go about it? And are Github issues the correct way to ask for support?

Thank you for your time

**Comment by dsehnal** [comment]
Hi,

what you want is to run the ``AnimateUnitsExplode`` animation:

```ts
await plugin.managers.animation.play(AnimateUnitsExplode, { durationInMs: 1000 });
// ...
await plugin.managers.animation.stop();
```

and you should be set.

**Comment by Bartvelp** [comment]
Thanks so much for the swift response!
I am going to be totally honest, all these factories to generate a selection of a transformer are very difficult for me to comprehend, and I am not sure if I now understand more or less than when I started looking into this.

I adapted the implementation you linked to my use-case, so for future reference:
```typescript
  async explodeStructure (explosionDistance: number) {
    console.log("exploding structure")
    const state = this.plugin.state.data
    // Setup
    const reprs = state.select(StateSelection.Generators.ofType(PluginStateObject.Molecule.Structure.Representation3D));

    const update = state.build();
    let hasChanged = false;
    for (const r of reprs) {
        const explodes = state.select(
          StateSelection.Generators.ofTransformer(StateTransforms.Representation.ExplodeStructureRepresentation3D, r.transform.ref)
          )
        if (explodes.length > 0) continue;

        hasChanged = true;
        update.to(r.transform.ref)
            .apply(StateTransforms.Representation.ExplodeStructureRepresentation3D, { t: 0 }, { tags: 'animate-units-explode' });
    }

    if (hasChanged) await update.commit({ doNotUpdateCurrent: true })

    // Animate
    const anims = state.select(StateSelection.Generators.ofTransformer(StateTransforms.Representation.ExplodeStructureRepresentation3D));

    const newUpdate = state.build();
    for (const m of anims) {
      newUpdate.to(m).update({ t: explosionDistance });
    }
    await PluginCommands.State.Update(this.plugin, { state, tree: newUpdate, options: { doNotLogTiming: true } })
  }
```
