### ISSUE TITLE
has the default representation changed?

### ISSUE THREAD

**Issue by gustavo-salazar** [molstar/molstar#428]
Hey there,

I have updated the version of molstar from`3.5.0` into 3`3.6.0` and the same code I'm using to create a viewer is now on what I believe is the `Putty` representation, when it use to be `cartoon` by default, is this an expected change, or do I need something different in this version.
The code I'm using to create the viewer hasn't change the only significant change besides the upgrade of the molstar version is that I'm also upgrading to react 18.

**Comment by arose** [comment]
This is a bug, see #425. Got fixed already. We will release a new version in the coming days.

**Comment by gustavo-salazar** [comment]
Brilliant! Thanks so much!
