### ISSUE TITLE
Best way to reuse same PluginUIContext?

### ISSUE THREAD

**Issue by lazear** [molstar/molstar#429]
Hi,

I'm trying to create a Vue.js component based around the [Basic-Wrapper example](https://github.com/molstar/molstar/blob/master/src/examples/basic-wrapper/index.ts).

I can successfully load a single model, and apply custom theming/labeling - however, I would like to be able to display multiple protein structures (not simultaneously though) in the component. 

When I try a naive approach for this (creating a reactive binding for a PDB/alphafold URL), it reloads the existing structure until I try to `load()` a second time. Is there something I'm missing here?

**Comment by dsehnal** [comment]
I would need some more info (Eg code snippets) about how your code looks like to help you properly. But you might want to try calling await plug-in.clear() to make sure next time you use it it's empty.

**Comment by PENEKhun** [comment]
@lazear  Did you make it?
