### ISSUE TITLE
Get state transform for structure

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#431]
Hello,

I was wondering what the best way to programatically get the `StateObjectCell` or `StateTransform.Ref` for a given `Structure` (From 'mol-model') is?

I have retrieved the structure from from the current structure selection (`plugin.managers.structure.selection`) and would like to get the state object / transform corresponding to its creation (`ms-plugin.structure-from-model`).

Thank you in advance!

**Comment by dsehnal** [comment]
Have a look at plugin.state.data.selectQ function. There are examples across the codebase of how to use it.

**Comment by jpattle** [comment]
Thanks David,

I've got part of the way there using the following:

```javascript
// returns all StructureFromModel transforms
const structureStateTransforms = plugin.state.data
    .selectQ(q => q
        .ofTransformer(StructureFromModel)
        .ofType(PluginStateObject.Molecule.Structure))

// This returns nothing, there are no matches??
const matchingTransform = structureStateTransforms.find(transform => transform.obj?.data === mySelectedStructure)
```

However the second part (finding a matching transform) does not work, it seems the transform's data is not reference equal to the structure I retrieved from `plugin.managers.structure.selection`.

What's the best way to check for equality so I can determine which transform produced the structure?

**Comment by jpattle** [comment]
We're trying to access a custom transformer that is a child of the `StructureFromModel` transformer responsible for the structure in question

**Comment by jpattle** [comment]
Okay, I've managed to get the desired behaviour. Looks like you can use the `transformHash` that exists on the `Structure` object to compare with the `Structure` of a given component. This works as follows:

```javascript
// Gets all the StructureComponent transforms in state
const structureComponentStateTransforms = plugin.state.data
    .selectQ(q => q
        .ofTransformer(StructureComponent)
        .ofType(PluginStateObject.Model.Structure))

// This finds the first component that matches the structure you have selected
//    if you have multiple components built from the same structure there will be multiple matching transforms
// From here you can access the rest of the tree related to that structure
const firstMatchingTransform = structureComponentStateTransforms
    .find(transform => transform.obj?.data.transformHash === mySelectedStructure.transformHash)

if (!firstMatchingTransform)
{
    return 
}

// You can get to the full parent structure transform by using selectQ again
const structureFromModel = plugin.state.data.selectQ(q =>
    q
      .byRef(firstMatchingTransform.transform.ref)
      .ancestorWithTransformer(StructureFromModel)
      .ofType(PluginStateObject.Molecule.Structure)
      .first()
  );
```

Please let me know if this is not the intended use for the `Structure` property `transformHash`. Otherwise I'm happy for you to close this question :)

**Comment by arose** [comment]
Still not 100% sure what you are after. Maybe `plugin.helpers.substructureParent.get` can help. It returns the root node of given structure if existing and takes decorators into account.

**Comment by jpattle** [comment]
Hi Alexander, that looks like it might do what I want but unfortunately it always seems to return undefined. For example:

```
// Get the first structure in the current selection
const selection = plugin.managers.structure.selection
const { structure } = Array.from(selection.entries.values())

// always seems to return undefined, no matter what I select in the view
const substructureParent = plugin.helpers.substructureParent.get(structure)
```

The type definition of that function looks correct; it returns a StateObjectCell for the parent structure, but I'm not sure what sort of structure I have to pass in to get it to work.

**Comment by jpattle** [comment]
Okay so looks like you can get `substructureParent.get` to return you the state cell if you use the structure from the loci instead of the structure from selection:

```
// Get the first loci in the current selection
const selection = plugin.managers.structure.selection
const { selected } = Array.from(selection.entries.values())[0]

// returns the right state object cell
const substructureParent = plugin.helpers.substructureParent.get(selected.structure)
```

Thank you both for your help
