### ISSUE TITLE
Execute Specific file on page load

### ISSUE THREAD

**Issue by xx7Ahmed7xx** [molstar/molstar#432]
Using your mol viewer, How can someone make it automatically render a given .pdb file once the page is requested from server?
Which part of js (or whatever) to edit to dynamically assign it a file?

**Comment by dsehnal** [comment]
This example might be a good start for you https://github.com/molstar/molstar/blob/master/src/apps/viewer/embedded.html

**Comment by xx7Ahmed7xx** [comment]
> This example might be a good start for you https://github.com/molstar/molstar/blob/master/src/apps/viewer/embedded.html

Thank you, But i can't quite understand how exactly to use this page embedded, I can't see an example pdb file that it loads, neither the way to use it?

**Comment by dsehnal** [comment]
You call this function https://github.com/molstar/molstar/blob/master/src/apps/viewer/app.ts#L195 with the URL where your file is stored (the URL needs to support CORS if it's not the same domain).

**Comment by xx7Ahmed7xx** [comment]
So i call it from the html page in the javascript section, Can you demonstrate with example please?

**Comment by dsehnal** [comment]
I don't think I can in a way that would be meaningful to you, sorry.

**Comment by xx7Ahmed7xx** [comment]
Okay no problem, From what I see it is a typescript file (angular?) so I just can't get it, How can I use it without angular ?
Or if you can tag someone who knows...

**Comment by xx7Ahmed7xx** [comment]
Up ?

**Comment by xx7Ahmed7xx** [comment]
Okay solved it by myself, You need to call loadStructureFromUrl(string url) function in your javascript file, Using a live server or a full backend server for CORS, then it will show the file on loading the page ;)
example:
```
<body>
        <div id="app"></div>
        <script type="text/javascript" src="./molstar.js"></script>
        <script type="text/javascript">
            molstar.Viewer.create('app', {
                layoutIsExpanded: true,
                layoutShowControls: true,
                layoutShowRemoteState: false,
                layoutShowSequence: true,
                layoutShowLog: false,
                layoutShowLeftPanel: false,

                viewportShowExpand: false,
                viewportShowSelectionMode: false,
                viewportShowAnimation: false,

                pdbProvider: 'rcsb',
                emdbProvider: 'rcsb',
            }).then(viewer => {
                viewer.loadStructureFromUrl('./3bmp.pdb', format='pdb')
            });
    </script>
</body>
```
This satisfies best my need, and incase anyone else needs it, It is there! (don't forget all needed files for it to work)
Enjoy.
