### ISSUE TITLE
Out of sync state StructureRef.components 

### ISSUE THREAD

**Issue by Bartvelp** [molstar/molstar#438]
Hi,

I am trying to use the `StructureComponentManager` to manage my Structures and Representations, however, when loading 2 models, the Manager reports there are no representations associated with my second StructureRef, even though the there is, and the state has them. I am a bit confused as to how this is posibble, and if this is expected behaviour, specifically I am getting the following results with the following state tree:
![image](https://user-images.githubusercontent.com/13890340/168096511-e0ca6e8c-7dc4-4a83-a927-cf9422bbb9dc.png)

```js
// Directly from the state (correct result):
([...this.plugin.managers.structure.hierarchy.dataState.cells.values()]
     .map(e => e.obj.label)
     .filter(l => l === 'Cartoon').length) === 2

// Using the StructureComponentManager
([...this.plugin.managers.structure.hierarchy.current.structures]
        .flatMap(structure => structure.components)
        .flatMap(components => components.representations).length) === 1 // This is incorrect!

```

To be more clear:
```js
this.plugin.managers.structure.hierarchy.current.structures[1].components == []
```
While it is not supposed to be.

After I update the state using `await this.plugin.state.data.build().commit()`, the `StructureComponentManager` starts reporting the correct components again:
```js
[...this.plugin.managers.structure.hierarchy.current.structures]
        .flatMap(structure => structure.components)
        .flatMap(components => components.representations).length === 2 // Correct again
```

Representations are added like this:
```js
    async addRepresentation(typeName: representationType = 'gaussian-surface') {
        await this.plugin.dataTransaction(async () => {
            const structureManager = this.plugin.managers.structure
            for (const structure of this.structures) {
                await structureManager.component.addRepresentation(structure.components, typeName)
            }
        })
    }
```

What to do? Is this a bug or just a false assumption on my side?

**Comment by dsehnal** [comment]
Hi, the manager is not synced synchronously (as it is mainly meant to show the state in the UI), so you need to await a timeout before using it like this after the transforms have been applied.

**Comment by arose** [comment]
@dsehnal how would you ensure the manager is synced?

**Comment by dsehnal** [comment]
> @dsehnal how would you ensure the manager is synced?

That should already be happening. But the state tree update needs to finish before that could happen.

**Comment by Bartvelp** [comment]
> > @dsehnal how would you ensure the manager is synced?
> 
> That should already be happening. But the state tree update needs to finish before that could happen.

As you can see it also occurs when a check it in a 5000 ms timeout, so by then any process should be done. Should I have finished the update manually somehow?

**Comment by dsehnal** [comment]
That happens automatically https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/hierarchy.ts#L64

> As you can see it also occurs when a check it in a 5000 ms timeout, so by then any process should be done. Should I have finished the update manually somehow?

Well, awaiting the state updates that happen before that and doing ``await new Promise(res => requestAnimationFrame(res))`` should be enough to get the correct state in the the component manager.
