### ISSUE TITLE
How to draw a line programmtically?

### ISSUE THREAD

**Issue by HongjianLi** [molstar/molstar#440]
I'm new to Mol*. I read through the molstar viewer documentation, but could not find a way to programmatically draw a line between two points.

By using the example located at molstar-3.8.1/src/apps/viewer or docking-viewer, I managed to load the PDB structure 5L2T, and then wanted to draw a line between two points whose coordinates are (12, 28, -18) and (32, 48, 2).

My code looks like the following:

    molstar.Viewer.create('app', {}).then(viewer => {
        viewer.loadPdb('5L2T'); // Load my desired structure, which works fine.
        viewer.drawLine([12, 28, -18], [32, 48, 2]); // Is there an API like drawLine() which accepts the coordinates of two points?
    });

**Comment by arose** [comment]
There is no convenient api for that in the viewer app, you will need build your own viewer app and use a ShapeRepresentation (search the code for examples) to draw lines.
