### ISSUE TITLE
Proper way to update a representation

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#441]
Hi,
in my implementation I am using this to build a representation:

```ts
    const cartoonRepresentation = CartoonRepresentationProvider.factory(this.reprCtx, CartoonRepresentationProvider.getParams);
    cartoonRepresentation.setTheme({
      color: this.reprCtx.colorThemeRegistry.create('element-symbol', { structure }),
      size: this.reprCtx.sizeThemeRegistry.create('uniform', { structure })
    })
    await cartoonRepresentation.createOrUpdate({ ...CartoonRepresentationProvider.defaultValues, quality: 'auto' }, structure).run();
    this.canvas3d.add(cartoonRepresentation);
```
Which is the proper way to change the **structure** and update the representation in the canvas accordingly?  Should I make a new representaiton from scratch and remove the other or there is a better way?

**Comment by arose** [comment]
if the new and old structure share units then reuse the representation (some cpu/gpu resources will get reused), otherwise just create a new one

**Comment by giagitom** [comment]
Thanks!
