### ISSUE TITLE
How to change the style of amino acid indices in sequence view

### ISSUE THREAD

**Issue by xptree** [molstar/molstar#442]
Hi, thank you so much for the great macromolecular library!!!

I wonder if there is a way to configure the style of amino acid indices? For example, making the amino acid indices occur every five amino acids (like PyMOL, see below) instead of every 10 amino acids.

PyMOL:
<img width="158" alt="image" src="https://user-images.githubusercontent.com/3853009/169476775-a64f3ce7-4bef-49ca-a168-922c6c5c6ee4.png">

molstar:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/3853009/169477222-cdd9ceca-78a2-45dd-9cff-f5404be09bd4.png">

**Comment by arose** [comment]
Hi, thanks, glad you like it.

You can't change it in the provided viewer app but if you build your own version you can. The `Sequence` react component has a prop `sequenceNumberPeriod`, see https://github.com/molstar/molstar/blob/7692b59c7c63cbd8b00e23c24c52388ce496bcae/src/mol-plugin-ui/sequence/sequence.tsx.
