### ISSUE TITLE
Chain-level operations

### ISSUE THREAD

**Issue by cycle20** [molstar/molstar#443]
Hello!
How can I copy, delete and transform chains programmatically?
Should I do it after trajectory load? (our extension downloading mmCIF data)

```typescript
    const trajectory = await builders.structure.parseTrajectory(data, 'mmcif');
    await applyTransformations(pdbtmDescriptor, trajectory);
```
```pdbtmDescriptor``` contains our custom operations that transform the PDB coordinates at level of atoms.
I am looking for functions to access and modifies atoms of specified chains with no low level array operations.

```typescript
        let atomicConformationX = trajectory.data.representative.atomicConformation.x;
        let atomicConformationY = trajectory.data.representative.atomicConformation.y;
        let atomicConformationZ = trajectory.data.representative.atomicConformation.z;

        for (let i = 0; i < atomicConformationX.length; i++) {
            let coords = {
                x: atomicConformationX[i],
                y: atomicConformationY[i],
                z: atomicConformationZ[i]
            };
            coords = applyTransformationMatrix(coords, tmatrix);
            new_x.push(coords.x);
            new_y.push(coords.y);
            new_z.push(coords.z);
        }
```

I had to overwrite the xyz arrays with new arrays to apply the changes on the structure.
Do you have any better or higher level way to achieve the same effect?
Thank you.

**Comment by arose** [comment]
Hi, you can use `TransformStructureConformation` state transform (https://github.com/molstar/molstar/blob/b3b469223798c338f86f00440b0564dd753f2810/src/mol-plugin-state/transforms/model.ts#L553-L614) to apply a matrix to a whole structure. If you need to apply a matrix to different parts you can first create structure selections (using the `StructureSelectionFromScript` or the `StructureSelectionFromExpression` state transform). Look at https://github.com/molstar/molstar/blob/6c5224f33e9de20fe9967a82536c269bacf29738/src/examples/basic-wrapper/superposition.ts#L86 for an example.

**Comment by cycle20** [comment]
Hi,
Thank you for the response. I could do transformation based on your guidance.
However I am still struggling with delete and copy.
Are there any built-in functions for them?
Thank you.

**Comment by dsehnal** [comment]
Ok, I think I understand better what you want now. You actually want to build a custom assembly and not apply "transforms by hand and delete/copy chains".

Please have a loot at 

- https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/helpers/root-structure.ts#L112
- https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/symmetry.ts#L21
- https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/model.ts#L522

What you want in the end is a custom version of the ``StructureFromModel `` transform. Something like this:

```ts
const MyTransformerFactory = StateTransformer.builderFactory('extension-name-transforms');
type MyAssemblyFromModel = typeof MyAssemblyFromModel 
const MyAssemblyFromModel = MyTransformerFactory({
    name: 'custom-assembly-from-model',
    display: { name: 'Assembly' },
    from: PluginStateObject.Molecule.Model,
    to: PluginStateObject.Molecule.Structure,
    params: {
        info: PD.Value<any>(undefined, { isHidden: true })
    }
})({
    apply({ a, params }, plugin: PluginContext) {
        return Task.create('Build Assembly', async ctx => {
            const structure = buildMyAssembly(a.data, params.info); // based on StructureSymmetry.buildAssembly && RootStructureDefinition.buildAssembly
            return new PluginStateObject.Molecule.Structure(structure, { label: 'My Assembly' });
        });
    },
});
```

---------------------

Alternatively, you might try build a ``Symmetry`` object based on your definition and use/modify the built in method to create the assembly for you.

**Comment by dsehnal** [comment]
> Probably I initialize `matrix.data` parameter in a wrong way.

The matrices are stored in a column major (j * 4 + i indexing) format (i is row, j is column index). The matrix code in Mol* is an adaptation of [this library](https://github.com/toji/gl-matrix/).

**Comment by cycle20** [comment]
You are right. We can interpret the result as a custom assembly - created on-the-fly somehow.

> Please have a loot at
> 
> * https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/helpers/root-structure.ts#L112
> * https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/symmetry.ts#L21
> * https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/model.ts#L522

Are these part of STRUCT_NCS_OPER implementation?
https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/struct_ncs_oper.html
I am not so familiar with PDBx/mmCIF.
What is the correspondent category of Symmetry in PDBx/mmCIF?
Do you have a list of (Mol* type, mmCIF category) pairs?

**Comment by dsehnal** [comment]
> Are these part of STRUCT_NCS_OPER implementation?

Part of it, yes. The most important part is probably this loop https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/symmetry.ts#L45

What you want is to create a mapping of `Map<chain_id, list of symmetry operator>`, create the selections for each chain and then build the units with the operators similar to the loop linked above.

**Comment by cycle20** [comment]
As I see ```STRUCT_NCS_OPER``` does not support deletion of an asymmetry.
I cannot see functions for it in [symmetry.ts](https://github.com/molstar/molstar/blob/v3.9.1/src/mol-model/structure/structure/symmetry.ts#L20)
Is there any symmetry operator that support chain deletion?
Or any other solution in the code base?

**Comment by dsehnal** [comment]
You can specify the chains and the copies you want to do yourself (if you write your own custom buildAssembly function which I thought you were prepared to do), you don't have to adhere to the abstractions to NCS. Also in general you specify which chains you want to copy and just omit the ones you don't want at all (which serves as deletion).

**Comment by cycle20** [comment]
> ... just omit the ones you don't want at all (which serves as deletion).

It does not work in cases when I need to delete already existing chains.
We delete chain A and B here: http://pdbtm.enzim.hu/?_=/showfile/2atk/xml
```xml
  <BIOMATRIX>
...
    <DELETE CHAINID="A"/>
    <DELETE CHAINID="B"/>
  </BIOMATRIX>
```

Before biomatrix operations in Mol*:
![image](https://user-images.githubusercontent.com/46718432/175293157-a57a2862-84b3-4ba8-a321-9e0036a97c70.png)

After biomatrix operations in our obsoleted viewer with membrane planes:
![image](https://user-images.githubusercontent.com/46718432/175293508-f0605082-0abe-4d10-9814-876d95152a1c.png)

**Comment by cycle20** [comment]
Can copies inherit the colors of the source asymmetry? (residue level)

**Comment by dsehnal** [comment]
But you are not deleting chains from a structure, you are (should be) creating a different structure from the `Model` which never has the chains at all.

Residue coloring should be the same as these are same residues on the same chains.

**Comment by cycle20** [comment]
> But you are not deleting chains from a structure, you are (should be) creating a different structure from the Model which never has the chains at all.

Should I exclude unneeded atoms from data before creating ```trajectory```?
https://git.enzim.ttk.hu/web/TmMolStar/src/issue_2_pdbe_collaboration/src/extensions/tmdet/behavior.ts#L222

Or do I need to perform it during model-creation? I cannot see how I can pass a filter/query expression to this function:
https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/builder/structure.ts#L59
(I could not find any use case of it in the code)

**Comment by cycle20** [comment]
> If you want custom coloring, you need to write a `Theme` which assigns the coloring. There is no "direct" way to say `residue[10].color = 'red'` in Mol*.

I already implemented custom coloring with no any `Theme`. I provide residue ids through an `Expression` and color the selected residues. Is there any drawbacks of it?
https://git.enzim.ttk.hu/web/TmMolStar/src/issue_2_pdbe_collaboration/src/extensions/tmdet/behavior.ts#L196
Why is `Theme` a better idea? What are its advantages?

**Comment by dsehnal** [comment]
> Is there any drawbacks of it?
> https://git.enzim.ttk.hu/web/TmMolStar/src/issue_2_pdbe_collaboration/src/extensions/tmdet/behavior.ts#L196
> Why is Theme a better idea? What are its advantages?

Yes, you are creating a new representation instead just coloring an existing one.

The theme will use a single representation and just change the color buffer.

**Comment by dsehnal** [comment]
As a side note, I don't fully understand why you are using a full clone of mol* instead of just importing the package through npm and writing your extension built on top of that.

**Comment by cycle20** [comment]
> As a side note, I don't fully understand why you are using a full clone of mol* instead of just importing the package through npm and writing your extension built on top of that.

I do not have any preliminary TS/npm experience. I am not a frontend developer. I guess there is no way to inject debug lines into the pre-built package of mol*, so I need to place them into the base code.
Furthermore we started to study the project on a whole clone. Building/debugging examples and so on. I could not find any Developer Guideline to implement our needs. I do not understand the whole architecture of Mol*, semantics and relations between its types, functions, modules and its inner state and all these low-level stuffs. I think this is the background.

**Comment by cycle20** [comment]
>  A model is basically a list of atoms and a structure is a selection of these atoms, which can also be instanced together with a matrix. So what you can do is only apply the transformations from your XML file on the chains that require them and never create instances of the "deleted" chains.

How can I select chains (their atoms) from a `model` to build my custom `structure`?
I do not understand this transform: https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/model.ts#L522
I cannot see any chain-specific filter here.

**Comment by dsehnal** [comment]
The part which builds the structure from model was also pointed out in that post with https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/helpers/root-structure.ts#L112

**Comment by cycle20** [comment]
Do you mean `Structure.ofModel`?
https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/helpers/root-structure.ts#L131
How can I specify which part of the model is needed?
(I mean which chains: I cannot see any selection expression here. It gets the whole model.)

**Comment by cycle20** [comment]
Thank you. I can exclude chains by hacking this function. It is just a hard-wired prototyping update, but it works.
...and thank you for your patience in guiding me through this problem :wink:
