### ISSUE TITLE
How to select a structure from a merged structure

### ISSUE THREAD

**Issue by xptree** [molstar/molstar#448]
Thank you so much for the great software!

Suppose I have a merged structure from several PDB files (by the following `MergeStructures` function). Is there a way to select a particular PDB structure by `StructureSelectionFromExpression`?

https://github.com/molstar/molstar/blob/e7ce693e509885fb74eacc0a5a50540762eeb58f/src/apps/docking-viewer/index.ts#L184-L214

**Comment by arose** [comment]
`MolScriptBuilder.struct.atomProperty.core.modelIndex` should help.
