### ISSUE TITLE
automatically/programmatically load measurements and labels

### ISSUE THREAD

**Issue by mattpangenesis** [molstar/molstar#449]
hello! posting here with some additional context, from my original post in Discussions.

when opening a new PDB in molstar, we'd like to automatically show hydrogen bonds that are created between protein and ligand and label the residues.

wondering if:
1) there's a way we can programmatically provide pairs of residues/atoms to label and also show measurements for, without needing the user to manually specify them
2) Molstar has any default mode that automatically shows hydrogen bonds between protein and ligand

from browsing the codebase, we've seen this https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/structure/measurements.tsx, and I assume there's some way of updating the state to show these -- would appreciate if you have any suggestions/examples on how to do so.

thanks so much!

**Comment by dsehnal** [comment]
Hi, yes, you can do this. You can have a look at the implementation of the [measurement manager](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/measurement.ts#L97) to get you started.

**Comment by mattpangenesis** [comment]
thanks so much! do you have any references / examples on how to specify the atoms/residues of the structure, especially how they are specified as locis?

E.g. if we have a residue of proteinX and an atom of ligandY, how we pass in the correct locis to this

`this.plugin.managers.structure.measurement.addDistance(loci[0].loci,` loci[1].loci);`

thank you again for the help for this basic question

**Comment by dsehnal** [comment]
https://github.com/molstar/molstar/issues/168 should help.
