### ISSUE TITLE
Block scoping example

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#450]
Greetings,

Why is this portion of code enclosed in extra brackets?
https://github.com/molstar/molstar/blob/e7ce693e509885fb74eacc0a5a50540762eeb58f/src/apps/viewer/app.ts#L419

I understand it has to do with [block scoping rules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block#block_scoping_rules_with_let_const_or_function_declaration_in_strict_mode) but what is the intended effect here?

**Comment by dsehnal** [comment]
I think it's because the code used to be more complicated and I left it in this weird state with the brackets around. They are redundant in this case (tho removing them makes the linter complain about using let for a variable that isn't reassigned).
