### ISSUE TITLE
Issue with non standard PDB file

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#451]
Hi,
I'm having issues loading this example file [test-models-with-different-atoms.pdb](https://github.com/molstar/molstar/files/8868480/test-models-with-different-atoms-2.pdb.txt) that works for NGL.
This is a heterogeneous multi-model structure having CONECT records only on the first model. It seems that CONECT records are messing up bonds between atoms as you can see. If i remove CONECT records everything works fine instead.

First model
![image](https://user-images.githubusercontent.com/20627977/172806306-a3b3998f-40e2-41a6-8762-4cfa6c0bebc7.png)

Second model
![image](https://user-images.githubusercontent.com/20627977/172806378-5d6eac72-607f-473d-8d1a-254c556833f2.png)

**Comment by dsehnal** [comment]
Hi, thanks for bringing this up. However, I don't think this is something we should be fixing tho as it is a very rare edge case and arguably a malformed input.

**Comment by giagitom** [comment]
Hi @dsehnal 
ok no problem, thanks for letting me know.

**Comment by arose** [comment]
> Hi, thanks for bringing this up. However, I don't think this is something we should be fixing tho as it is a very rare edge case and arguably a malformed input.

agreed
