### ISSUE TITLE
Hide default trajectory controls with custom `PluginUISpec`

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#458]
Greetings,

How could I make the trajectory controls disappear (I intend to make custom ones to match the rest of my UI).

![test-traj](https://user-images.githubusercontent.com/46487703/174084804-5f4d9985-4f5b-43a3-aaa7-acd92c714dac.png)
![model-control](https://user-images.githubusercontent.com/46487703/174084818-c0b930c7-de31-446d-808f-01988d0f9027.png)

Please note that I start the plugin with the following spec at the moment:
```typescript
const PlayMoleculeSpec: PluginUISpec = {
  ...DefaultPluginUISpec(),
  config: [
    [PluginConfig.VolumeStreaming.Enabled, false],
    [PluginConfig.Viewport.ShowExpand, false],
    [PluginConfig.Viewport.ShowAnimation, false],
    [PluginConfig.Viewport.ShowControls, false],
    [PluginConfig.Viewport.ShowSettings, false],
    [PluginConfig.Viewport.ShowSelectionMode, false],
  ],
  canvas3d: {
    camera: { mode: "orthographic" },
    renderer: {
      backgroundColor: 0x303030 as Color,
    },
    postprocessing: {
      occlusion: {
        name: "off",
        params: {},
      },
    },
  },
};
```

**Comment by dsehnal** [comment]
They should already be hidden if you do that.

This line is in ``AnimationViewportControls``:

```ts
if (isPlaying || this.state.isEmpty || this.plugin.managers.animation.isEmpty || !this.plugin.config.get(PluginConfig.Viewport.ShowAnimation)) return null;
```

And testing it locally on ``viewer/app.ts`` it works as expected.

**Comment by ptourlas** [comment]
Hi,
I have not been precise in my description of the problem.
`[PluginConfig.Viewport.ShowAnimation, false]` works as intended but it is the model selection that I would also like to hide.

![AnimationControls2](https://user-images.githubusercontent.com/46487703/175529652-596d3c19-b8d0-4c53-8a67-d87268f36e82.png)

I believe it is the `TrajectoryViewportControls` in https://github.com/molstar/molstar/blob/0f5a6194ffc83b9963c2ce41e84f2625da00f203/src/mol-plugin-ui/controls.tsx that implements this.
Maybe a PR with a plugin spec option for these will do the trick?
