### ISSUE TITLE
How to clone a loci?

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#460]
Is there a function that allows to do this?

**Comment by arose** [comment]
Loci are immutable (if not by type than by convention, although we should fix the type), so there should be no need to clone them. What is your use case?

**Comment by giagitom** [comment]
> Loci are immutable (if not by type than by convention, although we should fix the type), so there should be no need to clone them. What is your use case?

Oh... ok. If loci are immutable I think that there is no problem. I'll use references to the same loci in case of necessity.

Thanks for the clarification
