### ISSUE TITLE
Possible issue with Loci.remap() 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#461]
I am trying to remap a loci based on a different structure using ```Loci.remap()```. Sometimes this works, but sometimes it doesn't and the output loci is empty (even if it shouldn't be).

I have found the possible issue here:
https://github.com/molstar/molstar/blob/0f5a6194ffc83b9963c2ce41e84f2625da00f203/src/mol-model/structure/structure/element/loci.ts#L152-L153

This issue could be entirely due to my wrong interpretation of how remap method should be used, but I have found that if i compare against ```unit.invariantId``` instead of ```unit.id``` everything seems to work fine.

if i get the unit in this way, it seems to work fine in every case in my code.
```ts
  let unit
   structure.units.forEach(u => {
      if (u.invariantId === invId) unit = u
   });
  if (!unit) return
```

**Comment by dsehnal** [comment]
How different is the structure? This only works for a different conformation of the same structure.

**Comment by giagitom** [comment]
What do you mean by "different conformation" more in detail?

The initial loci structure represents a full crystal asymmetric unit. Instead the final structure on which the loci will be remapped is an assembly derived from the same crystal. In this case the assembly structure has less units than the asymmetric unit. An example could be entry 2E4A.

**Comment by dsehnal** [comment]
That's not what the ``remap`` function is for. When you load a trajectory, each frame is a different structure (= "same structure with different conformation"). For your use case, you need to run your query on the assembly itself and not try to remap things onto an assembly.

**Comment by giagitom** [comment]
Ok, thanks for the help @dsehnal I'll try in this way. 

Regarding invariantId instead? I would like to better understand Molstar functioning

> Also I am wondering how invariantId is generated? I noticed this value doesn't change between correspondent units on different structures derived from same model. Can I always trust this correspondence between units?

**Comment by giagitom** [comment]
Instead what does ```chainGroupId``` represents?

**Comment by dsehnal** [comment]
> Instead what does `chainGroupId` represents?

All instances of the same unit have the same ``chainGroupId``. Mol* doesn't do "physical" copies of chains when rendering instances and this helps with performance of some algorithms.
