### ISSUE TITLE
hide and unhide protein and hetatm structure 

### ISSUE THREAD

**Issue by andreassteffen** [molstar/molstar#463]
hi,
how can I programmatically hide and unhide the protein and the hetatms of a structure independently of each other?

**Comment by dsehnal** [comment]
You can use the ``setSubtreeVisibility`` function on a node of the state tree to show/hide different parts.

**Comment by andreassteffen** [comment]
ok thanks.
I can achieve it this way:
```
 setSubtreeVisibility(window.molstar.state.data, window.molstar.managers.structure.hierarchy.current.structures[1].components[0].cell.transform.ref, show);
```
with structures[1] pointing to an existing protein structure, and components[0] pointing to the protein (protein component has the key: "structure-component-static-polymer", the ligand has the key: "structure-component-static-ligand"
