### ISSUE TITLE
Displaying a `.cube` file programmatically

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#467]
Greetings!

I would like to do as the title says. :smile:
* My approach at the moment is the following:
```typescript
if (file_extension === "cube") {
    const volume = await window.molstar.builders.data.rawData({ data: data }); //#1
    const parsed = await window.molstar.dataFormats
      .get("cube")
      .parse(window.molstar, volume); //#2

    const volumeParams = createVolumeRepresentationParams(
      window.molstar,
      parsed.data,
      {
        color: "uniform",
        type: "isosurface",
        typeParams: {
          visuals: "wireframe",
          alpha: 1,
          sizeFactor: 1.75,
        },
      }
    ); //#3

    await window.molstar
      .build()
      .to(volume.ref)
      .apply(
        StateTransforms.Representation.VolumeRepresentation3D,
        volumeParams
      )
      .commit(); //#4

    return;
  }
```
Steps `#1, #2` and `#3` appear to be working fine. Moving to `#4` though, I am greeted by:

`Error: No suitable parent found for 'tL5HU56flSzh_UXIuA6-uA'` and I have no idea which `StateObjectSelector` owns this ref.

---
I tried to replicate what's in
https://github.com/molstar/molstar/blob/d5659529d7e192ce45e7b667ffdfebe2d213ce4b/src/apps/viewer/app.ts#L350
with some tweaks for handling raw data instead, but no luck.

--- 
Additionally, what is the `plugin.dataTransaction(async () => ...)` used for in
https://github.com/molstar/molstar/blob/d5659529d7e192ce45e7b667ffdfebe2d213ce4b/src/apps/viewer/app.ts#L369 
?

Thanks in advance.

**Comment by dsehnal** [comment]
Hi, try having a look at https://github.com/molstar/molstar/blob/master/src/apps/viewer/app.ts#L350

**Comment by ptourlas** [comment]
@dsehnal Advice worked, my first examination of the code was rather sloppy. :wink: 

---
However, my question regarding the `plugin.dataTransaction(...)` part remains. My code works without it, but what does it do?

**Comment by dsehnal** [comment]
> However, my question regarding the `plugin.dataTransaction(...)` part remains. My code works without it, but what does it do?

I didn't read that far, can't sneak questions like this at the end :)

The transaction will automatically rollback the state tree if there is an error during evaluation inside it, e.g.

```ts
dataTransaction(async () =>{
  await update1();
  await update2();
  await updateThrows();
});
```

will automatically remove ``update1`` and ``update2``.

**Comment by ptourlas** [comment]
Great! Thanks a lot for the clarification. :+1:
