### ISSUE TITLE
Visualization of density maps (.mrc) kept on remote server

### ISSUE THREAD

**Issue by ag-deepesh** [molstar/molstar#468]
Hello,

I have git cloned Molstar on the remote server. I also have kept my density map in the examples folder on the remote server itself. Using ssh port forwarding, I open the Molstar in the local browser. When I open the 'Viewer' I am able to load local mrc files. However, when I click on the link corresponding to my density map file in the examples folder, it just merely downloads it locally.
How do I visualize the density map (.mrc file) kept in the remote server (examples folder) in the Molstar viewer in the local browser? Is there some additional processing required?
Your suggestions will be greatly appreciated.

Thanks and Regards,
Deepesh

**Comment by dsehnal** [comment]
Hi,

you will have to host your files somewhere where they can be accessed over HTTP and then you can load them in Mol*. [This function](https://github.com/molstar/molstar/blob/master/src/apps/viewer/app.ts#L350) (or it's variation which you customize yourself) should help you.
