### ISSUE TITLE
structure.parent/child question

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#470]
Hi,
I'm wondering what is the meaning of the ```parent``` and ```child``` property inside a ```structure``` object. What is it used for?

**Comment by dsehnal** [comment]
Hi,

Mostly used for visualization to get context for selections and also some optimizations. You can right-click the ``child`` property on ``Structure`` and "Find all references" which should give you more context.

**Comment by giagitom** [comment]
Thanks!
