### ISSUE TITLE
Not operating for a long time,this effect apperars

### ISSUE THREAD

**Issue by webtop1** [molstar/molstar#471]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/4414747/176575861-254e32b4-75f9-4363-82a7-dc44a73dd1a9.png">

**Comment by webtop1** [comment]
When I do not operate the page for a long time, the page will automatically change to the "screenshot" effect, what should I do?

**Comment by dsehnal** [comment]
This looks like you have used the graphics card memory for other things in the meantime and the browser (or perhaps the graphics card drivers) destroyed the viewport context for Mol*. Sometimes refreshing the page works, other times you need to restart your browser, sometimes even restarting computer is needed.

**Comment by arose** [comment]
This looks very much like the WebGL Context is lost. This happens when the browser (or the OS) reclaims the WebGL resources for something else. There is nothing I know of that we can do about.
