### ISSUE TITLE
How to avoid browser freezing while updating a representation?

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#472]
Hi,
I'm doing the update in this way at the moment. 
```ts
repr.createOrUpdate(params,data).run();
```

the problem is that when i'm updating something heavy like molecular surfaces for example, the browser completely freezes. In the web app this does not happen instead. How to obtain a similar behavior?

**Comment by arose** [comment]
You have to pass an observer to the run method. This will yield back control back to the browser intermittently. See https://github.com/molstar/molstar/blob/0b143812551e417008a53b88c08eb489e45f8a7e/src/tests/browser/parse-xtc.ts#L21-L23

**Comment by giagitom** [comment]
Awesome!
Thanks
