### ISSUE TITLE
How to hide waters by default?

### ISSUE THREAD

**Issue by rdk** [molstar/molstar#477]
Hi,

I couldn't find a way how to hide waters in newly loaded proteins (before they are rendered). Is it somehow possible?
I know how to hide or remove waters once the protein is loaded using `plugin.managers.structure.hierarchy.toggleVisibility()|remove()`, but that causes flash on the svcreen as the waters are rendered and then dissapear.
I am using custom `PluginUIContext` wrapper based on default Molstar `Viewer`.

More specific questions:

1. Is there a way how to globally hide all waters (also for proteins loaded in the future)?
2. Is there a way how to prevent waters from being loaded at all? (or remove them before the newly loaded protein is rendered)

Thanks a lot!

**Comment by dsehnal** [comment]
Hi,

the water is added [here](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/builder/structure/representation-preset.ts#L165) in the default present.

Two options:
- You write your own custom preset which doesn't add the water by default
- You create a PR for Mol* which adds ``ignoreWater`` option [here](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/builder/structure/representation-preset.ts#L39) and support it in the presents.
