### ISSUE TITLE
Updating volume representation parameters

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#478]
Greetings,

I am able to generate a volume from a cube file like this:
```typescript
      const parsed = await molstar.dataFormats
         .get("cube")
         ?.parse(molstar, _data);

      const repr = molstar.build();

      repr.to(parsed.volume.ref).apply(
        StateTransforms.Representation.VolumeRepresentation3D,
        createVolumeRepresentationParams(molstar, firstVolume.data, {
          type: "isosurface",
          typeParams: {
            visuals: [defaultVolumeParams.visuals],
            alpha: defaultVolumeParams.alpha,
            isoValue: Volume.adjustedIsoValue(
              volumeData,
              defaultVolumeParams.isoValue,
              "relative"
            ),
          },
          color: "uniform",
          colorParams: { value: defaultVolumeParams.color as Color },
        })
      );

      await repr.commit();
```

I keep `parsed.volume.ref` in a separate list so that I can access the state object later.
How can I update the representation shown above?

Thanks.

**Comment by dsehnal** [comment]
```ts
const representation = repr.to(parsed.volume.ref).apply(
        StateTransforms.Representation.VolumeRepresentation3D,
       ... 
).selector;

plugin.build().to(representation).update(createVolumeRepresentationParams(...))
```

**Comment by ptourlas** [comment]
Lifesaver. Thanks a ton.

(Sneaky question at the end: What is this `.selector` thing and why `parsed.volume.ref` does not work here? I want to write a documentation entry about it.)

**Comment by dsehnal** [comment]
- `selector` is a pointer to the current cell when building the state tree
- `parsed.volume.ref` is reference to the volume data, not the representation, these are different things.

**Comment by luna215** [comment]
@dsehnal RE this [comment](https://github.com/molstar/molstar/issues/478#issuecomment-1178587251), what sort of parameters would you pass for the second argument?

```typescript
const representation = repr.to(parsed.volume.ref).apply(
        StateTransforms.Representation.VolumeRepresentation3D,
       ... 
).selector;
```

This is what I currently have
```typescript
const representation = repr.to(cacheVolume.volumeRef as any).update(StateTransforms.Representation.VolumeRepresentation3D);
```
I am creating the volume representation exactly the same way, but when I do the code above and get the `representation` and pass onto this piece of code:

```typescript
await plugin.build().to(representation).update(createVolumeRepresentationParams(...)).commit();
```

I get an error that a following node can't be found. Any idea on this or guidance is greatly appreciated as always 🙏🏽 !

**Comment by dsehnal** [comment]
I have no idea from the code you posted. The create a last update looks correct tho. If it can't find the node it seems you might have a stale reference to the volume node.
