### ISSUE TITLE
Failure in opening PDB file on iOS or iPadOS

### ISSUE THREAD

**Issue by riquri** [molstar/molstar#479]
Hi, I tried to view a PDB file on my iPad (Chrome and Safari).

From "Open Files", the file app launched, but I could not select PDB files.
Instead of a raw PDB file, a zipped pdb file was selectable and viewable.
Is this a problem with the allowed file type on the molstar, or a limitation of iOS?

**Comment by arose** [comment]
I don't have an iOS device, can't say what the issue is.

**Comment by RowenaZireael** [comment]
I have the same issue on iPad. Drag and drop works if you can’t select files, but it doesn’t work if you want to load trajectory. I tried zipped .pdb, .gro, .xtc files when loading trajectory but all failed.

**Comment by RowenaZireael** [comment]
A temporary solution for trajectory is using VMD to put structure and trajectory together into a .gro file and then use drag and drop. But the size of this .gro file will be huge.

**Comment by tubiana** [comment]
Hi :-)

Sorry to come back to this!
Is there a filter type in the file selection coded in molstar @arose  :-) ?
I'm facing the same situation...

Thank you :)!

**Comment by tubiana** [comment]
Apparently it's an iOS problem...
https://discussions.apple.com/thread/8129699
