### ISSUE TITLE
em density map is displaied as a sphere...

### ISSUE THREAD

**Issue by pconesa** [molstar/molstar#48]
Hi! Nice project. I've found this

![image](https://user-images.githubusercontent.com/785633/82419441-b7e4bf80-9a7e-11ea-8de3-3c6e58957867.png)

This is not how users expect to visualise em maps.

This is how NGL does it and chimera does something similar:

![image](https://user-images.githubusercontent.com/785633/82419849-3b061580-9a7f-11ea-8980-b3187dc152bd.png)

Also, I didn't find a way to play with the sigma value.

**Comment by arose** [comment]
That looks funny, and not as it supposed to. Can you share the map file?

The isolevel can be changed in the controls panel on the right, see below

<img width="648" alt="Screen Shot 2020-05-20 at 12 56 22 AM" src="https://user-images.githubusercontent.com/272250/82420728-f9507d00-9a34-11ea-8f0f-e876180867c7.png">

**Comment by pconesa** [comment]
Thanks! I didn't get those panels. Might be related. When I click on the last ". . ." whole page goes blank.
 Got this in my console:
![image](https://user-images.githubusercontent.com/785633/82422347-9ede0d80-9a82-11ea-94e9-f0c7e0e2d9c0.png)

The map I'm using is a sharpened map. Hope you can find it here: https://mega.nz/file/6M5j1Z7J

I've tested other mrc volumes and look correct.

**Comment by arose** [comment]
the link asks me for a decryption key?

**Comment by pconesa** [comment]
Sorry, first time I use MEGA: https://mega.nz/file/6M5j1Z7J#xejFilMEDRQzjH0ExztktnkTI2VrvltUAWqpj5ecvoU

**Comment by arose** [comment]
Fixed, will publish tomorrow. We assumed the stats in the mrc header were always calculated but in that file they are all zero. Now this case is handled.

<img width="578" alt="Screen Shot 2020-05-20 at 1 54 31 AM" src="https://user-images.githubusercontent.com/272250/82426644-f8bbe480-9a3c-11ea-8676-43e21f90e515.png">

**Comment by pconesa** [comment]
Thanks! @arose , I'll contact the developers that are generating the file. May be the bug is theirs!

I'm getting this from the headers:

Printing headers...
Input: /home/pablo/ScipionUserData/projects/EMPIAR10200/Runs/001207_XmippProtLocSharp/extra/sharpenedMap_last.mrc

--- File information ---
Filename       : /home/pablo/ScipionUserData/projects/EMPIAR10200/Runs/001207_XmippProtLocSharp/extra/sharpenedMap_last.mrc
Endianess      : Little
Reversed       : False
Data type      : Floating point (4-byte)
Data offset    : 1024
--- Image information ---
Image type     : Real-space image
Dimensions     : 1 x 200 x 200 x 200  ((N)Objects x (Z)Slices x (Y)Rows x (X)Columns)
Sampling rate  : 
                 X-rate (Angstrom/pixel) = 0.814
                 Y-rate (Angstrom/pixel) = 0.814
                 Z-rate (Angstrom/pixel) = 0.814
--- Geometry ---
Euler angles   : 
                 Phi   (rotation around Z axis)                  = 0
                 Theta (tilt, second rotation around new Y axis) = 0
                 Psi   (third rotation around new Z axis)        = 0
Origin Offsets : 
                 Xoff  (origin offset in X-direction) = 0
                 Yoff  (origin offset in Y-direction) = 0
                 Zoff  (origin offset in Z-direction) = 0
Scale          : 1
Weight         : 1
Flip           : 0

Which stats are you referring to? Are there any max, min value meant to be in the header ?

**Comment by arose** [comment]
> Which stats are you referring to? Are there any max, min value meant to be in the header ?

amin, amx, amean, rms (https://bio3d.colorado.edu/imod/doc/mrc_format.txt)

**Comment by pconesa** [comment]
Thanks! I'll share this.
