### ISSUE TITLE
Question: How can I rotate camera around axis X by 90 degree?

### ISSUE THREAD

**Issue by cycle20** [molstar/molstar#482]
Hi,

Should I achieve the rotation in subject by updating camera position?
```ts
PluginCommands.Camera.Reset(this.plugin, { snapshot: { position: Vec3.create(x, y, z) }  });
```
Thank you

**Comment by dsehnal** [comment]
You can use either the ``Reset``  command or ``this.plugin.canvas3d?.requestCameraReset``

The rotation itself you can do by rotating the up vector around the ``camera.target - camera.position`` vector:

```ts
const snapshot = this.plugin.canvas3d?.camera.getSnapshot();
const newSnapshot = {
  ...snapshot,
  up: rotateUp(snapshot),
};
```

``Quat.setAxisAngle(Quat(), axis, Math.PI / 2);`` should help with the rotation itself.

**Comment by cycle20** [comment]
Should I apply the resulted `Quat` on `snapshot.up`?
```ts
const newSnapshot = {
  ...snapshot,
  up: Vec3.transformQuat(Vec3(), snapshot.up, q)
};
```
`q` effect is very similar to a rotation around axis Z by 90deg.
(_NOTE_: `snapshot.target - snapshot.position` is parallel with Z)

However using vector `v` [1, 0, 0] as `axis` parameter of `setAxisAngle` call does not work too.

**Comment by dsehnal** [comment]
Oh, I suppose you might want to rotate the position instead then (guess I misunderstood what you are trying to achieve). Try rotating the vector ``position - target`` with ``setAxis([1,0,0], Math.PI / 2)`` (or ``-Math.PI/2``) and setting the new position as ``target + my_rotation(position - target)``. Might require some more math with the ``up`` vector too, but I am sure you will figure it out :)

**Comment by cycle20** [comment]
Thank you! :+1:
