### ISSUE TITLE
Select instead of marking

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#483]
Hi,
I'm able to mark a loci using ```canvas3d.mark()```. How to apply/remove the selection marking instead?

**Comment by dsehnal** [comment]
can you please be more specific about what you want to achieve?

**Comment by giagitom** [comment]
I would like to be able to mark loci using two different colors. One color when hovering over a loci and one color to show a selection (that in the online app is in green)

**Comment by dsehnal** [comment]
These things can be managed by ``plugin.managers.interactivity``.

**Comment by giagitom** [comment]
Is there a solution using canvas3d instead? 

I'm not using ```plugin``` in my implementation.

**Comment by giagitom** [comment]
I have found a way using MarkerActions
