### ISSUE TITLE
camera manualReset option is ignored if canvas becomes empty

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#490]
In the situation in which a representation is updated using an empty structure ( so the canvas becomes empty ), even if I use manualReset option, camera clip space seems to be updated to 0. Is this something wanted?

**Comment by dsehnal** [comment]
I think this might be some edge-case handling going haywire. Maybe you can have a look in `mol-canvas3d/canvas3d.ts` where this logic is implemented and make a PR with a fix?

Alternatively, you can try restoring camera snapshots manually in your code to prevent this.
