### ISSUE TITLE
can I programmatically switch off the side-bar tools?

### ISSUE THREAD

**Issue by andreassteffen** [molstar/molstar#491]
Hi,
is it possible to switch/hide these tools?
<img width="532" alt="image" src="https://user-images.githubusercontent.com/1114010/179957247-eaf286e0-a774-4f2c-ab5e-24a67fc3a258.png">
Many thanks, Andreas

**Comment by dsehnal** [comment]
Some of them yes (see ``PluginUISpec.layout`` which you can pass in when creating the plugin instance. Most of the buttons can be hidden/disabled.

For the rest, you can override the CSS class or ultimately write your custom UI.

**Comment by andreassteffen** [comment]
ok, thanks.
for future reference:
```
    config: [
        [PluginConfig.VolumeStreaming.Enabled, false],
        [PluginConfig.Viewport.ShowExpand, false],
        [PluginConfig.Viewport.ShowAnimation, false],
        [PluginConfig.Viewport.ShowControls, false],
        [PluginConfig.Viewport.ShowSettings, false],
        [PluginConfig.Viewport.ShowSelectionMode, false],
    ]
```
