### ISSUE TITLE
mmcif and label

### ISSUE THREAD

**Issue by fmareuil** [molstar/molstar#495]
Hi,

I'm using plugin.builders.data.download to load a structure in the molstar plugin and I search a way to impose the label with a mmcif format file.

Indeed with pdb format file, label argument is working fine but not with mmcif format.

Thank you for your help and your great work.
best regards

**Comment by dsehnal** [comment]
The label in download will only affect the download node. What is your desired end behavior?

**Comment by fmareuil** [comment]
Hi,
I would like to impose the label regardless of the structure's format.
Is it possible?
Thanks for your help.
best regards

**Comment by dsehnal** [comment]
The label for mmCIF file is taken from the ``entry.id`` field. Can you modify that? 

Otherwise you would have to write your own transform that assigns the label you want. You can have a look at ``TrajectoryFromMmCif`` and ``TrajectoryFromPDB`` as a starting point.
