### ISSUE TITLE
Transparency issue?

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#497]
I don't know if this is a bug or an algorithm limitation but when setting alpha < 1 it seems that z-depth is ignored. 
Some questions in case this is a limitation:
- Is it possible in some way to fix this when exporting an image?
- Are there alternative transparency methods to use?

with alpha = 1  (correct)
![image](https://user-images.githubusercontent.com/20627977/180442121-e630fada-5304-461e-be94-4008881a6793.png)

with alpha = 0.9 (incorrect)
![image](https://user-images.githubusercontent.com/20627977/180442233-0b45f2fa-8d6b-4f52-be3f-fd3c7c4afdb7.png)

**Comment by dsehnal** [comment]
For the ordering, you need to have WBOIT enabled otherwise you get this behavior. Some browsers (e.g. Safari do not support this well I think). You might also have wboit disabled by mistake in your plugin instance.

![image](https://user-images.githubusercontent.com/21145776/180614710-ed3cc722-8fc3-482b-b262-2be8c59da8ff.png)

**Comment by giagitom** [comment]
Oh ok thanks,
Looking at the code maybe I have found the cause of my problem. ```DefaultAttribs``` are not passed to ```Passes``` constructor here
https://github.com/molstar/molstar/blob/31c98ef1ba56196abe166ad34d8458264c96bc4c/src/mol-canvas3d/canvas3d.ts#L142
so if i don't explicitly set ```enableWboit : true``` in attribs, it remains disabled.

**Comment by giagitom** [comment]
I noticed an other thing, 
If I set opacity to 0.99 it should be nearly opaque, instead i get this
![image](https://user-images.githubusercontent.com/20627977/180651691-44586538-d33b-4e89-81c3-ebb36cf27fc0.png)
transparency effect seems to be much more intense and also seems to depend somehow on the distance between the camera and the closest object.

**Comment by dsehnal** [comment]
Well, transparency is hard and there are tradeoffs that need to be made.

Regarding ``DefaultAttribs``, the WBOIT is enabled by default, so maybe your mistake was somewhere else.

**Comment by arose** [comment]
> transparency effect seems to be much more intense and also seems to depend somehow on the distance between the camera and the closest object.

that is the tradeoff of the wboit method, see https://jcgt.org/published/0002/02/09/, basic rule is, not use high opacity

**Comment by giagitom** [comment]
> Regarding `DefaultAttribs`, the WBOIT is enabled by default, so maybe your mistake was somewhere else.

@dsehnal, sorry maybe I was unclear. I think that `a` should be passed to `Passes` constructor instead of `attribs`. Otherwise `DefaultAttribs` aren't used.
https://github.com/molstar/molstar/blob/31c98ef1ba56196abe166ad34d8458264c96bc4c/src/mol-canvas3d/canvas3d.ts#L128
like this
```ts
const passes = new Passes(webgl, a);
```
---
> that is the tradeoff of the wboit method, see https://jcgt.org/published/0002/02/09/, basic rule is, not use high opacity

Thanks for the article @arose, I'm also wondering if there are (non real time) methods giving correct results for example when taking screenshots or making videos.

**Comment by dsehnal** [comment]
That makes sense. Can you please make a PR with a fix @giagitom ?

**Comment by arose** [comment]
> Thanks for the article @arose, I'm also wondering if there are (non real time) methods giving correct results for example when taking screenshots or making videos.

There is depth peeling (see https://developer.download.nvidia.com/assets/gamedev/docs/OrderIndependentTransparency.pdf and recent three.js example implementation https://github.com/mrdoob/three.js/pull/24227). It is one extra render pass for each transparency layer you want to resolve. For comparison, wboit always needs two passes. So, depending on the use case depth peeling may very well be real time. Do you want to give it a go?

**Comment by giagitom** [comment]
> There is depth peeling (see https://developer.download.nvidia.com/assets/gamedev/docs/OrderIndependentTransparency.pdf and recent three.js example implementation [mrdoob/three.js#24227](https://github.com/mrdoob/three.js/pull/24227)). It is one extra render pass for each transparency layer you want to resolve. For comparison, wboit always needs two passes. So, depending on the use case depth peeling may very well be real time. Do you want to give it a go?

It would be very nice to try this method. But seems complex to implement it in molstar (at least to me). Do you have any suggestions on how to approach this implementation?

**Comment by giagitom** [comment]
@arose I have found Dual depth peeling method. It halves the number of necessary passes, so I guess it could be better for realtime purposes. 

https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.193.3485&rep=rep1&type=pdf

**Comment by arose** [comment]
@giagitom I put some ideas on implementing depth peeling in #503.
