### ISSUE TITLE
How do I programmatically set highlighting.

### ISSUE THREAD

**Issue by webtop1** [molstar/molstar#500]
In the PDB loaded file, there are two molecules, as shown in the figure, how to programmatically highlight only one of the two molecules.
![image](https://user-images.githubusercontent.com/4414747/180696003-86e782d1-0654-4121-b6ac-9976840fac6d.png)

Thank you very much!

**Comment by webtop1** [comment]
I found it in the code:

PluginCommands.Interactivity.Object.Highlight(this.plugin, { state: this.plugin.state.data! , ref });

How do you know the REF of one of these molecules?

**Comment by dsehnal** [comment]
Hi, try having a look at the [basic wrapper example](https://github.com/molstar/molstar/tree/master/src/examples/basic-wrapper), it shows how to do this.

**Comment by webtop1** [comment]
> Hi, try having a look at the [basic wrapper example](https://github.com/molstar/molstar/tree/master/src/examples/basic-wrapper), it shows how to do this.

Yes, that worked! Thank you
