### ISSUE TITLE
Hiding and showing existing representations

### ISSUE THREAD

**Issue by luk27official** [molstar/molstar#501]
Hello,
I would like to know what is the best way to hide and show existing representations. I am able to create more representations and hide/re-show them manually in the menu, but I cannot find out how to do it programatically.

From what I have tried it seems like deleting a representation with `plugin.build().delete('representationName');` and re-creating it again later would possibly work, but I feel like there could be a more efficient way to do it, especially for a bigger number of groups.

Thank you!

**Comment by dsehnal** [comment]
Hi,

https://github.com/molstar/molstar/issues/463
https://github.com/molstar/molstar/discussions/171

**Comment by luk27official** [comment]
Works as expected, thanks.
