### ISSUE TITLE
How to access created components by their label?

### ISSUE THREAD

**Issue by cycle20** [molstar/molstar#504]
Hello,
I create some components by state transformation. I could add labels to via `StructureSelectionFromExpression`.
How can I refer to these components later for further operations by these label?
(`chain-test`-way does not work: it checks labels from data files and not the visual labels.)

_Another question:_
If I transform an asymmetry, the result also has its source asym id.
It looks like another view of the source. On mouse hover each result of the same asymmetry highlights the current residue and their labels is the same despite the label of resulted component(s).
How can I assign different asym ids of a resulted component during a transformation or after it?

**Comment by cycle20** [comment]
_Another question:_
If I transform an asymmetry, the result also has its source asym id.
It looks like another view of the source. On mouse hover each result of the same asymmetry highlights the current residue and their labels is the same despite the label of resulted component(s).
How can I assign different asym ids of a resulted component during a transformation or after it?

**Comment by dsehnal** [comment]
One way is to remember the "selector", e.g.

```ts
const update = plugin.build();
const selection = pluing.to(cell).apply(StructureSelectionFromExpression, ...).selector;
await update.commit();

// later
plugin.build().to(selection).update(...);
```

And sorry, I don't understand your second question.

**Comment by cycle20** [comment]
Thank you. Illustration for the second question. In this case I have four C ALA 29 (only 3 of them visible from this perspective):

![transformed_residues](https://user-images.githubusercontent.com/46718432/182096134-04fc18e4-2370-4c10-84cc-3f7be4d93bc5.png)

**Comment by arose** [comment]
For scripting there is `MolScriptBuilder.acp('operatorName')` which evaluates to `unit.conformation.operator.name`.

There is no easy way to change the asym id, you would need to create your own model, better to use the operator name to distinguish such chains.

**Comment by cycle20** [comment]
> There is no easy way to change the asym id, you would need to create your own model, better to use the operator name to distinguish such chains.

Do you mean I need to create create own model from CIF input data?

**Comment by cycle20** [comment]
> One way is to remember the "selector", e.g.
> 
> ```ts
> const update = plugin.build();
> const selection = pluing.to(cell).apply(StructureSelectionFromExpression, ...).selector;
> await update.commit();
> 
> // later
> plugin.build().to(selection).update(...);
> ```

I have tried it, but it gives back the source probably. And the second transformation had no effect on it.
I logged it after each transformation (in this case three times):

![image](https://user-images.githubusercontent.com/46718432/183637762-cb5452d4-8224-4fc1-b9fa-948607eb5756.png)

Another issue with this: already excluded chains appeared (black cartoon chains below the membrane region)

![image](https://user-images.githubusercontent.com/46718432/183637603-9b315654-b7dd-4fed-b85a-6f31484c0ae7.png)

As you can see: transformed chains could not be translated into the membrane region by the selector. Their source was translated there by an `apply` with a single matrix - in this case it does not require a first rotation.
