### ISSUE TITLE
More examples of how to control the behaviour of the viewer from javascript

### ISSUE THREAD

**Issue by elfin-sbreuers** [molstar/molstar#509]
Dear molecular visualisation enthusiasts,

molstar is a ingenious tool. Thank you for that.

I'd like to use it in a small application triggering the load of structures via JavaScript. I was able to use `viewer.loadStructureFromUrl()` to load locally served pdb files. The protein is currently displayed in a cartoon representation. For my purposes the Quick Style `illustrative`, providing outline, a flat shading, and space-filling representation, would be more suitable. I saw that there is a fourth parameter to `viewer.loadStructureFromUrl`. Reading through the code, I lost track of what happens to `representationParams`, that is used in one of the examples in `molstar/src/apps/viewer/embedded.html`:

```
viewer.loadAllModelsOrAssemblyFromUrl('https://cs.litemol.org/5ire/full', 'mmcif', false, { representationParams: { theme: { globalName: 'operator-name' } } })
```
A trial exchange of `operator-name` with `illustrative` was not successful.

Could anyone give me a hint on how to use the options object to control, how the loaded pdb is visually represented?

**Comment by arose** [comment]
The Quick Style `illustrative` is not available via the viewer app's api. The code for the Quick Styles is here https://github.com/molstar/molstar/blob/aa3d657d428e595d54288c52055ddee10df52815/src/mol-plugin-ui/structure/quick-styles.tsx. You will need to create your own viewer app build with that functionality added.

**Comment by elfin-sbreuers** [comment]
Thanks for your quick reply and for pointing me in the right direction. I did now this by shamelessly copying

```
await viewer.loadStructureFromUrl(url, format='pdb');
const { structures } = viewer.plugin.managers.structure.hierarchy.selection;
const preset = viewer.plugin.builders.structure.representation.providerMap.get("preset-structure-representation-illustrative");
await viewer.plugin.managers.structure.component.applyPreset(structures, preset);
if (viewer.plugin.canvas3d) {
    viewer.plugin.canvas3d.setProps({
        postprocessing: {
            outline: {
                name: 'on',
                params: { scale: 1, color: "#000000", threshold: 0.25 }
            },
            occlusion: {
                name: 'on',
                params: { bias: 0.8, blurKernelSize: 15, radius: 5, samples: 32, resolutionScale: 1 }
            },
        }
    });
}
```
Is there maybe a bit more information about how to use the API to for example control the background color, create my own selection, and/or generating representations? I mean except for a deep dive in this beautiful piece of code.

Thanks again for your help.
