### ISSUE TITLE
Hide topo/xtc objects in state tree

### ISSUE THREAD

**Issue by stefdoerr** [molstar/molstar#512]
Hi all, I'm using the following code to load a molecule with topology and coordinates into mol*. However in the state tree instead of a single object it shows three objects. Is something wrong in my code? Do I need to somehow hide the first two entries? Should they even be there? They are a bit weird because if I delete one of the two first it also deletes the Trajectory object.
Essentially I want just one entry on the left per structure which I visualize, sort of like VMD or pymol

![image](https://user-images.githubusercontent.com/7935362/183084486-d868be9c-d65a-4b84-87cc-2e1a585a8ca5.png)

```ts
export async function createStructureWithTrajectory(
    moldata: MoleculeData
  ) {
    const molstar = window.molstar as PluginUIContext;
    let {topodata, label, topoext, xtcdata} = moldata;
  
    const built_top = await molstar.builders.data.rawData({
      data: topodata,
      label: label,
    });
    const provider = molstar.dataFormats.get(topoext);
    const { topology } = await provider!.parse(molstar, built_top);

    const built_xtc = await molstar.builders.data.rawData({
        data: xtcdata,
        label: label + "-XTC",
      });
    
    const provider = molstar.dataFormats.get("xtc");
    const coords = await provider!.parse(molstar, built_xtc);
  
    const trajectory = await molstar
      .build()
      .toRoot()
      .apply(
        TrajectoryFromModelAndCoordinates,
        {
          modelRef: topology.ref,
          coordinatesRef: coords.ref,
        },
        { dependsOn: [topology.ref, coords.ref] }
      )
      .commit();
  
    await molstar.builders.structure.hierarchy.applyPreset(trajectory, "default");
    return trajectory;
  }
```

**Comment by arose** [comment]
Yeah, this is to handle creating a node in the state tree that needs input from more than one other node. The whole state in Mol8 is a series of transformation and the dependsOn concept was added to handle that use case. When you delete a node you will also delete all the children and all nodes that depend on it. The tree UI is just representing the state tree. We had some ideas to decouple the UI and the state tree but never got around to do it.

**Comment by stefdoerr** [comment]
I see. Do you think it would be possible to group all those three elements under a dummy parent node since it's a tree? So that I could do:
```
3PTB
    PSF
    XTC
    Trajectory
2DUM
    PSF
    XTC
    Trajectory
```
etc? As long as I could auto-collapse them it would work fine for me

**Comment by stefdoerr** [comment]
![image](https://user-images.githubusercontent.com/7935362/185573967-e6c00298-d326-4733-8d3b-5e7d95356882.png)
So I was able to add the Trajectory under the topology node by changing the code to `.to(topology.ref)` instead of `.toRoot()`
Ideally I wanted it to be under the `3PTB_E12202` instead of under the `PSF NAMD` node but ok, I can survive with this :P 
```ts
  const trajectory = await molstar
    .build()
    .to(topology.ref)
    .apply(
      TrajectoryFromModelAndCoordinates,
      {
        modelRef: topology.ref,
        coordinatesRef: coords.ref,
      },
      { dependsOn: [topology.ref, coords.ref] }
    )
    .commit();
```
I am not sure how to add the XTC under the `3PTB_E12202` node though. Also if you can point out how to auto-collapse and only show the top level elements it would be very helpful.

**Comment by stefdoerr** [comment]
Never mind, dug a bit into the source code and figured out how to group the XTC under the parent node:
![image](https://user-images.githubusercontent.com/7935362/185577117-fd710c64-fbf1-4944-bad7-246c5b3b0ac1.png)

Instead of using the `rawData` method for XTC I replaced it with
```ts
  const data = molstar.state.data.build().to(built_top.ref).apply(RawData, {
    data: xtcdata,
    label: 'xtc data',
  });
  let built_xtc = await data.commit({ revertOnError: true });
```
which allows me to specify which node to put it under in the `.to()` call.

So the only thing I'm missing now is the collapsing of the tree so that it only shows the top level

**Comment by dsehnal** [comment]
Hi @stefdoerr 

You can collapse a node in a state tree with:

```ts
this.plugin.state.data.updateCellState(ref, old => ({ ...old, isCollapsed: true }));
```

(the ``ref`` can be obtained from the selector, e.g. ``data.selector.ref`` from your example).

**Comment by stefdoerr** [comment]
Lovely! :heart: 
Got everything I needed now, thanks a lot!

**Comment by stefdoerr** [comment]
Ah out of curiosity. When I delete now the top node from the viewer does that free up the used memory? i.e. does it recursively delete all objects attached to it? (trajectories, topologies etc?)

**Comment by dsehnal** [comment]
> Ah out of curiosity. When I delete now the top node from the viewer does that free up the used memory? i.e. does it recursively delete all objects attached to it? (trajectories, topologies etc?)

Yes.
