### ISSUE TITLE
What are the [dis]advantages of ColorThemeProvider, CustomElementProperty and LociLabelProvider?

### ISSUE THREAD

**Issue by cycle20** [molstar/molstar#517]
I need to provide custom colors and labels for residues. There are more options to implement it and I am confused a 'bit'.

As I see I can do coloring with `ColorThemeProvider` and `CustomElementProperty`.
I can do labeling with `CustomElementProperty` and `LociLabelProvider`.

I can do labeling and coloring with `CustomElementProperty`, however I could not find any way to determine the `chainIndex` for a specific `residueIndex`.

```ts
    getData(model: Model) {
        const map = new Map<ElementIndex, number>();
...
        const residueIndex = model.atomicHierarchy.residueAtomSegments.index;
        for (let i = 0, _i = model.atomicHierarchy.atoms._rowCount; i < _i; i++) {
            const residueIdx = residueIndex[i];
            const authId = model.atomicHierarchy.residues.auth_seq_id.value(residueIdx).toString();
    
            // TODO: chainId of the current residue?
            //             I can get it in getColor below.
            map.set(i as ElementIndex, getSiteId(chainId, authId)); // <<<<<< value must be based on these ids
        }
...
```

When coloring functions of the provider get `Location`, I can get chain and residue ids which are corresponding to the input mmCIF data:

```ts
function getColor(location: Location): Color {
    let color = DefaultResidueColor;

    if (StructureElement.Location.is(location) && Unit.isAtomic(location.unit)) {
        const atomicHierarchy = location.unit.model.atomicHierarchy;
        const residueIdx = StructureElement.residueIndex(location);
        const chainIdx = StructureElement.Location.chainIndex(location);

        // I can determine these IDs here
        const authId = atomicHierarchy.residues.auth_seq_id.value(residueIdx).toString();
        const chainId = atomicHierarchy.chains.auth_asym_id.value(chainIdx).toString();

        color = residueColor(chainId, authId);
    }
    return color;
}
```

Probably I can also determine chainId and authId in case of a `Loci` parameter. Can you confirm this assumption?
I guess the CustomElementProperty-way can be faster then the others due to its `getData` provide a map for ElementIndex-based colors/labels. Furthermore coloring and labeling defined by a single builder.

Does it have any drawbacks? Can it be applied during state transformations somehow?

**Comment by dsehnal** [comment]
> I can do labeling and coloring with `CustomElementProperty`, however I could not find any way to determine the `chainIndex` for a specific `residueIndex`.

- ``model.atomicHierarchy.chainAtomSegments.index`` maps ``ElementIndex`` (atom index) to ``ChainIndex``
- ``model.atomicHierarchy.residueAtomSegments.offsets[residueIndex]`` maps ``ResidueIndex`` to its 1st ``ElementIndex``
- You can pass the index from ``for (let i = 0, _i = model.atomicHierarchy.atoms._rowCount; i < _i; i++) {`` to ``ElementIndex``.
  - ``StructureElement.Location.element`` field is this ``ElementIndex``.

----------

In general, the "canonical way" would be to use a ``ColorThemeProvider`` and register your own ``LociLabelProvider``. Anything else is a wrapper around that with the goal to make some workflows easier. 

The [PDBe Validation report extension](https://github.com/molstar/molstar/tree/master/src/extensions/pdbe/structure-quality-report) is probably a good example to copy-paste and modify for your needs.


> I guess the CustomElementProperty-way can be faster then the others due to its `getData` provide a map for ElementIndex-based colors/labels. Furthermore coloring and labeling defined by a single builder.

You can build such index inside a normal theme too, if  you look at how the property wrapper with the coloring is implemented.


> Does it have any drawbacks?

The ``CustomElementProperty`` has a specialized instance of coloring provider with less flexibilty than usual. Other than that, if it ends up doing what you need dont think there are drawbacks.

> Can it be applied during state transformations somehow?

The code inside the providers is called "automatically" as part of the state transformation.

**Comment by cycle20** [comment]
Thank you.
