### ISSUE TITLE
How can I navigate Typescript source code of molstar by using break points in VS code?

### ISSUE THREAD

**Issue by simonryu** [molstar/molstar#518]
First of all, I would like to thank molstar's developers for writing this wonderful library.

I would like to use molstar for my developing web service proejct and I am evaluating its some functions.

I have successfully built and run using the source code of molstar repository. I wonder if I could navigate the Typescript code of molstar using break points in VS code. I tried this by following the steps below (on both Ubuntu 18.04 and 20.04) but I could not make it. Would you help me or give me some advice?

0) change the option value of "SourceMap" to "true" of the following files:
- tsconfig.json, tsconfigcommonjs.json, webpack.config.common.js, launch.json
1) npm install 
2) npm run build
3) npm install -g http-server
4) add break points to some lines of .../molstar/src/apps/viewer/app.ts
5) http-server -p 1338
6) start debug function of VS code

After going through the above steps, I could see "molstar viewer" embedded in Chrome browser. I could also see the following files from "source tab of developer tools within Chrom": index.html, molstar.js, molstar.css.

I expected that I could jump into the corresonding line of typescript source code which I put break point in STEP 4. However, VS code did not work in that way.

**Comment by dsehnal** [comment]
Maybe ``launch.json`` requires additional config to link all the source maps?

**Comment by simonryu** [comment]
> Maybe `launch.json` requires additional config to link all the source maps?

Thank David for your comment. Could let me know how to add config to link all the source map? I am still struggling with this issue.

**Comment by MenFsq** [comment]
I encountered the following problem how to deal with? It shows that the two files cannot be found？

[2023-02-14T02:54:30.325Z]  "GET /lib/apps/viewer/molstar.css" Error (404): "Not found"
[2023-02-14T02:54:30.326Z]  "GET /lib/apps/viewer/molstar.js" Error (404): "Not found"
