### ISSUE TITLE
Load structure from Data URL

### ISSUE THREAD

**Issue by jmbuhr** [molstar/molstar#521]
I am looking to embed a molstart viewer into a self-contained html. For this I convert e.g. the pdb file to base64 encoding and create a [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) from it. Is is possible to use the functions in https://github.com/molstar/molstar/blob/33963c085a79e5eec64160b64c5d6ff3782b477b/src/apps/viewer/app.ts such as `loadStructureFromUrl` with Data URLs?

**Comment by dsehnal** [comment]
Just decode the base64 string and pass it to ``loadStructureFromData``.

**Comment by jmbuhr** [comment]
Thank you very much!
