### ISSUE TITLE
Some ligands showing as Carbohydrates

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#522]
Hello,

I think this may be a bug with the viewer. In the protein 5XWC the ligand is classified as a carbohydrate instead of a ligand.

Looking at the [code](https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/carbohydrates/constants.ts) the residue of the ligand (8GL) it seems to be included in the saccharide lists from Glycam, perhaps this is a misclassification?

Steps to reproduce:
- Open [molstar viewer](https://molstar.org/viewer/)
- Load the structure [5XWC](https://www.rcsb.org/3d-view/5XWC)
- Observe that the ligand has been created as Carbohydrate component

**Comment by arose** [comment]
Thanks, fixed in 92ffdeb5bf50bcecacf1b07006fa2c980d570d18
