### ISSUE TITLE
Bonds listed in sdf files are not always respected

### ISSUE THREAD

**Issue by dwilliams-nobias** [molstar/molstar#524]
I want to congratulate the developers on an excellent product.

While developing certain computational tools, I might produce sdf files with some nonphysical bond lengths. Nevertheless, it is important for me that the bonds are properly depicted. If I am not mistaken, even bonds explicitly stated in sdf files are filtered according to element-based rules by default, at least for ball+stick representations. I was wondering if the developers believe this is appropriate, and if so, whether an option to overrule this feature is available.

```
index 942f24a59..a65210450 100644
--- a/src/mol-model-formats/structure/mol.ts
+++ b/src/mol-model-formats/structure/mol.ts
@@ -80,7 +80,7 @@ export async function getMolModels(mol: MolFile, format: ModelFormat<any> | unde
         const indexA = Column.ofIntArray(Column.mapToArray(bonds.atomIdxA, x => x - 1, Int32Array));
         const indexB = Column.ofIntArray(Column.mapToArray(bonds.atomIdxB, x => x - 1, Int32Array));
         const order = Column.asArrayColumn(bonds.order, Int32Array);
-        const pairBonds = IndexPairBonds.fromData({ pairs: { indexA, indexB, order }, count: atoms.count });
+        const pairBonds = IndexPairBonds.fromData({ pairs: { indexA, indexB, order }, count: atoms.count }, {maxDistance: 1E10});
         IndexPairBonds.Provider.set(models.representative, pairBonds);
     }
```

**Comment by arose** [comment]
I suppose we can do that for SDF/MOL and MOL2 (without crystal symmetry). I created #525 for it, basically your patch but using Infinity. Please give it a try.

The reason why I am a bit hesitant is that not checking the distance causes problems periodic or symmetry systems where you want to limit (but not disallow) bonds across boundaries.

**Comment by dwilliams-nobias** [comment]
Thanks for the quick reply. I just tried #525, and it worked for me.
