### ISSUE TITLE
How to use molstar in vue 2.6 created by vue-cli

### ISSUE THREAD

**Issue by CDOnFoot** [molstar/molstar#532]
I want to use the library in vue SFC, how to init.

**Comment by dsehnal** [comment]
You need a reference to a parent div element and then call ``await createPluginUI(element)``.

**Comment by CDOnFoot** [comment]
but when i import createPluginUI in setup mode, it warn that get 504

**Comment by CDOnFoot** [comment]
sorry,it is in vue3.2

**Comment by CDOnFoot** [comment]
> 

why it get 504 when i use createPluginUI module

**Comment by CDOnFoot** [comment]
sorry, my project use vite creating
