### ISSUE TITLE
The page displays, but a black square is displayed instead of the WebGL scene.

### ISSUE THREAD

**Issue by qzzhang** [molstar/molstar#534]
This may be a very old (instead of a new) issue.  Exactly as said by the title line that I found at https://bugzilla.mozilla.org/show_bug.cgi?id=1481717

I am embedding mol* into my html page.  The page displays as expected except the middle structure window always has a black background.  Once I clicked on the "Toggle Controls Panel" icon, the black background disappear and everything shows. On the console, I get tons of warning like the following:

WebGL warning: drawArraysInstanced: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0: Attachment has no width or height.
WebGL warning: drawArraysInstanced: Framebuffer must be complete.

**Comment by dsehnal** [comment]
This might be caused by initializing the plug-in before the parent div has its layout calculated. Try adding `plugin.handleResize()` in a `setTimeout` to resolve the issue.

**Comment by qzzhang** [comment]
Thank you for the quick comment, dsehnal.  Can you give a brief example of your suggested solution please?

**Comment by dsehnal** [comment]
``setTimeout(() => plugin.handleResize(), 50);`` after you call ``createPluginUI``.

**Comment by qzzhang** [comment]
Hi David (I got your first name from Sebastian :))! Thank you for your help.

Unfortunately, after adding the above solution, the black background persists and with a new error msg on the console:
-----------------------------------------------------------
Uncaught (in promise) Error: empty textures are not allowed
    E https://molstar.org/viewer/molstar.js:2
    setSize https://molstar.org/viewer/molstar.js:2
    setSize https://molstar.org/viewer/molstar.js:2
    setSize https://molstar.org/viewer/molstar.js:2
    updateSize https://molstar.org/viewer/molstar.js:2
    ne https://molstar.org/viewer/molstar.js:2
......

**Comment by qzzhang** [comment]
Plus warnings:
WebGL warning: drawArraysInstanced: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)
WebGL warning: drawArraysInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization.

**Comment by dsehnal** [comment]
Can you share your code?

**Comment by arose** [comment]
@qzzhang can you make sure that the html element you use with the molstar plugin has a non-zero size? The errors you see all indicate that your html element has a zero size.

**Comment by qzzhang** [comment]
@arose Thank you for your message.  I have tried to set the size of the my html element either through the css class or directly adding the 'size=100' to the <div></div> element.  It did not make any difference, i.e., I still get the black background first.  Sorry that I did not reply before you closed this ticket.
