### ISSUE TITLE
The mouse click event and selection for a custom shape

### ISSUE THREAD

**Issue by simonryu** [molstar/molstar#535]
@arose 

Q1) I created some spheres using custom representation and added them to state tree. I could see my spheres rendered within molstar viewer. Now, I would like to capture "mouse click event" of those spheres. What I want to do is to re-render some ~control~ **component** outside molstar viewer when user clicks (selects) my spheres. I use my wrapper class which contains an object of "PluginUIContext" as one of its members.  I assign a unique tag to each sphere when it is added to state tree.

I quote your answer to some issue (**How can I detect when a user clicks an atom? #350**) below which, I believe, possibly resolves my issue as well. Can I use "focus behavior" for spheres to capture the click event? If so, would you give some advice how to modify the code? Otherwise, would you give me any alternatives?

---- Quote ----
One example is the the built in "focus" behavior, that shows sticks and interactions when clicking on a residue: https://github.com/molstar/molstar/blob/master/src/mol-plugin/behavior/dynamic/selection/structure-focus-representation.ts

_Originally posted by @arose in https://github.com/molstar/molstar/issues/350#issuecomment-1019560025_

 I add another question below because this is also related to handle custom shape. Sorry for the confusion.

 Q2) Is there an API to select a custom shape which is added to state tree using custom representation?
          In this case, I would like to focus my sphere which is selected using some kind of uniquely assigned tag information.

**Comment by dsehnal** [comment]
Hi, you want to subscribe to ``plugin.behaviors.interaction.click`` event and get the information out from there. There is also ``hover`` and ``drag`` events you can subscribe to.

**Comment by simonryu** [comment]
Thank David for your comments. I have found out the following code chunk:

https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/sequence/sequence.tsx

However, I have no idea of applying this code to my project.

Could you let me know some example code to handle events for custom shape?

**Comment by dsehnal** [comment]
For example this:

```ts
this.plugin.behaviors.interaction.click.subscribe(e => {
    if (Shape.isLoci(e.current.loci)) {
        // ...
    }
});
```

I am not sure from the top of my head what type of loci you will get after the click, but after playing around with it a little you should be able to figure out the details.

**Comment by simonryu** [comment]
Thanks for quick reply. 

Let me briefly show the skeleton of my code to get your help. I write MyPlugInWrapper class just like "BasicWrapper" class in examples of MOLSTAR repository.

export class MyPlugInWrapper {
    private defaultSpec: PluginUISpec; 
    plugin: PluginUIContext;
    ...
    add_click_event(){
        this.plugin.behaviors.interaction.click.subscribe(e => {
            if (Shape.isLoci(e.current.loci)) {
                // Call a method of "C2" to change its some properties.
                change_of_properties_of_C2();
            }
        }
        });
    }

    constructor(){
        ...
        **add_click_event**();
        ...
    }
    
    **load_my_spheres**(filename : string) {
        ...
        await this.plugin.build().to(StateElements.Model).applyOrUpdate(..., CreateSphere, {
           [follow this your advice to other issue](https://github.com/molstar/molstar/issues/82#issuecomment-687659919)
            ...
        }).commit(); 
    }
}

My React component "C1" imports  both "MyPlugInWrapper" and other component "C2".
My program runs as following steps.

STEP 1. Create an object of MyPlugInWrapper within C1.
STEP 2. Call "load_my_spheres()"

What I want to do is to communicate between an object of MyPlugInWrapper and C2.
I.e.,

If a user clicks my sphere, change the properties of C2.
If a user interacts with C2, focus on the corresponding my sphere.

I expected that "change_of_properties_of_C2()" would be called when I click my spheres. However, it did not work. Would you help me? Or Would give me some hints to resolve?

**Comment by dsehnal** [comment]
Some tips:

- Try adding ``console.log(e)`` (before testing for shape loci) to see what events you get back in ``plugin.behaviors.interaction.click.subscribe`` to see if it actually gets called when you click the sphere and that it provides this type of loci. If not, you might have a problem somewhere else, like making the sphere non-interactive when you create the shape.
- You can access the ``sourceData`` property on the ``Shape.Loci.shape()`` to determine if you are clicking on the correct sphere.
- I have no idea what ``change_of_properties_of_C2`` does, but maybe  you are misusing React here?

**Comment by simonryu** [comment]
@dsehnal 
Did I miss something else which is required to create my spheres?

**Comment by dsehnal** [comment]
I am sorry, I don't have time to debug details of your code from partial snippets you sent me. With the solution you linked the loci work, right? 

(The problem might be that you didn't assign groupId in the mesh builder in your solution).

**Comment by simonryu** [comment]
@dsehnal 
Sorry for the long silence. I have find [another github]([molstar-shape-example](https://github.com/hlvlad/molstar-shape-example)) which uses molstar.

**Comment by simonryu** [comment]
@dsehnal 

In my opinion, only difference between #lines 93 - 125 of [source code](https://github.com/hlvlad/molstar-shape-example/blob/719bbac29852721a6dca5e8a8f3830f08c5c9eed/src/MolstarDemoViewer.ts) and my code (CODE BLOCK A in the above) is as follows.

While one group has one shape in #lines 93 - 125 of [source code](https://github.com/hlvlad/molstar-shape-example/blob/719bbac29852721a6dca5e8a8f3830f08c5c9eed/src/MolstarDemoViewer.ts), one group has two or more shapes (set of spheres) in my code (CODE BLOCK A).

NOTE: I assign an unique label to each set of spheres as shown in "CreateSpheres" of CODE BLOCK B.

Still, I do not figure out what I missed and what happened to my program.

**Comment by dsehnal** [comment]
Add `builderState.currentGroup = group;` to before this line https://github.com/hlvlad/molstar-shape-example/blob/719bbac29852721a6dca5e8a8f3830f08c5c9eed/src/cubes/representation.ts#L37 (and possibly in other places where you use the builder).

Setting different group for different parts of the mesh could also let you differentiate between them.

**Comment by simonryu** [comment]
@dsehnal 
Thank you for your reply. I understand that I should assign an unique group Id to each sphere.

I created a set of spheres with each unique id. For example, I created S_1, S_2, and S_3, with 10, 20, and 30 spheres, respectively, as follows.

S_1  = {s_1, s_2, ..., s_10}
S_2 = {s_11, s_12, ..., s_30}
S_3 = {s_31, s_32, ..., s_60}

where "s_i" corresponds to a sphere with its group id "i".

I added S_1, S_2, and S_3 to spheresGroup of CODE BLOCK A one after the other.

I checked out that each sphere has its unique group id (i.e. unique state.currGroup value).

However, the code does not work.  Still, did I miss anything else?

Sorry for bothering you once again.

**Comment by dsehnal** [comment]
I went though the trouble to actually test the code in [https://github.com/hlvlad/molstar-shape-example](https://github.com/hlvlad/molstar-shape-example/blob/719bbac29852721a6dca5e8a8f3830f08c5c9eed/src/cubes/representation.ts#L37) and seeing if the Click event works there and it did.

I am sorry @simonryu, I don't have any more time to this debugging for you; you will have to figure out the bug on your own.

**Comment by simonryu** [comment]
@dsehnal 

Thank you for spending your times.



I figured out that 

"plugin.behaviors.interaction.click.subscribe()" works fine in my code

after 

"await structure.commit()".

However, it does not work if I call "plugin.behaviors.interaction.click.subscribe()" in constructor
(i.e. before "await structure.commit()")

**Comment by dsehnal** [comment]
That looks like there is some other error in your code then, since for a given plugin instance, this should not make any difference.

**Comment by simonryu** [comment]
@dsehnal 
You are right. I figured out what was wrong with my code. I have been tried to call "plugin.behaviors.interaction.click.subscribe()" in LABEL A below. I should have done in LABEL B.
Now, my works fine. 

@dsehnal 
Thank you so much agin for helping me!

`
...
this.plugin = new PluginUIContext(this.defaultSpec);
// LABEL A
...
this.plugin = await createPluginUI(document.getElementById(targetId)!, this.defaultSpec);
// LABEL B
...
`
