### ISSUE TITLE
Empty Mouse Controls section in the control panel

### ISSUE THREAD

**Issue by dlrice** [molstar/molstar#536]
In the `msp-viewport-controls-panel` there is a sub section: `Settings / Controls Info > Mouse Controls` which looks to be occluded when expanded. We've had (uniprot) user feedback that "the dropdown menu is covered up by the title of that section". However upon DOM inspection there isn't any content. Is it planned for this subsection to be populated? If not in the near future perhaps a "Coming soon" would be sufficient to let users now that the section is intentionally left blank?

![image](https://user-images.githubusercontent.com/4357962/186651408-2d724ced-d2bc-4b5b-ac4e-863a50ce096d.png)

**Comment by dsehnal** [comment]
Thanks for the report, fixed in 3.16.0.
