### ISSUE TITLE
Multiple apps on the same page share certain settings

### ISSUE THREAD

**Issue by jmbuhr** [molstar/molstar#540]
When embedding multiple apps on the same page, they appear to share state for the display settings `Occlusion` and `Outline`.
On this example page: https://jmbuhr.de/quarto-molstar/, we are loading a configuration from a snapshot, which retrospectively changes the `Outline` for all other apps on the page.

We found this while building a quarto extension to embed molstar viewers. This is the related issue: https://github.com/jmbuhr/quarto-molstar/issues/10

**Comment by jmbuhr** [comment]
For reference, this is the html we are constructing to embed the app:
https://github.com/jmbuhr/quarto-molstar/blob/5038ddd2ed7e9a5a61648fd95c5156920bafb61a/_extensions/molstar/molstar.lua#L111-L117
https://github.com/jmbuhr/quarto-molstar/blob/5038ddd2ed7e9a5a61648fd95c5156920bafb61a/_extensions/molstar/molstar.lua#L148-L185

**Comment by dsehnal** [comment]
Thanks for the report. I have fixed the issue in 2935717a06652da976d06dccd014308370e2f7cf and it will be included with the next release (I think within a week -- is this good enough for you?)

**Comment by jmbuhr** [comment]
Sure. Thank you so much!
