### ISSUE TITLE
Which is the cheapest way to find the minimum distances between each element of a Structure and a reference Structure?

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#543]
Hi, Is there a built in function for this?

**Comment by dsehnal** [comment]
Haave a look at how bonds are computed ``https://github.com/molstar/molstar/tree/master/src/mol-model/structure/structure/unit/bonds``.

**Comment by giagitom** [comment]
@dsehnal thanks for pointing to that. In my understanding bonds are computed by finding all elements within a max radius. But in my case I don't have a radius limit. I was thinking about iteratively execute `lookup3d.find(...)` increasing the radius until i find at least one element on the reference structure.. But I'm concerned about the performances of this method.. Maybe there is a better way?

**Comment by dsehnal** [comment]
I see. I think the best course of action then would be adding a ``nearest(x, y, z): T | undefined`` function to ``Lookup3D`` (and ``GridLookup3DImpl``) in ``mol-math/geometry/lookup3d``. It should be relatively straightforward to implement this. Can you make a PR with this and we can iterate from there?

Being even fancier, adding ``distanceTo(other: Lookup3D<T>)`` would make it possible to make an even more optimized version of this.

**Comment by arose** [comment]
@giagitom seems like this is done with your PR merged, right?

**Comment by giagitom** [comment]
@arose yes, it is. I'm closing this
