### ISSUE TITLE
When representing interactions, is it possible to exclude interactions among amino acids?

### ISSUE THREAD

**Issue by xuzuodong** [molstar/molstar#544]
When using `docking-viewer` example to represent interactions, is it possible to programmatically control Mol* to **only show interactions between polymer and ligand**, and **do not show interactions among amino acids** (e.g. interactions in the red box shown below)?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/51878637/187658354-a81f5198-af36-4882-b2be-d89ff1777489.png">

It seems that [this function](https://github.com/molstar/molstar/blob/master/src/mol-model-props/computed/interactions/interactions.ts#L183) determines computing process of interactions, maybe I should override this file and add some extra filtering logics here? If it's not too much trouble, can you give some code example to do so?

Thanks!

**Comment by dsehnal** [comment]
> maybe I should override this file and add some extra filtering logics here

Yes, that would be ideal solution. Maybe you can make a pull request with it and we integrate it to the main version of the viewer?

**Comment by xuzuodong** [comment]
I'm willing to do so. The problem is that I don't quite understand codes there yet. Can you give me some clues on how to implement?

**Comment by xuzuodong** [comment]
I've managed it in a hacking way to meet my on requirement. 

Here's my changes: 

1. Comment out [this line](https://github.com/molstar/molstar/blob/master/src/mol-model-props/computed/representations/interactions.ts#L19) to hide "intra interaction"
1. Override `validUnitPair` function used [here](https://github.com/molstar/molstar/blob/master/src/mol-model-props/computed/interactions/interactions.ts#L252) to this: 

```ts
function validUnitPair(s: Structure, a: Unit, b: Unit) {
    if (!Unit.isAtomic(a) || !Unit.isAtomic(b)) return false;
    if (a.residueCount > 1 && b.residueCount > 1) return false;
    return s.masterModel
        ? a.model === b.model || a.model === s.masterModel || b.model === s.masterModel
        : a.model === b.model;
}
```

After the modification, the example becomes: 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/51878637/187826419-1c17a26d-750f-42aa-bcd1-f4f6a8efc04b.png">

However, it no longer supports "intra unit interactions" since I just roughly disabled it.

**Comment by dsehnal** [comment]
Well, seems like it got the job done for you and the solution looks sounds. We might discuss with @arose later this if we include this to the main library.

**Comment by arose** [comment]
Hi, see #548 for a more general solution. It is not the most general but fairly straightforward to implement and use.

**Comment by xuzuodong** [comment]
@arose I checked out your branch and tried `parentDisplay: 'between'`, but it doesn't seem right?

<img width="450" alt="image" src="https://user-images.githubusercontent.com/51878637/188353898-73ebd34b-55d9-4a14-9105-f219aa3dd0a9.png">

**Comment by arose** [comment]
Note that you need to have the representation for a structure selection that only has the ligand. You will need to adjust the docking-viewer for that. Are you doing that?

> The way to use it is to create a structure selection that only has the ligand you want to see interactions to and then set the parentDisplay to "between".

**Comment by arose** [comment]
@xuzuodong OK, there was a bug for the 'between' option that I just fixed (f2f730bab5c0b535bd9d9af96a90934644e54371). I also changed the docking-viewer to use this feature (487450ec646a5fd1e818b5cc4c15655538e6361d).

**Comment by xuzuodong** [comment]
It seems perfect for me now, thanks for your help!😄 @arose @dsehnal

**Comment by Fx-Ren** [comment]
Hello everyone, the topic of current issue is very helpful for me.
But I have a question about docking-viewer, how to toggle the docking-viewer option? I did't see the toggle button on the UI.

Thanks a lot!

@arose @xuzuodong
