### ISSUE TITLE
Extract info from a given structure

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#546]
Greetings!

Supposing I have created a structure for protein (either from a pdb file or psf/xtc pair), how can I take a sneak peek at its internals?
I would need:

* residue ID's
* residue names
* atom names
* chain names
* coordinates

My aim is to reconstruct another file with that info for use with software outside of mol*.

**Comment by dsehnal** [comment]
For example

```ts
Structure.eachAtomicHierarchyElement(s, {
    atom: a => console.log(StructureProperties.atom.x(a), StructureProperties.atom.y(a), StructureProperties.atom.z(a)),
    residue: r => console.log(StructureProperties.residue.auth_seq_id(r))
})
```

You can have a look at how the ``eachAtomicHierarchyElement`` is implemented too so that you can iterate over atoms and residues in a single loop.

**Comment by ptourlas** [comment]
I can make the selection based on a given ref with:
```typescript
const _state_obj = window.molstar?.state.data.selectQ((q) => q.byRef(myref));
```
which returns an array of state cells. But how to progress from here? I am supposed to apply a transformer to the element of that array?

**Comment by ptourlas** [comment]
> I can make the selection based on a given ref with:
> 
> ```ts
> const _state_obj = window.molstar?.state.data.selectQ((q) => q.byRef(myref));
> ```
> 
> which returns an array of state cells. But how to progress from here? I am supposed to apply a transformer to the element of that array?

UPDATE:
I believe this is working:
```typescript
          const _state_obj = window.molstar?.state.data.selectQ((q) =>
            q.byRef(struct.ref)
          );

          if (_state_obj) {
            const structure = _state_obj[0];
            const s = structure.obj?.data;
            Structure.eachAtomicHierarchyElement(s, {
              atom: (a) =>
                console.log(
                  StructureProperties.atom.x(a),
                  StructureProperties.atom.y(a),
                  StructureProperties.atom.z(a)
                ),
              residue: (r) =>
                console.log(StructureProperties.residue.auth_seq_id(r)),
            });
          }
```

and I could also use the `resolveAndCheck` function to get the data required instead of a `byRef` query
```typescript
          const structureCell = StateObjectRef.resolveAndCheck(
            window.molstar?.state.data as State,
            myref
          );
          const s = structureCell?.obj?.data;

```
