### ISSUE TITLE
Protein gets merged with ligand structure, even when they are separated by TER 

### ISSUE THREAD

**Issue by saalim-ihub** [molstar/molstar#549]
I am trying to view the local .pdb structure containing protein and ligand separated by TER using the molstar JS plugin. But for a few complexes, the protein is getting merged with the ligand structure.

![Screenshot from 2022-09-03 09-38-16](https://user-images.githubusercontent.com/107020926/188255397-f08f7ab2-6c0f-4f2d-8bb3-3a8c3de7f96a.png)

What could be the issue? The structure looks fine when opened in chiimera and VMD.

**Comment by saalim-ihub** [comment]
Hello @a-r-j  I have not tried this in PyMol.

hey @arose 
[1a69.zip](https://github.com/molstar/molstar/files/9502796/1a69.zip) you can test it with the file in zip. However, I recently resolved this issue by replacing `C', H'` in etc in ligand with the letter `Z` in .pdb 

Thank you both!

**Comment by arose** [comment]
Hey @saalim-ihub, this will be fixed in molstar by #553.
