### ISSUE TITLE
Show ligand in a different color from protein (Viewer option) 

### ISSUE THREAD

**Issue by j2ho** [molstar/molstar#550]
I am using this Viewer wrapper (https://molstar.org/docs/plugin/) for my web page. 

part of my html code is as below

```
  var viewer = new molstar.Viewer('app', {
        layoutIsExpanded: false,
        layoutShowControls: false,
        layoutShowRemoteState: false,
        layoutShowSequence: true,
        layoutShowLog: false,
        layoutShowLeftPanel: true,

        viewportShowExpand: true,
        viewportShowSelectionMode: false,
        viewportShowAnimation: false,

        pdbProvider: 'rcsb',
        emdbProvider: 'rcsb',
    });
viewer.loadStructureFromUrl('pathtomystructure', 'pdb', false, { representationParams: {theme: {globalName: 'operator-name'}}})

```

My pdb file has protein + ligand in it, and currently both are shown in green.
(Ligand is indicated by pdb header 'HETATM')
Is it possible to show the ligand in a different color by changing the viewer option?  
(I want it to be shown in a different color as a default, not by changing something through the toolbar afterwards)

**Comment by dsehnal** [comment]
You can try ``{ representationParams: { theme: { carbonColor: 'element-symbol' } } }`` if this is enough for you.

Otherwise you would have to either:
- Create the state yourself, for which you would need WebPack to build the code.
- Update the code in ``src\mol-plugin-state\builder\structure\representation-preset.ts`` to support more options and make a Pull Request with the change.

**Comment by j2ho** [comment]
Thanks that option works for me. 
is there a document to see all available options? (e.g., other themes)

**Comment by dsehnal** [comment]
There is no external list, you can have a look at the available presets in ``src\mol-plugin-state\builder\structure\representation-preset.ts`` and built-in themes in ``src\mol-theme\color.ts``.
