### ISSUE TITLE
Not able to visualize protein structures which are present in my local system (in my computer) into my own html page using molstar.

### ISSUE THREAD

**Issue by gigity-gigity** [molstar/molstar#551]
Dear Sir/ma'am,
I am trying to plugin molstar into my website as a visualization tool to visualize some of the structures I have modeled on my own. When using Plugin parameters (options), i.e customData to get data from my computer and visualize it on my website, I am getting this error "GET /home/supremeleader/visualization/A0A0A0CIP3.cif" Error (404): "Not found." I have just learned javascript and website development. Can you please help me with this issue so I can visualize the modeled protein on my website using molstar. Thank you in advance.

I have been using this script from documentation to visualize it:
      var options = {
        customData:{url:'/home/supremeleader/visualization/A0A0A0CIP3.cif',format:'cif'}}
error: "GET /home/supremeleader/visualization/A0A0A0CIP3.cif" Error (404): "Not found"

Please let me know which option I should use and any format syntax to visualize the protein in my system in my database.

Prashant Upadhyay
PhD
Indian Institute of Technology Kanpur

**Comment by prashantupadhyay666** [comment]
Hi dsehnal,
Thank you very much for your reply I have tried hosting these files using above mentioned command
"npm install -g http-server
http-server -p 3333  /home/supremeleader/visualization/" 
still, I am not able to visualize these files. 

So now the error is changed from 
This ->"GET /home/supremeleader/visualization/5wuc-sf.cif" Error (404): "Not found"
This one ->"GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 
and still not able to visualize the protein structure inside molstar window. 
Also in the server where are hosted these files the output in the terminal is 
"GET /5wuc-sf.cif" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
(node:1512036) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)"
 
I eventually want to visualize the .pdb format not .cif format of 6000 modeled proteins in my own database using molstar. Please recommend to me what should I do. I am using node js to develop my database. In my stuck in visualizing this proteins in my database for more than 2 months now and I  specifically want to use molstar for this. But the documentation is poor and not much on stack and biostar telling how to do it. It would be highly obliged and grateful if you could suggest and recommend something to me. 

Thank You,
Prashant Upadhyay
PhD
Indian Institute of Technology Kanpur

**Comment by dsehnal** [comment]
I am sorry @prashantupadhyay666, but the issue you are running into is not Mol* related, poor documentation or not. Your issue seems to be not understanding of how hosting and requesting files works.

A quick google search reveals for example https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server that might explain some of it to you.

**Comment by prashantupadhyay666** [comment]
Thank You very much dsehnal, Very grateful for your help.

**Comment by prashantupadhyay666** [comment]
Hi @dsehnal 
Sorry, I said mol star has poor documentation in an earlier comment. I now realize it was my lack of understanding about CORS with the browser and my frustration of not being able to integrate this amazing tool into my database. Really sorry to your team, please don't be offended. 
Prashant Upadhyay
PhD
Indian Institute of Technology Kanpur

**Comment by orangeSi** [comment]
fixed it at https://github.com/molstar/pdbe-molstar/issues/95
