### ISSUE TITLE
Transparent background blending issue. Pixels of wrong colors transparent objects

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#558]
I have noticed this when enlarging the image. Could this be something related to antialiasing?

When exporting the image it looks like this
![image](https://user-images.githubusercontent.com/20627977/189885771-d38123ba-1359-44e3-96e8-691d97f7a74a.png)
![image](https://user-images.githubusercontent.com/20627977/189881410-259ced11-3996-4e25-9519-846f1e95e097.png)
![image](https://user-images.githubusercontent.com/20627977/189881667-17ff92d0-fec1-408f-82bc-a3b7cb8339fc.png)
![image](https://user-images.githubusercontent.com/20627977/189886335-2b3a1411-fe63-4287-bae7-e9476c19f052.png)
![image](https://user-images.githubusercontent.com/20627977/189887007-c365d9da-a65d-49a3-be91-7545a0519f7f.png)

**Comment by giagitom** [comment]
Anyone else noticed this artifacts?

**Comment by dsehnal** [comment]
At least the "inner ones" look like an overflow on near-white colors. Perhaps the edges too. @arose any idea where this could happen the shaders?

**Comment by giagitom** [comment]
An other (maybe related) thing.. This is a screenshot taken from an external screen capture tool (top) and a normal screenshot with transparent background that I overlayed for comparison purposes with molstar empty canvas (bottom). I notice two things:
- a thin white halo on borders of both opaque and transparent objects (only on the top image)
![image](https://user-images.githubusercontent.com/20627977/191934798-9b61ddc9-760a-4b1f-a5b6-806b88a2fe95.png)

- and also a slight change in colors that is more visible on transparent objects (that can be seen better in the oversaturated image below)
![image](https://user-images.githubusercontent.com/20627977/191940337-17eba8c0-87e4-46b6-9eac-b98a770139ba.png)

**Comment by dsehnal** [comment]
Maybe it's the ambient occlusion. If you turn that off, does this still happen? And if you turn of antialias?

**Comment by giagitom** [comment]
How to disable antialias? 
Disabling ambient occlusion i get this (same configuration)

- The thin white outline is more marked than before 
- I start seeing strange colors on borders on top 
![image](https://user-images.githubusercontent.com/20627977/191945055-5dc607ee-240f-4cd4-8444-d16fda16cfa6.png)

- The change in colors is still present 
![image](https://user-images.githubusercontent.com/20627977/191945258-44dbd12e-a1b0-40e1-95cb-1228696129f8.png)

**Comment by dsehnal** [comment]
![image](https://user-images.githubusercontent.com/21145776/191946506-989c765f-63fa-4101-9071-93aaf816b072.png)

**Comment by dsehnal** [comment]
It seems that the built screenshot blends against black background and the outside one against white. And this then creates the artifacts during the AO pass.

**Comment by giagitom** [comment]
With antialias turned off the colors on transparent areas are now uniform in both cases (see transparent cartoon)
![image](https://user-images.githubusercontent.com/20627977/191952093-1a14c8da-809b-43b1-9f30-40e6dd69fc35.png)

**Comment by arose** [comment]
So the border issues seem to come from the SMAA anti-aliasing. With anti-alias set to Off or FXAA the borders look good to me. So bug 1) is with SMAA and transparent background. I see the SMAA border issue in the viewport (white fringes) and in the screenshot view (black fringes). Workaround is to use FXAA instead. Maybe FXAA is good enough in general, especially with the manual multi-sampling. Or can someone fix SMAA?

What is puzzling to me is the black wholes in the screenshot view on what appears to be surface normals similar to the camera direction. In the viewport the same parts looks good.

![image](https://user-images.githubusercontent.com/272250/192083922-dcc0f654-7db3-4524-b3c9-17f4ed9099fa.png)

![image](https://user-images.githubusercontent.com/272250/192084180-932458ea-cf17-44d0-b9d4-cbfa3cb7d82c.png)

**Comment by giagitom** [comment]
> What is puzzling to me is the black wholes in the screenshot view on what appears to be surface normals similar to the camera direction. In the viewport the same parts looks good.

@arose,  regarding black wholes (that not always are black; I have seen also semi transparent green wholes) I noticed that by using `ignore light` in the representation there is no issue.

Furthermore, digging a bit I have found that the problem should be due to `directSpecular` calculation inside `RE_Direct_Physical`. Removing `directSpecular` from the `outgoingLight` sum the issue seems to disappear. That said, i think this is only part of the issue because the canvas works well with or without `directSpecular`. Maybe the real problem is in the differences between canvas and snapshot settings?

**Comment by arose** [comment]
Fixed some artifacts with 6ed0ae55b2aeda0dc7dc5df296d169cc844cdc74. Tried to `clamp` in a few more places but that did not help.

**Comment by giagitom** [comment]
Hi @arose, I think have found something else related to `specularColor` and `metalness` in `apply_light_color` chunk. This is a test state presenting the issue 
[test.molj.txt](https://github.com/molstar/molstar/files/9741821/test.molj.txt)

`specularColor` is used by `F_Schlick` in `BRDF_GGX`. 
- If i substitute `F_Schlick` return value with vec3(1,1,1) the issue disappears. 
- Furthermore if I set metalness >= 0.04 the issue is gone as well. It is ineresting that going below 0.04 the issue starts to appear since I have found vec3(0.04) here ```physicalMaterial.specularColor = mix(vec3(0.04), color.rgb, metalness);```. 
- Also the issue is present in a defined range of alpha values  

![image](https://user-images.githubusercontent.com/20627977/194763812-f8a39d40-ee8a-463a-8e94-e3803a1017ba.png)

**Comment by arose** [comment]
The example state shows a much larger section than on the screenshot. I looked around a bit but I am unable to reproduce that issue with the current version on my machine.

**Comment by arose** [comment]
The only issue I still have is black artifacts the screenshot preview with SMAA and transparent background and ignore light (all three on together). The downloaded image is fine though, as is the one on the canvas.

**Comment by giagitom** [comment]
Sorry, I forgot to tell that I had `dpoit` enabled. Using `wboit` the same view is ok for me. 
Here is an other example that is clearer on red and blue spheres at sticks extremities. [test.molj.txt](https://github.com/molstar/molstar/files/9742726/test.molj.txt)

![image](https://user-images.githubusercontent.com/20627977/194783604-985e33b8-a7d8-434a-9f55-2373913ed123.png)

**Comment by arose** [comment]
Thanks for the new view. I was looking at with dpoit enabled. It looks totally fine me. I suspect we are in driver-differences-territory... Does clamping `physicalMaterial.specularColor` fixes it for you?

**Comment by giagitom** [comment]
Ok good. Tomorrow I'll try and let you know

**Comment by giagitom** [comment]
I have made some tests. Clamping only `physicalMaterial.specularColor` doesn't solves the problem entirely. So far I can tell that to remove all artifacts there are two ways that seem to work for me:

- Clamp `physicalMaterial.specularColor` and `physicalMaterial.diffuseColor` between 0.0 and 1.0, and clamp `outgoingLight` between 0.001 and 0.999 

- Or clamp only `outgoingLight` between 0.0 and 1.0 and clamp `metalness` between 0.001 and 1.0

The second seems to be the less invasive way i think..

**Comment by giagitom** [comment]
@arose should I make a PR for this?

**Comment by arose** [comment]
> @arose should I make a PR for this?

Yes please, the first option sounds good to me
