### ISSUE TITLE
Error when canvas element is hidden entirely

### ISSUE THREAD

**Issue by russellp17** [molstar/molstar#560]
This is a pretty minor issue but wanted to see if there's a quick fix. For users viewing a structure on a small window, they may cover the canvas element entirely, especially when opening Mol* sidebars which results in a `Error: empty textures are not allowed` error:

<img width="818" alt="Screen Shot 2022-08-10 at 5 30 33 PM" src="https://user-images.githubusercontent.com/71293199/190192524-a3a131d3-52a3-4ccf-ad97-58ec9cd35a2d.png">

**Comment by dsehnal** [comment]
Thanks for the report, this might be an easy fix in the `canvas3d.ts:handleResize` function (or the functions it is calling) to make the minimum size say (2, 2). Would you create a PR for this?

**Comment by russellp17** [comment]
Yep, I can put up a fix soon
