### ISSUE TITLE
Back faces color options? 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#562]
Hi,
Is there some option to change back faces color?

**Comment by arose** [comment]
There are parameters to change them globally, either darken the exiting color or replace by a given color.

https://github.com/molstar/molstar/blob/aa414485a5439f4a19b7228c2925e929dea4e495/src/mol-gl/renderer.ts#L92-L94

**Comment by giagitom** [comment]
Awesome, thanks!
