### ISSUE TITLE
Component toggle visibility callback

### ISSUE THREAD

**Issue by bioinsilico** [molstar/molstar#564]
Is there any way to subscribe a function when components toggle visibility?

**Comment by dsehnal** [comment]
Yes, you can subscribe to events/behaviors of `plugin.state.data`.

**Comment by bioinsilico** [comment]
My best finding was

plugin.state.data.events.cell.stateUpdated.subscribe((s)=>{
            if(s.cell.obj?.type.name == "Structure" && typeof s.cell.state.isHidden === "boolean")
                console.log(s);
        });

I am not sure if this is the right way to go.

**Comment by dsehnal** [comment]
The components have a tag which starts with `structure-componen-`. If you want this supported for your own custom states, you need to either keep track of the cells or add the tags or use some other method that does what you want

```ts
plugin.state.data.events.cell.stateUpdated.subscribe((e)=> {
  if(e.cell.obj?.tags?.find(t => t.indexOf('structure-component-') === 0))
    console.log(s, !!s.cell.state.isHidden);
});
```

**Comment by bioinsilico** [comment]
Thank you, @dsehnal. I will follow your recommendation.
