### ISSUE TITLE
How to visualize protein structure from alphafold database.

### ISSUE THREAD

**Issue by gigity-gigity** [molstar/molstar#565]
Hi,
I want to visualize a structure from the Alphafold database in my web browser using the Molstar plugin. When I gave the "customData" "option" in Molstar and add the link to the Alphfold entry of the protein just like for  PDB, it showed a CORS (cross-origin resource sharing) error. Help me integrate structures from the Alphafold database to my website.

For example: I want to visualize this protein (uniprot/alphafold id: A0A0A0CIP3) I gave 
var options = {
                  customData: {url:'https://alphafold.ebi.ac.uk/entry/A0A0A0CIP3' ,format:'pdb'}
}
Is this the correct way of doing this ??
Thank You.

**Comment by dsehnal** [comment]
There is a `loadAlphaFoldDb` method in the `Viewer` class: https://github.com/molstar/molstar/blob/master/src/apps/viewer/app.ts#L289
