### ISSUE TITLE
Dpoit issue when postprocessing is off

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#568]
@arose here attached is a test state to reproduce the issue. [test.molj.txt](https://github.com/molstar/molstar/files/9654407/test.molj.txt)
There is some depth issue when dpoit is enabled and postprocessing is disabled (outlines, AO and environment are off). Enabling postprocessing resolves the problem. It seems also that the camera zoom level is important in some way.

With postprocessing disabled (issue)
![image](https://user-images.githubusercontent.com/20627977/192499007-8c1b6a1e-607e-437f-a1db-8c44a6a62fdf.png)

With postprocessing enabled (normal)
![image](https://user-images.githubusercontent.com/20627977/192499466-7bd3b961-4b98-4290-8bb9-3e31ee93fab1.png)

**Comment by arose** [comment]
Should be fixed with 7dabdf30852fcfa885e5695a8739b192596cc861

**Comment by giagitom** [comment]
Awesome thanks!
