### ISSUE TITLE
Presets: Show no cartoon for structures with many polymer-gaps

### ISSUE THREAD

**Issue by arose** [molstar/molstar#57]
For files that only contain a very partial, fragmented model, e.g. a binding site, it does make not much sense to show a cartoon representation.

Find presets code at https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/builder/structure/representation-preset.ts.

**Comment by arose** [comment]
@dsehnal can you link an example file?

**Comment by dsehnal** [comment]
https://cs.litemol.org/1cbs/ligandInteraction?authAsymId=A&authName=REA&authSeqNumber=200&radius=5

**Comment by arose** [comment]
https://molstar.org/viewer/?structure-url=https%3A%2F%2Fcs.litemol.org%2F1cbs%2FligandInteraction%3FauthAsymId%3DA%26authName%3DREA%26authSeqNumber%3D200%26radius%3D5&structure-url-format=mmcif
