### ISSUE TITLE
How would you load a gromacs file manually

### ISSUE THREAD

**Issue by dionjwa** [molstar/molstar#574]
Let's say I have molstar embedded.

And I have a gromacs generated trajectory, in the same javascript context.

What is the path to feed that into molstar?

The example viewer can do this, but it's unclear how to do that.

**Comment by dsehnal** [comment]
There is the method `Viewer.loadTrajectory` in viewer/app.ts which includes a sample how to use in a docstring above it.

**Comment by dionjwa** [comment]
Thank you! Appreciate it
