### ISSUE TITLE
Canvas shows checkered background -- program not linked

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#576]
Hey,

One of our users reported a strange visual glitch, I've seen the checkered canvas before but never with this oval shape.
Mol* is working on other machines with the same specs and software versions installed. Other WebGL applications work. The WebGL report looks OK as far as I can tell.

Just wanted to share this with you. Maybe you've seen this before or have an idea. Otherwise, feel free to close.

![issue](https://user-images.githubusercontent.com/9744615/193655548-7a16921c-ce49-4e32-9b84-7d2f7dc595c3.jpg)
![report](https://user-images.githubusercontent.com/9744615/193655560-ca7876f8-023f-45ab-899e-4b5c7edded30.png)

**Comment by arose** [comment]
There are shader linking issues in the screenshot, so all bets are of what the output is. I would like to see the console output with debug-mode enabled, e.g. https://molstar.org/viewer/?load-pdb=3pqr&pdb-provider=rcsb&debug-mode=1.

**Comment by JonStargaryen** [comment]
Thanks! Hope to report back soon.

**Comment by JonStargaryen** [comment]
Below is the console output:

![Issue1](https://user-images.githubusercontent.com/9744615/194362230-126c3c60-b380-421c-a9ac-74180dc777f0.JPG)
![Issue2](https://user-images.githubusercontent.com/9744615/194362253-58e62f96-c3c6-4c14-972f-b161ac2c4c60.JPG)
![Issue3](https://user-images.githubusercontent.com/9744615/194362260-8ad6f2f7-4449-485a-996a-c2aa2a957d18.JPG)
