### ISSUE TITLE
Configurable carbon color based on structure

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#577]
How might I implement a custom `ColorTheme` similar to Element Symbol that instead bases the carbon color on what structure the representation belongs to? That way everything showing for a single structure (polymer, ligand, carbohydrate, non-standard, focus target, focus surroundings, etc) would have the same carbon color. Ideally this would be configurable at the structure level, so that if you changed the color assigned to the structure all representations for that structure would automatically update.

Example:

- I load in 2 structures, 3FGR and 129L
- I want to set 3FGR's carbon color to blue for the whole structure (both chains)
- Similarly I want to set 129L's carbon color to purple
- Any new components I add to 3FGR or 129L should be have the same carbon color as the rest of the structure
- If I update the carbon color for 3FGR from blue to green then all the components with this new custom color theme should update

Is something like this possible? So far I've made a `ColorTheme` based on Element Symbol to set the carbon color to a single color, but I'm not sure how to tie that to the structure, or how to make it so that if the color for the structure updates it updates all representations to match.

Thanks in advance for your help!

**Comment by dsehnal** [comment]
You can use a custom property which defines the carbon color at the model level and a theme which pulls the color from there.

**Comment by arose** [comment]
There already is a `CustomModelProperty` called `Model.Index` that gets added by the `StructureInfo` behavior.

Maybe the model-index color theme could be extended to use the `Model.Index` in addition to `Model.TrajectoryInfo`. With that the model-index theme could become an option for the carbonColor in the element-symbol theme. I think that could be a nice contribution.

**Comment by jpattle** [comment]
@arose happy to contribute. How would I update the `model-index` color theme to use `Model.Index` in addition to `Model.TrajectoryInfo`? As far as I can tell it is coloring based off trajectory index and does not appear as an option in the UI if there's only one trajectory for the model. Would it be better to create another color theme, like `structure-index` that works similarly to `model-index` but colors based on model index instead of trajectory index, then add that as a carbon color option?

In addition, I noticed that the carbon color in `element-symbol` is not adjusted by the `props.saturation` and `props.lightness` values whereas the other element colors are. Is this intentional, or should I update this as a part of this enhancement (should be a quick fix)?

**Comment by arose** [comment]
Yeah, on second thoughts combining `Model.Index` and `Model.TrajectoryInfo` is not really useful. I like your suggestion of creating a new color theme that uses `Model.Index`. I would suggest to a breaking change here to improve on the naming and rename the current `model-index` theme (which I think is barely used, only once in molstar itself) to `trajectory-index` and use the `model-index` for a theme that uses `Model.Index`.

> In addition, I noticed that the carbon color in element-symbol is not adjusted by the props.saturation and props.lightness values whereas the other element colors are. Is this intentional, or should I update this as a part of this enhancement (should be a quick fix)?

That is not intentional. A fix would be nice.

**Comment by arose** [comment]
> > In addition, I noticed that the carbon color in element-symbol is not adjusted by the props.saturation and props.lightness values whereas the other element colors are. Is this intentional, or should I update this as a part of this enhancement (should be a quick fix)?

> That is not intentional. A fix would be nice.

Actually, maybe it is. If you apply the adjustments the carbon color won't match, e.g., the color of a cartoon which probably will look off.

**Comment by jpattle** [comment]
Created a Pull Request to implement the functionality discussed above [here](https://github.com/molstar/molstar/pull/583)

**Comment by jpattle** [comment]
Thank you for the updates @arose. Good to see this merged 👍
