### ISSUE TITLE
How to show Surroundings after clicking on structure

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#578]
Hi, 

in this [example](https://www.rcsb.org/3d-view/5OTA/1), when I click on the ligand, there are surrounding representations:
![Screen Shot 2022-10-05 at 8 25 52 AM](https://user-images.githubusercontent.com/7971405/194099398-3747caf5-29fc-4078-88fd-7a33aea03c65.png)

How would I go about doing this on the code side of things. I want this to be the default view as soon as I load mol* viewer? And is there a way to also exclude  N, CA, C, O atoms? Thanks so much in advance!

**Comment by luna215** [comment]
Hi @dsehnal, thanks for the quick reply here! I looked at the file you suggested and followed the code through, but I'm still having trouble selecting the surroundings. Here is my snippet of code:

```typescript
const ligandStructure = await this.createStructure({ url: 'https://molstar-example.s3.us-west1.amazonaws.com/2ym3_ligand.mol2', format: 'mol2', isBinary: false, assemblyId: '1' })

//... 
if (this.components.ligand) await this.plugin.builders.structure.representation.addRepresentation(this.components.ligand, { type: 'ball-and-stick', color: 'element-symbol', colorParams: { carbonColor: { name: 'element-symbol', params: {} } }, label: 'ligand' });

//..
const ligandData = this.plugin.managers.structure.hierarchy.current.structures[1]?.cell.obj?.data;
const ligandFocusEntry = getFocusEntries(ligandData as any)
this.plugin.managers.structure.focus.set(ligandFocusEntry[0] as any);
const { current } = this.plugin.managers.structure.focus;
if (current) this.plugin.managers.camera.focusLoci(current.loci);
```
This is the result:
![Screen Shot 2022-10-06 at 11 20 26 PM](https://user-images.githubusercontent.com/7971405/194480961-051e2a24-1172-4f06-8879-eb7d43bd9610.png)

**Comment by dsehnal** [comment]
If your ligand is a different structure than the protein (which it seems to be), the surroundings won't be shown automatically. You need to create a merged structure to do that; I recommend checking the docking example for doing that.

You can also have interactions between separate structure, but you would have to write a lot of code yourself.

**Comment by luna215** [comment]
@dsehnal yup! That example help a lot!
![Uploading Screen Shot 2022-10-07 at 4.25.01 PM.png…]()

I'm still a bit lost how I can just modify the surroundings? Is there a special function that helps with this?

**Comment by dsehnal** [comment]
There is the structure focus representation behavior (in mol-plugin). You can customize the looks of the surroundings via that or just copy it to your code,modify and replace the corresponding entry in the plug-in spec when you create it.

**Comment by luna215** [comment]
Hi @dsehnal! Thanks for helping with this. I couldn't quite find the example that you mentioned in mol-plugin, but I managed to get it working by looking at the example for the `InteractionsPreset` inside of `src/apps/docking-viewer/viewport.tsx`. 

![Screen Shot 2022-10-09 at 12 13 09 AM](https://user-images.githubusercontent.com/7971405/194743175-bab90e9e-8732-4988-8bf6-7373213694c1.png)

Thanks again!

**Comment by luna215** [comment]
@dsehnal Hi again! After you merge the structures, how would you go about selecting the ligand loci programmatically?
I currently have this:

```typescript
const ligandPlusSurroundings = StructureSelectionQuery('Surrounding Residues (5 \u212B) of Ligand plus Ligand itself', MS.struct.modifier.union([
    MS.struct.modifier.includeSurroundings({
        0: StructureSelectionQueries.ligand.expression,
        radius: 5,
        'as-whole-residues': true
    })
]));
```
and I can't find any functionality where I can use the StructureSelectionQuery to programmatically select the logi. Any help here would be greatly appreciated again! Thanks

**Comment by dsehnal** [comment]
The basic wrapper example shows this I think.

**Comment by luna215** [comment]
@dsehnal I looked at the example, but it doesn't seem to work on my end.

```typescript
this.loadStructuresFromUrlsAndMerge([
        { url: 'https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_ligand.mol2', format: 'mol2' },
        { url: 'https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_protein_processed.pdb', format: 'pdb' }
])

const data = this.plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
const sel = Script.getStructureSelection(ligandPlusSurroundings.expression, data as any);
const loci = StructureSelection.toLociWithSourceUnits(sel);
this.plugin.managers.interactivity.lociHighlights.highlightOnly({ loci });
this.plugin.managers.interactivity.lociSelects.select(loci as any);
```

Am I missing a step here? Again thanks for the help!

**Comment by dsehnal** [comment]
Isn't the selection from your expression empty?

**Comment by luna215** [comment]
@dsehnal You were right because the structures hadn't finished loading, but even if I do it after they have loaded, the ligand structure still isn't selected when I load the page.

```typescript
this.loadStructuresFromUrlsAndMerge([
        { url: 'https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_ligand.mol2', format: 'mol2' },
        { url: 'https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_protein_processed.pdb', format: 'pdb' }
]).then( async () => {
        console.log('Finished loading URLs...');
        this.plugin.behaviors.interaction.click.subscribe(e => {
            console.log(e)
        });

        const data = this.plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
        console.log('expression', ligandPlusSurroundings.expression)
        const sel = Script.getStructureSelection(ligandPlusSurroundings.expression, data as any);
        console.log('select', sel)
        const loci = StructureSelection.toLociWithSourceUnits(sel);
        console.log('loci', loci)
        this.plugin.managers.interactivity.lociHighlights.highlightOnly({ loci });
        this.plugin.managers.interactivity.lociSelects.select(loci as any);
});
```

**Comment by luna215** [comment]
I also print out the both locis. The loci I select with `const loci = StructureSelection.toLociWithSourceUnits(sel);` and the loci that returns when I click the structure: `e.current.loci` and they are identical beside the `indices` field.
![Screen Shot 2022-10-09 at 11 44 03 PM](https://user-images.githubusercontent.com/7971405/194810839-f2635465-8bbd-4656-9dae-c863e0aa8124.png)

**Comment by dsehnal** [comment]
I am sorry, I don't have time to go over this much detail for your problems.

**Comment by luna215** [comment]
@dsehnal no worries, appreciate the help greatly :)

**Comment by luna215** [comment]
@dsehnal I figured out what was wrong with my code. I think I needed to leave a delay because whenever I tried to extract the loci from a component within the structure, it would always come back empty. I just added a simple delay functionality and now it's working. Here's my snippet of code

```typescript
this.loadStructuresFromUrlsAndMerge([
        { url: 'https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_ligand.mol2', format: 'mol2' },
        { url: 'https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_protein_processed.pdb', format: 'pdb' }
).then( async () => {
    console.log('Finished merging structures...');
    this.plugin.behaviors.interaction.click.subscribe(e => {
         console.log(e.current.loci)
         this.plugin.managers.interactivity.lociHighlights.clearHighlights(e.current.loci as any)
    });
    delay(1000).then(() => {
         const ligandData = this.plugin.managers.structure.hierarchy.selection.structures[0]?.components[1]?.cell.obj?.data;
         const ligandLoci = Structure.toStructureElementLoci(ligandData as any)
         this.plugin.managers.camera.focusLoci(ligandLoci)
    })
})
```

I have no idea why adding a delay made it worked. I'm guessing the manager still needed time to fully process, but it works.

**Comment by dsehnal** [comment]
Oh, this is because the component manager is for UI purposes mostly and is a mirror of the state tree which gets updated asynchronously.

I would also not rely on the 1st component there to be what you are looking for each time. I would modify the load function to return the refs/selectors to the things you want to work with next.

**Comment by dsehnal** [comment]
More info:

``StructurePreset`` in the docking viewer actually does return polymer as 2nd component always. You can see that it returns ``return { components, representations };``. Something like this should work:

```ts
const preset = await this.plugin.builders.structure.representation.applyPreset(structureProperties || structure, StructurePreset);
if (!preset.components.polymer.isOk) return;
const ligandData = preset.components.polymer?.data;
// ...   
```
