### ISSUE TITLE
Extracting an atoms charge

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#585]
Hi, 

I'm trying to extract an atoms charge so I can replace the value programmatically. I have the following mol2 file and I'm trying to extract the last column. 
![Screen Shot 2022-10-12 at 7 05 53 PM](https://user-images.githubusercontent.com/7971405/195482010-a6d7aedc-e06f-41be-be89-f17b6975f186.png)

I managed to find the properties of the atom in the file `mol-model/structure/structure/properties.ts`, but I'm not seeing how to return the charge from here. This is what I have:

```typescript
Structure.eachAtomicHierarchyElement(structure as any, {
        atom: a => console.log(
                        StructureProperties.atom.x(a),
                        StructureProperties.atom.y(a), 
                        StructureProperties.atom.z(a),  
                        StructureProperties.atom.pdbx_formal_charge(a),
                        StructureProperties.atom.occupancy(a),
                        StructureProperties.atom.B_iso_or_equiv(a),
                        StructureProperties.atom.sourceIndex(a),
                        StructureProperties.atom. (a),
                    )
      })
```
But none of these return the charge of an atom. I want o change the atom's charge so I can repaint the structure. Any guidance/help is greatly appreciated here! 🙏🏽

**Comment by dsehnal** [comment]
This should work: 

```
function getPartialCharge(unit: Unit, element: ElementIndex) {
    return AtomPartialCharge.Provider.get(unit.model)?.data.value(element);
}
```

**Comment by luna215** [comment]
@dsehnal Worked like a charm!

Full code for anyone else looking for this:

```typescript
Structure.eachAtomicHierarchyElement(structure as any, {
        atom: a => console.log(
                        StructureProperties.atom.x(a),
                        StructureProperties.atom.y(a), 
                        StructureProperties.atom.z(a),  
                        StructureProperties.atom.pdbx_formal_charge(a),
                        StructureProperties.atom.occupancy(a),
                        StructureProperties.atom.B_iso_or_equiv(a),
                        StructureProperties.atom.sourceIndex(a),
                        getPartialCharge(a)
                    )
});

function getPartialCharge(location: Location) {
    if (StructureElement.Location.is(location)) {
        return AtomPartialCharge.Provider.get(location.unit.model)?.data.value(location.element);
    }

    return
}

```

**Comment by dsehnal** [comment]
Doing `const getCharge = AtomPartialCharge.Provider.get` outside the function might improve performance if there are many atoms.

**Comment by luna215** [comment]
@dsehnal  🙏🏽  at the moment I'm only working wth 42 atoms but thanks for the tip!

And anyone following the thread, in order for me to overpaint the structure, I would have to create a custom theme in `mol-theme/color/`.  A bunch of examples in there as well.
