### ISSUE TITLE
Update/initialize state of an extension

### ISSUE THREAD

**Issue by jeffreyspaan** [molstar/molstar#587]
Hi,

What is the proper way to initialize/update the state of an extension? In my case, I want to set a callback when the molstar plugin is first created and every time a specific event occurs outside of molstar.

The anvil extension has something like this, but it seems to be triggered by a predefined event in molstar itself.

For context, my extension is largely based on the geometry export extension.

**Comment by dsehnal** [comment]
Do you want to update custom UI component (similar to how the geo export extension does it) inside Mol* from an external event?

**Comment by jeffreyspaan** [comment]
Yes. For example, let's say I want to change the header of the UI of my extension (which extends CollapsableControls) based on an external event.

However, I don't see how the geo export extension currently does that?

**Comment by dsehnal** [comment]
I recommend you create a common behavior in `PluginContext.customState` (e.g. `plugin.customState.mySharedBehavior = new BehaviorSubject(...)`) and use that in both your extension and external event to sync the state.
