### ISSUE TITLE
Is molstar all front-end focused?

### ISSUE THREAD

**Issue by AlanWitmer** [molstar/molstar#591]
The question relates to whether the molstar viewer is safe to use for proprietary molecules - in other words, does structural, sequence, or other data ever get sent to any third party services for analysis or processing?  So far it appears the front-end is quiet for the operations I've tried so far, and I just want to be sure that a user can't accidentally expose the data.

Thank you!

**Comment by dsehnal** [comment]
- No data is shared with 3rd party services for the purposes of analysis automatically.
- The default viewer at `molstar.org` allows state-sharing functionality, which can be used to upload the description of the viewer state (what type of visuals are present but not the actual data)
- The default viewer allows to save a "session snapshot" to a local file, which contains all the uploaded data. This isn't uploaded to any 3rd party services.
- Some functions might leak the identifier of the structure that is open. This is for example when trying to load structure validation report from PDB or experimental data for protein structures.
- All of the above mentioned functionality can be disabled in your custom integration of the plugin.
