### ISSUE TITLE
Ability to export with theme colors applied

### ISSUE THREAD

**Issue by jk7f** [molstar/molstar#598]
We have an Angular application where the user is able to upload their model, and can color residues using data from our application (implemented via a theme).

I'm using the `to_mmCIF` to export the model, is there any way to include the theme with this export?

**Comment by dsehnal** [comment]
mmCIF doesn't support storing information about themes. You would have to add a custom category with your data & possibly an extension which automatically parses them. But it would be very hard to make this work with 3rd party software.

But you can store the entire user session and then open it later with this coloring in Mol*, this can be done via:

```ts
PluginCommands.State.Snapshots.DownloadToFile(this.plugin, { type: 'zip' })
```

and opened with 

```ts
PluginCommands.State.Snapshots.OpenFile(this.plugin, { file });
```

**Comment by jk7f** [comment]
That's what I expected. Thank you for the quick reply!
