### ISSUE TITLE
Creating AlphaOrbitals list

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#607]
Hi, 

I'm trying to replicate the controls that is in the `alpha-orbitals` example, but in my case, I am loading a cube from a url. From the example, I believe I need a list of `AlphaOrbitlas[]` to make this work, however, when I looked into the CubeFile, I see that `orbitals` is set to `boolean` and doesn't grab a list of orbitals. 

```typescript
export namespace CubeFile {
    export interface Header {
        orbitals: boolean,  // this is a boolean
        comment1: string,
        comment2: string,
        atomCount: number,
        origin: Vec3,
        dim: Vec3,
        basisX: Vec3,
        basisY: Vec3,
        basisZ: Vec3,
        dataSetIds: number[]
    }

    export interface Atoms {
        count: number,
        number: Column<number>,
        nuclearCharge: Column<number>,
        x: Column<number>,
        y: Column<number>,
        z: Column<number>
    }
}
```

Is there a helper function within molstar to help me generate a list of AlphaOrbitals from a cube file ? Or is this functionality not yet available? If this functionality is missing, I'd be more than happy to contribute to this, but might this some guidance on this.

**Comment by dsehnal** [comment]
A single cube file will only be one orbital. The field indicates if the data is an orbital. If you want to have the functionality of the example you will need multiple cube files and either download them ahead (likely very slow) or on demand, which will complicate your app logic.

**Comment by luna215** [comment]
Thanks for the speedy reply @dsehnal. One quick question and it might be a dumb one, but are the orbitals not the blobs that surround the structure in the demo?

RE to 

> There is actually no need the density to the atoms since you already have the density data in form of the cube file. What the orbitals extension does is compute the orbital density on the fly on GPU.

Does this mean that I can bind the volume representation to a selector as soon as I load it form the cube file?

**Comment by dsehnal** [comment]
- In this case, an orbital corresponds to a density field for a molecule. This is often visualized as two iso surfaces (the blue and red blobs) of this density. In your case, this would be a single cube file.
- Electron density is then a sum over all these orbitals (also can be represented as a separate cube file).

There are also different types of orbitals and who knows what, I don't really know the quantum chemistry theory in detail.

**Comment by luna215** [comment]
Have I finally found something that the great @dsehnal doesn't know 😲 ! Obviously kidding, but thank as always with the informative feedback!

**Comment by dsehnal** [comment]
Jesus, finally :D

If you have an academic domain email and want to see a different UI for obitals (uses the same code as in the Mol* extension) see https://www.entos.ai/envision.

**Comment by luna215** [comment]
@dsehnal thanks! Crossing my fingers that my UCSD email is still valid 😭  🤞🏽
