### ISSUE TITLE
When will I render an iframe with a z-index of 2147483647?

### ISSUE THREAD

**Issue by er-pai-r** [molstar/molstar#608]
I wrote a demo of rendering multiple files by referring to scr/apps/viewer and scr/apps/docker-viewer on the official website, but after a while I would render an iframe with a z-index of 2147483647. Am I passing the parameters incorrectly?

**Comment by dsehnal** [comment]
Sorry I don't know what you are asking. I am not aware of any iframes being used in mol*.

**Comment by er-pai-r** [comment]
t's just weird, if I render mol* separately from the project no problem

**Comment by er-pai-r** [comment]
this is bug demo url: https://github.com/er-pai-r/molstar-multiple-files-demo

**Comment by er-pai-r** [comment]
you can run it: npm install, then npm start
