### ISSUE TITLE
how to render multiple files？

### ISSUE THREAD

**Issue by er-pai-r** [molstar/molstar#609]

**Comment by luna215** [comment]
@er-pai-r Are you trying to do this programmatically or within the viewer itself? I can better help if you provide more details here..

**Comment by er-pai-r** [comment]
by programmatically

**Comment by er-pai-r** [comment]
this is a simple demo: https://github.com/er-pai-r/molstar-multiple-files-demo.

**Comment by luna215** [comment]
This is a nice example that helped me get started. You can mimic the functionality and call the function multiple times:  https://github.com/molstar/molstar/blob/d77981230b6887263e171e61907677c3110778f8/src/examples/lighting/index.ts#L112

**Comment by er-pai-r** [comment]
OK，i try try发自我的 iPhone在 2022年11月5日，12:02，Paul Luna ***@***.***> 写道：﻿
This is a nice example that helped me get started. You can mimic the functionality and call the function multiple times:  https://github.com/molstar/molstar/blob/d77981230b6887263e171e61907677c3110778f8/src/examples/lighting/index.ts#L112

**Comment by er-pai-r** [comment]
https://github.com/er-pai-r/molstar-multiple-files-demo/blob/main/src/pages/viewer/index.js#L279.
It doesn't seem to work very well. It is not the same as selecting the existing multiple file interfaces to render the content.
The url is my demo‘s code.

**Comment by luna215** [comment]
I thought you only wanted to render the structures? 
Sorry, I don't have time to go into specific code and debug but you'll also need to merge the structures. `docking-viewer` has a nice example of this.
