### ISSUE TITLE
Ligands are not Displayed in Symmetry Mates

### ISSUE THREAD

**Issue by bioinsilico** [molstar/molstar#61]
When the Structure Type Symmetry Mates option is selected, the ligands are not displayed for the model chain copies.

**Comment by arose** [comment]
That is probably on purpose. The Viewer chooses a Preset based on the number of residues in the structure. The more residues are there the more coarse the display will be. And the first thing that is not shown are ligands and water. If you click the Preset option in the Components panel you can pick a different preset yourself including Cartoon & Ligand. See https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/builder/structure/representation-preset.ts#L70-L97 as a starting point how the automatic preset is picked.

**Comment by bioinsilico** [comment]
However, choosing the preset "Polymer & Ligand" does not display ligands in the new Symmetry Mates instances, shouldn't ligands be displayed with this preset ? (e.g 2DB3)

![Screen Shot 2020-05-27 at 10 27 06 AM](https://user-images.githubusercontent.com/39187756/83052904-ce51c480-a004-11ea-8d0b-6ae45450821d.png)

**Comment by arose** [comment]
I see, as far as I can tell this because the Symmetry Mates option shows chains (actually units) within 5 A of the untransformed model (1_555). It does show some ligands but not all.

**Comment by arose** [comment]
An option would be to additionally show all units that have the same auth_asym_id and same transform as units within 5 A of the untransformed model (1_555).

@dsehnal @JonStargaryen @bioinsilico what do you think?

**Comment by dsehnal** [comment]
How about adding an option (and perhaps making it default) to do the mates search on the "Model" instead of "unit" level?
