### ISSUE TITLE
How to solve TypeError: A.palette.params.list.colors map is not a function

### ISSUE THREAD

**Issue by FreedomClannad** [molstar/molstar#610]
Conditions of use

1. The demo of the viewer in the compiled build folder is tested.

2. Use nginx to forward the proxy to the viewer folder

Problems encountered

In the mode of using url path, see the figure below
url：https://files.rcsb.org/view/7KZC.pdb

![image](https://user-images.githubusercontent.com/34476893/200451961-353743d7-cab5-4474-8e14-63dadbd1396b.png)

Sometimes this problem occurs and cannot be displayed normally
![image](https://user-images.githubusercontent.com/34476893/200452092-4f3345ed-cb97-4a53-87c2-d27ac03478f6.png)

How to solve this problem

**Comment by dsehnal** [comment]
Have you been able to see this error on `https://molstar.org/viewer/`? I can't seem to reproduce this.

**Comment by dsehnal** [comment]
I think you will have to figure this one out on your own then. It might be a problem with the compilation process you are using.

**Comment by FreedomClannad** [comment]
Thank you. Let me try to solve this problem first
