### ISSUE TITLE
How to programmatically set the loaded SDF file highlighting？

### ISSUE THREAD

**Issue by webtop1** [molstar/molstar#614]
Hi
I have multiple sdf files loaded in my view, I know the entity name of the SDF, how can I set one of them to highlight based on the name? I tried using this example    [basic wrapper example](https://github.com/molstar/molstar/tree/master/src/examples/basic-wrapper)  ，but no , is there any other way? Thanks a lot!

**Comment by luna215** [comment]
Hi @webtop1, 

let me know if this example helps: https://github.com/molstar/molstar/discussions/570. It is an alternative to extracting the loci of a structure.

**Comment by webtop1** [comment]
> Hi @webtop1,
> 
> let me know if this example helps: #570. It is an alternative to extracting the loci of a structure.
Thank you very much. I tried it. It works!
