### ISSUE TITLE
Load the PDB file. How can I set the default display mode to Model ？

### ISSUE THREAD

**Issue by webtop1** [molstar/molstar#616]
Load the PDB file. How can I set the default display mode to Model when I find that I now load the file and then display it to Assembly
<img width="299" alt="image" src="https://user-images.githubusercontent.com/4414747/201246874-eba6906c-9a06-4008-a449-e2ff1293d768.png">

**Comment by luna215** [comment]
Hi @webtop1 , I think this might be what you're looking for: https://github.com/molstar/molstar/blob/524e6d4f814e48a2b0584f04dd751458a4db311f/src/apps/viewer/app.ts#L222-L229
