### ISSUE TITLE
How to update CustomStructureProperty value and have custom theme pick up changes

### ISSUE THREAD

**Issue by rmisiakexscientia** [molstar/molstar#622]
I'm working on trying to inject some dynamic data (i.e. I can't hardcode it) into a custom theme to use to colour atoms.

The approach I'm try to use is have a CustomStructureProperty and PluginBehavior, update the value in the provider as needed and read it in our custom theme

In a state action I call 
```ts
StructureColorPropertyProvider.set(
  structure,
  { pocket: params.extra.pocket },
    params.extra.pocket
);
```
where `params` is some data we get from react props, to set the value

However by this point the theme has already been run once and doesn't seem to get triggered again (as in the top level function does not run again)
I have to call 
```ts
plugin.dataTransaction(async () => {
  for (const s of plugin.managers.structure.hierarchy.current.structures) {
    await plugin.managers.structure.component.updateRepresentationsTheme(
      s.components,
      { color: CustomThemeProvider.name as any }
    );
  }
});
```
to make the theme refresh, which doesn't seem correct because it's re-applying the theme to every structure and it couples the behaviour to a single theme. Is there a better way of doing this?

**Comment by dsehnal** [comment]
You need to update the themes for every representation separately. You can do this in one go by using the state builder and by looking how the `component.updateRepresentationsTheme` is represented. Something like this:

```ts
const update = this.plugin.build();
for (const repr of reprs) {
  update.to(repr).update(createParams(...));
}
await update.commit();
```

**Comment by arose** [comment]
I think if you set the `contextHash` property in the theme https://github.com/molstar/molstar/blob/4764251241b1ce88106c75d2ff867cd7d95b02e3/src/mol-theme/color/secondary-structure.ts#L94 and provide the `ensureCustomProperties` in the theme provider https://github.com/molstar/molstar/blob/4764251241b1ce88106c75d2ff867cd7d95b02e3/src/mol-theme/color/secondary-structure.ts#L129-L132, then calling `CustomStructureProperty.set` should update the theme.

**Comment by rmisiakexscientia** [comment]
@arose I've been doing that and it has no effect, the theme never gets updated

**Comment by rmisiakexscientia** [comment]
Repo here
https://github.com/rmisiakexscientia/molstar-test
The molstar folder contains the bits of molstar code
https://github.com/rmisiakexscientia/molstar-test/tree/main/src/molstar
in molstar-wrapper.tsx I call set() on my provider but the theme function doesn't get called, I must be missing something obvious

**Comment by dsehnal** [comment]
You are assigning the property after you have created the representation.

This should help: 

```ts
  const preset = await plugin.builders.structure.hierarchy.applyPreset(
      trajectory,
      "default"
    );
  // ...
  await plugin.build().to(preset.representations.polymer).update({}).commit();
```

Another option is passing the properties directly to the theme as `PD.Value(..., { isHidden: true })`.

**Comment by rmisiakexscientia** [comment]
Calling that update method resets the representation to the default cartoon rather than using `PluginConfig.Structure.DefaultRepresentationPreset`, do I need to set something in the update() to make it use my custom provider/theme?

**Comment by dsehnal** [comment]
Right, sorry. You can try passing the existing params (`selector.cell?.transform.params`), or use an empty callback `.update(x => {})`. 

Also, the preset itself might be an overkill for your use case and you might just include the model/structure creation, assign the custom prop, and then create your representation.

**Comment by rmisiakexscientia** [comment]
That works, thanks for the help!

**Comment by rmisiakexscientia** [comment]
To update my last comment

The empty callback didn't do anything and just using the current params didn't do anything so I had to add a dummy property 
```
await plugin
    .build()
    .to(representation)
    .update({ ...representation.transform.params, extra: null /* needed to make it actually update */ })
    .commit();
```
is there a more elegant way of doing it?

**Comment by dsehnal** [comment]
The state tree was designed around the idea that the information needed is contained in the props of a node and it uses react-like state reconciliation to update what is rendered. That is why you need to pass the dummy prop.

What you were/are doing with your approach would be analogous to assigning the value returned by useState in react and expecting the component to re-render.

**Comment by rmisiakexscientia** [comment]
That makes sense, thanks again for the help
