### ISSUE TITLE
Issue opening ligand cif files from RCSB

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#625]
If I try to open in Molstar any one of the ligand Definition cif files that can be downloaded from RCSB, I always get an error
![image](https://user-images.githubusercontent.com/20627977/202687348-3a6e879e-e508-425c-a3c8-734ef585d057.png)

**Comment by dsehnal** [comment]
Mol* doesn't support loading the chem comp cif files yet.

One way to do this would be to detect the the `chem_comp_atom` category in the mmCIF parser and transform it into two different models for both `ideal` and `measured` (I think it's called like this) coordinates in the file. This could be done as a pre-step in the standard mmCIF parser before the "schema" is applied to it.

I think there has been an interest in this from other people as well. Maybe you can do a PR with it? :)

**Comment by arose** [comment]
@JonStargaryen @mandarsd maybe something wwPDB members want to do?

**Comment by JonStargaryen** [comment]
> maybe something wwPDB members want to do?

No immediate plans from our end, but I would love to see Mol* on Ligand Summary Pages. Might happen eventually.
