### ISSUE TITLE
repr.createOrUpdate() not updating the very first time after updating structure

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#627]
The first time I try to change representation parameters using `repr.createOrUpdate(params)` after the representation structure has been updated using `repr.createOrUpdate({},structureData)` the update doesn't work. To notice this in the Molstar app you can try for example to set tubular helices in cartoon representation.

**Comment by giagitom** [comment]
Any one noticed this too? 
Not all parameters are affected. For example enabling or disabling visuals seems to work

**Comment by arose** [comment]
Do you still see this issue? Do you have simple repro?

**Comment by giagitom** [comment]
Yes I still see the issue. To reproduce just load the default structure 1TQN and try to toggle Tubular Helices on Polymer component on cartoon representation. It shoudn't work the first time (next times it will work)

The same issue happens any time you try to modify a component by adding or removing atoms.

**Comment by arose** [comment]
Thanks, got it. I found and fixed an issue in the update logic of the polymer trace visual (e36fe8c707ef22975d5408c4d1188e80b892f891). Do you see the issue anywhere else?

**Comment by giagitom** [comment]
Great. At the moment I'm not seeing any other problems. If I'll find something else I'll report. By the way I noticed a different issue on sticks. When aromatic bonds are on, if I try to change Size Factor, aromatic bonds aren't reevaluated automatically. To make it work properly I have to manually toggle aromatic bonds each time I change the size factor.

**Comment by arose** [comment]
Right, another update issue, should be fixed in b2924761abddae9b3c652f76548fa2168ef62cbf

**Comment by giagitom** [comment]
Yes thanks, I confirm
