### ISSUE TITLE
Differences in opaque bg vs transparent bg rendering

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#628]
@arose I have found a few differences comparing a rendering with opaque bg and the same rendering with transparent bg. 
Assuming that the opaque rendering is the correct one, I have found this (potential) issues in transparent bg:
- transparency is too high (maybe It's normal?)
- there is a different color tone

In the image the transparent layer is just blended with a white layer using gimp. 
![image](https://user-images.githubusercontent.com/20627977/202772198-167c91b3-80e9-40f1-96c0-4daa6b2bc0e6.png)

**Comment by arose** [comment]
Hmm, I can't reproduce that. Here is what I get when paste an image with a opaque (white) background and one with a transparent background into google slides.

![image](https://user-images.githubusercontent.com/272250/202960321-9dcf372d-3fed-4ea7-beaa-706ed5518237.png)

**Comment by giagitom** [comment]
Sorry, this was a problem with Gimp using the wrong composite space by default.
