### ISSUE TITLE
Selecting residues by list?

### ISSUE THREAD

**Issue by mattjmeier** [molstar/molstar#629]
Hello,

Thanks for providing this excellent tool.

I am interested in selecting many amino acid residues in a model - but I can't seem to find a way to provide an arbitrary list (e.g., R21, A34, etc., in a plain text file or pasted in somehow) to make a large selection. Is this possible? Or can I suggest it as a possible feature to add? I would prefer not to risk doing this task manually since that could be pretty error prone and also tedious!

Thank you

**Comment by dsehnal** [comment]
Hi, 

- try having a look at the basic wrapper example.
- combining it with src/mol-script/util/id-list.ts should give you what you need.

**Comment by mattjmeier** [comment]
Thanks for the reply - I will look into this approach!

I still think it would be a useful feature to implement more broadly but I'll close the issue for now.

All the best!
