### ISSUE TITLE
Visualization of non-standard RNA residues in cartoon representation 

### ISSUE THREAD

**Issue by aspetr01** [molstar/molstar#630]
Mol* does not seem to display non-standard RNA residues in cartoon representations when an individual chain is loaded from the coordinated server at [https://coords.litemol.org/](https://coords.litemol.org/).

**Comment by arose** [comment]
This is because the coordinate server does not return the `_chem_comp.type` field which molstar uses to identify non-standard nucleotides.

@JonStargaryen @dsehnal can the server be changed to include the `_chem_comp.type` field?

**Comment by dsehnal** [comment]
Litemol.org is running an older version of the server. Is the same issue present in https://models.rcsb.org?

**Comment by JonStargaryen** [comment]
models.rcsb.org runs Mol* 3.8.2.

For [101d entity 1](https://models.rcsb.org/v1/101d/atoms?label_entity_id=1&encoding=cif&copy_all_categories=false), `chem_comp.type` is exported:
```
loop_
_chem_comp.formula
_chem_comp.formula_weight
_chem_comp.id
_chem_comp.mon_nstd_flag
_chem_comp.name
_chem_comp.type
_chem_comp.pdbx_synonyms
'C9 H13 Br N3 O7 P' 386.093 CBR n "5-BROMO-2'-DEOXY-CYTIDINE-5'-MONOPHOSPHATE" 'dna linking' ? 
'C10 H14 N5 O6 P' 331.222 DA y "2'-DEOXYADENOSINE-5'-MONOPHOSPHATE" 'dna linking' ? 
'C9 H14 N3 O7 P' 307.197 DC y "2'-DEOXYCYTIDINE-5'-MONOPHOSPHATE" 'dna linking' ? 
'C10 H14 N5 O7 P' 347.221 DG y "2'-DEOXYGUANOSINE-5'-MONOPHOSPHATE" 'dna linking' ? 
'C10 H15 N2 O8 P' 322.208 DT y "THYMIDINE-5'-MONOPHOSPHATE" 'dna linking' ? 
```

**Comment by arose** [comment]
@aspetr01 Do you still have the issue?

**Comment by aspetr01** [comment]
Thank you, Alex! The responses were helpful. The issue is closed.
