### ISSUE TITLE
Clipping Min near issue

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#632]
When setting Clip Min Near to a low value I observe a wrong overlapping between an opaque object and a transparent one behind it. Here is a test project [test-3.molj](https://github.com/molstar/molstar/files/10066616/test-3.molj.txt). Just tune Min Near to see the effect. 

Correct state  (0.7 min near)
![image](https://user-images.githubusercontent.com/20627977/203296321-4633a2e0-b72e-4496-8a0f-634db80a1c87.png)

Wrong state (0.1 min near)
![image](https://user-images.githubusercontent.com/20627977/203296821-b14278ef-ce30-4c03-88f5-972be4182690.png)

**Comment by arose** [comment]
Maybe a depth precision issue, not sure. Could you investigate? Or just keep minNear high enough?

**Comment by giagitom** [comment]
Of course, I can investigate further. 
So far I can tall that 
- there is no issue with orthographic camera 
- and that the issue shows up only when camera is close enough

**Comment by arose** [comment]
Thanks @giagitom 

Other observations
- the issue also exists for larger minNear values if the scene is large enough (e.g., HIV Blood)
- I don't see the issue with blended transparency

![image](https://user-images.githubusercontent.com/272250/204036197-2e82afaf-e251-4688-95b4-51386acf80b7.png)

**Comment by giagitom** [comment]
Thanks @arose, f428e9f39ebbe962d5e580bfe75dd6ed3a71b190 solved this issue
