### ISSUE TITLE
Fix building of /src/cli tools, need full lib as es5

### ISSUE THREAD

**Issue by arose** [molstar/molstar#64]
Fix building of /src/cli tools, need full lib as es5. Currently only cli tools that don't use any mol* modules work.

**Comment by dsehnal** [comment]
Should be fixed in 422f4567.
Use thru ``lib/commonjs``.

**Comment by arose** [comment]
and some more fixes in 208cc2e48e4a34b3655c9cd114790a293f19b7cb
