### ISSUE TITLE
Best way of getting color of residue/loci

### ISSUE THREAD

**Issue by ernst-schmid** [molstar/molstar#640]
I have a very basic question regarding colors in structure representations.

I'm looking for the best way to extract the color of a particular residue after a user hovers over a specific location on a structure. 

Thank you.

**Comment by dsehnal** [comment]
There isn't really an easy/basic way to do this. If this is really required, I think we would be able to figure something out, but in general the color assignment happens in a way which isn't easily observable.

What is the goal you are trying to achieve by getting the color? Maybe there is a different solution to your problem instead of getting the color.

**Comment by ernst-schmid** [comment]
I want to be able to set the color of other HTML elements on the page to the color of the residue/chain.

I guess I could extract the color from the palette assigned to the active theme and then use that? Not entirely sure how I would implement that either, but that's one path I can envision.

**Comment by dsehnal** [comment]
I see. And you want this to work for any theme the user selects?

**Comment by ernst-schmid** [comment]
Yes exactly. I just want to have a visual correspondence between what the user sees in the viewer and information outside of it.

Thats also what I was thinking. Along those lines, how do you extract the instance of a theme that a structure is actively using.

**Comment by ernst-schmid** [comment]
So I tried the small snippet below: 

```
this.plugin.behaviors.interaction.click.subscribe(ev => {
        molstar.Color.toRgb(ev.current.repr?.theme.color.color(ev.current.loci))
});
```

But I keep getting [250,250,250] for 2 differently colored chains which represents the default color rather than the actual color. What am I doing wrong in this case?

Thanks for all your help.

**Comment by dsehnal** [comment]
The theme takes `location` and not `Loci`. 

```ts
if (StructureElement.Loci.is(loci)) {
    return StructureElement.Loci.getFirstLocation(loci);
}
```

If you are calling this many times, it's good to create a single `StructureElement.Location` and pass it as the 2nd argument of the `getFirstLocation`

**Comment by ernst-schmid** [comment]
That works prefectly now thank you!
