### ISSUE TITLE
Ring in NAI is detected as aromatic

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#641]
C4N in [NAI](https://www.rcsb.org/ligand/NAI) is sp3 hybridized but Mol* marks the corresponding ring as aromatic (https://molstar.org/viewer/?load-pdb=1t2c). This is because all other criteria for aromaticity hold and the ring happens to be planar enough to pass the final planarity check.

![ring1](https://user-images.githubusercontent.com/9744615/204894108-5d848072-3a0a-4f07-ba27-0525234646dd.png)

![ring2](https://user-images.githubusercontent.com/9744615/204894131-fd3cde88-278b-4610-b12e-313b5125cfbe.png)

We could check whether a ring contains >0 double bonds and skip the planarity check if there's a carbon with only single bonds (however, that will fail for the cyclopentadienyl anion). Don't think there's a clean solution here without counting pi-electrons. What do you think?

**Comment by arose** [comment]
If `chem_comp_bonds` are included (which is not generally the case) in the mmcif file you can remove `computed` from the `includeTypes` param. An improvement could be to check in the repr getParams function if the source data of all models of a structure are of mmcif fromat and have the `chem_comp_bonds` category, then remove `computed` from the `includeTypes` param.

**Comment by JonStargaryen** [comment]
Ah, I see, knowledge of double bonds would also require presence of the `chem_comp_bond` category... But good to know that the inclusion of computed bonds can be toggled in the UI. Thanks!
