### ISSUE TITLE
Iterating through residues in protein and get computed properties (ASA)

### ISSUE THREAD

**Issue by ernst-schmid** [molstar/molstar#642]
Hi, 

I'd like to programmatically iterate through the residues within a chain to extract residue properties such as ASA without having to use or apply the coloring theme. I tried doing this by creating a custom property provider, but kept getting undefined values and wasn't able to figure how to do this correctly. 

Thanks for the assistance.

**Comment by dsehnal** [comment]
- Need to attach the property manually in this case with `AccessibleSurfaceAreaProvider.attach(ctx, structure)`.
  - To get the runtime for the `ctx` param, you can wrap your operation in a task `Task.create(async taskCtx => { runtime: taskCtx, assetManager: this.plugin.managers.asset })`; or you can use `RuntimeContext.Synchronous`.
- src\mol-plugin\behavior\dynamic\custom-props\computed\accessible-surface-area.ts has usage for ASA
- `Structure.eachAtomicHierarchyElement` helps with iterating over elements in the structure. You can look at its implementation if you want to do this manually or include some filtering

**Comment by ernst-schmid** [comment]
So first I ran this:

```
 molstar.Task.create('attach ASA', async ctx => {

          molstar.AccessibleSurfaceAreaProvider.attach(ctx, viewer.plugin.managers.structure.hierarchy.current.structures[0]);
 });
```

and then tried to retrieve the data afterwards using:
```
var asa_value = view.plugin.customStructureProperties.providers.get('molstar_accessible_surface_area').get(e.current.loci).value;
```

but I get an error stating that "Uncaught TypeError: Cannot use 'in' operator to search for 'molstar_accessible_surface_area' in undefined"

Thanks again for the help.

**Comment by dsehnal** [comment]
You need to run the task as well: task:

``task.run()`` to run it synchronously or ``this.plugin.runTask(task);`` to run it in the plugin's context.

**Comment by Marwa-Da** [comment]
Hi
I tried this code:
` const t = Task.create('attach ASA', async ctx => {
                    await AccessibleSurfaceAreaProvider.attach(ctx, this.plugin.managers.structure.hierarchy.current.structures[0].cell.obj?.data);
                });
this.plugin.runTask(t)`

 but it keeps showing this error: 
`Cannot read properties of undefined (reading 'isSynchronous')`

What should I do?

**Comment by Marwa-Da** [comment]
Well, I think this is it:
```
const t = Task.create('attach ASA',  async ctx => {
                    const runtime = ctx, assetManager = this.plugin.managers.asset;
                    debugger
                    await AccessibleSurfaceAreaProvider.attach({runtime, assetManager},
                        this.plugin.managers.structure.hierarchy.selection.structures[0].cell.obj?.data);
                });

```
It worked for me.
