### ISSUE TITLE
Cartoon nucleic bases not shown in some regions of entry ID 4V6X

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#646]
Just found this. 
![image](https://user-images.githubusercontent.com/20627977/205686759-495bdfd2-49d9-4b1f-a780-942e9b93c8b1.png)

**Comment by arose** [comment]
Looks like the bases are simply not resolved for those parts

![image](https://user-images.githubusercontent.com/272250/205824248-b9e10a02-24b7-45c3-a12b-5a77f4bcc848.png)

**Comment by giagitom** [comment]
Oh.. I see. thanks!
