### ISSUE TITLE
Can I use molstar with Next.js?

### ISSUE THREAD

**Issue by bisejdiu** [molstar/molstar#648]
I have a Next.js project, and I thought I can use MolStar, but when I try to import it, I get a `SyntaxError`. 

For example: 

```TypeScript
import { PluginContext } from 'molstar/lib/mol-plugin/context';

const Home: NextPage = () => {

  console.log(PluginContext)

  ...
  
 ```

Gives the following error: 
```sh
error - /home/bisejdiu/tests/test/node_modules/molstar/lib/mol-plugin/context.js:7
import { __awaiter, __generator } from "tslib";
^^^^^^

SyntaxError: Cannot use import statement outside a module
...
```

I'm learning as I go, so I thought the problem may be due to SSR, but the error does not seem to suggest this. I wrote a small plugin that works with React, but when I tried to migrate it to my Next.js app, I am getting the error above.

**Comment by dsehnal** [comment]
I have no idea if this will work and if nextjs automatically ships the required code to the frontend and allows the required effects to run. But try importing commonjs version of the lib from `molstar/lib/commonjs/...`.

**Comment by bisejdiu** [comment]
Very interesting! This, indeed, does seem to work, but not without issues. I can console `PluginContext` and it works fine, but when I import the component that renders my molstar plugin, I get the same error. The error appears only after refreshing the page (or re-running `next dev`). 

If I disable SSR: 

```TypeScript
// contains a plugin similar to the MolStarProteopediaWrapper 
const DynamicMolStar = dynamic(() => import('../components/molstar'), {
  ssr: false,
})
```

and render it like this: 
```TypeScript
<Suspense>
  <DynamicMolStar {...prop} />
</Suspense>
```

It does work as expected. However, I do not see a reason why SSR should not work. I found this [thread](https://github.com/vercel/next.js/issues/9890) where people have reported similar problems when using three.js. 

I should also note that I had to remove this line from the plugin: 
```TypeScript
require('molstar/lib/mol-plugin-ui/skin/light.scss');
```

Because next.js complains: 
```
error - ./node_modules/molstar/lib/mol-plugin-ui/skin/light.scss
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
```
But this is a different error, and currently not essential to me.

**Comment by dsehnal** [comment]
It doesn't work because both threejs and Mol* are not "static" HTML content and require a side effect on the client (=browser) to work. This working with SSR only would be equivalent to rendering the entire scene on the server instead of using the client CPU/GPU to do that.

----

Maybe you mix using the commonjs and non-commonjs imports and that's why you get the error.
