### ISSUE TITLE
Remove structure from Viewer

### ISSUE THREAD

**Issue by LivC182** [molstar/molstar#65]
I managed to generate all the features that I want but I found no function to remove loaded structures from the viewer. In the old NGL there was a removeAllComponents function but I cannot find one for molstar. Could you help ?

**Comment by arose** [comment]
`viewer.plugin.clear()`

**Comment by LivC182** [comment]
Thank you so much. I am trying to write a documentation for my lab could you point me towards the file where you define this function, could not find it where the class is defined ?
I searched here: https://github.com/molstar/molstar/blob/4171008c3f233c2215ccb5723a8f854f5b56ad23/src/apps/viewer/index.ts#L60 
and then here: molstar/src/mol-plugin/
maybe I missed it.

**Comment by arose** [comment]
You can have a look at https://github.com/molstar/molstar/blob/master/src/mol-plugin/context.ts. I find it is easiest to get around the source by installing an editor with typescript support and explore the source through it.

**Comment by LivC182** [comment]
@arose this is what I initially tried. I installed visual studio code, created a folder project. and ran the following commands:
```
npm install express
npm install molstar
```
they appear in pakage.json.
```
{
  "name": "trail",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "molstar": "^1.0.5"
  }
}

```
However, when I try to import molstar:
```
const express = require('express')
const app = express();

const molstar = require('molstar')
const viewer = molstar.Viewer()
```
I get this error 
```
liviu@support-System-Product-Name:~/Projects/trail$ node index.js 
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'molstar'
Require stack:
- /home/liviu/Projects/trail/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/liviu/Projects/trail/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/liviu/Projects/trail/index.js' ]
}
```

**Comment by arose** [comment]
I am afraid that you can not import the molstar viewer like this. The molstar package exports the whole library and you need to import individual modules like `import { Model, Structure, StructureSymmetry, QueryContext, StructureSelection } from 'molstar/lib/mol-model/structure';`
