### ISSUE TITLE
How to create a monomer from a complex protein?

### ISSUE THREAD

**Issue by Gigiux** [molstar/molstar#650]
Hello,
I am new to Mol*Viewer and docking in general.
I have a protein that is essentially a homotetramer. Is it possible to remove 3 out of 4 proteins so to focus on a single element?
Thank you

**Comment by dsehnal** [comment]
Yes, it is possible to render just one chain of a structure by creating a custom selection. Best way would probably be to write your own "representation preset" (or reuse the code from there) similar to https://github.com/molstar/molstar/blob/volume-quick-color/src/mol-plugin-state/builder/structure/representation-preset.ts#L157.
