### ISSUE TITLE
How to show binding bonds?

### ISSUE THREAD

**Issue by Gigiux** [molstar/molstar#651]
Hello,
I am new to Mol*Viewer. I have generated a docking model with SwissDock, how can I show the bond between the target molecule and the ligand?

Thank you

**Comment by dsehnal** [comment]
There is a docking viewer app https://github.com/molstar/molstar/blob/volume-quick-color/src/apps/docking-viewer/index.ts#L4 which you can use as a starting point.

**Comment by Gigiux** [comment]
Thank you!
