### ISSUE TITLE
Getting information from mol* frontend & interact with backend

### ISSUE THREAD

**Issue by projectssimm** [molstar/molstar#652]
Hi guys. Basicly, we want to build some web services based upon mol*, thanks for such an excellent tool!

As a rookie to mol*, here are 2 issues which we need some help...

1、Is there a proper way to get the information from the mol* module, e.g. the positions users clicked (fig.1), the molecule users focus on (fig. 2), etc., and send it to the backend server?(maybe some http url, maybe).
2、Say if we want to build a docking service, is there a way we could use some functions to show the gridbox for docking? (dotted lines to emphasize a gridbox area, maybe somewhere centered the molecule shown in fig.2).

Any suggestions would be appreciated, thanks.

<img width="642" alt="微信图片_20221212193759" src="https://user-images.githubusercontent.com/43559168/207037304-06ab5691-905b-4d94-b9c4-bca90a54d665.png">

<img width="716" alt="微信图片_20221212194736" src="https://user-images.githubusercontent.com/43559168/207037676-5132577b-a9f8-452d-99bc-cd1c717b05b3.png">

**Comment by dsehnal** [comment]
- For the interactions, you can have a look at `PluginContext.behaviors.interactions` to which you can subscribe and extract the info using `StructureProperties` after extracting the "location"
- Yes, you can do that by writing a custom visual which renders the box
