### ISSUE TITLE
Mol* cannot read co-crystal?

### ISSUE THREAD

**Issue by projectssimm** [molstar/molstar#653]
Hi guys, another issue here, can molstar read co-crystal files? I got an example of this but got no luck (fig below), the molecule cannot be read. However, some software like Schrödinger would get it.

So, is my way of using mol* not correct? Or mol* does not get read co-crystal data at this version now?

p.s. the co-crystal file is also attched if useful (txt format, truely should be pdb, which not allowed in github)

<img width="915" alt="微信图片_20221212200907" src="https://user-images.githubusercontent.com/43559168/207042847-84b7504b-ed15-409c-88b4-5414db243dfe.png">

[8322_6wew.txt](https://github.com/molstar/molstar/files/10207837/8322_6wew.txt)

**Comment by dsehnal** [comment]
I think you are referring to the ligand now being shown. This seems to be a bug in the component recognition. Renaming the residue UNK to MOL renders it:

![image](https://user-images.githubusercontent.com/21145776/208961304-ec9d84f0-6868-4fc5-945b-a8185080686c.png)

@arose any ideas about a fix for this?

**Comment by arose** [comment]
The PDB convention (from mmCIF) is as follows

> For ambiguous polymer components three-letter code should be given as 'UNK'.  Ambiguous ions are assigned the code 'UNX'. Ambiguous non-polymer components are assigned the code 'UNL'.

Unless we want to stop adhering to that, there is nothing we can do.
