### ISSUE TITLE
Custom clipping issue with impostors 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#654]
Clipping both impostor spheres / cylinders isn't the same than clipping mesh spheres / cylinders. Here a comparison with spheres.

 - Mesh spheres
![image](https://user-images.githubusercontent.com/20627977/207042327-ec0be05c-c6bd-4e65-a531-28cea14c4264.png)

- Impostor spheres
![image](https://user-images.githubusercontent.com/20627977/207042285-a032b15c-7e94-4c3a-8794-fc2ec7d6b33f.png)

**Comment by arose** [comment]
Yeah, that was not implemented. Added it with 309e3dd9812080d998d16c2bdfbdcf22f8fdb19e. Note that the sphere depth gets not clamped to the intersection because we use a signed distance for clipping and the intersection depth is not available. Feel free to look into adding adding if you like.
