### ISSUE TITLE
Wrong pLDDT display if label_seq_id and auth_seq_id do not match

### ISSUE THREAD

**Issue by gtauriello** [molstar/molstar#656]
I have observed that the per-residue pLDDT values do not get displayed correctly if label_seq_id and auth_seq_id do not match in the file. The pLDDT values stored in the `_ma_qa_metric_local` table are mapped to residues using `label_seq_id` (see [here](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_qa_metric_local.label_seq_id.html) for doc) and so it should be irrelevant whether or not there is a different `_atom_site.auth_seq_id` in the file. Yet this does not seem to be the case.

In the attached package ([molstar-issue-testfiles.zip](https://github.com/molstar/molstar/files/10210331/molstar-issue-testfiles.zip)), there are two example files which only differ by how `auth_seq_id` values were filled:

- `O00257-D2_Q6W2J9-D8_auth.cif` is the file I would like to be handled properly. The pLDDT values in the file correctly relate to the residue numbers given in `label_seq_id` but yet I only see correct pLDDT values for the few residues in chain A which happen to have identical numbers for `label_seq_id` and `auth_seq_id`
- `O00257-D2_Q6W2J9-D8_no_auth.cif` "fixes" the display problem by simply having all `auth_seq_id` numbers matching the `label_seq_id`

As I would like to use mol* to display `O00257-D2_Q6W2J9-D8_auth.cif` in ModelArchive (file will be deposited there in the next few days), I would be happy if this can be fixed soon. It sounds like a minor bug to me, but as I don't know the mol* code, I hope it's not a can of worms...

**Comment by dsehnal** [comment]
Hi, thanks for noticing this. The issue is a (tricky) misuse of a residue lookup function.
I will put out a fix soon.
