### ISSUE TITLE
Show/hide polar hydrogens

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#662]
Hello,

I'm wondering whether it would be possible to extend the 'Show Hydrogens' functionality (shown below)
![image](https://user-images.githubusercontent.com/84507154/207600331-55e23139-f6c7-4dcf-93d0-e3d6cbaa006c.png)

to add a sub-option to show only polar hydrogens (potential mockup of the UI below)
![image](https://user-images.githubusercontent.com/84507154/207600582-c479afa0-9be3-401e-a5ed-d66344288d17.png)

Is this something that might be a good contribution?

If so, I have a few questions about how to go about it. It looks like the place where the `ignoreHydrogens` checks are actually made are in `makeElementIgnoreTest` in [element.ts](https://github.com/molstar/molstar/blob/master/src/mol-repr/structure/visual/util/element.ts#L38) and `makeIntraBondIgnoreTest` in [bond.ts](https://github.com/molstar/molstar/blob/master/src/mol-repr/structure/visual/util/element.ts#L38). Are there any other places that would need to be considered?

In addition there is a function, `hasPolarNeighbour` in [functional-group.ts](https://github.com/molstar/molstar/blob/master/src/mol-model-props/computed/chemistry/functional-group.ts#L219) that seems like it is making the right checks (thought I cannot see it used anywhere), but in the above `...IgnoreTest` functions we do not have access to the `StructureElement.UnitIndex` but rather the `ElementIndex`. Is there any way to reconcile this to re-use this existing function?

Finally I feel I may struggle to make this a non-breaking change as it would require the representation parameters to be updated to include this setting to drill the value down to where it is needed.

Thank you in advance

**Comment by dsehnal** [comment]
This has come up before and was my TODO list, created https://github.com/molstar/molstar/pull/663 with it. If you can review and test this it would help @jpattle.

**Comment by jpattle** [comment]
That looks like it's on the right track, I'll continue discussion inside the PR and close this issue. Thanks
