### ISSUE TITLE
Programmatically Overpaint Range of Residues

### ISSUE THREAD

**Issue by spencel** [molstar/molstar#664]
Hi Team,

I'm really interested in Molstar and gaining a deeper understanding and hopefully being able to contribute someday. Unfortunately, I come from a python and pymol background and I'm having difficulty navigating and understanding the source code in lieu of documentation. As the subject hints, I'm yet another one who is trying to use the overpaint feature using the API. Below is what I'm trying to achieve via an API. I manually created 4 overpaint layers, each with a simple selection statement because I'm not well versed with mol-script either.

(sel.atom.res (in-range atom.resno 70 70))
(sel.atom.res (in-range atom.resno 75 86))
(sel.atom.res (in-range atom.resno 89 91))
(sel.atom.res (in-range atom.resno 94 95))
![image](https://user-images.githubusercontent.com/14222431/207752561-6588f3f4-6fd7-4f69-b710-bd6114c4a974.png)

Can anyone provide a demo of this? I'm not sure where to start after the `viewer.loadPdb("6yun");` statement.

Any help would be greatly appreciated.

Warmly,
Spencer

**Comment by spencel** [comment]
We're just trying to highlight an epitope. I could add it to the examples directory if it would help others too.

**Comment by spencel** [comment]
I've been tracing stuff and learning my way around the source code. And, I just now figured out how to find the Structure instances for passing to overpaint.
![image](https://user-images.githubusercontent.com/14222431/208202630-40337a7d-4643-4498-8d29-1fa015abd94c.png)

**Comment by dsehnal** [comment]
Hi Spencer,

as a start you might look at https://github.com/molstar/molstar/blob/dir-vol-add-histogram/src/mol-plugin-state/helpers/structure-overpaint.ts#L37-L38 combined with https://github.com/molstar/molstar/blob/dir-vol-add-histogram/src/examples/basic-wrapper/index.ts#L138 to get the loci.

Basically you want to your code to look like this:

```ts
const cell = ...; // plugin.state.data.selectQ or component manager or store ref when you create the visual
const loci = ...; // from the 2nd link
const bundle = StructureElement.Bundle.fromLoci(loci);
const params = ...; // from the 1st link
const update = plugin.build();
update
  .to(cell)
  .apply(OverpaintStructureRepresentation3DFromBundle, params);
await update.commit();
```

**Comment by spencel** [comment]
What is the selector syntax for plugin.state.data.selectQ?

**Comment by spencel** [comment]
I couldn't figure out how to get the selectQ method to work because I'm not sure how to build a selector for that. I'm still not sure what the best way to do this is.

What I ended up doing, so far, is manually finding the Cartoon Representation3D instance from the cells map and utilized OverpaintStructureRepresentation3DFromScript instead of bundling loci, I'm not sure why I ended up going this route at this time but it's what I got to working so far.

For this application, I simply took the Viewer app and repurposed it. I call the custom class method below from the index.html as `Viewer.highlightEpitope()`. In the future it will handle PDB ID and epitope range loci as arguments. There is more work to be done and I'm looking forward to sharing and contributing anyway I can. Thank you for the support.

```
async highlightEpitope() {

        // Get cell object
        // Get cells
        const cells = this.plugin.state.data.cells;
        // Get key of map entry by index
        const cartoonKey = Array.from(cells.keys())[11];
        // Get cell
        const cell = cells.get(cartoonKey);

        // Set script language
        const language = 'mol-script';

        // Set epitope range loci
        const ranges = [
            [70, 70],
            [75, 86],
            [89, 91],
            [94, 95]
        ];

        // Create params object
        const params = {
            layers: []
        };
        // Add layers to params object
        for (let i = 0; i < ranges.length; i++) {
            const range = ranges[i];
            const start = range[0];
            const stop = range[1];
            params.layers.push({
                script: Script(
                    `(sel.atom.res (in-range atom.resno ${start} ${stop}))`,
                    language
                ),
                color: ColorNames.blueviolet,
                clear: false
            });
        }

        // Apply overpaint to epitope
        update.to(cell).apply(
            OverpaintStructureRepresentation3DFromScript,
            params);
        await update.commit();

    }
```

**Comment by dsehnal** [comment]
The selectors are similar to "jQuery for the state tree". Some examples:

```ts
const myCell = plugin.state.data.selectQ(q => q.byRef(cartoonRef))[0];
        const allRepresentations = plugin.state.data.selectQ(q => q.ofType(PluginStateObject.Molecule.Structure.Representation3D));
        const allSuper = plugin.state.data.selectQ(q => q.byRef(cartoonRef).subtree().withTag('my-super-tag'));
```

**Comment by spencel** [comment]
Sorry I'm getting back to this late. Thank you for the query examples. I was able to implement a solution, which I used to highlight the epitope on the SARS CoV-2 S protein for the ACE2 receptor. My next goal is to change representation of the protein subunits to molecular surface and with uniform color.

`for (let i = 0; i < lociList.length; i++) {
            const loci = lociList[i];
            const start = loci[0];
            const stop = loci[1];
            // @ts-ignore
            params.layers.push({
                script: Script(
                    `(sel.atom.res (in-range atom.resno ${start} ${stop}))`,
                    language
                ),
                color: ColorNames.blueviolet,
                clear: false
            });
        }

        // Apply overpaint to epitope
        const update = this.plugin.build();
        // @ts-ignore
        update.to(cartoonCell).apply(OverpaintStructureRepresentation3DFromScript, params);
        await update.commit();`

![image](https://user-images.githubusercontent.com/14222431/217935595-502e9d88-a637-45c6-a331-6cf7e8670c6d.png)
