### ISSUE TITLE
Side by side view of multiple structures

### ISSUE THREAD

**Issue by llambourne** [molstar/molstar#670]
Is there a way to view multiple structures side-by-side? I'm looking for something equivalent to [grid mode in pymol](https://pymolwiki.org/index.php/Grid_mode), where I could show several different isoforms of the same protein next to each other.

**Comment by dsehnal** [comment]
Yes, it is possible to achieve this. The drawback is that this isn't supported "out of the box" and currently requires quite a bit of work to set up.

A way to do is
to manage the canvas and plug-in contexts by hand and use different "viewports" for each of the Canvas3D instances which will end up sharing one HTML Canvas. This approach was used in https://www.entos.ai/envision for example.

**Comment by llambourne** [comment]
ok, I think that's a bit too much work for my needs and skill level. But thanks anyway!
