### ISSUE TITLE
dropFiles bug?

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#679]
hi, 

I was looking at the `src/mol-plugin-ui/plugin.tsx` file and noticed that there might be a bug [here](https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/plugin.tsx#L111). I believe we're supposed to grab the file at a certain index in each iteration instead of always grabbing the file at position 0

**Comment by dsehnal** [comment]
Nice spot, fixed it.

**Comment by luna215** [comment]
Fixed here: [3d83211](https://github.com/molstar/molstar/commit/3d83211503eaf5a90aec2a5c863316bd7e8196d3)
