### ISSUE TITLE
Getting info about user's selection

### ISSUE THREAD

**Issue by nikit00000s** [molstar/molstar#681]
Hello everyone, 

Firstly, I'd like to express my gratitude for providing community with such useful tool.
However, recently I had some problems with documentation: sadly, it's written quite poorly. I'm making a simple Angular application for calculation of dihedral angles and drawing a Ramachandran plot of any PDB entry. I would like to use Mol* to provide user with opportunity to select specific parts of protein for my application to draw it's Ramachandran plot. Yet I can't find out how am I supposed to obtain user's selection from plugin (list of residues: positions, names, etc...). Ideally, it would be a subscription to some observable with information about selection. But for now I only understood how to get information about simple user interaction (`PluginUIContext.behaviors.interaction.click`). Perhaps, this is the key to my problem.

I would be very grateful for anyone solving this problem!

**Comment by dsehnal** [comment]
Hi Nikita,

You can check `src/mol-plugin-state/manager/structure/selection.ts` (accessible through `plugin.managers.structure.selection`). You will likely still need to do some other transforms to the data or even have your own version of the selection manager which meets your needs.

David
