### ISSUE TITLE
How do I delete a line object？

### ISSUE THREAD

**Issue by webtop1** [molstar/molstar#682]
I draw multiple line objects in the following way. When mouseover, how can I get the line I drew? I want to delete in mouseover
<img width="821" alt="image" src="https://user-images.githubusercontent.com/4414747/209906256-6f4562d8-5a6d-4be0-8ac5-c072575dc03d.png">

**Comment by dsehnal** [comment]
The last argument the of `linesBuilder.add` is the "group" which you can use to identify which line use user interacted with. Depending on how many lines you want to draw you should either represent each line as a separate representation (and just call `canvas3d.remove`), or you will have to update/rebuild the old representation if you choose to put "everything in one" as separate lines the representation are not "objects" but rather values in a buffer.

An alternative might be to set 100% transparency on the lines you want to hide (I think you can do this with `repr.setState` function).

**Comment by webtop1** [comment]
Thank you very much!
