### ISSUE TITLE
Retrieve the atoms that have interactions

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#684]
Hi!

I add the `InteractionsRepresentationProvider` to display the non-covalent bonds here. I want to retrieve the a and b cell between these interactions. Is there a query that allows me to do this?
What I ultimately want to do is add some sort of highlight or custom shape around the the atoms that have the potential to have a non-covalent bond. 

I don't understand where the calculation is happening for these interactions. I stumbled into this [function](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/manager/structure/measurement.ts#L97) which would tell me the a and b atoms for these interactions, but I don't think it's used for the `InteractionsRepresentationProvider`. Any help here would be appreciated!

**Comment by arose** [comment]
> What I ultimately want to do is add some sort of highlight or custom shape around the the atoms that have the potential to have a non-covalent bond.

I would probably create a representation for that that is similar to the existing interactions representation. To prototype you could add an extra visual to the interactions representation.

**Comment by arose** [comment]
@luna215 anything you plan to do here?

**Comment by luna215** [comment]
@arose I needed this because I wanted to add my own bond interactions between phantom atoms and I was able to create custom bond visuals for this to draw the shapes of the atoms (sphere mesh) and the bonds (dashed cylinder mesh).
