### ISSUE TITLE
How to get the coordinates data of the original SDF file based on location?

### ISSUE THREAD

**Issue by webtop1** [molstar/molstar#690]
In selection mode, I can get the loci in the following way:

const loci = this.plugin.managers.structure.selection.additionsHistory;

How to get the coordinates data of the original SDF file based on location?

Thank you very much .

**Comment by dsehnal** [comment]
- `StructureProperties.atom.sourceIndex` to get the original atom index
  - need to convert the loci to a location for this; `Loci.getFirstLocation` should be enough.
- then look at the `Strcuture.model.sourceData` (going from top of my head, could be slightly different) which will contain raw parse of the input sdf file (should do something like `SDFFormat.is` on the value

------

If you want just the current coordinates of the atom `StructureProperties.atom.x/y/z` will work.
