### ISSUE TITLE
Using browser zoom makes canvas look blurry and also affects the axis helper size

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#691]
I have noticed this. It affects also the axis helper size when I refresh the page while having a non default zoom level
![image](https://user-images.githubusercontent.com/20627977/211121923-af69bb2d-078e-473a-8ae7-522c26d5bdc9.png)

**Comment by arose** [comment]
There was an issue with the devicePixelRatio that got fixed in 8e1876fc25c219d26b6c9e85a543e7ade324d434. Does that fix your issue?

**Comment by giagitom** [comment]
Yes thanks, I no longer see the blur effect. The axis size is related to the zoom factor though. It does not keep  the same size upon zooming in / out. Is this intentional?
 
![image](https://user-images.githubusercontent.com/20627977/218280820-00f58691-ee6b-4e2f-ac92-aba2fca084a2.png)

**Comment by arose** [comment]
Yeah, it is intentional. The rational is that it is an UI element and should get larger like the other browser UI elements. If you want a different behavior, feel free to do a PR.

**Comment by giagitom** [comment]
I understand now. Thanks, It looks good to me.

**Comment by giagitom** [comment]
@arose, I have found something else related. It seems that outlines aren't working on low zoom levels (>= 33% for me)

**Comment by arose** [comment]
Seems fine for me

![image](https://user-images.githubusercontent.com/272250/225230490-28e48175-0f13-4db3-a73f-78d12b2184e8.png)

![image](https://user-images.githubusercontent.com/272250/225230727-31cd8a61-2ccb-4776-a0d2-69be7160af47.png)

**Comment by giagitom** [comment]
Oh.. sorry I mean the marking outlines.

**Comment by arose** [comment]
right, handled with e636397f90106d78f4e354e52a40237171a5fa87 in the same way lines and points are handled

**Comment by giagitom** [comment]
Great,
I also noticed that increasing zoom leads to a blurry image (with wireframe but also with normal meshes) and increases marking outlines size. Instead normal outlines are perfect in any case and are never influenced by zoom levels.

![image](https://user-images.githubusercontent.com/20627977/225550375-e9752907-ccbc-4a7a-aaa9-fc790509d1ea.png)
![image](https://user-images.githubusercontent.com/20627977/225552079-05eb6b82-7b2d-440a-b007-e51528b6c097.png)


![image](https://user-images.githubusercontent.com/20627977/225552624-01a65b98-c90e-4f88-b105-001aa3bd74cd.png)

**Comment by arose** [comment]
That all looks like intended to me. The whole devicePixelRatio adjustment is for high dpi screens and you will see the above issues on extreme browser zooms. The blurriness you see is from SSAO running at a lower resolution when devicePixelRatio > 1 to improve performance.

**Comment by arose** [comment]
https://github.com/molstar/molstar/blob/e636397f90106d78f4e354e52a40237171a5fa87/src/mol-canvas3d/passes/postprocessing.ts#L414

we could change that something like

```ts
return Math.min(1, 1.25 / this.webgl.pixelRatio) * this.downsampleFactor;
```

but would need to do some performance tests on one of those underspec'd laptops with a weak gpu and a high dpi display

**Comment by giagitom** [comment]
Oh.. if this is done for performances reasons this looks good to me.. Maybe it would be nice to disable the downsampling while taking snapshots or making videos?

**Comment by arose** [comment]
> Maybe it would be nice to disable the downsampling while taking snapshots or making videos?

good point, we can use the `resolutionScale` parameter for that, done in 5dbca41da6e4957650e974dbd78ecd1c65133846

**Comment by giagitom** [comment]
Awesome! Thanks!
