### ISSUE TITLE
Data security issues

### ISSUE THREAD

**Issue by Fx-Ren** [molstar/molstar#696]
First of all, thanks so much for providing such a powerful and convenient tool.

I found there is a 'Remote States' Panel in the left main menu during using Mol* tool. ( As shown in the following figure )
![image](https://user-images.githubusercontent.com/17877321/212624558-445a11c6-4480-487d-a58b-b1ec64b91440.png)

So, my question is whether the mol* server collects local data of the user when I open the local molecule file and visualize it?
If yes, is there an off switch?

Thanks again!

@arose 
@sukolsak

**Comment by russellp17** [comment]
I can't comment on the server, but you can disable the "Remote States" panel with the `layoutShowRemoteState` option when creating a viewer instance: https://github.com/molstar/molstar/blob/e9c36c237528b4e5c7a7825715aa00c83e74075b/src/apps/viewer/app.ts#L159

**Comment by dsehnal** [comment]
Also, you have to explicitly upload the data to the server. There is nothing shared/saved by default.

There is some more info here https://github.com/molstar/molstar/issues/591
