### ISSUE TITLE
Is Molstar more or less efficient than NGL?

### ISSUE THREAD

**Issue by d-beltran** [molstar/molstar#697]
Hi everyone,

I'm implementing Molstar in our web server which is meant for full atomistic trajectories and where we were using NGL until now.
I just made a custom parser and loaded the simulation as explained [here](https://github.com/molstar/molstar/issues/282#issuecomment-964470116). Everything seems to work fine but when the animation is playing (with the default representation) the performance has fallen compared to NGL.

Does it mean I am doing something wrong? Or is this normal? Is there any trick to make Molstar lighter when iterating frames? Efficiency is critical for us since we have to deal with [huge structures](https://bioexcel-cv19-dev.bsc.es/#/browse/61e82ae5f29ec329a4d6edd2/trajectory) with more than 300k atoms.

Regards

**Comment by dsehnal** [comment]
It might be that the default representation in Mol* is slower, but tweaking how you display your system should improve the performance.

**Comment by d-beltran** [comment]
I reached a performance comparable to NGL by playing with the typeParams.quality value.
Options are custom, auto, highest, higher, high, medium, low, lower and lowest. You can lower the quality much and the visual impact is not dramatic to my inexpert eye. I picked the 'lower' option, since the difference when you choose the 'lowest' is remarkable.

```javascript
(...)
const structure = await plugin.builders.structure.createStructure(model);
const components = plugin.build().to(structure);
const lightRepresentation = createStructureRepresentationParams(plugin, void 0, {
       type: 'cartoon',
       typeParams: {
            quality: 'lower',
            ignoreHydrogens: 'all',
            ignoreHydrogensVariant: 'all',
            ignoreLight: true,
       }
});
components.apply(StateTransforms.Representation.StructureRepresentation3D, lightRepresentation);
await components.commit();`
