### ISSUE TITLE
'undefined' in sequence tab

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#70]
The sequence tab will report `undefined` for HETATMs. See example for 1brr, first label_comp_id is PCA.

<img width="495" alt="undefined" src="https://user-images.githubusercontent.com/9744615/84820988-480b1b80-afcf-11ea-9651-c188935511b4.png">

Iirc, it worked previously. Now
https://github.com/molstar/molstar/blob/f6acf0a60aa602418b63a79b02e0b9bf7a7b922c/src/mol-plugin-ui/sequence/polymer.ts#L30 
will return the string `'undefined'`. Might be some other underlying issue, otherwise I can also prepare a simple PR.

**Comment by arose** [comment]
Definitely a bug.

**Comment by arose** [comment]
Should be fixed now, was using the wrong index variable... after a recent refactoring
