### ISSUE TITLE
Set default color theme when creating new components

### ISSUE THREAD

**Issue by arussell123** [molstar/molstar#703]
Hi,

We have created a custom color theme and we would like to set it as the default color theme for any new components created y the user (i.e. made using the `+Add` button).

As far as I can see from the code this isn't currently possible - would it be possible to add a default color theme to the config which can be used instead of the individual provider defaults if it is set?
Alternatively it would work to add a `color` param to the `add` method in the `StructureComponentManager` so when this is called in by the add button we can pass through our color theme.

Thank you in advance!

**Comment by dsehnal** [comment]
Hi,

you should be able to that now. A bit hacky, but should do the trick:

```ts
this.plugin.representation.structure.registry.list.forEach(({ provider }) => {
  (provider.defaultColorTheme as any) = ...;
});
```

**Comment by arussell123** [comment]
Ah I hadn't thought to try that. That does what we want, thanks!
