### ISSUE TITLE
How to set the highlighted state based on the side chain name or index?

### ISSUE THREAD

**Issue by webtop1** [molstar/molstar#704]
How to set the highlighted state based on the side chain name or index,I can't do it the following way：
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/4414747/215641524-43e9480b-9071-480f-80a2-6e35820667d4.png">
Thank you very much for your guidance

**Comment by dsehnal** [comment]
Maybe you have "auth" coordinates and should use `auth_seq_id` instead?

**Comment by webtop1** [comment]
> Maybe you have "auth" coordinates and should use `auth_seq_id` instead?

I tried.  but the result was wrong. I couldn't get the object I needed


`
 sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
					"chain-test": Q.core.rel.eq([Q.struct.atomProperty.macromolecular.auth_seq_id, chain_name]),
					"residue-test": Q.core.rel.eq([Q.struct.atomProperty.macromolecular.label_seq_id(), seq_id]),
					"group-by": Q.struct.atomProperty.macromolecular.chainKey()
				}), data);
`

**Comment by webtop1** [comment]
I changed to the following mode, can run normally

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4414747/216940076-6829ac8a-d190-4abe-9b4e-95543f2587d9.png">

However ,it was found that atom-test was not working properly.

**Comment by arose** [comment]
@webtop1 is this solved for you?
