### ISSUE TITLE
How to render cif like VESTA?

### ISSUE THREAD

**Issue by jump2cn** [molstar/molstar#706]
Hi everyone,

I have a cif file, and it render in molstar viewer as two single ball , but actual it will be a bulk struct with box line.

> \# generated using pymatgen
> data_TiO2
> _symmetry_space_group_name_H-M   P4_2/mnm
> _cell_length_a   4.65327200
> _cell_length_b   4.65327200
> _cell_length_c   2.96920300
> _cell_angle_alpha   90.00000000
> _cell_angle_beta   90.00000000
> _cell_angle_gamma   90.00000000
> _symmetry_Int_Tables_number   136
> _chemical_formula_structural   TiO2
> _chemical_formula_sum   'Ti2 O4'
> _cell_volume   64.29197532
> _cell_formula_units_Z   2
> loop_
>  _symmetry_equiv_pos_site_id
>  _symmetry_equiv_pos_as_xyz
>   1  'x, y, z'
>   2  '-x, -y, -z'
>   3  '-y+1/2, x+1/2, z+1/2'
>   4  'y+1/2, -x+1/2, -z+1/2'
>   5  '-x, -y, z'
>   6  'x, y, -z'
>   7  'y+1/2, -x+1/2, z+1/2'
>   8  '-y+1/2, x+1/2, -z+1/2'
>   9  'x+1/2, -y+1/2, -z+1/2'
>   10  '-x+1/2, y+1/2, z+1/2'
>   11  '-y, -x, -z'
>   12  'y, x, z'
>   13  '-x+1/2, y+1/2, -z+1/2'
>   14  'x+1/2, -y+1/2, z+1/2'
>   15  'y, x, -z'
>   16  '-y, -x, z'
> loop_
>  _atom_type_symbol
>  _atom_type_oxidation_number
>   Ti4+  4.0
>   O2-  -2.0
> loop_
>  _atom_site_type_symbol
>  _atom_site_label
>  _atom_site_symmetry_multiplicity
>  _atom_site_fract_x
>  _atom_site_fract_y
>  _atom_site_fract_z
>  _atom_site_occupancy
>   Ti4+  Ti0  2  0.00000000  0.00000000  0.00000000  1
>   O2-  O1  4  0.19542000  0.80458000  0.50000000  1

**in molstar viewer**

![render in molstar viewer](https://user-images.githubusercontent.com/1173757/215976772-2b432095-cfe2-431d-bd08-a73610355caa.png)

**in VESTA**

![render in VESTA](https://user-images.githubusercontent.com/1173757/215976512-035709df-cbc2-4cad-9091-a9bf1cc30098.png)

so, is there any way to render it like what it will be in VESTA? it's better have a way to control by typescript.😊

 Thanks all.💡

**Comment by dsehnal** [comment]
You have to select to display symmetry mates explicitly: 

![image](https://user-images.githubusercontent.com/21145776/216848308-d8eabee7-2364-43c3-8a9d-2c50630237d2.png)

**Comment by jump2cn** [comment]
Thank you @dsehnal 🥂 it's helpful..!

And I have another two question about how to options render style.
1. In VESTA, model can be render like 'Ball-and-stick' + 'cell polyhedral'. Is there any representation component in mol* will render like this?
> ![image](https://user-images.githubusercontent.com/1173757/220496595-47070169-a1b1-4a88-9d47-a7c24bc3a553.png)

2. when I use 'symmetry' type to render cif file in mol*,  there have '*dashCount*' property to control inter-bond style in "ball-and-stick" representation, and the avaleable value range are [2,4, 6, 8, 10] , it seems an undisable feather.  but I want to get take it look like 'intra-bond'
