### ISSUE TITLE
[docking-viewer] Is it possible to get count of interactions?

### ISSUE THREAD

**Issue by xuzuodong** [molstar/molstar#707]
`docking-viewer` app shows the way to render interactions, while I want to go further and get **interaction count** between ligand and protein. 

After trying to add codes below to after [line 204 of this file](https://github.com/molstar/molstar/blob/master/src/apps/docking-viewer/viewport.tsx#L204): 

``` ts
// `apply` function in `InteractionsPreset` provider
const ctx = { runtime: SyncRuntimeContext, assetManager: new AssetManager() }
const interactionsParams = ... // my custom interaction params

await InteractionsProvider.attach(ctx, structure, interactionsParams)
const interactions = InteractionsProvider.get(structure).value!

console.log(interactions)
```

here's result: 

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/51878637/215981184-2f7282c6-bdc5-496c-9e52-60ef44d39bb5.png">

I thought `interactions.cantacts.edgeCount` represents interaction count, but the value doesn't equal to count of dash cylinder rendered in canvas.

Only 5 interactions can be found in this example, while `interactions.cantacts.edgeCount` is `14`. 

How to get the correct value? 

(complete modification: https://github.com/xuzuodong/molstar/commit/14362d8dd522aed390137867cdc31426bfe5d6c2#diff-06730aba7eb90d7293a543947c33d1d297dbacf9e2a6f7758a39ac2c1bf8c18a)

**Comment by dsehnal** [comment]
This is because the interactions are filtered before displayed. You might have to copy-paste some code since the functions are not exported, but [here](https://github.com/molstar/molstar/blob/445977d99bcb6d77e96e139266d440923a1a28d1/src/mol-model-props/computed/representations/interactions-inter-unit-cylinder.ts#L254) is a way to iterate over the interactions and [here](https://github.com/molstar/molstar/blob/445977d99bcb6d77e96e139266d440923a1a28d1/src/mol-model-props/computed/interactions/interactions.ts#L88) a way to turn it into a label.

You should be able to write your count function based on this.

**Comment by xuzuodong** [comment]
@dsehnal 

Thanks for pointing out the way to iterate over interactions and get their label! But currently I still get stuck on how to **filter interactions correctly**. 

I wanted to utilize [this ignore function](https://github.com/molstar/molstar/blob/445977d99bcb6d77e96e139266d440923a1a28d1/src/mol-model-props/computed/representations/interactions-inter-unit-cylinder.ts#L70), but roughly copying this function gives wrong result: 

``` ts
function ignore(edgeIndex) {...} // roughly copied from `interactions-inter-unit-cylinder.ts`

const validEdges = []

for (let edgeIndex = 0, _eI = interactions.contacts.edgeCount; edgeIndex < _eI; ++edgeIndex) {
    if (!ignore(edgeIndex)) {
        validEdges.push(interactions.contacts.edges[edgeIndex])
    }
}
```
since [the structure variable](https://github.com/molstar/molstar/blob/445977d99bcb6d77e96e139266d440923a1a28d1/src/mol-model-props/computed/representations/interactions-inter-unit-cylinder.ts#L40) doesn't seem to be the same as [the one I used here](https://github.com/molstar/molstar/blob/445977d99b/src/apps/docking-viewer/viewport.tsx#L202). 

How should I continue?
