### ISSUE TITLE
Bond breaking/forming is no longer happening

### ISSUE THREAD

**Issue by hekima31** [molstar/molstar#709]
Hi, I recently noticed that my trajectory files don't show bond breaking/forming. Instead bonds stretch unreasonably (See screenshot of XYZ file)
![image](https://user-images.githubusercontent.com/55980431/216447178-54f07c60-54f3-4a12-bf7f-c32b563a43c8.png)

**Comment by arose** [comment]
did you set dynamicBonds to true?

**Comment by hekima31** [comment]
Do you mind showing me where this setting is? I can't seem to find it

**Comment by hekima31** [comment]
> Do you mind showing me where this setting is? I can't seem to find it

Found it and this works. Thanks very much.
