### ISSUE TITLE
To embed snapshot file into a mediawiki page

### ISSUE THREAD

**Issue by WentaoXu22** [molstar/molstar#711]
Hi, I tried to embed a snapshot file "test_snapshot.molx" in to a mediawiki page by using lines shown here, but it doesn't work. How should I embed structure snapshot? Please give me some suggestions on solving this problem. Thank you!

<html>
    <style>
        .molstar {
            position: relative;
            width: 100%;
            padding-bottom: 56.25%;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="https://molstar.org/viewer/molstar.css" />
    <script type="text/javascript" src="https://molstar.org/viewer/molstar.js"></script>

    <div id="viewer-1" class="molstar" style="padding-bottom: 40%;"></div>
    <script type="text/javascript">
        molstar.Viewer.create('viewer-1', {
            layoutIsExpanded: false,
            layoutShowControls: false,
            layoutShowRemoteState: false,
            layoutShowSequence: true,
            layoutShowLog: false,
            layoutShowLeftPanel: true,

            viewportShowExpand: true,
            viewportShowSelectionMode: false,
            viewportShowAnimation: false,
        }).then(viewer => {
            viewer.loadStructureFromUrl('../test_snapshot.molx', 'molx');
        });
    </script>
</html>

**Comment by dsehnal** [comment]
Hi, there is a `loadSnapshotFromUrl` method, you are using "structure" version.

**Comment by WentaoXu22** [comment]
> Hi, there is a `loadSnapshotFromUrl` method, you are using "structure" version.

Thanks for your helping! Where can I find these methods? I only can find the document for how to use molstar viewer.

**Comment by dsehnal** [comment]
Generally, you would get this method as code completion in something like VS Code. The caveat is that this doesn't work with inlined code like you used.

This particular method is here https://github.com/molstar/molstar/blob/master/src/apps/viewer/app.ts#L208
