### ISSUE TITLE
How to run examples

### ISSUE THREAD

**Issue by ArnNag** [molstar/molstar#713]
I'm trying to use molstar/lib/examples/basic-wrapper/index.html to display static superpositions, but index.js fails with `SyntaxError: import declarations may only appear at top level of a module.` I switched the type attribute in the script tag to "module," but this still fails with `Uncaught TypeError: The specifier “tslib” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.` Do I need to change all tslib imports to relative references to the location of tslib in my node_modules directory? Is there another way I'm supposed to run npm build so that it recognizes the reference to tslib when I run the basic wrapper as a module?

**Comment by dsehnal** [comment]
```
npm install
npm run build
```

in the root dir and and go to ``build/examples`` folder.

After the initial build can also use ``npm run watch`` (or `watch-viewer`` if developing just that for better performance) for interactive updates (still needs manual browser refresh).

**Comment by ArnNag** [comment]
Thanks. The problem was that I was running `lib/examples`.
