### ISSUE TITLE
ERROR in /lib/mol-util/data-source.js with version >3.30

### ISSUE THREAD

**Issue by gustavo-salazar** [molstar/molstar#716]
Hey there,

I use molstar from the npm package and just got an issue while doing some dependencies updates for my project.

Using version `3.30.0` everything works and I can build my app with no issue, but `3.31.[0,1,2]` throws this error:

```
ERROR in ./node_modules/molstar/lib/mol-util/data-source.js 346:10-23
Module not found: Error: Can't resolve 'fs' in '/Users/gsalazar/projects/client/node_modules/molstar/lib/mol-util'

module (webpack 5.75.0) compiled with 1 error in 72702 ms
```
Do you know of any changes I'd need to do to build this version, did I miss anything in the CHANGELOG?

Cheers,

Gustavo

**Comment by mah51** [comment]
I am also having this issue.

**Comment by dsehnal** [comment]
Is this with using `create-react-app` or something similar? We've added a dynamic `require('fs')`  import to the `data-source.js` to enable some nodejs functionality.

**Comment by dsehnal** [comment]
- I've updated the import in `data-source.ts` in 3.31.3 so it should no longer cause trouble 
- Another solution which works using is webpack fallbacks (e.g. `fs: false`)
  - For create-react-app: https://web3auth.io/docs/troubleshooting/webpack-issues (e.g. `fs: false`)
  - Generally in webpack documentation

**Comment by eapearson** [comment]
The issue is still present for me with 3.31.3 and 3.31.4, with CRA and TypeScript. 3.30.0 is fine so far.

**Comment by dsehnal** [comment]
@eapearson are you including the `Viewer` class?

The mp4 export dependency references some node modules like fs or crypto too and the it is required to use the above workaround.

**Comment by gustavo-salazar** [comment]
Hey @dsehnal Thanks a lot for looking into this. 
I just tried `molstar@3.31.4` and I'm still getting the same error. I'll play a bit with your suggestion of the webpack config and will report back here.

BTW, my environment wasn't building CRA, but I'm indeed using webpack for bundling.

**Comment by gustavo-salazar** [comment]
Cool! the webpack fallback workaround works on my setup.

It's not ideal to have to add exceptions there for a single dependency, but at least it compiles and runs! 

Thanks so much for your help. If you release another version that doesn't require the workaround please post it here. I'd be happy to try it out and report back.

Cheers!

**Comment by dsehnal** [comment]
I tested the plug-in context instance build with CRA for the .3 version and the workaround worked there, but it is true the viewer complains. It's weird tho this error only appeared after the changes to the data source file. If you find a better workaround please make a PR.

**Comment by elliothershberg** [comment]
I want to note that I've also run into this issue as well.

When using the molstar viewer in NextJS, I had to update my Webpack config with the following:

```js
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  webpack(config) {
    config.resolve.fallback = {
      ...config.resolve.fallback,
      fs: false,
    };

    return config;
  },
};
```

When I was working on the [JBrowse](https://github.com/GMOD/jbrowse-components/) team, we also ran into a similar issue. Linking the issue [here](https://github.com/GMOD/jbrowse-components/issues/2244) for reference.
