### ISSUE TITLE
How to set specific residues to certain colors / gradient colors based on the PDB B-factors

### ISSUE THREAD

**Issue by yuanqm55** [molstar/molstar#719]
Hi,
I want to use Mol* to visualize my AI prediction for each residue in a protein structure. Specifically, I have a PDB file with the B-factor column recording the binary/continuous predictions. I have successfully shown a pdb on a website using Mol*, but I don't know how to set the color.
What I want to do:
1. The PDB B-factors record binary values of 0/1. I want to set the residues/atoms labeled with 1 to red, and others to grey.
2. The PDB B-factors record continuous values of [0, 1]. I want to set the residues/atoms to gradient colors based on the values (e.g. red for 1, light red for 0.5, grey for 0).
How to do these using Mol*? Thanks in advance!

**Comment by arose** [comment]
Have a look at the uncertainty color theme which reads data from the B-factor column. You can set the `domain` parameter to [0, 1] and provide a list of colors with the `list` parameter.

https://github.com/molstar/molstar/blob/b2924761abddae9b3c652f76548fa2168ef62cbf/src/mol-theme/color/uncertainty.ts
