### ISSUE TITLE
How to replace them before BUild

### ISSUE THREAD

**Issue by MenFsq** [molstar/molstar#720]
How to replace them before BUild？
![1676516174598](https://user-images.githubusercontent.com/71696702/219256517-5c9a7c67-f645-491c-9c18-77c531ae3ff8.png)

**Comment by arose** [comment]
Other than changing the source, you can't. What do you want to achieve?

**Comment by MenFsq** [comment]
> Other than changing the source, you can't. What do you want to achieve?

I want to use 'vieer.loadpdb ()' to automatically load my local pdb file when molstar renders to the browser, but it always seems to be the link address in the image!

**Comment by MenFsq** [comment]
> Other than changing the source, you can't. What do you want to achieve?

Sorry, I saw the solution below #37. I think I used the wrong API. Now I use 'loadStructureFromUrl()'.

**Comment by MenFsq** [comment]
> Other than changing the source, you can't. What do you want to achieve?
Sorry, I saw the solution below #37. I think I used the wrong API. Now I use 'loadStructureFromUrl()'.
