### ISSUE TITLE
SOS!!!How do I set up to see small molecules after importing a local file?

### ISSUE THREAD

**Issue by MenFsq** [molstar/molstar#721]
using the 'loadPdb()' method， you can see small molecules,
![image](https://user-images.githubusercontent.com/71696702/219328608-6952b6d7-622d-478f-8bdb-1568b9786e62.png)
using the 'loadStructureFromUrl()' method， you can't see small molecules,
![image](https://user-images.githubusercontent.com/71696702/219329393-86ec1541-9875-4173-b635-5e8314d6eec6.png)

**Comment by arose** [comment]
there seems to be a difference in the data being loaded. hard to know what is different without having the two pieces of tdata to reproduce
