### ISSUE TITLE
PCA degenerate case

### ISSUE THREAD

**Issue by midlik** [molstar/molstar#722]
@arose, I was wondering - shouldn't the third vector be (0, 0, 1)?

https://github.com/molstar/molstar/blob/b2924761abddae9b3c652f76548fa2168ef62cbf/src/mol-math/linear-algebra/matrix/principal-axes.ts#L30

**Comment by arose** [comment]
Yeah, I think it is a case of the copy'n'paste syndrom. Can you do a quick PR? Did you encounter this as an issue?

**Comment by midlik** [comment]
Thanks, I will create a PR.

I ran into this issue when trying to align structures to PCA axes. When I passed a 1-atom substructure to it, I got a non-invertible matrix which caused problems later. That's easy to fix – I can check the number of atoms before calling PCA, but still it should be fixed in the original PCA code.

Now I'm also thinking – what about positions.length === 0?
Currently it returns just NaNs, is this the desired behaviour?

**Comment by midlik** [comment]
Could you please merge it, if it's OK?

**Comment by arose** [comment]
> Now I'm also thinking – what about positions.length === 0?

probably best handled in application-specific code, does it occur for your use case?

**Comment by midlik** [comment]
OK.
