### ISSUE TITLE
deleteRepresentation functionality

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#723]
Hi, 

I created this custom function within `src/mol-plugin-state/builder/structure/representation.ts` because I needed a quick way to delete an old representation so a new representation I created shows on a given structure.

```typescript
deleteRepresentation(builder: StateBuilder.Root, structureRef: StateObjectRef<PluginStateObject.Molecule.Structure>, representationRef: any) {
        if (!structureRef) {
            console.log('No structure ref found');
        }
        if (!representationRef) {
            console.log('No representation Ref found');
            return;
        }
        builder.to(structureRef).delete(representationRef);
    }
```
I'm not sure if something like this exists within the code (at least I wasn't able to find it) - so I'm wondering if we should include this as part of the code as well? I think it can help other people. However, is there a reason there isn't a function like this within `src/mol-plugin-state/builder/structure/representation.ts`, is this the incorrect approach to this?

**Comment by arose** [comment]
@dsehnal thoughts? good addition to the builder?

**Comment by dsehnal** [comment]
I can't see how different this is from just deleting the ref directly. The delete function has always been global so the .to in the implementation does nothing.
