### ISSUE TITLE
Local PDB files for PDBe Molstar as JS Plugin

### ISSUE THREAD

**Issue by ShaheerSyed** [molstar/molstar#726]
Hello, 

I was wondering if it was possible to load local PDB files for the PDBe Molstar as JS plugin? I looked through the documentation and it only shows URL or MoleculeID options ?

For example:

```
//Create plugin instance
      var viewerInstance = new PDBeMolstarPlugin();
  
      //Set options (Checkout available options list in the documentation)
      var options = {
        customData: {
          url: 'https://alphafold.ebi.ac.uk/files/AF-O15552-F1-model_v1.cif',
          format: 'cif'
        },
        alphafoldView: true,
        bgColor: {r:255, g:255, b:255},
        hideCanvasControls: ['selection', 'animation', 'controlToggle', 'controlInfo']
      }
```

 Would it be possible to use a PDB file I already have of a protein instead of a URL? I apologize if this is a trivial question.  If this is not possible with the plugin, please also let me know.

Thank You.

**Comment by arose** [comment]
see #551
