### ISSUE TITLE
Issue with outline threshold and otrhographic camera view

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#728]
Seems that outline threshold is broken on big structures using orthographic camera view. Here a test state to reproduce 
[test-outline-with-orthographic.molj.txt](https://github.com/molstar/molstar/files/10777462/test-outline-with-orthographic.molj.txt)
![image](https://user-images.githubusercontent.com/20627977/219963534-90ef99cc-5f7e-4443-b640-73d24a021ab8.png)

**Comment by arose** [comment]
yeah, that is a bug, I have a fix but need some time to push it
