### ISSUE TITLE
Memory leak when parsing volume binary file

### ISSUE THREAD

**Issue by gfrn** [molstar/molstar#730]
Hello! First of all, this is an amazing project and I'm glad such a thing exists. Nevertheless, I have been trouble parsing MRC files without causing memory leaks. Every time I destroy the component, only part of the memory is freed the first time, and the subsequent times, memory isn't freed at all. 

The amount of new allocated memory seems to vary, but it seems to be between 2 and 3 times the size of the array buffer containing the raw data. I am currently using this to parse the data, which is already enough to trigger the leak:

```typescript
useEffect(() => {
    const plugin = new PluginContext(MySpec);
    async function init() {
      await plugin.init();

      plugin.initViewer(canvasRef.current as HTMLCanvasElement, viewerDiv.current as HTMLDivElement)

      const data = await plugin.builders.data.rawData({ data: rawData! }, {state: {isGhost: true}});
      const parsed = await plugin.dataFormats.get("ccp4")!.parse(plugin, data, {});
      
      /*
      This does not seem to affect the leak in a considerable way
      const volume: StateObjectSelector<PluginStateObject.Volume.Data> = parsed.volumes?.[0] ?? parsed.volume;

      const repr = plugin.build();

      repr
        .to(volume)
        .apply(
          StateTransforms.Representation.VolumeRepresentation3D,
          createVolumeRepresentationParams(plugin, volume.data!)
        );
      await repr.commit();*/
    }

    if (rawData) {
      init();
    }

    return () => {
      plugin?.dispose();
    };
  }, [rawData, viewerDiv, canvasRef]);
```

I have also tried destroying/recreating the canvas, using a global object for the plugin (and assigning `undefined` to it) and recreating the container itself. The cleanup function is fired when the component is closed/destroyed.

Creating the data object from raw data does not seem to trigger the leak, neither does initiating the viewer.

Is there something wrong with the way I am building my representations, or is this indeed odd behaviour? Thanks in advance!

**Comment by dsehnal** [comment]
Can you please try parsing the data without the `dataFormats` wrapper (this is from `Ccp4Provider.parse`):

```ts
const format = plugin.build()
    .to(data)
    .apply(StateTransforms.Data.ParseCcp4, {}, { state: { isGhost: true } });
const volume = format.apply(StateTransforms.Volume.VolumeFromCcp4, { entryId: params?.entryId });
await format.commit({ revertOnError: true });
```

**Comment by dsehnal** [comment]
- I just tested this in Chrome using the "Download Density" function (on 1jj2 2Fo-Fc) and the memory is being freed after the data is deleted (albeit it sometimes takes a while until the GC happens).
- In Firefox the memory seems to stay allocated for a longer period of time.

Might just be browser management of large data buffers. Also, where do your `rawData` come from?

**Comment by gfrn** [comment]
This seems to happen outside strict mode as well (of course, not as much memory is "lost" per iteration), and the problem persists even when `rawData` is initialised inside `init()`, so in theory, there shouldn't be any references to `rawData` past the lifetime of the effect.

Even without the second transform, it seems to keep happening, still

**Comment by dsehnal** [comment]
Does this happen in Chrome too?

**Comment by gfrn** [comment]
It does happen in Google Chrome as well, and it does also happen if I leave just `const data = await plugin.builders[...]`, oddly enough. 

It does not happen if I have, say, a state that contains an `arrayBuffer` with the relevant data, and I am easily able to free up the allocated memory by triggering garbage collection manually once the component is destroyed, or wait a few seconds until the browser frees up that memory.

But as soon as that data is referenced inside `plugin.builders.data.rawData`, it is no longer garbage collected (even when  frantically triggering GCs). This behaviour is consistent across both Firefox and Chrome.

**Comment by dsehnal** [comment]
And does this happen if you download the data using the Mol* plugin?

- One thing I can think of is that the data is saved in the [state tree history](https://github.com/molstar/molstar/blob/master/src/mol-state/state.ts#L79) but that should get cleared when the plugin is no longer referenced.
- You are using your own UI, so the leak isn't caused by the UI either.

**Comment by dsehnal** [comment]
Two more thing: Can you try calling  `await plugin.clear()` before the dispose (or `plugin.clear().then(() => plugin.dispose()))`? Because when I tested if the memory gets freed, I've actually only cleared the plugin and assumed the `dispose` would do the same.

**Comment by dsehnal** [comment]
I just tested this in Chrome on https://molstar.org/viewer/

![image](https://user-images.githubusercontent.com/21145776/220991026-075c2371-126e-4108-9d93-75bcfdffa20a.png)
After loading:
![image](https://user-images.githubusercontent.com/21145776/220991299-db35134e-e311-43b3-b1ca-0b4b3e1d533c.png)
After clearing state:
![image](https://user-images.githubusercontent.com/21145776/220991393-4bc98e15-2c40-4772-a4fe-6e8849f1613c.png)

So I have no idea what is going on...

**Comment by gfrn** [comment]
Good morning! Seems like I got to the bottom of it: checking the dominator tree, it seems like `animationLoop` is kept alive since `_isAnimating` is left floating in a `true` state. Explicitly stopping the animation loop when disposing of the plugin instance allows the plugin to be properly dereferenced, and in turn, GC can collect it with no issue.

If relevant, I can share Chrome/Firefox memory mapping comparisons, but to me, stopping the loop under `dispose()` did it

**Comment by dsehnal** [comment]
Thanks for finding this. I've made a patch release with the fix.

**Comment by gfrn** [comment]
Many thanks! Should we close the issue now?

**Comment by dsehnal** [comment]
Up to you... if you have some time to dig into the leaked strings as well, that might be helpful.

**Comment by gfrn** [comment]
I've dug into what may be causing the strings-with-no-clear-use to be there, and these are actually amino acid names, polymer types, and so on, all referenced by the `ElementSymbol` function in `mol-model/structure/model/types.js`. However, this doesn't "continuously" leak, the reference merely stays alive and is reused when the next plugin object is created.

So while this could potentially be annoying because some memory could be freed (especially if the user destroys the Molstar plugin for good and never reuses it again), this doesn't get out of control and the footprint is relatively small, so I don't think this is worth investigating any further
