### ISSUE TITLE
Color for Mesh not working - Potential bug?

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#732]
Hi, 

I created a sphere using similar logic to [this](https://github.com/molstar/molstar/issues/82#issuecomment-687659919), but the color wasn't working, and I would always get a black sphere.

I was able to fix this by changing the value of `currentGroup` to `0` instead of `-1`

https://github.com/molstar/molstar/blob/de84a8c8c5d57e1bf6b773af3fa1ae6900b4bac8/src/mol-geo/geometry/mesh/mesh-builder.ts#L44

Having this set to  `-1` kept returning a float array for our `groups` which eventually bubbled down to us never calling this piece of code which would color the shape:
https://github.com/molstar/molstar/blob/de84a8c8c5d57e1bf6b773af3fa1ae6900b4bac8/src/mol-theme/color/shape-group.ts#L28-L33

and now my shapes have colors:
![Screenshot 2023-02-21 at 3 36 54 PM](https://user-images.githubusercontent.com/7971405/220483146-34064cb5-6464-4a4d-ac2e-a9387369fa31.png)

but not sure if this will have other issues.

**Comment by arose** [comment]
A negative currentGroup will not work in almost all cases as it will be used as an array index. You can find some more shape examples here https://github.com/molstar/molstar/blob/master/src/tests/browser/render-shape.ts

**Comment by luna215** [comment]
I see that the samples you provided overrides the `currentGroup`:
https://github.com/molstar/molstar/blob/6d76bf120dd0f77eba6cde9c4d4ca27718244d7b/src/tests/browser/render-shape.ts#L75

Shouldn't we just make the currentGroup default to 0, so we don't have to override the currentGroup every time?

**Comment by arose** [comment]
devs should be encouraged to set the currentGroup so they are conscious to what of their data it points to
