### ISSUE TITLE
colouring according to pLDDT

### ISSUE THREAD

**Issue by mouhandalkadri** [molstar/molstar#736]
Hello 

I have integrated my web app with the Mol* viewer, I am interested now in colouring the protein structure according to the Alpha Fold's pLDDT, as I understand those values are embedded in the B-factor in the pdb file, and I think the Mol* already implemented this functionality.
is there any documentation to do that and where can I find it, if there's no docs can anyone help me achieving that ?
Thank you in advance

**Comment by jk7f** [comment]
I was in the same ship as you a few months ago, here's what I had to do:

when creating the plugin: add the behaviour for the quality assessment to the PluginSpec 
`behaviors: [PluginSpec.Behavior(MAQualityAssessment), ...defaultPluginSpec.behaviors]`

activate it: 
```
plugin.dataTransaction(async () => {
      await plugin.managers.structure.component.applyPreset(
        plugin.managers.structure.hierarchy.current.structures,
        QualityAssessmentPLDDTPreset
      );
    });
```

**Comment by mouhandalkadri** [comment]
@jk7f  Thank you very for answering, I really appreciate it.
another question does this extension supports QA from `pdb` files or as I see just `cif` files ?

**Comment by mouhandalkadri** [comment]
Ok, as I see it's just for `cif` files 
as I noticed in the `src/extensions/model-archive/quality-assessment/prop.ts` file
```ts
 export function isApplicable(model?: Model, localMetricName?: 'pLDDT' | 'qmean'): boolean {
        // Explicitly checks for cif format
        if (!model || !MmcifFormat.is(model.sourceData)) return false;
        const { db } = model.sourceData.data;
        const hasLocalMetric = (
            db.ma_qa_metric.id.isDefined &&
            db.ma_qa_metric_local.ordinal_id.isDefined
        );
        if (localMetricName && hasLocalMetric) {
            for (let i = 0, il = db.ma_qa_metric._rowCount; i < il; i++) {
                if (db.ma_qa_metric.mode.value(i) !== 'local') continue;
                if (localMetricName === db.ma_qa_metric.name.value(i)) return true;
            }
            return false;
        } else {
            return hasLocalMetric;
        }
    }

```
as in the first line it checks for `cif` format

**Comment by arose** [comment]
The `uncertainty` color theme uses data from the B-factor column of PDB files. You can adjust the domain and colors in the parameters.
