### ISSUE TITLE
Best way to add extra panel to left side bar

### ISSUE THREAD

**Issue by mah51** [molstar/molstar#739]
Hi, 

I've forked the project and I'm trying to add a custom section in the left side bar. So far I have just copied and pasted this section to add another icon to the sidebar. 
 https://github.com/molstar/molstar/blob/a50e81551fc32d383b43e452d1fd704a99799893/src/mol-plugin-ui/left-panel.tsx#L95

Then duplicated the root tab info and named the key 'custom'. So when I click on the new Icon it comes up with the new section which is currently just a duplicate of the home menu. I see that the items in the list are a list of actions defined in https://github.com/molstar/molstar/blob/a50e81551fc32d383b43e452d1fd704a99799893/src/mol-plugin/spec.ts#L66

However, I am a bit confused by the nodeRef string (-=root=-) and how this then lists the correct actions that have the from: PluginStateObject.Root property. As I don't want the -=root=- actions but the nodeRef property is required by StateObjectActions.

It would be a great help if someone could drop me a few bullet points of how I should proceed / the best way to add a custom section into the left panel with custom actions / buttons

Thanks

**Comment by dsehnal** [comment]
I think you can remove this control then https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/left-panel.tsx#L71 and replace it with whatever you want there.

**Comment by dsehnal** [comment]
I see. The actions shown there are the ones which have `from: PluginStateObject.Root` in their definition. If you don't want to show some of the existing ones, you need to remove them from the plugin spec.

**Comment by mah51** [comment]
Ah okay, that makes sense. Is it possible to duplicate that functionality. e.g. have from: PluginStateObject.Custom on some custom actions and then only the custom ones show up because it's the custom panel?

**Comment by dsehnal** [comment]
I guess you can write your own version of  `<StateObjectActions  />` which does the filtering according to your needs then

**Comment by mah51** [comment]
Okay great, thanks. I'll give it a shot. Cheers for the help
