### ISSUE TITLE
Can the viewer be used as a standalone package?

### ISSUE THREAD

**Issue by lidaof** [molstar/molstar#74]
Can anyone share how to use the mol-viewer as a standalone package? like  can be imported to React.

Thank you in advance!

**Comment by dsehnal** [comment]
Hi, for example like this https://github.com/molstar/molstar/blob/master/src/apps/viewer/embedded.html

**Comment by lidaof** [comment]
Thank you @dsehnal for reply. I was not able to run through the build process in order to run the example...

![image](https://user-images.githubusercontent.com/102806/88486626-a15a5900-cf44-11ea-8713-61b7b7965a0a.png)

**Comment by lidaof** [comment]
thanks, build error was fixed #75

**Comment by jiucenglou** [comment]
> Thank you @dsehnal for reply. I was not able to run through the build process in order to run the example...
> 
> ![image](https://user-images.githubusercontent.com/102806/88486626-a15a5900-cf44-11ea-8713-61b7b7965a0a.png)

I have downloaded the latest 2.0.7 zip from the releases section, extracted, and opened `D:\molstar-2.0.7\src\apps\viewer\embedded.html` in Edge. However, the page is blank and the Console says errors similar to those shown above. Could you suggest how to workaround this ?

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
molstar.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
embedded.html:23 Uncaught ReferenceError: molstar is not defined
    at embedded.html:23
```

**Comment by dsehnal** [comment]
The file needs to be opened from the /build directory and not the /src one.

**Comment by jiucenglou** [comment]
> The file needs to be opened from the /build directory and not the /src one.

Thank you for your helpful clarification !
After `npm install` and `npm run build` within `D:\molstar-2.0.7\` (my unpacked directory), I can open `build\viewer\embedded.html` flawlessly !
