### ISSUE TITLE
Hiding certain residues

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#743]
Hi, 

How would I go about hiding a certain residue of a structure? For example if I were to use this https://files.rcsb.org/view/1UBQ.pdb, which has 76 residues, how would I go about showing/hiding specific residues?

I know how to hide an entire structure, but not individual components. Any help here is greatly appreciated!

**Comment by dsehnal** [comment]
I remembered there is one more method to achieve this: you can subtract selection:

![image](https://user-images.githubusercontent.com/21145776/225720018-5f7d3840-0d58-42a3-acf4-ac82d01db634.png)
![image](https://user-images.githubusercontent.com/21145776/225720080-1edb40d9-6bf7-4aaf-bd2e-b94d458deeb6.png)

**Comment by luna215** [comment]
@dsehnal  thank you this helped me write this programmatically! 

For anyone looking for a similar solution, I did the following:

```typescript
// Get sequence
const wrappers: { wrapper: (string | SequenceWrapper.Any), label: string }[] = getSequenceWrappers(structure, this.plugin.managers.structure.selection);

// From the sequence, we retrieved, add certain loci to selection
// Once part of the selection, then we can delete the selected.
const sel = this.plugin.managers.structure.hierarchy.getStructuresWithSelection();
const componentsToDelete: StructureComponentRef[] = [];
for (const s of sel) componentsToDelete.push(...s.components);
this.plugin.managers.structure.component.modifyByCurrentSelection(componentsToDelete, 'subtract');

```

`getSequenceWrappers` is very similar to: https://github.com/molstar/molstar/blob/e636397f90106d78f4e354e52a40237171a5fa87/src/mol-plugin-ui/sequence.tsx#L266

Can add loci to selection like so:
```typescript
this.plugin.managers.structure.selection.fromLoci('add', loci);
```
