### ISSUE TITLE
How to set the State Tree as the default left panel view?

### ISSUE THREAD

**Issue by mattpangenesis** [molstar/molstar#744]
I'm working with the `docking-viewer`, and have expanded the left panel by default programmatically. But it always shows the "Home" view instead of the "State Tree" view. I've gone through all the settings but don't know which one to change. Any tips? Thanks!

**Comment by dsehnal** [comment]
`plugin.behaviors.layout.leftPanelTabName.next('data')` should do the trick.

**Comment by mattpangenesis** [comment]
Works perfectly. Much appreciated.
