### ISSUE TITLE
Uncertainty coloring missing when loading a model + coordinates file pair

### ISSUE THREAD

**Issue by marionatf** [molstar/molstar#747]
I have a cif file with b-factor values, which I can display using the Uncertainty color scheme. When I load the same cif file together with a trajectory, the Uncertainty color scheme shows an uniform color instead. The same happens if I load a pdb + trajectory file pair.
Is there a way to display b-factor values (uncertainty) when loading a model + coordinates file pair?

Here are the files I am loading: [bfact.tar.gz](https://github.com/molstar/molstar/files/10989423/bfact.tar.gz)

**Comment by arose** [comment]
Hey, we did not include `occupancy` and `B_iso_or_equiv` when creating a trajectory. Supported with occupancy #773.
