### ISSUE TITLE
"Hover" events detected on molstar even when the viewer is not the focused element

### ISSUE THREAD

**Issue by russellp17** [molstar/molstar#748]
I noticed that if a molstar is embedded in an app, then "hover" interactions occur even when the viewer is not in focus. For instance, if you launch a modal over the viewer, then moving the mouse over the modal could still trigger the info in the bottom right corner about residue index, etc.

It seems like this was added specifically to handle dragging where the cursor leaves the main container element: https://github.com/molstar/molstar/blob/e636397f90106d78f4e354e52a40237171a5fa87/src/mol-util/input/input-observer.ts#L335-L337

Is it possible to enforce that "hover" behavior only occurs when the container element is in focus?

**Comment by dsehnal** [comment]
I've ran into this too recently. A workaround is to put `e.stopPropagation()` registered on the overlay element.

I will have a look into addressing this in the core.

**Comment by dsehnal** [comment]
I put up https://github.com/molstar/molstar/pull/750. Can you please review it @russellp17  and check if it works for your use case?
