### ISSUE TITLE
Resize not detected when container element changes size

### ISSUE THREAD

**Issue by russellp17** [molstar/molstar#749]
Molstar handles resizing the window, but there can be cases where the container element is resized but the window is not resized (e.g. another element is added/removed that causes the viewer to shrink in size). I think this can be handled with https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver - I'll try to put up a PR soon

**Comment by dsehnal** [comment]
I usually just use `ResizeObserver` and call `handleResize` on the plugin context manually. Having this built in would be nicer tho if you find time to do a PR.
