### ISSUE TITLE
Webpack is not getting fooled

### ISSUE THREAD

**Issue by rtviii** [molstar/molstar#754]
ERROR in ./node_modules/molstar/lib/mol-util/data-source.js 381:8-17
Module not found: Error: Can't resolve 'fs' in '/home/rxz/dev/scaffold-molstar/node_modules/molstar/lib/mol-util'

**Comment by dsehnal** [comment]
Your webpack is smarter than mine it seems. Hopefully https://github.com/molstar/molstar/pull/755 fixes this.

**Comment by rtviii** [comment]
Beauty. Thank you!

**Comment by rtviii** [comment]
P.S. i wish it weren't :laughing:
