### ISSUE TITLE
Initializing multiple plugins

### ISSUE THREAD

**Issue by elliothershberg** [molstar/molstar#756]
Hi! 👋

Thanks for the incredible technology. I'm looking to use the molstar viewer as a plugin in an app that I'm building, and I've successfully gotten it working based on the docs and examples.

In my app, I want to be able to display two viewers, side by side. In the [plugin docs](https://molstar.org/docs/plugin/), it's alluded to that there might be more to do in order to get this to work:

> A single-plugin setup is shown the example below. In order to initialize multiple plugins, each with its own context and viewport, some extra steps are required (docs section to be added).

I'm wondering if I could get some help making this happen?

Another direction I've considered is superimposing two structures to compare them. I've seen this in the [viewer docs](https://molstar.org/viewer-docs/faqs-scenarios/#how-do-i-comparesuperpose-multiple-structures) and examples, and I'm wondering: would it be possible to accomplish this using the plugin?

**Comment by elliothershberg** [comment]
Thanks! I'm just going to have two plugins. I tried creating two instances of the plugin and get an error from the call to `parseTrajectory`: `Error: Could not find node 'tng7TF8eCPiC-AeQIQKvZA'.`

So I assumed there was some conflict that I wasn't aware of.

Could you tell me what function I would need to call in order to render the plugin with two protein structures? The structures I'll be viewing will be very similar to each other.

**Comment by elliothershberg** [comment]
Just following up here: @dsehnal do you know why rendering two plugins causes this error, or could you point me to examples/docs for adding two structures to the same plugin?

**Comment by dsehnal** [comment]
It's works for me by modifying the `viewer/embedded.html` code.

```ts
molstar.Viewer.create('app', {
    layoutIsExpanded: false,
    layoutShowControls: false,
}).then(viewer => {
    viewer.loadPdb('7bv2');
});
molstar.Viewer.create('app2', {
    layoutIsExpanded: false,
    layoutShowControls: false,
}).then(viewer => {
    viewer.loadPdb('1tqn');
});
```

so you are likely doing something else wrong.

**Comment by Mustafa-Albekaa** [comment]
I'm trying to do this same thing and am using the "basic wrapper" example provided in this repo so that I can make more use of this amazing software than just the simple viewport.

I'm running into the same problem as @elliothershberg, I've tried many permutations of initialisation and loading (different and identical files) and have not been able to get both instances to run at once. Any help (or fleshing out of the docs) would be appreciated.

**Comment by Mustafa-Albekaa** [comment]
It was such a simple fix in the end that I should have realised it from the beginning. For anyone coming after me, this is how I got the Basic Wrapper example to initialise two plugins:

```
// basic-wrapper/index.ts

// line 28:
export default class BasicWrapper {

// line 182:
// (window as any).BasicMolStarWrapper = new BasicWrapper();
```

```
// your-file.js

import MolstarWrapper from 'basic-wrapper/index.ts';
var MolstarWrapperClass1 = new MolstarWrapper;
var MolstarWrapperClass2 = new MolstarWrapper;

MolstarWrapperClass1.init(...);
MolstarWrapperClass2.init(...);

MolstarWrapperClass1.load(...);
MolstarWrapperClass2.load(...);

// etc
```

Thank you again for this amazing 3D viewer!
