### ISSUE TITLE
Cannot find type definition  

### ISSUE THREAD

**Issue by Pantelispanka** [molstar/molstar#758]
Cannot find type definition file for 'react'. and Cannot find namespace 'JSX'. 

When importing

import { DefaultPluginSpec, PluginSpec } from 'molstar/lib/mol-plugin/spec';
import { PluginContext  } from 'molstar/lib/mol-plugin/context';
import { PluginConfig } from 'molstar/lib/mol-plugin/config';

in an angular application  with PluginContext without built-in React UI.

Is there an example how molstar can be used in angular somewhere? 
Thanks a lot!!

**Comment by dsehnal** [comment]
It would be helpful to get a better error message. E.g. what file is missing the declaration.

**Comment by Pantelispanka** [comment]
Thats the logs from the angular application. Hope that this will be useful!

**Comment by dsehnal** [comment]
Thanks, this should be fixed with next release. 

There is a similar issue you want to use some of the extensions, I will think about addressing this separately.
