### ISSUE TITLE
Can't colour protein by the B-factor.

### ISSUE THREAD

**Issue by Ieremie** [molstar/molstar#759]
There are many cases in which the protein structure needs to be coloured by a used defined measure which can  be put into the B-factor field. This is possibly in pymol.

**Comment by arose** [comment]
Try the Uncertainty/Disorder color theme

![image](https://user-images.githubusercontent.com/272250/227004067-b85128a6-8485-486b-872f-2e9f8d00f280.png)

**Comment by Ieremie** [comment]
Hello @arose, is that picking up the B-factor column?

**Comment by Ieremie** [comment]
Seems it does! Cheers! I just didn't find this in the documentation, maybe it would be useful to add that there.
