### ISSUE TITLE
new format g3d request

### ISSUE THREAD

**Issue by lidaof** [molstar/molstar#76]
Hi there,

last year I asked Alex and he kindly add support for .3dg format (commit: 901fac97), i actually developed a new binary format based on that with small modifications...i named this format .g3d and an example file is [here](https://wangftp.wustl.edu/~dli/tmp/GSM3271347_gm12878_01.impute3.round4.clean.g3d).  I also have a Javascript library to parse the file either from URL or upload from local disk: [g3djs](https://www.npmjs.com/package/g3djs). 

So I have been trying to add g3d support following the 3dg example added by Alex in past days...but I made barely no progress...my format supports query data from a specify genomic region, or a whole chromosome or entire genome, given a specific resolution. It supports data in multiple resolutions as well.  I tried to look at the cif examples/IO/model library code, but didn't figure out how to incorporate my JS library in to do the data IO.

Thank you so much in advance for any help/suggestions/instructions etc.

**Comment by dsehnal** [comment]
Hi,

would it be possible for you to write a function that takes ``Uint8Array`` and then returns the data structure which could be converted to this schema https://github.com/molstar/molstar/blob/master/src/mol-io/reader/3dg/parser.ts#L17 (you said there were some modifications, so it does not have to be exactly that). 

It would then be quite easy to integrate your parser into Mol* and I would do it.

PS: As a side note, have you considered using BinaryCIF?

**Comment by lidaof** [comment]
Hi @dsehnal thank you so much for your response!

Sorry for late reply...I was think about your question and then tried to look at some example in mol* source...I don't think I use that low level of data structure...I also used msgpack for encode and decode data, but I didn't deal with Uint8Array or any DataView thing...so sorry I am not sure how to do that... But I tried to crate a [codesandbox](https://codesandbox.io/s/objective-carson-q37gk?file=/src/App.js) link for you to help you understand the format...

the schema for my format would be different, will look like this:

```
export const SchemaG3D = {
    /** Chromosome name */
    chromosome: Schema.str,
    /** Base position start */
    start: Schema.int,
    /** Base position end */
    end: Schema.int,
    /** X coordinate */
    x: Schema.float,
    /** Y coordinate */
    y: Schema.float,
    /** Z coordinate */
    z: Schema.float,
    /* haplotype  */
    haplotype: Schema.str,
};
export type SchemaG3D = typeof SchemaG3D;

export interface FileG3D {
    table: Table<SchemaG3D>;
}

const FieldNames = ['chromosome', 'start', 'end', 'x', 'y', 'z', 'haplotype'];
```
this is for genomics 3D data, I am not sure if binaryCIF work or not as I am not quite familiar with binaryCIF format...

**Comment by dsehnal** [comment]
I want you to write a simplified version of https://github.com/lidaof/g3d/blob/master/g3djs/g3dFile.js 

```ts
interface G3dHeader {
  ...
}

interface G3dFile {
  header: G3dHeader,
  data: Uint8Array
}

interface G3dReadParams {
  chromosome?: string, // optional chromosome name
  range?: [number, number], // optional range
  resolution: number
}

interface G3dData {
  file: G3dFile,
  params: G3dReadParams,

  chromosome: string[],
  start: number[], // could be Int32Array
  end: number[], // could be Int32Array
  x: number[], // Float32Array
  y: number[], // Float32Array
  z: number[], // Float32Array
  haplotype: string[]
}

async function readFile(input: Uint8Array): Promise<G3dFile> {
  // read the header basically
  // might not need to be async as reading the header should be fast
}

async function readData(file: G3dFile, params?: Params): Promise<G3dData> {
  // ....
}
```

You can write it in plain JS, should not be a big deal to add the types.

The way you return the data in your parser isn't good for large-scale data. I.e. you are using a row based approach while column based one is much more appropriate.

---------------------

I will then take this code, modify it to support the ``Task`` interface in Mol* and integrate it.

I don't want to use your library directly because of the dependencies it uses. We have msgPack parser directly as part of Mol*, and I don't want to include lodash nor Buffer polyfill.

**Comment by lidaof** [comment]
Hi @dsehnal , thank you for the explanation! sorry I didn't understand what you mean before.

I will give it a try! Thanks again!

**Comment by lidaof** [comment]
Hi @dsehnal , I have spent on this for the whole day sorry that so far I can do is to remove the dependency of lodash etc...I don't know how to switch to column based approach...nor how to use the IO functions provided by mol*....it looks like quite a big challenge for me..not sure if I could figure it out..

**Comment by dsehnal** [comment]
You don't need to use the IO functions provided by Mol* per se. The file reading/download will be handled by rest of the framework.

- ``Uint8Array`` is essentially same as ``Buffer`` and it will contain the binary data for the entire file. In the browser setting it doesn't make sense to do "streaming" on files. To slice it you can do ``new Uint8Array(old.buffer, old.byteOffset + offset, size)``
- Mol* has ``msgpackDecode`` function in ``mol-io/common/msgpack/decode``
- ``unzip`` is in ``mol-util/zip/zip``
- To do the column based data model: This depends on how the data are stored in the underlying file format, but worst case you can transform the data with a for loop. 
  * When you are loading the file, do you know how many rows will be there for a given "data chunk" in advance?

**Comment by dsehnal** [comment]
I think we got off on a wrong foot here.

I didn’t realize your “remote file” was actually querying a range from the server. Initially, I thought you wanted to download the entire file and parse it on a client. But I understand now this is not the case and you always download just the block with the specified resolution.

The way you go around this is very non-intuitive as it was not clear at all that it requires specific server support.

Regardless, what you want to do is possible to do in mol* but indeed requires more than providing a mol-io module the same way the previous format worked. If its to be useful it would require some custom UI elements as well.

What is your timeline when you would like this to be implemented?

Also, I was thinking about the format itself and there are things which I think could be significantly improved. For example the whole “binning” approach doesn’t make sense at all since you can just do binary search and get the row range in log time. Then you can store the entire resolution as an object of arrays and reduce the parse time significantly. And if you want I can elaborate on this more.

**Comment by lidaof** [comment]
Hi @dsehnal , thank you so much for the input. You are correct I am only fetching the data blocks on a specific region, or a specific chromosome, or entire genome. I am using [UCSC binning system](http://genomewiki.ucsc.edu/index.php/Bin_indexing_system) to do region based data query as genomics 3D dataset are pretty big, with higher resolution the file will become even bigger and it's not idea to read the file in whole into memory.

Also you are correct this requires the server enable CORS and Range request, I am developing genome browser and I need this enabled as well for other genomic formats like bigwig, bedgraph etc.  So actually I have developed [an own 3D visualization app](https://g3dv.now.sh/), but my PI said 'it's very ugly'...that's why I come to mol* :) As you can see, the UI in my ugly app indeed has more UI elements allow user query 3D data in a specific region/gene. I an not very rush on this, if can be implemented in 1 month would be great.

I definitely learnt a lot from your comments, although I don't quite get them so far, I will keep digging. Thank you again!

**Comment by dsehnal** [comment]
You are wrong about using the chunks. They only make it slower.

The data model you use to store the chunk is a JSON object (encoded using msgPack) of the form

```ts
interface ResolutionChunk {
  [binkey: string]: { chromosome, start, end, x, y, z, haplotype }[]
}
```

So each time you read such a chunk you decode the entire thing using these 3 lines (https://github.com/lidaof/g3d/blob/master/g3djs/g3dFile.js#L125):

```js
const buffer = Buffer.from(response);
const unzipped = await unzip(buffer);
const out = msgpack.decode(unzipped);
```

Only after you decode them you iterate over ALL the bins to filter the data. 

Storing the data in this way is very non-efficient, because for every single row you create a new full object. MsgPack actually stores the property names for each row repeatedly, so your data looks like this:

```ts
{
  1 /* bin number */: [
    { chromosome, start, end, x, y, z, haplotype },
    { chromosome, start, end, x, y, z, haplotype },
    { chromosome, start, end, x, y, z, haplotype },
    { chromosome, start, end, x, y, z, haplotype },
    ....
  ],
  10: [
    { chromosome, start, end, x, y, z, haplotype },
    ...
  ],
  ...
}
```

What ``msgpack.decode`` is that it creates a new JS object anyway. Then you pass this to array of arrays and finally return the data using ``_.flatten`` (another waste of memory).

--------------------------------

What I am suggesting is this:

```ts
interface ResolutionChunkColumns {
  chromosome: string[], 
  start: number[], 
  end: number[], 
  x, y, z, haplotype // arrays for each.
}
```

In this case, the data in memory would look likes this:

```
const data = {
  chromosome: [.....],
  start: [0, 10, 20, 30],
  end: [10, 20, 30, 40],
  ...
}
```

To read the data you would do this (simplified):

```ts
async function readChunk(file, { offset, size }, range) {
  const buffer = Buffer.from(await file.read(offset, size));
  const unzipped = await unzip(buffer);
  const chunk = msgpack.decode(unzipped);
  
  // If no range is specified, just return the chunk as is, no need to filter anything.
  if (!range) return chunk;
  
  // take this with a grain of salt, there the might be some off by 1 error somewhere
  // but the overall idea is sound
  const start = binarySearch(chunk.start, range.start);
  const end = binarySearch(chunk.start, range.end + 1);
  
  const ret = Object.create(null);
  for (const key of Object.keys(chunk)) {
    ret[key] = chunk[key].slice(start, end);
  }
  return ret;
}
```

This could be further improved by ditching msgpack for the chunks altogether and just storing the raw binary data. You could then do the slices even more efficiently. Or just store the ``start/end`` coords and only read these in full.

What I am trying to say that for a given resolution you read ALL the data anyway, so the bins have absolutely zero point.

**Comment by lidaof** [comment]
Hi @dsehnal thank you!! Really appreciate! This is very helpful!
I will think about your suggestions and try to improve the library. (might take some time I have no CS background :) )

**Comment by lidaof** [comment]
Hi David @dsehnal ,

I have modified the file format according to what you suggested, [the file](https://target.wustl.edu/dli/tmp/test2.g3d) size become bit smaller :)
I made this small [codesandbox demo](https://codesandbox.io/s/eloquent-breeze-x7u1x) to fetch data and show data structure, I put all data in msgpack encoded dictionary, removed the fixed header, so after get the data from buffer, unzip it, it's a dict of this structure:
```
{
  resolution: {
    haplotype: {
      chromosome: {
        starts: [0, 1, 2...],
        coordinates: [ [x1,y1, z1], [x2, y2, z2] ... ]
      }
    }
  }
}
```
Would this make better to included to mol*? I am not sure if should add the header back with offset information for different resolutions, fetch the whole 22Mb file seems fine...

Please let me know if there is anything I can do. Thank you so much!!

**Comment by dsehnal** [comment]
I don't understand why you did it this way. I thought the point was to have the resolutions separate so that you can query and download the data only at a given resolution. Having everything in the same object which you read at once goes against that. Actually, the format then just becomes more wasteful, because I can then get the lower-res data from the highest resolution by simply getting every n-th entry with a simple for loop.

Same with the ``[x, y, z]`` coords, why did you decide to put them into separate arrays again? It's slightly better than the object approach before but essentially suffers from the same issue -- i.e. instead of parsing all the coords into 3 separate arrays, a separate array has to be allocated for each coord.

The grouping to the haplotype/chromosome is good tho.

The 20MB that the file is is quite large actually given the fact I can only download it at 80KB/s here at Czech Republic.

**Comment by dsehnal** [comment]
Out of curiosity I have tried to create a BinaryCIF file from the data in your original test file. For the most dense resolution (20k) with 250k entries the gzipped BinaryCIF file has 5.7MB vs 7.21MB read from your format.

The BinaryCIF is binary encoding of CIF with fields

```
data_DATA
#
loop_
_atom_site.chromosome
_atom_site.start
_atom_site.end
_atom_site.x
_atom_site.y
_atom_site.z
_atom_site.haplotype
chr1 67100000 67120000 -11.139482 -3.875342 -11.771078 m 
chr1 67100000 67120000 23.510587 -1.752036 -3.749148 p 
chr1 201320000 201340000 31.730733 -32.412448 -15.464363 p 
chr1 201320000 201340000 14.610118 -33.001859 -36.548242 m 
...
```

I also did two tests with "raw" msgpack. Encoding data directly yields back 7MB gzipped file (down from the 7.21MB read originally as it was encoded in a single chunk). Encoding the data as columns reduces the size to 6.5MB,

So BinaryCIF can provide some improvement but maybe not worth the trouble for this particular use case.

What is the largest 3D genome that you would like to be able to encode/visualize at the same time?
Also, are there some specific 3D visuals that could be used for the visualization other than a "trace"?

**Comment by lidaof** [comment]
> I don't understand why you did it this way. I thought the point was to have the resolutions separate so that you can query and download the data only at a given resolution. Having everything in the same object which you read at once goes against that. Actually, the format then just becomes more wasteful, because I can then get the lower-res data from the highest resolution by simply getting every n-th entry with a simple for loop.
> 
Hi David @dsehnal sorry for this...I misunderstand that mol* prefer get the data in one time...I can try encode them in separate resolutions...with adding back the header part.

> Same with the `[x, y, z]` coords, why did you decide to put them into separate arrays again? It's slightly better than the object approach before but essentially suffers from the same issue -- i.e. instead of parsing all the coords into 3 separate arrays, a separate array has to be allocated for each coord.
> 
For this part, do you mean create three arrays like:
```
    x: [x1, x2, ...],
    y: [y1, y2, ...],
    z: [z1, z2, ...]
```
Sorry I was thinking my way make the data structure looks simpler -,-
> The grouping to the haplotype/chromosome is good tho.
> 
> The 20MB that the file is is quite large actually given the fact I can only download it at 80KB/s here at Czech Republic.

Thank you so much for checking this!

**Comment by dsehnal** [comment]
> Hi David @dsehnal sorry for this...I misunderstand that mol* prefer get the data in one time...I can try encode them in separate resolutions...with adding back the header part.

Mol* can handle streaming quite well. It would help tho if you supported the "range" parameter as part of the URL and not just in the header.

> For this part, do you mean create three arrays like:
> 
> ```
>     x: [x1, x2, ...],
>     y: [y1, y2, ...],
>     z: [z1, z2, ...]
> ```
> 
> Sorry I was thinking my way make the data structure looks simpler -,-

Yes, I mean this structure. This way you avoid the excessive allocations.

**Comment by lidaof** [comment]
> Out of curiosity I have tried to create a BinaryCIF file from the data in your original test file. For the most dense resolution (20k) with 250k entries the gzipped BinaryCIF file has 5.7MB vs 7.21MB read from your format.
> 
> The BinaryCIF is binary encoding of CIF with fields
> 
> ```
> data_DATA
> #
> loop_
> _atom_site.chromosome
> _atom_site.start
> _atom_site.end
> _atom_site.x
> _atom_site.y
> _atom_site.z
> _atom_site.haplotype
> chr1 67100000 67120000 -11.139482 -3.875342 -11.771078 m 
> chr1 67100000 67120000 23.510587 -1.752036 -3.749148 p 
> chr1 201320000 201340000 31.730733 -32.412448 -15.464363 p 
> chr1 201320000 201340000 14.610118 -33.001859 -36.548242 m 
> ...
> ```
> 
Can BinaryCIF support multiple resolutions? If yes, I would love to try it instead...as it's more popular and standardized. 

> I also did two tests with "raw" msgpack. Encoding data directly yields back 7MB gzipped file (down from the 7.21MB read originally as it was encoded in a single chunk). Encoding the data as columns reduces the size to 6.5MB,
> 

I am not quite getting this, but thank you for testing!

> So BinaryCIF can provide some improvement but maybe not worth the trouble for this particular use case.
> 
> What is the largest 3D genome that you would like to be able to encode/visualize at the same time?
I guess that depends on resolution, if resolution goes really high, like 1kb or 100bp resolution in a genome, the 3D data array will be pretty big...but I am not sure how large will be or looks like as I haven't deal with such data
> Also, are there some specific 3D visuals that could be used for the visualization other than a "trace"?

I don't understand what `trace` mean here, [3dmol.js](https://3dmol.csb.pitt.edu/) is a similar tool.

**Comment by dsehnal** [comment]
> Can BinaryCIF support multiple resolutions? If yes, I would love to try it instead...as it's more popular and standardized.

Supports multiple data blocks but cannot read that out without parsing everything currently. In a future version we plan to support that so could have G3d as a test case.

> > I also did two tests with "raw" msgpack. Encoding data directly yields back 7MB gzipped file (down from the 7.21MB read originally as it was encoded in a single chunk). Encoding the data as columns reduces the size to 6.5MB,
> 
> I am not quite getting this, but thank you for testing!

Take the object that you return by ``readGenome`` in your library and call ``msgpack.encode`` on it. Then I converted the object to the column-based representation that I suggested and did the same.

> > Also, are there some specific 3D visuals that could be used for the visualization other than a "trace"?
> 
> I don't understand what `trace` mean here, [3dmol.js](https://3dmol.csb.pitt.edu/) is a similar tool.

Tube with centerline using spline interpolation on the 3D positions.

**Comment by lidaof** [comment]
> > Hi David @dsehnal sorry for this...I misunderstand that mol* prefer get the data in one time...I can try encode them in separate resolutions...with adding back the header part.
> 
> Mol* can handle streaming quite well. It would help tho if you supported the "range" parameter as part of the URL and not just in the header.
> 

I am actually not sure how to do in url parameter, I only know set range in Header request. 

> > For this part, do you mean create three arrays like:
> > ```
> >     x: [x1, x2, ...],
> >     y: [y1, y2, ...],
> >     z: [z1, z2, ...]
> > ```
> > 
> > 
> > Sorry I was thinking my way make the data structure looks simpler -,-
> 
> Yes, I mean this structure. This way you avoid the excessive allocations.

I added the header back with offset information for each resolution, and also update both [file](https://target.wustl.edu/dli/tmp/test2.g3d) and [codesandbox](https://codesandbox.io/s/eloquent-breeze-x7u1x) link.. i do see the file size become even bit smaller. Please note the example fetch data I used hard coded offset and size for demo purpose.

**Comment by dsehnal** [comment]
> I am actually not sure how to do in url parameter, I only know set range in Header request.

Well if you use something like Django it should not be a big issue. See for example https://stackoverflow.com/questions/5074803/retrieving-parameters-from-a-url
 
> I added the header back with offset information for each resolution, and also update both [file](https://target.wustl.edu/dli/tmp/test2.g3d) and [codesandbox](https://codesandbox.io/s/eloquent-breeze-x7u1x) link.. i do see the file size become even bit smaller. Please note the example fetch data I used hard coded offset and size for demo purpose.

This is starting to look better. Would you be able to create a proper API for it on your server?

Endpoints like
- ``/:id/header``
- ``/:id/genome?resolution=...``
- ``/:id/range?start=..&end=...&resolution=...[&chromosome=...]``

The params could be optional as well. For example resolution could by default be the most coarse one.

Would also be able to support the same functionality from a local full-file input.

**Comment by lidaof** [comment]
> > I am actually not sure how to do in url parameter, I only know set range in Header request.
> 
> Well if you use something like Django it should not be a big issue. See for example https://stackoverflow.com/questions/5074803/retrieving-parameters-from-a-url
> 

I see...I am using Apache2 to host files, out IT only allow 80 and 443 for outside access...I haven't use Django...will check

> > I added the header back with offset information for each resolution, and also update both [file](https://target.wustl.edu/dli/tmp/test2.g3d) and [codesandbox](https://codesandbox.io/s/eloquent-breeze-x7u1x) link.. i do see the file size become even bit smaller. Please note the example fetch data I used hard coded offset and size for demo purpose.
> 
> This is starting to look better. Would you be able to create a proper API for it on your server?
> 
> Endpoints like
> 
> * `/:id/header`
> * `/:id/genome?resolution=...`
> * `/:id/range?start=..&end=...&resolution=...[&chromosome=...]`
> 
> The params could be optional as well. For example resolution could by default be the most coarse one.
> 

why we need an API server for this? we can always get the data from the file itself by setting correct range bytes, I think?

> Would also be able to support the same functionality from a local full-file input.

For Local file input we can use node's fs, I see mol* uses `const readFile = util.promisify(fs.readFile);`, for user upload we can use FileReader API.

**Comment by dsehnal** [comment]
To be able to provide UI for given remote entry, I need the header. I mean, could use a hack and read the first 64k for header using the Apache range header approach. Not a fan but I suppose it would work. The API was to not use these hacks.

``fs.readFile`` will not work in a browser, but you needn't worry about that. I would just copy-paste the code from your repo anyway.

**Comment by lidaof** [comment]
> > Can BinaryCIF support multiple resolutions? If yes, I would love to try it instead...as it's more popular and standardized.
> 
> Supports multiple data blocks but cannot read that out without parsing everything currently. In a future version we plan to support that so could have G3d as a test case.
> 
> > > I also did two tests with "raw" msgpack. Encoding data directly yields back 7MB gzipped file (down from the 7.21MB read originally as it was encoded in a single chunk). Encoding the data as columns reduces the size to 6.5MB,
> > 
> > 
> > I am not quite getting this, but thank you for testing!
> 
> Take the object that you return by `readGenome` in your library and call `msgpack.encode` on it. Then I converted the object to the column-based representation that I suggested and did the same.
> 
> > > Also, are there some specific 3D visuals that could be used for the visualization other than a "trace"?
> > 
> > 
> > I don't understand what `trace` mean here, [3dmol.js](https://3dmol.csb.pitt.edu/) is a similar tool.
> 
> Tube with centerline using spline interpolation on the 3D positions.

I understand what `trace` means now, yeah, I can only think of this way for genomic 3D visual currently...thank you for explanation! We can adjust the tube line size so the visual will be different.

**Comment by lidaof** [comment]
> To be able to provide UI for given remote entry, I need the header. I mean, could use a hack and read the first 64k for header using the Apache range header approach. Not a fan but I suppose it would work. The API was to not use these hacks.
> 
> `fs.readFile` will not work in a browser, but you needn't worry about that. I would just copy-paste the code from your repo anyway.

Thank you so much. Yeah, I read your Litemol paper before, there is a densityServer setup step. I am thinking if a user want to visual this file, s/he just need to provide the file URL instead of set an API server. how do you think? (One reason is that I am not sure how to setup an API server yet, there is also restrictions on department Firewall etc.)

**Comment by dsehnal** [comment]
You would still provide the URL as well. You would provide the base URL for where the file is hosted, say ``https://foo.com/test-data``. The code would then automatically add the params. Could also have endpoint ``:id/raw`` which would just send all the binary data.

And indeed the API would be similar to how DensityServer works.

**Comment by lidaof** [comment]
I understand now. I will take a look how to setup an API server.
Can the UI component get data from the fixed sized header instead? (i guess it can, but more work? )

**Comment by dsehnal** [comment]
Yes, could get the data from the fixed size header as well in case you wont be able to do the API.

**Comment by dsehnal** [comment]
6b1edd9 adds extension with basic support for your format. Should be enough for you to be able to play around with it.

![image](https://user-images.githubusercontent.com/21145776/90126858-9ab14b80-dd64-11ea-8fab-13491138d886.png)

**Comment by lidaof** [comment]
This is awesome, I am going to try it now. Thank you so much @dsehnal
