### ISSUE TITLE
Loading structures from compressed file with URL 

### ISSUE THREAD

**Issue by kscgl** [molstar/molstar#760]
Is there a way or any recommendations loading structures with compressed data using 'url' source? 

eg;

```
source: {
  name: 'url',
  params: {
    url: 'https://.....gz',
    format: 'gz',
    ....
  }
} 
```

**Comment by dsehnal** [comment]
Do you have access to the server and can you set `content-encoding: gzip` header? Then the browser will decompress the data for you.

**Comment by kscgl** [comment]
Unfortunately I don't have any control over the server. I will check that out though.

**Comment by dsehnal** [comment]
- Export this function https://github.com/molstar/molstar/blob/master/src/mol-util/data-source.ts#L127-L128
- Add optional `compression` param to https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/data.ts#L55 and call the `decompress` in `apply` and update `update` to `Recreate` if the compression param changes
- Add the optional `compression` param to https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/actions/structure.ts#L92 and pass it to the `downloadParams` in the body.
- Then you can pass it the way you wanted in the original post.

Feel free to ask if you need more help.
