### ISSUE TITLE
Weird build error with 3.32.0

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#766]
Hi, 

My team and I have a custom molstar library and we created a custom theme where we color the atoms based on the electron's charge... 

Here is a snippet of the code:

```typescript
import { ColorTheme } from '../../mol-theme/color';
import { ThemeDataContext } from '../../mol-theme/theme';
import { Color, ColorScale } from '../../mol-util/color';
import { ParamDefinition as PD } from '../../mol-util/param-definition';
import { AtomPartialCharge } from '../../mol-model-formats/structure/property/partial-charge';
import { StructureElement, Unit, Bond, ElementIndex } from '../../mol-model/structure';
import { customColorList, customElectroStaticCharges, customDomain } from '../../quan-mol';
import { ColorThemeCategory } from './categories';

// ...


export const ElectroStaticColorThemeProvider: ColorTheme.Provider<{}, 'electrostatic'> = {
    name: 'electrostatic',
    label: 'Electrostatic',
    category: ColorTheme.Category.Misc,
    factory: ElectroStaticColorTheme,
    getParams: () => ({}),
    defaultValues: { },
    isApplicable: (ctx: ThemeDataContext) => true,
};

```

However, when I build the project and launch the `index.html` file that is produced, I get the following error:
![Screenshot 2023-03-29 at 10 12 14 AM](https://user-images.githubusercontent.com/7971405/228616159-521af6b4-81bf-4cd1-bb2d-f029b82554db.png)

And this is where the error lies in the code, according to the web console
![Screenshot 2023-03-29 at 10 13 12 AM](https://user-images.githubusercontent.com/7971405/228616386-99c56f2e-410a-4fee-a7b3-fc6893fb9f6f.png)

But, when I replace this line:
```typescript
 category: ColorTheme.Category.Misc,
```
with this:
```typescript
category: ColorThemeCategory.Misc
```

it works...I'm not sure if this is a bug or if this has to do with how namespaces work, but any clarity or guidance would be greatly appreciated here!

**Comment by dsehnal** [comment]
Internally, `ColorTheme.Category.??` works for us. We did change how this field is assigned though in an effort to reduce reliance in `namespaces`, but it seems like this causes other issues elsewhere.

I've actually ran into a similar issue when I tried to use `esbuild`, so it might be a bundler setting issue. I am not really sure what to do here now other than you having to fix this in your code.

**Comment by luna215** [comment]
@dsehnal can you point me to the PR where you changed how `ColorTheme` is assigned? I'm currently trying to dig deeper into this issue.

**Comment by dsehnal** [comment]
I don't think that will be much help https://github.com/molstar/molstar/commit/7384bebf4eb59d8953924415b5940e96001da5f3
I think the biggest problem is us using `namespaces` and how the TS compiler handles them. Refactoring things to not use them will be a lot of work and quite a few breaking changes (4.0 prolly).

**Comment by luna215** [comment]
@dsehnal happy to curate a list of where we use namespaces to slowly pick at the list if you think this would be helpful? Unless the team already has this list.

**Comment by dsehnal** [comment]
No, don't have the list. There was an attempt to change this in the past, but there were some issues with the implementation https://github.com/molstar/molstar/pull/481.

I think we can change some of the namespace uses to class/plain objects. In some cases, we might introduce a breaking change. 

If you would like to pick this up and create a check list (and perhaps with notes if can be changed without breaking changes), that would be very welcome.
