### ISSUE TITLE
Dynamic `require()` calls in LazyImport causes Webpack to skip bundling dependencies

### ISSUE THREAD

**Issue by russellp17** [molstar/molstar#767]
When trying to use HeadlessPluginContext I noticed that webpack fails to include the dependencies `gl`, `jpeg-js`, and `pngjs`. It seems that since they are being `require()`'d dynamically, Webpack does not recognize that they need to be included in the output bundle. Warning message looks like:  `Critical dependency: the request of a dependency is an expression`

cc @midlik

**Comment by dsehnal** [comment]
These dependencies are not mandatory (didn't want to force users who use this only in browser to have to install these, mostly because of the `gl` package which took several minutes to compile on my mac on each install) and that's why we chose to implement it this way.

If you want to use this with webpack, I think the best way would be to copy the headless plugin context code and include the dependencies with `import` like in the rest of the code.

**Comment by midlik** [comment]
Hi, I ran into the very same problem today. I'm starting to think that the whole idea of wanting GL there without being listed in the dependencies (and then using magic to import it) was bad. 
@dsehnal do you think we could move the responsibility of importing gl, jpeg-js, and pngjs to the caller? 
I mean, the HeadlessPluginContext would have a parameter in which the caller would have to supply the imported libraries. Something like this:
```
    import * as gl from 'gl';
    import * as pngjs from 'pngjs';
    import * as jpegjs from 'jpeg-js';
    const plugin = new HeadlessPluginContext({gl, png, jpegjs}, pluginSpec, canvasSize, options);
    ...
```
Does it make sense at all?

**Comment by dsehnal** [comment]
I am ok with that @midlik

**Comment by midlik** [comment]
OK, I will create a PR for this and change it there.

**Comment by dsehnal** [comment]
Although, I don't understand why you want to use the headless plugin with WebPack?

If you want to render screenshots on the browser, the standard `PluginContext` can be used for that too.

**Comment by dsehnal** [comment]
Oh, then molrender does that incorrectly. There is actually `molstar/lib/commonjs/<everything else the same>` which you can use in NodeJs directly without further compilation.

**Comment by midlik** [comment]
I got rid of the LazyImports in PR #772 . It is now responsibility of the caller to import gl, jpeg-js, pngjs and pass them to HeadlessPluginContext. Seems to work when "install" it in another project (i.e. copy the built files to node_modules) and build that one with Webpack.
@dsehnal could you check it and merge if OK?

**Comment by dsehnal** [comment]
> Seems to work when "install" it in another project (i.e. copy the built files to node_modules) and build that one with Webpack.

You can install npm packages from a directory to test btw.

I will have a look.

**Comment by russellp17** [comment]
thanks! The original error is resolved, but I do have a further couple suggestions

With the current approach, there aren't many guarantees about what version of the packages get passed in. It could be a different major version than what is expected. It also feels un-ergonomic to ask clients to pass in modules

Another approach is to make those dependencies `peerDependencies` and mark them as optional in [peerDependenciesMeta](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta). The benefits are:
- the packages won't be installed automatically for users because they're peerDepencies
- the `HeadlessPluginContext` and other usages have stronger guarantees about what version of the package is present
- no longer need the client to pass in the modules

**Comment by russellp17** [comment]
closing this out since the original issue is resolved now

I'm less sure about the peerDependencies approach after doing some more reading since it seems that [more recent versions of NPM install `peerDependencies`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies) regardless of whether they are optional

> In npm versions 3 through 6, peerDependencies were not automatically installed, and would raise a warning if an invalid version of the peer dependency was found in the tree. As of npm v7, peerDependencies are installed by default.

Although it's not clear to me that Yarn behaves the same way, so things could depend on which package manager client apps use. I do still think there's some risk of an unexpected version being passed in with the current approach, but it at least unblocks things

> Although, I don't understand why you want to use the headless plugin with WebPack?

The use-case is that you can have a build system that bundles together most of the dependencies into a single file before deploying to a Node env. For the headless case, you still need to install `headless-gl` on the Node host machine since there are bindings, but it simplifies the deployment somewhat

**Comment by dsehnal** [comment]
@russellp17 these are in `optionalDependencies`, but it might be the same. We will see and potentially tweak it later.
