### ISSUE TITLE
Issue with odd aromatic dash count 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#771]
I noticed this, probably it is something already known..
![image](https://user-images.githubusercontent.com/20627977/229158234-3657dbf1-b9a9-41d2-a04b-65606ed75f9f.png)

**Comment by arose** [comment]
Do you have a state or instructions to reproduce this?

**Comment by arose** [comment]
I see you literally mean an odd number of dashes. That is not supported (and not allowed with the params). Happy to review a PR though.
