### ISSUE TITLE
is there any observer to expand (full screen) action? 

### ISSUE THREAD

**Issue by bioinsilico** [molstar/molstar#777]
Hi molstar team!

I would like to change some behaviors based on molstar is on fullscreen or not. Is it possible to subscribe a method to this action?

Thanks a lot for your help!

**Comment by dsehnal** [comment]
You can subscribe to `plugin.layout.events.updated` and then check `plugin.layout.state`.

**Comment by bioinsilico** [comment]
Thank you, @dsehnal. This is what I needed.
