### ISSUE TITLE
Positive Dihedral Angle

### ISSUE THREAD

**Issue by bioinsilico** [molstar/molstar#78]
It seems that computed dihedral angles are always positive. Any 4 atoms selection and its reverse give the same positive angle. Is that intended ?

**Comment by dsehnal** [comment]
Yes, the label is always displayed as absolute value. Would it be more accurate to display it with the negative sign?

**Comment by bioinsilico** [comment]
I think dihedral angle signs are important, Ramachandran plots are commonly defined between -180 and 180 degrees

**Comment by bioinsilico** [comment]
Thank you David, now dihedral angles seem to have the expected values. At some point it will useful to have those changes in the npm repo

**Comment by dsehnal** [comment]
It's up already at npm.
