### ISSUE TITLE
Multi-scale SSAO can break rendering with very small viewports

### ISSUE THREAD

**Issue by MadCatX** [molstar/molstar#784]
Changes introduced by 9eb8714e11644558ac4c7d378155ea4ccff27b99 can lead to zero values of the downsampled dimensions if the viewport is very small in at least one dimension. This eventually leads to an exception here https://github.com/molstar/molstar/blob/5e1bb4b10698572c74c57e975414737ddabc2e5d/src/mol-gl/webgl/texture.ts#L282 and then the renderer gets stuck in a weird state. Ensuring that `s[h|w]` `h[h|w]` and `q[h|w]` have a value of at least 1 fixes the problem for me.

**Comment by arose** [comment]
thanks, should be fixed with 55e940e88c577803b73e6900b374900aea813dd2

**Comment by MadCatX** [comment]
Thanks, it indeed seems fixed!
