### ISSUE TITLE
Paint molecular surface using partial charge

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#785]
Hi, 

I created a custom preset that displays a polymer, ligand, and surroundings. This is the query I am using for the surroundings:

```typescript
export const ligandPlusSurroundings = StructureSelectionQuery('Surrounding Residues (5 \u212B) of Ligand plus Ligand itself', MS.struct.modifier.union([
    MS.struct.modifier.includeSurroundings({
        0: StructureSelectionQueries.ligand.expression,
        radius: 5,
        'as-whole-residues': true
    })
]));

export const ligandSurroundings = StructureSelectionQuery('Surrounding Residues (5 \u212B) of Ligand', MS.struct.modifier.union([
    MS.struct.modifier.exceptBy({
        0: ligandPlusSurroundings.expression,
        by: StructureSelectionQueries.ligand.expression
    })
]));

```

For the surrounding representation, I am using the `molecular-surface`, and for the coloring, I am using `partial-charge`, but this is the resulting visuals: 
![Screenshot 2023-04-12 at 3 39 46 PM](https://user-images.githubusercontent.com/7971405/231601747-e1a239dd-d613-424d-82a5-8ca15520b9ac.png)

It seems that the `partial-charge` isn't able to properly retrieve the atom charge for the surroundings? I also stumbled into this isssue https://github.com/molstar/molstar/issues/328 so is this still not implemented? I be happy to work on this with some guidance here. Thanks in advance!

**Comment by arose** [comment]
Are other representations colored by partial charge? Does the structure contain partial charge data?

**Comment by luna215** [comment]
@arose I'm not sure if there is partial charge data, but I do know that the atoms have a charge (is the charge of an atom different than partial charge?), but no other representation is using the `partial-charge`. I can add the partial charge to the ligand and this is what I get:
![Screenshot 2023-04-13 at 10 43 11 AM](https://user-images.githubusercontent.com/7971405/231841270-08c4bf4b-96eb-49ac-84c5-b4fa4a6fe02c.png)

I believe the ligand itself has partial charges as it does change the color. From the surroundings, I am able to access the atom schema, but I just get a charge of 0 for each atom. Can this be a bug?

**Comment by arose** [comment]
formal-charge and partial-charge are different. If they are not defined they will be 0. Hard to say if something is wrong without seeing the data.

**Comment by krab1k** [comment]
@luna215 Have a look at [Atomic Charge Calculator II](https://acc2.ncbr.muni.cz/), which has Mol* integrated with the support for the partial atomic charges via this [extension](https://github.com/molstar/molstar/tree/master/src/extensions/sb-ncbr).
