### ISSUE TITLE
`length` is undefined in `readAllLinesAsync`

### ISSUE THREAD

**Issue by russellp17** [molstar/molstar#788]
On this line: https://github.com/molstar/molstar/blob/18be09e9d5743893347cd83864bc9c2936e44a8e/src/mol-io/reader/common/text/tokenizer.ts#L177

`length` is undefined at runtime (at least in a recent run for me). It's surprising because I don't see a TS error, but it's true that there does not seem to be any `length` variable defined in that scope.

For the fix, I think it should be `state.length` (the outer `state`, because it gets shadowed in the callback), but not positive

**Comment by dsehnal** [comment]
That's weird. I've changed it to `state.length` in [47c2d15](https://github.com/molstar/molstar/commit/47c2d153aa7f5471e88b4df4df77e7e888bd74e2), hopefully that will fix it.

**Comment by russellp17** [comment]
it looks like you changed `readLinesAsync`, but was actually seeing this in `readAllLinesAsync` - also made that mistake when investigating 🤦

**Comment by dsehnal** [comment]
I see. Made one more commit. It's super weird the compiler doesn't warn about this.

**Comment by russellp17** [comment]
@dsehnal Thanks for addressing! Was able to verify locally that this addresses the error I hit, so going to close out the issue. If you're able to release a new molstar version that would be super helpful too

**Comment by dsehnal** [comment]
Going to do a new release over the weekend.
