### ISSUE TITLE
Big Outline scale issue?

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#791]
Is this normal? progressively increasing outline size seems to lead to an increased aliasing effect. 
![image](https://user-images.githubusercontent.com/20627977/232337258-6fd58435-557f-4b2b-96ac-2ff64e027ed4.png)

**Comment by arose** [comment]
It is just not that good with larger scale values. Increasing the threshold helps a bit.

**Comment by giagitom** [comment]
Ok thanks!
