### ISSUE TITLE
How to enable selection mode / measurements in the Docking Viewer?

### ISSUE THREAD

**Issue by mattpangenesis** [molstar/molstar#793]
Hi, thanks again for the guidance you provided the last time on customizing the Docking Viewer.

I'm now interested in trying to enable selection mode and measurements in the Docking Viewer, specifically in the Interactions view.

In the `create` function for the `Viewer` class (in `docking-viewer`), I set `viewportShowSelectionMode: true,`.

However, when I click the Select button that shows up, nothing happens, and I don't get the selector palette that I normally get at the top with the normal viewer (e.g. the one that allows me to select "Residue", etc). And thus can't set measurements, or make further customizations.

I'm assuming I'm missing some other setting. Thanks so much!

**Comment by dsehnal** [comment]
The docking example defines it's own custom viewport component in https://github.com/molstar/molstar/blob/master/src/apps/docking-viewer/viewport.tsx#L1

You might compare it with the build in implementation https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/plugin.tsx#L226

**Comment by mattpangenesis** [comment]
thank you so much!
i got the control to show up by adding `<SelectionViewportControls />`.

however, clicking on the residues still doesn't cause them to actually be selected (it just nothing). any further guidance on where I should be looking?

much appreciated, even rough pointers are helpful so I can learn to be self-sufficient over time.

**Comment by arose** [comment]
in the default viewer we have behavior that bind a mouse action with things like select/highlight, see https://github.com/molstar/molstar/blob/master/src/mol-plugin/behavior/dynamic/representation.ts
