### ISSUE TITLE
How to visualize particular chain?

### ISSUE THREAD

**Issue by haotianteng** [molstar/molstar#794]
Is there a way in Molstar to visualize only a particular chain, for example, chain A of the protein? I can hide the Ions/water/protein but I didn't find a way to hide/view certain chain.

**Comment by MadCatX** [comment]
You will probably have to use MolQL selection scripts to do this with sufficient flexibility. If you're using the plain Mol* Viewer, you can display the State Tree, expand the Polymer item, click "Apply Action" -> "Selection". You can use this example Expression below to filter only A chain:

```(sel.atom.atom-groups :atom-test (= atom.chain A))```

Then you can hide the entire Polymer and add a 3D Representation only for your selection.

![image](https://user-images.githubusercontent.com/1009657/233110501-d2742b9d-3b5a-43ab-8daa-b7f5ed27f006.png)
