### ISSUE TITLE
adding a surface representation to a residue selection

### ISSUE THREAD

**Issue by andreassteffen** [molstar/molstar#799]
Hi,
I would like to add a surface representation to selected residues of a protein structure.
```
const structureData = window.molstar.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
const sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
    "residue-test": MS.core.set.has([
        MS.set(...selected_residues),
        MS.ammp("auth_seq_id"),
    ]),
    'group-by': Q.struct.atomProperty.macromolecular.residueKey()
}), structureData)
```
How can I add the surface representation to my selection sel?
Many thanks, Andreas

**Comment by dsehnal** [comment]
You can use one of the `plugin.builders.structure. tryCreateComponent*` functions and then `plugin.builders.structure.representation` on the result of that.
