### ISSUE TITLE
Measurements selection broken

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#80]
- selecting residue ranges by holding shift will report incorrect number in `Measurements` component (range of 4 residues selected from sequence but only the 2 selections are recognized)
- deleting selections in `Measurements` component won't propagate elsewhere

<img width="1680" alt="selection" src="https://user-images.githubusercontent.com/9744615/91484915-d1a45880-e85e-11ea-8874-1c79aa75f282.png">

**Comment by dsehnal** [comment]
> selecting residue ranges by holding shift will report incorrect number in Measurements component (range of 4 residues selected from sequence but only the 2 selections are recognized)

That's a feature. What you describe creates 2 selections, one the original one and the other one with the entire range. 

If you want the 4 residues as different selections, you need to click on the 4 residues one by one and then they will show as 4 entries.

> deleting selections in Measurements component won't propagate elsewhere

This is intended. The entries in the that list are "history" and editing the list only affects the entries from which the measurements will be created.

---------

Having said that I agree that the "measurement experience" can be improved upon. Do you have any suggestions for better UX?

**Comment by JonStargaryen** [comment]
That makes sense, thanks @dsehnal. I was somewhat confused while checking in on the positive angle fix.

> Having said that I agree that the "measurement experience" can be improved upon. Do you have any suggestions for better UX?

- An 'explode selection(s)' option could be useful to some. Select a sequence range and 'explode' at 'residue' granularity would yield all distinct residues as selections. Select a residue and 'explode' at 'atomic' granularity would yield all atoms.
- A 'Move to top' button could be useful for larger selection lists.

**Comment by dsehnal** [comment]
>     * An 'explode selection(s)' option could be useful to some. Select a sequence range and 'explode' at 'residue' granularity would yield all distinct residues as selections. Select a residue and 'explode' at 'atomic' granularity would yield all atoms.
> 

Maybe add an option that works on the entire current selection that will create individual entries from:

- all atoms
- C-alpha atoms
- residues
- backbone

?

And possibly add more options like "show torsion angles" for currently selected residue range?

>     * A 'Move to top' button could be useful for larger selection lists.

- The list will only show latest 4 entries, so the move to top could be an overkill.

**Comment by JonStargaryen** [comment]
> Maybe add an option that works on the entire current selection that will create individual entries from:
> 
> * all atoms
> * C-alpha atoms
> * residues
> * backbone
> 
> ?

Might be useful in general. But has diminishing returns as the history size is limited to 4 entries.

> And possibly add more options like "show torsion angles" for currently selected residue range?

Seems nice. Another possible addition would be dedicated options to show the phi/psi angles for a selected amino acid.

**Comment by arose** [comment]
Anyone wants to follow up on one of the above suggestions?
