### ISSUE TITLE
Selecting residues from particular asymmetric unit

### ISSUE THREAD

**Issue by skrhakv** [molstar/molstar#806]
Hello,

Thanks for the great tool you are developing here!

I would like to select the first N residues starting from position X automatically from a specified chain. Here is what I've got:
```
// let's say that X=0, N=123
// select structure
let data = this.plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;

let selection = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
        'chain-test': Q.core.rel.eq(['A', Q.ammp('auth_asym_id')]), // select chain-id='A'
        'residue-test': MS.core.rel.inRange([MS.ammp('label_seq_id'), 0, 123])  // select range [0, ..., 122]
}), data);
let loci = StructureSelection.toLociWithSourceUnits(selection);

this.plugin.managers.interactivity.lociSelects.selectOnly({ loci });
```

However, I am running into problems with structures like the [1VWM](https://www.rcsb.org/3d-view/1VWM). The problem is, that the structure is assembled from four identical chains, which is repeated 4 times. So when I use the `selection` as in the example, the residues will get selected from EVERY CHAIN. However, I would like to select only the residues from the first chain.

Is there a way how to do that in Mol*? I've already searched the examples and the source code, however, I haven't found anything that would help my situation.

Maybe the function `MS.struct.filter.first(...)` might be helpful to filter the first N residues, but I wasn't able to put the correct parameters there, as I found no examples in the source code for that kind of operation (only how to select the first residue).

I would greatly appreciate any assistance regarding this issue.

Thank you!

**Comment by skrhakv** [comment]
Hi David,

Thank you very much for your reply!

 I implemented the solution as you suggested:
```
let data = this.plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
if (!data) return;
let selection = Script.getStructureSelection(Q => MS.struct.filter.first([
    Q.struct.generator.atomGroups({
        'group-by': Q.struct.atomProperty.macromolecular.residueKey(),
        'chain-test': Q.core.rel.eq(['B', Q.ammp('auth_asym_id')]), // select chain-id='B'
        'residue-test': MS.core.rel.inRange([MS.ammp('label_seq_id'), 0, 100])  // select range [0, ..., 100]
    })]), data);
let loci = StructureSelection.toLociWithSourceUnits(selection);

this.plugin.managers.interactivity.lociSelects.selectOnly({ loci });
```

Unfortunately, this solution selects only the first residue from each asymmetric unit, as you can see in the video screen which I attached to this comment: [Screencast from 2023-04-28 12-03-27.webm](https://user-images.githubusercontent.com/57826305/235121477-b8babf73-93d7-497a-95b4-66559c3390e9.webm)

From the video you can observe, that only first residue from each asymmetric unit is selected, however, I would like to select first N residues from the first asymmetric unit (in this case N=100).

I also tried some alternatives to `.residueKey()` like: `.chainKey()`, `.entityKey()` and others, but I never got the desired result.

Could you please take a look if I implemented the solution correctly, and possibly point me in the right direction?

Many thanks for your help!

**Comment by dsehnal** [comment]
Try grouping by operator name.

**Comment by skrhakv** [comment]
Could you please expand on what you mean by that?

**Comment by dsehnal** [comment]
`struct.atomProperty.core.operatorKey()` (or `operatorName`) will group things together by unique assembly operators.

**Comment by skrhakv** [comment]
Splendid, adding:
```
 "group-by": MS.struct.atomProperty.core.operatorName()
```
is what did the job.

I am deeply grateful for your help. Thanks, David!
