### ISSUE TITLE
how to define display order of components?

### ISSUE THREAD

**Issue by ccbiozhaw** [molstar/molstar#814]
Hello. I would like to create a new component from a selection, color it and display it over the initial protein. for example i want to select a loop, color it and highlight it on top of the initial protein. However, it seems as though elements that components created first display over components created later? in the image below, the component active can not be displayer over the component polymer however, it is possible to first create a new component "helix", then create a new component from the whole protein "protein", which then behaves in the desired way. is there a way to manually define which component displays over an other? or reorder the component tree?

![image](https://user-images.githubusercontent.com/80820813/236767140-f8f4ca41-e335-4f13-84e8-b4065b63d3af.png)

**Comment by dsehnal** [comment]
There is currently no way to reorder. However, if you just want to recolor, you can apply an overpaint instead which will apply the color directly to the original visual.
