### ISSUE TITLE
Iterating over atomgroups grouped by operatorName

### ISSUE THREAD

**Issue by Simard302** [molstar/molstar#818]
I would like to create several StructureSelections, each for a different asymmetric unit. My current code for generating the query is:
```typescript
const queries = MS.struct.generator.atomGroups({
    'residue-test': MS.core.rel.eq([resId, MS.ammp('label_seq_id')]),
    'chain-test': MS.core.rel.eq([chainId, MS.ammp('label_asym_id')]),
    'group-by': MS.struct.atomProperty.core.operatorName()
});
// Iterate over groups to create individual selections
for (const q in ...) {
    const selection = Script.getStructureSelection(
        q,
        structure
    );
}
```
How would I iterate over every atom grouped that was grouped by "operatorName"? I know to only filter the first one, I can do 
```typescript
const query = MS.struct.filter.first([queries])
```
but I would like to do the same for each entry

**Comment by dsehnal** [comment]
You can use `StructureSelection.forEach` to iterate over each group on the result of `Script.getStructureSelection`. 

-----------

Also, if you are building the selections in code and don't need to use it in the state tree (and even then if you convert the result to  a "bundle"), you don't need to use the builder at all can call the queries directly, for example:

```ts
const ctx = new QueryContext(structure);
const query = Queries.generators.atoms({
    residueTest: l => StructureProperties.residue.label_seq_id(l.element) === 123
});
const result = query(ctx);
StructureSelection.forEach(result, s => ...);
```

**Comment by Simard302** [comment]
The `StructureSelection.forEach(result, s => ...)` gives me access to a structure to use an an iterand. If I wanted to create a loci for each group in the selection, how would I achieve this from the structure starting point?

In the end, my goal is to create a label for each group of residue in my selection. I use 
```javascript
const loci = StructureSelection.toLociWithSourceUnits(...);
await this.plugin.managers.structure.measurement.addLabel(loci, { ... } )
```
to create my label, but this requires a `StructureSelection` object for creating the loci.

**Comment by dsehnal** [comment]
```ts
const toLabel: Loci[] = [];
StructureSelection.forEach(result, s => toLabel.push(Structure.toSubStructureElementLoci(s)));

for (const l of toLabel) {
   await await this.plugin.managers.structure.measurement.addLabel(l, ...);
}
```

Something like this. You should not do the await inside the `.forEach` because that would break the state as all the update would be executed simultaneously.
