### ISSUE TITLE
How To: create spheres, do highlights, create clipping objects

### ISSUE THREAD

**Issue by corredD** [molstar/molstar#82]
Can someone point me on how to from the basic-wrapper example or if it need an extension : 
- create a sphere at a given center with a given radius 
- show/hide and highlight/select at the "model" level. I found some example in basic-wrapper but the selection was on 'residue-test'.
- create clipping object 

Thanks in  advance

**Comment by dsehnal** [comment]
> 
> 
> Can someone point me on how to from the basic-wrapper example or if it need an extension :
> 
>     * create a sphere at a given center with a given radius

If you want custom visuals, you need to create a custom Representation that builds it and then a Transform, that adds it to the state tree.

Rough guideline:

- Create ``MySphereRepresentation`` that uses ``MeshBuilder`` to build your geometry (you can base it say on https://github.com/molstar/molstar/blob/master/src/mol-repr/shape/model/unitcell.ts that draws unit cell box) 
- the transform will look something like this

```ts
const CreateTransformer = StateTransformer.builderFactory('my-namespace');

export const CreateSphere = CreateTransformer({
    name: 'create-sphere',
    display: 'Sphere',
    from: PluginStateObject.Root, // or whatever data source
    to: PluginStateObject.Shape.Representation3D,
    params: {
        center: PD.Vec3(Vec3()),
        radius: PD.Numeric(1)
    }
})({
    canAutoUpdate({ oldParams, newParams }) {
        return true;
    },
    apply({ a, params }, plugin: PluginContext) {
        return Task.create('Custom Sphere', async ctx => {
            const repr = MySphereRepresentation({ webgl: plugin.canvas3d?.webgl, ...plugin.representation.structure.themes }, () => ({ /* params here */  }));
            await repr.createOrUpdate(params, data).runInContext(ctx);
            return new PluginStateObject.Shape.Representation3D({ repr, source: a }, { label: `My Sphere` });
        });
    }
});
```

- Then you can can do ``plugin.build().toRoot().apply(CreateSphere, { ... }).commit()``

That's a lot of steps to draw a bloody sphere :) Anyway, this could use a nicer API, I will think about adding a custom geometry builder to make this process easier in the future.

> 
>     * show/hide and highlight/select at the "model" level. I found some example in basic-wrapper but the selection was on 'residue-test'.

You can highlight a whole object with this command https://github.com/molstar/molstar/blob/master/src/mol-plugin/commands.ts#L47 (you will need to pass the ref of the structure object or below for it work).

```
PluginCommands.Interactivity.Object.Highlight(this.plugin, { ref: refs /** one or more refs **/, state: this.plugin.state.data });
```

You can use the selection as well as shown in the basic-wrapper example and tweak it make a test at the ``entity-test`` level to check for some model-level properties https://github.com/molstar/molstar/blob/master/src/mol-script/language/symbol-table/structure-query.ts#L270 (I just hope they are "implemented", if not I will fix it).

The ``ClearHighlights`` to clear.

> 
>     * create clipping object
> 

By specifying renderer clipping objects:

```
this.plugin.canvas3d?.setProps({ renderer: { clip: ....  } })
```

https://github.com/molstar/molstar/blob/master/src/mol-gl/renderer.ts#L80

> 
> Thanks in advance

**Comment by corredD** [comment]
thanks a lot for the quick and thorough reply. 
This is great I was able to do the clipping plane and the sphere. About the sphere, is it possible to change the rendering for it ? like double side, or only back face ?

Also I am still struggling with the highlight though. What should be the selection query if I want all the entity with a given name ? or a given model id ? I tried the following with no success : 
if aName is a string corresponding to the entity name
`const sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
                                    'entity-test': Q.core.rel.eq([Q.struct.atomProperty.core.modelIndex, modelIdx])
                                }), structure);`

` const sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
                'entity-test': Q.core.rel.eq([Q.ammp('entityKey'), aName])
            }), data);      `

`const sel = Script.getStructureSelection(Q => Q.struct.generator.atomGroups({
                'entity-test': Q.core.rel.eq([Q.struct.atomProperty.macromolecular.entityKey, aName])
            }), data);`
I would just like to be able to reproduce the mouse over with the granularity "model".

Thanks again for your help !

**Comment by arose** [comment]
> About the sphere, is it possible to change the rendering for it ? like double side, or only back face ?

For mesh geometries there are `doubleSided` and `flipSided` params, see https://github.com/molstar/molstar/blob/master/src/mol-geo/geometry/mesh/mesh.ts#L331-L332. Add these parameters to `/* params here */` in the example in the earlier comment.


> What should be the selection query if I want all the entity with a given name

Note that entityDescription is a list.

```
MS.struct.generator.atomGroups({
    'entity-test': MS.core.list.equal([MS.list(...names), MS.ammp('entityDescription')])
})
```

> or a given model id ?

`Q.struct.atomProperty.core.modelIndex` should work. It is, for mmcif or pdb files, usually a number starting from one (note that this is typed as a string because mmcif defines it as such). We don't currently expose the index of a model in the array of models backing a structure object.

**Comment by arose** [comment]
Also, for doubleSided to work you need to set quality: 'custom' if I remember correctly.

**Comment by corredD** [comment]
Thanks you all for the precious help. I was able to do everything I wanted !
I ended up using a Unit-test instead of the entity and I am happy with the results.
e.g :
`            const q = Queries.generators.atoms({
                unitTest: ctx => {
                    return (
                        SP.unit.model_entry_id(ctx.element) === aName
                    );
                }
            });
            const loci = StructureSelection.toLociWithSourceUnits(StructureQuery.run(q, data));
`
