### ISSUE TITLE
switch off z-depth culling programmatically

### ISSUE THREAD

**Issue by andreassteffen** [molstar/molstar#821]
Hi,
can I programmatically switch off the z-depth culling after focusing on a residue?
![image](https://github.com/molstar/molstar/assets/1114010/a1e34b4d-0f17-4c7f-8c1a-8d29739e7cab)

**Comment by andreassteffen** [comment]
not possible?

**Comment by arose** [comment]
`ctx.canvas3d?.setProps({ cameraClipping: { far: false } })` with ctx being the PluginContext should do the trick

**Comment by andreassteffen** [comment]
thanks
