### ISSUE TITLE
Override Selection Color with Overpaint

### ISSUE THREAD

**Issue by chemsseddine** [molstar/molstar#829]
Hi ,

first , thanks for the great work 

I want to ask if it's possible to select loci , to be able to highlight it in the sequence panel and also to override the colors with overpaint ?
```
...
const loci = StructureSelection.toLociWithSourceUnits(sel);
plugin.managers.structure.selection.fromLoci('add', loci);
```

and after that , I want to color the chains differently (to override the green default color given for selected/highlighted residue)

```
Object.values(highlightedChains).forEach((range, ix) => {
	const color = colors[ix] // here giving a random color;
	const [start, stop] = range;
	params.layers.push({
		script: Script(
			`(sel.atom.res (in-range atom.resno ${start} ${stop}))`,
			language
		),
		color: randoms[ix],
		clear: true,
	});
});

...

update.to(repr).apply(OverpaintStructureRepresentation3DFromScript, params);
```

overpaint is applied but not overriding the selection color , any idea how to achieve this ?

<img width="797" alt="image" src="https://github.com/molstar/molstar/assets/6200384/47ca46c2-6b8f-4f4b-b201-75de80ff6fd9">

thanks

**Comment by chemsseddine** [comment]
@dsehnal or @arose  is there any way to do this ? (coloring chain  differently and having the sequence highlighted at same time)

**Comment by dsehnal** [comment]
You can override the selection color for the whole scene, but not per overpaint.

What is the UX you want to  achieve by this?

**Comment by chemsseddine** [comment]
awesome @dsehnal , that worked  thanks a lot
