### ISSUE TITLE
Injection of bond orders for PDB

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#832]
Hello Molstar devs.

Following on from previous discussions [here](https://github.com/molstar/molstar/issues/626) about bond orders for PDB files I'd like to ask some questions about some workarounds we've tried. Our overall aim is to use the mmcif format but migrating across to the new format is proving challenging. As such we've been looking at workarounds for getting them included.

We can calculate the bond orders using an external package and have been looking at ways to insert them when the PDB file is loaded. We have tried merging an external `chem_comp_bond` table into resulting mmcif after the PDB is loaded. That is, within `trajectoryFromPDB` (`mol-model-formats/structure/pdb.ts`) after `pdbToMmCif` is called. Essentially we create the new `CifFrame` with the following code:

```
const newCif = {
  …cifFromPdb,
  categoryNames: […cifFromPdb.categoryNames, "chem_comp_bond"],
  categories: {…cifFromPdb.categories, ["chem_comp_bond"]: tableFromExternal
}
```

Where `tableFromExternal` is created using `Table.ofPartialColumns(mmCIF_Schema.chem_comp_bond, …)`

However, this manual insertion does not appear to work as expected. The data is included in the new cif, but it is not respected when the trajectory is created. I would appreciate any help on this, and I also understand this is an unusual request given we are not using Molstar for its intended purpose.

Thanks in advance,

Jason

**Comment by arose** [comment]
At that point I think you need to add it manually using `ComponentBond.Provider.set()`, from `src\mol-model-formats\structure\property\bonds\chem_comp.ts`.

**Comment by jpattle** [comment]
Hi Alexander, thanks for the suggestion. I've tried this out but it didn't seem to work, perhaps I've done it in the wrong way?

I've created a branch with my experiment [here](https://github.com/jpattle/molstar/tree/bond-order-investigation). Essentially I've added two more format providers in the extensions folder to load PDB and mmCIF files while manually injecting a set of hard-coded bond order data (for structure 1udt, test files exist in the branch).

The code where I manually inject the bond orders can be found [here](https://github.com/jpattle/molstar/blob/bond-order-investigation/src/extensions/bond-order-insertions/pdb-add-mock-bond-orders.ts#L38)

The code where I have tried the above suggestion to use `ComponentBond.Provider.set()` can be found [here](https://github.com/jpattle/molstar/blob/bond-order-investigation/src/extensions/bond-order-insertions/model-bond-order-edits.ts#L164).

Please let me know if I'm doing something incorrect, thank you for your help!

**Comment by arose** [comment]
@jpattle did you got it to work?
