### ISSUE TITLE
[image-renderer] gl return null 

### ISSUE THREAD

**Issue by yooki0328** [molstar/molstar#841]
I am using image-renderer to draw a thumbnail of a protein structure. I can generate the image successfully on my local machine (MacBook Pro). However, when I deploy this service to a Linux server, it fails to render the image properly.
<img width="828" alt="image" src="https://github.com/molstar/molstar/assets/17794392/5a785cf6-5299-4e52-af2f-34e55721f02a">

**Comment by arose** [comment]
From the error it looks like the WebGLRenderingContext `gl` is not defined. How do you create it? Note that you need to provide certain modules to `HeadlessPluginContext`, see https://github.com/molstar/molstar/blob/f428e9f39ebbe962d5e580bfe75dd6ed3a71b190/src/mol-plugin/headless-plugin-context.ts#L22

**Comment by yooki0328** [comment]
> 
The code created is as follows:
```javascript
import * as fs from 'fs';
import * as gl from 'gl';
import * as pngjs from 'pngjs';
import * as jpegjs from 'jpeg-js';

import { HeadlessPluginContext } from 'molstar/lib/commonjs/mol-plugin/headless-plugin-context';
import { DefaultPluginSpec } from 'molstar/lib/commonjs/mol-plugin/spec';
import {
  ExternalModules,
  defaultCanvas3DParams,
} from 'molstar/lib/commonjs/mol-plugin/util/headless-screenshot';
import { setFSModule } from 'molstar/lib/commonjs/mol-util/data-source';
import { ColorNames } from 'molstar/lib/commonjs/mol-util/color/names';

setFSModule(fs);

let plugin;

const initPlugin = async () => {
  const externalModules: ExternalModules = { gl, pngjs, 'jpeg-js': jpegjs };
  const canvas3d = defaultCanvas3DParams();
  canvas3d.renderer.backgroundColor = ColorNames.black;
  canvas3d.camera.fov = 30;
  plugin = new HeadlessPluginContext(
    externalModules,
    DefaultPluginSpec(),
    undefined,
    {
      canvas: canvas3d,
    },
  );
  await plugin.init();
};

```
The same code works fine on a Mac Pro environment. However, it fails to work when launched through Docker on a Linux server environment.

**Comment by russellp17** [comment]
Is there an X server running in your Linux environment? I would assume it's not if it's a server

`headless-gl` gives some suggestions on how to set this up: https://github.com/stackgl/headless-gl#how-can-headless-gl-be-used-on-a-headless-linux-machine where the easiest solution should look something like `xvfb-run node program.js`

**Comment by yooki0328** [comment]
Yes, I tried using xvfb, but the speed of generating images was slow. I currently have a Linux server with an Nvidia GPU, so I'm wondering if it's possible to generate images without using xvfb?

**Comment by arose** [comment]
> I'm wondering if it's possible to generate images without using xvfb?

Not that I know of. Also in my experience the rendering speed is not a big limiting factor when creating images. Parsing the input, creating the geometry and writing png/jpg files all happen on the CPU and take more time.
