### ISSUE TITLE
How can I move one of the structures when multiple structures are loaded?

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#844]
<img width="670" alt="image" src="https://github.com/molstar/molstar/assets/1294316/1bdb526a-f411-430f-960d-38f2dc087bfc">

very thanks~

**Comment by dsehnal** [comment]
You can apply a "Transform Conformation" action to the structure node: 
![image](https://github.com/molstar/molstar/assets/21145776/846251b9-9db9-44a5-9043-ae8421deef0f)

or try to use the superposition (albeit that one is quite basic now);

![image](https://github.com/molstar/molstar/assets/21145776/bc204af9-a68d-4969-89c5-05e72987e1f2)

**Comment by luckyxutao** [comment]
th
