### ISSUE TITLE
Chrome webgl issue

### ISSUE THREAD

**Issue by lcsthom** [molstar/molstar#845]
Hello guys, did you see that there is an issue with chrome ? 

We have a webgl issue, the same issue was there during a few hours I think a few months back. Each occurrence seems to be linked to a chrome update but I'm not entirely sure of it. Modifying "Use hardware acceleration when available" chrome option does fix the issue. 

![image](https://github.com/molstar/molstar/assets/17882765/f02e9e90-e7ef-48de-972e-6f716328e74e)

I'm copying the issue I created in the website repo here as it seems more lively  (https://github.com/molstar/molstar.github.io/issues/10)

**Comment by lcsthom** [comment]
In fact we have this console error : 
![image](https://github.com/molstar/molstar/assets/17882765/c7af8813-1024-4443-aeb9-31b1ba4d5267)

**Comment by dsehnal** [comment]
I have just tested Chrome 114 on PC and MacOS and both work for me.

**Comment by lcsthom** [comment]
Ok, I'm running it on ubuntu but the chrome is the 114 too (Version 114.0.5735.198 (Official Build) (64-bit)) what is even more weird is when we test webgl it works => https://get.webgl.org/ can see the spinning cube.

**Comment by qubit-nathan** [comment]
I have also the same problem. I use ubuntu 22.04.2, I have chrome version 114.0.5735.198. The same console error if I use the website: https://molstar.org/viewer/. 
- If I use this site: https://get.webgl.org/, webgl seems to works just fine. 
- If I use breakpoints in https://molstar.org/viewer/ and remove the option: [powerPreference: "high-performance"] from the powerPreference in the file molstar.js, the error doesn't show anymore but I have those warnings: 
![image](https://github.com/molstar/molstar/assets/135967487/a54c0f2f-40f0-45bf-a024-8c269dbdb145)

**Comment by dsehnal** [comment]
@arose  any ideas?

**Comment by arose** [comment]
Hmm, is this recent or have seen it with Chrome version before 114? There was a Chrome bug in 2022 but it is marked as fixed, see https://bugs.chromium.org/p/chromium/issues/detail?id=1283929.

Does https://codepen.io/arose/pen/qBQrQjz show an error?

**Comment by lcsthom** [comment]
It works now

**Comment by JonStargaryen** [comment]
Hi,

one of our team members experiences this issue since February. Only in Chrome (current version). WebGL itself works on https://get.webgl.org/. Mol* itself works in Safari. Unclear if there's a console error for https://codepen.io/arose/pen/qBQrQjz, can double-check if needed.

Are you by any chance aware of issues in Chrome that might cause this?
More of an FYI, she's using Safari as fallback for now.

**Comment by arose** [comment]
I am not aware of any issue. Would be good to have some more info.

- what Browser version exactly 
- are GPU drivers up-to-date?
- any errors in the Browser console?
- output of `chrome://gpu/`

**Comment by JonStargaryen** [comment]
Hi, here's all the gathered info:

> what Browser version exactly

Chrome 126.0.6478.127 (x86_64)

> are GPU drivers up-to-date?

Yes, it's a MacBook Pro with Intel Iris Plus Graphics. OS and drivers are up-to-date.

> any errors in the Browser console?

Yes, same error and stack trace as above.

> output of chrome://gpu/

Please find the corresponding output attached. Output was obtained before the OS/driver update.

> Unclear if there's a console error for https://codepen.io/arose/pen/qBQrQjz, can double-check if needed.

No error message here.

[about-gpu.txt](https://github.com/user-attachments/files/16130981/about-gpu.txt)

**Comment by arose** [comment]
```
*   WebGL: Software only, hardware acceleration unavailable
*   WebGL2: Software only, hardware acceleration unavailable
*   WebGPU: Software only, hardware acceleration unavailable
```

To allow molstar without hardware acceleration you need to add a GET param `?allow-major-performance-caveat=1`. But note that it will be slow to render anything not small or at a normal resolution/fullscreen!

**Comment by JonStargaryen** [comment]
Got it, thanks. Will try to remember this if the issue comes up again.
