### ISSUE TITLE
Add distance between atoms mol* plugin

### ISSUE THREAD

**Issue by m-iguel** [molstar/molstar#846]
Hello, 

I am trying to render a pdb in a mol* plugin and following the example from the documentation (https://molstar.org/docs/plugin/) I am able to do so, however, I want to display the distance between atoms 2 and 100 programatically. In order to do so, I developed the following snippet of code but I am having a lot of issues when accessing the 'structure' object to later call the addDistance function on it. The code is the following:

```
<style>
    #app {
        position: absolute;
        left: 100px;
        top: 100px;
        width: 800px;
        height: 600px;
    }
</style>

<link rel="stylesheet" type="text/css" href="./molstar.css" />
<script type="text/javascript" src="./molstar.js"></script>

<div id="app"></div>

<script type="text/javascript">

    molstar.Viewer.create('app', {
        layoutIsExpanded: false,
        layoutShowControls: false,
        layoutShowRemoteState: false,
        layoutShowSequence: true,
        layoutShowLog: false,
        layoutShowLeftPanel: true,

        viewportShowExpand: true,
        viewportShowSelectionMode: false,
        viewportShowAnimation: false,

        pdbProvider: 'rcsb',
        emdbProvider: 'rcsb',
    }).then(viewer => {
        viewer.loadPdb('2dn1').then(() => {
            const plugin = viewer.plugin;
            const measurementManager = plugin.managers.structure.measurement;
            const structure = plugin.managers.structure.hierarchy.current.structures[0];
   
            const atom1 = 2; // Atom index 2
            const atom2 = 100; // Atom index 100

            const line = viewer.managers.structure.measurement.addDistance(atom1, atom2);
            line.style.color = 0xff0000; // Set line color (red)

            viewer.managers.structure.measurement.setVisibility(true); // Show the distance measurement

            viewer.render(); // Trigger a re-render to update the view
        });
    });
</script>
```

So far I have been able to load the strucre correctly (the 'structure' object is not undefined). However, I am lost on how I can use this structure to select the atoms I need to measure the distance between and given them to the addDistance function.

I already checked these two issues that ask something similar:

#439 
#449 

But I am still unable to handle the structure properties correctly. I would very much appreciate if anyone can point me in the right direction or provide any implementation examples if there are.

I hope this is clear and not too obvious of a question. Thank you in avance :)

**Comment by dsehnal** [comment]
Hi,

unfortunately, the current implementation doesn't all to do what you want as easily and the feature cannot be used directly from the compiled code.
