### ISSUE TITLE
Color plddt scores from local PDB files

### ISSUE THREAD

**Issue by mzhang5579** [molstar/molstar#849]
Hi,
I've been trying to map these proteins from local pdb files based on model confidence like AlphaFold (90-100 dark blue, 70-90 cyan, 50-70 yellow, 0-50 orange). The plddt scores per residue are found in the Beta column on the pdb files just like alphafold's pdb file, but not sure how to color based on model confidence and whether this is even possible.

**Comment by dsehnal** [comment]
Can you generate the same mmCIF file that are available in the AlphaFoldDB? Then you will get the coloring for free without extra work.

**Comment by arose** [comment]
the `uncertainty` color theme uses the data from a PDB file's beta column
