### ISSUE TITLE
Ligand selection does not pick N-terminal acetyl

### ISSUE THREAD

**Issue by midlik** [molstar/molstar#856]
If I understand correctly, the 'ligand' static component should contain any non-polymer residues bound to the protein N-terminus or C-terminus. However, I noticed that in 2fq5 this works for the C-terminal amide (NH2) but not for the N-terminal acetyl (ACE). 

<img width="625" alt="Screenshot 2023-07-07 at 11 34 12" src="https://github.com/molstar/molstar/assets/14818844/f3a6f215-8079-4adc-8425-bfaf475fce85">

**Comment by arose** [comment]
Actually, we want to exclude protein caps from the ligand definition which was missing for NH2. I added more caps in #859.

**Comment by midlik** [comment]
Oh I see. It was exactly the opposite than I thought :D
Thanks for fixing.

Anyway, I found another related suspicious thing. 
In 1gkt, residue A SUI 54 is treated as non-standard and shown in ball-and-stick - that's fine. But B LOV 6 is treated as a ligand, i.e. its neighbours are shown in ball-and-stick as well. Is this intentional?
Similarly for the OPN residue in 1hzs - could you please check if this is what it should look like?
![Screenshot 2023-07-10 at 12 14 57](https://github.com/molstar/molstar/assets/14818844/5d4aa1bb-374a-451d-accd-912d5ba8104a)
![Screenshot 2023-07-10 at 12 15 35](https://github.com/molstar/molstar/assets/14818844/b8935e4d-f099-4969-8d05-d39120071fe8)

**Comment by arose** [comment]
Both cases are intentional, that said the display of PRDs and Peptide Nucleic Acids is not the best but haven't come up with a better heuristic.
