### ISSUE TITLE
how to fixed zoom?

### ISSUE THREAD

**Issue by yooki0328** [molstar/molstar#866]
I am currently using Mol* to visualize protein structures, and I have multiple PDB files generated by a specific algorithm. These PDB files exhibit subtle differences in their structures. I would like to showcase these structural changes using a carousel mode. Currently, I am using the following approach:

Load PDB1
Execute plugin.clear()
Load PDB2
Execute plugin.clear()
Load PDB3
...
Repeat the process for all PDB files
However, with this approach, the resulting zoom level differs significantly, and the spatial positioning of the structures also varies greatly. I am seeking guidance on how to maintain a consistent zoom level throughout the visualization process.

Alternatively, I am open to exploring other solutions, such as using a trajectory. However, I am unsure about the steps involved in implementing this feature effectively.

I would greatly appreciate any advice, suggestions, or best practices to achieve my goal of displaying multiple protein structures with consistent zoom or any alternative approaches like utilizing trajectories.

Thank you for your assistance!

**Comment by yooki0328** [comment]
I need your help, thanks!

**Comment by yooki0328** [comment]
I'm currently using this workaround where I add it first, then delete it, and then set the color again. However, the result is not very satisfactory.

```
const structureOptions = getStructureOptions(this.viewer!.plugin.state.data);
        const structureRef = structureOptions.options[0][0];
        await this.viewer?.loadStructureFromData(pdbStr, format);

        PluginCommands.State.RemoveObject(this.viewer!.plugin, {
            state: this.viewer!.plugin.state.data,
            ref: structureRef,
        });

        setTimeout(() => {
            this.coloring.applyDefault();
        }, 0);
```

**Comment by dsehnal** [comment]
You can set the `manualReset` option on the canvas: `plugin.canvas3d?.setProps({ camera: { manualReset: true } });`. This will let you control manually when to reset the camera.
