### ISSUE TITLE
Question:  default representation

### ISSUE THREAD

**Issue by yooki0328** [molstar/molstar#867]
I have loaded the 7pky PDB file using Mol* and noticed that it defaults to displaying the Gaussian Surface representation. However, I have observed that other PDB files usually default to the Cartoon representation. Could you please explain the reason behind this difference in default representations?

**Comment by dsehnal** [comment]
For structures from certain size, mol* defaults to the surface representation. If you are loading the structure in your own app, it is possible to override this behavior.

**Comment by yooki0328** [comment]
> For structures from certain size, mol* defaults to the surface representation. If you are loading the structure in your own app, it is possible to override this behavior.

Thank you for your quick response and for providing a solution to my issue. I appreciate your help in resolving the problem.
