### ISSUE TITLE
Inquiry Regarding Automatic Structure Rotation in Mol* Viewer

### ISSUE THREAD

**Issue by Lola58** [molstar/molstar#869]
My name is Fan Bu, a student from the University of Science and Technology of China. I am writing to express my gratitude for the opportunity to use Mol* Viewer, which has been tremendously helpful to me.However, I have recently encountered some problems and I was wondering if you could provide some guidance or support.

Specifically, the PDB file loads successfully (as seen in Figure A), but I am unable to rotate the structure until I manually click the "Spin" button on the right-hand side of the viewer (as seen in Figure B). After enabling the "Spin" feature, the structure can be rotated as desired .
![mol_problems](https://github.com/molstar/molstar/assets/37244337/fb7ceaee-e1b2-4334-98e3-96e41a34afd7)

My question is whether it is possible to skip the manual step of enabling "Spin" and have the structure rotate automatically after the PDB file has finished loading. If this is possible, could you please provide guidance on how to achieve this?

Thank you for your time and assistance on this matter.

**Comment by dsehnal** [comment]
Hi,
this seems like an issue with how you are setting up the plugin. If this is inside a react app, don't you for example have 2 instance of the plugin shown on top of each other?
