### ISSUE TITLE
Structure superposition

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#87]
Requesting a superposition of 2 chains will report the correct RMSD but not apply the transformation to the representation. I think this broke between 1.1.7 and 1.1.8.

<img width="1146" alt="Screen Shot 2020-09-15 at 3 00 38 PM" src="https://user-images.githubusercontent.com/9744615/93398325-2d477d80-f830-11ea-8a0d-06b0bad2c0e7.png">

**Comment by arose** [comment]
Should be fixed. Would be nice if we could add some functional tests to check for such errors.

**Comment by JonStargaryen** [comment]
Thanks for fixing this!

> Would be nice if we could add some functional tests to check for such errors.

Out of curiosity, is there a good framework for this you can recommend?

**Comment by arose** [comment]
Actually I meant integration tests (like seeing how multiple units, as in unit tests, work together). Jest is fine for that, just should be separate from the unit tests so they can always be run quickly.

**Comment by JonStargaryen** [comment]
I see, I thought you referred to UI-tests.

Any plans for a release? :)

**Comment by JonStargaryen** [comment]
Thank you @dsehnal
