### ISSUE TITLE
Show specific interaction only

### ISSUE THREAD

**Issue by PilotTam** [molstar/molstar#871]
Hi,
I created a representation for displaying interaction like this after studying the docking-viewer example,
```javascript
builder.buildRepresentation(update, component, { type: InteractionsRepresentationProvider, typeParams: { includeParent: true, parentDisplay: 'between' }, color: InteractionTypeColorThemeProvider }, { tag: 'interactions' });
```
but I only want to show a specific bond in it. Can I make another provider which add params like `chainGroupId` or a range of `StructureElement.UnitIndex` as the target (UnitB) to limit the final interaction displayed?

I do not know if I can pass such params to `obtain` for `computeInteractions()` and maybe hopefully do something to get my result by modifying `findInterUnitContacts()`?
https://github.com/molstar/molstar/blob/106ee614e7203b46afaa98d5f2a684013f2cab85/src/mol-model-props/computed/interactions.ts#L22-L36

Many thanks in advance.

**Comment by PilotTam** [comment]
If I hardcode something like this in `findInterUnitContacts`
```typescript
if (unitA.chainGroupId == 2 && unitB.chainGroupId == 0)
    addStructureContacts(structure, unitA as Unit.Atomic, featuresA, unitB as Unit.Atomic, featuresB, builder, contactTesters, props);
```
I get what I want. So I wonder if I can pass my own InteractionParams to modify it.

**Comment by dsehnal** [comment]
One solution I can think of is something along these lines:

```
export type InteractionContactFilter = (a: StructureElement.Location, b: StructureElement.Location, contactKind: keyof ContactProviders) => boolean;

export const InteractionsParams = {
    providers: PD.Group(ContactProviderParams, { isFlat: true }),
    contacts: PD.Group(ContactsParams, { label: 'Advanced Options' }),
    contactFilter: PD.Value<InteractionContactFilter>(undefined as any, { isHidden: true })
};
```

and implement the necessary logic in the computation to apply it. The function can then be passed like this:

```
InteractionsProvider.set(structure, {
    ...PD.getDefaultValues(InteractionsParams),
    contactFilter: (a, b, kind) => ...
})
```

One drawback of this approach is that it is not serializable, although not all solutions require that functionality.

**Comment by PilotTam** [comment]
Many thanks for the fast reply. I will try to implement it.
