### ISSUE TITLE
Override InteractivityManager

### ISSUE THREAD

**Issue by nlarusstone** [molstar/molstar#873]
First off, thanks for a very helpful package!

I'm curious if there's a way to override InteractivityManager (or any other managers). I'd like to have a bit more control over the interaction patterns, but it seems like this is a `readonly` property. I'm curious if there's any way to manage this (or alternatively what the suggested way to have control over the interactivity is).

Specifically, I'm interested in allowing for multiple "types" of selection and I want to be able to control selections from outside of Molstar as well as within it. I've been looking into the source code for many hours and can get partial functionality using `fromCompiledQuery`. However, for my functionality I need to use the `set` StructureSelectionModifier, but that seems to update the action type globally, which I don't want -- I'd like to maintain the `add` StructureSelectionModifier interaction pattern for users. 

I believe the issue is on this line: https://github.com/molstar/molstar/blob/0ee8525b2d381c036c91d57e57eee7af86ab581e/src/mol-plugin-state/manager/structure/selection.ts#L432

My current thought was to override the InteractivityManager to solve this, but I'm open to learning about better ways to accomplish my goal too!

**Comment by dsehnal** [comment]
Hi, yes, this is possible. The manager is actually not used directly, but rather called by one of the "behaviors". The selection in particular is set up [here](https://github.com/molstar/molstar/blob/1afea8a86a25c91e60a783b2ea7d9a7084272608/src/mol-plugin/spec.ts#L118) (the [behavior](https://github.com/molstar/molstar/blob/1afea8a86a25c91e60a783b2ea7d9a7084272608/src/mol-plugin/behavior/dynamic/representation.ts#L112)). 

You can write your own version of `SelectLoci` behavior and use that instead of the default one when you are creating your plugin instance.

**Comment by nlarusstone** [comment]
Thanks for your response! I have been overriding the SelectLoci behavior, but the default one seems to just forward the behavior to some internal state that is out of my control. A couple of follow up questions:

Is there a way to extend the internal state of how selections are represented?
Is there a way to get just the selections which changed?

To give you a more concrete usecase:
I want to be able to have an external toggle that has values "green" and "red". If select a residue while the toggle is "green", I want to color that selection green. If I select a residue while that toggle is "red", I want to color that selection red (without losing the green selections).

**Comment by nlarusstone** [comment]
One way I could imagine doing this is storing some custom state on the `PluginContext`. That way I could still interact with it from the `SelectLoci` behavior as you suggest. But there doesn't seem to be a clean way to store external state into Molstar (which is understandable) or a even a good way to read external state from Molstar (which is more challenging)

**Comment by arose** [comment]
there are ways to cleanly store external state in Mol*, the https://github.com/molstar/molstar/tree/master/src/extensions/volumes-and-segmentations extension does it for example
