### ISSUE TITLE
Issue highlighting on PDB File 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#876]
I noticed something strange while highlighting in sequence viewer this PDB file from RCSB https://files.rcsb.org/download/1IGY.pdb
![image](https://github.com/molstar/molstar/assets/20627977/a1c9cc44-6d6e-4530-af4f-d9f464342107)
Here is a test session 
[mol-star_state_2023-7-20-18-53-47.molx.txt](https://github.com/molstar/molstar/files/12112131/mol-star_state_2023-7-20-18-53-47.molx.txt)
the correspondent cif model works fine instead and does not present gaps in the structure.

**Comment by arose** [comment]
@giagitom should be fixed with #946, please give it a try

**Comment by giagitom** [comment]
Hi @arose, I confirm it is working fine now! Thanks
