### ISSUE TITLE
Cannot load 1fqy

### ISSUE THREAD

**Issue by midlik** [molstar/molstar#877]
MolStar cannot load PDB structure 1fqy, showing "Error: No models found."

I tried it with older versions and it seems that it broke in this PR:
https://github.com/molstar/molstar/pull/731

(I suspect the problem is somewhere in the `trajectoryFromCCD` function because when I remove `_chem_comp_atom` category from the mmCIF, it loads it without error.)
https://github.com/JonStargaryen/molstar-proto/blob/2204e4e0d020bd59c86a26dd9b91b5f427f2661b/src/mol-plugin-state/transforms/model.ts#L306

**Comment by JonStargaryen** [comment]
Hmm, good to spot this. I was a bit worried about just checking for `chem_comp_atom` but thought it would be safe for archive structures. Should've checked: https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/chem_comp_atom.html.

https://github.com/molstar/molstar/blob/e92e5c5ceff4381de301449f5450c1675423847f/src/mol-plugin-state/transforms/model.ts#L306
could only trigger if `chem_comp_atom` is present and `atom_site`, `ihm_sphere_obj_site`, and `ihm_gaussian_obj_site` are all undefined.

At least, that's the "cleanest" way.

**Comment by midlik** [comment]
Thanks guys, that was super quick :D
