### ISSUE TITLE
how to use color: "uncertainty" to custom color theme

### ISSUE THREAD

**Issue by 13512263278** [molstar/molstar#879]
hi, first ,my pdb file's color by atom's score use updateRepresentationsTheme's :color:"uncertainty". but a atom just one score for pdb's file. now, I want to use a pdb's file and a score.txt file, score.txt have ten Scoring Rules，I want to give list for params to updateRepresentationsTheme can color my pdb file

this is my current part code
`const plugin : PluginUIContext = viewerInstance.plugin
  // await plugin.clear(true)
  await viewerInstance.load(customData);
  
  
  nextTick(async () => {    
    await plugin.dataTransaction(async ()=>{
    for (const s of plugin.managers.structure.hierarchy.current.structures) {
        await plugin.managers.structure.component.updateRepresentationsTheme(
          s.components,
          { color: "uncertainty"}
        );
      }
  })
  })`

this is my pdb file and score file
![image](https://github.com/molstar/molstar/assets/102570792/31725fe8-7fa7-4d1e-9a5d-f64bad6cb41e)
![image](https://github.com/molstar/molstar/assets/102570792/5710d8e2-5b85-42bb-80d2-f12973dce018)

**Comment by dsehnal** [comment]
Currently, you would have to write your own color theme that is able to interpret these data.  An example of this is the [structure quality report theme](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/extensions/pdbe/structure-quality-report/color.ts#L44).

We are working on a solution make these things a lot more straightforward, but that is still a few months away.

**Comment by 13512263278** [comment]
@dsehnal  thanks, I have create new file to solution the issue
