### ISSUE TITLE
Li element color displayed incorrectly

### ISSUE THREAD

**Issue by y805939188** [molstar/molstar#882]
Hi.
I want to render a `.gro` file, the file can be rendered normally but the color of the Li element is displayed as white as the hydrogen element. I also didn't find any configuration that can determine the color of this element:
![5563e507-a82a-4eee-8d24-67b0c55d9c69](https://github.com/molstar/molstar/assets/28889103/54b6463a-f29a-4121-8101-bef4c4e4d1c7)
But if replaced with other elements, such as potassium, it can be displayed in other colors:
![d89544fb-865e-4dc7-a793-dd1c34767154](https://github.com/molstar/molstar/assets/28889103/0f67786f-e340-4096-b794-da53e9bc9895)

Code link here: https://codesandbox.io/s/an-niu-lei-xing-antd-5-7-3-forked-nnpg67?file=/Molstar.jsx:1784-1799

So I would like to ask how to make the Li element display in other colors?

Thanks.

**Comment by dsehnal** [comment]
This should be fixed by https://github.com/molstar/molstar/pull/885.

**Comment by dsehnal** [comment]
I am sorry, I've only now noticed you created a PR with a fix separately. I will merge that.

**Comment by y805939188** [comment]
> This should be fixed by #885.

Thank you~🙏. I close this issue.
