### ISSUE TITLE
Will it be possible to export snapshots as vector graphics (svg, eps, ...)?

### ISSUE THREAD

**Issue by staalmannen** [molstar/molstar#884]
Most pdb structure viewers (for example PyMol) seem to only support exporting to raster graphics (png, tiff, ...), with some exceptions that I have found: 

UGene and VESTA but both are not quite suitable: while there is an export option in UGene it does not seem to export correctly. For VESTA the problem is that it only has the ball-and-stick view which results in very big svg files. Being able to export a "cartoon view" of a protein structure in vector format would be very nice.

Is this something being planned for Mol* ?

**Comment by dsehnal** [comment]
Sorry, this is not possible.

However, it is possible to export the raw geometry which can then be opened in a 3D party software that might be able to create more optimized SVG rendering of the scene (maybe Blender can do this?).
