### ISSUE TITLE
Position of residue when hovering

### ISSUE THREAD

**Issue by skrhakv** [molstar/molstar#888]
Hello,

I am working on interconnecting your tool with the [RCSB Saguaro Viewer](https://github.com/rcsb/rcsb-saguaro): when a user hovers over the residues in Mol*, I would like to highlight the particular residue in the RCSB Saguaro Viewer. 

To achieve this, I browsed through the codebase and found this function, which might suit my needs:
```
this.plugin.behaviors.interaction.hover.subscribe(ev => {
            console.log(ev);
});
```

However, I am unaware of how I could extract the position of the particular hovered-over residue from the `ev` variable. Therefore I would like to ask for your assistance - is there a way to extract the residue position from the `ev` hover event variable? 

Or is there any other built-in method that might be more suitable?

Thanks for your help in advance!

Vit

**Comment by dsehnal** [comment]
Hi, something like this should do the trick:

```ts
this.plugin.behaviors.interaction.hover.subscribe(ev => {
    if (StructureElement.Loci.is(ev.current.loci)) {
        const l = StructureElement.Loci.getFirstLocation(ev.current.loci);
        if (l) {
            const seq_id = StructureProperties.residue.label_seq_id(l);
        }
    }
});
```

**Comment by dsehnal** [comment]
You can try calling `StateSelection.Generators.rootsOfType(PluginStateObject.Molecule.Structure)` which will return the top level structures based on the addition order and then finding the index of each from `l.structure`. If that doesn't work, you can try first projecting `l.structure` to the parent using `plugin.helpers.substructureParent.get()`. Alternatively, maybe you add an extra tag/custom property value to the `Model` when you are loading the structures initially. E.g. 

```ts
const model = await this.plugin.builders.structure.createModel(trajectory);
model!.data!._staticPropertyData['_my_model_index'] = 1; // ideally create a getter/setter function for this to get rid of the magic string

// ...
const modelIndex = l.structure.model._staticPropertyData['_my_model_index'];
// ...
```

**Comment by skrhakv** [comment]
Thank you @dsehnal for your advice!

For future reference, I used the `adding extra custom property` approach to solve my issue.
