### ISSUE TITLE
Trajectory frame interpolation

### ISSUE THREAD

**Issue by pguillem** [molstar/molstar#889]
Hi all,

I recall NGLViewer had parameters to interpolate frames in a trajectory run. The outcome would be a smoother transition between frames. I went through the docs/issues failed to find it. Is it possible in MOL*?

All best. Thanks in advance.
Pedro

**Comment by dsehnal** [comment]
There is some basic scaffolding for this, but isn't implemented yet. The way to do this would be to implement the [`Trajectory` interface](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/mol-model/structure/trajectory.ts#L20) which handles the interpolation.

**Comment by pguillem** [comment]
Thanks again @dsehnal !
Best!
Pedro
