### ISSUE TITLE
Ellipsoid representation is set back to cartoon

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#890]
Hi,
I have a state node with X representation. When I try to set the representation as ellipsoid with some parameters it gets set up as cartoon.
Here's a code snippet:
`await this.molstarPlugin.build().to(node.transform.ref).update(createStructureRepresentationParams(this.molstarPlugin, void 0, {
    type: "ellipsoid",
    color: "element-symbol",
    size: "physical",
})).commit();
    }`

Am I missing something??

**Comment by Marwa-Da** [comment]
Edit:
I noticed that my molstar version is 3.35.0 and it doesn't have the ellipsoid option listed in the representation list:
![image](https://github.com/molstar/molstar/assets/11466297/52fbd536-7c93-49b3-a2f9-7fedab98d72e)

**Comment by Marwa-Da** [comment]
Edit:
I updated the package but the ellipsoid option isn't available yet.

**Comment by dsehnal** [comment]
The ellipsoid representation is only available for [structures with anisotrophy](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/mol-repr/structure/representation/ellipsoid.ts#L57). Does your file have the `atom_site_anisotrop` category?

**Comment by Marwa-Da** [comment]
Got it, no it doesn't. Does the same apply for other options, like the partial charge color theme?

**Comment by Marwa-Da** [comment]
Sure, here it is:
https://www.rcsb.org/structure/3VOS
I downloaded the *.pdb file.

**Comment by Marwa-Da** [comment]
![Screenshot 2023-08-12 072213](https://github.com/molstar/molstar/assets/11466297/24be0349-ba1a-4267-8e38-bcfe6ded630f)

**Comment by dsehnal** [comment]
I see. For mmCIF file, this representations is not there and the PDB file itself doesn't have the anisotrophy information. This seems like a small issue with the PDB parsed assigning the information (as an array of default values) even if it's not present in the data itself.

For this case, the `ellipsoid` representation is actually same as `ball and stick` with `size aspect ratio = 1` (and perhaps reducing the value of the size theme as well)

![image](https://github.com/molstar/molstar/assets/21145776/0b1ea881-1666-4b4f-8fa6-00397c40e79a)
![image](https://github.com/molstar/molstar/assets/21145776/da6d122b-9bdc-439a-8d28-637320157afd)

**Comment by Marwa-Da** [comment]
Ok, thank you for your reply!
Another question: I'm looking for the "electrostatic" coloring schemes that exists in ChimeraX, would you tell me its name in Mol*?

**Comment by dsehnal** [comment]
There is a theme based on `AtomPartialCharge` (e.g. from loading a mol2 file or assigning the property manually). Otherwise this type of coloring usually has to be done on per-app basis. There is also the [partial charges](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/extensions/sb-ncbr/partial-charges) extension which can help.

**Comment by Marwa-Da** [comment]
> There is also the [partial charges](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/extensions/sb-ncbr/partial-charges) extension which can help.

Thank you! I'll have a look at it.

**Comment by Marwa-Da** [comment]
Regarding using the partial charge extension: I had [this issue](https://github.com/molstar/molstar/issues/736) as a reference and followed the same steps but I still can't see the partial charge as an option in the coloring theme!
