### ISSUE TITLE
Is there a way to change the camera angle / rotation programtically ? 

### ISSUE THREAD

**Issue by pratykS** [molstar/molstar#891]
I have a use-case where I need to change the `camera position (axis position) `.
For example by default I can load the viewer with `x = 90, y = 90, z = 90` ?

please can someone share the code snippet if done it already ?

<img width="857" alt="Screenshot 2023-08-15 at 2 20 59 PM" src="https://github.com/molstar/molstar/assets/5937722/83459807-997f-4bc2-bc5b-1682f6dcdefd">

**Comment by dsehnal** [comment]
You can call `this.plugin.managers.camera.setSnapshot()`

**Comment by pratykS** [comment]
> You can call `this.plugin.managers.camera.setSnapshot()`

Do we need to pass any params to `setSnapshot()` like the coordinates `x,y,z`

**Comment by pratykS** [comment]
Also is there a way to print coordinates when we move the molecule using mouse ?
