### ISSUE TITLE
How to activate the partial charge extension?

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#892]
Regarding using the partial charge extension: I had https://github.com/molstar/molstar/issues/736 as a reference and followed the same steps but I still can't see the partial charge as an option in the coloring theme!

I feel like I really didn't get the idea of integrating one of the extensions. Any explanation is appreciated!

**Comment by MergunFrimen** [comment]
Hello, if you want to use the partial charge extension in your plugin instance then you will need to include it in the PluginUISpec specification. See [here](https://github.com/MergunFrimen/molstar-partial-charges/blob/e6d2e4ee1de7c8231c25b41cc8e96774d2ffdc44/src/viewer.ts#L53) for an example. If this doesn't help then the problem might be in the data. The extension only supports mmCIF data with custom categories. See [here](https://github.com/MergunFrimen/molstar-partial-charges#mmcif-categories) for more info about the mmCIF categories.

**Comment by Marwa-Da** [comment]
Thank you so much! I'll dig deep into them.
