### ISSUE TITLE
How to automatically load ply file when setting up the web service

### ISSUE THREAD

**Issue by CrazyHsu** [molstar/molstar#894]
Hello, 

I have a ply file which can be manually loaded by click the `Open Files` in molstar web service to describes the surface of a protein. However, I recently want it to be automatically loaded for visualization when setting up the web service or clicking on a new url. 

After learning the [examples](https://github.com/molstar/molstar/tree/master/src/examples), I found that they only mentioned how to automatically load `pdb` or `cif` files, and there is no related technical details in the documentation. Since I'm new to typescript, can you show me how to achieve this function? It would be great if there is example codes. Thank you in advance!

Feng

**Comment by CrazyHsu** [comment]
Can any one help me? T_T

**Comment by dsehnal** [comment]
Hi, you can manually apply these transforms for example:

- https://github.com/molstar/molstar/blob/14e6172c33b96fb03e49bbd29c750bf8f7c2224c/src/mol-plugin-state/formats/shape.ts#L22
- https://github.com/molstar/molstar/blob/14e6172c33b96fb03e49bbd29c750bf8f7c2224c/src/mol-plugin-state/formats/shape.ts#L33
- These can be combined into a single update as well.
- To get the basic `data`, you can do for example `await plugin.builders.data.download(...)`

**Comment by CrazyHsu** [comment]
Thank you, David. I will try the transforms you advised.

**Comment by CrazyHsu** [comment]
Hello David. Sorry, I still can't follow the code you provided.
Actually, what I want to know is how to modify the following javascript code to automatically load the local ply file and visualize it on molstar viewer. What should I do? Thank you in advance!
```javascript
<title>Molstar Viewer</title>

   <script type="text/javascript" src="./molstar.js"></script>
   <link rel="stylesheet" type="text/css" href="./molstar.css" />
</head>
<body>
   <div id="app-id" class="molstar-app"></div>
   <script type="text/javascript">
       molstar.Viewer.create("app-id", {
       }).then(viewer => {
           const plyFileUrl = 'path/to/my.ply'; 
           viewer.xxx(plyFileUrl, "ply");
       });
       
   </script>
</body>
```

**Comment by dsehnal** [comment]
- Generally, you should use a bundler like a WebPack; the compiled `Viewer` class exposes only limited functionality of the Mol* plugin.
- Browser doesn't usually have access to local files and you might have to host you `ply` file separately (using a tool like `serve` or `http-server`)
- In  your particular use case, this code might work (tho I haven't tested it):

```ts
.then(async viewer => {
    const plugin = viewer.plugin;
    const provider = plugin.dataFormats.get('ply');
    const data = await plugin.builders.data.download({ url: 'path', isBinary: false });
    const parsed = await provider.parse(plugin, data!);
    await provider.visuals(plugin, parsed);
});
```

**Comment by rtviii** [comment]
@dsehnal Apologies about tagging directly.  The you provided indeed worked out of the box for me. Many thanks

> * Generally, you should use a bundler like a WebPack; the compiled `Viewer` class exposes only limited functionality of the Mol* plugin.
> 
>     * Browser doesn't usually have access to local files and you might have to host you `ply` file separately (using a tool like `serve` or `http-server`)
> 
>     * In  your particular use case, this code might work (tho I haven't tested it):
> 
> 
> ```ts
> .then(async viewer => {
>     const plugin = viewer.plugin;
>     const provider = plugin.dataFormats.get('ply');
>     const data = await plugin.builders.data.download({ url: 'path', isBinary: false });
>     const parsed = await provider.parse(plugin, data!);
>     await provider.visuals(plugin, parsed);
> });
> ```

I'm wondering if there is a way to make a `Shape` into a standalone Component on par with `Cif` models such that i can `select`, `focus` and especially select surroundings with 5, 10 etc. angstrom of a given shape. 

I tried to follow the regular route of 
```typescript
    const data = await this.ctx.builders.data.download({ url: Asset.Url(myUrl.toString()), isBinary: false }, { state: { isGhost: true } });
    const trajectory = await this.ctx.builders.structure.parseTrajectory(data, 'mmcif');
    await this.ctx.builders.structure.hierarchy.applyPreset(trajectory, 'default');
    ```
    but am getting a little confused as to how would `applyPreset` work in the case of a `Shape`. It seems like `parseTrajectory` is for structural data only. (My shape is built from the `.ply` file).
    
    Thanks a bucket.


![image](https://github.com/user-attachments/assets/2713b02b-a628-446d-8f75-d2dfc82f2de0)

**Comment by dsehnal** [comment]
You can write your own transform that returns ShapeProvider. When creating a shape yourself, you can assign different "group numbers" to sets of vertices and these can the be interacted with independently as these will be addressable by Shape Loci similar to how atoms are addressed by Structure Element Loci.

However, you might still have to write a custom plugin behavior that handles the specific logic you are after as that usually varies from app to app so we didn't include much in this regard in Mol* directly. But for example the volumes and segmentations extension could help there as there we implemented custom integration with generic meshes.
