### ISSUE TITLE
Coloring by Model-index not working?

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#896]
Maybe I have found an issue with model index coloring. 
I tried using it with a random multi state structure (PDB Id 1G03) and it seems to color each state in the same way. is this an expected behavior? 

Here is a [test state](https://github.com/molstar/molstar/files/12410809/test.molj.txt)

**Comment by arose** [comment]
model-index colors by models in the state tree. You probable want trajectory-index.

**Comment by giagitom** [comment]
Hi @arose, I tried your suggestion but it seems not to work. Every model is shown as black using trajectory-index

![image](https://github.com/molstar/molstar/assets/20627977/35a65e0c-973f-4d01-a373-2c1522e22723)

**Comment by giagitom** [comment]
Oh.. I have found that when I load all models together in my implementation, trajectory index is working as expected. 

I have also discovered that utilizing the entity index yields identical outcomes as the trajectory index. However, shouldn't all entities be colored uniformly instead?

![image](https://github.com/molstar/molstar/assets/20627977/4b8e7169-01d0-4cf4-91d2-a2e688e883df)

**Comment by arose** [comment]
something is of but I don't time to look into it at the moment
