### ISSUE TITLE
Question: Unexpected Gaps in Protein/Nucleic Acid Secondary Structure Visualization

### ISSUE THREAD

**Issue by Neuron-Cell** [molstar/molstar#897]
When using the viewer to look at pdb structures, I noticed some interruptions in the secondary structure of proteins or nucleic acids. However, the same pdb appears continuous on the RCSB website. How can I achieve the same effect as on the RCSB? Any guidance or suggestions would be greatly appreciated. Thank you in advance!
interruptions:
![protein_gaps](https://github.com/molstar/molstar/assets/54050617/85eeac06-1f8e-4495-988f-b216d3ac2a9f)
![nucleic_acid_gaps](https://github.com/molstar/molstar/assets/54050617/fac1e8b5-b0a5-4d5b-8f93-3b166564b776)
same pdb on RCSB website:
![protein_RCSB](https://github.com/molstar/molstar/assets/54050617/043671af-e0c2-4ab1-98f8-1b3e78b80257)
![nucleic_acid_RCSB](https://github.com/molstar/molstar/assets/54050617/a3ddf811-fefb-4b23-8c43-1f90a9a35120)
problem pdb file:
[problem_pdb.zip](https://github.com/molstar/molstar/files/12429392/problem_pdb.zip)

**Comment by dsehnal** [comment]
Hi,
the RCSB/PDBe sites use the mmCIF format to load the structure. Mol* provides better support for mmCIF and sometimes shows ugly edge cases for old PDB format which you are observing.

In this particular case, the sequence residues have incorrect annotations where there are residues 1100 and 100 right next to each other in the PDB file. However, Mol* sorts the sequence residues by the sequence number under the hood which results in the confusing visuals (this fixes a different class of errors where some PDB files have sequence residues out of order).

![image](https://github.com/molstar/molstar/assets/21145776/bd2ad5cf-e060-4918-8428-b433ad7b2389)

In the mmCIF file, these residues have consecutive `atom_site.label_seq_id` which enables Mol* to render the structure correctly.

**Comment by arose** [comment]
@Neuron-Cell this should fixed for PDB files with #946, please have a look
