### ISSUE TITLE
Integrating the partial charges into the plugin

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#898]
Hi,
Imagine I have a CIF file lacking charges information. After some time, once I've parsed the file and built the plugin, I obtain a new file containing the partial charges (in text or CIF format). Is it possible to incorporate these charge values back into the plugin instance?

**Comment by dsehnal** [comment]
Yes, it is possible to do so. You can have a look at how these charges are attached for [MOL2 files](https://github.com/molstar/molstar/blob/25eb4450ad9feab81b54edb2485ca730cb8bee6b/src/mol-model-formats/structure/mol2.ts#L124). You should be able to call the `AtomPartialCharge.Provider.set` function which should the make these available for the built-in partial charges theme.
