### ISSUE TITLE
Visualizing structures sent over gRPC

### ISSUE THREAD

**Issue by stefdoerr** [molstar/molstar#90]
Hi all, in NGL I had written some code which allowed me to send over gRPC a PDB string blob and visualize it in the viewer like this:

```js
var stringBlob = new Blob([call.request.structure], { type: 'text/plain' });
stage.loadFile(stringBlob, {
    ext: "pdb",
    name: call.request.name
}).then(function (structureComponent) {
    var reqdata = call.request
    if (reqdata.repr_type) {
        if (reqdata.repr_selection) {
            structureComponent.addRepresentation(reqdata.repr_type, { sele: reqdata.repr_selection })
        } else {
            structureComponent.addRepresentation(reqdata.repr_type)
        }
    } else {
        stage.defaultFileRepresentation(structureComponent)
    }
    if (reqdata.traj && (reqdata.traj.length != 0)) {
        frames = trajToFrames(call.request.traj);
        structureComponent.addTrajectory(frames);
    }
})
```

I am however unable to find an equivalent for loading a structure from a PDB blob (and trajectory from an array).

What would be the correct way to do this in Mol*?

**Comment by pschmidtke** [comment]
I just asked a similar type of question on gitter ... mine was to update coordinates through a stream of coordinates that used to be possible I think in NGL as well.

**Comment by dsehnal** [comment]
Having build-in trajectory streaming support is currently on top of my todo list so in the coming weeks both your tasks should be made easier.

If you need it now, here are some pointers:

@stefdoerr 
- Add the ``PluginStateObject.Molecule.Model`` PDB structure to the state tree.
- Write a transformer that creates ``PluginStateObject.Molecule.Topology`` from your data. (here's an example https://github.com/molstar/molstar/blob/490c6679eb7cbcec230b3b0e2fc589262eed6833/src/mol-plugin-state/transforms/model.ts#L105)
- Use ``AddTrajectory`` state action (https://github.com/molstar/molstar/blob/482059cc9b1d0777d90cdde7d8b8fb0a94edbacc/src/mol-plugin-state/actions/structure.ts) to merge the 2 objects from  the above steps.

@pschmidtke 
- Write a custom implementation of https://github.com/molstar/molstar/blob/482059cc9b1d0777d90cdde7d8b8fb0a94edbacc/src/mol-model/structure/trajectory.ts#L20 that takes the info to set up your streaming.
  - ``getFrameAtIndex`` will do the query or use cached data.
- Write a transfomer that creates the custom ``Trajectory`` implementation.  (example https://github.com/molstar/molstar/blob/490c6679eb7cbcec230b3b0e2fc589262eed6833/src/mol-plugin-state/transforms/model.ts#L130)
- The rest of the state is the same as if the data was static.

**Comment by dsehnal** [comment]
Having build-in trajectory streaming support is currently on top of my todo list so in the coming weeks both your tasks should be made easier.

If you need it now, here are some pointers:

@stefdoerr 
- Add the ``PluginStateObject.Molecule.Model`` PDB structure to the state tree.
- Write a transformer that creates ``PluginStateObject.Molecule.Topology`` from your data. (here's an example https://github.com/molstar/molstar/blob/490c6679eb7cbcec230b3b0e2fc589262eed6833/src/mol-plugin-state/transforms/model.ts#L105)
- Use ``AddTrajectory`` state action (https://github.com/molstar/molstar/blob/482059cc9b1d0777d90cdde7d8b8fb0a94edbacc/src/mol-plugin-state/actions/structure.ts) to merge the 2 objects from  the above steps.

@pschmidtke 
- Write a custom implementation of https://github.com/molstar/molstar/blob/482059cc9b1d0777d90cdde7d8b8fb0a94edbacc/src/mol-model/structure/trajectory.ts#L20 that takes the info to set up your streaming.
  - ``getFrameAtIndex`` will do the query or use cached data.
- Write a transfomer that creates the custom ``Trajectory`` implementation.  (example https://github.com/molstar/molstar/blob/490c6679eb7cbcec230b3b0e2fc589262eed6833/src/mol-plugin-state/transforms/model.ts#L130)
- The rest of the state is the same as if the data was static.

**Comment by stefdoerr** [comment]
Thanks @dsehnal . Update this issue if possible when the streaming support is implemented!

**Comment by arose** [comment]
Welcome to Mol* @stefdoerr and @pschmidtke!

**Comment by stefdoerr** [comment]
Not anymore an issue. I figured out an alternative which I will publish soon in an electron application

**Comment by stefdoerr** [comment]
https://github.com/Acellera/molkitstar link to the electron application for future reference if anyone is interested in it

**Comment by d-beltran** [comment]
The link is broken. Could you please update it?
Thanks for sharing!
