### ISSUE TITLE
recognition of glycan chains

### ISSUE THREAD

**Issue by sakyw123** [molstar/molstar#910]
hello friends:

I drew some additional glycan (A2G1F) onto PDB 6m0j using MOE glycan builder, however the structure cannot be clearly recognized by mol*, GlcNAc was recognized as Glc.

Any idea about how to fix this issue?

Thanks!

![image](https://github.com/molstar/molstar/assets/43593555/ac393433-d3c9-4a44-86ad-cf36d8f6de96)

**Comment by dsehnal** [comment]
[Here is a table](https://github.com/molstar/molstar/blob/febc634d8babedb24e8542745151d1c0657899c5/src/mol-model/structure/structure/carbohydrates/constants.ts#L227) Mol* uses for the mapping. Perhaps adjusting the residue name will help?

**Comment by sakyw123** [comment]
Thanks, dsehnal! I renamed the glycan units, like GlcN (name in MOE) to NAG (name in mol*). This issue has been fixed.

![image](https://github.com/molstar/molstar/assets/43593555/686963e3-0ebf-46eb-9b57-12fffd2c2a4c)

**Comment by dsehnal** [comment]
Mol* uses the standard naming used by the PDB archive. It is also possible to use different naming schemes (also available in the file I linked, although this usually has to be done statically for all loaded structures and cannot be changed on per-structure basis).

**Comment by sakyw123** [comment]
Yes, I got it. Currently for illustration purpose, I changed glycan residue names in my 3D structure files (pdb format) using MOE, to follow the mol* style, then mol* can recognize it well. It seems that MOE should enhance their glycan naming styles.
