### ISSUE TITLE
How can I get the objectId of each ball?

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#917]
<img width="541" alt="image" src="https://github.com/molstar/molstar/assets/1294316/59b333b4-e50b-40ad-a1b0-cce5c8d29e24">

I need a function to select a custom shapes(ball) , very thans~

**Comment by luckyxutao** [comment]
I get it，I can store the pickingIds to make selection
The instability of objectId is mainly related to the rendering order?

**Comment by arose** [comment]
pickingIds are for internal use, you should use the pickingId to get a loci referencing stable data

**Comment by luckyxutao** [comment]
very thanks

**Comment by luckyxutao** [comment]
why the objectId is different every time it is rendered?

**Comment by arose** [comment]
objectId is part of the pickingId, so still internal state.

It looks like you are using a Shape Geometry, so the loci you get from the pickingId has a reference to the Shape object which has a sourceData property that contains your input data and there you could provide your own stable id.

**Comment by luckyxutao** [comment]
How can i get the loci base on sourceData?

**Comment by luckyxutao** [comment]
Is there any other way to get loci besides pickingId? The objectId in pickingId is auto-incrementing. 

Currently, I reset getNextId to 0 to ensure that the objectId remains stable after multiple renderings.
