### ISSUE TITLE
Passing a custom Sequence component to SequenceView

### ISSUE THREAD

**Issue by rdirisio** [molstar/molstar#921]
Hello, 

I currently have a custom `Sequence` component
```
export class MyCustomSequence extends Sequence<SequenceProps> {
  ...  
  }
```
that I would like to use in `SequenceView`. In order to do this at the moment, I need to copy the entire `SequenceView` component, even though I just want to really do a drop-in replacement for this one line in the `render()`
```
<MyCustomSequence key={i} sequenceWrapper={s.wrapper} /> // used to be <Sequence key={i} sequenceWrapper={s.wrapper} />
```
even extending `SequenceView` doesn't work because of all the private variables and functions.

I was wondering if SequenceView can either take a prop or somehow get its Sequence via `children` or something similar.

Thanks!

**Comment by rdirisio** [comment]
I see a few options for implementing this, but I don't feel like any are optimal at the moment. Perhaps I can list them here to get feedback on implementation:

1. Adding a `PluginUISpec?.components?.sequence`. I have an implementation of this locally, and it works in the basic-wrapper. I am worried about typing, though. I would like to make it something like `Sequence<SequenceProps> | any`, which works if I subclass Sequence, but I worry that would be too generic of a type for this.
2. Modifying SequenceView to have fewer protected variables. This doesn't seem like a viable option, since I'd want to change the render() method only, but that calls a bunch of protected variables and functions that should likely remain protected.
3. Make SequenceView somehow get the component via params / values. I am unsure how one would drill the custom Sequence component down into SequenceView with how it is currently set up in the plugin spec. If you have any suggestions for that I am also open to that.

**Comment by dsehnal** [comment]
How about just the ability to pass a component that renders instead of the default `SequenceViewer`? The component can just access the plug-in via `useContext` and any extra props it needs via `plugin.customState`.

I would not worry about the typing much, can just use React.FC or the ClassComponent with no params like in the other cases in the spec.

Tho I guess for v4.0 we should probably try to move away from the class components... whenever that will be.
