### ISSUE TITLE
Some overpainets are not applied

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#924]
Hi all,

I followed the solution given in this [issue](https://github.com/molstar/molstar/issues/227) to color each chain I have using "overpaint concept". But, only one chain was overpainted. What could be a possible reason? Could you give me some pointers /hints?

![image](https://github.com/molstar/molstar/assets/11466297/656d2f63-9b04-49ff-b659-7715e33a0bb7)

**Comment by Marwa-Da** [comment]
This is the code I used, in case needed:
```
const color = ColorNames.silver;
this.plugin.dataTransaction(async ctx => {
                                const getLoci = async (s) => StructureSelection.toLociWithSourceUnits(await chainSelection("A").getSelection(this.plugin, ctx, s));
                                await setStructureOverpaint(this.plugin, chainsComponents, color, getLoci);
                            }, {canUndo: 'Apply Theme'});
```

**Comment by dsehnal** [comment]
Your selection contains `chainSelection("A")`, which corresponds to the `chain_A` in the state tree, which seems expected...

**Comment by Marwa-Da** [comment]
Exactly! Sorry, my mistake! 
After your comment I reviewed the getSelection function again and I realized this line:
https://github.com/molstar/molstar/blob/fb16cd0070846fa4e42121961f888d5e73d3876c/src/mol-plugin-state/helpers/structure-selection-query.ts#L82C67-L82C67
I hadn't paid attention to the "expression" parameter :(
