### ISSUE TITLE
Passing properties to a component of customStructureControls 

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#926]
I created a custom component and assigned it to `customStructureControls`. However, it seems that I cannot pass any properties that are needed by my custom component. Is there a way to achieve this, or can I open a pull request (PR) to enable passing props to the `customStructureControls` section?

https://github.com/molstar/molstar/blob/fb16cd0070846fa4e42121961f888d5e73d3876c/src/mol-plugin-ui/controls.tsx#L276

 I would appreciate any suggestions or guidance on this matter.

**Comment by dsehnal** [comment]
You can have a look for example at the [controls for the export extension](https://github.com/molstar/molstar/blob/master/src/extensions/model-export/ui.tsx#L35). You can subscribe either to the hierarchy updates (`useBehavior(plugin.managers.structure.hierarchy.behaviors.selection);`) or perhaps directly updates of the state tree with something like this:

```ts
const [_, _update] = useState({});
useEffect(() => {
    const sub = plugin.state.data.events.changed.subscribe(_ => _update({}));
    // can search state tree for the Strucutre with your custom properties here
    // for example with plugin.state.data.selectQ(q => q.byRef(...)) or
    // plugin.state.data.selectQ(q => q.root.subtree().withTag('123'));
    return () => sub.unsubscribe();
}, []);
```

and then render the controls you want.
