### ISSUE TITLE
Displaying discontinuous connections in PDB numbering

### ISSUE THREAD

**Issue by tadsatlawa** [molstar/molstar#931]
Hi,

I try to visualize PDB file containing an antibody. It uses IMGT format for residue numbering containing gaps. Those gaps are displayed as dashed lines:
![ab_molstar](https://github.com/molstar/molstar/assets/91870171/efb229de-39c5-4904-99d9-1d0d37887be1)

Is there an option to display them as normal connection?

**Comment by dsehnal** [comment]
No, currently you can only turn them off:

![image](https://github.com/molstar/molstar/assets/21145776/d16814e8-53fa-43d9-90e1-caacbd141748)

**Comment by tadsatlawa** [comment]
I found workaround - one can convert pdb to mmcif hence it renders properly. Sample conversion could be done as described here: https://bioinformatics.stackexchange.com/a/10907
