### ISSUE TITLE
"Coordinates" and "trajectories" chapters could be mixed up

### ISSUE THREAD

**Issue by vladislove2020** [molstar/molstar#940]
Good afternoon! 
It seems that the names of chapters "Coordinates" and "Trajectories" could be mixed up
![IMG_20231004_170231_323](https://github.com/molstar/molstar/assets/146962151/9318bbaf-993c-48f3-982f-7a0a6ab60c8d)

**Comment by arose** [comment]
that is on purpose as it reflects how things are named internally (although it might not be the best user facing name)
