### ISSUE TITLE
Setting overpaint using Representation.setState does not trigger canvas update

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#941]
Hi,
When I try to set ```overpaint``` using ```Representation.setState()```

could it be caused by this lines? 
https://github.com/molstar/molstar/blob/e548a3ed8527211922091a7482ec31aa4483b9a4/src/mol-repr/representation.ts#L461-L463

Other settings like ```visible``` or ```themeStrength``` are working fine instead.

The only way I have found so far to update the canvas is by applying and removing marking on the representation after using ```Representation.setState()```

**Comment by giagitom** [comment]
More info about this:

I is NOT true that there is no update. For example if I keep changing the color of one overpaint layer I can see that the canvas always updates; but it updates to the previous color instead of the current one. Same thing happens if I change the loci, or set clear. Even if I add or remove layers there is the same issue.

Any suggestions on what could be the cause of this behavior? Also is there any way to properly force an update of the canvas instead of applying and removing the marking?

**Comment by dsehnal** [comment]
Calling `canvas.update(representation)` should solve the issue.

From the UI the overpaints are created using this transform: `https://github.com/molstar/molstar/blob/fc44e66b26d798d09fa681643e65e3d73241838e/src/mol-plugin-state/transforms/representation.ts#L339` and are applied by this behavior: https://github.com/molstar/molstar/blob/fc44e66b26d798d09fa681643e65e3d73241838e/src/mol-plugin/behavior/static/representation.ts#L51

**Comment by giagitom** [comment]
> Calling canvas.update(representation) should solve the issue.

Indeed it works perfectly! Thanks @dsehnal
