### ISSUE TITLE
The intersect combinator not implemented error

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#944]
Hi all,

I'm trying to write a selection query that get the protein part of a specific chain but I'm getting the following error:
Error: Symbol 'structure-query.combinator.intersect' is not implemented.

Here's my query:
```
StructureSelectionQuery(
        label,
        MS.struct.modifier.union([
            MS.struct.combinator.intersect([
                MS.struct.modifier.union([
                    MS.struct.generator.atomGroups({
                        "chain-test": MS.core.rel.eq([MS.ammp("auth_asym_id"), auth_asym_id]),
                    }),
                ]),
                MS.struct.modifier.union([
                    MS.struct.generator.atomGroups({'entity-test': _proteinEntityTest})
                ])
            ])
        ])
    );
```

Have I implemented something wrong to get that error?!

**Comment by dsehnal** [comment]
The intersect is indeed not implemented as it was quite a bit more complicated to do in Mol* than in the original MolQL implementation.

However, in your case you can just use 

```ts
MS.struct.generator.atomGroups({
  "chain-test": MS.core.rel.eq([MS.ammp("auth_asym_id"), auth_asym_id]),
  "entity-test": _proteinEntityTest
})
```

--------------

You can also create the selection expressions directly which is useful in some cases:

```ts
const xs = new Set([1, 2, 3]);
atoms({
    atomTest: ctx => xs.has(ctx.element.element)
});
```

and execute them by creating the corresponding `QueryContext` manually. The drawback of this is that you won't be able to serialize this query in the state tree and will have to convert it to a Selection Bundle if you want to use the result to create representation.

**Comment by Marwa-Da** [comment]
I'm not sure I fully comprehended the second approach so please bear with me.
 If I want to get the ligand part of a specific chain using the second approach, do you mean I should have the ligand's atoms indices first?
Another question, would you provide an example of how to use the Selection Bundle or any helping file? Because I want to add representation to the ligand component created earlier.

**Comment by arose** [comment]
@dsehnal there is https://github.com/molstar/molstar/blob/e4396039fd0843e110fe8062668f7938ec7447a3/src/mol-model/structure/query/queries/combinators.ts#L31-L65 but it is not hooked up.

**Comment by dsehnal** [comment]
Well, the more you know :) although that implementation would not work in the case for this thread I think.

**Comment by arose** [comment]
> Well, the more you know and seems like I wrote that too 5 years ago :) although that implementation would not work in the case for this thread I think.

so, irrespective of if it can be used here, should we bind it?

**Comment by Marwa-Da** [comment]
> You can also create the selection expressions directly which is useful in some cases:
> 
> ```ts
> const xs = new Set([1, 2, 3]);
> atoms({
>     atomTest: ctx => xs.has(ctx.element.element)
> });
> ```
> 
> and execute them by creating the corresponding `QueryContext` manually. The drawback of this is that you won't be able to serialize this query in the state tree and will have to convert it to a Selection Bundle if you want to use the result to create representation.

Sorry for getting back late to this issue, but I implemented today the mentioned approach and it's working. It would be nice of you if you can have a look at it; to make sure I used the appropriate functions for that:
```
const compiled = compile(StructureSelectionQueries.ligand.expression);
const result = compiled(new QueryContext(structure));
const structureOfExpression = StructureSelection.unionStructure(result);
const calculatedElements = structureOfExpression.units?.flatMap((unit) => OrderedSet.toArray(unit.elements));
const specificTypeOfChain = Q.generators.atoms({
        chainTest: Q.pred.eq((l) => P.chain.auth_asym_id(l.element), chainIdentifier),
        atomTest: Q.pred.inSet((l) => l.element.element, calculatedElements),
    });
const specificTypeOfChainSelection = specificTypeOfChain(new QueryContext(structure));
const specificTypeOfChainAsBundle =
    StructureElement.Bundle.fromSelection(specificTypeOfChainSelection);
const stateObject = update.to(structureCell).apply(
    StateTransforms.Model.StructureSelectionFromBundle,
    {
        bundle: specificTypeOfChainAsBundle,
        nullIfEmpty: true,
        label: "some-label",
    }
)apply(StateTransforms.Representation.StructureRepresentation3D,params);
