### ISSUE TITLE
Increase select/highlight radius

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#948]
Hi, 

how would one increase the select/highlight radius?

I now that we can change the color for these within these files:
https://github.com/molstar/molstar/blob/44c69f538b5fceff3ea1e4032db2a8c87485f3c1/src/mol-gl/renderer.ts#L99
https://github.com/molstar/molstar/blob/44c69f538b5fceff3ea1e4032db2a8c87485f3c1/src/mol-canvas3d/passes/marking.ts#L28

but not quite sure if there is a way to easily increase the area in which we highlight/select.

Any help here will be greatly appreciated!

**Comment by arose** [comment]
there is edgeScale

```ts
ctx.canvas3d?.setProps({
    marking: {
        edgeScale: 3,
    }
});
ctx.canvas3d?.requestDraw();
```
