### ISSUE TITLE
Retrieve the identity of atoms forming non-covalent contacts

### ISSUE THREAD

**Issue by bisejdiu** [molstar/molstar#95]
I am trying to understand the internal logic used by molstar to display non-covalent interactions. If I visualize, for example, hydrophobic contacts for a protein like 3NIR, I can see several contacts on the viewer. My goal, however, is to get useful information about these contacts (for example, which atoms are forming those contacts). How can I do that? 

In the ```computeInteractions``` function (defined in _src/mol-model-props/computed/interactions/interactions.ts_), when I log the result of: 
```javascript
const interactions = { unitsFeatures, unitsContacts, contacts };
refineInteractions(structure, interactions);
console.log(interactions);
```
I, unfortunately, cannot make sense of the output. 
I think my lack of understanding of how definitions such as ```IntAdjacencyGraph``` work is the reason for this, but I would appreciate some help explaining how to access atom information from calculated contacts.

**Comment by bisejdiu** [comment]
I think I may have found the answer. If I do the following: 
```javascript
index = infoA.members[infoA.offsets[infoA.feature]];
infoA.unit.model.atomicHierarchy.atoms.type_symbol.value(infoA.unit.elements[index]);
```
then I get the atom type, though there may be a better way of doing this. I guess my confusion was in not understanding how ```measure``` and ```offsets``` work. In the case of hydrogen bonds, ```measure``` contains the indices of donors and acceptors, ```types``` contains the FeatureType. I don't really know what ```offsets``` does. 

Is it possible to get a brief overview of how molstar keeps contact information and if I wanted to visualize some custom contact between two random atoms, how I would do that?

**Comment by dsehnal** [comment]
That's a rather loaded question :)

But have a look at the [label provider](https://github.com/molstar/molstar/blob/master/src/mol-plugin/behavior/dynamic/custom-props/computed/interactions.ts#L45) and [representation](https://github.com/molstar/molstar/tree/master/src/mol-model-props/computed/representations) for the interactions. It shows how to access that data.

**Comment by arose** [comment]
> if I wanted to visualize some custom contact between two random atoms, how I would do that?

There is no simple dedicated API for that but you got mainly two ways. Either create your own StructureRepresentation (see https://github.com/molstar/molstar/blob/master/src/extensions/rcsb/validation-report/representation.ts as an example for doing that within an extension) or create a ShapeRepresentation that takes Loci as input (see https://github.com/molstar/molstar/blob/master/src/mol-repr/shape/loci/distance.ts as an example).

**Comment by bisejdiu** [comment]
Reopening this because it makes more sense than creating a new issue. Anyway, how do I retrieve data from the viewer after it has been rendered? 

For instance: 
```javascript
viewer.plugin.selectionMode // returns either true or false
```
tells you if selection mode has been toggled on or off. If I want to, say, get the indices of the residues that have been selected, I can do something like this: 

```javascript
sel = viewer.plugin.managers.structure.selection
sel.entries.entries().next().value[1].selection.elements[0].indices
```
So, here are my questions. 
1. Is the approach above correct? It's quite laborious but it works. 
2. What should I do to get,  say, non-covalent interactions (i.e. indices of atoms forming the contacts)? 
3. When I try to get the indices of atoms (using the code above), I get different results depending on if I select a single atom (2.97079e-313), multiple atoms (actual indices), or all atoms of a residue (2.97079e-313). I do not understand the first and third value. 

In my use case, I have another application that I need to interface with molstar that's why I need to be able to retrieve this type of information.

**Comment by dsehnal** [comment]
https://github.com/molstar/molstar/discussions/111 should provide some insight. Basically you need to subscribe to one of the behaviors and then transform the event data.

The floating point numbers you are seeing are two integers packed into a single 64bit float to improve memory efficiency.
