### ISSUE TITLE
refactor assembly-symmetry extension

### ISSUE THREAD

**Issue by arose** [molstar/molstar#951]
follow-up on #950, for v4 due to breaking changes

to make it a bit more generic and reduce maintenance for the molstar project I propose the following
- rename to `AssemblySymmetry` (from `RCSBAssemblySymmetry`) and more to its own extension folder
- remove the graphql schema generation to reduce maintenance burden (only used here)
- review schema and make desired changes

**Comment by arose** [comment]
Hey @midlik & @JonStargaryen, please have a look at this proposal. With v4 we will have an opportunity for breaking changes. Please let me know if you are ok with this and if there are other things you would like changed. Specifically let me know if you would want any schema changes for the assembly symmetry.

**Comment by midlik** [comment]
Hi, 
> rename to AssemblySymmetry (from RCSBAssemblySymmetry) and more to its own extension folder
OK, makes sense.

> remove the graphql schema generation to reduce maintenance burden (only used here)
OK, we don't use graphql anyway (just a simple fetch to REST API).

> review schema and make desired changes
I think the schema is OK, our API uses almost the same schema with only two differences: 1) "stoichiometry" is a string, not a list of strings, 2) we don't provide "cluster" (that's why I implemented turning coloring off).

**Comment by midlik** [comment]
There is a small difference I noticed between showing 1e94 assembly 3 on RCSB and PDBe - the cage seems to be rotated by 30 degrees although the 6-fold symmetry axis is practically the same:
https://www.rcsb.org/3d-view/1E94/3?preset=symmetry&symindex=0
https://wwwdev.ebi.ac.uk/pdbe/entry/view3D/1e94/?view=entry_index&viewer=litemol&assembly=3
(the latter looks kinda better, as it reflects the shape of the assembly more)

I smell some indeterminism in choosing the cage orientation, it might be worth having a look at, even though it's not a big issue.

**Comment by JonStargaryen** [comment]
Sorry for the late reply. The proposal sounds good to me.

**Comment by arose** [comment]
will be closed by #1013
