### ISSUE TITLE
Transformation by model symmetry provider

### ISSUE THREAD

**Issue by cycle20** [molstar/molstar#952]
Hi,

Is it possible to transform structure conformation by customized model symmetry?
I have a symmetry provider and I can update matrix data in `pdbx_struct_oper_list` table.
But as I see it has no effect on the structures.
(when I update the CIF file and load it, the operator transforms as expected)
Maybe I missed something in my code, or it cannot be transformed by this way.
Should I try to do something with the raw data or this can be achieved at symmetry provider level?

Best regards,
Csongor

**Comment by dsehnal** [comment]
You will likely need to create your own transform that creates a new structure based on your custom assembly data. This could be done for example by copy-pasting and modifying the [built-in version](https://github.com/molstar/molstar/blob/492494033f1b117cc2da02f577b747fc1ba1cc03/src/mol-plugin-state/transforms/model.ts#L545).

Alternatively, you might be able to use the `'symmetry-assembly'` together with the built in transform linked above.

**Comment by cycle20** [comment]
Thank you. I will check it.
