### ISSUE TITLE
assembly-symmetry extension: disappearing controls

### ISSUE THREAD

**Issue by midlik** [molstar/molstar#954]
I noticed a strange behavior of the RCSBAssemblySymmetry extension on **1smv** - when you switch to any assembly other that '1', the Assembly Symmetry section in the right control panel disappears:
https://www.rcsb.org/3d-view/1smv/1 (section visible)
https://www.rcsb.org/3d-view/1smv/3 (section gone)

I'm not sure if this is the desired behavior (I see some related logic here: https://github.com/molstar/molstar/blob/492494033f1b117cc2da02f577b747fc1ba1cc03/src/extensions/rcsb/assembly-symmetry/prop.ts#L58C25-L58C25).
But for an outsider it looks like a bug.

**Comment by arose** [comment]
OK, that was very much on purpose, because RCSB only has Assembly Symmetry data for "Biological Assemblies" and the panel is only shown when Assembly Symmetry data potentially exists.

Do you need a different behavior?

**Comment by midlik** [comment]
Hmm, I see. But then it's confusing because the section is shown when showing Model structure or Symmetry Mates structure.

**Comment by midlik** [comment]
We currently don't have symmetry data calculated for non-"Biological Assemblies", but very probably will add them soon. It certainly makes sense for some of those assemblies (e.g. 1smv assembly 3 clearly has a C5 symmetry).

**Comment by arose** [comment]
Feel free to make an enhancement PR!
