### ISSUE TITLE
change the color of carbon atoms

### ISSUE THREAD

**Issue by ashipiling** [molstar/molstar#957]
Hello, is there a way to manually change the color of carbon atoms, as shown in the image below? I need to render multiple ligands simultaneously(same residue name and same chain), and I have tried using the uniform approach, but the display effect is not ideal.

![image](https://github.com/molstar/molstar/assets/44961008/56a55550-042b-411b-bae1-1285f30fb9e2)

**Comment by arose** [comment]
Yes, you can color the carbon by a number of themes

![image](https://github.com/molstar/molstar/assets/272250/e938a722-90bc-4276-a2af-904da8caf477)

**Comment by ashipiling** [comment]
![image](https://github.com/molstar/molstar/assets/44961008/f34b585a-1335-4cb7-9129-5133bd90cb6e)
Thanks, I have tried the "Uniform" approach, but I couldn't change the color of carbon atoms individually. I was successful in changing the color using the element symbol method (as shown in the image above).
Furthermore, I would like to know how to achieve this using code.

**Comment by ashipiling** [comment]
I tried to write it like this, but failed. Can you provide some examples? Thank you.

{
            type: 'ball-and-stick',
            colorTheme: { name: 'element-symbol', params: { carbonColor: { name: 'uniform' }, colors: ColorMap({'C': ColorNames['red']}) } },
}
