### ISSUE TITLE
why the glycan structure display is not correct?

### ISSUE THREAD

**Issue by sakyw123** [molstar/molstar#958]
Hi,

I used MOE to create my model for an ACE2Fc molecule. I exported the *.moe file into *.pdb file and open it using mol*. The glycan display is like this.

![image](https://github.com/molstar/molstar/assets/43593555/4573da26-8a94-4d25-a519-50ed8987cfd0)

In MOE display window, everything looks nice and correct. May I have a hint about how to fix this issue? Thanks in advance!

Bests,

 from Lingyu

**Comment by dsehnal** [comment]
Usually, ligands would be annotated as a different chain (at the very least in label_asym_id in mmCIF). Doing the the same thing for the PDB file should resolve this. 

Also hard to know the exact reason without seeing the actual PDB file.

**Comment by sakyw123** [comment]
Hi Sehnal: Here I attached the PDB file. Thanks for the prompt reply. I am still trying to solve this issue.
[231020-intactACE2Fc_MOEminimized_0claish_9cisAmide_final.zip](https://github.com/molstar/molstar/files/13052037/231020-intactACE2Fc_MOEminimized_0claish_9cisAmide_final.zip)

**Comment by arose** [comment]
Hi @sakyw123,

The PDB file has duplicate chain names and residue numbers. This is non-standard for PDB files. It causes issues in Mol* when interpreting the CONECT records, which is something we can't fix.

You have two options. a) remove the CONECT records from your PDB file and rely on Mol*'s automatic bonding. b) ensure your PDB files uses unique chain names/residue numbers.

**Comment by sakyw123** [comment]
> Hi @sakyw123,
> 
> The PDB file has duplicate chain names and residue numbers. This is non-standard for PDB files. It causes issues in Mol* when interpreting the CONECT records, which is something we can't fix.
> 
> You have two options. a) remove the CONECT records from your PDB file and rely on Mol*'s automatic bonding. b) ensure your PDB files uses unique chain names/residue numbers.

Hi, @arose :

I got the idea. Yes, it seems that the MOE exportation function is not adequately functioning. It is an issue related to MOE instead of Mol*.

Thank you for offering me the options, I will try them out.

Bests,

from Lingyu
