### ISSUE TITLE
orientAxes issue when used inside a program

### ISSUE THREAD

**Issue by qpxu007** [molstar/molstar#960]
I am trying to create a static image using the headless image-renderer script, the default code works fine, but if I added the following code:

    await plugin.managers.camera.orientAxes();

I got a blank image complaining that "Skipping PCA, no atoms".  I got the same results if I passed the selection using 

const data = plugin.managers.structure.hierarchy.current.structures[0]?.cell.obj?.data;
await plugin.managers.camera.orientAxes(data as any);

what the correct  doing this?

Thanks.

**Comment by dsehnal** [comment]
- `orientAxes` takes a list of structures as the argument, not a single once. So doing `[data]` should work
- Specifying the 2nd argument as 0 should apply the transform immediately: `orientAxes([data], 0)`
- You can look at the code for the `image-renderer` to render images in headless mode, should work inside browser too: https://github.com/molstar/molstar/blob/492494033f1b117cc2da02f577b747fc1ba1cc03/src/examples/image-renderer/index.ts

**Comment by qpxu007** [comment]
David,

Thanks. 

I tried insert one of these statements before saving image in the image-renderer example (right after  line 74:   await update.commit();): 

await plugin.managers.camera.orientAxes(undefined, 0);
or
await PluginCommands.Camera.OrientAxes(plugin)

in both cases the output image is blank. I believe the pca rotation calculation was performed (I can print the orientation matrix which is not unity).

It could be related to the weird firefox behavior of requiring an extra mouse click before the mol shows up if the above function is called.

**Comment by qpxu007** [comment]
I sort of fixed the issue/behavior with the following code:

        this.plugin.managers.camera.orientAxes(undefined, 0);
        await delay(500); // wait a bit
        this.plugin.canvas3d?.requestCameraReset();

is there any better option?

**Comment by dsehnal** [comment]
Instead of the delay, maybe you try `plugin.canvas3d?.commit(true)`?

I am pretty sure @midlik used the PCA orientation in an headless renderer app he wrote. @midlik can you help here?

**Comment by qpxu007** [comment]
Indeed, 
    plugin.managers.camera.orientAxes(undefined, 0);
    plugin.canvas3d?.commit(true);
    plugin.canvas3d?.requestCameraReset();

have fixed the issue in interactive/headless versions.

Thanks!

**Comment by dsehnal** [comment]
The last `plugin.canvas3d?.requestCameraReset();` should be reduntant and the commit should be enough. The `orientAxes` already does the reset.

**Comment by midlik** [comment]
Hi, 
if you're using `HeadlessPluginContext.saveImage` (or `getImage*`) in your headless version, it already contains `plugin.canvas3d?.commit(true)`, so you shouldn't need to call it explicitly. But in browser version, it's probably necessary.

Maybe unrelated, but I was also initializing `HeadlessPluginContext` with `manualReset: true` (see here: https://github.com/PDBeurope/pdb-images/blob/0354b62f42f14d4c255b2946ce978ed3884a9c8f/src/main.ts#L142). This avoids any automatic camera reset (e.g. when a structure is loaded). Might be helpful in headless mode (but probably inappropriate in browser).

Anyway, seems that you've already solved it :D

**Comment by midlik** [comment]
> The last `plugin.canvas3d?.requestCameraReset();` should be reduntant and the commit should be enough. The `orientAxes` already does the reset.

`requestCameraReset` is necessary here because `orientAxes` overrides the auto-zoom (i.e. the camera will be rotated correctly but will still be focused on [0,0,0]). `requestCameraReset` then requests auto-zoom to fix this.

Another solution is this:
```
this.plugin.canvas3d?.commit(true);
this.plugin.managers.camera.orientAxes(undefined, 0);
this.plugin.canvas3d?.commit(true);
```
(allows the auto-zoom to take effect before applying rotation)

**Comment by qpxu007** [comment]
The double commits work. Otherwise, the last statement is needed in both cases in order for the examples to work properly. 

Thanks both!
