### ISSUE TITLE
Is it possible to build the docking viewer from the npm package?

### ISSUE THREAD

**Issue by htaldo** [molstar/molstar#961]
Hi! First things first, thanks for this great piece of software! I'm currently finding my way through it, and I'm getting started with JS too, so I apologize if this question is too basic.
I read in [Issue #605 ](https://github.com/molstar/molstar/issues/605) I could clone the whole repo and build it so I could use the docking viewer, but having installed Mol* with the NPM package, I was wondering if it is possible to build it from 'node_modules/molstar/', since I noticed docking-viewer is located under 'lib/apps/', but not in 'build/', like the mainline viewer. If so, how would I go about it? 
Thanks in advance!

**Comment by dsehnal** [comment]
You should be able to do `import { DockingViewer } from 'molstar/lib/apps/docking-viewer'` and then call `DockingViewer.create` in your app.

**Comment by htaldo** [comment]
Thanks for the prompt response! I'm still trying to make it work, but I'll let you know if something pops up (I'm still learning basic stuff like bundlers and npm)

**Comment by htaldo** [comment]
Thank you! I finally got it to work, not sure if I did it the intended way, though:
- Install mol* in the root of the project (I'm working with Django)
- Create and import the bundle with the app in the HTML template
- Install sass as dependency
- Install loaders and add them to webpack.config.js `npm install -D html-loader css-loader sass-loader`
- Paste molstar.js and molstar.css to apps/docking-viewer
- Change `require('mol-plugin-ui/skin/light.scss');` to `require('../../mol-plugin-ui/skin/light.scss');` in docking-viewer/index.js
