### ISSUE TITLE
Display Incompleteness with pdb file in Molstar

### ISSUE THREAD

**Issue by yooki0328** [molstar/molstar#962]
Hello,

I hope this message finds you well. I am currently using Molstar and encountered an issue while trying to display the pdb file 6ky5. The problem I noticed is that the display is incomplete( chain A). However, when I remove the excess information from the pdb file, it displays correctly(chain A and chain B). I would like to provide a comparison between the two scenarios and kindly request your suggestions after reviewing them.

Thank you in advance for your assistance.
<img width="1118" alt="image" src="https://github.com/molstar/molstar/assets/17794392/643bacc4-a2c2-4b89-a51f-4b28a87c954d">
<img width="1135" alt="image" src="https://github.com/molstar/molstar/assets/17794392/de208158-ede5-4946-8cce-4fcd1f551c23">

**Comment by dsehnal** [comment]
By default, Mol* displays assemblies, not the asymetric units stored in the file. The two copies are built based on information in `REMARK 350` in the PDB file.
