### ISSUE TITLE
Any suggestions regarding representations presets performance issue

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#963]
Hi all,

I've written a custom representation preset that creates multiple components and applies different representations to them. I'm facing a performance issue when dealing with huge structures that has over 20 chains, mainly [this one](https://www.rcsb.org/structure/7cgo) and [this](https://www.rcsb.org/structure/5mq0) as an example.

Are there any alternative approaches to create those components other than in the preset function? Any hint is appreciated.
I'm thinking of creating the main components in the preset and create others using another approach...

**Comment by Marwa-Da** [comment]
Thank you! I'll check the mentioned extension and review my approach.

**Comment by Marwa-Da** [comment]
@dsehnal Really sorry for bothering you! It's ok if you don't have time to dig deeper in this issue.

> These structures load immediately with the default preset and in general we are able to create scenes with tens or even hundreds of structures representing billions of atoms (e.g. see the cellpack extension).

The preset of that extension doesn't create any component other than the main component and one representation. I also checked other files that create a preset but all don't create as much components as I do.

> It seems like the issue is in the way you are creating your components.

For each chain, I create individual components for various segments of the chain and then apply multiple representations to each of these components. I create the components using either `tryCreateComponentFromSelection` or [this](https://github.com/molstar/molstar/issues/944#issuecomment-1774065994)

**Comment by dsehnal** [comment]
Well, the question is if you really need a separate component for each chain. The components system was never really meant to be used like this.

I don't know what your exact application is so it's hard to help you, but in general:

- you might be able to create a custom coloring theme to apply individual coloring for multiple chains at once
- can try to merge the components together and create the custom representation you are talking about for multiple chains at once (this should work together with the theming support)
- if the above still fails, you can create a custom structure representation that builds the geometry you need for multiple chains at the same time. There is an extension that does something like this for inspiration (dnatco).

**Comment by Marwa-Da** [comment]
Thank you for the quick reply!
Creating detailed and small components is to have more control over the structure, so it becomes easier to change the color/hide/show of a specific part of a chain without the burden of creating it manually. That is the main goal.
Isn't that what the components is created for? It would be great if you guided me towards the right direction/goal of them.

**Comment by dsehnal** [comment]
- You can change colors easily as params to a single custom color theme or there is also the overpaint functionality for that.
- As for hiding parts of the structure, the overpaint can be used to set max transparency on a selection to achieve that (tho as I tested this, there seems to be a bug now, but it should allow to hide the residue).

![image](https://github.com/molstar/molstar/assets/21145776/651f2bcf-1fe1-447d-a326-ad69a98ef8b6)

> Isn't that what the components is created for?

The idea was to be able to create different representations for polymer, lingand, etc. and not having a single component for a chain for structures with large number of chains.

**Comment by arose** [comment]
You may try wrapping creating all the components in a single transaction

```
plugin.dataTransaction(async () => { ... });
```

I find looking at a performance profile in Chrome can help a lot to find bottlenecks.

> As for hiding parts of the structure, the overpaint can be used to set max transparency on a selection to achieve that (tho as I tested this, there seems to be a bug now, but it should allow to hide the residue).

Set it to 1.0 to hide (the transparency theme parameter is inverted compared to the opacity representation parameter).

**Comment by Marwa-Da** [comment]
> * You can change colors easily as params to a single custom color theme or there is also the overpaint functionality for that.
> 
>  * As for hiding parts of the structure, the overpaint can be used to set max transparency on a selection to achieve that (tho as I tested this, there seems to be a bug now, but it should allow to hide the residue).
> 

Sounds good for both the color and visibility. I'm using the toggleVisibility of a state node extensively.
> The idea was to be able to create different representations for polymer, lingand, etc. and not having a single component for a chain for structures with large number of chains.

Understood, thank you! So if the requirement is to have  various representations for each "chain", what could be a good alternative to control them, instead of creating component for each chain and apply the different representations to each of them?

P.S. I believe I've grasped your point regarding the components system, and I hope I'm asking about something that wasn't already covered earlier. Thank you for your patience!

**Comment by Marwa-Da** [comment]
> You may try wrapping creating all the components in a single transaction
> 
> ```
> plugin.dataTransaction(async () => { ... });
> ```

Thank you for the suggestion! I tried it and nothing changed.

**Comment by dsehnal** [comment]
Wrapping it in a single transaction won't change anything about the performance.

**Comment by Marwa-Da** [comment]
> Wrapping it in a single transaction won't change anything about the performance.

Unfortunately it didn't! :(

**Comment by dsehnal** [comment]
You are just gonna have to change how you think about the state of the application and hiding/coloring things on demand and separate the information of representation/components from what residues should be hidden and how they should be colored.

**Comment by Marwa-Da** [comment]
> You are just gonna have to change how you think about the state of the application and hiding/coloring things on demand and separate the information of representation/components from what residues should be hidden and how they should be colored.

Exactly, I'm considering implementing the option to generate the surface representation on-demand, particularly because the visual computation is time-intensive.
