### ISSUE TITLE
camera.project is not working properly starting from 3.34.0

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#967]
camera.projecionView is different in 3.32 and 3.34，The difference in projectionView causes the project method to be calculated incorrectly，this.viewport is the same in different versions
very thanks~

### 3.32(good)
![image](https://github.com/molstar/molstar/assets/1294316/404ab0fd-edce-4916-98db-34a7ec89b2a4)

### 3.33(good)
![image](https://github.com/molstar/molstar/assets/1294316/8b82d808-e604-42d9-9eb3-059a8d46b52e)

### 3.34(bad)
![image](https://github.com/molstar/molstar/assets/1294316/fb19bd5d-e463-4432-a2a8-d6d2cd264241)

### 3.41(bad)
![image](https://github.com/molstar/molstar/assets/1294316/d26c943c-acd9-4b97-9595-8f5c1f8fc3bc)

**Comment by arose** [comment]
I think this is because of `- Remove `camera.far` doubling workaround`. Admittedly it is different then before, but what makes you think it is wrong?

**Comment by arose** [comment]
In 3.33 there was this fix https://github.com/molstar/molstar/commit/ad116df73be7dd91679b68a1782c2fcbdbc2679d which may be breaking for you

**Comment by luckyxutao** [comment]
When converting the same 3d coordinates to screen coordinates, the x coordinate is correct but the y coordinate is incorrect。

The correct screen coordinates are x:455,y:395, and the incorrect ones are x:455,y:202

### bad:(3.35.8)
![截屏2023-10-30 14 06 51](https://github.com/molstar/molstar/assets/1294316/8038688a-d5e3-4c38-980d-df0f765e5da2)

### good(3.32)
![截屏2023-10-30 14 05 05](https://github.com/molstar/molstar/assets/1294316/dfd85a8d-1b3f-4684-be1f-8f8f95c870bf)


```js
    console.log('atomId10',this.toCanvasCoords(2.020, -1.099, -0.905))
    toCanvasCoords(x, y, z) {
        const { camera } = this;
        const standardVec = Vec3();
        camera.project(standardVec, Vec3.create(x, y, z));
        const aspectRatio = window.devicePixelRatio;
        return { x: standardVec[0] / aspectRatio, y: standardVec[1] / aspectRatio };
    }

```

**Comment by luckyxutao** [comment]
Whether it can be used mainly depends on the following two points:
1. camera.ts
<img width="1019" alt="image" src="https://github.com/molstar/molstar/assets/1294316/36d749bb-dd70-4ef7-810e-2ec4e6992bca">

2. mol-canvas3d/camera/util.ts

<img width="1246" alt="image" src="https://github.com/molstar/molstar/assets/1294316/6c88dfcb-06c4-4980-8b50-9beda876b6f8">

**Comment by arose** [comment]
yes, that is because of

> In 3.33 there was this fix https://github.com/molstar/molstar/commit/ad116df73be7dd91679b68a1782c2fcbdbc2679d which may be breaking for you

you need to do the y-flipping yourself

**Comment by luckyxutao** [comment]
Sorry, I don’t understand how to calculate coordinates through y-flipping
Except camera.project, I don’t know how to convert 3D to 2D screen coordinates. Will subsequent versions of molstar be unable to use camera.project? very Thanks

**Comment by arose** [comment]
you do camera project to get the 2d window coordinates and you rightly observed that in the new versions the y coordinate is not "correct". To "fix" is you need to do `height - y` where `height` is the height of the height of your canvas. This is what i meant by "y-flipping".

**Comment by luckyxutao** [comment]
Thank you very much for your answer
