### ISSUE TITLE
How to extract image from molstar without render it into UI?

### ISSUE THREAD

**Issue by manoharreddyaleti** [molstar/molstar#969]
I have pdb file and I need protein view of it. I need to extract image from molstar and I will insert that image into PPT programmatically. So I don't want to visualize protein in UI but I want to extract image of protein view. Could you please help me on this?

**Comment by qpxu007** [comment]
I have looked at this lately. There are a few ways, first you can modify one of the examples: image-renderer

first clone and build the molstar project, then you can run from the root of the project, e.g.

node lib/commonjs/examples/image-renderer 2che .

you could then modify the typescript for the example to achieve what you want. 

also you also can look at molrender  or pdbe-images (https://github.com/PDBeurope/pdb-images) that are based on molstar
