### ISSUE TITLE
Always full screen in Vue3.

### ISSUE THREAD

**Issue by EXGDT** [molstar/molstar#974]
```
<script setup lang="ts">
import { createPluginUI } from 'molstar/lib/mol-plugin-ui'
import { DefaultPluginUISpec } from 'molstar/lib/mol-plugin-ui/spec'
import { PluginSpec } from 'molstar/lib/mol-plugin/spec'
import { PluginConfig } from 'molstar/lib/mol-plugin/config'
import { ref, onMounted } from 'vue'
import 'molstar/lib/mol-plugin-ui/skin/light.scss'

const molstarParent = ref<HTMLElement | null>(null)

onMounted(async () => {
  if (molstarParent.value !== null) {

    const MySpec: PluginSpec = {
      ...DefaultPluginUISpec(),
      config: [
        [PluginConfig.VolumeStreaming.Enabled, false],
        [PluginConfig.Viewport.ShowExpand, true],
        [PluginConfig.Viewport.ShowControls, true],
        [PluginConfig.Viewport.ShowSettings, false],
        [PluginConfig.Viewport.ShowAnimation, false],
      ]
    }

    const molstar = await createPluginUI(molstarParent.value, MySpec)

    const data = await molstar.builders.data.download(
      { url: 'https://files.rcsb.org/download/3PTB.pdb'},
      { state: { isGhost: true } }
    )

    const trajectory = await molstar.builders.structure.parseTrajectory(data, 'pdb')
    await molstar.builders.structure.hierarchy.applyPreset(trajectory, 'default')
  }
})
</script>

<template>
  <div ref="molstarParent" style="height: 640px; width: 480px"></div>
</template>
```

Here is my code, just a little changes based on [https://molstar.org/docs/plugin/](url): #To use the plugin (with the React UI) inside another React app.

I can see that `<div ref="molstarParent" style="height: 640px; width: 480px"></div>`  is normal, but its child div don't have any style.
![image](https://github.com/molstar/molstar/assets/30069282/b13312a5-7a30-48c2-82d2-401b848f4b76)
![image](https://github.com/molstar/molstar/assets/30069282/30fc9c61-eaf4-4b5e-bd9f-992e91416f6e)

If write style in F12 tools, the <msp-plugin> can obtain a right size and all the page can be normal.
So what is the right way to set the molstar size as plugin if use Vue3?

**Comment by Cauwth** [comment]
![image](https://github.com/molstar/molstar/assets/143175589/3952b63f-5b9a-4a30-867f-c28fd4e58793)
try this

**Comment by dsehnal** [comment]
The parent element needs to have `position: relative` : `<div ref="molstarParent" style="height: 640px; width: 480px; position: relative"></div>

**Comment by EXGDT** [comment]
> The parent element needs to have `position: relative` : `<div ref="molstarParent" style="height: 640px; width: 480px; position: relative"></div>`

Yes, you are write, whether the parent div has the `position: relative` attribute is very important for Vue3. (Documents show that what React returns don't need relative~)

And another little question, do you know how to close the left panel、log、sequence, etc. ? I didn't find the source code about on/off these panel~ Just show them after clicking expand button is a better effect~

![image](https://github.com/molstar/molstar/assets/30069282/8b3d99c6-e503-49ff-a4b0-c6ad1a40c78c)

**Comment by EXGDT** [comment]
> ![image](https://user-images.githubusercontent.com/143175589/281946265-3952b63f-5b9a-4a30-867f-c28fd4e58793.png) try this

I tried a similar operation and it's worked, certainly, `<div style="position: relative">` is the most important way.

**Comment by EXGDT** [comment]
Problem solved
