### ISSUE TITLE
The default options for downloading structures representation

### ISSUE THREAD

**Issue by Cauwth** [molstar/molstar#978]
In the example on Mol* Viewer, the default value for the “representation” option when downloading a structure is “automatic (w/annotation)”.
![image](https://github.com/molstar/molstar/assets/143175589/a182a038-cbf7-4cd6-971e-e44bbbd594e5)
However, in the case of the Vue 3 code I’m using, the default value is “empty”. This results in the structure not automatically updating after downloading. Could you please advise which API I should use to adjust this and enable automatic updates in the display? Thank you very much! 🙌
![image](https://github.com/molstar/molstar/assets/143175589/3b49f9b9-49a7-4330-b055-3bc74cb78631)

**Comment by arose** [comment]
The preset is registered here

https://github.com/molstar/molstar/blob/e6a4122d1c5fa2655f417847167a1b4e197076a2/src/apps/viewer/app.ts#L208-L214

and defined as default here

https://github.com/molstar/molstar/blob/e6a4122d1c5fa2655f417847167a1b4e197076a2/src/apps/viewer/app.ts#L195
