### ISSUE TITLE
Get original cube file from loaded structure

### ISSUE THREAD

**Issue by ptourlas** [molstar/molstar#980]
Greetings!
Is there a way (or a hint I can work with) for getting the original cube file from a loaded volume?
I have checked how saving session state works, but `this.plugin.managers.asset.assets` in
https://github.com/molstar/molstar/blob/78874c00242e41c9a7333fe76e7f7b09af04f9f0/src/mol-plugin-state/manager/snapshots.ts#L231 
is empty in my case, maybe because I load the volume from a string that I pass directly.

Thanks

**Comment by arose** [comment]
if you load it from a string it should be a param of the transform you use to load it

**Comment by ptourlas** [comment]
thank you!
