### ISSUE TITLE
Representation as ball and stick with custom carbon color

### ISSUE THREAD

**Issue by AlessioDelConte** [molstar/molstar#989]
Hi,
I'm writing a piece of code that given a list of residues as chain name and residue index it needs to change their representation as ball and sticks and I want to color the atoms with a custom atom color. Is this possible? As you can see below I'm already passing a color to the colorParams, but it does not seem to affect it.

###
    protected async representAsBallAndStick(accs: string[], structure: any) {
        const query = queryFromResidues(accs);
        let component = await this.plugin.builders.structure.tryCreateComponentFromExpression(structure, query, 'selection_neighbors');

        await this.plugin.builders.structure.representation.addRepresentation(component!, {
           type : 'ball-and-stick',
           color : 'element-symbol',
           colorParams : {
               carbonColor : Color(0xff00ff),
          }
       });
    }
###

Also, would it be possible to take the color from the Overpaint.BundleLayer that was done on the structure before this?
Thanks!

**Comment by dsehnal** [comment]
Sorry for the late response, but do you still need help with this?

**Comment by AlessioDelConte** [comment]
Hi, yes I didn't manage to do it, if you have a piece of code that can do this it I will be happy to implement it into my code.

Thanks
Alessio

**Comment by Marwa-Da** [comment]
The carbon color should be like this:
`colorParams: { carbonColor: { name: 'uniform', params: {value: Color(0xff00ff)} } }`
