### ISSUE TITLE
Change the selection color of 3D structure

### ISSUE THREAD

**Issue by Marwa-Da** [molstar/molstar#993]
Hi all,

What is selectColor property supposed to change? How to turn the full green selection color into blue? Am I missing something?
![image](https://github.com/molstar/molstar/assets/11466297/7d304ecc-9c8b-4876-ae92-37f8b851fa27)

**Comment by dsehnal** [comment]
This looks like a bug where he color change isn't applied to the outline color.

**Comment by Marwa-Da** [comment]
Perfect, thank you!
