### ISSUE TITLE
Add Sass as peerDependency

### ISSUE THREAD

**Issue by Manubi** [molstar/molstar#997]
![CleanShot 2023-12-05 at 13 11 45@2x](https://github.com/molstar/molstar/assets/20935138/fd380dda-11d9-499e-b093-10662fa0b439)

**Comment by dsehnal** [comment]
For now, could you just add `sass` to your project's package JSON?

**Comment by Manubi** [comment]
> For now, could you just add `sass` to your project's package JSON?

Yeah i've added it and it works fine.
